Enable nullability in ObjectCollection
dotnet/winforms pull request #10017
Opened 2023-09-29 15:23 UTC by gpetrou

## Proposed changes

- Enable nullability in ObjectCollection.

2023-10-04 21:56 UTC, dreddy-work requested changes

2023-10-04 21:56 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollection.cs
> +                _comparer ??= new ItemComparer(_owner);
nit: this can be moved to expressional body.

2023-10-04 21:56 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollection.cs
> +                _items ??= new List<object>();
same here.

2023-10-04 21:56 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollection.cs
> +        public void Insert(int index, object? item)
why `item `nullable? We are throwing if null.

2023-10-04 21:56 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollection.cs
> +            int index = InnerArray.IndexOf(value!);
same here. why nullable?

2023-10-05 04:28 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollection.cs
> +        public void Insert(int index, object? item)
This is an interface implementation where `object` is nullable.

2023-10-05 04:28 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollection.cs
> +            int index = InnerArray.IndexOf(value!);
Same reason here.

2023-10-05 17:10 UTC, dreddy-work approved these changes

2023-10-05 17:15 UTC, merged