Vb code cleanup
dotnet/winforms pull request #10117
Opened 2023-10-14 10:37 UTC by paul1956

Fixes #

## Proposed changes
Clean up Visual Basic Code to eliminate suggestions, fixes 85 issues flagged by Visual Studio

## Customer Impact
None, if targets developers who get 85 issues that clutter up the Error List

## Regression? 
 No, it more about making code match .editorConfig included with project. Alternativity, .editorConfig could be changed to match the Visual Basic Code but that will cause other cosmetic issues, where other code does not match newer .editorConfig.

## Risk
Very low, mostly renaming of local variables, fix spelling errors in comments and adding missing "Public" on public functions, Biggert change is If Statement to if Expression.

## Test methodology
Code completes, existing tests pass, changes are mostly cosmetic.

This is on in 1 Project written in old Visual Basic

2023-10-16 19:42 UTC, lonitra reviewed
LGTM 👍 but will also let @KlausLoeffelmann have a look as well

2023-10-17 01:41 UTC, KlausLoeffelmann requested changes
Hey @paul1956,

I browsed about half through it, but I have a few things generically, which I would either suggest addressing or have a conversation about. Can you take a 2nd look?

Thanks so much for doing this - a few of those things were bothering me also for a long time!

2023-10-17 02:26 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/AssemblyInfo.vb
> +                    _description = If(Attribute Is Nothing,
@KlausLoeffelmann Because whoever set up .editorConfig for selected prefer If Expressions. I agree it is not as clear in VB as C# but changing EditorConfig to prefer If Statements might cause bigger changes. It's possible for VB and C# to have different preference for the two languages but for now they are the same.

2023-10-17 02:39 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Audio.vb
> +                    Throw New ComponentModel.InvalidEnumArgumentException(paramName, value, GetType(AudioPlayMode))
It's not an implicit conversion VB knows AudioPlayMode is an integer because its private and CInt or DIrectCast causes a suggestion.

2023-10-17 02:41 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Audio.vb
> +
The auto formatting is doing this on Save. I could revert using Notepad.

2023-10-17 02:46 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/ComputerInfo.vb
> +        Public Sub New()
Yes, if I changed to the wrong accessibility, you get warning below

Warning	RS0017	Symbol 'Microsoft.VisualBasic.Devices.ComputerInfo.New() -> Void' is part of the declared API, but is either not public or could not be found.

2023-10-17 02:47 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
> +
They are added by automatic former on save.

2023-10-17 02:48 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
> +                Throw GetArgumentNullException("address")
Leaving it cause suggestion.

2023-10-17 02:53 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
> +            Return Reply.Status = NetInfoAlias.IPStatus.Success
I reverted but this should also be set in  editorConfig

2023-10-17 03:04 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
> +        Public Sub DownloadFile(address As Uri,
Same issue its defined as Public in PublicAPI.Shipped as Public

2023-10-17 03:08 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
> +                        _pingBuffer(i) = Convert.ToByte(Asc("a"c) + i Mod 23, Globalization.CultureInfo.InvariantCulture)
I thought the same thing and VB Optimizes CByte(Asc since VB 16.0. I will change and test should pick up any issues.

2023-10-17 03:22 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
> +            Return If(userName.Length = 0 And password.Length = 0,
Reverted but again should be changed on editorConfig under VB and specify C# preferences under C# instead of globally.

# VB files
[*.vb]
dotnet_style_prefer_conditional_expression_over_assignment = false:none
dotnet_style_prefer_conditional_expression_over_return = false:none

2023-10-17 03:24 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
> +
This is how I typically do it. Let me know if you want me to change

2023-10-17 03:24 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/Hosting.vb
> +
The whole extra line thing is cause by Saving VB Code and autoformatting.

2023-10-17 03:26 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeTypes.vb
> +
@KlausLoeffelmann If you are asking about all the blank lines all I did was ^K^D Save and the VB formatter does it based on .editorConfig settings.

2023-10-17 07:28 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeTypes.vb
> +
You don't have to introduce anything, there is already a VB section in the top one in WinForms but there is very little in it. By default, it uses the common stuff in this section which as you correctly noticed is not optimal for VB.

```
# C# and VB files
[*.{cs,vb}]
```

C# then has its own section starting with
```
# C# files
[*.cs]
```

Lastly VB has a dedicated section starting with
```
[*.vb]
```
But it only has 1 line
```
# Modifier preferences
visual_basic_preferred_modifier_order = Partial,Default,Private,Protected,Public,Friend,NotOverridable,Overridable,MustOverride,Overloads,Overrides,MustInherit,NotInheritable,Static,Shared,Shadows,ReadOnly,WriteOnly,Dim,Const,WithEvents,Widening,Narrowing,Custom,Async:suggestion
```
BTW no idea why there is more than one .editorConfig in WinForms repo but there are dozens of them, and I have no idea which is causing the suggestions because editing the TOP one seems to do nothing

2023-10-18 00:09 UTC, KlausLoeffelmann commented
I would be surprised, if the Roslyn team doesn't have a dedicated .editorConfig for VB. Couldn't we steal that from them? I cannot believe that the current setting we're using should be some sort of standard for VB. 

@AlekseyTs: Asking for a friend! 😸

2023-10-18 00:26 UTC, AlekseyTs commented
Sorry. I prefer to stay oblivious of the .editorConfig stuff. Feel free to check what we have in the Roslyn repo. I personally never reformat entire file, and I would revert spacing changes if VS were to make them without me explicitly looking to make the changes. Regardless of what .editorConfig has.

2023-10-18 02:11 UTC, paul1956 commented
> I would be surprised, if the Roslyn team doesn't have a dedicated .editorConfig for VB. Couldn't we steal that from them? I cannot believe that the current setting we're using should be some sort of standard for VB.
> 
> @AlekseyTs: Asking for a friend! 😸

Roslyn has 1 editorConfig for the solution (VB and C#), a few ancillary repos have their own which inherit from the root one.

Spacing is one issue where blank lines after classes, punctions is currently specified and saving applies the formatting. it's possible there is a VS Setting to prevent this the auto formating but I haven't found it.

A separate issue is preferring If Expressions for C# and If Statements for VB.  This is controlled by .editorConfig and right now they share the same settings to prefer If Expressions.

2023-10-18 03:41 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/AssemblyInfo.vb
> +                    _description = If(Attribute Is Nothing,
@KlausLoeffelmann 
I believe I have undone the changes you didn't like and updated editorConfig to separate VB and C# for the three places that were causing this.

VB Now prefers If Statements to Coalesce, If Statements to If Expressions and If Statements to Return Expressions but left C# unchanged. 

The current WinForms Repo is missing a lot of standard options and if editorConfig is edited in Visual Studio through the UI they will be automatically added not necessarily with the desired values. If this needs to be fixed, it should be a separate PR as it probably affects C#.

2023-10-18 23:41 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/AssemblyInfo.vb
> +                    _description = If(Attribute Is Nothing,
> > and if editorConfig is edited in Visual Studio through the UI they will be automatically added not necessarily with the desired values.
> 
> Couldn't we just have the missing entries being filled in and then edited (only for VB of course) in the way, we want it? Since VB seems to be behaving in other areas fine, I would figure that the default behavior of the VB Editor _without_ .editorConfig and the default values, if VS fills them in, should be about the same? Or is that a wrong assumption?

@KlausLoeffelmann that should be a correct assumption, but I would not want to make a change that impacts formatting/issues in C#. Right now, the Cleanup PR has a modified editorConfig that gives you VB without suggestions and C# unchanged. There may be additional lines you should like to add but they only effect C#. You can see them by opening editorConfig by double clicking and then saving, then manually review the new settings. I don't know for example how you want collection initialization handled in C#.

2023-10-19 00:53 UTC, paul1956 commented
@KlausLoeffelmann I have manually removed all the extra lines that VS wants to add, the biggest manual change is separating Imports but root type. It that is a setting I don't know how to turn it off.

I have added ExceptionUtils and other prefixes like it back. The code was not consistent in how/when it used ExceptionUtils directly vs in an Imports. I have made all uses follow below
```
Imports ExUtils = Microsoft.VisualBasic.CompilerServices.ExceptionUtils
```

2023-10-24 09:53 UTC, paul1956 commented
@KlausLoeffelmann  Ping
This is all cleaned up with updated and separated editorConfig and updated VB project file with options specified. I think I removed all the extra blank lines, but any editing in VS will bring them back. Someone that knows about controlling the blank lines should review and recommend a fix that is more automatic and not requiring removing the blanks using Notepad. This should be reviewed and merged before the Fix to remove WebClient which has all the same formatting issues.

2023-10-25 00:12 UTC, KlausLoeffelmann commented
I need to take a bit more time, which I don't have right now.
I'll dial back to this in a bit. Sorry for the delay!

2023-10-26 00:10 UTC, paul1956 commented
> I need to take a bit more time, which I don't have right now. I'll dial back to this in a bit. Sorry for the delay!

@KlausLoeffelmann no issue, I continue to fix formatting differences between different files. I will continue to keep this PR up to date with Master.

2023-10-26 06:48 UTC, KlausLoeffelmann commented
When you get the chance, can you also start using the name "main" for the equivalence of our main branch to avoid confusion? Thx!

2023-11-16 18:13 UTC, lonitra commented
@KlausLoeffelmann gentle ping to keep this on your radar to take this to completion

2023-11-16 18:24 UTC, KlausLoeffelmann commented
Yes, Ma'am. 
As soon as I can get to it! Give me a bit more time - thanks for pinging me!

2024-01-09 01:22 UTC, paul1956 commented
Ping, is there an ETA when someone might review this?

2024-03-18 00:45 UTC, closed without merging

2024-03-18 00:46 UTC, paul1956 commented
This is replace by other PR's and is unneccessary