Refactor `SnapLines` to use `IList` directly instead of casting to `ArrayList`
dotnet/winforms pull request #10279
Opened 2023-11-12 03:48 UTC by elachlan

Kind of related: #8140

Mostly trying to remove `ArrayList` usage through the code base. This code is using a typesafe cast to `ArrayList`, where it can just use IList directly.

We cannot convert to `List<T>` because we have a public API that uses `ArrayList` ParentControlDesigner.AddPaddingSnapLines:
https://github.com/dotnet/winforms/blob/cc1a96870bfb794efc2005b843f3908e422865fe/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs#L295-L319

Ultimately it would be great if the public API could be changed to `List<SnapLine>` to be more explicit.

2023-11-12 22:12 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs
Changes in this file seem only stylistic. I root for them, but don't look like they belong to this PR

2023-11-29 23:16 UTC, elachlan commented
I'll set aside some time and get the last changes sorted.

2023-11-30 09:05 UTC, elachlan commented
@JeremyKuhne I am not really following on how the `ListAdapter` helps here? `IList<T>` can't be implicitly converted to `IList`.

2023-11-30 09:44 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowPanelDesigner.cs
> -#nullable disable
I'm not sure annotating `FlowPanelDesigner` for NRT should be part of this PR.

2023-11-30 18:08 UTC, JeremyKuhne commented
> I am not really following on how the `ListAdapter` helps here? `IList<T>` can't be implicitly converted to `IList`.

@elachlan `ListAdapter` is for our own "casting" to `IList<T>`. We know we want only `T`, not `T?`, and not `object?`. If the data structure is `IList<T>` it just casts to it, otherwise it creates an adapter for the `IList` from the property. That way we can write consuming code as if it is always `IList<T>`.

2023-11-30 23:00 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowPanelDesigner.cs
> -#nullable disable
Are you sure? Its a very small change.

2023-11-30 23:01 UTC, elachlan commented
@JeremyKuhne I think it clicked. Let me know if this makes sense.

2023-12-01 11:48 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowPanelDesigner.cs
> -#nullable disable
I though the parent class wasn't annotated, but apparently it is, so in that light it's a small change (though the parent's parent isn't, which exposes us to incorrect assumptions)

2023-12-01 18:53 UTC, JeremyKuhne requested changes
Added some comments. Sorry about the delay, a bit busy currently.

2023-12-01 18:53 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/LabelDesigner.cs
> +            return (IList)snapLines;
This won't work if the adapter is in play. One could add `IList` to the adapter, but then everything would get the wrapper at that point. If they try to do the same thing again.

You can just not expose the internal and do the `ListAdapter` call in each usage and return the original `IList`. Another option is to create some internal interface that we could use as a general pattern to handle this sort of wrapping. Something like:

``` C#
internal interface IWrapper<T>
{
    T Unwrap();
}

internal ListAdapter<T> : IList<T>, IWrapper<IList>
{
    // ...
}

internal static AdapterHelpers
{
    internal IList Unwrap(this IList list) => list is IWrapper<IList> wrapper ? wrapper.Unwrap() : (IList)list;
    internal IList<T> Adapt(this IList list) => list is IList<T> ilist ? ilist : new ListWrapper(list);
}

// Example usage:

IList<SnapLine> snapLines = SnapLines.Adapt<SnapLine>();
// ...
return snapLines.Unwrap();
```

2023-12-06 00:11 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/LabelDesigner.cs
> +            return (IList)snapLines;
I think this results in having to use `List<SnapLine>` and not `IList<SnapLine>` so as to avoid `((IList)snapLines).Unwrap();`

```csharp
// Example usage:

List<SnapLine> snapLines = base.SnapLines.Adapt<SnapLine>();
// ...
return snapLines.Unwrap();
```

Or should I just do the explicit cast?

2024-01-04 00:24 UTC, JeremyKuhne commented
@elachlan this looks good outside of adding comments to the new types and making sure they are in individual files per guidelines.

2024-01-04 00:26 UTC, JeremyKuhne requested changes
Looks good, just get comments on the new types and move them into their own files.

2024-01-04 01:14 UTC, elachlan commented
@JeremyKuhne how is that?

2024-01-04 01:20 UTC, JeremyKuhne requested changes
Just one more nit

2024-01-04 01:20 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AdapterHelpers.cs
> +/// Helpers for adapting between generic and non-generic lists.
nit: indent

2024-01-04 01:37 UTC, JeremyKuhne approved these changes

2024-01-04 01:55 UTC, elachlan commented
Weird test failure I think is unrelated.

2024-01-04 03:06 UTC, merged