Refactor `WeakRefCollections` to Generics
dotnet/winforms pull request #10291
Opened 2023-11-14 00:03 UTC by elachlan

* Unify `WeakRefCollection`s into single implementation in Common and share between projects.
* Refactor to use Generics

2023-11-14 00:03 UTC, elachlan commented
CC: @JeremyKuhne @halgab

2023-11-14 03:02 UTC, JeremyKuhne requested changes
I started adding comments and realized how messy this is. A much better solution would be to replace it with the following:

``` C#
/// <summary>
///  Weak reference collection of <typeparamref name="T"/>.
/// </summary>
internal class WeakRefCollection<T>() where T : class
{
    private readonly List<WeakReference<T>> _list = new();
    private bool _scavenge;

    public T? this[int index]
    {
        get
        {
            _scavenge = !_list[index].TryGetTarget(out T? target);
            return target;
        }
        set => _list[index] = new(value.OrThrowIfNull());
    }

    public void ScavengeReferences()
    {
        for (int i = Count; i >= 0; i--)
        {
            if (!_list[i].TryGetTarget(out T? target))
            {
                _list.RemoveAt(i);
            }
        }

        _scavenge = false;
    }

    public void RemoveAt(int index) => _list.RemoveAt(index);

    public void Remove(T value)
    {
        int index = IndexOf(value);
        if (index != -1)
        {
            _list.RemoveAt(index);
        }
    }

    public int IndexOf(T value)
    {
        for (int i = 0; i < _list.Count; i++)
        {
            if (!_list[i].TryGetTarget(out T? target))
            {
                _scavenge = true;
            }
            else if (target == value)
            {
                return i;
            }
        }

        return -1;
    }

    public void Add(T value)
    {
        if (_scavenge)
        {
            ScavengeReferences();
        }

        _list.Add(new(value));
    }

    public int Count => _list.Count;
}
```

Depending on the amount of iterators it might be useful to write an enumerator for it as well that already filters out all of the collected values.

The System.Drawing usage can ultimately go away. It is only used to get call backs on the DeviceContext disposals. If someone is feeling up for a challenge they can kill the DeviceContext class in System.Drawing. I did the same for WinForms some time ago. https://github.com/dotnet/winforms/pull/3553 was the last of that change.

2023-11-14 03:33 UTC, elachlan commented
> The System.Drawing usage can ultimately go away. It is only used to get call backs on the DeviceContext disposals. If someone is feeling up for a challenge they can kill the DeviceContext class in System.Drawing. I did the same for WinForms some time ago. https://github.com/dotnet/winforms/pull/3553 was the last of that change.

Is the gist that we switch `DeviceContext` with `IDeviceContext`, then use the extension methods on that?

2023-11-14 08:21 UTC, elachlan commented
I think the old WeakRefCollection never `ScavengeReferences` unless `RefCheckThreshold` was hit. The `RefCheckThreshold` was never set, so the error case was never hit, because we never cleaned up the collected references.

If I step through the tests slowly in debug, they all pass. If step through fast, some fail.

If I change remove to this they all pass, because `ScavengeReferences` isn't being triggered by the `IndexOf` searching for the value.
```csharp
public void Remove(T value)
{
    for (int i = 0; i < _list.Count; i++)
    {
        if (_list[i].TryGetTarget(out T? target) && target == value)
        {
            _list.RemoveAt(i);
        }
    }
}
```

2023-11-14 18:52 UTC, JeremyKuhne commented
> If I step through the tests slowly in debug, they all pass. If step through fast, some fail.

@elachlan all you're getting is this assert, right?

``` C#
        Debug.Assert(t_cellCount <= ToolStripManager.ToolStrips.Count, "who is allocating an extra toolstrippanel cell?");
```

I don't think the assert is correct and should be removed.

Also, you should always iterate backwards [when removing items from a list](https://www.techiedelight.com/remove-elements-from-list-while-iterating-csharp).

2023-11-14 21:46 UTC, halgab commented on src/Common/src/WeakRefCollection.cs
> +                if (weakRef.TryGetTarget(out T? target) && target is not null)
```suggestion
                if (weakRef.TryGetTarget(out T? target))
```

2023-11-14 23:27 UTC, JeremyKuhne requested changes
Added a few more comments.

2023-11-14 23:27 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
> +    internal static void PruneToolStripList() => t_toolStripWeakArrayList?.ScavengeReferences();
You can probably get rid of the helper method and just do this directly.

2023-11-14 23:27 UTC, JeremyKuhne commented on src/Common/src/WeakRefCollection.cs
> +    public IEnumerator<T> GetEnumerator()
If you're adding this you should implement `IEnumerable<T>` and actually use it.

2023-11-14 23:46 UTC, JeremyKuhne commented on src/Common/src/WeakRefCollection.cs
> +    public IEnumerator<T> GetEnumerator()
That is, do `for .. each` on the collection where we're already filtering these out.

2023-11-15 00:47 UTC, elachlan commented on src/Common/src/WeakRefCollection.cs
> +    public IEnumerator<T> GetEnumerator()
There might be issues with using the for each, since `ToolStripManager` was triggering `ScavengeReferences` when it found deadrefs whilst looping.

To combat this, I changed the enumerator to set `_scavenge = true;` when it found a deadref, so `ScavengeReferences` is run at the next opportunity.

2023-11-15 18:27 UTC, JeremyKuhne requested changes
Minor nits

2023-11-15 18:27 UTC, JeremyKuhne commented on src/Common/src/WeakRefCollection.cs
> +                continue;
nit: better to `if ... else` here rather than `continue`

2023-11-15 18:27 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
> +        return target is not null && RevertMerge(target);
nit: `=>`

2023-11-15 18:27 UTC, JeremyKuhne commented on src/Common/src/WeakRefCollection.cs
> +    public IEnumerator<T> GetEnumerator()
It would be good to document where it does that as it isn't obvious looking at the code.

2023-12-06 22:33 UTC, elachlan commented
@JeremyKuhne I think I have covered everything here, can you take another quick look?

2024-01-04 00:29 UTC, JeremyKuhne requested changes
Just a couple nits. Looks good otherwise!

2024-01-04 00:29 UTC, JeremyKuhne commented on src/Common/src/WeakRefCollection.cs
> +    /// <summary>
Nit: needs blank line before comment.

2024-01-04 00:29 UTC, JeremyKuhne commented on src/Common/src/WeakRefCollection.cs
> +    /// Cleans up dead weak references.
nit: Indent the comment

2024-01-08 22:36 UTC, elachlan commented
@JeremyKuhne rebased to fix conflict. No other changes.

2024-01-09 01:15 UTC, JeremyKuhne approved these changes

2024-01-09 01:15 UTC, merged