Verify that the drop source target window is in-process
dotnet/winforms pull request #10319
Opened 2023-11-16 03:27 UTC by willibrandon

Fixes #8903 

## Proposed changes

- Fix the tracking of the last drop target window in DragLeaveTarget.
- Exclude the `GiveFeedbackEventArgs` `Effect` property from the check for if the drag image has been updated.
- Check if the target window is in-process and if not, prevent the drag image from being updated during `GiveFeeback`.
- Only notify the drag-image manager that the cursor has left the drop target if the window is in-process.

## Customer Impact

- Fixes a drag image flicker and artefact that occurs when updating the drag image during `GiveFeedback` from another process.

## Regression? 

- No.

## Risk

- 

## Screenshots 

### Before

### After

## Test methodology 

- Manual

## Test environment(s) 

- 9.0.100-alpha.1.23511.2

2023-11-16 03:47 UTC, willibrandon commented
@weltkante - Thoughts?

2023-11-16 19:16 UTC, JeremyKuhne requested changes
Added a few minor comments.

2023-11-16 19:16 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +        && PInvoke.GetWindowThreadProcessId(_lastHwndTarget, out _) == PInvoke.GetCurrentThreadId();
Maybe we should stash the window's thread to avoid the repeated call? It would also be slightly faster if you also use the unsafe overload and pass `null` for the process id.

2023-11-16 20:10 UTC, weltkante commented
> @weltkante - Thoughts?

from just looking at the changes it looks good to me, can't see any problems with it. won't have time to tests it myself at the moment.

2023-11-17 04:52 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
>      internal const string CF_INSHELLDRAGLOOP = "InShellDragLoop";
That is cool. First time I've seen that.

2023-11-17 06:24 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +    internal const string CF_COMPUTEDIMAGE = "ComputedImage";
I believe a couple of these formats are unnecessary.

2023-11-17 07:24 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +        && PInvoke.GetWindowThreadProcessId(_lastHwndTarget, out _) == PInvoke.GetCurrentThreadId();
Good idea. Thank you for your help.

2023-11-29 20:06 UTC, lonitra reviewed
mainly some small stylistic comments, otherwise LGTM!

2023-11-29 20:06 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +    /// Determines whether the specified format is a drag loop format.
```suggestion
    ///  Determines whether the specified format is a drag loop format.
```

2023-11-29 20:06 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +    /// <see langword="true"/> if <paramref name="format"/> is a drag loop format; otherwise <see langword="false"/>.
```suggestion
    ///  <see langword="true"/> if <paramref name="format"/> is a drag loop format; otherwise <see langword="false"/>.
```

2023-11-29 20:06 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
>      }
nit: make this into a body expression

2023-11-29 20:06 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
>      }
Ditto here as well

2023-11-29 20:06 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/GiveFeedbackEventArgs.cs
> -            && giveFeedbackEventArgs.Effect == Effect
I'm not sure I follow why this needed to be removed, could you provide more details?

2023-12-02 04:31 UTC, merged