Enable nullability in some DataGridView.Methods members
dotnet/winforms pull request #10325
Opened 2023-11-16 19:31 UTC by gpetrou

## Proposed changes

- Enable nullability in some DataGridView.Methods members.

2023-11-16 19:56 UTC, JeremyKuhne requested changes
If you can change the formatting as described that would be great. Otherwise, looks good!

2023-11-16 19:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
> +        if (Events[s_multiselectChangedEvent] is EventHandler eh &&
The preferred way to break conditional lines is with the logical operator at the front of the line.

``` C#
&& !_dataGridViewOper[OperationInDispose]
&& !IsDisposed)
```

2023-11-17 04:39 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
> +        if (Events[s_multiselectChangedEvent] is EventHandler eh &&
Hmm, searching for "  && " returns 504 results while searching for "&&\r\n" returns 1183. So, this does not seem to be the case. Without an analyzer, it is hard to enforce such rules. Do you still want me to do the proposed change?

2023-11-17 18:17 UTC, JeremyKuhne requested changes
Nit on logical operator placement when breaking statements across multiple lines.

2023-11-17 18:17 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.Methods.cs
> +                    !CommitEdit(
Logical operators should never be at the end of the line when breaking logical statements. `&&`, `||`, `or`, etc. If you touch one that isn't that way, please convert it to the preferred pattern.

2023-11-17 18:18 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
> +        if (Events[s_multiselectChangedEvent] is EventHandler eh &&
Yes. We're converting them over.

2023-11-17 19:18 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
> +        if (Events[s_multiselectChangedEvent] is EventHandler eh &&
I added a separate commit. Is this OK now?

2023-11-20 19:57 UTC, gpetrou commented
@JeremyKuhne @lonitra any more feedback on this one?

2023-11-21 05:10 UTC, lonitra reviewed
One other small comment, otherwise LGTM!

2023-11-21 05:10 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.Methods.cs
> +                                    HandledMouseEventArgs hme = new HandledMouseEventArgs(e.Button, e.Clicks, e.X, e.Y, e.Delta, defaultHandledValue: false);
Let's convert these over to the preferred pattern since this code is being touched
```suggestion
                                    HandledMouseEventArgs hme = new(e.Button, e.Clicks, e.X, e.Y, e.Delta, defaultHandledValue: false);
```

2023-11-21 05:10 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.Methods.cs
> +                                HandledMouseEventArgs hme = new HandledMouseEventArgs(e.Button, e.Clicks, e.X, e.Y, e.Delta, defaultHandledValue: false);
```suggestion
                                HandledMouseEventArgs hme = new(e.Button, e.Clicks, e.X, e.Y, e.Delta, defaultHandledValue: false);
```

2023-11-21 05:10 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.Methods.cs
> +                                    HandledMouseEventArgs hme = new HandledMouseEventArgs(e.Button, e.Clicks, e.X, e.Y, e.Delta, defaultHandledValue: false);
```suggestion
                                    HandledMouseEventArgs hme = new(e.Button, e.Clicks, e.X, e.Y, e.Delta, defaultHandledValue: false);
```

2023-11-21 05:10 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.Methods.cs
> +                                HandledMouseEventArgs hme = new HandledMouseEventArgs(e.Button, e.Clicks, e.X, e.Y, e.Delta, defaultHandledValue: false);
```suggestion
                                HandledMouseEventArgs hme = new(e.Button, e.Clicks, e.X, e.Y, e.Delta, defaultHandledValue: false);
```

2023-11-21 05:39 UTC, lonitra approved these changes
👍

2023-11-21 05:54 UTC, merged