Convert Rest of IRawElementProviderX to Cswin32
dotnet/winforms pull request #10334
Opened 2023-11-17 23:05 UTC by lonitra

Converts `IRawElementProviderFragmentRoot` and `IRawElementProviderHwndOverride` to Cswin32. Each conversion is separated into its own commit.  Note that we do not currently return anything from `IRawElementProviderHwndOverride.GetOverrideProviderForHwnd` aside from null so I've added a commit to remove the corresponding virtual method in separate commit.

Tested manually with Narrator and AccessibilityInsights.

2023-11-18 00:54 UTC, Tanya-Solyanik reviewed
Looks good. Minor comment about styling changes in formatting ternary conditional, my preference is to indent the 'true' and 'false' forks. And I thought it was the more common pattern in this repo. Let's vote in the meeting?

2023-11-18 00:54 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/InteropTests/AccessibleObjectTests.cs
> -    [DllImport(NativeTests, ExactSpelling = true, CharSet = CharSet.Unicode)]
We don't have to remove these definitions, even if we don't use them yet. This is the way to expose surface area from the native test. What am I missing?

2023-11-20 18:45 UTC, lonitra commented on src/System.Windows.Forms/tests/InteropTests/AccessibleObjectTests.cs
> -    [DllImport(NativeTests, ExactSpelling = true, CharSet = CharSet.Unicode)]
My understanding is that we don't need these anymore as these are methods that are exposed through Cswin32 now and that is how we are testing them above.

2023-11-20 21:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/InteropTests/AccessibleObjectTests.cs
> -    [DllImport(NativeTests, ExactSpelling = true, CharSet = CharSet.Unicode)]
I see, I missed that test above. This test does not validate that marshaling between managed and native code is done correctly because it's 100% managed, the previous test was doing actual marshaling to 
https://github.com/dotnet/winforms/blob/7a6f7349b6c57cc74f346498df279c2078818075/src/System.Windows.Forms/tests/InteropTests/NativeTests/AccessibleObjectTests.cpp#L408 and invoked our managed `ElementProviderFromPoint` implementation from CPP.  I would prefer keeping the old test.

2023-11-21 20:20 UTC, lonitra commented on src/System.Windows.Forms/tests/InteropTests/AccessibleObjectTests.cs
> -    [DllImport(NativeTests, ExactSpelling = true, CharSet = CharSet.Unicode)]
Ah I see. I have reverted all the tests including changes I had made in previous PRs. I needed to make some adjustments to `AccessibleObjectTests.cpp` given that we are not tolerating passing in null for some methods now.

2023-11-21 20:30 UTC, lonitra commented on src/System.Windows.Forms/tests/InteropTests/NativeTests/AccessibleObjectTests.cpp
> +        assertEqualHr(E_POINTER, hr);
@JeremyKuhne it seems that in old code we were returning `HRESULT.COR_E_NOTSUPPORTED` in 2 cases:
1. Passing in a `SAFEARRAY**` where it was already holding some valid value to a `SAFEARRAY*`
2. Passing in null for `SAFEARRAY**`

For 1. I don't see in documentation that explicitly calls out that we should be checking the passed in.. Should we continue this behavior?

For 2. Our pattern is we had been returning `E_POINTER` if null is passed in for a `SOMETYPE**`, I think we should maintain our pattern for returning `E_POINTER` for this case, but what are your thoughts?

2023-11-21 23:40 UTC, JeremyKuhne requested changes
Just an indent miss

2023-11-21 23:40 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/InteropTests/AccessibleObjectTests.cs
> +    [MarshalAs(UnmanagedType.IUnknown)] object pUnk,
nit: lost an indent

2023-11-21 23:40 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/InteropTests/NativeTests/AccessibleObjectTests.cpp
> +        assertEqualHr(E_POINTER, hr);
`COR_E_NOT_SUPPORTED` is `NotSupportedException`. `E_POINTER` is much more clear.

2023-11-21 23:49 UTC, JeremyKuhne approved these changes

2023-11-22 00:15 UTC, merged