Fix Clear and Remove after Sort in TreeView
dotnet/winforms pull request #10377
Opened 2023-11-25 08:27 UTC by gpetrou

Fixes #10376

## Proposed changes

- Fix Clear and Remove after Sort in TreeView. It looks like we broke this in https://github.com/dotnet/winforms/pull/9078 by following https://github.com/dotnet/winforms/pull/9078#discussion_r1187710943. Perhaps we should just bring back the old method instead of using the current approach?

2023-11-27 19:02 UTC, JeremyKuhne requested changes
Thanks, @gpetrou. I've added comments.

I'm thinking about whether or not we should put back the original logic. There is some risk that it will change behavior with nodes that are equivalent.

In general, one has to be extremely careful with messing with sort algorithms or hashes.

2023-11-27 20:33 UTC, JeremyKuhne commented
@gpetrou It would be good to make sure we have tests that exercise the `TreeView` nodes and validate their indices after manipulation. Recursive sorting should be captured as well.

Whatever we do here will be in the February update (the next update is already locked) so we've got some time to make sure we've got good test coverage.

2023-11-27 20:33 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView/TreeNode.cs
>              if (parentTreeView?.TreeViewNodeSorter is null)
But in the other case we don't use `Text`, right?

2023-11-27 20:33 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView/TreeNode.cs
> +                _childNodes.Sort((x, y) =>
I added  a separate commit. Is this better?

2023-11-27 21:03 UTC, JeremyKuhne requested changes
Added another comment.

2023-11-27 21:03 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView/TreeNode.cs
> +                _childNodes[i]._index = i;
You should iterate over the collection twice to be completely safe. Otherwise sorting could observe the wrong index in the parent node, which it wouldn't have been able to do before.

2023-11-28 18:10 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView/TreeNode.cs
> +                _childNodes.Sort((x, y) =>
It needs to be in a separate iteration per my other comment: https://github.com/dotnet/winforms/pull/10377#discussion_r1406740350

2023-11-28 18:13 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView/TreeNode.cs
>              if (parentTreeView?.TreeViewNodeSorter is null)
@gpetrou correct, but that is what I have here I believe.

2023-11-28 19:33 UTC, JeremyKuhne commented
@gpetrou we discussed this further as a team and we want to put back the original sorting logic to avoid any further regressions around visibility of index changes during sorting and sorting behavior with equivalent nodes. Are you ok with doing this?

2023-11-28 22:09 UTC, JeremyKuhne requested changes
One more nit. Are you up for adding index validation tests?

2023-11-28 22:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView/TreeNode.cs
> +            TreeNode[] newOrder = new TreeNode[_childNodes.Count];
I think this can still be `List<TreeNode> newOrder = new(nodeCount)`.

2023-11-29 18:50 UTC, JeremyKuhne approved these changes

2023-11-29 19:14 UTC, lonitra approved these changes
🚢

2023-11-29 19:16 UTC, merged

2023-11-29 21:05 UTC, lonitra commented
/backport to release/8.0