Suppress finalizeation of ThreadMethodEntry class. Fix #10361.
dotnet/winforms pull request #10460
Opened 2023-12-11 13:02 UTC by kirsan31

Fixes #10361
After every call to `BeginInvoke`/`Invoke` instance of `ThreadMethodEntry` will end up in Freachable queue.

## Proposed changes
~~- Register for finalization only when WH is allocated.~~
~~- SuppressFinalize after WH disposed.~~
- Remove `ThreadMethodEntry` finalizer.
- Dispose `WaitHandle`  during  `Invoke` call.

## Customer Impact
- `ThreadMethodEntry` will not end in Freachable queue - GC will be more faster - overall improve performance.

## Regression? 

- No

## Risk

Minimal.

## Test methodology 

~~New UT added.
I would like to add tests for the triggering of the finalizer, but unfortunately we cannot correctly handle exceptions in it :( That is, the only option is to add some kind of debug only test logic - is this necessary?~~

--------------------------

 P.S. I have many test failure (not related to this PR) on my pc:
![testError](https://github.com/dotnet/winforms/assets/17767561/ccc850c3-6684-4b54-9a08-6edb8bb68ed4)

--------------------------

P.P.S. I have build error with VS 17.8.3:
```
21>MSBuild version 17.8.3+195e7f5a3 for .NET Framework
21>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'D:\Projects\winforms\artifacts\obj\NativeTests\x86\Debug\CMakeFiles\6366f68e1e32f772e531aff683e51b2d\Contract_i.c.rule' exited with code 9009. [D:\Projects\winforms\artifacts\obj\NativeTests\x86\Debug\NativeTests.vcxproj]
21>C:\Users\_\.nuget\packages\microsoft.dotnet.cmake.sdk\9.0.0-beta.23607.2\build\Microsoft.DotNet.CMake.Sdk.targets(190,5): error MSB3073: The command "
21>C:\Users\_\.nuget\packages\microsoft.dotnet.cmake.sdk\9.0.0-beta.23607.2\build\Microsoft.DotNet.CMake.Sdk.targets(190,5): error MSB3073:       call "D:\Projects\winforms\eng\init-vs-env.cmd" 
21>C:\Users\_\.nuget\packages\microsoft.dotnet.cmake.sdk\9.0.0-beta.23607.2\build\Microsoft.DotNet.CMake.Sdk.targets(190,5): error MSB3073:       
21>C:\Users\_\.nuget\packages\microsoft.dotnet.cmake.sdk\9.0.0-beta.23607.2\build\Microsoft.DotNet.CMake.Sdk.targets(190,5): error MSB3073:       cmake --build "D:\Projects\winforms\artifacts\obj\NativeTests\x86\Debug" --target install  --config Debug -- -verbosity:quiet /p:PlatformToolset=%__PlatformToolset%
21>C:\Users\_\.nuget\packages\microsoft.dotnet.cmake.sdk\9.0.0-beta.23607.2\build\Microsoft.DotNet.CMake.Sdk.targets(190,5): error MSB3073:       " exited with code 1.
21>Done building project "NativeTests.proj" -- FAILED.
```

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/10460)

2024-01-12 19:04 UTC, lonitra reviewed
Thank you for your patience! Added some small comments

2024-01-16 17:08 UTC, lonitra approved these changes
LGTM!

2024-01-16 18:20 UTC, JeremyKuhne requested changes
In general this looks good, just a few questions / comments.

2024-01-16 18:20 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
> +    public void Control_Invoke_SameThread_ThreadMethodEntry_Finalizeation_Success()
```suggestion
    public void Control_Invoke_SameThread_ThreadMethodEntry_Finalization_Success()
```

Same with the others.

2024-01-20 12:51 UTC, kirsan31 commented
@JeremyKuhne 
- Suggestions implemented.
- Fixed some tests (they never failed). _P.s. it's hard to have no way to check for failures :(_ For example this code:  
  ```cs
  using (Control control = new())
  {
      control.CreateControl();
      Action method = () => { };
      IAsyncResult res = control.BeginInvoke(method);
      WaitHandle waitHandle = res.AsyncWaitHandle;
      while (!waitHandle.WaitOne(1))
      {
          Application.DoEvents();
      }
  }
  
  GC.Collect();
  GC.WaitForPendingFinalizers();
  GC.Collect();
  GC.WaitForPendingFinalizers();
  ```
  will not trigger `ThreadMethodEntry` finalization for some reason  🤷‍♂️ And I had to move the code to a local function...
- [Question](https://github.com/dotnet/winforms/pull/10460#discussion_r1453862120) about `#if DEBUG` is still actual.


Also I have noticed some _interesting_ thing. In `ManualResetEventPrivate` I use:
```cs
protected override void Dispose(bool explicitDisposing)
{
    base.Dispose(explicitDisposing);
    if (explicitDisposing)
    {
        // The owner (ThreadMethodEntry) need to free only this waitHandle.
        // But ThreadMethodEntry can't be Disposed directly because it exposed though IAsyncResult interface.
        // So after freeing this waitHandle we mark owner ThreadMethodEntry to suppress finalization.
        GC.SuppressFinalize(_owner);
    }
}
```
and `explicitDisposing` here is always true (even when called from finalizer): 
```cs
~ThreadMethodEntry()
{
    _resetEvent?.Close();
    Debug.Fail($"{nameof(ThreadMethodEntry)} finalization hit!");
}
```

Due to `WaitHandle` code:
```cs
public virtual void Close() => Dispose();

protected virtual void Dispose(bool explicitDisposing)
{
    _waitHandle?.Close();
}

public void Dispose()
{
    Dispose(true);
    GC.SuppressFinalize(this);
}
```

could this be a problem?

2024-01-29 18:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
> +#if DEBUG
@kirsan31 There is probably at least some value in running the tests in release on the slim chance that they fail. If we're concerned about test performance I'd rather see these conditionalized in code.

2024-01-29 18:51 UTC, JeremyKuhne commented
@kirsan31

> will not trigger ThreadMethodEntry finalization for some reason 🤷‍♂️ And I had to move the code to a local function...

Presumably it is still rooted in a local? At least historically I remember the GC keeping all locals rooted to the end of a stack frame in debug.

2024-01-29 18:58 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs
>              _resetEvent?.Close();
@kirsan31 I hadn't really internalized that we're touching a class in the finalizer. Why do we even have a finalizer? The event has its own `SafeHandle` that should take care of things.

2024-01-29 19:11 UTC, kirsan31 commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs
>              _resetEvent?.Close();
Ha, I think you're right - why did I decide to overcomplicate everything? 🤦‍♂️ Indeed, removing the destructor and disposing `WaitHandle` after `Invoke` should solve all the problems...
I'll correct...

2024-02-09 19:26 UTC, JeremyKuhne approved these changes

2024-02-09 20:15 UTC, merged