Move to use Cswin32 IAccessible
dotnet/winforms pull request #10479
Opened 2023-12-14 05:32 UTC by lonitra

Related: https://github.com/dotnet/winforms/issues/9795

- Converts `IAccessibleEx` and `ILegacyIAccessibleProvider` to Cswin32 definition in dedicated commits
- Introduce ComSafeArrayScopeExtensions which provides a way to generically get Safe array scope of corresponding COM pointers given an array of COM interfaces.
- Move to use Cswin32 IAccessible:
    - Adds a few new internal virtual APIs to avoid excessive allocations by changing between managed and native types  e.g. BSTR <-> string, IDispatch <-> AccessibleObject. 
    `CanXDirectly` > Determines whether native type should be grabbed directly since it avoids new allocations
    `GetXInternal()` > Grabs the native type of interest
    The idea is that our internal objects should not need to move between native and managed types so much. They should use the native types all the way through if they can. Objects that overrides our public facing IAccessible properties/methods (e.g. `Parent`, GetSelected()`) need to be checked for whether they are subclassed, if they are not then this is another chance where we can avoid allocations by using the optimized path (native types).
    - Add `IManagedWrapper` to AccessibleObject
    - Fix tests, tests required more mock setup due to newly added internal methods.

2023-12-14 21:15 UTC, JeremyKuhne requested changes
Few initial comments, spoke offline.

2023-12-15 09:26 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/ComSafeArrayScopeExtensions.cs
> +    ///  Creates a <see cref="ComSafeArrayScope{T}"/> where T is <typeparamref name="TComStruct"/> from an array of <typeparamref name="TComInterface"/>.
Ideally this would be `ComSafeArrayScope<TComStruct>`, but I wasn't able to have the comment resolve this way 😞

2023-12-18 21:14 UTC, JeremyKuhne requested changes
Very nice! Added a few comments.

2023-12-19 20:55 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/ButtonBase.ButtonBaseAccessibleObject.cs
> +        internal override bool CanGetKeyboardShortcutInternal => IsInternal && !this.TryGetOwnerAs(out ButtonBase? owner);
Good point. I went ahead and moved any complexity when we are only returning null

2023-12-21 18:03 UTC, JeremyKuhne approved these changes
Awesome work, @lonitra!

2023-12-21 18:19 UTC, merged