Enable `IDE0008` / `IDE0090` analyzers
dotnet/winforms pull request #10502
Opened 2023-12-19 00:40 UTC by elachlan

Fixes #10500

2023-12-19 00:41 UTC, elachlan commented on .editorconfig
> +dotnet_diagnostic.IDE0008.severity = warning
I think we should probably just remove it from `.editorconfig`

2023-12-19 02:21 UTC, elachlan commented
@lonitra any suggestions on the build failures?

```
src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ListViewGroupTests.cs(1427,9): error CS0436: (NETCORE_ENGINEERING_TELEMETRY=Build) The type 'TestAccessors' in 'D:\a\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\PropertyGridInternal\TestAccessors.PropertyGridTestAccessor.cs' conflicts with the imported type 'TestAccessors' in 'System.Windows.Forms.Common.TestUtilities, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Using the type defined in 'D:\a\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\PropertyGridInternal\TestAccessors.PropertyGridTestAccessor.cs'.
```

https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0436

2023-12-19 03:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Drawing/Design/UITypeEditorTests.cs
> +        object result = new object();
Use target-typed `new` , this applies in multiple places in this PR.

2023-12-19 03:31 UTC, Tanya-Solyanik commented on .editorconfig
> +dotnet_diagnostic.IDE0008.severity = warning
The code style insists on specifying explicit types for built-in types - https://github.com/dotnet/winforms/blob/main/docs/coding-style.md#variables, not in cases like this one - 

>using var stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));

That was the reason for `silent` I assume

2023-12-19 03:51 UTC, lonitra commented on .editorconfig
> +dotnet_diagnostic.IDE0008.severity = warning
Recent arcade update has started causing IDE0008 build errors. I had gone through a pass to fix the errors to get arcade PR merged. All have been fixed except for ‘System.Windows.Forms.Test’ project. I was mistaken and thought that errors from arcade PR meant we needed to enforce IDE0008 but after some more reading it now seems like our editorconfig is not being respected.. 
@elachlan could you revert enabling IDE0008 for now? I’ll need to investigate why build errors are occurring for this. We do want IDE0090 enabled though.

2023-12-22 21:14 UTC, elachlan commented on .editorconfig
> +dotnet_diagnostic.IDE0008.severity = warning
Thanks! Ill get this sorted early in the new year. I'll be afk until then.

2023-12-22 21:16 UTC, lonitra commented on .editorconfig
> +dotnet_diagnostic.IDE0008.severity = warning
Sure thing, enjoy the holidays! (:

2023-12-29 15:39 UTC, sharwell requested changes

2023-12-29 15:39 UTC, sharwell commented on .editorconfig
> +dotnet_diagnostic.IDE0008.severity = warning
I'm going to tentatively request changes here since the preferred strategy is using dotnet/roslyn#69843. I need to review the status of that work.

2023-12-29 15:45 UTC, sharwell commented on .editorconfig
> +dotnet_diagnostic.IDE0008.severity = warning
It looks like this functionality was completed in dotnet/roslyn#69844. I'll test to see if it's working in the latest branches of this repository.

2023-12-29 15:52 UTC, sharwell commented on .editorconfig
> +dotnet_diagnostic.IDE0008.severity = warning
🎉 Verified that if you remove _all_ references to IDE0008 from the solution, it will use the three lines above for the severity. This allows the three different cases to each have their own severity instead of requiring an all-or-nothing approach. Based on this, I believe this pull request will end up dramatically simplified (items falling under `csharp_style_var_elsewhere = false:silent` no longer need to change), so it might be best to just start over on it.

2024-01-02 01:25 UTC, elachlan commented on .editorconfig
> +dotnet_diagnostic.IDE0008.severity = warning
@sharwell thank you for doing the leg work here.

2024-01-02 13:49 UTC, sharwell commented on src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
> +        using ComScope<IStream> stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));
❓ Was this change applied before or after the configuration was updated to make this location not be a warning? I would have expected this to stay as `var`.

2024-01-02 20:31 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
> +        using ComScope<IStream> stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));
I started from scratch and changed the `.editorconfig` before applying the codefix.

2024-01-02 21:22 UTC, sharwell commented on src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
> +        using ComScope<IStream> stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));
Interesting. Sounds like the Fix All infrastructure isn't filtering diagnostics based on severity.

2024-01-03 17:59 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
> +        using ComScope<IStream> stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));
We don't want changes from `var` -> `ComScope`. Explicit type should only be used for built-in types, or if it is necessary to know the type to understand what the code is doing and type is not immediately apparent from reading the code. 

@sharwell what would be your recommendation to avoid this? Should we have `csharp_style_var_elsewhere = true:silent` instead?

2024-01-03 20:14 UTC, sharwell commented on src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
> +        using ComScope<IStream> stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));
@lonitra The only way to avoid it currently is to manually review the changes and only commit the ones you want. Roslyn needs to fix the way it runs a Fix All operation with mixed severities.

Note that reverting the var&rarr;ComScope change will not introduce warnings.

2024-01-03 20:58 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
> +        using ComScope<IStream> stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));
I'll get this sorted today.

2024-01-03 22:35 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
> +        using ComScope<IStream> stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));
@sharwell is there an issue tracking the problem with the Fix All?

2024-01-03 23:19 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        IDictionaryEnumerator metadataEnumerator = reader.GetMetadataEnumerator();
Please revert some of these other ones back to `var` as well. We should only use explicit type for built in types or if the code cannot be understood easily without the explicit type. For most of these, there doesn't seem to be a need to know the type expicitly so we can revert back to `var`. If you feel strongly that a line should use the explicit type then please let me know, happy to discuss it.

2024-01-03 23:39 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        IDictionaryEnumerator metadataEnumerator = reader.GetMetadataEnumerator();
I'll revert the changes and then got through and individually fix each of the 150 errors. That way only the ones we want to be fixed will be fixed.

2024-01-03 23:53 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        IDictionaryEnumerator metadataEnumerator = reader.GetMetadataEnumerator();
@lonitra how is that?

2024-01-04 00:09 UTC, lonitra approved these changes
Awesome! LGTM thanks for going through that.

2024-01-04 01:21 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InternalTestAccessors.KeyboardToolTipStateMachineTestAccessor.cs
> +internal static partial class InternalTestAccessors
So most of it was "undone" already. Just the rename was needing to be undone.

Basically if we used an explicit type, it would cause the error.

2024-01-04 15:27 UTC, sharwell commented on src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
> +        using ComScope<IStream> stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));
Not currently.I 've been discussing it with @mavasani

2024-01-04 16:38 UTC, sharwell commented on src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
> +        using ComScope<IStream> stream = ComHelpers.GetComScope<IStream>(new Interop.Ole32.GPStream(memoryStream));
https://github.com/dotnet/roslyn/pull/71486

2024-01-04 17:47 UTC, lonitra approved these changes

2024-01-05 00:00 UTC, merged