Implement screen recording for integration tests
dotnet/winforms pull request #10552
Opened 2023-12-29 15:41 UTC by sharwell

2023-12-29 22:45 UTC, sharwell commented on eng/Version.Details.xml
> +    <Dependency Name="System.IO.Hashing" Version="9.0.0-alpha.1.23628.3">
📝 I manually edited this file to add this. I'm not sure if anything else needs to be changed to ensure it gets updated along with the other packages.

2024-01-03 19:33 UTC, JeremyKuhne requested changes
@sharwell spoke with @lonitra offline. We're a little concerned about maintaining our own screen recording code. We'd be more comfortable using existing functionality. One example (from a cursory look) is https://github.com/sskodje/ScreenRecorderLib.

Can you take a look at options here? Thanks!

2024-01-03 19:45 UTC, sharwell commented
@JeremyKuhne I believe the only thing that would need maintenance here is the screenshot timing code, and this would need to be maintained regardless of the solution you go with:
https://github.com/dotnet/winforms/blob/1b508b1bea081bb8ed669b81fa2002e53cf5c410/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ScreenRecordService.cs#L560-L610

In theory the compression strategy could be further improved, but in practice I'm seeing saved image sizes that are acceptably small even on high resolution displays.

2024-01-03 21:02 UTC, JeremyKuhne commented
> I believe the only thing that would need maintenance here is the screenshot timing code

All of the code needs to be maintained. The manual PNG manipulation code is a concern.

> but in practice I'm seeing saved image sizes that are acceptably small even on high resolution displays.

What is "acceptably small"?

2024-01-03 21:05 UTC, sharwell commented
> > but in practice I'm seeing saved image sizes that are acceptably small even on high resolution displays.
> 
> What is "acceptably small"?

Some of the longer Roslyn tests produced 300+ images @ 4K resolution in a test, and the saved files were 5-7MB. The shorter duration and lower resolution files for CI were <1MB. WinForms seemed to come in a bit smaller despite having a higher image capture rate because the tests are particularly short.

2024-01-29 18:33 UTC, JeremyKuhne submitted a review, later dismissed
Approved after further internal discussion with @lonitra

2024-01-29 18:37 UTC, lonitra commented
@sharwell seems that there are conflicts. Could you rebase this so we can get this merged?

2024-02-01 14:01 UTC, sharwell commented
This is now updated. Note that if another automated dependency merge occurs before merging this, it will need to be rebased again due to the introduction of the System.IO.Hashing dependency.

2024-02-01 16:59 UTC, merged