Add VB Tests
dotnet/winforms pull request #10684
Opened 2024-01-18 00:44 UTC by paul1956

Fixes # Missing VB Tests for Microsoft.VisualBasic.Devices

## Proposed changes

- Add tests without any changes to formatting 
- 
- 

## Customer Impact
Improve test coverage for VisualBasic.Devices before changes are made to improve functionality.

## Regression? 
- No

## Risk
- None- no runtime code changes

## Test methodology

- These are just adding tests to test existing code
- Code Coverage should improve, tests themselves should have 100% Coverage

2024-01-25 02:49 UTC, paul1956 commented
@KlausLoeffelmann, @merriemcgaw @elachlan this PR only adds tests for VB Networking, there are no code changes to any existing code. My other 2 PRs include this code and its very useful to identify different behavior. I have another App that runs the same tests on Framework that helps identify differences in behavior between Framework and Core, there are bugs in Framework and Core that I have reported. This also includes tests for code I have no immediate plans to change (but will need updating eventually to replace WebClient for upload). I believe reviewing and merging this PR first will be the easiest and allow establishing baseline behavior for My.Computer.Network. There is 1 test that fails that is skipped because it fails everywhere but matches the documentation, I assume it should be changed to match current behavior if there is no plan to fix it (and change documentation) or leave it skipped. I don't have tests for manually cancelling a transfer (No idea how to write and automatic one), but if you do cancel a upload on Core before my PR #9867, the behavior differs from Framework, after my PR #9867 the Behavior is the same.

My recommendation is to review and merge this first, then Code Cleanup #10117 which should have no logic changes and finally #9867 the start of removing WebClient, it will be followed by a PR removing WebClient from upload and finally a PR to expose the Async API's that require API review.

2024-01-25 03:07 UTC, elachlan commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        Private Shared Function ValidateDownLoad(tmpFilePath As String, destinationFilename As String) As Long
```suggestion
        Private Shared Function ValidateDownload(tmpFilePath As String, destinationFilename As String) As Long
```

2024-01-25 03:09 UTC, elachlan commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        ''' The file will contain the letters A-Z repeating as needed
```suggestion
        ''' If size >= 0 then create the file with size length
        ''' The file will contain the letters A-Z repeating as needed.
```

2024-01-25 03:11 UTC, elachlan commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        ''' So all temp directories and files end up in 1 place
```suggestion
        ''' This gets a master test folder using a predefined Guid,
        ''' so all temp directories and files end up in one place.
```

2024-01-25 03:12 UTC, elachlan commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        Private Const DownloadLargeFileUrl As String = "https://ash-speed.hetzner.com/100MB.bin"
These tests will be run numerous time, will this website be okay with us downloading files from them for each test run?

2024-01-25 03:14 UTC, elachlan commented
Looks good to me from my quick review.

2024-01-25 03:28 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        Private Const DownloadLargeFileUrl As String = "https://ash-speed.hetzner.com/100MB.bin"
@elachlan I believe so according to their Terms of Service, but it could easily be changed to something else. I don't have any WebServers personally. Really all the servers in this PR should be replaced with something else, even the file I downloaded from GitHub where I want to validate the content could be changed and the tests would break. Plus, I assume if the upload completes its correct, and username/password is not validated by server. The Server immediately deletes the file after uploading (which has its advantages for multithreaded testing). Are there servers that can be uses for network testing, because there are other things that might need testing and I have not looked for public servers to use to test all the uploading and downloading options.

2024-02-01 00:52 UTC, paul1956 commented
@lonitra These are tests for .NET Framework behaviors, no existing code was changed in PR. One test (UploadWithExpectedTimeOut) will fail and is skipped because Core implementation is broken (don't know if it ever worked correctly in Core or where it broke).

What will it take to Merge this PR?

NOTE: It uses public websites to test networking behavior, this is something that might need to change.

2024-02-01 17:52 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +                                                         destinationFilename,
This is an example of what I mean with "indention".

2024-02-01 17:54 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +                                             )
Can we also please always put the closing paranths directly adjacent to the last code?

2024-02-01 18:20 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        Private Const DownloadLargeFileUrl As String = "https://ash-speed.hetzner.com/100MB.bin"
@KlausLoeffelmann Also have no experience with Web-Dev. For now, I will "skip" the tests but leave the code to verify that the code actually works as intended until someone provides further direction.

I will update to get rid of heavy indentation, following your example.

2024-02-01 18:22 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +                                               )
Done

2024-02-01 19:26 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        Private Const DownloadLargeFileUrl As String = "https://ash-speed.hetzner.com/100MB.bin"
@KlausLoeffelmann one note, I think I can do download, but upload is a question because FTP is part of the deprecated WebClient.

2024-02-01 22:52 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        Private Const DownloadLargeFileUrl As String = "https://ash-speed.hetzner.com/100MB.bin"
I am wondering, if we should phase that out.

2024-02-02 01:44 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        Private Const DownloadLargeFileUrl As String = "https://ash-speed.hetzner.com/100MB.bin"
@KlausLoeffelmann All Downloads now use HttpListener, but the tests run Sync, I would been some help starting a local server common to all tests.

All indenting is fixed, all Upload tests are skipped, and comment added about not using public servers for testing added.

2024-02-02 02:06 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +        Private Const DownloadLargeFileUrl As String = "https://ash-speed.hetzner.com/100MB.bin"
> I am wondering, if we should phase that out.

@KlausLoeffelmann 
If "that" means FTP Upload/Download, then yes. The recommendation is to use FluentFTP, which is compatible with VB and much more complete. I assume using FluentFTP NuGet package is not possible, if it were putting VB Upload as a skin on top of it would be trivial.

2024-02-02 22:26 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTests.vb
> +                                               )
@KlausLoeffelmann I have added them, is the reason that reviews are not done in VS where the descriptions are added by the IDE?

2024-02-10 02:31 UTC, paul1956 commented
@KlausLoeffelmann I have set Upload tests to skip because I could not find a way not to use a 3rd party Website, I could delete them and all references to 3rd party website, move to another branch (in case Upload is every upgraded) or something else. The download tests work in Framework and produce identical results in my new version PR #9867 and all PR Feedback has been incorporated and no longer use a 3rd party Website. I use HttpListener to test download.

2024-02-17 23:35 UTC, paul1956 commented
@elachlan  @KlausLoeffelmann I will be at sea for the next week and then on and off until 4/1 without access to GitHub.

Response will be slow.

2024-03-08 11:26 UTC, paul1956 commented
@elachlan I have improved code coverage to ~100% for Download File, but I have no idea how to rerun Code Coverage Report so its possible there are a few missed coverage lines, which could easily be fixed with a new report. I realized that I need tests that don't throw to cover all the "End Sub" Statements. Tests are grouped and ordered by PublicAPI.Shipped.txt order.

Not existing files are changed I just added files to enable testing.

Also the ship now allows access to GitHub so I can respond.

2024-03-08 12:23 UTC, elachlan commented
Hey Paul,

I'm sure the team will get to it soon. I wouldn't be too stressed on getting 100% code coverage on a report. Pretty cool you were able to do it though.

2024-03-09 04:58 UTC, paul1956 commented
Spoke too soon, got new report and missed a few lines.  Will fix this weekend, needed to rework all the authorization code in my server simulator because results didn’t match code going away for very odd cases like null passwords. Also add 2 new SR messages because I can't get them from the code going away. Pretty sure I did it wrong. Sent from my iPhoneI apologize for any typos Siri might have made.(503) 803-6077On Mar 8, 2024, at 2:23 AM, Lachlan Ennis ***@***.***> wrote:﻿
Hey Paul,
I'm sure the team will get to it soon. I wouldn't be too stressed on getting 100% code coverage on a report. Pretty cool you were able to do it though.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

2024-03-15 00:36 UTC, JeremyKuhne commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTestsCommonFunctions.vb
> +        Private Shared Function CreateTempDirectory(<CallerMemberName> Optional memberName As String = Nothing) As String
We should probably use the TempFile class from the Common.TestUtilities

2024-03-15 07:26 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTestsCommonFunctions.vb
> +        Private Shared Function CreateTempDirectory(<CallerMemberName> Optional memberName As String = Nothing) As String
I reinvested the same functions except to guarantee everything is under common directory which really helped know when behavior was not identical and fragments are left behind. Since everything is working I will look at switching. It will take a some time as I need to translate the latest C# global usings to VB.

2024-03-15 09:39 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTestsCommonFunctions.vb
> +        Private Shared Function CreateTempDirectory(<CallerMemberName> Optional memberName As String = Nothing) As String
@JeremyKuhne while not impossible, using  Common.TestUtilities really complicates the code. I built a Download server and there is an connection between WebServer and Tests filename. The Common.TestUtilites put everything under "temp" with a random filename but the WebServer uses the fileName as part of the URL and to create the file (since no real files are downloaded) to prevent tests conflicts and know what size file to deliver. There is no possibility for directories to conflict as I use same algorithm as Common.TestUtilities and a single sub directory under temp based on a GUID. and everything is cleaned up using Try Finally. This also allows tests to run in parallel. with a single WebServer.  I also have 100% Test coverage. The filename is not random, it contains information for WebServer to know file to simulate. Some extra comments may help explain the logic.

2024-03-20 01:22 UTC, KlausLoeffelmann requested changes
I had a few questions and things I would like to discuss first.

2024-03-20 01:22 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkDownloadTests.vb
> +#Region "Microsoft.VisualBasic.Devices.Network.DownloadFile(address As String, destinationFileName As String) -> Void"
I personally hate regions. Are we using them at other places in tests in WinForms (I know we do not use them in the Designer repo).
If not, could you get rid of them?

2024-03-20 01:22 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WebListener.vb
> +        ''' </summary>
Could you principally structure  XML comments by one character, so like

```visualbasic
''' <summary>
'''  The name of the function that creates the server is uses to establish the file to be downloaded
''' </summary>
```

2024-03-20 01:22 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WebListener.vb
> +            Dim listener As New HttpListener()
What kind of policy do we want for using empty lines for forming logical code block and better orientation?
You also mentioned once, that on save, the editor would change something in terms of deleting or inserting lines? 
Do I remember correctly?

2024-03-20 01:22 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WebListener.vb
> +        Public ReadOnly Address As String
Could you position this separatly for clarity?

2024-03-20 01:22 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkUploadTests.vb
> +        Private Const UploadFileUrl As String = "ftp://speedtest.tele2.net/upload/testing.txt"
So, what's the deal with this. 
We cannot have this in the source.
Would you rather skip the upload-test for now?

2024-03-20 01:22 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTestsCommonFunctions.vb
> +        Private Shared Function CreateTempDirectory(<CallerMemberName> Optional memberName As String = Nothing) As String
> using Common.TestUtilities really complicates the code.

I on first glance have to agree with Jeremy, and I have not really understood what fact does complicate having the download files in the temp directory?

2024-03-20 01:22 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkDownloadTests.vb
> +            Try
Again, about formatting:
Do we want to try to be close/similar to our standards in C# or Roslyn?

2024-03-20 01:27 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkDownloadTests.vb
> +#Region "Microsoft.VisualBasic.Devices.Network.DownloadFile(address As String, destinationFileName As String) -> Void"
Easily, there is a code fix to remove them. They were just preventing reorder of functions during code cleanup.

2024-03-20 01:30 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WebListener.vb
> +            Dim listener As New HttpListener()
CodeMaid was doing most of it, There are a lot of code fixes that add and remove blanks in CodeMaid, I can set it however you want the VB code has everything combination possible in main.

2024-03-20 01:31 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WebListener.vb
> +        Public ReadOnly Address As String
Not following request?

2024-03-20 01:34 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkUploadTests.vb
> +        Private Const UploadFileUrl As String = "ftp://speedtest.tele2.net/upload/testing.txt"
Upload is well beyond my ability unless a server exists that I can use and even then httpClient doesn't support it. The recommendation is to use a NuGet package which I assume is not allowed. I could just remove the tests that never run.

2024-03-20 01:45 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkTestsCommonFunctions.vb
> +        Private Shared Function CreateTempDirectory(<CallerMemberName> Optional memberName As String = Nothing) As String
I use the "temp directory", I just create a single subdirectory (which is easy to remove) under it then a unique subdirectory for each test so I can look for artifacts after failed tests that is harder if I don't know the name and some tests test directory creation so I still need a subdirectory under temp. I would also need to modify the file names as the serve needs to know which file to pretend to download and that is part of file name. 

I did not find a CreateTempDirectory function if one exists then I could get rid of all the code.

2024-03-20 01:46 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkDownloadTests.vb
> +            Try
Whatever something can force.

2024-03-20 02:39 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WebListener.vb
> +        ''' </summary>
@KlausLoeffelmann  There is no consistency in the code around this issue in the VB Repo, most of it has no extra space (1 total), some has 2 spaces, some 3 and some many more. Visual Studio does not care. Automatically going to just 1 space is very easy, anything else is possible but manual.

2024-03-20 02:42 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/NetworkUploadTests.vb
> +        Private Const UploadFileUrl As String = "ftp://speedtest.tele2.net/upload/testing.txt"
I have backed if up offline and deleted it.

2024-03-20 03:13 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WebListener.vb
> +        ''' </summary>
@KlausLoeffelmann 
May I suggest you and anyone else that has an opinion agree and let's document it for the Repo. Then I can use CodeMaid and/or manually have everything match whatever is agreed to. This should include placement of locals, order of private, friend and public functions, spacing in XML Comments and spacing between different program elements, how and when to wrap lines, including use of _, CodeMaid has a local settings file that enforce the rules, Visual Studio also has some things it can do on save. The original stuff I created was formatted by CodeMaid (it's now disabled) and has a specific order. This PR would have no code changes.

This will never be as good as C# which has its own formatter built on top of  editorConfig.

2024-04-16 01:14 UTC, paul1956 commented
This is now redundant, I am closing

2024-04-16 01:14 UTC, closed without merging