Add Fallback to CursorConverter.ConvertTo
dotnet/winforms pull request #10814
Opened 2024-02-03 01:07 UTC by lonitra

Fixes https://github.com/dotnet/winforms/issues/10185

We had previously removed this code in https://github.com/dotnet/winforms/pull/10005 in an attempt to avoid using reflection when converting Cursor->string. We had tried to avoid reflection by adding property `CursorsProperty` to `Cursor` to track the "string version" of the Cursor. This will work as expected when we are setting the cursor, however there are times when other processes set the cursor, in which we only have the handle available to us i.e. we cannot utilize `CursorsProperty` to properly convert Cursor->string since we will not have that information. To handle this case, we should fall back to our old code to convert the cursor properly.

Manually testing results:
![cursor](https://github.com/dotnet/winforms/assets/30007367/2e81532f-a4c9-43d6-9bdc-16dc7b987e53)

2024-02-03 01:54 UTC, Tanya-Solyanik submitted a review, later dismissed
Great fix!

2024-02-03 01:54 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Input/CursorConverter.cs
> +                    Cursor? c = (Cursor?)prop.GetValue(obj: null, index: null);
Please use full words for local variable names

2024-02-03 02:22 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Input/CursorConverter.cs
> +                    Cursor? c = (Cursor?)prop.GetValue(obj: null, index: null);
Whoops, thank you!

2024-02-03 03:04 UTC, Tanya-Solyanik approved these changes

2024-02-03 06:21 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Input/CursorConverter.cs
> +                for (int i = 0; i < props.Length; i++)
As we discussed, this is somewhat obtuse. It would be good to add a comment that explains what this is doing.

``` C#
// Try to find an exact instance match to a Cursors property, falling back on HCURSOR equality (==) with one
```

2024-02-03 06:23 UTC, JeremyKuhne requested changes

2024-02-03 06:23 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Input/CursorConverter.cs
> +                        if (ReferenceEquals(knownCursor, value))
In theory we shouldn't have to do this anymore as it would always be caught by the optimized path above. You wouldn't need `bestMatch` either, just the first `==`.  I think I'm seeing this right?

2024-02-03 06:24 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Input/CursorConverter.cs
> +                for (int i = 0; i < props.Length; i++)
The wording here is contingent on my other comment. Explaining the scenario would probably be good too.

2024-02-03 15:57 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Input/CursorConverter.cs
> +                        if (ReferenceEquals(knownCursor, value))
We can remove this, but seems like `bestMatch` was actually there because Cursors.Arrow and Cursors.Default share the same handle, so we had always ended up returning "Default" for Cursors.Arrow. I still removed this, but I needed to also add this case. Decided to put it before the loop to avoid doing the check every time.

2024-02-03 17:44 UTC, JeremyKuhne submitted a review, later dismissed
Looks good! One could walk backwards to replicate the old behavior, but I think it is better to be explicit about the Default case (which may have been accidental, honestly).

2024-02-03 21:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Input/CursorConverter.cs
> +                // We have a cursor that only has handle information. This can happen if other processes set the cursor.
It doesn't matter what process sets the cursor, the same process can be setting the cursor and then reading the cursor with Cursor.Current.

2024-02-04 22:02 UTC, Tanya-Solyanik approved these changes

2024-02-05 05:20 UTC, JeremyKuhne approved these changes

2024-02-05 17:08 UTC, merged