Add missing Stream overloads in DataStreamFromComStream
dotnet/winforms pull request #10857
Opened 2024-02-09 21:01 UTC by halgab

## Proposed changes

- Add optimised overloads to methods `DataStreamFromComStream.ReadByte` and `WriteByte`

## Customer Impact

- remove some small arrays allocations

## Risk

- low

## Test methodology 

- CI

2024-02-12 22:18 UTC, JeremyKuhne requested changes
Thanks for this! Just a minor comment.

2024-02-12 22:18 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/DataStreamFromComStream.cs
> +        Span<byte> oneByteArray = stackalloc byte[1];
You should be able to use the new span constructor, which would be the prefered method:

``` C#
byte data;
int r = Read(new Span<byte>(ref data));
// ...
```

2024-02-13 22:04 UTC, halgab commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/DataStreamFromComStream.cs
> +        Span<byte> oneByteArray = stackalloc byte[1];
Done. I hesitated between the two versions and initially chose this one because it didn't require me to initialise the data field.

2024-02-16 01:30 UTC, lonitra approved these changes

2024-02-16 18:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/DataStreamFromComStream.cs
> +        Span<byte> oneByteArray = stackalloc byte[1];
@halgab you could mark this method as `[SkipLocalsInit]` if you see that it makes it more efficient (look at sharplap.io).

2024-02-16 18:56 UTC, JeremyKuhne approved these changes
This is good, if you want to further optimize see my comment on [SkipLocalsInit]

2024-02-20 07:39 UTC, halgab commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/DataStreamFromComStream.cs
> +        Span<byte> oneByteArray = stackalloc byte[1];
I tried looking at the il and the assembly in sharplab [(here)](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyAMABMugHQCSA8gNw75GkBKArgHbBgC2ApiQMID2HAA6QuAJwDK4gG5gAxlwDONXAGYiqArwIBvHAQMEJwMVwCGHAopPnLAXgIsuAdwIBZLh35iAnsdMWABQAlCqGROpgbO4huvrhhgBGPsBcBDBmwGYEDjBcAGZmTBDAYQkGUcAEYjlWNhYkDOYwgU6uEkJmLAA8yakAfIGm+emZZsGh8eXIAOzVOQ6EAPwEALToBCCjWWUGAL5TBIcA2hIA1mBCADL8cmYQimQsYMAAuofIkdFu55exethygY+mkMllanlCsVSodwpV5g5rAEOI1mq0XEZOj0QYNhttxpNAUDZgjFgQVutNvjdgQDtg9kA=). I can't really interpret the results. I just notice that the asm looks bigger with the attribute. Also, we still have to set `data` to something despite the attribute.

I guess all those concerns are minor anyway compared to the gains of just defining this method overload properly

2024-02-21 01:22 UTC, merged