Wrap Com DataObject when BuiltInCom is Off
dotnet/winforms pull request #10854
Opened 2024-02-08 23:07 UTC by lonitra

Fixes #10853 

When dealing with COM pointers that are not ComWrappers-created unmanaged wrappers and built-in COM interop is turned on, `Marshal.GetObjectForIUnknown` generates an RCW under the hood for us to use, which is why we are able to cast the COM data object  we receive back seamlessly to `System.Runtime.InteropServices.ComTypes`. However when built-in COM interop is turned off and the COM pointer we receive is not a ComWrappers-created unmanaged wrapper, we need mimic built in COM behavior and wrap the object in a RCW ourselves to maintain same behavior

Trimmed drag/drop
Before:
![dragb4](https://github.com/dotnet/winforms/assets/30007367/74b829c7-0008-4bb0-830f-7d5074a1a34b)

After:
![drag](https://github.com/dotnet/winforms/assets/30007367/34ec8dda-5918-443b-abe7-b14eb195a6c9)

2024-02-08 23:07 UTC, lonitra commented
cc: @LakshanF

2024-02-08 23:24 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DropTarget.cs
> +    private static IDataObject? PrepareOutgoingDropData(object managedDataObject)
It would be nice if we could directly pass `Com.IDataObject*` here to avoid ptr->object->ptr in the last case, but I couldn't make that work in tests when we invoke this method dynamically.

2024-02-09 19:42 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/FORMATETC.cs
> +            cfFormat = (ushort)formatEtc.cfFormat,
As these are bit-equivalent you can use `Unsafe.As<T,T>` to convert them or simply cast pointer types when you are dealing with pointers (such as passing FORMATETC* in).

2024-02-12 19:25 UTC, JeremyKuhne requested changes
Triple check ref counts.

2024-02-12 22:22 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/STATDATA.cs
> +            pAdvSink = ComHelpers.GetComPointer<IAdviseSink>(statData.advSink),
I'm still unclear on how this IAdviseSink add ref gets released.

2024-02-12 22:28 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/STATDATA.cs
> +            pAdvSink = ComHelpers.GetComPointer<IAdviseSink>(statData.advSink),
We have one usage of this cast currently, which is here https://github.com/dotnet/winforms/pull/10854/files#diff-23196ea13d7ab5a81c9001467c40bd4ada54be0f7a591a7e7e6845c987ecd709R43 and I am releasing before end of that method. Maybe I could implement `IDisposable` additionally?

2024-02-12 23:16 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComDataObjectAdapter.cs
> +            uint[] retrieved = [1];
Better to just use `uint` and not an array. Then you won't allocate an array or have to pin.

2024-02-12 23:39 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs
> +/*        yield return new object[] { DATADIR.DATADIR_GET, null };
Uncomment

2024-02-13 01:23 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs
> +/*        yield return new object[] { DATADIR.DATADIR_GET, null };
This should actually be removed since the test below is mocking `ComTypes.IDataObject.EnumFormatEtc` to return null, but this shouldn't return null if native method succeeded.

2024-02-13 02:11 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/STATDATA.cs
> +        if (adviseSink is not null)
I'm pretty sure we always need to release `pAdvSink` if it was passed to us, presumably by just putting a `using` up above.

2024-02-13 02:15 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/STATDATA.cs
> +        if (adviseSink is not null)
We will always release it. If `adviseSink` is null, it will be released in `AdviseSinkWrapper` via the `AgileComPointer` we create there.

2024-02-13 02:16 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.EnumStatDataWrapper.cs
> +            if ((pceltFetched is not null && pceltFetched.Length == 0)
if (pceltFetched is null || pceltFetched.Length == 0) return E_POINTER

2024-02-13 02:17 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.EnumStatDataWrapper.cs
> +            for (int i = 0; i < nativeStatData.Length; i++)
This has to be ppceltFetched, not the full length.

2024-02-13 02:19 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/STATDATA.cs
> +        if (adviseSink is not null)
Ah. It would be clearer if we did not takeOwnership and just always release.

2024-02-13 02:20 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.EnumStatDataWrapper.cs
> +            if ((pceltFetched is not null && pceltFetched.Length == 0)
Both are effectively "null" for what would be the int*

2024-02-13 04:03 UTC, JeremyKuhne approved these changes

2024-02-13 04:45 UTC, merged