Refactor DataObject
dotnet/winforms pull request #10918
Opened 2024-02-20 23:47 UTC by lonitra

DataObject has been difficult to read/maintain as it deals with all 3 IDataObject interface variations (`System.Runtime.InteropServices.ComTypes`, `System.Windows.Forms.IDataObject`, and `Windows.Win32.System.Com.IDataObject.Interface`) without clear separation. 
This PR refactors `DataObject` to be more readable by adding 5 new classes to separate the logic.
- `ComposedDataObject`: Encapsulates all the logic to move between the 3 interface by using the next 4 classes under the hood.
- `WinFormsDataObjectToNativeAdapter`: Maps `System.Windows.Forms.IDataObject` to `Windows.Win32.System.Com.IDataObject.Interface` calls (This is equivalent to what we had implemented in `DataObject` that was removed)
- `RuntimeDataObjectToNativeAdapter`: Maps `System.Runtime.InteropServices.ComTypes.IDataObject` to `Windows.Win32.System.Com.IDataObject.Interface` calls
- `NativeDataObjectToWinFormsAdapter`: Maps the native IDataObject pointer to `System.Windows.Forms.IDataObject` calls (This is equivalent to our old `ComDataObjectAdapter` that is removed in this PR)
- `NativeDataObjectToRuntimeAdapter`: Maps the native IDataObject pointer to `System.Runtime.InteropServices.ComTypes` calls 

After changes, DataObject now forwards all calls to the inner `ComposedDataObject` which knows how to move between the 3 IDataObject interfaces no matter what we started out with (`System.Runtime.InteropServices.ComTypes`, `System.Windows.Forms.IDataObject`, or `Windows.Win32.System.Com.IDataObject`).

2024-02-21 03:26 UTC, JeremyKuhne requested changes
Much more contained! Added a few comments.

2024-02-21 03:26 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToRuntimeAdapter.cs
> +        private class NativeDataObjectToRuntimeAdapter : Com.IDataObject.Interface, ComTypes.IDataObject
I don't think you need to implement `Com.IDataObject.Interface` here.

2024-02-21 03:26 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.cs
> +            var runtimeToNative = new RuntimeDataObjectToNativeAdapter(runtimeDataObject);
nit: Target typed new

2024-02-21 03:26 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.cs
> +            Com.IDataObject.Interface nativeDataObject = new WinFormsDataObjectToNativeAdapter(winFormsDataObject);
```suggestion
            WinFormsDataObjectToNativeAdapter nativeDataObject = new(winFormsDataObject);
```

2024-02-21 03:26 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.WinFormsDataObjectToNativeAdapter.cs
> +        private unsafe class WinFormsDataObjectToNativeAdapter : IDataObject, Com.IDataObject.Interface
I don't think you need `IDataObject` on this one?

2024-02-21 20:33 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            dataObject = comDataObject;
Does this need to be wrapped? This still seems to work as expected when built in COM in turned off as test is passing. It will be wrapped on the 'drop' side if the object only implements runtime IDataObject.

2024-02-21 20:36 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            dataObject = comDataObject;
Presumably something is wrong with the test. If it is truly just implementing the runtime IDataObject, how can it possibly get a CCW without built-in COM?

2024-02-22 01:30 UTC, JeremyKuhne approved these changes
🚀 🚀 Go go!

2024-02-22 16:58 UTC, merged