Add unimplemented types for deprecated UI controls
dotnet/winforms pull request #10913
Opened 2024-02-20 06:35 UTC by SimonZhao888

Fixes #

## Proposed changes

- 
- 
- 

## Customer Impact

- 
- 

## Regression? 

- Yes / No

## Risk

-

## Screenshots 

### Before

### After

## Test methodology 

- 
- 
- 

## Accessibility testing  

 

## Test environment(s) 

-

2024-02-28 02:04 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/ContextMenu.cs
> +#pragma warning disable RS0016 // Add public types and members to the declared API
```suggestion
#pragma warning disable RS0016 // Add public types and members to the declared API to simplify porting of applications from .NET Framework to .NET. These types will not work, but if they are not accessed, other features in the application will work.
```

2024-03-12 20:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +    private const int GRIDSTATE_trackColResize = 0x00000008;
Do we need the private variables?

2024-03-12 20:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +    private int BorderWidth
We don't need private or internal properties, only protected or public.

2024-03-12 20:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/AccessibleObjectTests.cs
> +        {
Please use the modern collection initialization syntax, see https://github.com/dotnet/winforms/pull/11024

2024-03-12 20:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +namespace WinformsControlsTest;
Could you please add a comment that this is added to test compile time compatibility only. 

Also consider adding a button to the main page that attempts to create this form in a Try/Catch statement and catches the appropriate exception. If it's too awkward, then ignore this suggestion.

2024-04-02 01:58 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/ContextMenu.cs
> +[Obsolete("ContextMenu has been deprecated. Use ContextMenuStrip instead.")]
Done.

2024-04-02 01:58 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/ContextMenu.cs
> +        get
Done.

2024-04-02 01:58 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/Menu.cs
> +    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never),
Done.

2024-04-02 01:59 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +    internal TraceSwitch DataGridAcc = new TraceSwitch("DataGridAcc", "Trace Windows Forms DataGrid Accessibility");
Done.

2024-04-02 01:59 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +    private const int GRIDSTATE_trackColResize = 0x00000008;
Done.

2024-04-02 01:59 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +    private int BorderWidth
Done.

2024-04-02 01:59 UTC, SimonZhao888 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/AccessibleObjectTests.cs
> +        {
Done.

2024-04-02 02:00 UTC, SimonZhao888 commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +namespace WinformsControlsTest;
I had added a comment to it.

2024-04-02 02:11 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/MenuMerge.cs
> +    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
These attributes don't work on class, I tried it on a button and take the `AutoSizeMode` for example.

**Attributes on the class:**
The `AutoSizeMode` property is still displayed in the Properties panel.
![image](https://github.com/dotnet/winforms/assets/133954995/f57b75f7-5140-4847-bd7c-da10ec0f327a)

**Attributes  not on the class:**
The `AutoSizeMode` property is no longer display in the Properties panel.
![image](https://github.com/dotnet/winforms/assets/133954995/90dc319f-22bd-4338-8d3f-7034e1ef7a18)

2024-04-02 09:19 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +        get => new Size(130, 80);
Done.

2024-04-02 09:20 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridColumn.cs
> +        => SetDataGridInColumn(value);
Done.

2024-04-02 09:20 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridCell.cs
> +         => !(left == right);
Done.

2024-04-03 06:51 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +    }
`public int FirstVisibleColumn => throw new PlatformNotSupportedException();`

2024-04-03 06:51 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +    }
Use expression body
` protected ScrollBar HorizScrollBar => throw new PlatformNotSupportedException();`

2024-04-03 06:51 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridAddNewRow.cs
> +        => base.PaintCellContents(g, cellBounds, column, backBr, foreBrush, alignToRight);
Why not throw exception here directly?

2024-04-03 06:51 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridColumn.cs
> +        => throw new PlatformNotSupportedException();
It is also a Protected method. Why do some throw exceptions and some do not do this?

2024-04-03 06:51 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridColumn.cs
> +        }
Use expression body for this and other properties
`public static TraceSwitch DGEditColumnEditing => throw new PlatformNotSupportedException();`

2024-04-03 06:51 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/StatusBar/StatusBar.cs
> +    }
Use expression body for property

2024-04-03 06:51 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/StatusBar/StatusBarDrawItemEvent.cs
> +#pragma warning disable RS0016 // Add public types and members to the declared API
Add same comment with other class
`#pragma warning disable RS0016 // Add public types and members to the declared API to simplify porting of applications from .NET Framework to .NET. These types will not work, but if they are not accessed, other features in the application will work.`

2024-04-07 02:44 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/Menu.cs
> +    public const int FindShortcut = 1;
I think our goal is to make sure that after the control is migrated from the framework to .NET Core, error message "xxx not found" will be replaced by " xxx has been deprecated", so the public variables should be kept ensuring that the errors of the relevant controls are displayed in only one way.

2024-04-07 02:44 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +    }
Done.

2024-04-07 02:44 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGrid.cs
> +    }
Done.

2024-04-07 02:45 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridAddNewRow.cs
> +        => base.PaintCellContents(g, cellBounds, column, backBr, foreBrush, alignToRight);
Done.

2024-04-07 02:50 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridColumn.cs
> +        => throw new PlatformNotSupportedException();
![image](https://github.com/dotnet/winforms/assets/133954995/6f47a80d-94e7-4848-b147-8c87d4fb0f73)
https://github.com/dotnet/winforms/issues/3783#issuecomment-1920172606

2024-04-07 02:50 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridColumn.cs
> +        }
Done.

2024-04-07 02:51 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/StatusBar/StatusBar.cs
> +    }
Done.

2024-04-07 02:51 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/StatusBar/StatusBarDrawItemEvent.cs
> +#pragma warning disable RS0016 // Add public types and members to the declared API
Done.

2024-04-08 04:47 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +|  __`WFDEV006`__ | `Menu.MenuItemCollection` has been deprecated. |
For classes that don't have a direct replacement, I would say something like: `Use ToolStrip control and related classes in your application." of `Use DataGridView control and related classes in your application.`

2024-04-08 04:47 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridRelationshipRow.cs
> +    internal class DataGridRelationshipAccessibleObject : AccessibleObject
We don't need to restore internal classes because customers couldn't compile against them in .NET Framework either.

2024-04-09 08:26 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/ContextMenu.cs
> +        => throw new PlatformNotSupportedException();
Done.

2024-04-09 08:26 UTC, SimonZhao888 commented on docs/list-of-diagnostics.md
> +|  __`WFDEV006`__ | `Menu.MenuItemCollection` has been deprecated. |
Done.

2024-04-09 08:27 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridRelationshipRow.cs
> +    internal class DataGridRelationshipAccessibleObject : AccessibleObject
Done.

2024-04-09 10:13 UTC, ricardobossan commented
LGTM

2024-08-09 21:33 UTC, JeremyKuhne requested changes
It would probably be good to create a test project that is built against .NET Framework with the "removed" types in them.

Idea: Have some public methods that use the types in some way with a `try .. catch (PlatformNotSupportedException)` around the usage. Then the tests can call the methods and see that they don't fall over.

2024-09-02 08:06 UTC, SimonZhao888 commented
> It would probably be good to create a test project that is built against .NET Framework with the "removed" types in them.
> 
Do you mean like this: https://github.com/dotnet/winforms/tree/cd0fd6dcdb6f8e71609889bb9bd7ad2e67124731/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +#pragma warning disable WFDEV006, WFDEV007, WFDEV009, WFDEV011, WFDEV015, WFDEV017, WFDEV022, WFDEV025 // Type or member is obsolete
Please add a link to the workitem for reference.

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +        MainMenu mainMenu = new MainMenu();
Please use the target-typed `new`

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +    public ObsoleteControls()
Please add a white space between the field declaration and the constructor.

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +        AddCustomDataTableStyle();
Please add a blank line after `return`

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +        MessageBox.Show("Current BindingManager Position: " + bmGrid.Position);
Please use string interpolation

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +            /* Add a GridColumnStyle and set its MappingName
Please use `//` -style comments.

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +            DataGridTableStyle ts1 = new DataGridTableStyle
Please spell out local variable names.

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +            SetUp();
Do we need to call `Setup`? Aren't we throwing before getting there?

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/Control.ControlAccessibleObjectTests.cs
> +            .Select(type => new object[] { type });
Please align with the line above.

2024-09-04 02:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/Control.ControlAccessibleObjectTests.cs
> +        var typesToIgnore = new[]
Please share this collection between the tests.

2024-09-04 02:41 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.Designer.cs
> +        this.components = new System.ComponentModel.Container();
Please remove `this` in this file.

2024-09-05 06:09 UTC, SimonZhao888 commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +            SetUp();
No, we don't need call `Setup `method.

2024-09-05 08:41 UTC, LeafShi1 reviewed
The pipeline failures need to be resolved

2024-09-05 18:48 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
> +using WinformsControlsTest;
Please find there the namespace didn't get renamed Winforms-> WinForms and fix the source.

2024-09-05 18:48 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.Designer.cs
> +namespace WinformsControlsTest;
```suggestion
namespace WinFormsControlsTest;
```

2024-09-05 18:48 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +        MessageBox.Show("New menu item clicked", "DataGrid");
Please use expression-body syntax

2024-09-05 18:48 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +            SetUp();
Right, we will never execute the setup method. This might be confusing. Please add a comment that explains that this code works only when re-targeting to NET48

2024-09-05 19:13 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +        new DataColumn("CustID", typeof(int));
Please indent or put everything on a single line

2024-09-06 22:59 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +            CreateMainMenu();
Could you please remove the trailing white spaces?

2024-09-11 19:47 UTC, Tanya-Solyanik reviewed
I took a closer look, and I see 2 important issues.
1. when I generate the diff using the APiCompat tool, I see that 1 type and some members are still missing.

before(4.8.1 vs rc1:
```
Microsoft.DotNet.ApiCompat.Tool.exe --left-assembly "c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\System.Windows.Forms.dll" --right-assembly "c:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\9.0.0-rc.1.24452.1"\system.windows.forms.dll 2> a.txt
```
after(4.8.1 vs your PR):
```
Microsoft.DotNet.ApiCompat.Tool.exe --left-assembly "c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\System.Windows.Forms.dll" --right-assembly "C:\winforms\artifacts\obj\System.Windows.Forms\Debug\net9.0\ref\System.Windows.Forms.dll" 2> b.txt
```

I see that all formelly removed types are now present in the dll, except for
>Type 'System.Windows.Forms.DataGridColumnStyle.DataGridColumnHeaderAccessibleObject'

<details>

```
Type 'System.Windows.Forms.ContextMenu'
Type 'System.Windows.Forms.DataGrid'
Type 'System.Windows.Forms.DataGridBoolColumn'
Type 'System.Windows.Forms.DataGridCell'
Type 'System.Windows.Forms.DataGridColumnStyle'
Type 'System.Windows.Forms.DataGridLineStyle'
Type 'System.Windows.Forms.DataGridParentRowsLabelStyle'
Type 'System.Windows.Forms.DataGridPreferredColumnWidthTypeConverter'
Type 'System.Windows.Forms.DataGridTableStyle'
Type 'System.Windows.Forms.DataGridTextBox'
Type 'System.Windows.Forms.DataGridTextBoxColumn'
Type 'System.Windows.Forms.FileDialogCustomPlace'
Type 'System.Windows.Forms.FileDialogCustomPlacesCollection'
Type 'System.Windows.Forms.GridColumnStylesCollection'
Type 'System.Windows.Forms.GridTablesFactory'
Type 'System.Windows.Forms.GridTableStylesCollection'
Type 'System.Windows.Forms.IDataGridEditingService'
Type 'System.Windows.Forms.MainMenu'
Type 'System.Windows.Forms.Menu'
Type 'System.Windows.Forms.MenuItem'
Type 'System.Windows.Forms.MenuMerge'
Type 'System.Windows.Forms.StatusBar'
Type 'System.Windows.Forms.StatusBarDrawItemEventArgs'
Type 'System.Windows.Forms.StatusBarDrawItemEventHandler'
Type 'System.Windows.Forms.StatusBarPanel'
Type 'System.Windows.Forms.StatusBarPanelAutoSize'
Type 'System.Windows.Forms.StatusBarPanelBorderStyle'
Type 'System.Windows.Forms.StatusBarPanelClickEventArgs'
Type 'System.Windows.Forms.StatusBarPanelClickEventHandler'
Type 'System.Windows.Forms.StatusBarPanelStyle'
Type 'System.Windows.Forms.ToolBar'
Type 'System.Windows.Forms.ToolBarAppearance'
Type 'System.Windows.Forms.ToolBarButton'
Type 'System.Windows.Forms.ToolBarButtonClickEventArgs'
Type 'System.Windows.Forms.ToolBarButtonClickEventHandler'
Type 'System.Windows.Forms.ToolBarButtonStyle'
Type 'System.Windows.Forms.ToolBarTextAlign'
```
</details>

but some members are **newly** missing

<details>

```
Member 'void System.Windows.Forms.MenuItem.CloneMenu(System.Windows.Forms.MenuItem)'
Member 'void System.Windows.Forms.MenuItem.OnClick(System.EventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnDrawItem(System.Windows.Forms.DrawItemEventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnInitMenuPopup(System.EventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnMeasureItem(System.Windows.Forms.MeasureItemEventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnPopup(System.EventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnSelect(System.EventArgs)'
Member 'void System.Windows.Forms.MenuItem.Visible.set'
Member 'void System.Windows.Forms.ToolBar.OnButtonClick(System.Windows.Forms.ToolBarButtonClickEventArgs)'
Member 'void System.Windows.Forms.ToolBar.OnButtonDropDown(System.Windows.Forms.ToolBarButtonClickEventArgs)'
```
</details>

I'm not sure why these were not detected by the tool when comparing 481 vs RC1, maybe because I didn't use a ref assembly for RC1. 
These are mostly protected virtuals, except for the MenuItem.Visible setter. Was there a reason to exclude them? Users might have custom MenuItems derived from our MenuItem, there is no reason to break binary compat for that. 

2. When I run the sample application, I'm getting the platform not supported exception from the finalizer thread:
```
System.Windows.Forms.dll!System.Windows.Forms.DataGrid.Dispose(bool disposing) Line 656	C#
System.ComponentModel.Primitives.dll!System.ComponentModel.Component.~Component()	Unknown
System.Private.CoreLib.dll!System.GC.RunFinalizers()	Unknown

```

All Dispose methods should do nothing at all instead of throwing an exception. In fact I think all `void` methods should do nothing.

>protected override void Dispose(bool disposing) { };

2024-09-11 19:47 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +public partial class ObsoleteControls : Form
Please add `[DesignerCategory("code")]`

2024-09-11 19:47 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +/// This is added to test compile time compatibility only.
```suggestion
///  This is added to test compile time compatibility only. 
```

2024-09-11 23:02 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/ContextMenu.cs
> +public class ContextMenu : Menu
Suppress your new warning that ContextMenu is obsolete
> #pragma warning disable WFDEV005 // Type or member is obsolete

2024-09-11 23:28 UTC, Tanya-Solyanik reviewed
> I took a closer look, and I see 4 important issues.
1. when I generate the diff using the APiCompat tool, I see that 1 type and some members are still missing.

before(4.8.1 vs rc1:
```
Microsoft.DotNet.ApiCompat.Tool.exe --left-assembly "c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\System.Windows.Forms.dll" --right-assembly "c:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\9.0.0-rc.1.24452.1"\system.windows.forms.dll 2> a.txt
```
after(4.8.1 vs your PR):
```
Microsoft.DotNet.ApiCompat.Tool.exe --left-assembly "c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\System.Windows.Forms.dll" --right-assembly "C:\winforms\artifacts\obj\System.Windows.Forms\Debug\net9.0\ref\System.Windows.Forms.dll" 2> b.txt
```

I see that all formerly removed types are now present in the dll, except for
>Type 'System.Windows.Forms.DataGridColumnStyle.DataGridColumnHeaderAccessibleObject'

please add it.
<details>

```
Type 'System.Windows.Forms.ContextMenu'
Type 'System.Windows.Forms.DataGrid'
Type 'System.Windows.Forms.DataGridBoolColumn'
Type 'System.Windows.Forms.DataGridCell'
Type 'System.Windows.Forms.DataGridColumnStyle'
Type 'System.Windows.Forms.DataGridLineStyle'
Type 'System.Windows.Forms.DataGridParentRowsLabelStyle'
Type 'System.Windows.Forms.DataGridPreferredColumnWidthTypeConverter'
Type 'System.Windows.Forms.DataGridTableStyle'
Type 'System.Windows.Forms.DataGridTextBox'
Type 'System.Windows.Forms.DataGridTextBoxColumn'
Type 'System.Windows.Forms.FileDialogCustomPlace'
Type 'System.Windows.Forms.FileDialogCustomPlacesCollection'
Type 'System.Windows.Forms.GridColumnStylesCollection'
Type 'System.Windows.Forms.GridTablesFactory'
Type 'System.Windows.Forms.GridTableStylesCollection'
Type 'System.Windows.Forms.IDataGridEditingService'
Type 'System.Windows.Forms.MainMenu'
Type 'System.Windows.Forms.Menu'
Type 'System.Windows.Forms.MenuItem'
Type 'System.Windows.Forms.MenuMerge'
Type 'System.Windows.Forms.StatusBar'
Type 'System.Windows.Forms.StatusBarDrawItemEventArgs'
Type 'System.Windows.Forms.StatusBarDrawItemEventHandler'
Type 'System.Windows.Forms.StatusBarPanel'
Type 'System.Windows.Forms.StatusBarPanelAutoSize'
Type 'System.Windows.Forms.StatusBarPanelBorderStyle'
Type 'System.Windows.Forms.StatusBarPanelClickEventArgs'
Type 'System.Windows.Forms.StatusBarPanelClickEventHandler'
Type 'System.Windows.Forms.StatusBarPanelStyle'
Type 'System.Windows.Forms.ToolBar'
Type 'System.Windows.Forms.ToolBarAppearance'
Type 'System.Windows.Forms.ToolBarButton'
Type 'System.Windows.Forms.ToolBarButtonClickEventArgs'
Type 'System.Windows.Forms.ToolBarButtonClickEventHandler'
Type 'System.Windows.Forms.ToolBarButtonStyle'
Type 'System.Windows.Forms.ToolBarTextAlign'
```
</details>

but some members are **newly** missing
<details>

```
Member 'void System.Windows.Forms.MenuItem.CloneMenu(System.Windows.Forms.MenuItem)'
Member 'void System.Windows.Forms.MenuItem.OnClick(System.EventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnDrawItem(System.Windows.Forms.DrawItemEventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnInitMenuPopup(System.EventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnMeasureItem(System.Windows.Forms.MeasureItemEventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnPopup(System.EventArgs)'
Member 'void System.Windows.Forms.MenuItem.OnSelect(System.EventArgs)'
Member 'void System.Windows.Forms.MenuItem.Visible.set'
Member 'void System.Windows.Forms.ToolBar.OnButtonClick(System.Windows.Forms.ToolBarButtonClickEventArgs)'
Member 'void System.Windows.Forms.ToolBar.OnButtonDropDown(System.Windows.Forms.ToolBarButtonClickEventArgs)'
```
</details>

I'm not sure why these were not detected by the tool when comparing 481 vs RC1, maybe because I didn't use a ref assembly for RC1. 
These are mostly protected virtuals, except for the MenuItem.Visible setter. Users might have custom MenuItems derived from the deprecated MenuItem, there is no reason to break binary compat for that. 


3. remove all `override` methods, except for statics, if any. They are not required for binary compat, i.e. code will compile against the base class methods.  And instance methods are impossible to call because constructor throws. Override properties that define attributes, should stay, because we need the attributes.
4. When I run the sample application, I'm getting the platform not supported exception from the finalizer thread:
```
System.Windows.Forms.dll!System.Windows.Forms.DataGrid.Dispose(bool disposing) Line 656	C#
System.ComponentModel.Primitives.dll!System.ComponentModel.Component.~Component()	Unknown
System.Private.CoreLib.dll!System.GC.RunFinalizers()	Unknown

```
I think this is called because constructor calls base() under the covers before throwing. Wouldn't be a problem when you remove the override methods.

2024-09-11 23:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +            MessageBox.Show(ex.Message);
This is an extra pop-up box that we have to close , this is an extra click when testing. Consider
```suggestion
            title = ex.Message;
```

2024-09-11 23:42 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Obsolete/ObsoleteControls.cs
> +#pragma warning disable WFDEV006, WFDEV007, WFDEV009, WFDEV011, WFDEV015, WFDEV017, WFDEV022, WFDEV025 // Type or member is obsolete
```suggestion
#pragma warning disable WFDEV006, WFDEV007, WFDEV009, WFDEV011, WFDEV015, WFDEV017, WFDEV022, WFDEV025, CS0618 // Type or member is obsolete
```

2024-09-17 02:54 UTC, Tanya-Solyanik commented
@SimonZhao888  - I noticed that compat tool had not generated APIs like this one - https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.contextmenu?view=netframework-4.8.1 in the diff. APIs that were removed from the existing types. I think we should restore APIs like this one as well. Could you please generate a list of these APIs?

2024-09-18 20:29 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/ContextMenu.cs
> +public class ContextMenu : Menu
Could you please add EditorBrowsable attribute set to Never to all restored classes.

2024-09-23 08:43 UTC, SimonZhao888 commented
> Type 'System.Windows.Forms.FileDialogCustomPlace'
> Type 'System.Windows.Forms.FileDialogCustomPlacesCollection'

These 2 members have been moved to System.Windows.Forms.Primivives, not been removed.

2024-09-23 17:15 UTC, Tanya-Solyanik commented
> Type 'System.Windows.Forms.FileDialogCustomPlace'
> Type 'System.Windows.Forms.FileDialogCustomPlacesCollection

You are right, good point!

2024-09-23 17:21 UTC, Tanya-Solyanik commented
Tests are failing because the newly re-added accessible object should be excluded from AccessibleObject_RuntimeId_IsOverriden_TestData

2024-09-23 17:44 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +|  __`WFDEV006`__ | `DataGrid` has been deprecated. Use `DataGridView` instead. |
I re-read the guidance - https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/better-obsoletion.md#goalsand it seems that we don't have to have obsoletion ID per Type, instead a single obsoletion ID should cover the technology. In fact, you already have the same message for all related classes.
I suggest that all classes related to DataGrid (line 43-58) have one ID; all Menu-related classes (59-63) have a single ID, StatusBar classes have a single ID, and ToolBar classes a single ID.

2024-09-23 18:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/MenuItemCollection.cs
> +#pragma warning restore CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
We had recently changed this pattern to have to explanation comment only at the suppression site, espessially when the disable and restore are so close to each other.
```suggestion
#pragma warning restore CS8767
```

2024-09-23 18:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridPreferredColumnWidthTypeConverter.cs
> +#pragma warning disable CS0114 // Member hides inherited member; missing override keyword
In this case it will be sufficient to disable this warning in the beginnin of the file and restore in the end.

2024-09-23 18:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridTextBoxColumn.cs
> +    protected internal override void Paint(Graphics g1,
Consider re-ordering this file so that all Paint methods are together.

2024-09-23 18:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/HitTestInfo.cs
> +#pragma warning restore CS0114 // Member hides inherited member; missing override keyword
```suggestion
#pragma warning disable CS0114 // Member hides inherited member; missing override keyword
        public bool Equals(object obj) => throw new PlatformNotSupportedException();

        public int GetHashCode() => throw new PlatformNotSupportedException();

        public string ToString() => throw new PlatformNotSupportedException();
#pragma warning restore CS0114
```

2024-09-23 18:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> +override System.Windows.Forms.DataGridBoolColumn.Abort(int rowNum) -> void
We don't need to restore the override methods because callsites will resolve to the base class implementations. The code will be binary compatible without the overrides.

2024-09-24 08:26 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> +override System.Windows.Forms.DataGridBoolColumn.Abort(int rowNum) -> void
We have removed all of the override keywords except for the implementation of abstract methods.
Here is the abstract methods list:
```
abstract void Abort(int rowNum);
abstract bool Commit(CurrencyManager dataSource, int rowNum);
abstract void Edit(CurrencyManager source,
        int rowNum,
        Rectangle bounds,
        bool readOnly,
        string displayText,
        bool cellIsVisible);
abstract Size GetPreferredSize(Graphics g, object value);
abstract int GetMinimumHeight();
abstract int GetPreferredHeight(Graphics g, object value);
abstract void Paint(Graphics g1,
        Graphics g,
        Rectangle bounds,
        CurrencyManager source,
        int rowNum);
abstract void Paint(Graphics g,
        Rectangle bounds,
        CurrencyManager source,
        int rowNum,
        bool alignToRight);

```

2024-09-24 21:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> +override System.Windows.Forms.DataGridBoolColumn.Abort(int rowNum) -> void
Sorry about the confusion, we should remove all override *methods*, not the keyword `override` (except for abstract virtual methods that are not implemented on the base class). In the case of abstract virtual methods, please keep them and keep the keyword `override`.

2024-09-24 21:22 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/HitTestInfo.cs
> +#pragma warning restore CS0114 // Member hides inherited member; missing override keyword
Actually this was a wrong suggestion. There should be declared as override methods.

2024-09-24 21:23 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/DataGrid/DataGridPreferredColumnWidthTypeConverter.cs
> +#pragma warning disable CS0114 // Member hides inherited member; missing override keyword
This was a wrong suggestion, these methods should be mostly removed, unless they are abstract

2024-09-25 00:16 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Obsolete/ContextMenu/ContextMenu.cs
> +    EditorBrowsable(EditorBrowsableState.Never)]
Looks like you didn't push this change...

2024-10-01 19:13 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> +override System.Windows.Forms.DataGridBoolColumn.Abort(int rowNum) -> void
>We have removed all of the override keywords except for the implementation of abstract methods.

This is correct. We should keep overrides of these methods.

2024-10-02 17:21 UTC, JeremyKuhne commented
We should have a project that builds against .NET Framework with the removed types that we can write tests against. See the BuildAssist project for how we're doing this for the AxHosts project.

2024-10-02 17:23 UTC, JeremyKuhne commented on docs/list-of-diagnostics.md
> +|  __`WFDEV005`__ | `ContextMenu` has been deprecated. Use `ContextMenuStrip` instead. |
Perhaps `is not supported` is better than `deprecated`.

2024-10-02 17:40 UTC, JeremyKuhne requested changes
We should have at least some basic smoke tests where we try to run code built against .NET Framework with these removed types. The BuildAssist project has the pattern for doing this- it builds the AxHosts.csproj against .NET Framework.

Something similar to this:

``` C#
// In the .NET Framework dll project
public static class TestUnsupportedTypes
{
   public static void CreateContextMenu()
   {
      // Create the ContextMenu
   } 
}

// In our normal tests:
[Fact]
public void ContextMenu_CreateFromFrameworkAssembly_ThrowsNotSupported()
{
   // See that calling CreateContextMenu throws the expected exception.
}
```

The unit tests you've already written are good. Doing this as well will give us both basic sanity and the ability to add more specific regression tests if we need to in the future.

2024-10-02 20:16 UTC, Tanya-Solyanik commented
@JeremyKuhne do you think we need an integration test as is implemented now? I'm not sure it's useful

2024-10-02 20:17 UTC, Tanya-Solyanik commented on src/Common/src/Obsoletions.cs
> +    internal const string ContextMenuMessage = $"{nameof(ContextMenu)} has been deprecated. Use {nameof(ContextMenuStrip)} instead.";
I'll trust you with this recommendation :)

2024-10-02 20:30 UTC, JeremyKuhne commented
> @JeremyKuhne do you think we need an integration test as is implemented now? I'm not sure it's useful

I'm not sure I see value in the current integration test over the current unit tests, so no.

2024-10-04 00:47 UTC, JeremyKuhne approved these changes

2024-10-10 23:47 UTC, lonitra reviewed
Overall LGTM, would it be useful to add some sort of readme file under the controls/unsupported folder that explains why these are added even though they are unsupported for future references?

2024-10-10 23:47 UTC, lonitra commented on src/System.Windows.Forms/tests/AxHosts/AxHosts.cs
> +[DesignerCategory("Default")]
Why is this change needed?

2024-10-10 23:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AxHosts/AxHosts.cs
> +[DesignerCategory("Default")]
To open this file with a double click in the solution explorer. Because this is a form, designer tries to open this file but fails to resolve Winforms types from a project to project reference and fails.

2024-10-11 16:15 UTC, lonitra submitted a review, later dismissed
🚀

2024-12-06 05:38 UTC, LeafShi1 commented
@Tanya-Solyanik Lonitra approved this PR, can it be merged now or does it need further changes?

2024-12-06 05:38 UTC, LeafShi1 submitted a review, later dismissed

2024-12-06 22:55 UTC, Tanya-Solyanik commented
>@Tanya-Solyanik Lonitra approved this PR, can it be merged now or does it need further changes?

It needs further changes

2025-01-21 18:06 UTC, Tanya-Solyanik commented
To the copilot comment - 
> Add a comment for the AddRange method to maintain consistency with the rest of the code.

I'm not adding comments to re-added methods inside the re-added types.

2025-01-22 22:29 UTC, JeremyKuhne approved these changes
Looks good!

2025-01-22 23:26 UTC, Tanya-Solyanik commented
Fixes https://github.com/dotnet/winforms/issues/3783



Add controls removed in NET3.1 Back to .NET10 for binary compatibility.

None of the re-added types can be constructed, all constructors throw new PlatformNotSupportedException(), default constructors are suppressed by introducing throwing public constructors if needed.
All attributes that have been present on the .NET Framework types, are preserved, as they are accessible by reflection.
All re-introduced types are decorated with [EditorBrowsable(EditorBrowsableState.Never)] attribute that hides them from the intellisense. Type names can be typed in by the developer manually and intellisense would show the same members as it did for .NET Framework projects.
All re-introduced types are decorated with the ObsoleteAttribute that results in a compile time warning. All types share a single deprecation warning Id, to simplify suppression, but have different explanation messages.
All re-introduced types are decorated with [Browsable(false)] attribute to not show custom control properties of these types in the property browser.
All public members are re-introduced with their metadata, except for the private attributes.
Members inherited from the base classes (Control, for example) are not re-introduced even if they had been overridden in the past because they are not required for binary compatibility, unless they are decorated with different attributes.
Members that are re-added to the existing types (Form and Control) are returning defaults or doing nothing.
Non-void public or protected instance members on the restored types throw null, not the PlatformNotSupportedException to save space.
Void public or protected instance members do nothing.
Public or protected fields return default values.
Nullability is disabled for all re-added classes, structs and delegates for compatibility with the .NET Framework.

2025-01-22 23:26 UTC, merged