Fix ComponentModel.Design.serialization not support .Net8
dotnet/winforms pull request #10937
Opened 2024-02-23 06:54 UTC by SimonZhao888

Fixes #10425

## Proposed changes

- 
- 
- 

## Customer Impact

- 
- 

## Regression? 

- Yes / No

## Risk

-

## Screenshots 

### Before

### After

## Test methodology 

- 
- 
- 

## Accessibility testing  

 

## Test environment(s) 

-

2024-02-26 08:07 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +            // info.AddValue(AssembliesKey, AssemblyNames);
Hi @Tanya-Solyanik ,
When we debug these changes with customer's project, if we don't comment out this line, the process will throw an error:
`"Type 'System.Reflection.AssemblyName' in Assembly 'System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable."`
![image](https://github.com/dotnet/winforms/assets/133954995/7212d21f-5869-40ad-bf9b-c138d67c786b)
I'm not clearly how to solve this problem, can you give us some advice?

2024-02-26 20:55 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +            // info.AddValue(AssembliesKey, AssemblyNames);
@SimonZhao888  - your test application should enable BinaryFormatter in the project file, or in unit test use BinaryFormatterScope. This workitem is about temporarily enabling old BinaryFormatter scenarios until we have an alternative serialization method in place (https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat).

We can't make AssemblyName class serializable because we don't own it, but we can serialize different pieces of information that would replace AssemblyName. 
1. I would investigate if, for the purposes of this scenario, we can replace AssemblyName with a new `AssemblyNameInfo` class that contains serializable and non-obsolete properties of AssemblyName class
ContentType
CultureName (not the CultureInfo)
AssemblyNameFlags
FullName
Name
Version

When serializing, we create this new class and serialize it instead of assemblyName, when deserializing we deserialize this class and then create AssemblyName class from it.

2. Maybe all we need to support this scenario is Assembly.Location or Assembly.FullName - something that allows us to load this assembly. Experiment with the sample app from the bug when that app is retargetted to net481. Note that to properly test that you must add different types(start with all control types) to the app.

2024-02-27 18:24 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +        public AssemblyNameInfo(AssemblyContentType contentType,
Consider adding constuctor that takes AssemblyName.

2024-02-28 00:25 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +        public AssemblyNameInfo(AssemblyContentType contentType,
Yes, like this, we can also set other properties to private.
![image](https://github.com/dotnet/winforms/assets/133954995/aa2b7c36-24da-4843-908d-b1c6083c5394)

2024-03-01 22:36 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.AssemblyNameInfo.cs
> +// Licensed to the .NET Foundation under one or more agreements.
Remove the duplicate header 😄

2024-03-01 22:36 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ExceptionCollection.cs
> +        throw new PlatformNotSupportedException();
Isn't this constructor required to restore the scenario?

2024-03-01 22:36 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +        Assert.Throws<NotSupportedException>(() => formatter.Serialize(stream, collection));
If we are enablin gthe serialization store scenario, we should re-write this test.

2024-03-05 02:03 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ExceptionCollection.cs
> +        throw new PlatformNotSupportedException();
If we don't add this constructor, there will throw an error in our build.cmd.

2024-03-05 23:48 UTC, Tanya-Solyanik commented
@LeafShi1 @Epica3055 @ricardobossan  - please review this change, specifically compare this code to the InProc designer in the VS repo

2024-03-13 01:09 UTC, ricardobossan commented
> @LeafShi1 @Epica3055 @ricardobossan - please review this change, specifically compare this code to the InProc designer in the VS repo

@Tanya-Solyanik The changes seem very familiar to those existing in InProc designer. For exemple, modified code for [ExceptionCollection in this PR](https://github.com/dotnet/winforms/pull/10937/files#diff-dc4b46b82fb9ffb51dde3794d0d877e9a09d93dd7f4cc0b8644c3ae22de5b610) seems very similar to InProc, in https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsip/Designer/Host/ExceptionCollection.cs

2024-03-14 07:08 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +            Assert.NotSame(deserialized.Exceptions, deserialized.Exceptions);
Assert.Equal is used to check if the contents of the values are equal, while Assert.NotSame is used to check if the variables reference the same object. When comparing value types, you should use Assert.Equal, while when comparing reference types, you can use Assert.AreSame to check if they have the same reference

2024-03-14 07:16 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +        Assert.Throws<ArgumentNullException>(() => collection.GetObjectData(null, new StreamingContext()));
This is because we have updated this method 
https://github.com/dotnet/winforms/blob/e85479c04fb618d1316a3ef9b4aae62f216e5b96/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ExceptionCollection.cs#L37-L42

2024-03-14 22:41 UTC, JeremyKuhne requested changes
Added a couple comments

2024-03-14 22:41 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs
> +        using BinaryFormatterScope formatterScope = new(enable: false);
It would be good to add tests that validate the serialization of the SerializationStore

2024-03-14 22:41 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +    public void ExceptionCollection_Serialize_Deserialize_Success(ArrayList exceptions)
It would also be good to have tests that try to deserialize `ExceptionCollection` data that was serialized in .NET Framework.

2024-03-15 09:01 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +    public void ExceptionCollection_Serialize_Deserialize_Success(ArrayList exceptions)
I tried to add this test case, but it doesn't pass the test. It throws one error as:
`System.Runtime.Serialization.SerializationException : Invalid BinaryFormatter stream.
---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
-------- System.InvalidCastException : Object must implement IConvertible.`

1. I serialized the `ExceptionCollection `data in .NET Framework, and save them in a txt file.
2. Use .Net Core project to read the file to MemoryStream, and deserialize the stream, but it throws the error.
3. When I use .Net FrameWork project to read the file and deserialize the `ExceptionCollection` data, it passed.
4. .Net Core project also deserialize its own generated serialization file.

2024-03-15 09:02 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +    public void ExceptionCollection_Serialize_Deserialize_Success(ArrayList exceptions)
I tried to add this test case, but it doesn't pass the test. It throws one error as:
`System.Runtime.Serialization.SerializationException : Invalid BinaryFormatter stream.
---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
-------- System.InvalidCastException : Object must implement IConvertible.`

1. I serialized the `ExceptionCollection `data in .NET Framework, and save them in a txt file.
2. Use .Net Core project to read the file to MemoryStream, and deserialize the stream, but it throws the error.
3. When I use .Net FrameWork project to read the file and deserialize the `ExceptionCollection` data, it passed.
4. .Net Core project also deserialize its own generated serialization file.

2024-03-19 07:54 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
>          Assert.Throws<ArgumentException>(() => new ExceptionCollection(exceptions));
Done, for other test file, we will do it in other PR.

2024-03-19 22:22 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +            collection.Exceptions.Should().BeEquivalentTo(exceptions);
Why do you use `BeEquivalentTo` instead of `Be`

2024-03-19 22:22 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +    public void ExceptionCollection_Serialize_Deserialize_Success(ArrayList exceptions)
I would guess that round trip will not work because in Core we are can't serialize assembly and instead we are serializing our own "proxy" AssemblyInfo. 
@JeremyKuhne  - is roundtripping the goal in this work? The specific request was about enabling the same scenario in Core as was possible in the Framework.

2024-03-19 22:39 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +    public void ExceptionCollection_Serialize_Deserialize_Success(ArrayList exceptions)
We likely changed the fields involved and we need to fix that by either putting the fields back the way they were or implementing `ISerializable` to put the data out in the same format.

2024-03-19 22:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.AssemblyNameInfo.cs
> +                throw new NotImplementedException();
I'm surprised that this works. I would expect that deserialization code invokes this constructor, and it should be implemented fully.

2024-03-19 22:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.LocalDesignerSerializationManager.cs
> +                    names[idx++] = new AssemblyName(assemblyNameInfo.FullName);
When initializing AssemblyName, please use all the data available in AssemblyNameInfo

2024-03-19 22:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.LocalDesignerSerializationManager.cs
> +                AssemblyName[] names = new AssemblyName[_store.AssemblyNameInfos!.Length];
Is it possible to get rid of the null-forgiving operator?

2024-03-19 22:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            ArgumentNullException.ThrowIfNull(info);
We will not be able to serialize this class unless this constructor is fully implemented... Could you please share your test samples, or add them to the WinformsControlsApp?

2024-03-19 22:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +    internal sealed class CodeDomComponentSerializationState : ISerializable
Please move this class to a dedicated file. Preferable in a new PR that you will merge before merging this one.

2024-03-19 22:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerException.cs
> +        ArgumentNullException.ThrowIfNull(info);
you probably need this implementation to fully support design time scenarios

2024-03-19 23:12 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.LocalDesignerSerializationManager.cs
> +    internal sealed partial class CodeDomSerializationStore
Is making this internal only being done for tests? We should rely on reflection of TestAccessor to access internals rather than risk introducing unintended coupling in the product code.

2024-03-19 23:23 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +    public void ExceptionCollection_Serialize_Deserialize_Success(ArrayList exceptions)
Because this type is private and `AssemblyName` and `CultureInfo` are no longer serializable there is no easy way to make it compatible with Framework serialized data. That being the case I think it is fine to deviate, the one thing I would do is check in the serialization constructor to see if the data is in the old format (look for the type of one of the records) and throw a `NotSupportedException` with helpful text. There should be comments in the code that copy these details.

2024-03-19 23:39 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            ArgumentNullException.ThrowIfNull(info);
OK, I will add the test apps to WinformsControlsApp.

2024-03-19 23:54 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.AssemblyNameInfo.cs
> +                throw new NotImplementedException();
This class was added to replace the AssemblyName class, which throws an exception when serialized.

2024-03-20 01:07 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.AssemblyNameInfo.cs
> +                throw new NotImplementedException();
But we want to be able to serialize this class as part of the serialized representation of the CodDomSerializationStore.

2024-03-20 01:08 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            ArgumentNullException.ThrowIfNull(info);
Actually unit tests might be easier and more usefull

2024-03-20 01:47 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.AssemblyNameInfo.cs
> +                throw new NotImplementedException();
Got it.

2024-03-25 06:22 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
> +            collection.Exceptions.Should().BeEquivalentTo(exceptions);
When the `ExceptionCollection `is not null, either  `Be` or `BeSameAs` fails, only `BeEquivalentTo` can be executed via the test case.

2024-03-26 00:19 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomComponentSerializationState.cs
> +        public void GetObjectData(SerializationInfo info, StreamingContext context)
Got it!

2024-03-26 00:41 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomComponentSerializationState.cs
> +    internal sealed class CodeDomComponentSerializationState : ISerializable
Add test for this class.

2024-03-26 00:41 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
>      public void ExceptionCollection_GetObjectData_ThrowsPlatformNotSupportedException()
rename this test to match the exception we test for.

2024-03-26 00:41 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs
> +
remove this blank line

2024-03-26 00:41 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomSerializerExceptionTests.cs
> +        Assert.Throws<ArgumentNullException>(() => exception.GetObjectData(null, new StreamingContext()));
This test should be testing successful rounds-trip in Core and deserialization of a .NET framework exception.

2024-03-26 08:29 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomSerializerExceptionTests.cs
> +        Assert.Throws<ArgumentNullException>(() => exception.GetObjectData(null, new StreamingContext()));
If the params of SerializationInfo is null, it will throw ArgumentNullException.
I have extended the test case.

2024-03-26 08:30 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs
> -            Assert.Throws<SerializationException>(() => formatter.Serialize(stream, store));
I've reverted this change and tweaked the code.

2024-03-26 08:31 UTC, SimonZhao888 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs
> +        obj.MoveNext();
Done.

2024-03-26 18:00 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +            _objects = [];
Serialization constructor should initialize fields by extracting data from SerializationInfo, `info.GetValue`  https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2229#example

2024-04-04 22:58 UTC, closed without merging