Add test "ToolStrip_Font_ApplyParentFontToMenus_GetReturnFont_SameAsA…
dotnet/winforms pull request #10975
Opened 2024-03-01 03:14 UTC by LeafShi1

Related PR #10906 

Add test for switch "ApplyParentFontToMenus"

2024-03-02 02:04 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
> +        // Generally at this stage NativeWindow.AnyHandleCreated=true, we won't be able to set the font.
It's ok to test this scenario in the interactive test - `WinformsControlsApp`

2024-03-04 06:42 UTC, LeafShi1 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
> +        // Generally at this stage NativeWindow.AnyHandleCreated=true, we won't be able to set the font.
In the Unit test, the font of the Application cannot affect the font of the Form and the font of the control. The test for switch "ApplyParentFontToMenus" has been added to the WinformsControlsTest App

2024-03-04 18:05 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +            if (switchName == ApplyParentFontToMenusSwitchName)
Do we want this switch to be only available in .NET 9? If so I think we need to place this under the if statement below.

2024-03-04 20:22 UTC, Tanya-Solyanik reviewed
> Do we want this switch to be only available in .NET 9? If so I think we need to place this under the if statement below. 

We don't have to. This is a good point though, this switch should be available after SetApplicatinFont API had beed introduced

2024-03-04 20:47 UTC, Tanya-Solyanik requested changes

2024-03-04 20:47 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.cs
> +        LocalAppContextSwitches.SetLocalAppContextSwitchValue(LocalAppContextSwitches.ApplyParentFontToMenusSwitchName, true);
Had you tried adding a runtimeconfig.json file? I would add the default values for other switches for easy experiments:

{
  "configProperties": {
    "System.Windows.Forms.AnchorLayoutV2": false,
    "System.Windows.Forms.ApplyParentFontToMenus": true,
    "System.Windows.Forms.DataGridViewUIAStartRowCountAtZero": false,
    "System.Windows.Forms.DoNotCatchUnhandledExceptions": true,
    "System.Windows.Forms.EnableMsoComponentManager": false
    "System.Windows.Forms.NoClientNotifications": false,
    "System.Windows.Forms.ScaleTopLevelFormMinMaxSizeForDpi": false,
    "System.Windows.Forms.ServicePointManagerCheckCrl": false,
    "System.Windows.Forms.TrackBarModernRendering": false,
  }
}

2024-03-04 20:47 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Program.cs
> +Application.SetDefaultFont(new Font(new FontFamily("Microsoft Sans Serif"), 8.25F, FontStyle.Regular, GraphicsUnit.Point, 0));
the project file is already setting ApplicationFont.

2024-03-04 20:55 UTC, Tanya-Solyanik commented
> > Do we want this switch to be only available in .NET 9? If so I think we need to place this under the if statement below.
> 
> We don't have to. This is a good point though, this switch should be available after SetApplicatinFont API had beed introduced

Never mind, this switch has 2 effects - inherit Font from the parent container if available or from the Application object. Parent container font is applicable to all versions. We don't have to special-case the switch availability, we just use the same default value everywhere, if the developer wants the switch ON, they have to opt-in.

2024-03-04 21:01 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.cs
> +        LocalAppContextSwitches.SetLocalAppContextSwitchValue(LocalAppContextSwitches.ApplyParentFontToMenusSwitchName, true);
Also it would be nice to have another toolstrip with a custom font to show that custom font is preserved.

2024-03-05 23:37 UTC, Tanya-Solyanik submitted a review, later dismissed

2024-03-05 23:38 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +            if (switchName == ApplyParentFontToMenusSwitchName)
Do we still need this change?

2024-03-06 03:42 UTC, LeafShi1 commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +            if (switchName == ApplyParentFontToMenusSwitchName)
I don't think this is necessary, I will remove this.

2024-03-06 03:46 UTC, SimonZhao888 approved these changes

2024-03-07 01:34 UTC, merged