[Proposal] Provide DarkMode Theming
dotnet/winforms pull request #10985
Opened 2024-03-03 10:19 UTC by KlausLoeffelmann

Work in Progress.

- [x] New API for DarkMode control on Application.
- [x] New API for DarkMode control on Control.
- [x] Mapping SystemColors -> Application.SystemColors/patch for DarkMode
- [x] New API for controlling Form Titelbar Color/BorderColor/TextColor
- [x] Scrollbars for Form/ScrollableControl/ListView/TreeView/ListBox/ComboBox
- [x] Radio Button
- [x] CheckBox
- [x] ComboBox DarkMode
- [x] Button DarkMode
- [x] TreeView DarkMode
- [x] ListView DarkMode
- [x] TextBox/RichtextBox
- [x] Strips - Still have issues, but the basics work fine!
- [ ] Groupbox Caption
- [ ] ColumnHeaders ListView Forground Text
- [ ] ListView Forground Group Caption (might be an issue to get it brighter).
- [ ] TabControl (Scrollbars are working in DarkMode)
- [ ] MonthCalendar (We should have a new one altogether - that thing is a visual A11Y challenge.)
- [ ] DateTimePicker

![image](https://github.com/dotnet/winforms/assets/9663150/6a53ec53-c1e5-451e-ab57-bdf7ae19d259)

2024-03-04 03:00 UTC, elachlan commented
Test failures are caused by white space analyzer errors.
```
##[error]src\System.Windows.Forms\src\System\Windows\Forms\Controls\ToolStrips\StatusStrip.cs(32,1): error SA1028: (NETCORE_ENGINEERING_TELEMETRY=Build) Code should not contain trailing whitespace (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md)
D:\a\_work\1\s\src\System.Windows.Forms\src\System\Windows\Forms\Controls\ToolStrips\ToolStripManager.cs(573,1): error SA1028: Code should not contain trailing whitespace (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md) [D:\a\_work\1\s\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
##[error]src\System.Windows.Forms\src\System\Windows\Forms\Controls\ToolStrips\ToolStripManager.cs(573,1): error SA1028: (NETCORE_ENGINEERING_TELEMETRY=Build) Code should not contain trailing whitespace (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md)
D:\a\_work\1\s\src\System.Windows.Forms\src\System\Windows\Forms\Controls\ToolStrips\ToolStripManager.cs(575,1): error SA1028: Code should not contain trailing whitespace (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md) [D:\a\_work\1\s\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
##[error]src\System.Windows.Forms\src\System\Windows\Forms\Controls\ToolStrips\ToolStripManager.cs(575,1): error SA1028: (NETCORE_ENGINEERING_TELEMETRY=Build) Code should not contain trailing whitespace (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md)
```

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    protected virtual bool IsDarkModeEnabled
[maintenability] please observe the existing file organisation and add new memebers in the lexicographical order.

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    or Form))
[maintenability] please order this list as well or provide clear guidance how this list is to be maintained

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    private static unsafe void PrepareDarkMode(HWND hwnd, bool darkModeEnabled)
```suggestion
    private static unsafe void PrepareDarkMode(HWND hwnd, BOOL darkModeEnabled)
```

...and perfrom the cast at the callsite. This makes the intent obvious.

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    private static unsafe void PrepareDarkMode(HWND hwnd, bool darkModeEnabled)
Not sold on the method name either, it doesn't feel like it belongs to the vocabulary of this codebase (i.e., it's not very customary to call methods "PerpareXyz" here). It's probably more appropriate to call this `SetDarkMode`.

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.cs
> +            qaContainer.colorFore = GetOleColorFromColor(Application.SystemColors.WindowText);
This change looks like noise, and it makes viewing the actual change much more difficult. Can this be reverted?

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +        private const string DarkModeKey = "AppsUseLightTheme";
Misindented?

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
> +            _ = PInvoke.SetWindowTheme(HWND, "DarkMode_Explorer", null);
`DarkMode_Explorer` is repeated in few places (same with `Explorer` for that matter). It makes sense to define constants for these.

Ditto for other theme related constants.

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.cs
> +            switch (renderMode)
IMO the pattern matching version was easier to read.

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DarkModeSettings.cs
> +namespace System.Windows.Forms
For the new files it's worth considering using top level namespaces.
```suggestion
namespace System.Windows.Forms;
```

2024-03-04 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +    public enum WindowCornerPreference
Move to own file please

2024-03-05 07:44 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    protected virtual bool IsDarkModeEnabled
![image](https://github.com/dotnet/winforms/assets/9663150/2a3ad7b1-16b6-4b0e-9366-4f3d20b02bb3)

2024-03-05 07:47 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    private static unsafe void PrepareDarkMode(HWND hwnd, bool darkModeEnabled)
It's not a public method?

2024-03-05 07:52 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    public static bool SetDefaultDarkMode(DarkMode darkMode) => darkMode switch
I would not go with `ColorSomething` in the name, since my language feeling would imply theming. Per our first internal discussion, this should not go in that direction, as we would most likely overpromise.

2024-03-05 07:54 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Theming/ForcedLightThemedSystemColors.cs
> +    internal class ForcedLightThemedSystemColors : ThemedSystemColors
Good question! 
I wanted to capture the palette settings for the light mode somewhere, so, if folks want to experiment with deriving/inversing them, not each of us need to do that investigation in a silo. I'll add a comment what's this for!

2024-03-05 08:31 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.cs
> +            switch (renderMode)
Actually, this was a merge victim. I wrote the code before this was refactored, I think.

2024-03-05 08:32 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.cs
> +            qaContainer.colorFore = GetOleColorFromColor(Application.SystemColors.WindowText);
No, because it would change the meaning? Or am I missing something?

2024-03-05 08:35 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    or Form))
I never spent thought about sorting this, since I was in the process of experimenting with what controls do have what effect.

But I think this list maybe should be sorted by inheritance level? 
Does that make sense?

2024-03-06 02:09 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    private static unsafe void PrepareDarkMode(HWND hwnd, bool darkModeEnabled)
It is part of the codebase, and it needs to be maintained. The more cohesive the codebase is, the less mental tax is.

2024-03-06 02:15 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.cs
> +            qaContainer.colorFore = GetOleColorFromColor(Application.SystemColors.WindowText);
Oh, I totally missed that there's a new property at the `Application` type. This is not very good. It'd be better if the new property name wasn't clashing with the existing type name as it _will_ introduce clashes in user code that will need to be reconciled by introducing aliases. This is never pretty.

2024-03-06 02:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    or Form))
I'm not sure an average Igor "the Windows Forms developer" would know what right inheritance level order is, but I may be mistaken. Personally, I'd sort this alphabetically, as this is the easiest option.

2024-03-07 19:13 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    private static unsafe void PrepareDarkMode(HWND hwnd, bool darkModeEnabled)
I'll take a look.

2024-03-19 03:06 UTC, AraHaan commented
I personally do not like the extensive usage of ``SystemColor`` in this change. I would prefer the ability to instead pass in (optionally) a type derived from ``ProfessionalColorTable`` instead of that. This way not only does it integrate the the existing ``Renderer`` types in the API, but also could be used to theme everything as well. Say for example one wants to be able to have a switch from ``Light``, ``Dark``, and ``Pink`` mode in their application. With that change they can and besides if we are already exploring theming support might as well invest a little bit extra work to allow custom app defined themes as well :smile:. I have such an application where such a change would eliminate thousands of lines of code where I have to manually draw everything or make "fake" versions of controls within winforms today using picture boxes and svg images that I manipulate the colors on using System.Drawing.Common apis. Of which is a pain in the butt to maintain.

2024-03-20 23:27 UTC, KlausLoeffelmann commented
Please read my comments on theming in the respective issue.

Thanks!

2024-04-23 16:43 UTC, AraHaan commented
I still would prefer if the changes were ONLY made to ProfessionalColorTable and for that to detect if it *should* use dark mod or not with a subclass of it that is meant for applications who want to *always* use the dark colors in their application for everything (including the scrollbars and non-client area stuffs. Also with it using a user provided ``ProfessionalColorTable`` instance theey could also define their own themes with their own colors as well and pass it in to say ``Application.Theme.set(ProfessionalColorTable)`` (and internally inside of ``Control.WndProc`` it will always check ``Application.Theme.get`` to obtain the current ``ProfessionalColorTable`` instance that is then used to update it's ``Paint``.

2024-04-27 17:34 UTC, AraHaan commented
Please migrate from ``Application.SystemColors`` in this change to prefer application registered and provided ``ProfessionalColorTable`` subclasses. I also have existing code that provides dark version color of the items inside of that as well.

Also it would allow for me to have very minimal changes to my code to allow using it ***globally*** as well as remove any code that needed to be provided to manually dark theme my program (most of it copied from ShareX btw).

https://github.com/Elskom/Els_kom_new/blob/main/Els_kom/Themes/DarkColorTable.cs
https://github.com/Elskom/Els_kom_new/blob/main/Els_kom/Themes/Theme.cs

Basically applications can then do this and register it using ``Application.SetColorTable(ProfessionalColorTable)`` and then winforms would use that color table globally from then on *until* the user tells it to change color tables which would cause a repaint on everything according to the new color table. Also would need a new public method of ``Application.GetColorTable`` (or expose it as a property) and it would do the same thing if not *BETTER* than the *SystemColors* option. Besides they get used for special coloring on ``ContextMenuStrips``, etc anyways so why not extend it to work with all of Windows Forms for free (along with non-client area painting).

2024-04-29 23:29 UTC, RussKie commented
> I am starting to think that with dark theme support, it might be better to have it mature a bit more and have it be slated for .NET 10, also with more of that time being invested would mean a much deeper integrated dark theme support and with it perhaps support for all controls + the default scrollbars in the `ScrollableControl`s all based on the user's provided `ProfessionalColorTable` that gets registered into the `Application` class in WinForms.

I don't think there's a reason to delay the API, if those are believed to be usable. Those API, however, must be marked as [`experimental`](https://learn.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.experimentalattribute) ([spec](https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-12.0/experimental-attribute)). This would allow to collect valuable feedback, and make any changed in the following release (**including** the options to completely rewrie or remove the API).

2024-04-29 23:29 UTC, RussKie commented
> Please migrate from `Application.SystemColors` in this change to prefer application registered and provided `ProfessionalColorTable` subclasses. I also have existing code that provides dark version colors of the items inside of that as well.
> 
> Also it would allow for me to have very minimal changes to my code to allow using it _**globally**_ as well as remove any code that needed to be provided to manually dark theme my program (most of it copied from ShareX btw).
> 
> [Elskom/Els_kom_new@`main`/Els_kom/Themes/DarkColorTable.cs](https://github.com/Elskom/Els_kom_new/blob/main/Els_kom/Themes/DarkColorTable.cs?rgh-link-date=2024-04-27T17%3A34%3A06Z) [Elskom/Els_kom_new@`main`/Els_kom/Themes/Theme.cs](https://github.com/Elskom/Els_kom_new/blob/main/Els_kom/Themes/Theme.cs?rgh-link-date=2024-04-27T17%3A34%3A06Z)
> 
> Basically applications can then do this and register it using `Application.SetColorTable(ProfessionalColorTable)` and then winforms would use that color table globally from then on _until_ the user tells it to change color tables which would cause a repaint on everything according to the new color table. Also would need a new public method of `Application.GetColorTable` (or expose it as a property) and it would do the same thing if not _BETTER_ than the _SystemColors_ option. Besides they get used for special coloring on `ContextMenuStrips`, etc anyways so why not extend it to work with all of Windows Forms for free (along with non-client area painting).

💯

2024-05-04 06:11 UTC, KlausLoeffelmann commented
I agree with Igor here.

And again: we have no plans to go down the theming route. That has way too much potential to mess with existing APIs and screw up existing theming concepts.

With Application.SystemColors you have an easy way to implement DarkMode, but you can also easily break the Ambient Ancestor DarkMode chain at any point and take over manually with your own palette.

Or just opt out of it at the beginning, if you think your third party's theming is doing a visually more compatible job for your target audience.

Thanks

Klaus

2024-05-05 20:51 UTC, AraHaan commented
> I agree with Igor here.
> 
> And again: we have no plans to go down the theming route. That has way too much potential to mess with existing APIs and screw up existing theming concepts.
> 
> With Application.SystemColors you have an easy way to implement DarkMode, but you can also easily break the Ambient Ancestor DarkMode chain at any point and take over manually with your own palette.
> 
> Or just opt out of it at the beginning, if you think your third party's theming is doing a visually more compatible job for your target audience.
> 
> Thanks
> 
> Klaus

I am referring to very simple themese provided only by specific colors using the existing ``ProfessionalColorTable`` class and any subclasses. As it would be basically the same as the ``SystemColors`` option, however more compatible with existing API as then they would need to call 1 or 2 new functions in ``Application`` (or a single property with ``get; set;``) and it being much like how it would be to go into Windows settings itself and "creating your own color scheme" by changing all of the system colors inside of a "theme" (not really a theme much it is just altered colors).

2024-05-10 19:17 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    or Form))
@KlausLoeffelmann 

You need to add apply "DarkMode_Explorer" Theme to MdiClient Control also


```
  if (IsDarkModeEnabled)
  {
      if (this is

          // Controls with 4 levels of inheritance, sorted alphabetically by type name
          DomainUpDown         // Inherits from UpDownBase, ContainerControl, ScrollableControl, Control
          or NumericUpDown     // Inherits from UpDownBase, ContainerControl, ScrollableControl, Control

          // Controls with 3 levels of inheritance, sorted alphabetically by type name
          or CheckedListBox    // Inherits from ListBox, ListControl, Control
          or Form              // Excluded - too invasive.
          or FlowLayoutPanel   // Inherits from Panel, ScrollableControl, Control
          or SplitContainer    // Inherits from ContainerControl, ScrollableControl, Control
          or TabPage           // Inherits from Panel, ScrollableControl, Control
          or TableLayoutPanel  // Inherits from Panel, ScrollableControl, Control

          // Controls with 2 levels of inheritance, sorted alphabetically by type name
          // or ComboBox       // Excluded - directly handled.
          or ListBox           // Inherits from ListControl, Control

          or Button            // Inherits from ButtonBase, Control
          or CheckBox          // Inherits from ButtonBase, Control
          or MaskedTextBox     // Inherits from TextBoxBase, Control
          or Panel             // Inherits from ScrollableControl, Control
          or RadioButton       // Inherits from ButtonBase, Control
          or RichTextBox       // Inherits from TextBoxBase, Control
          or TextBox           // Inherits from TextBoxBase, Control
          or HScrollBar        // Inherits from ScrollBar, Control
          or VScrollBar        // Inherits from ScrollBar, Control

          // Base classes and controls with direct inheritance from Control, sorted alphabetically by type name
          or ButtonBase        // Inherits from Control
          or DateTimePicker    // Inherits from Control
          // or GroupBox       // Inherits from Control directly, but behaves like a container
          or Label             // Inherits from Control
          or LinkLabel         // Inherits from Label, Control
          // or ListView       // Excluded - directly handled.
          or MonthCalendar     // Inherits from Control
          or PictureBox        // Inherits from Control
          or ProgressBar       // Inherits from Control
          or ScrollableControl // Inherits from Control
          // or TextBoxBase    // Excluded - probably too invasive.
          or TrackBar          // Inherits from Control
          or TreeView          // Inherits from Control
          or UpDownBase
          or MdiClient
          )       // Inherits from Control

      // Base class for all UI controls in WinForms
      // or Control           // Excluded.
      {
          _ = PInvoke.SetWindowTheme(HWND, "DarkMode_Explorer", null);
      }
```
This will Apply Dark Theme to mdi Scrollbar that appear When mdi Child Form move out of MdiClient rectangle

before

![2024-05-10_22-14-07-ezgif com-optimize](https://github.com/dotnet/winforms/assets/12494184/9370e45d-729b-4a50-b7b8-397010be87bd)

after

![2024-05-10_21-57-47-ezgif com-optimize](https://github.com/dotnet/winforms/assets/12494184/bade31e1-ca3b-4243-b6ea-4888954cd2ed)

2024-06-21 17:31 UTC, KlausLoeffelmann commented
> I am referring to very simple "themes" provided only by specific colors using the existing ProfessionalColorTable class and any subclasses. 

I get what you mean and feel you. But there are more implications if we did that, namely: Accessibility.
So, we need to make sure for now, we can adhere without any risks to the requirements for colors and color schemes around A11Y. And for that reason, for this first version of the feature, we cannot open up the theming at this point.

2024-06-23 15:22 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStylesMode.cs
> +    Latest = Version10
If Latest VisualStylesMode will support DarkMode VisualStyleRenderer

2024-06-23 18:09 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    or Form))
Good point!

2024-06-23 18:16 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    private static unsafe void PrepareDarkMode(HWND hwnd, bool darkModeEnabled)
Would `InitializeDarkMode` more appropriate in your opinion?

2024-06-23 18:28 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.cs
> +            qaContainer.colorFore = GetOleColorFromColor(Application.SystemColors.WindowText);
@RussKie: Thinking about this right now. We cannot extend `SystemColors` easily, since this outside of "our" domain. Also, it doesn't seem right, since `SystemColors` does not pick up the dark mode palette. We also agreed that defining/tweaking your own dark mode palette won't be happening, since this goes into the area of theming, and we agreed that's extremely difficult to tackle, since we cannot retro-standardize theming and keeping our 3rd party control vendors in mind and happy. But what's even more important since it's the law: A11Y. We need to make sure, we are ensuring a dark mode color scheme, which has sufficient contrast, and we can establish a standard for that.

So. With that, and then taking also discoverability into account, the idea was to Map the `SystemColors` to `Application.SystemColors` for high contrast and standard theming color settings. But if dark mode is enabled, we take over with a palette which we can control. And again, that would be reflected by `Application.SystemColors`.

Would you think `Application.ApplicationColors` would make more sense?

2024-06-23 18:35 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStylesMode.cs
> +    Latest = Version10
Well, yes and no. It's a "Yes" in principle but a "No" in completely done. That's why I also did not start with Version9. It would set expectation; we couldn't address completely. But. We need to start at one point. 

And also, we need to be prepared to requirements which will demand slightly changed sizes or demands for bigger default margins/paddings due to A11Y changes which will come. 

Does that make sense?

2024-06-24 00:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    private static unsafe void PrepareDarkMode(HWND hwnd, bool darkModeEnabled)
I've got to admit it's been a while since I look at the codebase, but `Initialize` feels more "native" to the codebase.
Thanks for asking.

2024-06-24 01:05 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.cs
> +            qaContainer.colorFore = GetOleColorFromColor(Application.SystemColors.WindowText);
My main concern here was the member name/type name clashes. `Application.ApplicationColors` should addess the issue 👍 
And IMO `ApplicationColors` is better name too - it denotes that the propoerty exposes _application_ colours. Those could be system colours but don't have to be (since a user could make a choice), right?

2024-06-25 05:45 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    private static unsafe void PrepareDarkMode(HWND hwnd, bool darkModeEnabled)
You got it!

2024-06-25 05:47 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.cs
> +            qaContainer.colorFore = GetOleColorFromColor(Application.SystemColors.WindowText);
Yep, I agree. 
Meant to change it already, but today was just a crazy meeting day...despite of being Monday... :-(

2024-06-25 23:31 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    or Form))
I refactored this, so, this case should be included as well.

2024-06-26 01:33 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // These controls need to be individually themed.
My be specify the controls is better because there are Custom control inherit from control and no need to dark it

2024-06-26 03:28 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // These controls need to be individually themed.
I would actually like for my custom controls to be automatically dark though if I want them to be dark. I don't want to do them myself when all of the built-in once are automatically dark when I configure winforms to always be dark.

2024-06-26 05:13 UTC, paul1956 commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // These controls need to be individually themed.
I have composite controls like a Panel with TextBoxes and Labels and another panel the new control implements custom behaviors. Will these just work or is there a way to opt in, I don’t do any drawing?

2024-06-30 05:03 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    and not ListView
But Don't ListView support this theme though? I thought it did and I need it to be the case for the scrollbars in it to be automatically dark.

2024-07-03 09:26 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            HDC hdc = PInvokeCore.GetWindowDC((HWND)m.HWnd);
take care draw directly to  WindowDC without buffer or select the correct region into it
always causes filcher on mouse focus and resize parent  and take window over taskbar and not appear in all computer  etc.... 
 you can see here 
https://github.com/r-aghaei/TextBoxBorderColor/issues/1

another example

https://github.com/dotnet/winforms/assets/12494184/be1bdec9-b936-4b64-8e80-3e66bf1d134f

2024-07-04 11:41 UTC, AraHaan approved these changes

2024-07-04 11:41 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            HDC hdc = PInvokeCore.GetWindowDC((HWND)m.HWnd);
I would like to take a lo9ok at that entire NCPaint if you do not mind.

2024-07-04 11:42 UTC, AraHaan commented
I did not mean to do the approve changes there 😄.

2024-07-06 21:58 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            HDC hdc = PInvokeCore.GetWindowDC((HWND)m.HWnd);
I'll be changing to GDI+, because I need Antialias to render rounded corners in higher quality. GDI doesn't really work. But sure, please comment while I'll be working on this. Will not be doing much though over the 4th-week.

2024-07-10 17:46 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            HDC hdc = PInvokeCore.GetWindowDC((HWND)m.HWnd);
@KlausLoeffelmann 


> I'll be changing to GDI+, because I need Antialias to render rounded corners in higher quality. GDI doesn't really work. But sure, please comment while I'll be working on this. Will not be doing much though over the 4th-week.

With my respect but GDI work fine but your drawing technique not fine  I see you tried more than once to make it work. so I create quick debug session to see why GDI not working but I find it  working fine I attached TextBoxBase
that working but like I say before GDI+ make it flickering as you see in next video so if you  need Antialias to render rounded corners in higher quality draw GDI+ with buffer(buffer graphics or vista buffer paint) or use GDI only or track
the mouse to see why it flickering

[TextBoxBase.zip](https://github.com/user-attachments/files/16167015/TextBoxBase.zip)


https://github.com/dotnet/winforms/assets/12494184/87081c2d-63ab-466e-b416-8a336634ed32

2024-07-10 17:58 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            HDC hdc = PInvokeCore.GetWindowDC((HWND)m.HWnd);
@AraHaan
> I would like to take a look at that entire NCPaint if you do not mind.

I do not mind.

if you do not mind can I know why it's not completed it's only to show my idea to make GDI painting dark None client 
area without  using undocumented function if you need to ask about something I will be here
  
you cane see it here 
https://github.com/memoarfaa/rufus/commit/814c4df261eb78ce5e1ffdaebc3cc7f6687f220e

2024-07-11 22:49 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
> +            var result = PInvoke.GetComboBoxInfo(HWND, ref cInfo);
We are not using `result`, did you mean to put a Debug.Assert here?

2024-07-11 22:49 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBox.cs
> +    private unsafe void WmPaintInternal(ref Message m)
Consider making this a local function since this seems to only be used in WndProc

2024-07-11 22:49 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
> +            }
nit: spacing

2024-07-15 01:49 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental("WFO9000")]
I very much encourage you to use [`UrlFormat`](https://learn.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.experimentalattribute.urlformat?view=net-8.0#system-diagnostics-codeanalysis-experimentalattribute-urlformat) parameter as well
```suggestion
    [Experimental("WFO9001", UrlFormat = Experiments.SharedUrlFormat)]
```

Then follow the same procedures as you do for the obsoletions - aka.ms links, the doc page, etc. This'd make it easy for the team (from the maintenanace perspective) and for your users (from the consumption perspective).

2024-07-15 22:52 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental("WFO9002")]
I imagine this won't be the case, but just noting that if this attribute is going to be kept around, we should have a static class that has this as a const, similar to https://github.com/dotnet/roslyn/blob/d9c433ee4784f95890d4e641c840670a1ca10ae1/src/Compilers/Core/Portable/InternalUtilities/RoslynExperiments.cs#L10

2024-07-16 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // These controls need to be individually themed.
You can always opt-out by setting the `DarkMode` property (which is ambient) of a Control to disabled.

2024-07-16 21:56 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            HDC hdc = PInvokeCore.GetWindowDC((HWND)m.HWnd);
> With my respect but GDI work fine but your drawing technique not fine I see you tried more than once to make it work. so I create quick

It was never not working. I have tried a few approaches to take HighDPI and custom NCPainting into account. I never checked in complete attempts. We need to settle for Graphics (GDI+) for AntiAlias reasons. Double buffering we can consider in the RC1 time frame, if it becomes necessary.

2024-07-16 21:59 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            HDC hdc = PInvokeCore.GetWindowDC((HWND)m.HWnd);
Some of the flickering still results from the `PlaceHolderText` painting, btw.

2024-07-16 22:20 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> -System.Windows.Forms.TextBoxBase.Padding.set -> void
It's a technicality in this case. We had shadowed `Padding` to disable it. So, to enable it again, we need to "unshadow" it by taking the `new` away. That means that the `TextBoxBase` `Padding` gets unshipped, and the original `Control.Padding` implementation takes over. It's no source code breaking change. But it is a binary breaking change.

2024-07-16 22:27 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    public static DarkMode DefaultDarkMode
Actually, this API is obsolete.

2024-07-16 22:28 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    public static bool IsVisualStylesSupported
Same. Obsolete. We do not need it.

2024-07-16 22:32 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    internal static Font DefaultFont => s_defaultFontScaled ?? s_defaultFont!;
This is not part of this change.
In VB it's set by WindowsFormsApplication base and I think in C# it's code generated?

2024-07-16 22:41 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                { }
Uh - yes, but: that was a refactoring which went south! Good catch!

2024-07-16 22:45 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
> +            var result = PInvoke.GetComboBoxInfo(HWND, ref cInfo);
Nope. Corrected.

2024-07-16 23:29 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental("WFO9002")]
True. But these consts will be defined in a PR, which hasn't merge yet. There will be an additional PR to make this clean.

2024-07-16 23:30 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental("WFO9000")]
I will address this once I the Analyzer PR got merged. I want these IDs also defined as consts. That PR will take care of that.

2024-07-17 17:04 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    and not ListView
I'll take a look directly after the API Review, which I am concentrating on right now.

2024-07-17 17:07 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    public static DarkMode DefaultDarkMode
No, it's not at all - sorry for the wrong comment.
I added XML comments.

2024-07-17 17:08 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            {
There were a series of format issues, which I suspect were merge issues. I should have corrected them all! Thanks for catching this!

2024-07-17 17:10 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBox.cs
> +    private unsafe void WmPaintInternal(ref Message m)
Is this a general rule? I am asking, since sometimes I like normal functions better, since they can be XML documented, which makes sense to me even if they're private.

2024-07-17 18:02 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBox.cs
> +    private unsafe void WmPaintInternal(ref Message m)
Yep, generally if a function is only being used once, it should be made into a local function so it is clear that it is being used just in that method. I think documenting the local function should not cause issues with readability, but we can revisit this if this is a concern.

2024-07-17 18:14 UTC, JeremyKuhne requested changes
Added comments.

2024-07-17 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +        graphics.SmoothingMode = SmoothingMode.AntiAlias;
You should be saving the Graphics state before modifying it. `GraphicsStateScope` is the one here.

2024-07-17 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +        graphics.Clip = new Region(bounds);
Region needs to be in a using or it will leak. Setting the clip copies it.

2024-07-17 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            bool wParam = m.WParamInternal != 0;
What is this one for?

2024-07-17 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextBox/AnimatedBorderStyleRenderer.cs
> +            using Brush parentBackgroundBrush = new SolidBrush(parentBackColor);
Use scopes for these to get caching, there are extensions on Color for that.

2024-07-17 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextRenderer.cs
> +            // Disabled. We are getting this pretty much whenever we call a DrawText.
These need to come back, you aren't scoping your transforms and clipping.

2024-07-17 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextBox/AnimatedBorderStyleRenderer.cs
> +            graphics.SmoothingMode = SmoothingMode.AntiAlias;
You must scope the Graphics state to not dirty it when you change properties on it (rendering mode, clipping, etc.). Use `GraphicsStateScope`.

2024-07-17 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Theming/DarkThemedApplicationColors.cs
> +    internal class DarkThemedApplicationColors : ApplicationColors
Seal this

2024-07-17 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Theming/ForcedLightThemedSystemColors.cs
> +    internal class ForcedLightThemedSystemColors : ApplicationColors
Seal

2024-07-17 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Theming/LightThemedApplicationColors.cs
> +    {
Seal

2024-07-23 11:24 UTC, hyperquantum commented
Is this PR still going to target .NET 9 or will it be .NET 10?
Asking because of issue #11731.

2024-07-29 07:39 UTC, MagicAndre1981 commented
1 question. does this PR also handle dark/light theme change in settings app and changes the colors on the fly without closing/reopening the window to take effect?

2024-07-29 09:12 UTC, RussKie commented
> 1 question. does this PR also handle dark/light theme change in settings app and changes the colors on the fly without closing/reopening the window to take effect?

I don't believe it does. It was called out during the [API review](https://github.com/dotnet/winforms/issues/7641#issuecomment-2237384450).

2024-07-29 09:31 UTC, RussKie reviewed
Quick partial review

2024-07-29 09:31 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
> +        ///  Retrieves the ambient back s_colorMode for the control.
This needs to be reverted. Ditto below.

2024-07-29 09:44 UTC, AngeloCresta commented
> > 1 question. does this PR also handle dark/light theme change in settings app and changes the colors on the fly without closing/reopening the window to take effect?
> 
> I don't believe it does. It was called out during the [API review](https://github.com/dotnet/winforms/issues/7641#issuecomment-2237384450).

Is it not possible to add an event when the ColorMode changes? 
In this way a component that will loop through controls and force repainting in something easy for us to implement and let the 3party controls producers to style the "stock controls" while theming their own ...

2024-07-29 22:30 UTC, RussKie commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Adorner.cs
> +///  can be enabled/disabled.  Only Dark Adorners will receive hit test
I don't think this (and all similar) change is correct. This looks like a bulk find-replace that was too eager...

2024-07-29 22:32 UTC, RussKie commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
>          if (InheritanceAttribute != InheritanceAttribute.InheritedReadOnly)
This change doesn't look correct (and all similar) either...

2024-07-29 22:33 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerActionServiceTests.cs
> +        // Not Classic.
This change doesn't look correct

2024-07-29 22:34 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/InheritanceUITests.cs
> +    [InlineData(InheritanceLevel.NotInherited, "System control")]
This doesn't look correct

2024-07-29 23:34 UTC, RussKie commented
I've gone through 89/139 of files and I don't see how the new "colour system" is expected to work. That is, I see `ControlSystemColors` being an adapter for the `SystemColors`. The issue with this - as was pointed during the the API Review - all consumers will have to essentially rewrite their apps to use `ControlSystemColors` instead of `SystemColors`. And, if consumers happen to use some 3P controls, which in turn, use `SystemColors`, those 3P controls will become "unusable" because those controls won't match the colour scheme...

2024-08-01 22:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental(DiagnosticIDs.ExperimentalDarkMode, UrlFormat = "https://aka.ms/WfoExperimental/{0}")]
Suggest turning `https://aka.ms/WfoExperimental/{0}` into a const as well. The same way it's done for the obsoletions:
https://github.com/dotnet/winforms/blob/6194fcc4bd5b23a47be4298f4cdc15ed78da8e0f/src/Common/src/Obsoletions.cs#L8-L10

2024-08-01 22:57 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental(DiagnosticIDs.ExperimentalDarkMode, UrlFormat = "https://aka.ms/WfoExperimental/{0}")]
‼️ Also, keep the aka.ms link aligned to the existing naming conventions. "https://aka.ms/WfoExperimental/" is rather meaningless to users and aka.ms maintainers.

Please use something along the lines of `https://aka.ms/winforms-experiments/{0}`. Or just stay within `https://aka.ms/winforms-warnings/` namespace.

/cc: @merriemcgaw @JeremyKuhne for visibility

2024-08-04 01:42 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            HDC hdc = PInvokeCore.GetWindowDC((HWND)m.HWnd);
It's buffered now.

2024-08-04 01:42 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental("WFO9000")]
Done.

2024-08-04 01:45 UTC, KlausLoeffelmann commented on .editorconfig
> +dotnet_style_object_initializer = true:suggestion
No idea how this happened. I guess that I wanted to add an exception in code via a CodeFix, did not hit, and changed a rule instead.

2024-08-04 01:45 UTC, KlausLoeffelmann commented on src/System.Drawing.Common/src/System/Drawing/SystemPens.cs
> +public static class SystemColorsRouter
None. Left over, deleted.

2024-08-04 01:54 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +                        defaultValue: -1) ?? 0);
Good point.

2024-08-04 01:55 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +        => IsDarkModeEnabled
That's muscle memory from the Designer repo. Is there an Analyzer which would error this?

2024-08-04 01:59 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    private void SetDarkMode(DarkMode darkMode)
All the dark mode related properties are gone from control. But it was a fair question, anyway.

2024-08-04 02:02 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                && Equals(value, VisualStylesMode))
Old habit. Operators can be overloaded. Changed it.

2024-08-04 02:03 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                if (this is not ComboBox
Yep. This is a style now.

2024-08-04 02:06 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    public Dictionary<string, int> DebuggerBreakCounters { get; set; } = [];
That was just for me for the time being. It's gone.

2024-08-04 02:06 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/Appearance.cs
> +    ToggleSwitch = 2
We changed it to 5000, as talked about.

2024-08-04 02:13 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +    private int GetBorderThicknessDpiFactor()
I did some tests, and completely refactored this.

2024-08-04 02:15 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +        using Brush parentBackgroundBrush = new SolidBrush(parentBackColor);
Is that a public API now?

2024-08-04 02:19 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +        graphics.Clip = new Region(bounds);
Damn, yes.

2024-08-04 02:23 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +            bool wParam = m.WParamInternal != 0;
We only can have this once, whenever the handle is getting (re)created.

2024-08-04 02:25 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +        graphics.SmoothingMode = SmoothingMode.AntiAlias;
Can you take another look at the caching I introduced for the NC-Painting? When we had scrollbars or multi line text boxes, the flickering was terrible. Now, it's absolutely smoothly, but I need your expertise to make sure, we're not leaking anything.

2024-08-04 03:23 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +        graphics.SmoothingMode = SmoothingMode.AntiAlias;
Since I am drawing in a Bitmap now, saving the state is redundant, or is it?

2024-08-04 03:25 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextRenderer.cs
> +            // Disabled. We are getting this pretty much whenever we call a DrawText.
Yes, done.

2024-08-04 03:33 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Theming/DarkThemedApplicationColors.cs
> +    internal class DarkThemedApplicationColors : ApplicationColors
It's gone.

2024-08-04 03:34 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Theming/ForcedLightThemedSystemColors.cs
> +    internal class ForcedLightThemedSystemColors : ApplicationColors
Gone.

2024-08-04 03:34 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Theming/LightThemedApplicationColors.cs
> +    {
Gone.

2024-08-04 03:35 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
> +        ///  Retrieves the ambient back s_colorMode for the control.
That was a bad merge. Everything around that has been reverted.

2024-08-04 03:36 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Adorner.cs
> +///  can be enabled/disabled.  Only Dark Adorners will receive hit test
Actually, way more subtle. Somehow, the settings in Roslyn's Symbol Rename opted to Comments and Strings. They should not exist!!

2024-08-04 03:38 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental(DiagnosticIDs.ExperimentalDarkMode, UrlFormat = "https://aka.ms/WfoExperimental/{0}")]
OK, no problem.

2024-08-04 03:40 UTC, KlausLoeffelmann commented
@RussKie: https://github.com/dotnet/runtime/pull/105525

2024-08-04 23:15 UTC, RussKie reviewed
👍

2024-08-04 23:15 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +                : s_systemColorMode.Value;
[doc/nit] The comment here largely repeats the implementation - i.e., what's easy to read and infer by looking at the code. At the same time, this comment is valuable (but absent) in the xml-doc for the consumer who doesn't have access to the code.
Please move the comment into `<returns>` tag.

2024-08-04 23:15 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    ///  Note: In a high contrast mode, this will always return <see langword="false"/>.
[docs] This should be move to the "returns" section.

2024-08-04 23:15 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/CommonDialogs/FontDialog.cs
> +            // Convert to RGB and back to resolve indirect colors like Application.SystemColors.ControlText
This should be reverted, right?

2024-08-04 23:15 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/DrawItemEventArgs.cs
> +    ///  A suggested color drawing: either Application.SystemColors.WindowText or Application.SystemColors.HighlightText,
Ditto

2024-08-04 23:15 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextRenderer.cs
> +        // If the color is darker than Application.SystemColors.Control make it slightly darker,
Ditto

2024-08-04 23:15 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ProfessionalColorTable.cs
> +    ///  turned on, we'll fall back to Application.SystemColors.
Ditto

2024-08-05 06:03 UTC, KlausLoeffelmann commented on .editorconfig
> +    .Clear() instead of Span<T>.Fill()
I have NO idea what's causing this constant changes of the .editorConfig. It's driving me absolutely bananas.
I thought first it was me, doing something accidently with running CodeFixes. But it's not. 🤷‍♂️

2024-08-05 06:10 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ProfessionalColorTable.cs
> +    ///  turned on, we'll fall back to Application.SystemColors.
I'll do a find/replace of those!

2024-08-05 17:26 UTC, JeremyKuhne commented on .editorconfig
> +    .Clear() instead of Span<T>.Fill()
Need to undo this file.

2024-08-05 17:42 UTC, JeremyKuhne commented on src/System.Drawing.Common/src/System/Drawing/SystemBrushes.cs
> +        if (s_colorSetOnLastAccess != SystemColors.UseAlternativeColorSet)
The "right" way to do this is to poke the callbacks when you flip the color set. Probably best to look for `".NET System Events"` window and send the right message to it to get the `SystemColorTracker` to respond.

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> -System.Windows.Forms.TextBoxBase.Padding.set -> void
Are we still trying to avoid binary breaking change here?

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +#pragma warning restore WFO5001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
Not a priority but have this comment twice is distracting
```suggestion
#pragma warning restore WFO5001
```

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +        int systemColorMode = -1;
What does -1 represent?

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    // [SRDescription(nameof(SR.ControlVisualStylesModeChangedDescr))]
Did we want to uncomment this now?

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            if (Equals(Properties.GetObject(s_visualStylesModeProperty), Parent?.VisualStylesMode))
Consider combining if statements

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                (uint)sizeof(BOOL));
Did we want to assert success here?
```suggestion
            PInvoke.DwmSetWindowAttribute(
                hwnd,
                DWMWINDOWATTRIBUTE.DWMWA_USE_IMMERSIVE_DARK_MODE,
                &value,
                (uint)sizeof(BOOL)).AssertSuccess();
```

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/ControlStyles.cs
> +    ContainerControl = 0b00000001, // 0x00000001
Consider lining up the `=` for this enum for better readability of the 0b0....

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/LinkLabel.cs
> +    private static Color s_ieDisabledLinkColor = Color.Empty;
what is 'ie' in `s_ieDisabledLinkColor`?

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
> +    private void DefineClientRectangle()
where is this used?

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabPage.cs
> +            else if (!Application.IsDarkModeEnabled
```suggestion
            else if (!Application.IsDarkModeEnabled
```

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DarkProfessionalColors.cs
> +{
```suggestion
namespace System.Windows.Forms;
```

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/SystemColorMode.cs
> +{
```suggestion
namespace System.Windows.Forms;
```

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        }
```suggestion
        get => Properties.ContainsInteger(s_propFormCornerPreference)
                        ? (FormCornerPreference)Properties.GetInteger(s_propFormCornerPreference)
                        : FormCornerPreference.Default;
```

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +            {
Consider removing `else` to avoid indent in. It's not needed since the if statement above will return.

2024-08-05 18:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +            else
Ditto here

2024-08-05 20:23 UTC, JeremyKuhne commented on src/System.Private.Windows.Core/src/NativeMethods.txt
> +ExtSelectClipRgn
If you're not using this code in Core you should move these defines to Primitives

2024-08-05 20:32 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs
> +        if (color.IsSystemColor && SystemColors.UseAlternativeColorSet)
This should not be necessary. `ColorTranslator.ToWin32` looks up the value the color every time it uses it.

Note that this method is terrible as it will look up the color value three times. Created an issue for myself to fix that: https://github.com/dotnet/runtime/issues/105992

2024-08-05 20:35 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/CreateBrushScope.cs
> +#pragma warning disable SYSLIB5002 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
Do this additional check in the PInvoke.GetSysColorBrush overload.

2024-08-05 20:43 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> -System.Windows.Forms.TextBoxBase.Padding.set -> void
Reiterating here that we _cannot_ make a binary breaking change or we cannot use any assembly that hasn't been recompiled against the new framework that touches this property (non-starter).

2024-08-05 20:48 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental(DiagnosticIDs.ExperimentalDarkMode, UrlFormat = "https://aka.ms/WfoExperimental/{0}")]
This needs resolved.

2024-08-05 21:06 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/CheckBox.cs
> +            // In here, we take care of both the event changed events for Checked...
nit: Please don't use `...` in comments. This particular comment doesn't seem to offer much over the actual code.

2024-08-05 21:08 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
> +        // NOTE: Setting SelectedIndex must be the last thing we do!
nit: avoid exclamation points in the comments.

2024-08-05 21:13 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DateTimePicker/DateTimePicker.cs
> +        get => ShouldSerializeBackColor()
Why are we making the check here? SystemColors.Window should have the right color.

2024-08-05 21:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DateTimePicker/DateTimePicker.cs
> +        get => ShouldSerializeForeColor()
SystemColors.WindowText should have the right color.

2024-08-05 21:17 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/GroupBox/GroupBox.cs
> +            if (ShouldSerializeForeColor() || Application.IsDarkModeEnabled || !Enabled)
Follow up is that we should add new methods to make this pattern clearer. Reusing `ShouldSerialize` is confusing. `HasCustomForeColor` would be so much clearer.

2024-08-05 21:20 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/GroupBox/GroupBox.cs
> +            if (ShouldSerializeForeColor() || Application.IsDarkModeEnabled || !Enabled)
I presume the only reason we need this is because we don't use VisualStyleRenderer.DrawText. We should have a tracking issue here to see why we don't use it, as presumably it would be themed correctly.

2024-08-05 21:23 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
> +                // ...and then just let the default handling play out.
nit: avoid `...`

2024-08-05 21:23 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
> +
nit: please don't put blank lines between blocks in `if .. else` chains.

2024-08-05 21:25 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
> +        base.OnNcPaint(graphics);
Why does the need an override?

2024-08-05 21:27 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBox.cs
> +        unsafe void WmPaintInternal(ref Message m)
I don't think this needs unsafe

2024-08-05 21:32 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +                // TODO: I am not sure, if this calculation still fits since we got the underlined border style.
Don't leave TODO, create an issue if there is a follow-up

2024-08-05 21:59 UTC, paul1956 commented on .editorconfig
> +    .Clear() instead of Span<T>.Fill()
@KlausLoeffelmann I have noticed that just opening .editorConfig in editor and closing/saving makes changes that are unexpected and not welcome. I have reported it through Visal Studio Feedback but don't know the team considers it important.

2024-08-05 22:02 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> -System.Windows.Forms.TextBoxBase.Padding.set -> void
We discussed this in the API Review. 
They said un-shadowing an existing API is not a breaking change, since the resolution will automatically fallback to the base control.

2024-08-05 22:06 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +        int systemColorMode = -1;
Internally, -1 and 0 are the values from the registry.
Let me put consts here to make it clearer.

2024-08-05 22:08 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/LinkLabel.cs
> +    private static Color s_ieDisabledLinkColor = Color.Empty;
Who knows. "Internet Explorer" I suppose.

2024-08-05 22:10 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs
> +        if (color.IsSystemColor && SystemColors.UseAlternativeColorSet)
It unfortunately is. Internally, it seems, it's making a call to GetSysColors(), which therefore bypasses our Color-DarkMode conversion.

2024-08-05 22:16 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
> +        base.OnNcPaint(graphics);
RichTextBox adds its own NC-Calculation, which needs to happen first, otherwise, it does not know where to put the scrollbars (and other internal stuff). TextBoxBase, however, cannot have that, so, that's why I did it this way.

2024-08-05 22:47 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs
> +        if (color.IsSystemColor && SystemColors.UseAlternativeColorSet)
If you've flipped `SystemColors` this should _not_ be happening.

2024-08-05 22:48 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> -System.Windows.Forms.TextBoxBase.Padding.set -> void
@ericstj Can you please help confirm this?

2024-08-05 22:52 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextBox/AnimatedBorderStyleRenderer.cs
> +        // Contrast to Copilot's suggestions, we need to first exclude
Don't reference Copilot here, that isn't a stable authority

2024-08-05 22:54 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextBox/AnimatedBorderStyleRenderer.cs
> +        // Fill the background with the specified brush:
nit: Don't use `:` or `...`, use `.` to end comment blocks.

2024-08-05 22:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextBox/AnimatedBorderStyleRenderer.cs
> +                // Draw a rounded Rectangle with the border thickness
This isn't a rounded rectangle. Not sure if these comments provide any value.

2024-08-05 22:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextBox/AnimatedBorderStyleRenderer.cs
> +                // fill a rounded Rectangle
Over expressive comments

2024-08-05 23:01 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/Animation/AnimationManager.cs
> +    public const int FrameRate = 40;
Frames per what?

2024-08-05 23:06 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/Animation/AnimationManager.cs
> +        _timer.Dispose();
Why is this not in the lock?

2024-08-05 23:08 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/Animation/AnimationManager.cs
> +    public const int FrameRate = 40;
Did we look at prior art for what intervals we should be using?

2024-08-05 23:16 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/Animation/AnimationManager.cs
> +    private readonly Dictionary<AnimatedControlRenderer, AnimationRendererItem> _renderer = [];
Why are you not using a `ConcurrentDictionary`? That would make this class much simpler.

2024-08-05 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/MDI/MDIClient.cs
> +    internal override bool ShouldSerializeBackColor()
Why change this?

2024-08-05 23:25 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        DWM_WINDOW_CORNER_PREFERENCE dwmCornerPreference = cornerPreference switch
No need to map again, just cast and inline the PInvoke. Validate enum values as we do elsewhere with `SourceGenerated.EnumValidator.Validate(value);`.

2024-08-05 23:26 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +    private unsafe Color GetFormAttributeColorInternal(DWMWINDOWATTRIBUTE dmwWindowAttribute)
If there is only one caller just do these calls inline.

2024-08-05 23:34 UTC, ericstj commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> -System.Windows.Forms.TextBoxBase.Padding.set -> void
It's not a binary breaking change.  We explicitly allow that in APICompat: https://github.com/dotnet/sdk/blob/2f19fa0db2e5a800b1cf09334c3a7c25f3249f7b/test/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs#L66-L103

2024-08-05 23:39 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.NonClientBitmapCache.cs
> +    private class NonClientBitmapCache : IDisposable
This is dangerous to be adding this late. Please use `BufferedGraphics`.

2024-08-05 23:42 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
> +        base.OnNcPaint(graphics);
This is just calling base, that tells me this is a no-op.

2024-08-05 23:44 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> -System.Windows.Forms.TextBoxBase.Padding.set -> void
Eric confirmed that this particular case is ok.

2024-08-06 05:44 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
> +        base.OnNcPaint(graphics);
Oh, I am sorry, I misread. Thought this was NcCalc. 
You're right.

2024-08-06 05:46 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
> +    private void DefineClientRectangle()
Left-over. Good catch!

2024-08-06 05:47 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +#pragma warning restore WFO5001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
Let's purge them in .NET 10.

2024-08-06 05:49 UTC, KlausLoeffelmann commented on .editorconfig
> +    .Clear() instead of Span<T>.Fill()
I know that one. But I only open it with the text editor. Still, something screws this file up permanently.

2024-08-06 06:02 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    ///  Note: In a high contrast mode, this will always return <see langword="false"/>.
No. I want to see this in the tool tips.

2024-08-06 06:03 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +    // [SRDescription(nameof(SR.ControlVisualStylesModeChangedDescr))]
Uh, yeah!

2024-08-06 06:10 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/CheckBox.cs
> +            // In here, we take care of both the event changed events for Checked...
It actually does. You accidentally ignore Check_State_Change pretty quickly.

2024-08-06 06:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental(DiagnosticIDs.ExperimentalVisualStyles, UrlFormat = "https://aka.ms/winforms-experimental/{0}")]
Any specific reason you're avoiding a const for `"https://aka.ms/winforms-experimental/{0}"`?

2024-08-06 06:42 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental(DiagnosticIDs.ExperimentalDarkMode)]
Missing `UrlFormat` parameter

2024-08-06 06:42 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental(DiagnosticIDs.ExperimentalDarkMode)]
Ditto.

Not going to comment for other places.

2024-08-06 06:42 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    ///  Note: In a high contrast mode, this will always return <see langword="false"/>.
The return value is shown in the tooltip.
![image](https://github.com/user-attachments/assets/38f331cf-ee14-4449-a05b-d61560058a00)

2024-08-06 06:42 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +
[nit] redundant line

2024-08-08 05:39 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +
No, I need the visible space here. This will be gone for .NET 10 automatically, once we're purging all of pragmas.

2024-08-08 05:45 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +    [Experimental(DiagnosticIDs.ExperimentalVisualStyles, UrlFormat = "https://aka.ms/winforms-experimental/{0}")]
Globally replaced.

2024-08-08 06:09 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ControlStyles.cs
> +    ContainerControl = 0b00000001, // 0x00000001
Not a big fan of that.

2024-08-08 06:20 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/CreateBrushScope.cs
> +#pragma warning disable SYSLIB5002 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
Ah, yes, sure!!

2024-08-08 06:38 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/GroupBox/GroupBox.cs
> +            if (ShouldSerializeForeColor() || Application.IsDarkModeEnabled || !Enabled)
https://github.com/dotnet/winforms/issues/11836

2024-08-08 06:39 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
> +
This is nothing I do on purpose. Muscle memory. Can we enforce this?

2024-08-08 06:48 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
> +                // TODO: I am not sure, if this calculation still fits since we got the underlined border style.
They are fine. I checked - the TODO is gone.

2024-08-08 06:50 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextBox/AnimatedBorderStyleRenderer.cs
> +        // Contrast to Copilot's suggestions, we need to first exclude
I was referring to a COPILOT comment in the error list. It might confuse folks. Currently, you need to opt in to see those. I removed the comment anyway.

2024-08-08 07:11 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/Animation/AnimationManager.cs
> +    public const int FrameRate = 40;
Added an extensive description.

2024-08-08 07:16 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/MDI/MDIClient.cs
> +    internal override bool ShouldSerializeBackColor()
Sorry. Left-over from attempt from `Application.SystemColor`. Good catch!

2024-08-08 07:24 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        DWM_WINDOW_CORNER_PREFERENCE dwmCornerPreference = cornerPreference switch
Cannot use `SourceGenerated.EnumValidator.Validate(value)`. The code generator cannot deal with the experimental attribute.

2024-08-08 21:42 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/CreateBrushScope.cs
> +#pragma warning disable SYSLIB5002 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
The point is to always kick back the solid color brush and not the sys one when getting syscolorbrush or you're going to miss cases.

2024-08-08 21:42 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/CreateBrushScope.cs
> +#pragma warning disable SYSLIB5002 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
C:\Users\jkuhne\source\repos\winforms\src\System.Windows.Forms.Primitives\src\Windows\Win32\PInvoke.GetSysColorBrush.cs

2024-08-08 21:58 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/CreateBrushScope.cs
> +#pragma warning disable SYSLIB5002 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
Done.

2024-08-09 17:36 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/Appearance.cs
> +    ///  This setting is not taken into account, when <see cref="VisualStylesMode"/> is set
The second part of this should be a remarks section.

2024-08-09 17:48 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextRenderer.cs
> -                || graphics.Clip is null
This file needs undone.

2024-08-09 17:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/CheckBox/AnimatedToggleSwitchRenderer.cs
> +            path.AddArc(rect.X, rect.Y, radius * 2, radius * 2, 180, 90);
Is this a rounded rectangle?

2024-08-09 17:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Rendering/Animation/AnimationManager.cs
> +    private readonly WindowsFormsSynchronizationContext? _syncContext = (WindowsFormsSynchronizationContext?)SynchronizationContext.Current;
You're going to be grabbing this for whatever the thread happens to be that the static Instance runs on. Is this really what you want? I presume you'd be better off just calling `SynchronizationContext.Currrent?.Post()` inline.

2024-08-09 20:38 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
>      public Color FormBorderColor
Good catch! I will test and add this to the docs! Nice one - adds _real_ value!

2024-08-09 21:38 UTC, KlausLoeffelmann commented
Locked the discussion, since we need to separate this out into different PRs.
More background info to come soon.

2024-08-09 23:13 UTC, merriemcgaw commented
### Important! 
I've made the extremely hard decision to bump this feature's release to 10. This was coming in awfully hot for .NET 9 RC1 and wasn't looking like everything we needed to do internally (t's crossed and i's dotted) could be addressed in time to meet code complete, which is in just a couple of days. Rather than try to force it into RC1 I decided the best course of action will be to move it to 10 and have it ready to go well before the first preview. Given the bake time it will have in the next release, I think we can be confident of a successful release in 10.

Those of you who are invested in the Dark Mode and VisualStyles work - we want **all** of the feedback that we can get. You will be able to start seeing builds with this feature work in a few weeks at most when .NET repos move Main to target .NET 10. We have every confidence in this feature and are looking forward to having it ready for you with the very first builds of .NET 10 for your evaluation.

If you have any questions, please don't hesitate to ask on the main issue #7641.

2024-08-10 19:21 UTC, closed without merging

2024-08-12 01:58 UTC, RussKie commented
Looks like the dark-mode landed in .NET 9 afterall --> https://github.com/dotnet/winforms/pull/11857
🎉

2024-08-12 19:09 UTC, merriemcgaw commented
Indeed it did! We were able to separate it from the bigger Visual Styles work and get it in for .NET 9. Huge Kudos to @KlausLoeffelmann  and @JeremyKuhne for the heroics over the weekend to make sure we had this for .NET 9. Without their above and beyond efforts we would not have been able to make code-complete. Please use and provide feedback!