WinForms Repo Readme update
dotnet/winforms pull request #11060
Opened 2024-03-15 19:38 UTC by KlausLoeffelmann

We got some very good and important feedback on the summit, and this is a first step (and draft) to get that feedback addressed in a quick way.

Please read and comment.

Thanks!

2024-03-15 20:41 UTC, JeremyKuhne commented on README.md
> +**Important:** As a Third Party Control Vendor, when you migrated controls from .NET Framework to .NET, you're control libraries _at runtime_ are expected to work as before in the context of the resp
```suggestion
**Important:** As a Third Party Control Vendor, when you migrate controls from .NET Framework to .NET, your control libraries _at runtime_ are expected to work as before in the context of the respective new TFM (special modernization or security changes in the TFM kept aside, but those are rare breaking changes). Depending on the richness of your control's design-time support, the migration of control designers from .NET Framework to .NET might need to take a series of areas with breaking changes into account. The provided link points out additional resources which help in that migration process.
```

2024-03-15 20:43 UTC, JeremyKuhne commented on README.md
> +WinForms is a technology which was originally introduced as a part of .NET Framework 1.0 on February 13th, 2002. It's primary and foremost trait was and is to be a Rapid Application Tool for Windows
```suggestion
WinForms is a technology which was originally introduced as a part of .NET Framework 1.0 on February 13th, 2002. It's primary focus was and is to be a Rapid Application Tool for Windows based Apps, and that principal sentiment has not changed over the years. WinForms at the time addressed developer's requests for
```

2024-03-15 20:44 UTC, JeremyKuhne commented on README.md
> +* A Framework to carrie stable, monolithic Line of Business Apps, even with extremely complicated and complex domain-specific workflows
```suggestion
* A framework for stable, monolithic Line of Business Apps, even with extremely complicated and complex domain-specific workflows
```

2024-03-15 20:45 UTC, JeremyKuhne commented on README.md
> +* The ability to easy provide rich and accessibility-complient UIs according to the Zeitgeist at the time (realisticly from .NET Framework 2.0 on)
```suggestion
* The ability to easily provide rich and accessibility-compliant UIs
```

2024-03-15 20:46 UTC, JeremyKuhne commented on README.md
> +* A safe and - over the first 3 versions of .NET Framework - increasingly performant way to communicate accros process boundaries via .NET Remoting and later Windows Communication Services, or access
```suggestion
* A safe and - over the first 3 versions of .NET Framework - increasingly performant way to communicate across process boundaries via .NET Remoting and later Windows Communication Services, or access on-site databases via ADO.NET providers.
```

2024-03-15 20:46 UTC, JeremyKuhne commented on README.md
> +* A very easy to use, visual what-you-see-is-what-you-get-Designer, which requires next to none ramp-up time, and was primarily focused to support 96 DPI resolution-based, pixel-coordinated drag & dr
```suggestion
* A very easy to use, visual what-you-see-is-what-you-get designer, which requires little ramp-up time, and was primarily focused to support 96 DPI resolution-based, pixel-coordinated drag & drop design strategies.
```

2024-03-15 20:47 UTC, JeremyKuhne commented on README.md
> +* An incredible flexibel, .NET reflection-based Designer extensibility model, utilizing the .NET Component Model to its extremes.
```suggestion
* A flexible, .NET reflection-based Designer extensibility model, utilizing the .NET Component Model.
```

2024-03-15 20:48 UTC, JeremyKuhne commented on README.md
> +* A special concept for visual Controls and Components, which provide their own design-time functionality through Control Designers
```suggestion
* Visual Controls and Components, which provide their own design-time functionality through Control Designers
```

2024-03-15 20:51 UTC, JeremyKuhne commented on README.md
> +Over time though, and with a growing need to address working scenarios with multi-monitor work places, monitors with way higher resolution, remoting technologies, which were no longer safe enough for
```suggestion
Over time though, and with a growing need to address working scenarios with multi-monitor, high resolution monitors, changing remoting technology requirements, and much more, WinForms needed to be modernized.
```

2024-03-15 20:59 UTC, JeremyKuhne commented on README.md
> +* A safe and - over the first 3 versions of .NET Framework - increasingly performant way to communicate accros process boundaries via .NET Remoting and later Windows Communication Services, or access
I'm sort of concerned about this bullet point in general. Calling out remoting is going to be confusing now that remoting is no longer supported.

2024-03-15 21:07 UTC, JeremyKuhne commented on README.md
> +The other one is Windows itself: When WinForms came out, it needed Windows 2000 as a reasonable choice for the operating system to run the Developer tools on. Keep in mind, even WinForms .NET Framewo
From here on I don't think the info is helpful. It's too specific and way too detailed. Something more like:

```
We'll continue to invest in making WinForms usable and compliant in current environments while doing our best to maintain compatibility for existing applications. We'll make utilizing modern coding practices and patterns easier and give you the best possible platform for building Win32 based Windows desktop applications.
```

2024-03-15 21:26 UTC, Tanya-Solyanik commented on README.md
> +For information about the WinForms Designer supporting the .NET runtime and the changes between the .NET Framework Designer (supporting .NET Framework up to version 4.8.1) vs. the .NET Designer (supp
```suggestion
For information about the WinForms Designer supporting the .NET runtime and the changes between the .NET Framework Designer (supporting .NET Framework up to version 4.8.1) vs. the .NET Designer (supporting .NET 6, 7, 8, 9+), please see [Windows Forms Designer Documentation](https://learn.microsoft.com/dotnet/desktop/winforms/controls-design/designer-differences-framework?view=netdesktop-8.0).
```

2024-03-15 22:25 UTC, KlausLoeffelmann commented on README.md
> +The other one is Windows itself: When WinForms came out, it needed Windows 2000 as a reasonable choice for the operating system to run the Developer tools on. Keep in mind, even WinForms .NET Framewo
```suggestion
And then there is the evolution of Windows: When new versions of Windows introduce new or change existing APIs or technologies - WinForms needs to keep up and adjust their APIs accordingly.
```

2024-03-15 22:26 UTC, KlausLoeffelmann commented on README.md
> +The other one is Windows itself: When WinForms came out, it needed Windows 2000 as a reasonable choice for the operating system to run the Developer tools on. Keep in mind, even WinForms .NET Framewo
I think it's important to just point out, that when they modernize, we often need to adjust, since we're depending. But I'll shorten that!

2024-03-15 22:33 UTC, merriemcgaw requested changes
Thanks @KlausLoeffelmann

2024-03-15 22:33 UTC, merriemcgaw commented on README.md
> +* A safe and - over the first 3 versions of .NET Framework - increasingly performant way to communicate accros process boundaries via .NET Remoting and later Windows Communication Services, or access
I agree with @JeremyKuhne, I would cut this bullet altogether, honestly.

2024-03-15 22:33 UTC, merriemcgaw commented on README.md
> +The other one is Windows itself: When WinForms came out, it needed Windows 2000 as a reasonable choice for the operating system to run the Developer tools on. Keep in mind, even WinForms .NET Framewo
agreed. Let's keep it brief here and focus on the fact that we're working to provide a SAFE, compliant, etc. way to keep evolving/keep pace with the operating system evolution.

2024-03-15 22:33 UTC, merriemcgaw commented on README.md
> +* New requests from governments in the area of accessibility
```suggestion
* New features to comply with updated industry standards for accessibility.
```

2024-03-15 22:33 UTC, merriemcgaw commented on README.md
> +* HighDPI and per Monitor V2-Scenarios, since they can quickly impose accessibility impediments.
```suggestion
* HighDPI and per Monitor V2-Scenarios.
```
I don't think we need to explain why for this area😄

2024-03-15 22:33 UTC, merriemcgaw commented on README.md
> +* Picking up changed or extended Win32 Control functionality, to keep controls in WinForms working the way, the Windows team wants them to be used.
```suggestion
* Picking up changed or extended Win32 Control functionality, to keep controls in WinForms working the way the Windows team wants them to be used.
```

2024-03-15 22:33 UTC, merriemcgaw commented on README.md
> +* Addressing Performance and Security issues in the underlying render layers WinForms is based on, like GDI, GDI+, conflicting rendering spots like the Windows Desktop Manager
```suggestion
* Addressing Performance and Security issues
```

2024-03-15 22:33 UTC, merriemcgaw commented on README.md
> +* Addressing accessibility and visual contrast issues like providing a general guide for implementing dark mode, which integrates in the current OS as seemless as possible without changing existing c
```suggestion

```
I don't think you need to address accessibility twice in this. I think the first bullet also would cover contrast ratios

2024-03-15 22:33 UTC, merriemcgaw commented on README.md
> +* New functionality, which modern Desktop UIs like WPF or WinUI clearly have already
```suggestion
* New functionality which modern Desktop UIs like WPF or WinUI clearly have already
```

2024-03-20 21:44 UTC, merriemcgaw approved these changes
Thanks @KlausLoeffelmann

2024-03-21 22:48 UTC, merged