Add code coverage for ComboBox
dotnet/winforms pull request #11262
Opened 2024-04-24 07:51 UTC by Nora-Zhou01

Related #10453 

## Proposed changes

- Add unit tests for ComboBox to test its MaxLength property

## Customer Impact

- None

## Regression? 

- No

## Risk

- Minimal

## Test methodology 

- Unit tests

2024-04-24 08:49 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        using var control = new ComboBox();
Please use target type new

using ComboBox control = new();

2024-04-24 08:49 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        using var control = new ComboBox();
Please use target type new

using ComboBox control = new();

2024-04-24 08:49 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        Assert.False(control.IsHandleCreated);
https://github.com/dotnet/winforms/pull/10693#discussion_r1480614532. 

For a detailed guide, refer to the Fluent Assertions documentation [here](https://fluentassertions.com/introduction).

2024-04-24 08:49 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        Assert.True(control.IsHandleCreated);
https://github.com/dotnet/winforms/pull/10693#discussion_r1480614532.

For a detailed guide, refer to the Fluent Assertions documentation [here](https://fluentassertions.com/introduction).

2024-04-24 08:49 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        Assert.False(control.IsHandleCreated);
https://github.com/dotnet/winforms/pull/10693#discussion_r1480614532.

For a detailed guide, refer to the Fluent Assertions documentation [here](https://fluentassertions.com/introduction).

2024-04-24 08:49 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        using var control = new ComboBox();
Please use target type new

using ComboBox control = new();

2024-04-24 08:49 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        Console.WriteLine($"MaxLength after setting to -1: {control.MaxLength}");
Maybe we can remove this line

2024-04-24 09:27 UTC, Zheng-Li01 requested changes

2024-04-24 09:27 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        Assert.NotEqual(IntPtr.Zero, control.Handle);
use target type new for this line

2024-04-25 01:39 UTC, Nora-Zhou01 commented
/azp run

2024-04-25 01:40 UTC, Epica3055 commented
/azp run

2024-04-26 01:00 UTC, SimonZhao888 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +    public void ComboBox_MaxLength_SetNegative_SetsToZero()
This test case is redundant because, you have already verified the out-of-range value in the other two test cases.
Please remove it.

And please try to merge the 2 test cases above.

2024-04-29 16:15 UTC, lonitra approved these changes
🚀

2024-04-30 14:18 UTC, merged