Add code coverage for ListView
dotnet/winforms pull request #11264
Opened 2024-04-24 08:37 UTC by MandiMan

Related #10453 

## Proposed changes

- Add unit tests for ListView to test its RightToLeftLayoutChanged event

## Customer Impact

- None

## Regression? 

- No

## Risk

- Minimal

## Test methodology 

- Unit tests

2024-04-24 09:02 UTC, Zheng-Li01 requested changes

2024-04-24 09:09 UTC, Zheng-Li01 requested changes

2024-04-24 09:09 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
> +
Please remove extra blank line 5968

2024-04-25 08:50 UTC, Zheng-Li01 requested changes

2024-04-25 08:50 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
> +
Remove the below code section, you maybe just need to add the` public new void OnRightToLeftLayoutChanged(EventArgs e) => base.OnRightToLeftLayoutChanged(e); `code line in the  `private class SubListView : ListView` class, which have been implemented in the ListViewTests.cs file

  public class TestListView : ListView
    {
        public new void OnRightToLeftLayoutChanged(EventArgs e) => base.OnRightToLeftLayoutChanged(e);
        public void InvokeOnRightToLeftLayoutChanged(EventArgs e)
        {
            base.OnRightToLeftLayoutChanged(e);
        }
    }

2024-04-26 00:55 UTC, SimonZhao888 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
> +    public void ListView_RightToLeftLayoutChanged_AddRemove_Success()
Please merge these two test cases because, they serve the same purpose.

2024-04-26 15:16 UTC, lonitra approved these changes

2024-04-26 15:16 UTC, merged