Enable nullability in TransparentBehavior
dotnet/winforms pull request #11298
Opened 2024-05-01 04:50 UTC by gpetrou

## Proposed changes

- Enable nullability in TransparentBehavior.

2024-05-03 03:09 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
>                  _controlRect = _designer.Control.RectangleToScreen(_designer.Control.ClientRectangle);
```suggestion
            if (_designer?.Control is { } control)
            {
                _controlRect = control.RectangleToScreen(_designer.Control.ClientRectangle);
```

2024-05-16 02:20 UTC, LeafShi1 commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
> +        internal TransparentBehavior(ControlDesigner designer) => _designer = designer.OrThrowIfNull();
The designer here can be changed to be nullable `ControlDesigner? designer` because `designer.OrThrowIfNull()` is added, so that you can avoid changing the Public method in `ControlBodyGlyph.cs`

2024-06-05 18:32 UTC, gpetrou commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
> +        internal TransparentBehavior(ControlDesigner designer) => _designer = designer.OrThrowIfNull();
This was suggested in https://github.com/dotnet/winforms/pull/11298#discussion_r1588480259. @lonitra should we revert the changes?

2024-06-05 21:54 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
> +        internal TransparentBehavior(ControlDesigner designer) => _designer = designer.OrThrowIfNull();
Hmm.. I see that `ControlBodyGlyph` constructor has nullable `ControlDesigner` as a param. To me it does not make much sense for the designer to be nullable. In all instances that we call `ControlBodyGlyph` constructor we ensure that it is called with nonnull designer value, so I am leaning towards that we need to change the constructor for `ControlBodyGlyph`'s `designer` value to be nonnullable. @Tanya-Solyanik , @KlausLoeffelmann are there any cases that I may be missing where a null `ControlDesigner` is valid when constructing a `ControlBodyGlyph`?

2024-06-12 00:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
> +        internal TransparentBehavior(ControlDesigner designer) => _designer = designer.OrThrowIfNull();
I don't think you are missing anything, this looks like an oversight in the previous changes, or a fallout from adding nullability chunk by chunk.

2024-06-12 01:21 UTC, LeafShi1 approved these changes

2024-06-12 01:51 UTC, LeafShi1 commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
> +        internal TransparentBehavior(ControlDesigner designer) => _designer = designer.OrThrowIfNull();
I see, when developers call `ControlBodyGlyph ` they should get a warning or suggestion that Designer cannot be null, and if they still force a null value, the exception will be caught here. This does make more sense.

2024-06-13 01:09 UTC, lonitra requested changes

2024-06-13 01:09 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
> +        internal TransparentBehavior(ControlDesigner designer) => _designer = designer.OrThrowIfNull();
Agree, fallout from adding nullability chunk by chunk seems to be likely what happened here. @gpetrou could we go ahead and update `ControlBodyGlyph`'s constructor to have nonnullable `ControlDesigner`?

2024-07-07 05:53 UTC, gpetrou commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
> +        internal TransparentBehavior(ControlDesigner designer) => _designer = designer.OrThrowIfNull();
Isn't that already done? Or you mean something else?

2024-07-10 19:49 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
> +            _designer?.OnDragLeave(e);
`_designer` is now never null here so I don't think we need the ? anymore

2024-07-10 19:50 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
> +        internal TransparentBehavior(ControlDesigner designer) => _designer = designer.OrThrowIfNull();
Oh, I thought it was not added yet, Apologies seems I had missed the change.

2024-07-23 16:18 UTC, lonitra approved these changes

2024-07-23 16:18 UTC, merged