Add unit test for DateTimePicker 12 properties
dotnet/winforms pull request #11385
Opened 2024-05-16 10:10 UTC by John-Qiao

related https://github.com/dotnet/winforms/issues/10453

## Proposed changes

- Add unit tests for below 6 events

1. CalendarFont
2. Checked
3. CustomFormat
4. DropDownAlign
5. MaxDate
6. MaximumDateTime
7. MinDate
8. MinimumDateTime
9. RightToLeftLayout
10. ShowUpDown
11. Text
12. Value

2024-05-21 04:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +public class DateTimePickerTests: IDisposable
I would prefer to create a new control in every test to be sure that we start in a clean state every time.

2024-05-21 06:40 UTC, Epica3055 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +    }
this is official site
> https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.datetimepicker.maximumdatetime?view=windowsdesktop-9.0
> 
> ## Remarks
> The maximum date is set to December 31, 9998.

I think we don't have to test it by using the same logic.

Maybe can simple write something like this: 
DateTimePicker.MinimumDateTime.Should().Be(new DateTime(December 31, 9998));

what do you think @Tanya-Solyanik

2024-05-21 07:26 UTC, LeafShi1 requested changes

2024-05-21 07:26 UTC, LeafShi1 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +        result.Should().Be(expectedDate);
It is enough to verify that `MinimumDateTime` is in the correct range

`Assert.True(DateTimePicker.MinimumDateTime >= new DateTime(1753, 1, 1, 0, 0, 0));`

2024-05-21 07:26 UTC, LeafShi1 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +        _dateTimePicker.Value.Should().Be(DateTime.Parse(validDateString, CultureInfo.CurrentCulture));
Why not verify the value of the `_dateTimePicker.Text`?

2024-05-21 19:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +public class DateTimePickerTests: IDisposable
XUnit creates the new test class object before running the test, but I don't know if we are guaranteed that Dispose is called in the case of an exception, or if constructor is called on the same thread the test executes on.

2024-05-21 19:46 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +    }
It's possible that the min date is different on different cultures, I think it's ok to keep the more defensive logic.

2024-05-22 18:52 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +public class DateTimePickerTests: IDisposable
I see that Dispose pattern is recommended by xUnit, and we are not creating control in the test constructor, so the handle is not created, that will be safe to use.

2024-05-27 09:28 UTC, John-Qiao commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +    }
According to Tanya's suggestion, still using that original codes.

2024-05-29 07:23 UTC, LeafShi1 commented
LGTM! @lonitra Please review this PR

2024-05-29 21:58 UTC, lonitra reviewed
Few small comments, otherwise LGTM!

2024-05-29 21:58 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +        var expectedDate = new DateTime(2022, 12, 31);
Please use target type new
```suggestion
        DateTime expectedDate = new(2022, 12, 31);
```

2024-05-29 21:58 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +        var expectedDate = new DateTime(2022, 1, 1);
```suggestion
        DateTime expectedDate = new(2022, 1, 1);
```

2024-05-29 21:58 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +        var expectedDate = new DateTime(2022, 1, 1);
Ditto here as well

2024-05-29 21:58 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +    }
```suggestion
    public DateTimePickerTests() => _dateTimePicker = new();
```

2024-05-29 21:58 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
> +    }
```suggestion
    public void Dispose() => _dateTimePicker.Dispose();
```

2024-05-30 09:40 UTC, LeafShi1 approved these changes

2024-05-30 16:17 UTC, lonitra approved these changes
Thank you!

2024-05-30 16:17 UTC, merged