Added an opt-in switch to use BinaryFormater.Deserialize in Clipboard get methods.
dotnet/winforms pull request #11526
Opened 2024-06-12 23:07 UTC by Tanya-Solyanik

The switch is not fully used up yet. It requires that app opt's in into binary formatter use globally.

2024-06-13 04:14 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/runtimeconfig.template.json
> +    "Switch.System.Windows.Forms.NoClientNotifications": false,
No, they are already in use, at least the second one is in use in the designer repo.

2024-06-13 04:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/SafeRestrictiveBinder.cs
> +internal class SafeRestrictiveBinder : SerializationBinder
Switch allows use of BF.Deserialize with the unsafe binder. It can be used when porting an app with the "old" APIs to NET9 and making it BF-safe with a single switch with no recompile. 
Clipboard.GetData APIs are always using the unsafe binder behind the scenes and can be controlled by this appcompat switch.
Clipboard.TryGetData APIs that don't take a custom binder parameter, always use the safe binder. They are used for a new app that wants to be safe. Theoretically this should be equivalent to skipping BF.Deserialize, but I don't know how to prove that. This binder also makes the implementation simpler as we always have a binder parameter. Also, because the switch does not control this binder, the same application can use both the old and the new APIs. This sounds inconsistent, but I'm thinking of 3rd party dlls that are not under the app author control and should be backward compatible. 
Clipboard.TryGet API that takes a custom binder is controlled only by the "global" app compat switch. This is for a new app, or for a ported app that is being recompiled and wants to deserialize a hashtable with a custom comparer (I had not double-checked that yet).
So far comments in the code are for tracking what I want to do next, i'll edit them when we have a better picture.
What you are saying is a clearer model, but we might need more flexibility.

2024-06-13 16:54 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/SafeRestrictiveBinder.cs
> +internal class SafeRestrictiveBinder : SerializationBinder
I see, thanks laying out some of the details here! I can see that always having a binder does make the implementation simpler and I think with either approach we are ultimately achieving what we want here, but I agree it'll be clearer when we get a better picture and other changes are out.

2024-06-13 16:55 UTC, lonitra approved these changes

2024-06-13 18:03 UTC, JeremyKuhne requested changes
We'll want to update this to a static helper class that has static `Func<TypeName, Type>` methods.

We'll need an internal `SerializationBinder` that takes said `Func<TypeName, Type>` and creates the `TypeName` based on the string arguments.

2024-06-13 18:03 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/SafeRestrictiveBinder.cs
> +internal class SafeRestrictiveBinder : SerializationBinder
Seal the class

2024-06-13 20:34 UTC, Tanya-Solyanik commented
>We'll want to update this to a static helper class that has static Func<TypeName, Type> methods.

Yeah, I updated this branch and then push was incomplete and I didn't notice it. This is why I pinged the thread for a review.

2024-06-14 15:27 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/UnsafeCompatibleBinder.cs
> +internal class UnsafeCompatibleBinder : SerializationBinder
removed this class

2024-06-14 17:26 UTC, lonitra approved these changes
👍

2024-06-14 18:04 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/SafeRestrictiveBinder.cs
> +internal class SafeRestrictiveBinder : SerializationBinder
not applicable

2024-06-14 18:05 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/UnsafeCompatibleBinder.cs
> +    internal static readonly UnsafeCompatibleBinder s_instance = new ();
removed this code

2024-06-14 21:12 UTC, JeremyKuhne requested changes
Added some feedback. It is a little odd to approve this without the consuming code. I presume you'll add additional commits with the rest of the implementation.

2024-06-14 21:12 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ClipboardHelper.cs
> +    internal static Func<TypeName, Type> SafeResolver { get; } = (typeName) =>
I believe the best way to do this is simply have static methods:

``` C#
internal static Type NotSupportedResolver(TypeName typeName) => throw new ...
```

Don't say that it is safe, just say what it does.

2024-06-14 21:12 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ClipboardHelper.cs
> +internal static class ClipboardHelper
There is no need for this to get its own class, just put it in `Clipboard`.

2024-06-14 21:12 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ClipboardHelper.cs
> +        if (!Switches.ClipboardEnableUnsafeBinaryFormatterDeserialization)
It is unclear that this would be the best place for the switch check.

2024-06-14 21:12 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ClipboardHelper.cs
> +    /// <exception cref="NotSupportedException"></exception>
If you don't think a comment is needed for this XML block, then close it `/>`

2024-06-14 21:47 UTC, closed without merging