Adding new TryGet methods to Clipboard, DataObject and IDataObject.
dotnet/winforms pull request #11545
Opened 2024-06-18 07:51 UTC by Tanya-Solyanik

The existing GetData methods now call the new ones. TryGetData methods will fall back to use BinaryFormatter if a binder is provided. The GetData methods will use a binder that allows BInaryFormater to resolve all types is the application sets EnableUnsafeBinaryFormatterDeserialization AppContext switch to true, by default this switch is `false`.

2024-06-18 22:16 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +            private static T? GetObjectFromDataObject<T>(Com.IDataObject* dataObject, string format, Func<TypeName, Type> resolver, out bool doNotContinue, out MemoryStream? stream)
Could we add some more comments detailing what it means when memory stream is null vs. nonnull

2024-06-18 22:16 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        TryGetDataInternal(DataFormats.Bitmap, Resolver, autoConvert: true, out Image? image);
It it hard to tell from reviewing on GitHub, but double checking we will not run into issue of not returning anything since `Image` is abstract?

2024-06-18 22:16 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                    return false;
My 2 cents here is that we should throw instead of failing silently in this case since it is not very intuitive that the T should not be an unbounded type.

2024-06-18 22:16 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> + ((ComTypes.IDataObject)_innerData).SetData(ref pFormatetcIn, ref pmedium, fRelease);
nit: indent

2024-06-18 23:43 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormattedObjectExtensions.cs
> +        switch (format.RootRecord)
I'm not sure if I should process RootRecords that are `BinaryObjectString` or other types

2024-06-18 23:47 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormattedObjectExtensions.cs
> +                return (typeName, assemblyName) == GetNamesFromTypeName(name);
I intended to call `GetNamesFromTypeName` from `GetNamesFromType(Type type)`.

2024-06-19 13:47 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        TryGetDataInternal(DataFormats.Bitmap, Resolver, autoConvert: true, out Image? image);
This will fail unless the app opted in into the unbounded resolver.  This is desirable, as a custom class derived from the Image could have an object-typed or delegate field. We could add a GetBitmap method assuming that bitmaps are the most common images.

2024-06-19 20:34 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        TryGetDataInternal(DataFormats.Bitmap, Resolver, autoConvert: true, out Image? image);
Would it be better for `GetImage` to call `TryGetDataInternal` with `Bitmap` as the T? At a glance, I don't think we ever serialize other `Image` types besides `Bitmap` even with BinaryFormatter due to the existing `BitmapBinder`. -- well unless users call SetData with a format that isn't `DataFormats.Bitmap`, but for GetImage() we had always been calling the internal get method with `DataFormats.Bitmap` so we seem to always be expecting `Bitmap` here.

2024-06-20 18:01 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
>                  return format switch
It might be clearer to do an initial check that `T` matches the built-in types and bail if it does not.

2024-06-20 18:04 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                            if (resolver != Clipboard.UnboundedResolver && !binaryFormattedObject.Contains<T>())
You really shouldn't be checking the `UnboundedResolver` everywhere. If `<T>` is `object`, you don't need to check anything. You should have guarded against that in the entry points.

2024-06-20 18:07 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                            if (binaryFormattedObject.TryGetObject(out object? value))
You shouldn't be getting the object out before you check `<T>`.

2024-06-20 18:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                            value = binaryFormattedObject.Deserialize();
You will never get null from this.

2024-06-20 18:10 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        TryGetDataInternal(DataFormats.Bitmap, Resolver, autoConvert: true, out Image? image);
I see what you mean, BitmapBinder was an opt-in in .NET Framework, but since it's been in the .NET Core for a long time now, we can assume that Bitmaps are the only images that we support.

2024-06-20 18:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                                catch (NotSupportedException)
Should we be catching this? I don't think so?

2024-06-20 18:19 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                                if (!binaryFormattedObject.TryGetRootTypeName(out TypeName? name))
I don't think this should be a "Try", you should always be able to get the root type name. We should be able to read almost any object that we put on the clipboard.

2024-06-20 18:22 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                                return CastOrDefault(value);
Value should be what you checked for, you should have asserts to that effect.

2024-06-20 18:41 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        TryGetDataInternal(DataFormats.Bitmap, Resolver, autoConvert: true, out Image? image);
Then perhaps the failure to serialize and deserialize Metafile should not be silent?

2024-06-20 20:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                            if (binaryFormattedObject.TryGetObject(out object? value))
But we know that TryGetObject is safe.

2024-06-21 00:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/IDataObject.cs
> +        TryGetData(format, resolver: Clipboard.NotSupportedResolver, autoConvert, out data);
But the default implementation will always depend on the custom implementation of IDataObject.GetData, this check will not make it secure

2024-06-21 01:14 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
>                  return format switch
I had a check in the entry point in this class, but it looked like a code duplication between these 2 places, at this spot this switch and casts are required even if I matched types to Formats. Initial check would skip the interop calls to QueryGetData and GetData.

2024-06-21 01:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                        ? CastOrDefault(ReadStringFromHGLOBAL(hglobal, unicode: false))
I'm using pattern matching to convert `string` to `T`.

2024-06-21 01:36 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                static bool IsString() => typeof(T) == typeof(string);
removed them.

2024-06-21 02:01 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +            private static bool IsUnbounded(Type type) => type.IsInterface || type.IsAbstract || type == typeof(object);
Should I test `IsSealed` instead of `== typeof(object)`?

2024-06-21 02:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +            private static bool IsUnbounded(Type type) => type.IsInterface || type.IsAbstract || type == typeof(object);
>If you have a resolver it doesn't matter what the type is

Do I understand this correctly?

Clipboard.TryGetData(format, resolver, autoConvert, out data)
or
DataObject.TryGetData(format, resolver, autoConvert, out data)

and (resolver != null)

Then don't look at the type here, resolver will get the concrete type.

If I move this check to the entry point in DataObject.cs, I will also block IDataObject methods in DataStore class. Is this desirable? That store is a dictionary and never serializes anything.

2024-06-21 03:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                                catch (NotSupportedException)
Makes sense, BinaryFormatter wouldn't catch the same exception thrown from the Binder

2024-06-21 03:50 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/IDataObject.cs
> +        if (GetData(format, autoConvert) is T result)
Our DataStore class implements IDataObject, and I didn't add the new methods to it. That class is tested in DataObjectTests.cs. The only new tests in that class would be related to new exceptions when using NotSupportedResolver and object type. The new exceptions would make DataObject class behave consistently regardless of what the inner object it. So far, I haven't added them as they are not making the code more secure.

2024-06-21 15:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                                if (!binaryFormattedObject.TryGetRootTypeName(out TypeName? name))
I don't know what kind of a record the root record could be, is there a way to read type information from a record, or should I read it for each record type individually?

2024-06-21 16:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                            if (resolver != Clipboard.UnboundedResolver && !binaryFormattedObject.Contains<T>())
Unbounded resolver always returns null and can't be used to get type for IsAssignableTo test.

2024-06-21 19:23 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                data = GetObjectFromDataObject<T>(nativeDataObject, format, resolver, out bool doNotContinue, out MemoryStream? stream);
We are reading HGLOBAL as a MemoryStream in ReadByteStreamFromHGLOBAL

2024-06-24 17:55 UTC, JeremyKuhne requested changes
Added some more comments. I'm a little concerned that we're using TypeName where it isn't necessary in some cases. We should optimize this before we fully validate this as changing it afterwords would be risky.

I still need to spend more time reviewing.

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/BinaryFormat/WinFormsArrayRecordExtensions.cs
> +        return primitiveArray.PrimitiveType switch
This is going to be hugely expensive. We should at least cache these. An array of `TypeName[]` or `TypeName?[]` where you lazily fill in everything or each when needed.

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormattedObjectExtensions.cs
> +            TypeName parsed = TypeName.Parse($"{type.FullName}, {GetAssemblyShortName(type)}");
Why are we doing this? It seems wasteful. Why can't you just get the strings directly from the `Type`?

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ComposedBinder.cs
> +        TypeName parsed = TypeName.Parse($"{type.FullName}, {type.Assembly.FullName}");
Is this actually necessary? Why aren't we just using the properties of `Type`?

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ComposedBinder.cs
> +        TypeName parsed = TypeName.Parse($"{typeName}, {assemblyName}");
If we could do this only when we call the nested resolver that would help performance.

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                object? ReadObjectOrStreamFromHGLOBAL(HGLOBAL hglobal, bool restrictDeserialization)
Why did you remove the `static`? Generally, it is preferable to have these be static for perf and clarity on coupling.

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                    object? ReadObjectFromStreamDeserializer(MemoryStream stream, bool restrictDeserialization)
Why did you nest again? Is it really necessary to create another method here?

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                            binaryFormattedObject = new(stream);
`BinaryFormattedObject` needs a binder just as `BinaryFormatter` does as you're calling `Deserialize` on it. The binder setting should be made mutable so you can do this when you get to the `Deserialize` and not take the cost of creating the binder until you actually deserialize.

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                        object? ReadObjectWithBinaryFormatterDeserializer()
Make it static, don't nest so deep.

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                            // TanyaSo: Can BF do better than BFO did?.
It can handle some things that BFO cannot. Most notably, more complicated `IObjectReference` graphs.

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                        bool TryGetRootType([NotNullWhen(true)] out Type? type)
Again, try to use static methods.

2024-06-24 17:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/IDataObject.cs
> +        if (GetData(format, autoConvert) is T result)
You should still have explicit tests just for the interface and the default methods.

2024-06-24 18:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                    if (data is null && stream is T t)
refactored the code

2024-06-24 18:43 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ComposedBinder.cs
> +        TypeName parsed = TypeName.Parse($"{type.FullName}, {type.Assembly.FullName}");
I thought that TypeName normalizes names.

2024-06-24 19:07 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/BinaryFormat/WinFormsArrayRecordExtensions.cs
> +        return primitiveArray.PrimitiveType switch
Can we cache type and assembly name on the record when we are parsing it?

2024-06-24 19:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                object? ReadObjectOrStreamFromHGLOBAL(HGLOBAL hglobal, bool restrictDeserialization)
I need to capture one of the variables, I think the resolver in particular.

2024-06-24 19:36 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                    object? ReadObjectFromStreamDeserializer(MemoryStream stream, bool restrictDeserialization)
I only renamed the existing method, it was nested already, the new one is the one that calls the binary formatter.

2024-06-24 20:14 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                        object? ReadObjectWithBinaryFormatterDeserializer()
Gladly! All these were static in .NET Framework, someone nested them in Core, I had un-nested some of them in fact.

2024-06-24 21:26 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/BinaryFormat/WinFormsArrayRecordExtensions.cs
> +        return primitiveArray.PrimitiveType switch
They have their type and assembly name, I'm not sure why that can't be a direct string comparison instead of going through `TypeName`.

2024-06-24 21:28 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ComposedBinder.cs
> +        TypeName parsed = TypeName.Parse($"{type.FullName}, {type.Assembly.FullName}");
It breaks apart string type descriptions, but I don't think you can get more canonical than what is on `Type` itself.

2024-06-24 21:28 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                object? ReadObjectOrStreamFromHGLOBAL(HGLOBAL hglobal, bool restrictDeserialization)
Pass the resolver.

2024-06-24 21:30 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                    object? ReadObjectFromStreamDeserializer(MemoryStream stream, bool restrictDeserialization)
Try not to nest methods more than once inside methods. When our nesting gets more than 4 or 5 levels deep it really increases comprehension difficulty.

2024-06-24 21:31 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                        object? ReadObjectWithBinaryFormatterDeserializer()
Static nested methods to be clear. They should still be encapsulated, but you don't need to make them instances. Just try not to nest methods more than one level deep.

2024-06-24 21:50 UTC, JeremyKuhne requested changes
We should not be falling into the default interface implementations for our own types that derive from `IDataObject`.

2024-06-24 21:50 UTC, JeremyKuhne commented on Directory.Build.props
> +    <LangVersion Condition="'$(LangVersion)' == ''">preview</LangVersion>
Why change this?

2024-06-24 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            DataFormats.OemTextConstant => typeof(string).IsAssignableTo(typeof(T)),
`typeof(T) == typeof(string)` is the right check here.

2024-06-24 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            CF_DEPRECATED_FILENAMEW => typeof(string[]).IsAssignableTo(typeof(T)),
`typeof(string[]) == typeof(T)`

2024-06-24 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            DataFormats.BitmapConstant or BitmapFullName => typeof(Bitmap).IsAssignableTo(typeof(T)),
This would optimize better if you checked both possibilities: `typeof(Bitmap) == typeof(T) || typeof(Image) == typeof(T)`

2024-06-24 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +        bool FormatSupportsType() => format switch
Consider putting this inline for clarity or coming up with a clearer name.

2024-06-24 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            null => false,
Should never be `null`

2024-06-24 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            && (resolver is null || resolver == Clipboard.NotSupportedResolver)
Why are we checking null here? We aren't taking `Func<TypeName, Type>?`

2024-06-24 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            // TanyaSo - should I test IsSealed instead of == typeof(object)?
I presume no, `IsSealed` should return `false` for concrete types that are not `sealed`.

2024-06-24 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/IDataObject.cs
> +        if (GetData(format, autoConvert) is T result)
`DataStore` _should_ implement the new methods. We should not be falling back to the default implementation anywhere in our own code outside of tests.

2024-06-24 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            && (resolver is null || resolver == Clipboard.NotSupportedResolver)
There has to be a better way to deal with checking the case of `== NotSupportedResolver`. We should be able to pass the needed context or check higher up the stack.

2024-06-24 22:46 UTC, Tanya-Solyanik commented on Directory.Build.props
> +    <LangVersion Condition="'$(LangVersion)' == ''">preview</LangVersion>
preview does not work with VB projects, other wise

2024-06-24 22:55 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            // TanyaSo - should I test IsSealed instead of == typeof(object)?
Should I test `!type.IsSealed` instead of `type == typeof(object)`?

2024-06-24 22:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            && (resolver is null || resolver == Clipboard.NotSupportedResolver)
Yes, we can get a null from here - 

```
            bool IDataObject.TryGetData<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] T>(
                string format,
                Func<TypeName, Type> resolver,
                bool autoConvert,
                [NotNullWhen(true), MaybeNullWhen(false)] out T data)
                => TryGetDataInternal(format, resolver, autoConvert, out data);
```

2024-06-24 23:01 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            && (resolver is null || resolver == Clipboard.NotSupportedResolver)
I preferred having a single verification function, otherwise there will be slight differences in verification code in each entry point.

2024-06-24 23:08 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                    object? ReadObjectFromStreamDeserializer(MemoryStream stream, bool restrictDeserialization)
I didn't add nesting.

2024-10-11 20:42 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/IDataObject.cs
> +        if (GetData(format, autoConvert) is T result)
Added IDataObjectTests file

2024-10-11 23:03 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
> +                            binaryFormattedObject = new(stream);
Not applicable to NrbfDecorder, it does not deserialize payload

2024-10-15 22:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs
> +    public void RoundTripOfType_TestData_CustomResolver()
@lonitra  - FYI

2024-10-16 01:07 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
> +        DateTime date = DateTime.Now;
@lonitra  - I wonder what is the difference between your test and this one...

2024-10-16 15:38 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
> +        DateTime date = DateTime.Now;
Difference is when trying to get the data off of the clipboard BinaryFormatter is disabled.

2024-10-18 19:36 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs
> +        var result = RoundTripOfType<TestDataBase>(value, TestDataResolver).Should().BeOfType<TestData>().Subject;
@lonitra  - users can do this, but it requires a more complex resolver, we would recommend users to have classes like on line 571

2024-10-18 22:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
> +                SerializationBinder binder = restrictDeserialization
@GrabYourPitchforks  - this is the method we are talking about

2024-11-07 20:24 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
> +#if false // TODO(TanyaSo) - modify TryGetObjectFromJson to take a resolver and rename to HasJsonData???
@lonitra  - fyi

2024-11-12 01:45 UTC, JeremyKuhne requested changes
Some initial comments, I'll look more at this tomorrow

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///  This is a safer alternative to <see cref="GetData(string)"/> that does not use <see cref="BinaryFormatter"/> to deserialize the payload.
This statement doesn't seem true- this will use the BinaryFormatter if available.

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    /// </summary>
What does the return value mean?

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        if (GetDataObject() is ITypedDataObject dataObject)
I would think that this should throw `NotSupportedException` if the data object doesn't support `ITypedDataObject`.

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///  <paramref name="resolver">
This block should be a top level `<param>`, not a `<paramref>`.

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
Perhaps better as `string[]`?

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +#pragma warning disable CS3001 // Argument type is not CLS-compliant
We should mark the assembly as not CLS-compliant. It doesn't really matter anymore and we're having to put stuff in like this.

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    /// </example>
The return value isn't defined.

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        if (GetDataObject() is ITypedDataObject dataObject)
I would presume this should throw NotSupported if not ITypedDataObject as discussed above. We should also comment on SetData about needing to support `ITypedDataObject`. The SetData could get an analyzer perhaps that would help validate.

We may want to alternatively consider just throwing from SetData if we fall out of the ITypedDataObject paths and provide some sort of compat switch that allows passing in things that don't implement.

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        IDataObject? data = GetDataObject();
This looks like a repeated pattern that should be put in a helper like `GetLegacyData<T>(...)`

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataFormats.cs
> +        ArgumentException.ThrowIfNullOrWhiteSpace(format, nameof(format));
This is unnecessary. It already grabs the name.

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.BitmapBinder.cs
> +        private static ImmutableArray<byte> AllowedTokenArray => AllowedToken.ToImmutableArray();
This is unnecessary and has negative perf implications. Just use the span.

2024-11-12 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.BitmapBinder.cs
> +        [RequiresUnreferencedCode("Calls System.Reflection.Assembly.GetType(String)")]
This doesn't call `GetType` or use unreferenced code. When we know we aren't doing this sort of thing we shouldn't flow this general catch all annotation.

What I would consider is creating another interface that isn't attributed and create a deserializer overload that suppresses the warnings. That is what I was planning to do with this anyway.

2024-11-12 02:43 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        if (GetDataObject() is ITypedDataObject dataObject)
DataObjectExtensions throw NotSupportedException, it makes sense to do the same thing.

2024-11-12 03:04 UTC, JeremyKuhne commented
Implements #12362

2024-11-12 03:15 UTC, JeremyKuhne requested changes
Another batch of comments

2024-11-12 03:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DragDropHelper.cs
> +            && dataObject.TryGetData(PInvoke.CFSTR_INDRAGLOOP, out DragDropFormat? dragDropFormat))
This can throw if the data does not support ITypedDataObject, right?

2024-11-12 03:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.DataStore.cs
> +    private class DataStore : IDataObject, ITypedDataObject
Don't know why we didn't seal this, but we should.

2024-11-12 03:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.cs
> +        #region ITypedDataObject
Probably should make these public so we don't have to cast to `ITypedDataObject` as we store `Composition` itself in the `DataObject`. Probably the same for `IDataObject`?

2024-11-12 03:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        if (GetDataObject() is ITypedDataObject dataObject)
SetData does not work with IDataObject, it takes raw data, and SetDataObject is not virtual and creates the concrete DataObject type. Please clarify your comment

2024-11-12 18:17 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
You might want to avoid the `!`. One thing to consider here is creating a `TypeName` array off the types as this would be a pretty common scenario I think (for partial comparison). We don't have to show anything other than full comparison, but if this is where they start, doing partial compares might be easier. @adamsitnik Any thoughts on our canonical example for this??

2024-11-12 18:46 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.BitmapBinder.cs
> +        private static ImmutableArray<byte> AllowedTokenArray => AllowedToken.ToImmutableArray();
Further clarification here: When using the pattern of `static ReadOnlySpan<byte> Value => [];` you get a wrapped pointer to the raw resource in the loaded .dll image. No heap object is created.

2024-11-12 18:54 UTC, lonitra reviewed
Got through about half

2024-11-12 18:54 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
> +                    && LocalAppContextSwitches.ClipboardDragDropEnableNrbfSerialization
Why do we want a switch to allow for nrbf deserialization for new APIs?

2024-11-12 18:54 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +            private static object? ReadObjectOrStreamFromHGLOBAL<T>(HGLOBAL hglobal, Func<TypeName, Type>? resolver, bool restrictDeserialization, bool legacyMode)
Consider making this a local function again since it is only used in the method above.

2024-11-12 18:54 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +                    if (typeof(Bitmap).IsAssignableTo(typeof(T)) && TryGetBitmapData(dataObject, format, out Bitmap? bitmap))
Should this be the following? Bitmap is sealed type.
```suggestion
                    if (typeof(Bitmap) == typeof(T) && TryGetBitmapData(dataObject, format, out Bitmap? bitmap))
```

2024-11-12 20:01 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +            private Type? GetType(string assemblyName, string fullTypeName, TypeName? typeName)
GetKnownType might be clearer

2024-11-12 20:02 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +            public Binder(Type type, Func<TypeName, Type>? resolver, bool legacyMode)
Comments on these, especially what is `legacyMode`?

2024-11-12 20:03 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +            internal static bool Matches(Type type, TypeName typeName)
@adamsitnik copied blob :)

2024-11-12 20:06 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +            ///   If <paramref name="dataObject"/> contains <see cref="MemoryStream"/> that contains a serialized object,
nit: indent

2024-11-12 20:07 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +            /// <remarks>
Should probably be `<returns>`

2024-11-12 20:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            DataFormats.TextConstant or
`or` should be at the front of the lines and indented

2024-11-12 20:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +        or BitmapFullName
indent `or`

2024-11-12 20:12 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +    internal static bool ValidateTryGetDataArguments<T>(string format, Func<TypeName, Type> resolver)
This should be combined with the next method and could stand to have a brief summary as "Validate" is pretty generic.

2024-11-12 20:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
@JeremyKuhne  - I think `!` helps making this sample more concise, user will not use the FullName property anyway, they will hardcode in the string.

@adamsitnik  - is it possible to make your Matches method public for use in this method -  https://github.com/dotnet/runtime/blob/5d69e2dca30524a93b00cd613be218144b5f95d1/src/libraries/System.Formats.Nrbf/src/System/Formats/Nrbf/SerializationRecord.cs#L54

2024-11-12 21:04 UTC, JeremyKuhne requested changes

2024-11-12 21:04 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.DataStore.cs
> +            if (_data.TryGetValue(format, out DataStoreEntry? dse) && dse.Data is T t)
Can this be `is T data`? Should probably change `_data` to `_mappedData` for clarity.

2024-11-12 21:10 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
@Tanya-Solyanik ideally they _should_ use `TypeName` so they match the right components if looking at individual pieces so they don't compare apples and oranges. I'd rather push them towards correct.

2024-11-12 22:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +        if (GetDataObject() is ITypedDataObject dataObject)
`Anyone looking at this would assume that it could sometimes not be ITypedDataObject`
I think it won't be a read ITypedDataObject when copy/pasting between .NET Framework and NET10 and I don't think i'm handling that correctly

`This dependency should be easily observable in the code- GetDataObject() should return the concrete type or we should introduce our own internal interface `

Are you suggesting an internal version of GetDataObject?

2024-11-12 22:45 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ITypedDataObject.cs
> +public interface ITypedDataObject
API review explicitly mentioned that it's an add -on interface

2024-11-12 22:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +                    if (typeof(NotSupportedException).IsAssignableTo(typeof(T)))
When do we call this with T = NotSupportedException?

2024-11-12 22:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +                        bool ITypedDataObject.TryGetData<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] T>(
nit: indentation seems to be off

2024-11-12 22:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.DataStore.cs
> +        public virtual bool TryGetData<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] T>(
Should these be non virtual?

2024-11-12 22:51 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +    protected virtual bool TryGetDataCore<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] T>(
This seems like it should be made private or internal.

2024-11-12 22:51 UTC, lonitra commented on src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
> +// [UISettings(MaxAttempts = 3)] // Try up to 3 times before failing.
Perhaps not an intentional change?

2024-11-12 22:51 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs
> +        var result = Utilities.ReadObjectFromStream<object>(
Should results be validated here?

2024-11-12 22:51 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs
> +    private const float Delta = 0.0003f;
Consider placing this inside TestData class

2024-11-13 00:09 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
> +                    && LocalAppContextSwitches.ClipboardDragDropEnableNrbfSerialization
This is more secure than BinaryFormatter, but it still loads assemblies, users might want to control that.

2024-11-13 00:10 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +            private static object? ReadObjectOrStreamFromHGLOBAL<T>(HGLOBAL hglobal, Func<TypeName, Type>? resolver, bool restrictDeserialization, bool legacyMode)
I had considered it, but indentation really makes this hard to read. Are you sure?

2024-11-13 00:59 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
> +                    return false;
This is the case when we couldn't verify if type is assignable to T, I think we should return false. Otherwise resolver should resolve all possible types, which is impossible or we would always throw on type mismatch. Exception is more suitable for when serialization fails.

2024-11-13 01:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +                { "System.Byte", typeof(byte) },
Why do you think that TypeName is a better option - TypeName class does not expose functions to compare TypeNames

2024-11-13 01:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +            private Type? GetType(string assemblyName, string fullTypeName, TypeName? typeName)
This method calls resolver, it's not resolving only the known types

2024-11-13 02:42 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +    internal static bool ValidateTryGetDataArguments<T>(string format, Func<TypeName, Type> resolver)
`IsUnboundedType` is used in 2 spots, it should not be combined with Validate.

2024-11-13 03:10 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +                if (_resolver is null)
Are you sure that it makes sense to break up this method? I'm using the short name for both known type and user type lookup and these 2 methods are always called together.

2024-11-13 03:13 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.DataStore.cs
> +            if (_data.TryGetValue(format, out DataStoreEntry? dse) && dse.Data is T t)
`is T data` would be a second declaration of `data` as a local variable , while it's already a function parameter

2024-11-13 20:28 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.BitmapBinder.cs
> +        [RequiresUnreferencedCode("Calls System.Reflection.Assembly.GetType(String)")]
What do you think about adding a parameter that controls if `GetType` method throws or not?

2024-11-13 20:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DragDropHelper.cs
> +            && dataObject.TryGetData(PInvoke.CFSTR_INDRAGLOOP, out DragDropFormat? dragDropFormat))
removed

2024-11-13 21:24 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ITypedDataObject.cs
> +public interface ITypedDataObject
It is still an "add-on" interface. What we didn't want to do is have these methods directly on `IDataObject`.   `ITypedDataObject : IDataObject` is what I'm reflecting on. The question is whether or not there is ever a case where you would implement `ITypedDataObject` and _not_ `IDataObject`.

When we're taking `object` as a parameter, what does it mean when it has `ITypedDataObject` but **not** `IDataObject`? What is the user experience there? Are consumption failures going to be obvious? If our guidance is to always implement both, why would we not capture that in the interface?

2024-11-13 22:21 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
> +                    && LocalAppContextSwitches.ClipboardDragDropEnableNrbfSerialization
The second switch now controls if we use only BinaryFormatter for compatibility

2024-11-13 22:45 UTC, JeremyKuhne requested changes
More comments

2024-11-13 22:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +                { "System.Byte", typeof(byte) },
Because then you are comparing the right components- it is the whole point of TypeName. String comparison is fraught with errors.

2024-11-13 23:14 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.TypeNameComparer.cs
> +            public int GetHashCode(TypeName obj)
I can't use the full name as an identity because it could contain assembly name in collections, for example, that might be type-forwarded to another assembly.

2024-11-14 02:13 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.TypeNameComparer.cs
> +            public int GetHashCode(TypeName obj)
`Where did this come from?` - I didn't find anything in the runtime.. Do you have suggestions where to search?

2024-11-14 02:13 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +    private static bool IsUnboundedType<T>()
I made it a local function

2024-11-14 02:23 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +    /// <devdoc>
Oops, I'm not throwing for invalid format

2024-11-14 02:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +    /// <devdoc>
Not throwing is consistent with this:
```
    public static object? GetData(string format) =>
        string.IsNullOrWhiteSpace(format) ? null : GetData(format, autoConvert: false);
```

2024-11-14 22:07 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +                    if (typeof(NotSupportedException).IsAssignableTo(typeof(T)))
Makes sense, but IIUC I don't think we ever call this method with T = NotSupportedException so we will never get into this if statement.

2024-11-15 11:06 UTC, adamsitnik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +                { "System.Byte", typeof(byte) },
> TypeName class does not expose functions to compare TypeNames

It does not, because different users want to compare different parts of type name. Some want to compare just the full names, some want to include assembly names, but without version. Some want to make it always a full match.

For example, `SerializationRecord.TypeNameMatches` ignores assembly names: https://github.com/dotnet/runtime/blob/5d69e2dca30524a93b00cd613be218144b5f95d1/src/libraries/System.Formats.Nrbf/src/System/Formats/Nrbf/SerializationRecord.cs#L48

So we decided to not include any default comparison method just to force all the users to think what they want to compare and implement it themselves.

2024-11-15 11:35 UTC, adamsitnik reviewed
I provided the answers to all the questions, please feel free to tag me again.

2024-11-15 11:35 UTC, adamsitnik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
> Any thoughts on our canonical example for this??

The main gotchas here are:
- different assembly versions. Example: the user has persisted and instance of `MyClass1` using an older version of the same assembly: `MyClass1, MyAssembly, Version=1.0.0.0` vs `MyClass1, MyAssembly, Version=2.0.0.0`. Full name does not include the version for all the type names except of generic types.
- type forwarding ([how to get it](https://github.com/dotnet/runtime/blob/e5129e5323155feec25cd75e8d67986b601921d1/src/libraries/System.Formats.Nrbf/tests/TypeExtensions.cs#L12)). I am not sure how common it is for the end users to use it, but it's quite common in runtime for the most basic types. Example: https://github.com/dotnet/runtime/blob/e5129e5323155feec25cd75e8d67986b601921d1/src/libraries/System.Private.CoreLib/src/System/DateTime.cs#L48

For both cases, it gets really tricky for generic types, where `typeof(T).FullName` is different than the name exported by binary formatter (because full name of the generic type includes the assembly names of generic type arguments). That is why I was pushing so hard to include `SerializationRecord.TypeNameMatches` in the public API (so the users would not need to worry about it).

So as long as you don't expect generic types with generic arguments, the example is fine. If you expect them to be common, you could extend the comparison to do something similar to https://github.com/dotnet/runtime/blob/5d69e2dca30524a93b00cd613be218144b5f95d1/src/libraries/System.Formats.Nrbf/src/System/Formats/Nrbf/SerializationRecord.cs#L68.

And BTW it's great that you return the type itself, as it avoids the possibility to load a hostile assembly. Example: if we have a `Type`: "MyClass1, MyNiceAssembly" and a type name "MyClass1, HostileAssembly", the full names match and returning the type avoids loading the `HostileAssembly`, which users could do with 

```diff
if (type.FullName == typeName.FullName)
{
-    return type;
+    return Type.GetType(typeName.AssemblyQualifiedName);
}
```

>  is it possible to make your Matches method public for use in this meth

The method you have referenced (`SerializationRecord.TypeNameMatches`) is already public, but from the context I guess that you meant the helper method that it calls with `TypeName` and `Type` arguments which makes it unrelated to `SerializationRecord`:

https://github.com/dotnet/runtime/blob/5d69e2dca30524a93b00cd613be218144b5f95d1/src/libraries/System.Formats.Nrbf/src/System/Formats/Nrbf/SerializationRecord.cs#L68

The job it does is specific to NRBF, so I am pretty sure that we can't include it in `TypeName` (System.Reflection.Metadata needs to be unaware of the existence of NRBF and can't offer anything specific to NRBF). But I would not mind exposing it in `System.Formats.Nrbf`, I am just not sure what would be the best way to do it (we can't expose extension methods for types that we own) and if you want to have a depedency to `System.Formats.Nrbf`.

2024-11-20 07:04 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
Thank you, @adamsitnik! We already have a dependency on 'system.formats.nrbf', but this is about the customer application having a dependency on your assembly. 
> But I would not mind exposing it in System.Formats.Nrbf

I think customers will benefit from it. Right now my only option is to publish this method (Matches) as an example for users to copy over, like you said, that if users must match generic, or arrays or nullable types, they need it. Of cause we don't know what types users need on the clipboard, but generic collections are not unexpected.

2024-11-20 07:28 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.TypeNameComparer.cs
> +            public int GetHashCode(TypeName obj)
I can't use HashCode.Combine as it does not call this GetHashCode method recursively, most of these values are TypeNames and should have their assembly names removed.

2024-11-20 14:14 UTC, adamsitnik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
> Right now my only option is to publish this method (Matches) as an example for users to copy over

An alternative would be to introduce an abstract class / interface that would expose this method and let the users call it and then accept it instead oft `Func<TypeName, Type> as an argument.

Or even require the users to provide a set of allowed types up-front, and do that logic for them? But this on the other hand would not give them any flexibility when it comes to the comparison.

2024-11-20 14:16 UTC, adamsitnik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
> Just curious, why are you not resolving type-forwarded assembly when matching SerializationRecord's TypeName to Type.

Because we ignore assembly names. We expect that if you provide us a type `MyClass` it can be defined only in one assembly.

2024-11-20 21:26 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
> introduce an abstract class / interface that would expose this method and let the users call it and then accept it instead of Func<TypeName, Type> as an argument.

This is an option that we'll consider after getting some user feedback. A collection of Types provided by the user provides a benefit of rooting these types for the future trimmability.

2024-11-20 23:45 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +                    if (typeof(Bitmap).IsAssignableTo(typeof(T)) && TryGetBitmapData(dataObject, format, out Bitmap? bitmap))
FYI, `typeof(Bitmap).IsAssignableTo(typeof(Image)) == true`, but `typeof(Bitmap) == typeof(T) || typeof(Image) == typeof(T)` is more efficient

2024-11-21 04:55 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +                    if (typeof(NotSupportedException).IsAssignableTo(typeof(T)))
This is the case of an offset array on the clipboard, SetData/GetData with BinaryFormatter on roundtrips correctly, but user trying to read it as TryGetData<int[,]> returns false and then TryGetData<NotSupportedException>returns an error message. But it will be easier to see what went wrong if that exception bubbled up to the user as an exception... thank you!

2024-12-06 20:07 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +    ///      Type[] allowedTypes =
Updated the sample

2024-12-06 21:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +                { "System.Byte", typeof(byte) },
@JeremyKuhne  - are you suggesting using TypeName for both built-in and known types and user types? String comparison is a bit of an optimization for the built-in types.

2024-12-06 21:17 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +    private static bool IsUnboundedType<T>()
This validation had been refactored, but I'm not sure if it is useful at all.

2024-12-09 17:22 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            DataFormats.BitmapConstant or BitmapFullName =>
Should we also do a check that if format is audio, type should be stream?

2024-12-09 17:24 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +                    " using `TryGetData<T>(string, out T)` method.",
nit: use string interpolation

2024-12-09 17:41 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
> +                    if (legacyMode && LocalAppContextSwitches.ClipboardDragDropEnableUnsafeBinaryFormatterSerialization)
Do we not want legacy mode to use nrbf?

2024-12-09 18:20 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/ITypedDataObject.cs
> +public interface ITypedDataObject
Is there a resolution to this thread? It still seems our guidance is that both should be implemented.

2024-12-09 18:20 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.FullCompatScope.cs
> +    internal readonly ref struct FullCompatScope : IDisposable
Maybe we should call this `BinaryFormatterFullCompatScope`? It might be vague when looking at what this is in tests.

2024-12-09 18:25 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs
> +                using BinaryFormatterInClipboardDragDropScope clipboardDragDropScope = new(enable: true);
I believe this can be simplified now to `using FullCompatScope`

2024-12-09 18:46 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +                    " using `TryGetData<T>(string, out T)` method.",
string interpolation will not work with resources

2024-12-09 18:48 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropHelperTests.cs
> +            Assert.NotNull(dragDropFormat);
```suggestion
            dataObject.TryGetData(DragDropHelper.DRAGIMAGEBITS, out DragDropFormat dragDropFormat).Should().BeTrue();
            dragDropFormat.Should().NotBeNull();
```

2024-12-09 18:48 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NativeToWinFormsAdapterTests.cs
> +        " define a resolver function that supports types that you are retrieving from the Clipboard or being dragged and dropped.";
use string interpolation

2024-12-09 18:48 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
> +                    if (legacyMode && LocalAppContextSwitches.ClipboardDragDropEnableUnsafeBinaryFormatterSerialization)
At this point, NRBF is not usable because we don't have the root record.  Since we don't have the root record, we can't do type comparison required by the typed APIs either, but there is a slight chance that BinaryFormatter can work.

2024-12-09 19:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +            DataFormats.BitmapConstant or BitmapFullName =>
We support code like this before this PR - 
Clipboard.SetData(DataFormats.WaveAudio, "abc");
string text = (string)Clipboard.GetData(DataFormats.WaveAudio);
and i'm keeping this scenario as is.

This validation is based on the formats that are not binary-formatted.

If the user wants, they can do Clipboard.TryGetData(DataFormats.WaveAudio, out MemoryStream audio).

2024-12-09 19:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
> +                    if (medium.tymed == Com.TYMED.TYMED_HGLOBAL && !medium.hGlobal.IsNull && hr != HRESULT.COR_E_SERIALIZATION)
I'm not reading the HGLOBAL if a serialization error had occured.

2024-12-09 21:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
> +    /// </remarks>
https://github.com/dotnet/winforms/issues/12608

2024-12-10 01:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NativeToWinFormsAdapterTests.cs
> +    public void TryGetData_AsInterface_ListOfPrimitives_RequiresResolver(string format)
@JeremyKuhne - the call to dataObject.TryGetData below does not work because I'm blocking interfaces at the T when user does not supply a resolver. But this particular scenario works with no resolver otherwise. The interface T is automatically added to _userTypes cache and List<int> is read with no formatters or resolver as a list of known types. Then we can test that the record type is assignable to the specified interface.  I think we should remove the validation for non-concrete types.

2024-12-10 01:42 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
> +                { "System.Byte", typeof(byte) },
I'm a little concerned about hard coding the names. Are we sure that all cases will have `mscorlib`, for example? Are we confident that we aren't allowing a "System.Int32" from some random assembly? Do we care? I'm not sure that it matters a ton, but I'd rather start with more careful.

2024-12-10 01:48 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NativeToWinFormsAdapterTests.cs
> +    public void TryGetData_AsInterface_ListOfPrimitives_RequiresResolver(string format)
I don't know that we should allow a situation where it "sometimes" works. I don't think it is legitimate to ask for non-concrete types without a custom resolver.

2024-12-11 23:06 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +    ///  If <see langword="true"/>, then Clipboard and DataObject Get and Set methods will attempts to deserialize
```suggestion
    ///  If <see langword="true"/>, then Clipboard and DataObject Get and Set methods will attempts to serialize or deserialize
```

2024-12-11 23:19 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
> +            // TODO (TanyaSo): localize string
yes

2024-12-12 00:51 UTC, lonitra approved these changes
LGTM, nice! 🚀

2024-12-12 00:55 UTC, merged