Attempt to use `BinaryFormattedObject`/`BinaryFormatWriter` before `BinaryFormatter`
dotnet/winforms pull request #11614
Opened 2024-06-30 02:14 UTC by elachlan

Fixes #11607 
Related: #9428

Work was based on other usages in `System.Windows.Forms`.

2024-06-30 02:18 UTC, elachlan commented
@JeremyKuhne I just did a quick look into this and it seems to have fixed #11607

It does not fix #9416, because I was unable to use `WinFormsBinaryFormatWriter` as its internal to `System.Windows.Forms`.

2024-06-30 02:24 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +        internal static bool EnableUnsafeBinaryFormatterInNativeObjectSerialization { get; } =
When the switch is cached in a static, it can't be turned on/off when tests are entering the scope.

2024-06-30 02:33 UTC, elachlan commented
@Tanya-Solyanik would using `InternalsVisibleTo` be inappropriate to resolve the issue of `WinFormsBinaryFormatWriter` not being accessible from `System.Windows.Forms.Design`? It feels a bit wrong to me.

2024-06-30 02:36 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +        internal static bool EnableUnsafeBinaryFormatterInNativeObjectSerialization { get; } =
Its a static property, so I think the getter will check each time? The same pattern is used all over winforms.

2024-06-30 04:59 UTC, elachlan commented
I've played around with it. `InternalsVisibleTo` causes a bunch of warnings/errors when used to allow `Design` to access `Forms`.

Because of the internal APIs used by `TryGetImageListStreamer`/`WriteImageListStreamer`, we can't share the code between the two projects like we do with `Common.

I can't think of an easy fix for this that isn't complicated. Something like:
```csharp
namespace System.Windows.Forms.Primitives
{
    internal interface IBinaryFormattedObjectHandler
    {
        bool TryWriteObject(Stream stream, object value);
        bool TryGetObject(BinaryFormattedObject format, out object? value);
    }

    internal static class WinFormsBinaryFormatterRegistry
    {
        private static readonly List<IBinaryFormattedObjectHandler> _handlers = new();

        public static void RegisterHandler(IBinaryFormattedObjectHandler handler)
        {
            _handlers.Add(handler);
        }

        public static bool TryWriteObject(Stream stream, object value)
        {
            if (BinaryFormatWriter.TryWriteFrameworkObject(stream, value))
            {
                return true;
            }

            foreach (var handler in _handlers)
            {
                if (handler.TryWriteObject(stream, value))
                {
                    return true;
                }
            }
            return false;
        }

        public static bool TryGetObject(BinaryFormattedObject format, out object? value)
        {
			if (format.TryGetFrameworkObject(stream, value))
            {
                return true;
            }
			
            foreach (var handler in _handlers)
            {
                if (handler.TryGetObject(format, out value))
                {
                    return true;
                }
            }
            value = null;
            return false;
        }
    }
}
```

2024-07-01 20:10 UTC, lonitra reviewed
Changes RLGTM. @JeremyKuhne is out this week, but I think we might want to consider pulling some of the writer and maybe even the reader code to System.Private.Windows.Core if we are starting to need these across different assemblies. We'll need to discuss this.

2024-07-01 20:10 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +                        success = BinaryFormatWriter.TryWriteFrameworkObject(_resourceStream, _resources.Data);
Looks like we are always writing a Hashtable so perhaps change this to utilize `BinaryFormatWriter.TryWriteHashtable`

2024-07-02 00:39 UTC, elachlan commented
@lonitra I was able to refactor the `WinFormsBinaryFormatWriter` to move the Bitmap part into `PrimitivesBinaryFormatWriter`.

Which will allow each project to have access to `WriteBitmap`.

I had to add `FXAssembly`/`AssemblyRef` to the Primitives project, which has caused some compilation problems. So I might just define `AssemblyRef.SystemDrawing` in `PrimitivesBinaryFormatWriter` as a constant. The other option is to move all the `AssemblyRef`/`FXAssembly` to Primitives and remove them from `System.Windows.Forms`? But I am unsure if it is required to stay inside the project?

2024-07-02 01:23 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +                        success = BinaryFormatWriter.TryWriteFrameworkObject(_resourceStream, _resources.Data);
Done. #9416 fails here because `Bitmap` is not a primitive. 

CoreImageExtensions could add:
```csharp
internal static byte[] Save(this IImage image)
{
    using MemoryStream stream = new();
    image.Save(stream);
    return stream.ToArray();
}
```

Then we can save it to a `byte[]` which we can maybe handle somehow?

2024-07-02 17:04 UTC, lonitra commented
Oops, I realized we had already moved BinaryFormatWriter to System.Private.Window.Core ignore my previous comment about moving it.🤦‍♀️ There is a possibility we ship System.Private.Windows.Core in the future for code sharing so we do not want it to contain code related to items that are specific to WinForms. We could consider moving the Bitmap part to System.Private.Windows.Core since it is fairly common and not necessarily WinForms specific, but as you mentioned there would still be issues with `ImageListStreamer`. Your approach with `WinFormsBinaryFormatterRegistry` seems like the way to go, but ultimately I would want Jeremy to weigh in.

2024-07-08 18:17 UTC, JeremyKuhne requested changes
Couple of comments

2024-07-08 18:17 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +                long startPosition = _resourceStream.Position;
We should seek to the beginning here, there is no need to save the position.

2024-07-08 18:17 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +                        _resources = new LocalResourceManager(value);
You should return here if you were successful.

2024-07-08 18:59 UTC, JeremyKuhne commented
> I've played around with it. `InternalsVisibleTo` causes a bunch of warnings/errors when used to allow `Design` to access `Forms`.
> 
> Because of the internal APIs used by `TryGetImageListStreamer`/`WriteImageListStreamer`, we can't share the code between the two projects like we do with `Common.
> 
> I can't think of an easy fix for this that isn't complicated.

We should never give `WinForms.Design` internal visibility to `WinForms`.

The better inversion here is to do something like this in Core (which has the right visibility):

``` C#
internal delegate bool DeserializationDelegate(Stream stream, out object value);

internal static class ObjectSerializers
{
    private static readonly ConcurrentDictionary<Type, DeserializationDelegate> _deserializers = new();

    // This should be called in the assembly initializer for all known types
    internal static void AddDeserializer<T>(DeserializationDelegate deserializer)
    {
        if (!_deserializers.TryAdd(typeof(T), deserializer))
        {
            throw new InvalidOperationException();
        }
    }

    internal static bool TryDeserialize(Stream stream, out object value)
    {
        foreach ((_, var deserializer) in _deserializers)
        {
            if (deserializer(stream, out value))
            {
                return true;
            }
        }

        value = default!;
        return false;
    }

    internal static bool TrySerialize(Stream stream, object value)
    {
        if (value is IStreamSerializable serializable)
        {
             return serializable.TrySerialize(stream);
        }

        // Try Framework serializers here

        return false;
    }
}

internal interface IStreamSerializable
{
    bool TrySerialize(Stream stream);
}

// Upstream somewhere
public class Foo : IStreamSerializable
{
    bool IStreamSerializable.TrySerialize(Stream stream)
    {
        throw new NotImplementedException();
    }
}
``

2024-07-11 02:16 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
> +                        _resources = new LocalResourceManager(value);
What about the section below around `using (delegator.Manager.CreateSession())`?

2024-07-11 03:38 UTC, elachlan commented
@JeremyKuhne I don't think the `ObjectSerializers` structure you outlined helps us with the `CodeDomSerializationStore` Serialization, because we are serializing a `Hashtable` which contains objects. So the `BinaryFormatWriter.TryWriteHashtable` would have to be adjusted to handle `IStreamSerializable` values. 

Does that sound right?

2024-07-11 17:12 UTC, JeremyKuhne commented
> cause we are serializing a `Hashtable` which contains objects. S

It is really limited, so it doesn't buy much. It may actually be too difficult for users to figure out what works and doesn't so we might not want to do this.

2024-07-11 23:15 UTC, elachlan commented
@JeremyKuhne Have you got any suggestions on being able to handle `Bitmap` and `ImageListStreamer` in the hashtable? or doe we leave that to another PR?

2024-07-11 23:35 UTC, JeremyKuhne commented
> @JeremyKuhne Have you got any suggestions on being able to handle `Bitmap` and `ImageListStreamer` in the hashtable? or do we leave that to another PR?

It is a tricky question. While we could expand the manual handling, it gets a bit unwieldly. With a general deserializer we can handle that a little easier, but we don't have a good answer for serialization.

What other WinForms and Framework types can we see in this hashtable?

2024-07-11 23:52 UTC, elachlan commented
Technically any type that has the `[Serializable]` attribute can be added to it as far as I can tell. which is pretty broad. Its not super easy to follow in terms of seeing what resources are added to the hashtable.

2024-07-12 00:02 UTC, elachlan commented
For Winforms types `Tag` is the most problematic property I think, because its `object` and user input.

2024-07-17 00:27 UTC, elachlan commented
@JeremyKuhne should we implement the `ObjectSerializers` in a follow up PR? Or did you want me to add it here?

2024-07-17 01:09 UTC, JeremyKuhne commented
@elachlan my point is that I'm not sure we should do this as we can only handle a very limited set of things. It would be more confusing than helpful I think. If you're using the CodeDomSerializer you really should be taking the dependency on BinaryFormatter.

2024-07-17 01:20 UTC, elachlan commented
I think limited coverage for our winforms controls would be positive. Anything we can cover in a safer manner than the `BinaryFormatter` is a good thing.

Happy to not implement it and we can leave this PR as is.

2024-07-23 19:45 UTC, closed without merging