Mark the Form.OnClosed and OnClosing methods with the ObsoleteAttribute
dotnet/winforms pull request #11767
Opened 2024-07-29 11:41 UTC by geniuszxy

Fixes #11727

## Proposed changes

- Mark the Form.OnClosed and OnClosing methods, as well as their override methods, with the ObsoleteAttribute.
- Disable CS0618 warnings for related callsites.

## Customer Impact

- CS0618 warnings will be reported if these two methods are overloaded.

## Regression? 

- No

## Risk

- Minimal

## Test methodology 

- Existing unit tests.

2024-07-30 20:40 UTC, lonitra commented
👍 This is waiting on API review board

2024-08-06 19:42 UTC, lonitra commented
@geniuszxy API has been approved! 🥳 There are some change requests which have been outlined [here](https://github.com/dotnet/winforms/issues/11727#issuecomment-2271642622). If you could go ahead and make these changes, that would be great and we can get this merged. Please let me know if any assistance is needed.

2024-08-07 01:27 UTC, RussKie commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
> +            [Obsolete("The OnClosed method is obsolete starting with the .NET Framework 2.0; use the OnFormClosed method instead.")]
The obsoletions should follow this format:
https://github.com/dotnet/winforms/blob/ab9eb71f903d7771849887a15ab5ff3f37ba4c00/src/System.Windows.Forms/src/System/Windows/Forms/Controls/UpDown/DomainUpDown.DomainItemAccessibleObject.cs#L10-L15

2024-08-07 01:30 UTC, RussKie commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
> +            [Obsolete("The OnClosed method is obsolete starting with the .NET Framework 2.0; use the OnFormClosed method instead.")]
https://github.com/dotnet/winforms/blob/main/docs/list-of-diagnostics.md must be updated as well.

@lonitra a new entry into aka.ms will need to be added; the docs will need to be updated as well.

2024-08-07 09:04 UTC, geniuszxy commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
> +            [Obsolete("The OnClosed method is obsolete starting with the .NET Framework 2.0; use the OnFormClosed method instead.")]
I have picked WFDEV004 and updated the format.

2024-08-07 22:26 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
>      protected virtual void OnClosed(EventArgs e)
We should also obsolete `Closing` and `Closed` events

2024-08-08 05:25 UTC, geniuszxy commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
>      protected virtual void OnClosed(EventArgs e)
I ran into a few issues:
1. There're 2 classes subscribed to the Closed event, but they are subscribed in the designer. Should I change the event to FormClosed, or suppress the warnings, or leave them alone?
2. Should I obsolete `s_closingEvent` and `s_closedEvent` too? These 2 fields are private and only used by the events.

2024-08-08 05:33 UTC, KlausLoeffelmann requested changes

2024-08-08 05:33 UTC, KlausLoeffelmann commented on docs/list-of-diagnostics.md
> +|  __`WFDEV004`__ | `Form.OnClosing` and `Form.OnClosed` are obsolete. Use `Form.OnFormClosing` and `Form.OnFormClosed` instead. |
What are those IDs? Diagnostic ID?
If yes, these need to be changed.

We are starting with WFO and have certain number groups.
What's the system behind these?

2024-08-08 05:33 UTC, KlausLoeffelmann commented on src/Common/src/Obsoletions.cs
> +    internal const string FormOnClosingClosedDiagnosticId = "WFDEV004";
Let's please sync up about these standards here.

2024-08-08 05:33 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +#pragma warning disable WFDEV004 // Type or member is obsolete - compat
Same.

2024-08-08 05:33 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +#pragma warning disable WFDEV004 // Type or member is obsolete - compat
Same.

2024-08-08 06:17 UTC, geniuszxy commented on docs/list-of-diagnostics.md
> +|  __`WFDEV004`__ | `Form.OnClosing` and `Form.OnClosed` are obsolete. Use `Form.OnFormClosing` and `Form.OnFormClosed` instead. |
I followed the steps above the file: "Add the obsoletion to the table below, claiming the next diagnostic id", if I can't use it, what should I do?

2024-08-08 14:08 UTC, RussKie commented on docs/list-of-diagnostics.md
> +|  __`WFDEV004`__ | `Form.OnClosing` and `Form.OnClosed` are obsolete. Use `Form.OnFormClosing` and `Form.OnFormClosed` instead. |
@KlausLoeffelmann: that's an established and documented convention. See https://learn.microsoft.com/dotnet/desktop/winforms/wfdev-diagnostics/obsoletions-overview

Changing this will be a breaking change. If the team decides to change it - it's up to you. But that's orthogonal to this PR, it just follows the established convention.

2024-08-08 16:46 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
>      protected virtual void OnClosed(EventArgs e)
1. I took a look at the code and we are using Closed and Closing in [`DataGridViewAddColumnDialog`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewAddColumnDialog.cs#L467), [`DataGridViewColumnCollectionDialog`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs#L627), and [`DesignerActionPanel`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs#L443). It seems safe to change these to hook to `FormClosed`/`FormClosing` events since these are internal classes and `OnFormClosed`/`OnFormClosing` are called in the same places as `OnClosed`/`OnClosing` would be called, but I would also want @Tanya-Solyanik to weigh in in case I am missing any details that would deter us from wanting to make this change.
2. We can leave these as is. We do not typically obsolete private fields it seems.

2024-08-12 19:45 UTC, Tanya-Solyanik commented
@geniuszxy  - COuld you please also fix the comment here - https://github.com/dotnet/winforms/blob/382ad3e43a8e9c81fbb738940a33cdc0f6442a59/src/System.Windows.Forms/src/System/Windows/Forms/FormClosedEventArgs.cs#L7 to say that these arguments are also used with FormClosed event

2024-08-12 20:02 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
>      protected virtual void OnClosed(EventArgs e)
@lonitra @geniuszxy  - I don't see any problems with replacing Closed/Closing events with FormClosed/FormClosing events and OnClosed/OnClosing overrides with OnFormClosed/OnFormsClosing in the Design namespace. Implementations don't rely on the form being in the Application.OpenForms collection.

2024-08-12 20:23 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
>              protected override void OnClosed(EventArgs e)
Designer can override OnFormClosed instead. This is in fact preferable, because if CloseReason is the app exit, we shouldn't potentially recreate the action panel            `   _parent.ActionPanel.SetDropDownActive(false);`

2024-08-13 16:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
>      protected override void OnClosing(CancelEventArgs e)
This could be OnFormClosing as well

2024-08-13 16:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/FormClosingEventArgs.cs
> +///  Provides data for the <see cref="Form.OnFormClosing"/> event.
```suggestion
///  Provides data for <see cref="Form.OnFormClosing"/> and <see cref="Form.OnClosing"/> events.
```

2024-08-13 16:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/FormClosedEventArgs.cs
> +///  Provides data for the <see cref="Form.OnFormClosed"/> event.
```suggestion
///  Provides data for <see cref="Form.OnFormClosing"/> and <see cref="Form.OnClosing"/> events.
```

2024-08-13 16:11 UTC, Tanya-Solyanik commented on src/Common/src/Obsoletions.cs
> +    internal const string FormOnClosingClosedMessage = "Form.OnClosing, Form.OnClosed and the corresponding events are obsolete. Use Form.OnFormClosing and Form.OnFormClosed instead.";
```suggestion
    internal const string FormOnClosingClosedMessage = "Form.OnClosing, Form.OnClosed and the corresponding events are obsolete. Use Form.OnFormClosing, Form.OnFormClosed, Form.FormClosing and Form.FormClosed instead.";
```

2024-08-13 16:11 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +|  __`WFDEV004`__ | `Form.OnClosing`, `Form.OnClosed` and the corresponding events are obsolete. Use `Form.OnFormClosing` and `Form.OnFormClosed` instead. |
```suggestion
|  __`WFDEV004`__ | `Form.OnClosing`, `Form.OnClosed` and the corresponding events are obsolete. Use `Form.OnFormClosing`, `Form.OnFormClosed`, `Form.FormClosing` and `Form.FormClosed` instead. |
```

2024-08-14 04:25 UTC, geniuszxy commented on src/System.Windows.Forms/src/System/Windows/Forms/FormClosingEventArgs.cs
> +///  Provides data for the <see cref="Form.OnFormClosing"/> event.
I see that this class is only used by `OnFormClosing` (`OnClosing` accepts `CancelEventArgs`), perhaps I should keep it sync with [the document](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.formclosingeventargs?view=windowsdesktop-8.0)? like this? `Provides data for the <see cref="Form.FormClosing" /> event.`

2024-08-14 04:37 UTC, geniuszxy commented on src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
>      protected override void OnClosing(CancelEventArgs e)
Can I directly change it to `OnFormClosing`? This is a public class, won't it become another breaking change?

2024-08-14 06:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
>      protected override void OnClosing(CancelEventArgs e)
It's unfortunate that this class is not sealed... You are right, this would be a breaking change.

2024-08-14 07:10 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/FormClosingEventArgs.cs
> +///  Provides data for the <see cref="Form.OnFormClosing"/> event.
FormClosingEventArgs are CancelEventArgs, so there is no contradiction to the docs. At the invocation time however we allocate the FormaClosingEventArgs to pass into both events - for example https://github.com/dotnet/winforms/blob/9feb143049e1b51b760579d17456874d5b30fa3e/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L6712

2024-08-15 01:05 UTC, lonitra approved these changes
LGTM

2024-08-15 17:12 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +#pragma warning disable WFDEV004 // Type or member is obsolete - compat
Is it possible to suppress these in the suppressions file instead?

2024-08-16 05:45 UTC, geniuszxy commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +#pragma warning disable WFDEV004 // Type or member is obsolete - compat
Do you mean GlobalSuppressions.cs?

2024-08-16 11:48 UTC, geniuszxy commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +#pragma warning disable WFDEV004 // Type or member is obsolete - compat
This is a compiler warning, and besides pragma it seems that I can only suppress it through the nowarn option.

2024-08-16 17:06 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +#pragma warning disable WFDEV004 // Type or member is obsolete - compat
Yes, I was thinking about GlobalSuppressions.cs, but that file is used to suppress warnings from analysis tools, not from the compiler, you are right.

2024-08-19 05:32 UTC, geniuszxy commented on src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
> +    [Obsolete(
I removed the attribute, only suppress the warnings now.

2024-08-19 18:54 UTC, Tanya-Solyanik approved these changes
Thank you! Looks good to me

2024-08-20 20:41 UTC, merged

2024-08-20 20:43 UTC, lonitra commented on docs/list-of-diagnostics.md
> +|  __`WFDEV004`__ | `Form.OnClosing` and `Form.OnClosed` are obsolete. Use `Form.OnFormClosing` and `Form.OnFormClosed` instead. |
@KlausLoeffelmann We have some others that are following this pattern at the moment. Let's chat about aligning all of our diagnostic IDs.

2025-03-05 02:07 UTC, Tanya-Solyanik commented
Related to https://github.com/dotnet/docs/issues/44894

2025-03-05 02:16 UTC, Tanya-Solyanik commented
Related to https://github.com/dotnet/docs-desktop/issues/2025