Property Store Refactor - `GetSize`/`SetSize`
dotnet/winforms pull request #11779
Opened 2024-07-30 20:55 UTC by elachlan

Related: #9508

2024-07-31 01:01 UTC, elachlan commented
@lonitra `PropertyStore` has `private static int s_currentKey;`. we use it via: `public static int CreateKey() => s_currentKey++;`. Should we use `Interlocked.Increment` here?

2024-07-31 18:33 UTC, lonitra commented
> Should we use `Interlocked.Increment` here?

Comment on this seems to indicate that we are always calling this in class initializer and we do not have same class hierarchy initializing on multiple threads. I looked for the callers of this and that seems to still be true, so I think we should be ok to leave it as is here.

2024-08-01 17:06 UTC, JeremyKuhne commented
> > Should we use `Interlocked.Increment` here?
> 
> Comment on this seems to indicate that we are always calling this in class initializer and we do not have same class hierarchy initializing on multiple threads. I looked for the callers of this and that seems to still be true, so I think we should be ok to leave it as is here.

After we're done with moving to the new API we should probably create a **global** enum with "keys" as a more efficient replacement. Then we won't have hundreds of these calls on startup, no threading concerns, and greatly simplified static field content. Maybe something like:

``` C#
internal enum PropertyKey
{
    BackgroundBrush,   // Instead of s_backBrushProperty
    FontHeight,        // Instead of s_fontHeightProperty
}
```

2024-08-01 17:11 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            Properties.AddOrRemoveValue(s_dataContextProperty, value);
I don't think you can remove as currently you can override the parent data context to not have one. This is one where we have to allow an explicit `null`.

2024-08-01 17:18 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
> +        get => Properties.TryGetValue(s_propDrawMode, out DrawMode drawMode) ? drawMode : DrawMode.Normal;
This could just be the OrDefault overload as DrawMode.Normal is the default.

2024-08-01 17:24 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
> +                Properties.AddValue(s_propDrawMode, value);
Related to the value being the default, it might be better to update `AddOrRemoveValue` to not be constrained to class and instead check `== default(T)`. Then we can be removing entries for other default values as well.

2024-08-01 17:37 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewBand.cs
> +        get => Properties.TryGetValue(s_propDividerThickness, out int dividerThickness) ? dividerThickness : 0;
Shouldn't this be GetValueOrDefault?

2024-08-01 17:38 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewBand.cs
>              if (value != DividerThickness)
This is one where AddOrRemoveValue simplifies things. You can then check the result to see if value is different. (See my earlier comment about opening this overload up to all T values).

2024-08-01 17:39 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
> +        if (Properties.TryGetValue(s_propItemHeight, out int _))
ContainsKey?

2024-08-01 17:43 UTC, JeremyKuhne commented
@elachlan I left some comments. I've reviewed about half of it. I'll review again after you ping me.

This is about the largest change size we'd want to make for this. I'd even suggest making them a little smaller in the future so we can review with a bit more confidence that we aren't missing something.

2024-08-01 20:20 UTC, elachlan commented
@JeremyKuhne I have made another branch locally to keep the changes and reverted this branch to the last know test pass. This change set should also be smaller now. 

Ill open up a follow up PR once this is merged.

2024-08-01 20:42 UTC, JeremyKuhne requested changes
Left a few comments

2024-08-01 20:42 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs
> +        !container.Properties.TryGetValue(s_wrapContentsProperty, out bool wrap) || wrap;
```suggestion
        !container.Properties.GetValueOrDefault<bool>(s_wrapContentsProperty);
```

2024-08-01 20:42 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
> +        return element.Properties.TryGetValue(s_layoutBoundsProperty, out Size _);
```suggestion
        return element.Properties.ContainsKey(s_layoutBoundsProperty);
```

2024-08-01 20:42 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +            bool shouldUpdate = false;
`updated` or `sizeUpdated` is probably better here

2024-08-01 20:42 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +            bool shouldUpdate = false;
`updated` or `sizeUpdated` is probably better here

2024-08-01 20:42 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            Properties.AddOrRemoveValue(s_dataContextProperty, value);
This needs fixed still.

2024-08-01 21:28 UTC, JeremyKuhne commented
In general looks good, looks like some tests need updated.

2024-08-01 21:42 UTC, elachlan commented
I'm just reviewing it again myself. I've found a few more discards and places where we can use `GetValueOrDefault`. I'll push it through once the current test run finishes.

2024-08-01 22:07 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs
> +        !container.Properties.TryGetValue(s_wrapContentsProperty, out bool wrap) || wrap;
It needs to be `TryGetValue` because the default value is `true`. `GetValueOrDefault` doesn't allow passing in a default value.

2024-08-01 22:45 UTC, elachlan commented
@JeremyKuhne can you check CI please? It's got a fail. But no test failures.

2024-08-01 23:03 UTC, JeremyKuhne commented
Integration tests failed, but didn't report the failing test

2024-08-01 23:11 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs
> +        !container.Properties.TryGetValue(s_wrapContentsProperty, out bool wrap) || wrap;
Ugh, this one is terrible. The original code is trying to make the default value `true` by passing in `0` for true. I didn't register that you had flipped this on the set.

2024-08-01 23:11 UTC, JeremyKuhne approved these changes

2024-08-01 23:38 UTC, merged