Refactor `PropertyStore`
dotnet/winforms pull request #11803
Opened 2024-08-02 02:06 UTC by elachlan

Related: #9508

2024-08-02 08:16 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.cs
> +        get => Properties.TryGetValue(s_propComboBoxCellDisplayStyle, out DataGridViewComboBoxDisplayStyle displayStyle) ? displayStyle : DataGridViewComboBoxDisplayStyle.DropDownButton;
What is the standard for wrapping when using the conditional operator like this?

2024-08-02 09:51 UTC, elachlan commented
@JeremyKuhne hopefully this change set is small enough.

2024-08-02 16:43 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
> +        get => !Properties.TryGetValue(s_lastCanEnableImeProperty, out bool lastCanEnableIme) || lastCanEnableIme;
This pattern isn't the easiest to follow. The fact that we've seen this multiple times I'm thinking we need to update `GetValueOrDefault` so that it takes the (optional) default value. Then this could be:

``` C#
   get => Properties.GetValueOrDefault<bool>(s_lastCanEnableImeProperty, defaultValue: true);
```

``` C#
public T? GetValueOrDefault<T>(int key, T? defaultValue = default)
```

2024-08-02 16:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.cs
> +        get => Properties.TryGetValue(s_propComboBoxCellDisplayStyle, out DataGridViewComboBoxDisplayStyle displayStyle) ? displayStyle : DataGridViewComboBoxDisplayStyle.DropDownButton;
Operators always begin the line, exception is `=>`.

``` C#
get => Properties.TryGetValue(s_propComboBoxCellDisplayStyle, out DataGridViewComboBoxDisplayStyle displayStyle)
    ? displayStyle
    : DataGridViewComboBoxDisplayStyle.DropDownButton;
```

2024-08-02 16:48 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
> +        get => !Properties.TryGetValue(s_lastCanEnableImeProperty, out bool lastCanEnableIme) || lastCanEnableIme;
With this we should be not passing the default value if getting it is expensive. That is, you're calling some property or method that does a lot of work to get a default value you don't normally expect to need.

2024-08-02 16:49 UTC, JeremyKuhne requested changes
Looks good, although I think we should add the default value as mentioned before we close this one out.

2024-08-02 21:59 UTC, elachlan commented
@JeremyKuhne it ended up simplifying to code quite a bit.

2024-08-02 22:52 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewImageCell.cs
> +        get =>Properties.TryGetValue(s_propImageCellLayout, out DataGridViewImageCellLayout imageLayout) ? imageLayout : DataGridViewImageCellLayout.Normal;
```suggestion
        get => Properties.TryGetValue(s_propImageCellLayout, out DataGridViewImageCellLayout imageLayout) ? imageLayout : DataGridViewImageCellLayout.Normal;
```

2024-08-02 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
> +        get => Properties.TryGetValue(s_mergeIndexProperty, out int index) ? index : -1;
Missed this one

2024-08-02 22:58 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
> +        get => Properties.GetValueOrDefault<CheckState>(s_propCheckState);
It is clearer now that we have the parameter to show the default value in this case. (Then you don't need to know Unchecked is the default)

```suggestion
        get => Properties.GetValueOrDefault(s_propCheckState, CheckState.Unchecked);
```

2024-08-02 22:58 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
> +        get => Properties.GetValueOrDefault<Keys>(s_propShortcutKeys);
```suggestion
        get => Properties.GetValueOrDefault(s_propShortcutKeys, Keys.None);
```

2024-08-02 23:01 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewImageCell.cs
> +        get =>Properties.TryGetValue(s_propImageCellLayout, out DataGridViewImageCellLayout imageLayout) ? imageLayout : DataGridViewImageCellLayout.Normal;
This line should also be broken up (too long).

2024-08-02 23:02 UTC, JeremyKuhne requested changes
Looking good, just one more set of nits.

2024-08-03 01:57 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
> +        get => Properties.GetValueOrDefault(s_mergeIndexProperty, , -1);
```suggestion
        get => Properties.GetValueOrDefault(s_mergeIndexProperty, -1);
```

2024-08-03 20:00 UTC, JeremyKuhne approved these changes
Looking good!

2024-08-03 20:00 UTC, merged