Dark mode experimental feature
dotnet/winforms pull request #11857
Opened 2024-08-11 23:08 UTC by JeremyKuhne

The first commit pulls from @KlausLoeffelmann's https://github.com/dotnet/winforms/pull/10985/files. Styling features and non-critical changes were stripped out to make this the smallest change possible.

The second commit are my changes to address my feedback on the original PR mentioned above.

2024-08-11 23:21 UTC, paul1956 requested changes
Please put back \<OptionInfer>Off\</OptionInfer>
It should not affect anything in .Net 9 or going forward.

2024-08-11 23:21 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/src/Microsoft.VisualBasic.Forms.vbproj
@JeremyKuhne is there a reason you removed Option Infer Off from VB Projects? That was added in recently approved PR for .Net 9?

2024-08-12 00:01 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/src/Microsoft.VisualBasic.Forms.vbproj
We need to isolate changes as much as possible in this, otherwise there wouldn't have a dark mode.
So, we need to be getting things addressed for VB in .NET 10.

2024-08-12 00:19 UTC, KlausLoeffelmann approved these changes
Looks like a surprising compromise, customers will be really happy about.
Unit tests pass, I did a series of exploratory tests, also in conjunction with  my async feature, I merged earlier, and this version of the dark mode feature looks really good! What an amazing and surprising ride this was! Lifetime experience! So glad, we made this for .NET 9!

2024-08-12 00:29 UTC, KlausLoeffelmann commented on src/Microsoft.VisualBasic.Forms/src/Microsoft.VisualBasic.Forms.vbproj
That said, we will have the App Framework updated, so VB can consume dark mode in .NET 9.

2024-08-12 00:36 UTC, KlausLoeffelmann approved these changes
🕶️ 
:shipit:

2024-08-12 01:05 UTC, merged

2024-08-12 01:50 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
> +        // Ee've mapped to a system defined bitmap we know how to draw.
Typo?

2024-08-12 19:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
> +        // Ee've mapped to a system defined bitmap we know how to draw.
Deliberately undoing typo fixes to make the diff as small as possible.

2024-08-16 07:31 UTC, Philip-Wang01 commented
Verified this issue in the release/9.0, Dark Mode feature works fine, but there are still some GitHub issues to track.
![image](https://github.com/user-attachments/assets/bdb46665-af33-4910-9d71-4816d0154f5f)

2024-08-21 00:25 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +    ///  Sets or gets the Form's title bar back color.
this should have been text color in the summary.

2024-08-26 06:02 UTC, Zheng-Li01 commented
Verified the issue with .NET 9.0.100-rc.1.24422.10 test pass build, for now the Dark mode have been supported for .NET WinForm project.

2024-08-29 01:21 UTC, creizlein commented
I'm sorry if this is not the right place to ask this, but how can we test it? I am running sdk 9 preview 7 and cant get winforms project to recognize Application.SetDefaultDarkMode at all
Is it avail on 9.0.100-preview.7 or I need to grab and compile sdk 9.0 rc1 manually?

Please feel free to delete this post if totally out of topic, apologize in advance.

2024-08-29 02:26 UTC, Zheng-Li01 commented
Please install the 9.0 rc1 form https://github.com/dotnet/sdk/blob/main/documentation/package-table.md try to see if Application.SetDefaultDarkMode is available or not if you can access.

2024-09-04 02:04 UTC, Zheng-Li01 commented
Verified the issue with .NET 9.0.100-rc.1.24452.12 test pass build, for now the Dark mode have been supported for .NET WinForm project.