V2 of WinForms Async experimental APIs
dotnet/winforms pull request #11854
Opened 2024-08-10 00:17 UTC by KlausLoeffelmann

[NOTE] NOT READY FOR REVIEW, DRAFT.

Introduces new experimental APIs for .NET 9:

`Control.InvokeAsync`.
`TaskDialog.ShowDialogAsync`.
`Form.ShowAsync`.
`Form.ShowDialogAsync`

Fixes https://github.com/dotnet/winforms/issues/10739.
https://github.com/dotnet/winforms/pull/11828
Replaces https://github.com/dotnet/winforms/pull/9827.

2024-08-11 01:51 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +    private readonly Lock _syncObj = new();
nit: can you please call this `_lock` or `_doesSomethingLock`?

2024-08-11 02:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        lock (_syncObj)
What exactly are we locking against here? All access to the field is not in the lock. It could be set to null outside of the lock.

2024-08-11 02:20 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control_InvokeAsync.cs
> +#pragma warning disable RS0026 // Do not add multiple public overloads with optional parameters
Not sure why this warning is coming up. Might want to add these to the GlobalSuppressions.cs to make this more readable.

2024-08-11 02:26 UTC, JeremyKuhne requested changes
The locking in Form is the only thing I'm particularly concerned about.

2024-08-11 05:05 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        lock (_syncObj)
I talked with Immo about this. It's the combination of overloads and defaults, where the respective Analyzer is a bit overzealous. I wouldn't it flat out suppress but decide on a case by case and probably wait for an updated version and then purge these out.

2024-08-11 05:06 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control_InvokeAsync.cs
> +#pragma warning disable RS0026 // Do not add multiple public overloads with optional parameters
I talked with Immo about this. It's the combination of overloads and defaults, where the respective Analyzer is a bit overzealous. I wouldn't it flat out suppress but decide on a case by case and probably wait for an updated version and then purge these out.

2024-08-11 05:12 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        lock (_syncObj)
My thinking is, that we need only to lock it, when we're testing, if another thread is just in the process of preparing a `ShowAsync` or `ShowDialogAsync`. That could be a race condition, where 2 threads have access to the same instance (which would be a bad design to begin with, but hey!) might be trying to show a form asynchronously at the same time.

Once we have the task completion source for modal or non-modal, we should be good. If then another thread would dispose or close it, fine. It can only be shown once by the original logic, anyway.

And, the waiting of the task completion source could also not be done inside of the lock.

I think it's fine this way.

2024-08-11 16:49 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control_InvokeAsync.cs
> +#pragma warning disable RS0026 // Do not add multiple public overloads with optional parameters
My suggestion was to make these _instances_ suppressed in the GlobalSuppressions.cs so they aren't in your face as they are meaningless.

2024-08-11 16:54 UTC, JeremyKuhne commented on src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/DiagnosticIDs.cs
> +    public const string UrlFormat = "https://aka.ms/winforms-experimental/{0}";
Sorry I missed this. We should make this more generic like Runtime does:

```suggestion
    public const string UrlFormat = "https://aka.ms/winforms-warnings/{0}";
```

2024-08-11 17:04 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +            if (_tcsNonModalForm is not null)
Let's suppose `_tcsNonModalForm` can be changed underneath you. Would you want a null ref here or would you want to try to set the exception on the instance you found?

2024-08-11 17:10 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +    private TaskCompletionSource? _tcsNonModalForm;
In general it is against our guidelines to use abbreviations like this. I've been looking at other naming patterns with these and trying to figure out naming that better aligns with our standards.

`_nonModalCompletion` works a lot better I think. You can be wordier, but I think this gets enough across without having to decode `tcs` in your head.

2024-08-11 17:11 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control_InvokeAsync.cs
> +        TaskCompletionSource tcs = new(TaskCreationOptions.RunContinuationsAsynchronously);
Mentioned naming elsewhere, but we can meet our guidelines better by calling this `completion` or possibly `completionSource`.

2024-08-11 17:13 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control_InvokeAsync.cs
> +#pragma warning disable RS0026 // Do not add multiple public overloads with optional parameters
The concern here is that you're spending time looking at whether or not there actually is a problem here and there is nothing in the code that would make you want to see the suppression.

2024-08-11 17:15 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control_InvokeAsync.cs
> +#pragma warning disable RS0026 // Do not add multiple public overloads with optional parameters
> these instances suppressed in the GlobalSuppressions.cs.

Ah. OK. I wasn't aware that (_instances_ globally suppressed) was an option we would do. 
Let me patch this.

2024-08-11 17:22 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        lock (_syncObj)
I have more meta concerns are about what it means to fire off dialogs async.

- Should the rest of the app be "modal" from the time of the request (not processing keyboard/mouse input)?
- Should dialogs (across the application dialog APIs) open in the order you requested them?

Since these are experimental APIs we can use the feedback cycle to answer these with more clarity. We should have a very detailed matrix with appropriate docs when we think we're "done".

2024-08-11 18:25 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        lock (_syncObj)
> - Should the rest of the app be "modal" from the time of the request (not processing keyboard/mouse input)?

In my opinion no, because then the effective behavior would be exactly the same as in `ShowDialog`, and the setting up of a complex dialog would block immediately. In the current implementation, the setting-up of the Dialog would still run on the UI Thread alright, but - since `BeginInvoke` 'd - postponed to a point, where not only the current Window Message would be finished without blocking, but other meanwhile queued messaged would also be processed before setting up the complex dialog. And that would make up the way smoother experience, which `ShowDialogAsync` promises.

> Should dialogs (across the application dialog APIs) open in the order you requested them?

Yes, and I think they do - here is why. Since the check for the task completion sources is locked, a concurrent attempt to `Show[Dialog]Async` the same instance of a Form from different threads would fail way before marshalling it to the UI Thread. And since only the UI Thread will effectively show the Forms which are requested to be asynchronously shown, the Form will appear in the order you requested them.

2024-08-11 18:47 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +            if (_tcsNonModalForm is not null)
First part: Since everything except the initial calls to `ShowAsync` or `ShowDialogAsync` will run on the UI Thread, I cannot think of an edge case, where the completion source could be change underneath. There is only `Close` / `Dispose` which `null` it. If I call them from a different thread, I am getting a cross-thread-exception. The call back from `Application.ThreadException` also originate from a message queue message, so: UI Thread. And closing the UI (the form) by the user is also calling `Close` / `Dispose` on the UI-Thread. So, since everything potential changing the task completion source in my opinion is running on the UI thread, I do not see a scenario, where the completion source can be changed while running this method. Thinking more about this, I am almost certain, that we do not need to even need to lock this here, don't you think?

Second part: Sure, I'll change it!

2024-08-11 19:41 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/DiagnosticIDs.cs
> +    public const string UrlFormat = "https://aka.ms/winforms-experimental/{0}";
My thinking is that we later have more AKAs, like winforms-experimental and winforms-warnings and ... so we can have more landing pages for categories.  But I have no preference. If you want this all warnings, I can create a new alias.

2024-08-11 19:55 UTC, JeremyKuhne commented on src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/DiagnosticIDs.cs
> +    public const string UrlFormat = "https://aka.ms/winforms-experimental/{0}";
Let's start with following the libraries pattern.

2024-08-11 19:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/GlobalSuppressions.cs
> +[assembly: SuppressMessage("ApiDesign", "RS0026:Do not add multiple public overloads with optional parameters", Justification = "<Pending>", Scope = "member", Target = "~M:System.Windows.Forms.Contro
Can't leave this with "<Pending>"

2024-08-11 20:00 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/GlobalSuppressions.cs
> +[assembly: SuppressMessage("ApiDesign", "RS0026:Do not add multiple public overloads with optional parameters", Justification = "<Pending>", Scope = "member", Target = "~M:System.Windows.Forms.Contro
"False positive" is fine

2024-08-11 20:29 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        void ShowDialogProc(ref TaskCompletionSource<DialogResult> tcsModalForm, IWin32Window? owner = default)
Another tcs instance

2024-08-11 20:29 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +    ///  The task will complete when the form is closed or disposed.
nit: tag indentation

2024-08-11 20:31 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/TaskDialog/TaskDialog.cs
> +    ///   Shows the task dialog with the specified owner asynchronously.
nit: 1 space indenting for XML tags

2024-08-11 21:02 UTC, JeremyKuhne approved these changes
Looks good!

2024-08-11 21:42 UTC, merged

2024-08-11 23:04 UTC, RussKie commented on src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/DiagnosticIDs.cs
> +    public const string UrlFormat = "https://aka.ms/winforms-experimental/{0}";
NB: now you have two copies of the same const:
![image](https://github.com/user-attachments/assets/7c6e19e2-aaeb-4981-a5a1-5a1ae06d2989)

2024-08-12 17:45 UTC, JeremyKuhne commented on src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/DiagnosticIDs.cs
> +    public const string UrlFormat = "https://aka.ms/winforms-experimental/{0}";
@RussKie thanks for pointing this out. We'll clean it up.

2024-08-12 17:46 UTC, JeremyKuhne commented
Fixes #4631

2024-08-16 09:01 UTC, Olina-Zhang commented
Verified it in Winforms Release/9.0 branch, we can see these Async APIs.

2024-08-26 06:01 UTC, Zheng-Li01 commented
Verified the issue with .NET 9.0.100-rc.1.24422.10 test pass build, for now the InvokeAsync. ShowAsync, ShowDialogAsync APIs has been implemented.

2024-09-04 02:04 UTC, Zheng-Li01 commented
Verified the issue with .NET 9.0.100-rc.1.24452.12 test pass build, for now the InvokeAsync. ShowAsync, ShowDialogAsync APIs has been implemented.