Add Dark Mode Visual Style Theme Subclass
dotnet/winforms pull request #11985
Opened 2024-08-25 17:48 UTC by memoarfaa

This is an improvement to  new Dark Mode experimental feature 
 https://github.com/dotnet/winforms/pull/11857
see 
https://learn.microsoft.com/en-us/windows/win32/controls/theme-subclasses#two-ways-to-use-a-theme-subclass

Fixes https://github.com/dotnet/winforms/issues/11893.
Fixes https://github.com/dotnet/winforms/issues/11953.

2024-08-25 18:48 UTC, memoarfaa commented
@dotnet-policy-service agree

في الأحد، ٢٥ أغسطس ٢٠٢٤ ٨:٤٩ م dotnet-policy-service[bot] <
***@***.***> كتب:

> Assigned #11985 <https://github.com/dotnet/winforms/pull/11985> to
> @memoarfaa <https://github.com/memoarfaa>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dotnet/winforms/pull/11985#event-14004926109>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC7KK2CGY675YZFK4S663ZDZTIKK5AVCNFSM6AAAAABNCXIQDKVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGAYDIOJSGYYTAOI>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-08-26 03:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCheckBoxCell.cs
> +
The double blank line is causing the build to fail.

2024-08-26 03:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBoxRenderer.cs
> +        : VisualStyleElement.ComboBox.DropDownButton.Normal;
The agreed styling in the repo AFAIK is as follows:
```suggestion
    private static readonly VisualStyleElement s_comboBoxElement = Application.IsDarkModeEnabled
        ? VisualStyleElement.CreateElement("DarkMode_CFD::COMBOBOX", 1, 1)
        : VisualStyleElement.ComboBox.DropDownButton.Normal;
```

2024-08-26 03:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewButtonCell.cs
> +    private static readonly VisualStyleElement s_darkButtonElement = VisualStyleElement.CreateElement("DarkMode_Explorer::BUTTON", 1, 1);
I think, instead of hardcoding "DarkMode_Explorer" it should be an interpolated const, e.g.: `{DarkModeIdentifier}_{Explorer}`.
See:
https://github.com/dotnet/winforms/blob/14acefa2ad27de0425ae3fe914204bc045f1e6d1/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L162-L165

If any more consts need adding - they should be added here.

2024-08-26 03:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabRenderer.cs
> +        // see https://learn.microsoft.com/en-us/windows/win32/controls/theme-subclasses.
Links shouldn't have locale information
```suggestion
        // see https://learn.microsoft.com/windows/win32/controls/theme-subclasses.
```

2024-08-26 03:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +    /// </summary>
The `summary` section needs to explain the purpose of an API.
The `returns` section explains the return values.

You can see examples in the codebase and/or check this doc: https://learn.microsoft.com/dotnet/csharp/language-reference/xmldoc/recommended-tags.

2024-08-26 03:21 UTC, RussKie commented
@KlausLoeffelmann @JeremyKuhne @merriemcgaw  @lonitra - if this fixes the rendering issue, this change would be a great to addition to .NET 9 release.

2024-08-26 06:10 UTC, AraHaan commented
As long as I can use the new API to set color mode on my entire application from my settings form at runtime at *any* time to switch between light and dark mode I would be happy in the .NET 9 release.

2024-08-26 18:36 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +    public static bool IsDarkModeSupported
We also need to take any High Contrast mode into account. If any High Contrast mode is enabled, we do not allow dark mode.

2024-08-28 22:00 UTC, lonitra reviewed
Could you please also update the description to provide a visual of the before/after of this change?

2024-09-03 21:48 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +    /// </summary>
Sorry for the delay in replying, I was on a summer vacation in Sharm El Sheikh, Egypt.
The function was copied from the function before it so I assumed it was correct for some reason. Does the summary look good now?

2024-09-03 22:16 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabRenderer.cs
> +        // see https://learn.microsoft.com/en-us/windows/win32/controls/theme-subclasses.
thanks for this information.

2024-09-03 22:18 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCheckBoxCell.cs
> +
Thank you for bringing this to my attention.

2024-09-03 22:21 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewButtonCell.cs
> +    private static readonly VisualStyleElement s_darkButtonElement = VisualStyleElement.CreateElement("DarkMode_Explorer::BUTTON", 1, 1);
Done, does that look good now?

2024-09-03 22:23 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +    public static bool IsDarkModeSupported
Done, does that look good now?

2024-09-03 22:35 UTC, memoarfaa commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +                supported = hTheme != IntPtr.Zero;
The function was copied from the function before it so I assumed it was correct for some reason. Does it look good now?

2024-09-04 21:44 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewButtonCell.cs
> +    private static readonly VisualStyleElement s_darkButtonElement = VisualStyleElement.CreateElement("DarkMode_Explorer::BUTTON", 1, 1);
I believe this was missed
```suggestion
    private static readonly VisualStyleElement s_darkButtonElement = VisualStyleElement.CreateElement($"{Control.DarkModeIdentifier}_{Control.ExplorerThemeIdentifier}::BUTTON", 1, 1);
```

2024-09-04 21:44 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +    /// </summary>
```suggestion
    /// <summary>
    ///  Gets a value specifying whether the operating system has Dark Mode visual styles subclass and the Application can use this subclass to draw controls with Dark Mode theme.
    ///</summary>
    ///<return>
    /// <see langword="true"/> if Visual Style Dark Mode subclass is supported by the operating system,
    /// enabled in the client area, and operating system not running high contrast mode.</para>
    /// <para> Otherwise, returns <see langword="false"/>. Note that if <see langword="false"/> is returned, attempts to create/use objects of this class will throw exceptions.</para>
    ///</return>
```

2024-09-04 21:44 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +    public static bool IsDarkModeSupported
At this point we cannot add new public API for net 9. Does this need to be public?

2024-09-04 21:44 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> -        int systemColorMode = SystemDarkModeDisabled;
This is still outstanding. Could you revert this change?

2024-09-04 21:51 UTC, KlausLoeffelmann requested changes
Hey @memoarfaa,

I have a couple of additional issues which need to be addressed - most of them are just using consts for the theme names, so nothing big.

That said, while we would need to take a closer look at your proposed additional API for .NET 10, we cannot take that in RC2 for .NET 9 since we're way past code complete. Also, for new APIs, we need to bring that to the API review board, and it has to be officially discussed and then agreed to.

If you can do these changes on short notice, that would be nice, because the cut-of-date is approaching, and you bug fix would need to be tested before!

Thanks so much for doing this - we really appreciate!!

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> +static System.Windows.Forms.VisualStyles.VisualStyleRenderer.IsDarkModeSupported.get -> bool
We cannot take new APIs at this point. So, this needs to be reverted.

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> -        int systemColorMode = SystemDarkModeDisabled;
This needs to be as it is, please revert this.

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> -        return systemColorMode;
Same here - we need to keep this.

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBoxRenderer.cs
> +        ? VisualStyleElement.CreateElement($"{Control.DarkModeIdentifier}_{Control.ComboBoxButtonThemeIdentifier}::COMBOBOX", 1, 1)
Could you introduce a const for `COMBOBOX` as well?

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewButtonCell.cs
> +    private static readonly VisualStyleElement s_darkButtonElement = VisualStyleElement.CreateElement("DarkMode_Explorer::BUTTON", 1, 1);
Actually, I do not see that you changed anything.
Can you make the changes?

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCheckBoxCell.cs
> +    private static readonly VisualStyleElement s_darkCheckBoxElement = VisualStyleElement.CreateElement($"{Control.DarkModeIdentifier}_{Control.ExplorerThemeIdentifier}::BUTTON", 3, 1);
Can you introduce a const for the button part as well?

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellRenderer.cs
> +                    ?  VisualStyleElement.CreateElement($"{Control.DarkModeIdentifier}_{Control.ItemsViewThemeIdentifier}::Header", 1, 1)
Can you introduce a const for the Header part as well?

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewColumnHeaderCell.cs
> +        ? VisualStyleElement.CreateElement($"{Control.DarkModeIdentifier}_{Control.ItemsViewThemeIdentifier}::Header", 1, 1)
Same here?

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.DataGridViewComboBoxCellRenderer.cs
> +            ? VisualStyleElement.CreateElement($"{Control.DarkModeIdentifier}_{Control.ComboBoxButtonThemeIdentifier}::COMBOBOX", 6, 1)
Can you address the Combox text as well (both spots)? Thanks!

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.DataGridViewComboBoxCellRenderer.cs
> +            ? VisualStyleElement.CreateElement($"{Control.DarkModeIdentifier}_{Control.ComboBoxButtonThemeIdentifier}::COMBOBOX", 5, 1)
And here! 😸

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRowHeaderCell.cs
> +        ? VisualStyleElement.CreateElement($"{Control.DarkModeIdentifier}_{Control.ItemsViewThemeIdentifier}::Header", 1, 1)
Same for the "Header".

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewTopLeftHeaderCell.cs
> +        ? VisualStyleElement.CreateElement($"{Control.DarkModeIdentifier}_{Control.ItemsViewThemeIdentifier}::Header", 1, 1)
And here! 😺

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabControl.cs
> +                PInvoke.SendMessage(tooltipHwnd, PInvoke.TTM_SETWINDOWTHEME, default, "DarkMode_Explorer");
Can you use the existing const here?

2024-09-04 21:51 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +            bool supported = AreClientAreaVisualStylesSupported;
This is too invasive a change this late in the game.
Can we revert this to the existing method, because that had been tested exhaustively?

2024-11-14 15:40 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabControl.cs
> +            _ = PInvoke.SetWindowTheme(
If not all tabs can be shown at once, the tab control will display an up-down control that will also need to be styled.

2025-03-24 04:20 UTC, KlausLoeffelmann commented
Closing this PR, as the author did not come back for a while to address requested issues.

We collected other suggestions over the time, which we'll start to implement now.

Please again note, that there is no urgency or necessity to rush these fixes for servicing, since Dark Mode is experimental, and experimental Features are never serviced.

2025-03-24 04:20 UTC, closed without merging