Add Unit test coverage for the PropertyGrid class
dotnet/winforms pull request #12098
Opened 2024-09-10 10:42 UTC by John-Qiao

Related https://github.com/dotnet/winforms/issues/12055

## Proposed changes

- Add unit test for PropertyGrid 49 properties and methods in PropertyGridTests.cs file.
- Enable nullability in PropertyGridTests.

2024-09-10 19:54 UTC, Tanya-Solyanik commented
@John-Qiao  - please fix the build failure

2024-09-12 07:57 UTC, LeafShi1 requested changes

2024-09-12 07:57 UTC, LeafShi1 commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridTests.cs
> +        (_propertyGrid.SelectedObjects)[0].Should().Be(btn1);
Consider directly define object collections and add null value validation
```
object[] objects = [new Button(), new TextBox(), null!];
_propertyGrid.SelectedObjects = objects;
```

2024-09-12 07:57 UTC, LeafShi1 commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridTests.cs
> +        if (_propertyGrid.SelectedGridItem is not null)
It would be better to use  `_propertyGrid.SelectedGridItem.Should().NotBeNull();`

2024-09-12 07:57 UTC, LeafShi1 commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridTests.cs
> +    public void PropertyGrid_LargeButtons_GetSet_ReturnsExpected()
Duplicate test with https://github.com/dotnet/winforms/blob/179219f07e55bdbc0cccfb5de926496a4795149f/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs#L2070

Please compare other test scenarios with file https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs

2024-09-30 06:51 UTC, Epica3055 commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridTests.cs
> +        _propertyGrid.RefreshTabs(PropertyTabScope.Component);
if we don't call `RefreshTabs` method, this case could also pass. 😂

2024-09-30 06:52 UTC, Epica3055 commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridTests.cs
> +        _propertyGrid.SelectedObjects = Array.Empty<object>();
consider simplifying it.
```suggestion
        _propertyGrid.SelectedObjects = [];
```

2024-09-30 06:52 UTC, Epica3055 commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridTests.cs
> +        Action act = () => _propertyGrid.SelectedObjects = objects;
```suggestion
        Action act = () => _propertyGrid.SelectedObjects = [];
```

2024-10-08 16:17 UTC, lonitra commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridTests.cs
> +        object[] objects = [new Button(), new TextBox(), new ComboBox()];
We should dispose these controls

2024-10-08 16:17 UTC, lonitra commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridTests.cs
> +public class PropertyGridTests : IDisposable
nit:
```suggestion
namespace System.Windows.Forms.UITests;

public class PropertyGridTests : IDisposable
```

2024-10-09 18:19 UTC, Tanya-Solyanik approved these changes
Thank you!

2024-10-09 18:19 UTC, Tanya-Solyanik commented
@LeafShi1  - please re-review this PR

2024-10-11 01:18 UTC, LeafShi1 approved these changes

2024-10-11 01:18 UTC, merged