Add code coverage for ToolStripSplitButton
dotnet/winforms pull request #12238
Opened 2024-09-27 02:01 UTC by Zheng-Li01

related https://github.com/dotnet/winforms/issues/10453

Proposed changes
Add unit tests for ToolStripSplitButton.cs to test its properties & methods & events

2024-09-27 07:15 UTC, LeafShi1 requested changes

2024-09-27 07:15 UTC, LeafShi1 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitButtonTests.cs
> +
If the target of the test is the constructor, you must ensure that the corresponding constructor is called. From the current test, only the Image property is tested, Other test cases also have this problem.
so this test here should like following, 

```
using Bitmap image1 = new Bitmap(10, 10);
_toolStripSplitButton = new("Test", image);

_toolStripSplitButton.SupportsSpaceKey.Should().BeTrue();
_toolStripSplitButton.Image.Should().Be(image);

int defaultDropDownButtonWidth = _toolStripSplitButton.TestAccessor().Dynamic.DefaultDropDownButtonWidth;
_toolStripSplitButton.DropDownButtonWidth.Should().Be(defaultDropDownButtonWidth);

_toolStripSplitButton = new("Test", image: null);
_toolStripSplitButton.Image = null;
_toolStripSplitButton.Image.Should().BeNull();
_toolStripSplitButton.DropDownButtonWidth.Should().Be(defaultDropDownButtonWidth);
```

The above example needs to be optimized

2024-09-27 17:30 UTC, ricardobossan reviewed
Other than existing comments, LGTM

2024-09-29 10:14 UTC, Epica3055 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitButtonTests.cs
> +        _toolStripSplitButton.DropDownButtonWidth.Should().Be(11);
```suggestion
        _toolStripSplitButton.DropDownButtonWidth.Should().Be(_toolStripSplitButton.TestAccessor().Dynamic.DefaultDropDownWidth);
```

And below as well.

2024-09-30 06:52 UTC, LeafShi1 reviewed
LGTM with a little question

2024-09-30 06:52 UTC, LeafShi1 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitButtonTests.cs
> +     {
Extra space

2024-10-01 06:19 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitButtonTests.cs
> +        toolStripSplitButton.Text.Should().BeEmpty();
```suggestion
        _toolStripSplitButton.Text.Should().BeEmpty();
```
I don't think you have to invoke constructor because we are guaranteed that it is called, we can test properties of our field.

2024-10-01 06:19 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitButtonTests.cs
> +
>If the target of the test is the constructor, you must ensure that the corresponding constructor is called.

This test is testing constructor with 2 arguments, not the default one that you call on line 16 in the test class constructor.
In this case we want to dispose button allocated on line 16 and then initialize that field using constructor that takes 2 arguments
>_toolStripSplitButton.Dispose();
_toolStripSplitButton = new("Test", image);

In other tests, that validate properties, we are guaranteed that the default constructor is called before the Fact runs. There is no need to execute it twice in other Facts.

2024-10-08 17:53 UTC, Tanya-Solyanik commented
@LeafShi1  - please re-review

2024-10-11 00:54 UTC, LeafShi1 approved these changes

2024-10-11 00:56 UTC, merged