Moved to SDK RC2
dotnet/winforms pull request #12254
Opened 2024-10-02 08:15 UTC by Tanya-Solyanik

Moved to SDK RC2 to get the same build errors in the VS and CLI build and be able to fix them.

Before this change the IntPreview version of VS was correctly complaining about a redundant cast(IDE0004) in ToolStrip.cs
    g.DrawLines(SystemPens.ControlText, (ReadOnlySpan<Point>)
        [
            new(verticalBeamStart, _lastInsertionMarkRect.Y), new(verticalBeamStart, _lastInsertionMarkRect.Bottom - 1),
            new(verticalBeamStart + 1, _lastInsertionMarkRect.Y), new(verticalBeamStart + 1, _lastInsertionMarkRect.Bottom - 1)
        ]);

But the CLI build required this cast.

After the upgrade to RC2, IDE0300 - Collection initialization can be simplified - became more robust and required code fixes that use collection expressions applied to the solution.

2024-10-02 17:13 UTC, JeremyKuhne commented on src/System.Drawing.Common/tests/System/Drawing/Drawing2D/GraphicsPathTests.cs
> +            () => gp.AddCurve([new(1, 1), new(2, 2)], 0, segment, 0.5f));
It seems odd that we're only updating the `Point` overload (and not `PointF`).

2024-10-02 17:14 UTC, JeremyKuhne requested changes
Left a few comments. Also: please double check to make _sure_ that the System.Drawing calls are binding to the span overloads and not the array ones.

2024-10-02 17:34 UTC, Tanya-Solyanik commented on src/System.Drawing.Common/tests/System/Drawing/Drawing2D/GraphicsPathTests.cs
> +            () => gp.AddCurve([new(1, 1), new(2, 2)], 0, segment, 0.5f));
I only updated places that we detected by rule only. I think analyzer does not detect floats correctly, this is the difference between the versions as I see it.

2024-10-02 18:04 UTC, Tanya-Solyanik commented on src/System.Drawing.Common/tests/System/Drawing/Drawing2D/GraphicsPathTests.cs
> +            () => gp.AddCurve([new(1, 1), new(2, 2)], 0, segment, 0.5f));
>        AssertExtensions.ThrowsAny<ArgumentException, ArgumentOutOfRangeException>(
>           () => gp.AddCurve([new(1f, 1f), new(2f, 2f)], 0, segment, 0.5f));

generates
>Argument 1: cannot convert from 'float' to 'int'

in VS after the update to rc2

2024-10-02 18:23 UTC, Tanya-Solyanik commented on src/System.Drawing.Common/tests/System/Drawing/Drawing2D/GraphicsPathTests.cs
> +            () => gp.AddCurve([new(1, 1), new(2, 2)], 0, segment, 0.5f));
Oh maybe the difference is more specifically in the PointF rather than any float

2024-10-02 18:29 UTC, Tanya-Solyanik commented
>please double check to make sure that the System.Drawing calls are binding to the span overloads and not the array ones.

If both n array and ReadonlySpan overloads are available, we resolve the span one in VS editor and when running tests.

> 	System.Drawing.Drawing2D.GraphicsPath.AddLines(System.ReadOnlySpan<System.Drawing.Point> points) Line 361	C#
>	System.Drawing.Drawing2D.Tests.GraphicsPathTests.AddLines_Success() Line 256	C#

2024-10-03 00:21 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StyleEditorForm.cs
> +            _percentNumericUpDown.Maximum = new decimal(lo: 9999, mid: 0, hi: 0, isNegative: false, scale: 0);
You should be able to just call `new decimal(9999)`. The _most_ performant one is `new decimal(9999u)`, but not by much.

2024-10-03 01:23 UTC, merged