Add unit tests for DesignerExtenders
dotnet/winforms pull request #12337
Opened 2024-10-16 07:29 UTC by MelonWang1

Related https://github.com/dotnet/winforms/issues/10773

## Proposed changes

- Add unit test DesignerExtendersTests.cs for public properties and method of the DesignerExtenders.
- Enable nullability in DesignerExtenders.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/12337)

2024-10-18 02:28 UTC, LeafShi1 requested changes

2024-10-18 02:28 UTC, LeafShi1 commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerExtendersTests.cs
> +    }
The reflection can be replaced by invoking TestAccessor().Dynamic

```
 IExtenderProvider[] providersField = _designerExtenders.TestAccessor().Dynamic._providers;
IExtenderProviderService extenderServiceField = _designerExtenders.TestAccessor().Dynamic._extenderService;

providersField.Should().NotBeNull();
extenderServiceField.Should().NotBeNull();

// Dispose the designer extenders and verify the expected behavior
_designerExtenders.Dispose();
_extenderServiceMock.Verify(s => s.RemoveExtenderProvider(It.IsAny<IExtenderProvider>()), Times.Exactly(2));
_designerExtenders.Invoking(d => d.Dispose()).Should().NotThrow();

providersField = _designerExtenders.TestAccessor().Dynamic._providers;
extenderServiceField = _designerExtenders.TestAccessor().Dynamic._extenderService;

providersField.Should().BeNull();
extenderServiceField.Should().BeNull();
```

2024-10-18 09:38 UTC, LeafShi1 submitted a review, later dismissed

2024-10-18 21:55 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerExtendersTests.cs
> +        IExtenderProvider[] providersField = _designerExtenders.TestAccessor().Dynamic._providers;
We can simplify this name, and service's too.
```suggestion
        IExtenderProvider[] providers = _designerExtenders.TestAccessor().Dynamic._providers;
```

2024-10-18 21:55 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerExtendersTests.cs
> +        _designerExtenders.Dispose();
Since your test case is disposing this object, you don't have dispose it after the test finishes. That would lead to disposing the object twice. You can remove IDisposable from the test class and allocate both Mock<IExtenderProviderService> and DesignerExtenders  in the test case (Fact) directly.

2024-10-21 19:19 UTC, lonitra approved these changes

2024-10-22 05:50 UTC, merged