Add code coverage for ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter
dotnet/winforms pull request #12394
Opened 2024-10-28 06:06 UTC by Zheng-Li01

related https://github.com/dotnet/winforms/issues/10453

**Proposed changes**
Add unit tests for ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs to test its properties & methods

2024-10-29 01:30 UTC, ricardobossan reviewed
If checks pass, all LGTM.

2024-10-29 01:30 UTC, ricardobossan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
Is there a reason why the CI tests are not runnig?

2024-10-29 01:30 UTC, ricardobossan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
Is there a reason why the CI tests are not runnig?

2024-10-29 01:55 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
> Is there a reason why the CI tests are not runnig?
Not sure, but for previous PRs which also included this line for the new add file, and the PR working well, same as https://github.com/dotnet/winforms/pull/12316/files.

2024-10-29 12:45 UTC, ricardobossan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
My comment is not related to any particular line in the code, so I just chose the first one.

2024-10-29 22:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +        _comboBox = null;
You don't have to set it to null because it is highly unlikely this class would be reused, as we are not passing the test class around. It will be more convenient to declare both fields as readonly.

2024-10-29 22:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +        if (isToolStripComboBoxControl)
I would prefer 2 tests instead of a theory in this case as each step in this test depends on the input data

2024-10-29 22:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +        ProfessionalColorTable colorTable = (ProfessionalColorTable)_adapter!.TestAccessor().Dynamic.GetColorTable(_comboBox!);
Consider
```suggestion
        var colorTable = (ProfessionalColorTable)_adapter!.TestAccessor().Dynamic.GetColorTable(_comboBox!);
```

2024-10-29 22:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +        _comboBox!.Enabled = enabled;
if you declare this field as readonly, you wouldn't need the null forgiving operator (!)

2024-10-30 19:44 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +        if (!isToolStripComboBoxControl)
I'm not sure I understand what `isToolStripComboBoxControl` is being used for. It doesn't seem to be used in setting anything so we should remove it completely.

2024-10-30 19:44 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> +    public void UseBaseAdapter_ThrowsException_ForNonToolStripComboBoxControl(bool isToolStripComboBoxControl)
Ditto here as well.

2024-11-01 18:25 UTC, Tanya-Solyanik submitted a review, later dismissed

2024-11-01 23:53 UTC, lonitra requested changes

2024-11-01 23:53 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> -    }
I believe we want to keep this test to have coverage for `ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.UseBaseAdapter(ComboBox)`, but this can just be a `WinFormsFact` instead of theory.

2024-11-04 07:05 UTC, Zheng-Li01 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> -    }
For this test case, which always failed for the pipeline as below.

```
System.Windows.Forms.Tests.ToolStripComboBox_ToolStripComboBoxFlatComboAdapterTests.UseBaseAdapter_ThrowsException_ForNonToolStripComboBoxControl

Expected boolean to be true because the UseBaseAdapter method should be called and throw an InvalidOperationException, but found False.
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Primitives.BooleanAssertions`1.BeTrue(String because, Object[] becauseArgs)
   at System.Windows.Forms.Tests.ToolStripComboBox_ToolStripComboBoxFlatComboAdapterTests.UseBaseAdapter_ThrowsException_ForNonToolStripComboBoxControl() in /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs:line 57
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
   However, actually this test case can run successfully on local machine with same code as below.
```
   Executing test method: System.Windows.Forms.Tests.ToolStripComboBox_ToolStripComboBoxFlatComboAdapterTests.UseBaseAdapter_ThrowsException_ForNonToolStripComboBoxControl
========== Starting test run ==========
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.8.1+ce9211e970 (64-bit .NET 10.0.0-alpha.1.24526.4)
[xUnit.net 00:00:00.64]   Starting:    System.Windows.Forms.Tests
[xUnit.net 00:00:00.96]   Finished:    System.Windows.Forms.Tests
========== Test run finished: 1 Tests (1 Passed, 0 Failed, 0 Skipped) run in 977 ms ==========
```
So I removed this test case for this PR, and will investigate the failed reason and will fix it on another PR.

2024-11-04 18:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
> -    }
@Zheng-Li01 
```
            private static bool UseBaseAdapter(ComboBox comboBox)
            {
                if (comboBox is not ToolStripComboBoxControl toolStripComboBox
                    || toolStripComboBox.Owner?.Renderer is not ToolStripProfessionalRenderer)
                {
                    Debug.Assert(comboBox is ToolStripComboBoxControl, "Why are we here and not a toolstrip combo?");
                    return true;
                }
```

This method does not throw, it raises a Debug.Assert. When you run this test locally, you have an Assert listener set up by the tooling, but the CI run does not have one. This explains the difference.

@lonitra  - I would rather keep this assert in the source code and not test the private method. Assert is informative for debugging. I think we have a test class wrapper that suppresses asserts in the local runs. Once you can run tests in a context that suppresses asserts in the debug build, this private method can be tested via the Get*Color protected methods by passing in a plain ComboBox, not a ToolStripComboBox.

2024-11-05 17:07 UTC, lonitra approved these changes

2024-11-05 17:08 UTC, merged