Sealed the internal DataStore class, and some minor clean-up
dotnet/winforms pull request #12503
Opened 2024-11-17 22:28 UTC by Tanya-Solyanik

2024-11-17 22:40 UTC, Tanya-Solyanik commented on src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/ComputerTests.cs
> -[UISettings(MaxAttempts = 3)] // Try up to 3 times before failing.
This test does not invoke OLE interfaces

2024-11-17 22:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropHelperTests.cs
> -                Assert.Equal(0, (int)PInvokeCore.GlobalSize(dragDropFormat.Medium.hGlobal));
`GlobalSize` native function throws an AV when invoked with a null parameter. This line is not verifying anything additional to comparison to `nint.Zero` below.

2024-11-18 18:12 UTC, JeremyKuhne requested changes
Some minor comments

2024-11-18 19:37 UTC, JeremyKuhne commented on src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/ComputerTests.cs
> +// This class does not access system singletons, it is safe to run in parallel.
Move to the clipboard method

```suggestion
// This method does not actually access the clipboard and as such, it is safe to run in parallel.
```

2024-11-18 19:48 UTC, Tanya-Solyanik commented on src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/ComputerTests.cs
> +// This class does not access system singletons, it is safe to run in parallel.
Sequential collection is not dedicated to the clipboard. It's used for mouse position as well.

2024-11-18 21:34 UTC, Tanya-Solyanik commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsApplicationBaseTests.vb
> -        Public Sub Run_SingleInstanceNoStartupFormException()
@paul1956  - we shouldn't call `WindowsFormsApplicationBase.Run` method in tests because it attempts to alter the application state:
```
 Expected a <Microsoft.VisualBasic.ApplicationServices.NoStartupFormException> to be thrown, but found <System.InvalidOperationException>: 
"\r\n"System.InvalidOperationException: We could net set the HighDpiMode.\r\n
   at System.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Common/tests/TestUtilities/ThrowingTraceListener.cs:line 14\r\n   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)\r\n
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)\r\n
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)\r\n
   at System.Diagnostics.Debug.Assert(Boolean condition, String message)\r\n
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnInitialize(ReadOnlyCollection1 commandLineArgs) in /_/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb:line 779\r\n
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel() in /_/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb:line 524\r\n
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine) in /_/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb:line 1055\r\n
```

2024-11-18 22:16 UTC, JeremyKuhne commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsApplicationBaseTests.vb
> -        Public Sub Run_SingleInstanceNoStartupFormException()
You could (and probably should) move this to the remote executor.

2024-11-18 23:26 UTC, paul1956 commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsApplicationBaseTests.vb
> -        Public Sub Run_SingleInstanceNoStartupFormException()
@Tanya-Solyanik @JeremyKuhne do I have an issue I need to deal with?

2024-11-18 23:27 UTC, JeremyKuhne approved these changes

2024-11-18 23:42 UTC, merged

2024-12-09 21:21 UTC, Tanya-Solyanik commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsApplicationBaseTests.vb
> -        Public Sub Run_SingleInstanceNoStartupFormException()
No, it was re-enabled and moved to the remote executor