Bump up NuGet Packs and apply new Analyzer Rules.
dotnet/winforms pull request #12512
Opened 2024-11-20 02:21 UTC by KlausLoeffelmann

Updates the NuGet packages to the latest versions and applies the new respective Analyzer Rules.

2024-11-20 23:19 UTC, JeremyKuhne requested changes
Minor comments. If many/most methods of a struct or class are unsafe we're leaning towards mark the whole type unsafe.

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Private.Windows.Core/src/Windows/Win32/Graphics/Gdi/CreateDcScope.cs
> +    public static unsafe implicit operator HGDIOBJ(in CreateDcScope scope) => (HGDIOBJ)(scope.HDC.Value);
There really should be an implicit operator on `HDC` to convert to `HGDIOBJ` as that cast is always legit. Then this can just be `scope.HDC`.

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Private.Windows.Core/src/Windows/Win32/Graphics/Gdi/CreatePenScope.cs
> +    public static unsafe implicit operator HGDIOBJ(in CreatePenScope scope) => (HGDIOBJ)scope.HPEN.Value;
As mentioned above, should have an implicit conversion operator on `HPEN` to go to `HGDIOBJ`.

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Private.Windows.Core/src/Windows/Win32/Graphics/Gdi/HGDIOBJ.cs
> +    public static unsafe implicit operator HGDIOBJ(HDC value) => (HGDIOBJ)value.Value;
mark the struct instead

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Private.Windows.Core/src/Windows/Win32/UI/WindowsAndMessaging/HCURSOR.cs
> +    public static unsafe explicit operator HCURSOR(HANDLE handle) => new((nint)handle);
mark the struct unsafe

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Private.Windows.Core/src/Windows/Win32/UI/WindowsAndMessaging/HICON.cs
> +    public static unsafe explicit operator HICON(HANDLE handle) => new((nint)handle);
mark the struct unsafe

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Private.Windows.Core/src/Windows/Win32/UI/WindowsAndMessaging/ICONINFO.cs
> +    public unsafe void Dispose()
mark the struct unsafe

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.ModalMenuFilter.HostedWindowsFormsMessageHook.cs
> +                        (HINSTANCE)(nint)0,
```suggestion
                        HINSTANCE.Null,
```

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.MouseHook.cs
> +                    (HINSTANCE)(nint)0,
```suggestion
                    HINSTANCE.Null,
```

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/tests/TestUtilities/Win32/WindowClass.cs
> +                    hInstance: (HINSTANCE)(nint)0,
```suggestion
                    hInstance: HINSTANCE.Null,
```

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/tests/TestUtilities/Win32/WindowClass.cs
> +                        hInstance: (HINSTANCE)(nint)0,
```suggestion
                        hInstance: HINSTANCE.Null,
```

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/tests/TestUtilities/Win32/WindowClass.cs
> +            cursor = PInvoke.LoadCursor((HINSTANCE)(nint)0, (PCWSTR)(char*)PInvoke.IDC_ARROW);
```suggestion
            cursor = PInvoke.LoadCursor(HINSTANCE.Null, (PCWSTR)(char*)PInvoke.IDC_ARROW);
```

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/tests/TestUtilities/Win32/WindowClass.cs
> +            icon = PInvokeCore.LoadIcon((HINSTANCE)(nint)0, (PCWSTR)(char*)PInvokeCore.IDI_APPLICATION);
```suggestion
            icon = PInvokeCore.LoadIcon(HINSTANCE.Null, (PCWSTR)(char*)PInvokeCore.IDI_APPLICATION);
```

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.MouseHook.cs
> +                        (HINSTANCE)(nint)0,
```suggestion
                        HINSTANCE.Null,
```

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Input/Cursor.cs
> +        _handle = PInvoke.LoadCursor((HINSTANCE)(nint)0, nResourceId);
```suggestion
        _handle = PInvoke.LoadCursor(HINSTANCE.Null, nResourceId);
```

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.WindowClass.cs
> +                    if (!PInvoke.GetClassInfo((HINSTANCE)(nint)0, n, &windowClass))
```suggestion
                    if (!PInvoke.GetClassInfo(HINSTANCE.Null, n, &windowClass))
```

2024-11-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs
> +                    Control? window = GetCurrentToolWindow();
nit: `if (GetCurrentToolWindow() is Control window)`

2024-11-20 23:19 UTC, JeremyKuhne commented on eng/Versions.props
> +    <MicrosoftCodeAnalysisAnalyzersVersion>3.12.0-beta1.24559.1</MicrosoftCodeAnalysisAnalyzersVersion>
We'll want to update the versions for WPF as well. I'll sync with you on that.

2024-11-22 23:20 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs
> +                    if (GetCurrentToolWindow() is Control window)
Should this still be IWin32Window? Below code seems to indicate it may not always be a Control

2024-11-22 23:20 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/HiDpi/DPI_AWARENESS_CONTEXT.cs
> +            && (bool)PInvoke.AreDpiAwarenessContextsEqual(this, dpiContext));
nit for readability:
```suggestion
            || (OsVersion.IsWindows10_1607OrGreater()
                && (bool)PInvoke.AreDpiAwarenessContextsEqual(this, dpiContext));
```

2024-12-08 21:22 UTC, KlausLoeffelmann commented on src/System.Private.Windows.Core/src/Windows/Win32/Graphics/Gdi/CreatePenScope.cs
> +    public static unsafe implicit operator HGDIOBJ(in CreatePenScope scope) => (HGDIOBJ)scope.HPEN.Value;
There already was. Calling `Value` was redundant.

2024-12-09 20:48 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/HiDpi/DPI_AWARENESS_CONTEXT.cs
> +            && (bool)PInvoke.AreDpiAwarenessContextsEqual(this, dpiContext));
`&&` shouldn't be on the same level because it is within a parenthesis with `OsVersion.IsWindows10_1607OrGreater()`
```suggestion
        (this == UNSPECIFIED_DPI_AWARENESS_CONTEXT && dpiContext == UNSPECIFIED_DPI_AWARENESS_CONTEXT)
        || (OsVersion.IsWindows10_1607OrGreater()
            && (bool)PInvoke.AreDpiAwarenessContextsEqual(this, dpiContext));
```

2024-12-09 20:48 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/HiDpi/DPI_AWARENESS_CONTEXT.cs
> +    internal static DPI_AWARENESS_CONTEXT UNSPECIFIED_DPI_AWARENESS_CONTEXT { get; } = Null;
Why did we change this to Null? Is this now defined in cswin32?

2024-12-09 21:36 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/HiDpi/DPI_AWARENESS_CONTEXT.cs
> +            && (bool)PInvoke.AreDpiAwarenessContextsEqual(this, dpiContext));
Oh, you're right. I did not catch that.

2024-12-09 22:39 UTC, lonitra approved these changes

2024-12-09 22:43 UTC, merged