Add unit tests for LinkUtilities
dotnet/winforms pull request #12647
Opened 2024-12-16 10:14 UTC by Olina-Zhang

related https://github.com/dotnet/winforms/issues/10453

## Proposed changes

- Add unit tests for LinkUtilities to test its  GetIELinkBehavior and EnsureLinkFonts methods.

2024-12-17 23:31 UTC, ricardobossan requested changes
There are failing tests in the CI that need to be addressed.

2024-12-17 23:31 UTC, ricardobossan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkUtilitiesTests.cs
> +        using var key = Microsoft.Win32.Registry.CurrentUser.CreateSubKey(LinkUtilities.IEMainRegPath);
Please declare variables as specific types instead of using `var`.

2024-12-17 23:31 UTC, ricardobossan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkUtilitiesTests.cs
> +        using var key = Microsoft.Win32.Registry.CurrentUser.CreateSubKey(LinkUtilities.IEMainRegPath);
Please declare variables as specific types instead of using `var`.

2024-12-18 03:13 UTC, Olina-Zhang commented
> There are failing tests in the CI that need to be addressed.

I don't why test scenarios failed, because all are passed in my local machine:
![image](https://github.com/user-attachments/assets/93800f6b-ae4d-4888-af62-10795dc32855)

2024-12-18 19:21 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkUtilitiesTests.cs
> +    public void LinkUtilities_EnsureLinkFonts_CreatesExpectedFonts(LinkBehavior behavior, FontStyle linkFontStyle, FontStyle hoverLinkFontStyle)
This test fails in CI with

System.Windows.Forms.Tests.LinkUtilitiesTests.LinkUtilities_EnsureLinkFonts_CreatesExpectedFonts(behavior: SystemDefault, linkFontStyle: Regular, hoverLinkFontStyle: Regular)
Error message
Expected the enum to be FontStyle.Regular {value: 0}, but found FontStyle.Underline {value: 4}.



Stack trace
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Primitives.EnumAssertions`2.Be(TEnum expected, String because, Object[] becauseArgs)
   at System.Windows.Forms.Tests.LinkUtilitiesTests.LinkUtilities_EnsureLinkFonts_CreatesExpectedFonts(LinkBehavior behavior, FontStyle linkFontStyle, FontStyle hoverLinkFontStyle) in D:\a\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\LinkUtilitiesTests.cs:line 49
   at InvokeStub_LinkUtilitiesTests.LinkUtilities_EnsureLinkFonts_CreatesExpectedFonts(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, Culture

2024-12-18 19:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkUtilitiesTests.cs
> +        linkFont!.Style.Should().Be(linkFontStyle);
To get rid of the null-forgiving operator(!), you can use `.Should().BeOfType(Font).Subject` instead of `NotBeNull()`

2024-12-18 19:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkUtilitiesTests.cs
> +    public void LinkUtilities_EnsureLinkFonts_CreatesExpectedFonts(LinkBehavior behavior, FontStyle linkFontStyle, FontStyle hoverLinkFontStyle)
The reason CI gets a different default value is that this value comes from the registry - https://github.com/dotnet/winforms/blob/7d887519300b04881d228ca5fa5ee3ffcecca570/src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/LinkUtilities.cs#L126-L133
and it might be different from what you have on your machine.
For this property value we can only test that we don't throw when setting it, we can't validate the resulting value.

2024-12-18 19:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkUtilitiesTests.cs
> +        linkFont!.Style.Should().Be(linkFontStyle);
Tis applies in multiple places in this PR

2024-12-19 15:43 UTC, ricardobossan approved these changes

2024-12-20 22:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkUtilitiesTests.cs
> +        RegistryKey? key = Registry.CurrentUser.CreateSubKey(LinkUtilities.IEMainRegPath);
Registry values are machine-wide singletons, multiple test cases might be accessing them at the same time. If we are changing these values, we have to move all tests that read and write them into a sequential collection. It will be hard to identify all tests that read these values behind the scenes. And we might miss that the future tests read this value going forward.
Instead of writing this key I would suggest to read it, and set the right expected LinkBehavior based on the key value.

2025-01-07 04:22 UTC, Tanya-Solyanik approved these changes
Thank you, looks good!

2025-01-07 04:23 UTC, merged