Add unit tests for ControlDesigner.ControlDesignerAccessibleObject
dotnet/winforms pull request #12664
Opened 2024-12-20 09:36 UTC by MelonWang1

Related https://github.com/dotnet/winforms/issues/10773

## Proposed changes

- Add unit test ControlDesigner.ControlDesignerAccessibleObjectTests.cs for public properties and method of the ControlDesigner.ControlDesignerAccessibleObject.

- Enable nullability in ControlDesigner.ControlDesignerAccessibleObjectTests.cs.

2024-12-20 19:02 UTC, ricardobossan requested changes

2024-12-20 19:02 UTC, ricardobossan commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObjectTests.cs
> +    public void Properties_ReturnExpectedValues(object expectedValue, string propertyName)
This method has the same concerns as `Methods_ReturnExpectedResults(AccessibleStates state, string methodName, int x = 0, int y = 0)`. Specifically:

- Avoid excessive abstraction in unit tests.
- Minimize the use of reflection to reduce complexity and improve readability.

Straightforward and explicit unit tests for each property would be preferable.

2024-12-23 21:00 UTC, ricardobossan approved these changes
Thank you!

2025-01-07 04:19 UTC, Tanya-Solyanik reviewed
Looks good, I added some minor comments only.

2025-01-07 04:19 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObjectTests.cs
> +public class ControlDesignerControlDesignerAccessibleObjectTests : IDisposable
```suggestion
public class ControlDesignerAccessibleObjectTests : IDisposable
```
To improve readability.

2025-01-07 04:19 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObjectTests.cs
> +public class ControlDesignerControlDesignerAccessibleObjectTests : IDisposable
Please also rename the tests cases.

2025-01-07 04:19 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObjectTests.cs
> +    public ControlDesignerControlDesignerAccessibleObjectTests()
Consider using expression-bodied syntax for single line functions
public ControlDesignerControlDesignerAccessibleObjectTests() => _designer = new();

2025-01-07 19:33 UTC, Tanya-Solyanik approved these changes
Thank you, looks good!

2025-01-07 19:33 UTC, merged