Write unit test for DataGridViewAddColumnDialog
dotnet/winforms pull request #12662
Opened 2024-12-20 01:51 UTC by Liv-Goh

Related https://github.com/dotnet/winforms/issues/10773

## Proposed changes
1. Add unit test DataGridViewAddColumnDialogTests.cs for public properties and method of the DataGridViewAddColumnDialog.
2. Enable nullability in DataGridViewAddColumnDialogTests.cs.

2024-12-20 16:07 UTC, ricardobossan reviewed
Other than small comments, all LGTM!

2024-12-20 17:54 UTC, ricardobossan requested changes

2024-12-20 17:54 UTC, ricardobossan commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewAddColumnDialogTests.cs
> +        DataGridView dataGridView = new();
Please dispose of created controls with `using` statements. This happens in several places in this file.

2024-12-23 20:01 UTC, ricardobossan commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewAddColumnDialogTests.cs
> +        ComponentDesigner? result = DataGridViewAddColumnDialog.GetComponentDesignerForType(typeResolutionService, type);
Please add a `using` statement here.

2024-12-23 20:01 UTC, ricardobossan commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewAddColumnDialogTests.cs
> +        ComponentDesigner? result = DataGridViewAddColumnDialog.GetComponentDesignerForType(typeResolutionService, type);
Please add a `using` statement here.

2024-12-27 00:19 UTC, ricardobossan approved these changes
Thank you!

2025-01-07 03:53 UTC, Tanya-Solyanik approved these changes
Thank you, looks good!

2025-01-07 03:53 UTC, merged