Recalculate the node position of the TreeView when DrawMode = TreeViewDrawMode.OwnerDrawText
dotnet/winforms pull request #12698
Opened 2024-12-31 08:05 UTC by LeafShi1

Fixes #12681

## Root Cause
When `treeView.DrawMode = TreeViewDrawMode.OwnerDrawText`, the node's `FillRectangle` and `FocusRectangle` positions are calculated incorrectly

## Proposed changes

- Update function `CustomDraw` of the TreeView.cs, When `RightToLeft == RightToLeft.Yes && RightToLeftLayout` reverses the X drawing coordinates of `FillRectangle` and `FocusRectangle`

## Customer Impact

- When setting RightToLeft = Yes and RightToLeftLayout = True, the selected node box is fully rendered

## Regression? 

-  No

## Risk

- Minimal

## Screenshots 

### Before
<img width="233" alt="image" src="https://github.com/user-attachments/assets/b6f30d07-bb92-4028-96c6-4a9afa923af9" />

### After
When setting RightToLeft = Yes, RightToLeftLayout = True and .DrawMode = TreeViewDrawMode.OwnerDrawText, the selected node box is fully rendered
<img width="290" alt="image" src="https://github.com/user-attachments/assets/10aaa43c-7627-4c2d-a587-45a537c4ac91" />

## Test methodology 

- Manually

## Test environment(s) 

- .net 10.0.0-alpha.1.24628.1

2025-01-03 19:41 UTC, ricardobossan commented
I proceeded to test the PR and the issue seems to have been solved:

![image](https://github.com/user-attachments/assets/3439dc6d-5921-4a33-ada2-50d4873d8ba5)

The code LGTM!

2025-01-07 00:27 UTC, Tanya-Solyanik reviewed
Had you tested this change at different scaling factors and in different level nodes in a tree view? For example 3rd level child? 
It will be helpful to add code comments that describe what the constants are for.

2025-01-07 00:27 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +                            int invertedX = Width - 2 - bounds.X - textSize.Width;
What is the `-2` here? Should it be scaled for the DPI?

2025-01-07 10:26 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +                            int invertedX = Width - 2 - bounds.X - textSize.Width;
Considering that the control has a border, to ensure that the rectangle does not cling to the edge of the control

2025-01-07 10:28 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
> -                        Point textLoc = new(bounds.X - 1, bounds.Y); // required to center the text
My test results are currently good, but this may require further testing by the Olina team

2025-01-07 19:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +                            int invertedX = Width - 2 - bounds.X - textSize.Width;
If this looks good on different DPI and is only needed to emphasize the border, then we don't have to scale it. But add a comment to the code.

2025-01-27 04:43 UTC, LeafShi1 commented
No regressions found in private PRs

2025-01-28 03:39 UTC, Tanya-Solyanik commented
@LeafShi1  - even though "issue5" as reported by Olina, is not a regression from the previous release, it is a regression from .NET Framework, could you please investigate it?

2025-03-04 09:58 UTC, LeafShi1 commented
The issue5: The right border of the node's checkbox is not visible in the edit mode of the node  
<img width="155" alt="image" src="https://github.com/user-attachments/assets/853b16d5-c461-4a66-8325-d4bd268f3991" />

This issue repro in MFC app and not repro in .NET Framework project:

2025-03-06 08:34 UTC, LeafShi1 commented
> @LeafShi1 - even though "issue5" as reported by Olina, is not a regression from the previous release, it is a regression from .NET Framework, could you please investigate it?

I didn't find any method to redraw the EditTextBox position in the .NetFramework code

Since this problem has nothing to do with `TreeViewDrawMode.OwnerDrawText`, but for all drawing modes, can we solve it in a separate issue?

2025-03-07 03:17 UTC, LeafShi1 commented on src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +                    PInvoke.SetWindowPos((HWND)editHandle,
Reposition the edit text box to fix the issue `The right border of the node's checkbox is not visible in the edit mode of the node`

<img width="122" alt="image" src="https://github.com/user-attachments/assets/32d0a8ee-bf6d-4edb-83ea-33c02f41c46b" />

2025-03-10 07:08 UTC, Epica3055 commented on src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +            {
Maybe it's better to add a comment explaining why we need `BeginInvoke`

2025-03-10 07:52 UTC, LeafShi1 commented on src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +                        goto default;
To solve the following problem, hide the item text in edit mode

![image](https://github.com/user-attachments/assets/27323283-0bd5-4b1d-a932-b79970504628)

2025-03-12 21:07 UTC, JeremyKuhne requested changes
Added a few comments

2025-03-12 21:07 UTC, JeremyKuhne commented on src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +    private int PreferredHeight
There are no comments here. This is a very expensive call as it will send messages for the node and all children. As such it should not be a property. As there is only one caller, consider moving this inside the calling method. Additionally, the recursive sub-method should be nested.

2025-03-12 21:07 UTC, JeremyKuhne commented on src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +        int height = ItemHeight;
`ItemHeight` should never change, why call it every time? It looks like you're actually calculating `ExpandedNodeCount` * `ItemHeight`.

2025-03-13 02:37 UTC, LeafShi1 commented on src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +            BeginInvoke((MethodInvoker)(() =>
> When would this be happening on anything but the UI thread? What exactly are we waiting for with "fully initialized"? What has to happen before we do this?

This is just a comment on BeginInvoke((MethodInvoker)), but Windows Forms controls cannot be called across threads, so the comment on cross-thread calls seems redundant.

I tried calling `PInvoke.SetWindowPos` directly here, and although it was executed, it had no effect, so I added `BeginInvoke((MethodInvoker))` here to ensure that all properties and states of the `EditControl` have been set and layout completed before performing the repositioning.

2025-03-13 02:49 UTC, LeafShi1 commented on src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +                        e.Node.Bounds.Height + 2,
> Why are we not scaling the height?

`e.Node.Bounds.Height` is already scaled according to DPI, +2 just adds the top and bottom borders to the original height of Node.

2025-04-16 00:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs
> +            BeginInvoke((MethodInvoker)(() =>
Maybe you should pump messages after setting windows position? Application.DoEvents. But this change seems to be too complicated and risky, I suggest gropping it and re-visiting this bug if reported by customers.

2025-04-16 01:16 UTC, Tanya-Solyanik commented
@LeafShi1  - I'll close this PR, the issue is too edge-case and the solution is getting too complicated.

2025-04-16 01:16 UTC, closed without merging