WIP: Fixing issue 2704: Cannot find the RichEdit control of the "Text" property in UIA structure of a PropertyGrid control
dotnet/winforms pull request #3014
Opened 2020-03-26 08:28 UTC by M-Lipin

Adding PropertyGrid DropDown control holder and its child edit control to the UIA hierarchy of the PropertyGrid.

Fixes #2704 

## Proposed changes

- Adding accessible object for PropertyGrid's DropDownControlHolder;
- Implementing accessible navigation to find DropDownControlHolder pane and its child edit control in UIA hierarchy in PropertyGrid.
- Adding resource to announce DropDownControlHolder pane accessible name to inform users that the currently edited RichEdit control or another edit control is hosted in PropertyGrid's DropDown control holder.

## Customer Impact

- Customers will be able to distinguish the dropped down control from another form controls if using Narrator or another screen reader.

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before

![image](https://user-images.githubusercontent.com/23213980/73003863-605b7d80-3e17-11ea-92af-f66d92fec2a1.png)

### After

![image](https://user-images.githubusercontent.com/23213980/73004026-ae708100-3e17-11ea-845d-448e48585d7d.png)

## Test methodology 

- Manual testing;
- Unit tests (to be implemented);
- UI tests.

## Accessibility testing  

 

## Test environment(s) 

.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-alpha1-015763
 Commit:    0d0c902b77

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-alpha1-015763\

2020-03-26 09:40 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            PropertyGrid propertyGrid = new PropertyGrid();
```suggestion
            using PropertyGrid propertyGrid = new PropertyGrid();
```

2020-03-26 09:41 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            TestPropertyGridView testPropertyGridView = new TestPropertyGridView(null, null);
if these are disposable, they must be used with `using`

2020-03-26 14:36 UTC, M-Lipin commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            PropertyGrid propertyGrid = new PropertyGrid();
Fixed, thanks!

2020-03-26 14:38 UTC, M-Lipin commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            TestPropertyGridView testPropertyGridView = new TestPropertyGridView(null, null);
Fixed this. Thanks!

2020-03-30 02:01 UTC, RussKie commented
Please ensure we don't end up with NREs:

```
    System.Windows.Forms.PropertyGridInternal.Tests.PropertyDescriptorGridEntryAccessibleObjectTests.PropertyDescriptorGridEntryAccessibleObject_Navigates_to_DropDownControlHolder [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs(6248,0): at System.Windows.Forms.PropertyGridInternal.PropertyGridView.DropDownHolder.get_CreateParams()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs(4939,0): at System.Windows.Forms.Control.CreateHandle()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs(3136,0): at System.Windows.Forms.Form.CreateHandle()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs(2464,0): at System.Windows.Forms.Control.get_Handle()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs(32,0): at System.Windows.Forms.Control.ControlAccessibleObject..ctor(Control ownerControl)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs(6207,0): at System.Windows.Forms.PropertyGridInternal.PropertyGridView.DropDownHolder.DropDownHolderAccessibleObject..ctor(DropDownHolder dropDownHolder)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs(6198,0): at System.Windows.Forms.PropertyGridInternal.PropertyGridView.DropDownHolder.CreateAccessibilityInstance()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs(498,0): at System.Windows.Forms.Control.get_AccessibilityObject()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs(1193,0): at System.Windows.Forms.PropertyGridInternal.PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.GetFirstChild()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs(1157,0): at System.Windows.Forms.PropertyGridInternal.PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.FragmentNavigate(NavigateDirection direction)
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs(41,0): at System.Windows.Forms.PropertyGridInternal.Tests.PropertyDescriptorGridEntryAccessibleObjectTests.PropertyDescriptorGridEntryAccessibleObject_Navigates_to_DropDownControlHolder()
 ````

2020-03-31 01:32 UTC, RussKie commented
The builds are still failing

2020-04-06 02:52 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
> +            internal class DropDownHolderAccessibleObject : ControlAccessibleObject
Move it out to own file

2020-04-06 02:52 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
> +                DropDownHolder _dropDownHolder;
Missing accessors
```suggestion
                private readonly DropDownHolder _dropDownHolder;
```

2020-04-06 02:54 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +        internal class TestPropertyGridView : PropertyGridView
```suggestion
        private class TestPropertyGridView : PropertyGridView
```

2020-04-08 20:00 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
> +            internal class DropDownHolderAccessibleObject : ControlAccessibleObject
Fixed this. Thanks! Maybe we also need to move DropDownHolder class to a separate file in an additional refactoring bug/task/PR.

2020-04-08 20:00 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
> +                DropDownHolder _dropDownHolder;
Fixed this. Thanks!

2020-04-08 20:01 UTC, M-Lipin commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +        internal class TestPropertyGridView : PropertyGridView
Fixed this. Thanks!

2020-04-09 07:55 UTC, M-Lipin commented
After QA verification there are 2 errors when get information about some drop-down list controls, but I did not manage to reproduce it. Have sent some questions to QA to investigate these cases.

2020-04-17 19:52 UTC, M-Lipin commented
Prepared the fix for the issue found while private testing. At this moment waiting for test results.

2020-04-20 06:29 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
> +
Can we add a test for this?

2020-04-20 06:29 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObject.cs
> +            internal class DropDownHolderAccessibleObject : ControlAccessibleObject
Tests?

2020-04-20 06:30 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
> +        internal partial class DropDownHolder : Form, IMouseHookClient
Tests?

2020-04-22 18:03 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
> +
Thanks, I have covered it in PropertyDescriptorGridEntryAccessibleObject_Navigates_to_DropDownControlHolder test.

2020-04-22 18:07 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObject.cs
> +            internal class DropDownHolderAccessibleObject : ControlAccessibleObject
Added the initial test for this as a template to begin work on covering DropDownHolder by unit tests. It seems to me that we should do this in a separate task as DropDownHolder itself is not affected in the fix (except changing class definition access modifier).

2020-04-22 18:08 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObject.cs
> +            internal class DropDownHolderAccessibleObject : ControlAccessibleObject
DropDownHolderAccessibleObject implementation is covered by tests.

2020-04-22 18:08 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
> +        internal partial class DropDownHolder : Form, IMouseHookClient
Can we do this in a separate task?

2020-04-24 13:14 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
> +        internal partial class DropDownHolder : Form, IMouseHookClient
As DropDownHolder does not have the changes in the implementation in the current PR, moved this to a separate task: #3136

2020-04-24 13:15 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
> +
Added more tests to cover all navigation cases for DropDownHolder.

2020-04-24 20:04 UTC, M-Lipin commented
Reworked commit PR history. Moved Accessibility changes related to PropertyGrid ListBox control to #3137 and is tracked in issue #3124.

2020-04-27 05:06 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObject.cs
> +                    }
Doesn't `base(dropDownHolder)` throw if `dropDownHolder == null`? So this check if redundant. We just need to have a test to verify an exception gets thrown.

2020-04-27 05:08 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
> +            }
[nit] please keep methods after properties

2020-04-27 05:09 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> -            }
Why?

2020-04-27 05:12 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
> +            PropertyGridView propertyGridView = gridViewField.GetValue(propertyGrid) as PropertyGridView;
We're writing a lot of duplicated code... Which repeated many times will turn into a maintenance overhead.
Please have a look at @JeremyKuhne's proposal to interact with types via reflection: https://gist.github.com/JeremyKuhne/e8c9c33d037ac5e5ed4c477817cae414

2020-04-27 18:46 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
> +            PropertyGridView propertyGridView = gridViewField.GetValue(propertyGrid) as PropertyGridView;
I'll look at getting that in so it doesn't drop off the end of the earth.

2020-04-28 11:52 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObject.cs
> +                    }
Yes, thanks! Fixed it.

2020-04-28 11:54 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
> +            }
Fixed it, thanks!

2020-04-28 11:58 UTC, M-Lipin commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> -            }
This is to use it in multiple test files. But at this moment have copied the similar one to another test file to avoid such confusion.

2020-04-28 20:41 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObject.cs
> +                    }
Yes, thank you for this point.

2020-04-28 20:42 UTC, M-Lipin commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
> +            }
Thanks, moved method lower under properties.

2020-04-28 20:44 UTC, M-Lipin commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> -            }
Did this to share `TestDropDownHolder` for multiple test files. But this is not clear, so added `TestDropDownHolder` to two files and fixed access modifiers.

2020-04-28 20:45 UTC, M-Lipin commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
> +            PropertyGridView propertyGridView = gridViewField.GetValue(propertyGrid) as PropertyGridView;
Thank you for this point. I've added the similar accessor class and reworked dependent WinFormsFacts.

2020-04-28 20:51 UTC, M-Lipin commented
Put the test request on hold and waiting for #3137 to be merged to fix accessibility issues. Then will proceed with final test request to ensure there is no regression.

2020-04-30 02:12 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
> +            PropertyGridView propertyGridView = gridViewField.GetValue(propertyGrid) as PropertyGridView;
You're going to hate me but I will be asking you to rewrite reflection-based tests again shortly.

@JeremyKuhne has implemented a new testing infra that allows simple access to non-public API (including statics), which will be landing shortly. His work for the most part will obsolete a lot of plumbing you have written in these tests. 
This is a fresh news.

2020-07-14 05:16 UTC, RussKie commented
@Ryuugamine this branch needs to be rebased on top of the latest as it contains very old changes, some of which are no longer relevant.

2020-08-06 14:05 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
> +
It seems there is an extra blank line. Please check if so

2020-08-06 14:10 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            var firstChild = gridEntry.AccessibilityObject.FragmentNavigate(Interop.UiaCore.NavigateDirection.FirstChild);
Please explicit **var**s everywhere in your tests

2020-08-06 14:19 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            PropertyGridView propertyGridView = gridViewField.GetValue(propertyGrid) as PropertyGridView;
- We already have TestAccessor for these cases. So please use it everywhere in your tests for non-pablic members.
- Use type cast instead of using **as** operator to avoid getting NRE in the next. Use it for such places everywhere in your tests.
```suggestion
            PropertyGridView propertyGridView = (PropertyGridView)propertyGrid.TestAccessor().Dynamic._gridView;
```

2020-08-06 14:25 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/TestUtilities/Accessor.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
We already have TestAccessor() to get non-public values in unit tests. So just remove this file

2020-08-06 14:28 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
> +            using var propertyGridView = propertyGrid.GetFieldValue("_gridView") as PropertyGridView;
- Please use exist using var propertyGridView = (PropertyGridView)TestAccessor().Dynamic._gridView for this
- Please use type cast instead using **as** operator

Please make these for all tests and files that you added

2020-08-21 04:01 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +        }
This makes no sense, you return `_propertyGridView` which is set via .ctor, but set the base property

2020-08-21 04:02 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +                }
Why are you creating an new instance of the collection every time it is being accessed?

2020-08-21 04:03 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            internal override Control ParentInternal
Why do we need the override?

2020-08-21 04:05 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            public Font FontProperty
Can we use a lighter object (`Font` is quite heavy)? Or better yet a struct?

2020-08-21 04:06 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            using Form form = new Form();
Why do we need the form in this test?

2020-08-21 04:07 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
> +            using Form form = new Form();
Why do we need the form for the test? 
Ditto below

2020-08-21 04:08 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
> +            using PropertyGridView propertyGridView = (PropertyGridView)propertyGrid.TestAccessor().Dynamic._gridView;
Why is this being disposed? It belongs to `PropertyGrid`.
Ditto below

2020-08-24 11:05 UTC, Ryuugamine commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
> +            internal override Control ParentInternal
We need it because in Control class implementation setter looks like value.Controls.Add(this). But we need to set _parent property instead of use given parent object to add current control as child for it.

2020-08-27 00:36 UTC, RussKie requested changes

2020-08-27 00:36 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewListBoxTests.cs
> +            PropertyGridView.GridViewListBox gridViewListBox = new PropertyGridView.GridViewListBox(propertyGridView);
```suggestion
            using PropertyGridView.GridViewListBox gridViewListBox = new PropertyGridView.GridViewListBox(propertyGridView);
```

2020-08-27 00:36 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridViewTests.cs
> +            using Form form = new Form();
Why do we need the form here?

2020-08-27 00:36 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
> +            PropertyGridView propertyGridView = (PropertyGridView)propertyGrid.TestAccessor().Dynamic._gridView;
We now have `PropertyGridTestAccessor`, and we have tests that show how to use it, e.g.  `PropertyDescriptorGridEntryAccessibleObject_ExpandCollapseState_reflects_ExpandablePropertyState`
```suggestion
            PropertyGridView propertyGridView = propertyGrid.TestAccessor().GridView;
```

The same applies everywhere else

2020-08-27 00:36 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
> +            PropertyGridView.DropDownHolder dropDownHolderControl = new PropertyGridView.DropDownHolder(propertyGridView);
As per our discussion, anything that is new'ed up must be disposed of

The same applies everywhere else

2020-08-27 00:36 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolderTests.cs
> +            using Form form = new Form();
Why do we need the form here? And the same below

2020-08-28 04:53 UTC, RussKie commented
There are still 2 outstanding issues that needs resolution

2020-09-07 08:36 UTC, SergeySmirnov-Akvelon commented
CTI approved

2020-09-08 01:01 UTC, RussKie commented
/azp run

2020-09-08 02:25 UTC, RussKie approved these changes

2020-09-08 02:25 UTC, merged