Update build instructions
dotnet/winforms pull request #3746
Opened 2020-08-20 05:27 UTC by RussKie

2020-08-20 08:41 UTC, Olina-Zhang requested changes

2020-08-20 08:41 UTC, Olina-Zhang commented on docs/building.md
> +    winforms> pushd .\src\System.Windows.Forms\tests\AccessibilityTests>
Remove right angle bracket, it should be **winforms> pushd .\src\System.Windows.Forms\tests\AccessibilityTests**

2020-08-20 09:05 UTC, Olina-Zhang commented on docs/building.md
> +  * you can do this in VS at Tools :arrow_right: options :arrow_right: Projects and Solutions :arrow_right: .net core :arrow_right: use previews
This option is moved to Tools->Options->Environment->Preview Features->Use previews of the .Net Core SDK (Requires restart)

2020-08-20 10:23 UTC, hughbe commented on docs/building.md
> +1. Run `.\start-code.cmd` from the repository root. This will prepend the repo-local .NET SDK to the path, and open `Winforms.sln` in Visual Studio.
nit: numbering

2020-08-20 10:24 UTC, hughbe commented on docs/building.md
> +1. Run `.\start-code.cmd` from the repository root. This will prepend the repo-local .NET SDK to the path, and open `Winforms.sln` in Visual Studio.
nit: Visual Studio Code, not Visual Studio

2020-08-20 10:24 UTC, hughbe commented on docs/building.md
> +    ```
nit:indent?

2020-08-21 02:06 UTC, RussKie commented on docs/building.md
> +1. Run `.\start-code.cmd` from the repository root. This will prepend the repo-local .NET SDK to the path, and open `Winforms.sln` in Visual Studio.
Thank you, but MD is smart enough to automatically increment numbering.

2020-08-21 02:08 UTC, RussKie commented on docs/building.md
> +    ```
It is correct, I want it indented.


Unindented it would look like this:
![image](https://user-images.githubusercontent.com/4403806/90844306-f56f2680-e3a6-11ea-8c5a-26b90eadcff4.png)

2020-08-21 02:26 UTC, merged