Fixing issue with read the state of the CheckBox as checked/unchecked after selection in DataGridViewCheckBoxColumn by Narrator
dotnet/winforms pull request #3749
Opened 2020-08-20 10:04 UTC by SergeySmirnov-Akvelon

Fixes #3597

## Proposed changes
- Added logic for reading of state of the CheckBox by Narrator when user changes state of checkbox in DataGridViewCheckBoxColumn

## Customer Impact
- No

## Regression? 

- No

## Risk
- Minimal

## Test methodology 
- Unit tests 
- CTI

## Test environment(s) 
- Microsoft Windows [Version 10.0.18363.900]
- NET Core 5.0.100-rc.1.20411.10

2020-08-20 18:11 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/Resources/SR.resx
> +  <!--
Please remove the comment block.

2020-08-20 18:11 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/Resources/SR.resx
> -    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
Please revert the version numbers to 4.0.0.0.

2020-08-20 18:12 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +                                    Automation.AutomationNotificationKind.Other,
Arguments should only be indented once.

2020-08-20 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +                    //RaiseCellClick(new DataGridViewCellEventArgs(ColumnIndex, rowIndex));
Why is this commented out?

2020-08-20 18:29 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
> +            Assert.Equal(1, cellAccessibilityObject.RaiseAutomationNotificationCallCount);
Why aren't you checking that you're getting the right arguments?

2020-08-20 18:41 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
> +        public virtual bool RaiseAutomationNotification(AutomationNotificationKind notificationKind, AutomationNotificationProcessing notificationProcessing, string notificationText)
You cannot do this- this is a public API. You can add an `internal virtual bool InternalRaiseAutomationNotification()` that calls the public one if you want to test the behavior. Additionally I would have the internal one conditionalize on there being active listeners so we can avoid unnecessary overhead when there are no automation clients active (like the other methods do).

``` C#
internal virtual bool RaiseAutomationNotification(AutomationNotificationKind notificationKind, AutomationNotificationProcessing notificationProcessing, string notificationText)
{
    if (UiaCore.UiaClientsAreListening().IsTrue())
    {
        return RaiseAutomationNotification(notifcationKind, notificationProcessing, notificationText);
    }

    return notificationEventAvailable;
}
```

2020-08-24 12:47 UTC, RussKie approved these changes

2020-08-25 10:40 UTC, SergeySmirnov-Akvelon commented
CTI approved

2020-08-25 12:21 UTC, RussKie approved these changes

2020-08-25 21:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +            AccessibilityObject?.InternalRaiseAutomationNotification(
UIA Notifications are designed to handle a different scenario. The main use case is to announce that file download is complete, it alerts the user to an event that is not related to the currently focused control. UIA clients can disable notifications based on their kind. And notifications do not affect state of the UIA client because they don't raise  appropriate events. 
Problems:
* We don't want to announce check box state change when user is mousing over some some other piece of UI
* Please test what is announced in the narrator scan mode - notifications are not changing UIA client state, I don't expect scan mode to reflect state correctly
* MSAA state is not updated, sure this is not part of our commitment, but right now  it is mainstream for winforms

The same comment applies to other PRs.

Sample code:
https://github.com/dotnet/winforms/blob/77647c9af043171fa92e279fb46604d4b6b7712b/src/System.Windows.Forms/src/System/Windows/Forms/Button.cs#L244-L262

2020-08-26 14:20 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +            AccessibilityObject?.InternalRaiseAutomationNotification(
Thank you, @Tanya-Solyanik. I found that we call the MSAA events for `onMouseUp` , `onKeyUp` and `DoDefaultAction` methods. I added calls of UIA events to these places instead of the call in `NotifyDataGridViewOfValueChange` method.

2020-08-31 07:45 UTC, RussKie requested changes

2020-08-31 07:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.cs
>                              // notify MSAA clients that the default action changed
The comment is no longer accurate, please remove

2020-08-31 07:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +            bool ret = false;
What's a `ret`?

2020-08-31 07:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +            AccessibilityObject?.InternalRaiseAutomationNotification(
Why execute all the above if we don't have a valid `AccessibilityObject`?
The same goes for `NotifyMSAAClient`

2020-08-31 08:49 UTC, vladimir-krestov approved these changes
Good work!

2020-08-31 08:49 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/Resources/SR.resx
> +  </data>
Think about `DataGridViewCheckBoxCellUncheckedStateDescription`
- Without `_` to be consistent with the rest
- Add `StateDescription` for more informativeness what is the resource

2020-08-31 08:49 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +
@RussKie, may it have a negative customer impact due to it is a public method?

2020-08-31 08:49 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
> +            public void OnMouseUpInternal() => base.OnMouseUpInternal(new DataGridViewCellMouseEventArgs(0, 0, 10, 10, new MouseEventArgs (MouseButtons.Left, 1, 10, 10, 0)));
I would prefer to move the specific parameters into the test where it is used because this sub-method may be used with other arguments in the future in other new unit tests

2020-08-31 08:49 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
> +            public void OnKeyUp() => base.OnKeyUp(new KeyEventArgs(Keys.Space), 0);
ditto

2020-08-31 08:49 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +                    : string.Format(SR.DataGridViewCheckBoxCell_Unchecked, AccessibilityObject.Name));
May `AccessibilityObject.Name` be null here?

2020-08-31 09:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +
We're doing exactly the same in https://github.com/dotnet/winforms/pull/3432. We're sending a message which requires a valid handle. Forcefully creating a handle has a higher chance of negatively affecting customers.

2020-08-31 10:38 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +            AccessibilityObject?.InternalRaiseAutomationNotification(
I will remove this condition because AccessibleObject always exists

2020-08-31 10:49 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +            bool ret = false;
Fixed name of variable.

2020-08-31 10:51 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +                    : string.Format(SR.DataGridViewCheckBoxCell_Unchecked, AccessibilityObject.Name));
Thank you. I added default value for case when `AccessibilityObject.Name` is null.

2020-08-31 11:02 UTC, RussKie approved these changes

2020-08-31 22:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>{0} check box checked</value>
The first argument could be string.Empty. I would add single quotes around the placeholder for the first argument to indicate that there is a name.

2020-08-31 23:03 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
> +                checkboxBoolValue
personally, I would add a local variable for description and would initialize it outside the function parameters list, to make code less dense.

2020-08-31 23:35 UTC, Pilchie commented
Approved for RC1 if merged before 10am Pacific on 2020-09-01.

2020-09-01 10:27 UTC, RussKie approved these changes

2020-09-01 10:42 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>{0} check box checked</value>
Hi @Tanya-Solyanik. After adding of single quote, testers found that single quote is displayed as '&apos;' in Narrator. We suppose that Accessible.Name should always return not-null value.  If Accessible.Name is null then this means that something went wrong and the control does not work correctly

2020-09-01 10:59 UTC, merged

2020-09-09 10:00 UTC, SergeySmirnov-Akvelon commented
Fix has been ported to [master branch](https://github.com/dotnet/winforms/commit/54d95fe3a72b587bbc91698c3c0a9d822a5a44ac)