Restore original RichTextBox.Text EoL
dotnet/winforms pull request #3821
Opened 2020-09-02 07:42 UTC by RussKie

Fixes #3778

## Proposed changes

The default behaviour of EM_GETTEXTEX is to normalise line endings to '\r' (see: GT_DEFAULT, https://docs.microsoft.com/en-au/windows/win32/api/richedit/ns-richedit-gettextex#members),
whereas previously we would normalise to '\n'.
Setting GT.USECRLF flag we can only ask for '\r\n' line endings, but unable to ask for '\n'.

Unless GT.USECRLF was set, convert '\r' with '\n' to retain the original behaviour.

## Customer Impact

- The original behaviour from .NET Framework/.NET Core is retained

## Regression? 

- Yes, introduced in https://github.com/dotnet/winforms/pull/3726

## Risk

- Minimum

## Test methodology 

- Locally reverted https://github.com/dotnet/winforms/pull/3726
- Added unit tests to capture the original behaviour
- Restored https://github.com/dotnet/winforms/pull/3726
- Added the new fix to adhere to the original behaviour and see the tests pass

2020-09-02 21:18 UTC, JeremyKuhne requested changes
I think we could use some more test cases here, particularly to get better coverage over the initial change that introduced this problem. I think the risk for the initial change isn't low, but thorough tests would ease my mind a bit.

2020-09-02 21:18 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
> +                    while (index < actualLength)
We should consider doing a more efficient replace in the future, say with Span<char>.IndexOf perhaps.

2020-09-02 23:14 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +        [InlineData("\ud83c\udf09", "\ud83c\udf09")]
It is a surrogate pair, https://charbase.com/1f309-unicode-bridge-at-night

Item | Value 
--- | ----
Your Browser | 🌉
Index | U+1F309 (127753)
Class | Other Symbol (So)
Block | Miscellaneous Symbols And Pictographs
Java Escape | "\ud83c\udf09"
Javascript Escape | "\ud83c\udf09"
Python Escape | u'\U0001f309'
HTML Escapes | \&#127753; \&#x1f309;
URL Encoded | q=%F0%9F%8C%89
UTF8 | f0 9f 8c 89
UTF16 | d83c df09

2020-09-02 23:17 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +        [InlineData(null, "")]
I written and executed tests _after_ rolling back #3726, so essentially against our original implementations. Then I re-applied all the new changes, and verified the result remained expected.

2020-09-02 23:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
> +                    while (index < actualLength)
By using `Span.IndexOf` we'd be scanning the array twice though, whereas now we're scanning the array once.

2020-09-02 23:51 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +        [InlineData("\ud83c\udf09", "\ud83c\udf09")]
A comment would be good. :)

2020-09-02 23:51 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +        [InlineData(null, "")]
That's good, but we want to make sure we understand the behavior against the old version of RichEdit as well.

2020-09-04 02:48 UTC, RussKie commented
Added few more tests 😊
![image](https://user-images.githubusercontent.com/4403806/92193967-e7dc9500-eeac-11ea-9cb4-8a46e0645b58.png)

2020-09-04 02:55 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
> +                    while (index < actualLength)
As discussed offline this optimisation is out of scope of this PR.

2020-09-04 05:17 UTC, RussKie commented
Feels like `RichEditWithVersion` is crashing the process under stress -> [dmp](https://dev.azure.com/dnceng/_apis/resources/Containers/5004674/Windows_NT_Windows%20Debug?itemPath=Windows_NT_Windows%20Debug%2Fdotnet.exe.1028.dmp)

![image](https://user-images.githubusercontent.com/4403806/92202181-c0dc8e00-eec1-11ea-9ebe-e2e783c1c085.png)


```
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DefWndProc(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 515	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.DefWndProc(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 5040	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 13032	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.TextBoxBase.WndProc(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 2204	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.RichTextBox.WndProc(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 3725	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 67	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 119	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.Callback(System.IntPtr hWnd = 0x00000000004105c6, Interop.User32.WM msg = NCCREATE, System.IntPtr wparam = 0x0000000000000000, System.IntPtr lparam = 0x00000022b7dbca90) Line 372	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.WindowClass.Callback(System.IntPtr hWnd = 0x00000000004105c6, Interop.User32.WM msg = NCCREATE, System.IntPtr wparam = 0x0000000000000000, System.IntPtr lparam = 0x00000022b7dbca90) Line 55	C#	Symbols loaded.
 	[Native to Managed Transition]		Annotated Frame
 	[Managed to Native Transition]		Annotated Frame
 	System.Windows.Forms.Primitives.dll!Interop.User32.CreateWindowExW(Interop.User32.WS_EX dwExStyle = CLIENTEDGE, string lpClassName = "WindowsForms10.RichEdit20W.app.0.37a9c05_r3_ad1", string lpWindowName = null, Interop.User32.WS dwStyle = 1445003332, int X = 0, int Y = 0, int nWidth = 100, int nHeight = 96, System.IntPtr hWndParent = 0x00000000009a0626, System.IntPtr hMenu = 0x0000000000000000, System.IntPtr hInst = 0x00007ff7a1910000, object lpParam = null) Line 43	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams cp = {System.Windows.Forms.CreateParams}) Line 460	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.CreateHandle() Line 4934	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.TextBoxBase.CreateHandle() Line 1374	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.CreateControl(bool fIgnoreVisible = false) Line 4998	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.CreateControl() Line 4960	C#	Symbols loaded.
>	System.Windows.Forms.Tests.dll!System.Windows.Forms.Tests.RichTextBoxTests.RichTextBox_Text_GetWithHandle_ReturnsExpected(string text = "abc", string expectedText = "abc", string oldWayExpectedText = "abc", string oldControlExpectedText = "abc") Line 6909	C#	Symbols loaded.
```

2020-09-04 07:46 UTC, RussKie commented
I converted the theory into a single test to reduce the UI stress - create two controls and run 1.5K test cases instead of repeatedly creating these controls 1.5K times. This seems to have pleased the CI gods, but certainly made the test more complicated and harder to maintain.

2020-09-08 23:00 UTC, RussKie commented
CTI approved

2020-09-08 23:11 UTC, JeremyKuhne approved these changes

2020-09-09 02:17 UTC, merged