Empty string check optimization
dotnet/winforms pull request #3826
Opened 2020-09-02 21:28 UTC by Youssef1313

See https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1820?view=vs-2019

2020-09-02 21:29 UTC, Youssef1313 commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs
> +            if (secondRowLabel.Text.Length == 0)
:warning: :warning: Can the `Text` property be null in any case? If it can be null, then my change can null reference exception :warning: :warning:

2020-09-04 07:40 UTC, RussKie requested changes

2020-09-04 07:40 UTC, RussKie commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs
> +            if (secondRowLabel.Text.Length == 0)
We should never make any assumptions about return values, especially without completed NRT annotations. If anything we should use `string.IsNullOrEmpty()` or `string.IsNullOrWhiteSpace()` methods, where appropriate.
Also changes should be accompanied by tests to reduce risks of regressions.

The same applies below.

2020-09-04 10:27 UTC, Youssef1313 commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs
> +            if (secondRowLabel.Text.Length == 0)
@RussKie I gave this method a quick look, and the `Text` can never be null.

The following line will always execute (it's outside any conditions):

https://github.com/dotnet/winforms/blob/b02c87ecb521839f1d73b91fc0fcb4f2f954e7c8/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs#L264

Then, the **only** changes that can happen to `Text` property are values that come from resources, which are obviously non-null values. I believe it's safe to access the Length property.

Regarding the tests, I'm unsure how these small changes can be tested?
They are pretty straight-forward with no any semantic changes.

2020-09-08 02:54 UTC, RussKie commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs
> +            if (secondRowLabel.Text.Length == 0)
Righto! In this case it is worth updating line:264 to `secondRowLabel.Text = string.Empty;`
And then collapse line:318-325 to `secondRowLabel.Visible = secondRowLabel.Text.Length == 0;`

2020-09-08 08:50 UTC, Youssef1313 commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs
> +            if (secondRowLabel.Text.Length == 0)
@RussKie `secondRowLabel.Visible = secondRowLabel.Text.Length == 0;` you probably meant `>` not `==`?

2020-09-09 00:52 UTC, RussKie approved these changes

2020-09-09 00:52 UTC, RussKie commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs
> +            if (secondRowLabel.Text.Length == 0)
Aye, indeed :)

2020-09-09 00:53 UTC, merged

2020-09-09 00:53 UTC, RussKie commented
Thank you