Adding Text pattern to ToolStripTextBox
dotnet/winforms pull request #3865
Opened 2020-09-09 12:48 UTC by vladimir-krestov

Fixes #3860
Orginal Bug: [1155254](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1155254)
Based on PR #2701

## Proposed changes

- Enable **Text pattern** support for `ToolStripTextBoxControlAccessibleObject`

## Customer Impact

- Visually impaired users will be able to read and interact with the text content of a ToolStripTextBox

## Regression? 

- No

## Risk

- Minimal

### Before

- Narrator does not announce the text navigation and selection of a ToolStripTextBox

### After

- Narrator announces the text content of a ToolStripTextBoxs (navigation, selection)

## Test methodology 

- Manual testing
- CTI
- Unit tests

## Accessibility testing  
- Using Narrator and Inspect
   
     

## Test environment(s) 

- .Net 5.0 Version: 5.0.0-rc.1.20431.5
- Microsoft Windows [Version 10.0.19041.450]

2020-09-10 04:05 UTC, RussKie commented
/azp run

2020-09-11 08:24 UTC, vladimir-krestov commented
Testers approved the fix ✔️ 
There are 2 known issues that will be fixed as a separate fix for DataGridViewTextBoxCell and PropertyGridView Edit too: 
- [#2794](https://github.com/dotnet/winforms/issues/2794): Narrator doesn't announce a text mouse selection (a keyboard selection works well) 
- Narrator doesn't show the blue rectangle around an added character when typing

But the main Issue #3860 was fixed

2020-09-14 11:02 UTC, RussKie requested changes

2020-09-14 11:02 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControlAccessibleObject.cs
> +                _owningTextBoxBase = toolStripHostedControl;
Test for `toolStripHostedControl is null`?

2020-09-14 11:02 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControlAccessibleObject.cs
> +            public ToolStripTextBoxControlAccessibleObject(TextBox toolStripHostedControl, ToolStripControlHost? toolStripControlHost) : base(toolStripHostedControl, toolStripControlHost)
❗ `ToolStripHostedControlAccessibleObject` must be NRT annotated before any of its descendants (i.e. `ToolStripTextBoxControlAccessibleObject`) can be annotated.

2020-09-14 20:14 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControlAccessibleObject.cs
> +            public ToolStripTextBoxControlAccessibleObject(TextBox toolStripHostedControl, ToolStripControlHost? toolStripControlHost) : base(toolStripHostedControl, toolStripControlHost)
Annotated NRT for `ToolStripHostedControlAccessibleObject`. 
I checked - related types: `ToolStripNumericUpDownAccessibleObject` and `ToolStripTextBoxControlAccessibleObject`

2020-09-15 05:27 UTC, vladimir-krestov commented
@JeremyKuhne, I fixed your #3853 review points here for .Net 5.0. Could you please check if I made this correctly?

2020-09-18 04:47 UTC, JeremyKuhne commented
Handling of handles looks much better.

2020-09-18 05:52 UTC, RussKie approved these changes

2020-09-21 03:28 UTC, RussKie approved these changes

2020-09-21 03:28 UTC, merged