Adding Text pattern to DataGridViewTextBoxCell
dotnet/winforms pull request #3866
Opened 2020-09-09 14:25 UTC by vladimir-krestov

Fixes #3658 
Original Bug: [1159872](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1159872)
Based on PR #2701

## Proposed changes

- Enable **Text pattern** support for `DataGridViewTextBoxEditingControlAccessibleObject`

## Customer Impact
- Visually impaired users will be able to read and interact with the text content of a DataGridViewTextBoxCell

## Regression? 

- No

## Risk

- Mininmal

### Before
- Narrator does not announce the text navigation and selection of a DataGridViewTextBoxCell

### After
- Narrator announces the text content of a DataGridViewTextBoxCell (navigation, selection)

## Test methodology 

- Manual testing
- CTI
- Unit tests

## Accessibility testing  
- Using Narrator and Inspect

 

## Test environment(s) 

- .Net 5.0 Version: 5.0.0-rc.1.20431.5
- Microsoft Windows [Version 10.0.19041.450]

2020-09-10 05:19 UTC, RussKie commented
/azp run

2020-09-14 05:14 UTC, RussKie requested changes
Please rebase

2020-09-14 10:53 UTC, RussKie requested changes
LGTM module the feedback.

2020-09-14 10:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs
> +                _owningDataGridViewTextBoxEditingControl = ownerControl;
Test for `ownerControl is null`?

2020-09-16 09:41 UTC, vladimir-krestov commented
Testers approved the fix ✔️
There are 2 known issues that will be fixed as a separate fix for PropertyGrid edit and ToolStripTextBox too:
- #2794: Narrator doesn't announce a text mouse selection (a keyboard selection works well)
- #3897: Narrator doesn't show the blue rectangle around an added character when typing

Also, this fix doesn't implement Text pattern for a DataGridViewTextBoxCell in non-edit mode (just selected). Text pattern works only when the cell in **edit** mode.

But the main aim was achieved.

2020-09-17 01:35 UTC, RussKie approved these changes

2020-09-18 04:10 UTC, merged