Adding Text pattern to PropertyGridView.GridViewEdit
dotnet/winforms pull request #3876
Opened 2020-09-10 17:45 UTC by vladimir-krestov

Fixes #3683
Original Bug: [1159883](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1159883)
Based on PR #2701

## Proposed changes

- Enable **Text pattern** support for `GridViewEditAccessibleObject`

## Customer Impact

- Visually impaired users will be able to read and interact with the text content of a ToolStripTextBox

## Regression? 

- No

## Risk

- Minimal

### Before

- Narrator does not announce the text navigation and selection of a PropertyGridView.GridViewEdit

### After

- Narrator announces the text content of a PropertyGridView.GridViewEdit (navigation, selection)

## Test methodology 

- Manual testing
- CTI
- Unit tests

## Accessibility testing  
- Using Narrator and Inspect

## Test environment(s) 

- Net 5.0 Version: 5.0.0-rc.1.20431.5
- Microsoft Windows [Version 10.0.19041.450]

2020-09-11 16:30 UTC, vladimir-krestov commented
Testers approved the fix ✔️
There are 2 known issues that will be fixed as a separate fix for DataGridViewTextBoxCell and PropertyGridView Edit too:

- #2794: Narrator doesn't announce a text mouse selection (a keyboard selection works well)
- Narrator doesn't show the blue rectangle around an added character when typing

But the main Issue #3683 was fixed

2020-09-14 05:13 UTC, RussKie requested changes
Please rebased

2020-09-14 10:57 UTC, RussKie requested changes
LGTM module the feedback

2020-09-14 10:57 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObject.cs
> +                    _owningPropertyGridView = owner.psheet;
Test for `owner is null`?

2020-09-17 02:27 UTC, RussKie approved these changes

2020-09-21 03:16 UTC, RussKie approved these changes

2020-09-21 03:16 UTC, RussKie commented
/azp run

2020-09-21 07:02 UTC, merged