Adding Text pattern to UpDownControls
dotnet/winforms pull request #3878
Opened 2020-09-10 19:16 UTC by vladimir-krestov

Fixes #1588

## Proposed changes

- Enable **Text pattern** support for `UpDownEditAccessibleObject`

## Customer Impact

- Visually impaired users will be able to read and interact with the text content of a UpDownControls 

## Regression? 

- No

## Risk

- Minimal

### Before

- Narrator does not announce the text navigation and selection of a UpDownControls

### After

- Narrator announces the text content of a UpDownControls (navigation, selection)

## Test methodology 

- Manual testing
- CTI
- Unit tests

## Accessibility testing  
- Using Narrator and Inspect

 

## Test environment(s) 

- .Net 5.0 Version: 5.0.0-rc.1.20431.5
- Microsoft Windows [Version 10.0.19041.450]

2020-09-18 15:03 UTC, vladimir-krestov commented
I implemented Text pattern for `UpDownEdit` and now it has the following behavior (I'm clicking the Up keyboard arrow):
![rHIHl8liOb](https://user-images.githubusercontent.com/49272759/93611680-463e6300-f9d7-11ea-9069-01f182487212.gif)
Text pattern works expectedly, but the Narrator blue rectangle jumps when clicking "Up/Down" keyboard arrows when NumericUpDown has the 2-digit value.
This behavior can seem confusing but I think all right because this is expected Text pattern behavior. Like in `RichTextBox` that supports Text pattern from Win32:
![5Y1bRNe6Hp](https://user-images.githubusercontent.com/49272759/93612253-f8762a80-f9d7-11ea-8ba1-1ffc99632661.gif)
Here you can see the same Narrator steps:
- Click the Up/Down keyboard arrow
- Narrator reads a whole line where the caret is
- Narrator shows the blue rectangle for a character after the caret

I think the current `NumericUpDown` Text pattern behavior is correct. @merriemcgaw, @Tanya-Solyanik, could you please approve my thoughts?

2020-09-18 18:08 UTC, merriemcgaw commented
@SergeySmirnov-Akvelon  - does this impact the non-narrator situation where currently up/down arrows are used to increase/decrease the value in the box? Would that still work with this text pattern?

2020-09-21 20:22 UTC, vladimir-krestov commented
@merriemcgaw No, Text pattern doesn't impact the non-narrator situation. This is needed only to Narrator announces UpDown characters correctly.
You won't notice the change without Narrator.
@merriemcgaw Will we keep the current implementation? (https://github.com/dotnet/winforms/pull/3878#issuecomment-694921303)

2020-09-21 22:39 UTC, merriemcgaw commented
@vladimir-krestov that looks good to me. Does the Narrator user get to head over to the up/down controls next to the edit and use them as usual?
@Olina-Zhang, let us know the test results ASAP. 
@SteveCarrollMSFT this should be the last thing we bring for the TextPattern support, and then we're compliant for this UIA pattern!

2020-09-21 22:48 UTC, RussKie requested changes
Need to tighten up the validation.

2020-09-21 22:48 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObject.cs
> +                readonly UpDownBase _parent;
```suggestion
                private readonly UpDownBase _parent;
```

2020-09-21 22:48 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObject.cs
> +                    _parent = parent;
We're not enforcing or checking `parent is not null`, this may lead to NREs

2020-09-22 05:51 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObject.cs
> +                    _parent = parent;
Yes, thanks, you are right! `UpDownEditAccessibleObject` constructor is used once, so I just added `ArgumentNullException` throwing if `parent` is null.

2020-09-22 23:14 UTC, vladimir-krestov commented
@merriemcgaw Now it has some differences, but a user hears the same.
![image](https://user-images.githubusercontent.com/49272759/93946619-6311c800-fd42-11ea-902c-705220ccd240.png)

In the rest, UpDown controls work as usual. A user can navigate to these controls and move from them to other controls on a form using "Tab".

2020-09-22 23:23 UTC, vladimir-krestov commented
Testers approved the fix ✔️ 
But there are some test issues:
- Narrator doesn't announce a new value sometimes if to click Up/Down buttons using a mouse
![image](https://user-images.githubusercontent.com/49272759/93946833-fb0fb180-fd42-11ea-881c-d4615abf7e37.png)
It happens in the first running. Also, using Narrator with a mouse is not the common scenario. So moved the issue to .Net 6.0. It won't be fixed here.
- The Narrator blue rectangle has some little differences in different OS versions. They are not critical for a user. And it seems it is Narrator issue.

But the main Issue #1588 was fixed.

2020-09-23 10:28 UTC, RussKie approved these changes

2020-09-23 11:27 UTC, merged