Adding access to page buttons on PrintPreviewDialog by keyboard shortcut keys
dotnet/winforms pull request #3929
Opened 2020-09-16 11:51 UTC by SergeySmirnov-Akvelon

Fixes #3682

## Proposed changes

- Adding support of keyboard shortcut keys for access to page buttons on PrintPreviewDialog

## Customer Impact
- The user will be able to switch between viewing modes using the shortcut keys (Ctrl+1, Ctrl+2, etc) on PrintPreviewDialog

## Regression? 

-  No

## Risk

- Minimal

## Test methodology 

- Manual testing

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- NET Core 5.0.100-rc.1.20420.14

2020-09-16 17:01 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/Resources/System/Windows/Forms/PrintPreviewDialog.resx
> +    <value xml:space="preserve">Six pages (Ctrl+5)</value>
What was the reason to go with `Ctrl+5` and not with `Ctrl+6`? Did you find any guidance about it?

2020-09-17 02:04 UTC, RussKie commented on src/System.Windows.Forms/src/Resources/System/Windows/Forms/PrintPreviewDialog.resx
> +    <value xml:space="preserve">Six pages (Ctrl+5)</value>
This was my suggestion https://github.com/dotnet/winforms/issues/3682#issuecomment-689948410 that everyone has agreed with.

In my opinion it is a logical sequence - option 1, 2, ...5, and not based on number of pages. E.g. if there was a sixth option to show 12 pages - as a user I wouldn't expect <kbd>CTRL</kbd>+<kbd>12</kbd> but <kbd>CTRL</kbd>+<kbd>6</kbd>.

2020-09-17 02:13 UTC, RussKie reviewed
👍

2020-09-17 02:13 UTC, RussKie commented on Winforms.sln
> -		{C272DA06-B98D-4BB7-B1C4-ECF58F54B224}.Release|x64.Build.0 = Release|x64
Why have these been deleted?

2020-09-17 02:13 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
> +                Func<PrintPreviewDialogToolStripButton, bool> performPageClick = (PrintPreviewDialogToolStripButton pageToolStripButton) =>
It is better to use local functions vs expressions, as they have less overhead (http://mustoverride.com/local_functions/).
Convert to a local function and place it after line:1293

2020-09-17 07:46 UTC, SergeySmirnov-Akvelon commented on Winforms.sln
> -		{C272DA06-B98D-4BB7-B1C4-ECF58F54B224}.Release|x64.Build.0 = Release|x64
Changes are reverted

2020-09-17 08:11 UTC, RussKie submitted a review, later dismissed

2020-09-18 04:36 UTC, RussKie requested changes

2020-09-18 04:36 UTC, RussKie commented on Winforms.sln
> -		{C272DA06-B98D-4BB7-B1C4-ECF58F54B224}.Release|x64.Build.0 = Release|x64
❗  This is System.Windows.Forms.Interop.Tests which is a C/C++ project that must specify x86 and x64 platforms explicitly.

2020-09-25 02:31 UTC, RussKie approved these changes

2020-09-25 02:31 UTC, RussKie commented
/azp run

2020-09-25 05:48 UTC, merged

2020-09-25 18:04 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/Resources/System/Windows/Forms/PrintPreviewDialog.resx
> +    <value xml:space="preserve">Six pages (Ctrl+5)</value>
Had you guys looked at what Office or windows are doing in similar cases?