fix: PlaceholderText  BackColor
dotnet/winforms pull request #4008
Opened 2020-09-25 09:10 UTC by yvz5

Changed the backcolor to empty of the placeholder text when the textbox is disabled.

Added a check to see if the Enabled property is true, if so the BackColor of the textbox will be used, if not Color.Empty will be used to render the placeholder text's background transparently.

Fixes #3642

## Screenshots 

### Before

![before](https://user-images.githubusercontent.com/439370/94249038-98bfd800-ff1f-11ea-8b35-8c23783a3767.png)

### After

![after](https://user-images.githubusercontent.com/439370/94248991-89d92580-ff1f-11ea-87f7-4169de3ad7e7.png)

2020-09-28 02:39 UTC, RussKie reviewed
👍 

Now we need to write tests :)

Please have a look at `ToolStrip_RendersBackgroundCorrectly` to get an idea how we do it with TestAccessors() to access non-public API, and EMF to verify rendering aspects.

Holler if you get stuck.

2020-09-28 12:38 UTC, yvz5 commented
Thanks for your reply. I wanted to write a test but I couldnt find a proper ui test :) I also can not find `ToolStrip_RendersBackgroundCorrectly`. Can you tell me where this method  / test is ?

2020-09-28 13:22 UTC, RussKie commented
https://github.com/dotnet/winforms/blob/548ab3a871c69e33a40ca0aea4a07e866ee945e7/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.Rendering.cs#L15

2020-09-28 13:46 UTC, yvz5 commented
Ah I see that file was not in my master branch. There is no `TextBoxTests.Rendering.cs` file. Should I create one and put the test inside it ? or is it ok to write the ui test inside the `TextBoxTests.cs` file ?

2020-09-28 23:06 UTC, RussKie commented
> Should I create one and put the test inside it ?

Yes, please. I expect more rendering tests to be added in the future.

2020-09-30 09:18 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4008) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4008) before we can accept your contribution.<br/><br/>:x: yvz5 [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4008)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=4008) it.</sub>

2020-09-30 10:49 UTC, RussKie commented
We don't merge the main branch in feature branches, because it now contains not only your changes but also unrelated changes that the other branch contains. This makes it difficult to reason about your change.
Please rebase on top of the latest master and force push your branch.

2020-09-30 11:14 UTC, yvz5 commented
@RussKie sorry about that, Im really new to forking. When I rebase using `git rebase upstream/master` into my feature branch, I get lots of commits. It also deletes my local changes. How do I recover from here ? Should I create a new PR ?

2020-09-30 11:30 UTC, RussKie commented
> Should I create a new PR ?

No.

> When I rebase using `git rebase upstream/master` into my feature branch, I get lots of commits. It also deletes my local changes. 

\<personal opinions>
This is why I always say - there's no shame in using UI tools :) I personally use [Git Extensions](https://github.com/gitextensions/gitextensions), but you can use any git UI out there.
</personal opinions>

Instead of running `git rebase` or `git pull` I firstly run:
```
git fetch -all
````
This way my current state **does not change**, I just download all the remote changes, and now I can decide where I want to be.
After that I rebase the current branch on top of the master (or whatever other commit I want to be on):
```
git -c rebase.autoSquash=false rebase "<target commit hash>"
```
And once it is done, the solution builds and tests pass, I force push back into my fork:
```
git push -f
```
NB: I don't manually run any of those commands, Git Extensions does it for me, but the essence is the same.

Hope this makes sense.

2020-10-01 05:36 UTC, RussKie requested changes

2020-10-01 05:36 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/TextBoxTests.Rendering.cs
> +        public void TextBox_PlaceholderText_RendersBackgroundCorrectly()
Whilst this is a good test to have - to verify the background is rendered correctly, this test has no relation to the bug you're fixing.

This is what this test asserts:
![image](https://user-images.githubusercontent.com/4403806/94768555-19d11080-03f3-11eb-8124-4e002ca7f567.png)

You can see this by executung `form.ShowDialog();` after `form.PerformLayout();`.

This is what we want to fix (btw the problem doesn't appear when a custom background colour is used):
![image](https://user-images.githubusercontent.com/4403806/94768369-96172400-03f2-11eb-8dbf-b5ccef7d8c6e.png)
...or
![image](https://user-images.githubusercontent.com/4403806/94768231-33be2380-03f2-11eb-8d9e-a23acc201d18.png)

A test we are looking for must do this:
```cs
            using var emf = new EmfScope();
            DeviceContextState state = new DeviceContextState(emf);
            using var dc = new HdcDeviceContextAdapter(emf.HDC);

            textBox.TestAccessor().Dynamic.DrawPlaceholderText(dc);

            emf.Validate(state, ...)
```

and this is what we probably want to assert:
```
[EMRSETBKMODE] Mode: BKMODE_OPAQUE
```

You will also need to update the signature of `DrawPlaceholderText` to the following:
```diff
diff --git a/src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs b/src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
index 433b16d8b..ce3c4cad6 100644
--- a/src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
+++ b/src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
@@ -891,7 +891,7 @@ namespace System.Windows.Forms
         /// <summary>
         ///  Draws the <see cref="PlaceholderText"/> in the client area of the <see cref="TextBox"/> using the default font and color.
         /// </summary>
-        private void DrawPlaceholderText(Graphics graphics)
+        private void DrawPlaceholderText(IDeviceContext deviceContext)
         {
             TextFormatFlags flags = TextFormatFlags.NoPadding | TextFormatFlags.Top |
                                     TextFormatFlags.EndEllipsis;
@@ -936,7 +936,7 @@ namespace System.Windows.Forms
                 }
             }
 
-            TextRenderer.DrawText(graphics, PlaceholderText, Font, rectangle, SystemColors.GrayText, BackColor, flags);
+            TextRenderer.DrawText(deviceContext, PlaceholderText, Font, rectangle, SystemColors.GrayText, BackColor, flags);
         }
```
/cc: @JeremyKuhne looks like this was missed

2020-10-01 18:29 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/TextBoxTests.Rendering.cs
> +        public void TextBox_PlaceholderText_RendersBackgroundCorrectly()
> looks like this was missed

Yep, I didn't follow all of the callers back. The best choice here is that the `HDC` should be passed through from the `TextBox.WndProc()` as there is an overload for `TextRenderer.DrawTextInternal()` that takes an HDC directly. Then you can avoid creating unnecessary adapters to `IDeviceContext` (`Graphics` or `HdcDeviceContextAdapter`), saving some _significant_ allocations in the `Graphics` case.

> [EMRSETBKMODE] Mode: BKMODE_OPAQUE

You'll need to create a state validator.  Simple enough to do- just copy one of the existing ones, such as `TextColorValidator` to make a `BackgroundModeValidator` and add the convenience method on `State`.  You'll be taking `Gdi32.BKMODE` and checking against `DeviceContextState.BackgroundMode`.

I accidentally removed this state check when I refactored the validation code into state validators.  🤦‍♂️ `TextRenderer_DrawText_DefaultBackground_RendersTransparent` needs to make the same `State.BackgroundMode` check. @yvz5, if you can add that to the list of state validators in that test when you do this, that would be much appreciated! :)

2020-10-02 12:02 UTC, yvz5 commented on src/System.Windows.Forms/tests/UnitTests/TextBoxTests.Rendering.cs
> +        public void TextBox_PlaceholderText_RendersBackgroundCorrectly()
Well to be honest, I am totally lost here. I have never worked with winforms source code before and I thought adding a check would be enough to fix this problem. You throw all these terms but I don't even know what they mean.  

I dont understand how the EmfScope and its validators work. I'm afraid I am not able to work alone on this anymore. I need serious babysitting to understand and do the proper changes. Either you take over the ticket or you invest time on teaching me how to do it :)

2020-10-06 03:30 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/TextBoxTests.Rendering.cs
> +        public void TextBox_PlaceholderText_RendersBackgroundCorrectly()
> I thought adding a check would be enough to fix this problem

Any change should be validated and tested. Whilst the fix you proposed looks correct, the tests you have put in place aren't testing your fix, they are testing something else.



> You throw all these terms but I don't even know what they mean.
> 
> I dont understand how the EmfScope and its validators work.

That's ok, no one knows everything, ask questions as we'll do our best to answer.

We use [Enhanced Metafiles](https://docs.microsoft.com/en-us/windows/win32/gdi/enhanced-format-metafiles) (or EMF for short) to validate rendering operations, i.e. assert that correct shapes were drawn with expected colours and brushes. The initial support was added in https://github.com/dotnet/winforms/pull/3645 and enhanced ever since.

```cs
            using var emf = new EmfScope();
            DeviceContextState state = new DeviceContextState(emf);
            using var dc = new HdcDeviceContextAdapter(emf.HDC);

            textBox.TestAccessor().Dynamic.DrawPlaceholderText(dc);

            emf.Validate(state, ...)
```

So what we do here is create a new EMF into which will draw (as oppose to drawing on your monitor), then we draw the placeholder text into the EMF, after which we assert the drawing instructions were correct, i.e. we haven't drawn an opaque background for the placeholder text (that's what we're trying to fix here, right?).

> Either you take over the ticket or you invest time on teaching me how to do it :)

Demands won't take us really far.

2020-10-06 05:59 UTC, RussKie commented
@yvz5 please have a look at https://github.com/dotnet/winforms/pull/4057

2020-10-06 06:20 UTC, yvz5 commented
@RussKie sorry if I come across "demanding". I just wanted to let you know that it would take more time for me to understand EMF and validators, as there is no documentation about how it works.

Thanks for taking time and implementing the tests yourself. Appreciate that.

2020-10-06 23:14 UTC, RussKie commented
> I just wanted to let you know that it would take more time

The .NET 6.0 release is almost a year away, so we have time :)

2020-10-09 06:06 UTC, closed without merging

2020-10-09 06:07 UTC, RussKie commented
Thank you for attempting to fix this.