Add Rich Navigation to CI, a new Rich Nav pipeline
dotnet/winforms pull request #4086
Opened 2020-10-12 04:24 UTC by jepetty

I've altered two files:
1. Add a Rich Navigation specific build (which will appear as a new build pipeline), indexing on every push to master. This will allow you to use Rich Navigation in Visual Studio to enable cross-repository searches, serverless navigation at https://online.visualstudio.com/github/dotnet/msbuild, and integrated GitHub C# navigation once that is released (or, comment below if you want to be added to the preview now 😊).
1. Added the Rich Navigation task to your normal unit test CI. This has all the same benefits of ^, but also indexes your pull requests for a richer code review experience. This does come at the cost of increasing the time of your CI.

Based on your team's preference, only one of these changes is necessary.

## Rich Code Navigation

[Docs Link](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/1047/Rich-Code-Navigation)
With Rich Code Navigation, you can use editor-level navigation capabilities (like peek definition, find all references, and even diagnostics) on a pull request, without requiring a local checkout. This is available across all files and dependencies of your repository.

Rich Code Navigation is available for Visual Studio (for repos hosted on GitHub or Azure Repos) and Visual Studio Code (for repos hosted on GitHub).

Rich Code Navigation supports these capabilities:

- Hover
- Peek definition and Go to definition
- Peek references and Find all references
- Go to type definition
- Go to implementation
- Diagnostics

2020-10-12 05:23 UTC, RussKie commented
/azp run

2020-10-12 05:24 UTC, RussKie commented
> 1. comment below if you want to be added to the preview now 😊

Yes, please!

2020-10-12 05:36 UTC, RussKie reviewed
Thank you!

Few noob questions.

2020-10-12 05:36 UTC, RussKie commented on eng/ci.yml
> +        enableRichCodeNavigation: true
Do we need to do this for both public and internal infras?
If not, perhaps move it above after line:20 as `enableRichCodeNavigation: ${{ if eq(variables['System.TeamProject'], 'public') }}`?

Also this build definition executes for both PR and normal builds, do we still need azure-pipelines-richnav.yml?

2020-10-12 23:34 UTC, RussKie commented
![image](https://user-images.githubusercontent.com/4403806/95799218-b5417a00-0d3f-11eb-9ee3-87b0d0487856.png)

2020-10-13 04:29 UTC, jepetty commented on eng/ci.yml
> +        enableRichCodeNavigation: true
Great call! I've updated to only run on the public build. Thank you!

2020-10-14 03:38 UTC, RussKie commented
Waiting for https://github.com/dotnet/arcade/pull/6345

2020-10-21 11:06 UTC, RussKie reviewed
LGTM (with my limited knowledge in this area)

2020-10-21 11:06 UTC, RussKie commented
@AdamYoblick what do you think?

2020-10-21 11:09 UTC, RussKie commented
@jepetty can we see the results of this pipeline any where before we merge?

Also once it is merged, do we need to do anything special to run this pipeline, or will it run on automagically its own? And once it is run we'll be able to peek defs/navigate the code on GitHub, right?

2020-10-21 15:51 UTC, jepetty commented
@RussKie I've added it to the normal CI and you can see its successful [run](https://dev.azure.com/dnceng/public/_build/results?buildId=860636&view=logs&j=1f132584-ab08-5fbf-e5d0-5685de454342). It does add 10 minutes to your build, so I'm guessing you'll want the separate, Rich Nav specific pipeline?

2020-10-21 15:54 UTC, jepetty commented
Please ignore my last HACK-tackular commit where I replaced the normal CI with the Rich Nav CI. I'm doing this just to verify that the Rich Nav pipeline runs correctly and will revert once that's done.

2020-10-21 16:31 UTC, jepetty commented
I reverted my hack-tacular change to the main CI and applied the fixes that it uncovered to the Rich Nav branch. You can see a successful build of the Rich Nav pipeline [here](https://dev.azure.com/dnceng/public/_build/results?buildId=861304&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=33a05e2b-74e7-5741-ccc1-a0526385f425) - although it failed the publishing step because I had an extraneous variable which I've since removed.

2020-10-23 21:46 UTC, AdamYoblick commented
@RussKie - I spoke with Jessica offline and we agreed that adding 10 minutes to the build is probably not the best idea since leadership is heavily pushing towards reduced build times (going so far as to remove the unit tests from the actual build pipeline).

So she's going to modify this PR and make a new pipeline just for richnav. 😄

2020-10-23 21:48 UTC, AdamYoblick requested changes
Just requesting a change on removing the section we talked about in ci.yml. Thank you! 😄

2020-10-23 21:48 UTC, AdamYoblick commented on eng/ci.yml
> +      ${{ if eq(variables['System.TeamProject'], 'public') }}:
Please remove this section once the new pipeline is added

2020-10-23 21:48 UTC, AdamYoblick commented on azure-pipelines-richnav.yml
> +            /bl:$(BUILD.SOURCESDIRECTORY)\artifacts\log\Debug\BuildSrc.binlog
Since you're only doing a build, you don't need to overwrite the default binlog name/location. Consider removing this line.

2020-10-26 16:38 UTC, jepetty commented on eng/ci.yml
> +      ${{ if eq(variables['System.TeamProject'], 'public') }}:
Removed! I'll add the new pipeline once this PR is merged.

2020-10-26 16:39 UTC, jepetty commented on azure-pipelines-richnav.yml
> +            /bl:$(BUILD.SOURCESDIRECTORY)\artifacts\log\Debug\BuildSrc.binlog
Removed! Thanks for the review!

2020-10-29 20:36 UTC, jepetty commented
@RussKie and @AdamYoblick thanks for your reviews and time! Are there other changes you're looking for, or do you think this is ready to merge?

2020-10-29 20:43 UTC, AdamYoblick commented
Ah sorry Jessica, I was heads down on other stuff and this completely slipped my mind. My apologies.

I have to watch the kids for a doctor appt right now but I will approve/merge as soon as I’m available :)

________________________________
From: Jessica Petty <notifications@github.com>
Sent: Thursday, October 29, 2020 3:37:13 PM
To: dotnet/winforms <winforms@noreply.github.com>
Cc: Adam Yoblick <Adam.Yoblick@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [dotnet/winforms] Add Rich Navigation to CI, a new Rich Nav pipeline (#4086)


@RussKie<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRussKie&data=04%7C01%7CAdam.Yoblick%40microsoft.com%7C13466f9f78a94ed2092e08d87c4a6ab5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637396006347315950%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z2tNHsgBvhbDkQQIf5KBXkN%2BzdbHLgmQLf5X6cKQ%2BT8%3D&reserved=0> and @AdamYoblick<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdamYoblick&data=04%7C01%7CAdam.Yoblick%40microsoft.com%7C13466f9f78a94ed2092e08d87c4a6ab5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637396006347315950%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=de2DWk8LThS77iFfdJgNaID1aiR45TKsbWxpIvQKD1U%3D&reserved=0> thanks for your reviews and time! Are there other changes you're looking for, or do you think this is ready to merge?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fpull%2F4086%23issuecomment-719006918&data=04%7C01%7CAdam.Yoblick%40microsoft.com%7C13466f9f78a94ed2092e08d87c4a6ab5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637396006347325942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SkK6TwbbuGbHNXzcDCzIBgV1axVZNSFniipSaPh2GD0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHASVDI4XZIRQ5X7LT74ZZ3SNHG7TANCNFSM4SMIZ3MQ&data=04%7C01%7CAdam.Yoblick%40microsoft.com%7C13466f9f78a94ed2092e08d87c4a6ab5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637396006347325942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xsvp0u4llyL4WJiLnh%2B9IlkRZag0t%2FhjiEp1yf6M32I%3D&reserved=0>.

2020-10-29 20:50 UTC, AdamYoblick submitted a review, later dismissed
Approved with one nitpick 😄

2020-10-29 20:50 UTC, AdamYoblick commented on azure-pipelines-richnav.yml
> +        # Build and rename binlog
Just a nit - this comment is stale. The binlog is not being renamed, and the Coverage argument is not being passed. So might wanna update this. Otherwise looks good :)

2020-10-29 20:52 UTC, AdamYoblick commented
I'm out watching the kids, so I probably won't be able to merge this in until tomorrow. @RussKie if you want to do it, I'm all signed off.

2020-10-29 20:54 UTC, jepetty commented on azure-pipelines-richnav.yml
> +        # Build and rename binlog
Always love removing lines :) Thanks for the comment!

2020-10-29 21:44 UTC, AdamYoblick approved these changes

2020-10-29 21:44 UTC, merged

2020-10-29 21:44 UTC, AdamYoblick commented
Looks good, merging this in. :)

2020-10-29 22:31 UTC, RussKie commented
The internal CI failed:
![image](https://user-images.githubusercontent.com/4403806/97639470-b50ce280-1a92-11eb-82fd-a9041f446023.png)

What are we missing?

2020-10-29 23:27 UTC, jepetty commented
@RussKie that looks unrelated to my change (maybe an interim outage)? I re-queued the failed build and it passed that step the second time