Fixing issue with getting of textbox from DataGridViewTextBoxCell  by Accessibility Insights
dotnet/winforms pull request #4124
Opened 2020-10-16 11:53 UTC by SergeySmirnov-Akvelon

Fixes #3925

## Proposed changes
- Restored logic for recreation of textbox handle;

## Customer Impact
Fixed issue with hanging of Accessibility Insights during getting of data about textbox from DataGridViewTextBoxCell

## Regression? 

- Yes

## Risk
- Minimal

## Test methodology 
- Manually 

## Accessibility testing  
- Narrator
- Inspector
- Accessibility Insights

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core 5.0.100-rc.1.20420.14

2020-10-23 11:01 UTC, RussKie requested changes

2020-10-23 11:29 UTC, RussKie approved these changes

2020-10-26 12:39 UTC, SergeySmirnov-Akvelon commented
CTI approved

2020-10-27 06:30 UTC, merged

2020-10-27 06:30 UTC, RussKie commented
Thank you