Add some codes in Accessibility sample app to work around bug 1155463
dotnet/winforms pull request #4132
Opened 2020-10-19 09:01 UTC by Amy-Li03

Fix bug [1155463](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1155463?src=WorkItemMention&src-action=artifact_link), add some codes on sample app to make Narrator say "Please enter first name now" and added dataGridView.Focus() on "Click" event of "Add new" button.

## Proposed changes
Update related codes in DataControls.Designer.cs and DataControls.cs files

## Customer Impact
After this update, Narrator can read the status message as row added after click on Add New button.

## Regression? 

No

## Risk

No

## Screenshots 
### After

![image](https://user-images.githubusercontent.com/62929087/96423666-2cb45500-11e9-11eb-907a-0954c44dad5a.png)

2020-10-19 09:01 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4132) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4132) before we can accept your contribution.<br/><br/>:x: Amy-Li03 [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4132)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=4132) it.</sub>

2020-10-20 05:00 UTC, RussKie requested changes
How/why did "InteropTests/NativeTests/out/build/x64-Debug (default)" get committed? Please add "InteropTests/NativeTests/out" to .gitignore, and revert these files

2020-10-21 01:53 UTC, Amy-Li03 commented on src/System.Windows.Forms/tests/AccessibilityTests/DataControls.cs
> +              "Please enter first name now");
Done

2020-10-21 01:53 UTC, Amy-Li03 commented on src/System.Windows.Forms/tests/AccessibilityTests/DataControls.cs
> +        private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
Done

2020-10-21 11:33 UTC, RussKie commented
All of these files must be removed from the PR:
![image](https://user-images.githubusercontent.com/4403806/96714088-62299000-13ed-11eb-9fe1-64f430a88439.png)

2020-10-22 05:46 UTC, RussKie approved these changes

2020-10-22 06:00 UTC, RussKie commented
/azp run

2020-10-22 06:33 UTC, merged