Fix 4169
dotnet/winforms pull request #4184
Opened 2020-11-02 08:22 UTC by RussKie

Fixes #4169

## Proposed changes

- 
- 

## Customer Impact

- 
- 

## Regression? 

- Yes / No

## Risk

-

## Screenshots 

### Before

### After

## Test methodology 

- 
- 
- 

## Accessibility testing  

 

## Test environment(s) 

-

2020-11-02 12:10 UTC, weltkante requested changes
I don't think this fix is safe, ownership is transferred to the native control, the native image list can be deleted at arbitrary points in time.

2020-11-02 13:36 UTC, hughbe commented on src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
> +                // Add tehe image to the unmanaged imagelist which is ghosting this managed instance
nit: typo

2020-11-03 08:18 UTC, weltkante reviewed
@RussKie Is this a clean rollback of the original workaround-PR now, or is there something to review? ~~I'll look which issues need to be reopened (or followed up) for a rollback and link them.~~

I was apparently misremembering some designer issue being resolved by this PR, or I can't find it. The other issue was #3531 and is still open. It will need to be adressed, or you have to remove that usage pattern from all your tests, otherwise tests go back to flaky upon reverting. (I think they'll still be flaky anyways from other mishandled ownership scenarios, but it might be worth trying to see if avoiding that particular usage pattern can significantly reduce the amount of flakyness.)

Also test failures here may be related to assertions introduced in separate PRs, you'll have to remove assertions that verify no double-free happens on the ImageList.

2020-11-04 03:12 UTC, RussKie commented
Yes, there have been a few things done that reduced the amount of issues we have with the `ImageList`. I'm still testing and exploring what needs to be done.

2020-11-04 04:19 UTC, RussKie commented
@weltkante I think I may have finally found a reasonable fix, thanks to your suggestions. We have a plumbing to alert the `ImageList` about changes in the collection, and we can use the same mechanism to force it re-create native handles.

2020-11-04 05:59 UTC, RussKie commented
A release build failed in `ImageCollection_Item_Get32bppColorDepth_Success`:
```
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs(193,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs(193,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs(193,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format32bppArgb, pixel00Color: Color [Empty], pixel10Color: Color [Empty]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=0, R=0, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs(193,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs(193,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format32bppPArgb, pixel00Color: Color [Empty], pixel10Color: Color [Empty]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=0, R=0, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs(193,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs(193,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
```

2020-11-04 06:34 UTC, RussKie commented
/azp run

2020-11-04 08:18 UTC, weltkante commented
Those failures are probably just #3898 again.

2020-11-04 12:34 UTC, RussKie commented
Yes, they feel very random. Subsequent builds succeeded.

2020-11-05 10:02 UTC, RussKie commented
/azp run

2020-11-12 01:43 UTC, RussKie commented
/azp run

2020-11-12 04:24 UTC, merged