Allow loading custom comctl32.dll
dotnet/winforms pull request #4289
Opened 2020-11-27 07:26 UTC by RussKie

## Proposed changes

Provide functionality to load a custom comctl32.dll from the application startup folder, if comctl32.dll is present in that location.

This allows loading debug and custom builds of the library.

## Screenshots 

![image](https://user-images.githubusercontent.com/4403806/100421914-68daaf80-30dd-11eb-9dbd-1b16299f6aa2.png)

## Test methodology 

- Adding a debug version comctl32.dll to /src/System.Windows.Forms/src
- Build and run WinformsControlsTest project
- Observe the comctl32.dll is copied to the output folder
- Run "ListView" example and observe debug asserts being hit in the comctl32 source
- Check loaded modules in "Modules" window

2020-11-28 21:00 UTC, hughbe commented
Is this to help with the ImageList problems?

2020-11-29 23:27 UTC, RussKie commented
> Is this to help with the ImageList problems?

It certainly relates, yes. This change allows us to load the debug version of comctl32, so we can step through the code. 
But this also opens other use cases. :)

2020-12-01 22:00 UTC, JeremyKuhne requested changes
Few minor comments.

2020-12-01 22:00 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.LoadLibrary.cs
> +                if (File.Exists(customPath))
You can ignore this check- the OS is going to do it again when you call LoadLibrary anyway.

2020-12-01 22:00 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.LoadLibrary.cs
> +                string customPath = Path.Combine(startupPath, Libraries.Comctl32);
I'd assert here that we got a `Path.IsFullyQualified()` on the `startupPath` and bail to the system path otherwise.

2020-12-01 22:00 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.LoadLibrary.cs
> +        /// <returns>A </returns>
Returns what?

2020-12-02 00:10 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.LoadLibrary.cs
> +                string customPath = Path.Combine(startupPath, Libraries.Comctl32);
One more nit- prefer `Path.Join` over `Path.Combine`.

2020-12-03 01:51 UTC, RussKie commented
Updated

2020-12-04 02:35 UTC, merged