TreeNodeCollection does not allow adding a TreeNode that already exists in TreeView using this[int index] setter
dotnet/winforms pull request #4297
Opened 2020-11-30 01:18 UTC by manuelvalenzuela

Fixes #4293

## Proposed changes
- Setter of method this[int index] of class TreeNodeCollection should not allow adding a TreeNode that already exists in the TreeView

2020-11-30 23:21 UTC, RussKie reviewed
Build is failing

2020-11-30 23:21 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
> +                if(value.Handle != IntPtr.Zero)
[nit] incorrect spacing
```suggestion
                if (value.Handle != IntPtr.Zero)
```

2020-12-01 01:44 UTC, manuelvalenzuela commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
> +                if(value.Handle != IntPtr.Zero)
Thank you, I have solved the spacing and trailing whitespace

2020-12-01 03:49 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
> +            Assert.Throws<ArgumentException>(() => collection[0] = node);
This does have a weird feel about this. Assigning item onto itself assuming it is still bound to the same tree shouldn't throw... 🤔 

@dotnet/dotnet-winforms thoughts?

2020-12-01 05:29 UTC, manuelvalenzuela commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
> +            Assert.Throws<ArgumentException>(() => collection[0] = node);
@RussKie It makes a lot of sense. I was assuming that this[int index] should behave similar to Insert(int index, TreeNode), but Insert adds a node in index and displaces the existing ones.

I propose to "return" in case the node being added already exists in the same index.

2020-12-01 21:44 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
> +            Assert.Throws<ArgumentException>(() => collection[0] = node);
> I propose to "return" in case the node being added already exists in the same index.

Seems reasonable to me.

2020-12-02 05:11 UTC, manuelvalenzuela commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
> +            Assert.Throws<ArgumentException>(() => collection[0] = node);
Thank you, just updated!

2020-12-02 06:02 UTC, RussKie requested changes

2020-12-02 06:02 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
> +
In other scenarios, where we're trying to set a treenode bound to another treeview - we need to throw

2020-12-02 06:19 UTC, manuelvalenzuela commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
> +
I agree with you, also when the TreeNode being set already exists in the same TreeView in a different index. Do you suggest I create a new Issue or should I address it in this one?

2020-12-02 23:05 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
> +
No, let's fix it here. We'll just need few more tests for the various scenarios.

2020-12-03 07:56 UTC, manuelvalenzuela commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
> +
I have added those cases! Thank you

2020-12-04 04:10 UTC, RussKie requested changes
Almost there :)

2020-12-04 04:19 UTC, RussKie commented
On a side note, in general you'd want to avoid tracking-merges as they mangle the history and make it significantly harder to review a PR outside GitHub and alike. 

![image](https://user-images.githubusercontent.com/4403806/101120966-0df80980-3643-11eb-849f-18b266e3f568.png)

Whilst we generally squash-merge PRs in this repo, in other repos this may not be an accepted practice. If, for example, your PR is merged as is, and then for whatever reason it would need to be reverted - it could become a headache for contributors.

A rebase (with a squash or fixups) is generally better alternative.


You also definitely don't want to work off the master branch, or any other branches that you didn't create for that matter:
  ![image](https://user-images.githubusercontent.com/4403806/101121203-ab533d80-3643-11eb-8d18-37b99b47ceda.png)
By working on a branch that you don't own you're inviting troubles such as conflicts and possibility of lost work. It is a good practice to create a new branch for each piece of work you do.

2020-12-04 05:55 UTC, manuelvalenzuela commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
> +        public void TreeNodeCollection_Item_SetExistentTreeNodeSameIndex_ThrowsArgumentException()
I have improved... if still wrong please suggest me a better one.
Thank you for the comments!

2020-12-05 04:39 UTC, RussKie requested changes

2020-12-05 04:39 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
> +        public void TreeNodeCollection_Item_SetTreeNodeAlreadyAdded_ThrowsArgumentException()
This test doesn't throw exceptions, hence the name is incorrect.
```suggestion
        public void TreeNodeCollection_Item_SetSameNodeAgain_Noop()
```

2020-12-05 04:39 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
> +        public void TreeNodeCollection_Item_SetExistentTreeNodeInSamePosition_ThrowsArgumentException()
ditto

Though I don't see a great value in this test, it does the same as the one above. I suggest removing it.

2020-12-05 05:37 UTC, manuelvalenzuela commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
> +        public void TreeNodeCollection_Item_SetTreeNodeAlreadyAdded_ThrowsArgumentException()
OMG, just fixed it, thank you

2020-12-05 06:32 UTC, RussKie approved these changes

2020-12-05 06:32 UTC, RussKie commented
Thank you

2020-12-05 06:32 UTC, merged

2020-12-16 01:24 UTC, RussKie commented
Docs: https://github.com/dotnet/docs/issues/22020