Granular NumericUpDownTests (#4211)
dotnet/winforms pull request #4303
Opened 2020-12-01 06:49 UTC by willibrandon

Fixes #4211 

## Proposed changes

- Split `NumericUpDown_VisualStyles_off_BasicRendering` into 2 smaller tests that assert a single case, enabled and disabled.

## Customer Impact

- None

## Regression? 

- No

## Risk

- Low

## Test methodology 

- Ran the rendering tests.

2020-12-01 19:30 UTC, JeremyKuhne requested changes
Thanks! Just need to enable the tests again.

2020-12-01 19:30 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
>          [ActiveIssue("https://github.com/dotnet/winforms/issues/4211")]
You'll need to remove the `[ActiveIssue]` attributes to reflect that it is resolved and let the test will run now.

2020-12-01 19:30 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
> +            //Check the disabled state
nit: space after `//`

2020-12-01 21:47 UTC, willibrandon commented on src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
>          [ActiveIssue("https://github.com/dotnet/winforms/issues/4211")]
Thank you and will do, I was wondering about that.

2020-12-01 21:47 UTC, willibrandon commented on src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
> +            //Check the disabled state
Will do.

2020-12-02 05:55 UTC, RussKie approved these changes

2020-12-03 02:20 UTC, merged

2020-12-03 02:20 UTC, RussKie commented
Thank you