Implemented ScrollItemPattern for ComboBoxItemAccessibleObject
dotnet/winforms pull request #4350
Opened 2020-12-10 07:46 UTC by vladimir-krestov

Fixes #4335

## Proposed changes

- Implement `ScrollIntoView` method of `ScrollItemPattern`

## Customer Impact

- Accessibility tools or users can scroll a combo box drop-down list to some item

## Regression? 

- Yes (from .NET Framework 4.7.2)

## Risk

- Minimal

## Screenshots 

### Before

TODO 

### After

TODO

## Test methodology 

- TODO: Unit tests
- Manual testing
- CTI

## Accessibility testing  
- Using Inspect

 

## Test environment(s) 

- Microsoft Windows [Version 10.0.19042.685]
- .NET v. 6.0.100-alpha.1.20554.10

2020-12-10 07:48 UTC, vladimir-krestov commented
Just a draft. Needs more testing and improvements.

2020-12-11 07:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    visibleItemsCount = (_owningComboBox.Size.Height - 26) / itemHeight; // 26 is an edit control hight (23) + 3px of borders
Would CB_GETMINVISIBLE  work?

2020-12-11 09:10 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    visibleItemsCount = (_owningComboBox.Size.Height - 26) / itemHeight; // 26 is an edit control hight (23) + 3px of borders
@Tanya-Solyanik 
No. It always returns 30.
```cs
int visibleCount = User32.SendMessageW(_owningComboBox, (User32.WM)User32.CB.GETMINVISIBLE, (IntPtr)currentIndex).ToInt32(); // = 30
```
I spent much time to find `CB_GETMINVISIBLE` value, because we don't have it in the project and the documentation.
`SETMINVISIBLE = 0x1701,`
`GETMINVISIBLE = 0x1702`

Actually, our `ComboBox` works incorrectly.
We have the following ComboBox properties:
- [IntegralHeight](https://docs.microsoft.com/dotnet/api/system.windows.forms.combobox.integralheight)
- [DropDownHeight](https://docs.microsoft.com/dotnet/api/system.windows.forms.combobox.dropdownheight)
- [MaxDropDownItems](https://docs.microsoft.com/dotnet/api/system.windows.forms.combobox.maxdropdownitems)

They don't reflect on each other.
- `MaxDropDownItems` has **8** as the default value. We can see 8 items in a drop-down if to set `IntegralHeight` to **`false`** only and if `DropDownHeight` is not set. If `IntegralHeight` is true or `DropDownHeight` is set then `MaxDropDownItems` doesn't reflect a real count of visible items. For example:
```cs
this.comboBox3.IntegralHeight = false;
this.comboBox3.DropDownHeight = 131; // 8.5 items are visible. One item is 15px height
this.comboBox3.MaxDropDownItems = 5; // All the same we see 8.5 items
```
- `MaxDropDownItems` and `DropDownHeight` don't affect a drop-down height of a `ComboBox` with the `Simple` drop-down style. And these properties will store not real values.
- `MaxDropDownItems` and `DropDownHeight` do not matter if `IntegralHeight` is **`true`** (default value) and they store not real visible values.
- If `MaxDropDownItems` is set then `DropDownHeight` doesn't reflect a real value. For example:
```cs
this.comboBox3.IntegralHeight = false;
this.comboBox3.MaxDropDownItems = 5; // The real drop-down height is about 75 px (5*15px)
//this.comboBox3.DropDownHeight = 131; // Is not set, but if we try to get this value we will get 106 px
```

I expect that these 3 properties should reflect real visible values when some of them are set. I think, we can discuss it and fix it as another Issue. We should use `CB_SETMINVISIBLE` to set correct values for a native control.

2020-12-11 09:12 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    visibleItemsCount = (_owningComboBox.Size.Height - 26) / itemHeight; // 26 is an edit control hight (23) + 3px of borders
At this moment, I'm working on getting a real value of a drop-down height from a native window. It will allow us to a get real count of visible items.

2020-12-12 17:17 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    visibleItemsCount = (_owningComboBox.Size.Height - 26) / itemHeight; // 26 is an edit control hight (23) + 3px of borders
Have made it. Please review.

2020-12-12 17:51 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                return (dropDownWindow.Size.Height + 2) / itemHeight; // 2px of borders
It works well in the high DPI mode.
Sometimes dropdown window size lacks a couple of pixels and we add it here to get the correct visible items count.

2020-12-14 05:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    visibleItemsCount = (_owningComboBox.Size.Height - 26) / itemHeight; // 26 is an edit control hight (23) + 3px of borders
> We have the following ComboBox properties...(snip)
> They don't reflect on each other.

The docs state that setting `DropDownHeight` will reset `IntegralHeight` to `false`

2020-12-14 06:00 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    visibleItemsCount = (_owningComboBox.Size.Height - 26) / itemHeight; // 26 is an edit control hight (23) + 3px of borders
Yes, you are right, that is a little worked point. 
But if you set `IntegralHeight` as true after that, then the visible items count will be **30** and `DropDownHeight` will not reflect real value.

2020-12-14 18:10 UTC, vladimir-krestov commented
Tested in HDPI mode and without enabled visual styles. The algorithm works well.

2020-12-15 07:51 UTC, RussKie commented
> Tested in HDPI mode, in High Contrast mode and without enabled visual styles.

Got screenshots? :)

2020-12-15 07:51 UTC, RussKie reviewed
LGTM

2020-12-15 11:27 UTC, vladimir-krestov commented
> > Tested in HDPI mode, in High Contrast mode and without enabled visual styles.
> 
> Got screenshots? :)

- DPI 150%
![1](https://user-images.githubusercontent.com/49272759/102209189-7667a600-3ee1-11eb-83bc-d932c1f96e2d.gif)

- HighContrast
![2](https://user-images.githubusercontent.com/49272759/102209228-87181c00-3ee1-11eb-99a2-ab6e12fccc08.gif)

- Without visual styles
![3](https://user-images.githubusercontent.com/49272759/102209260-9008ed80-3ee1-11eb-9977-8317467fd685.gif)

2020-12-15 20:44 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    patternId == UiaCore.UIA.ScrollItemPatternId ||
Is this pattern always available in 4.7.2, or only when the scroll bar is displayed?

2020-12-15 20:47 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    patternId == UiaCore.UIA.ScrollItemPatternId ||
A good question, will check it in 4.7.2.

2020-12-16 20:35 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                int currentIndex = _owningComboBox.Items.IndexOf(_owningItem);
Please set the top item instead of this calculation.

2020-12-17 17:25 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    patternId == UiaCore.UIA.ScrollItemPatternId ||
Yes

![image](https://user-images.githubusercontent.com/49272759/102521357-e4f56100-40a5-11eb-9573-126da6c3ff3f.png)

2020-12-17 17:46 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                int currentIndex = _owningComboBox.Items.IndexOf(_owningItem);
I oriented to our `ListBox` and thought that the current behavior is better. But I checked **4.7.2** and a native `ComboBox` (that the same) and `ListBox`. They work as you said. They just set a top index. I'll make it as there to be consistent.

2020-12-17 19:03 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                int currentIndex = _owningComboBox.Items.IndexOf(_owningItem);
Done and tested

2020-12-17 21:18 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                if (!_owningComboBox.IsHandleCreated || _owningComboBox.Items.Count == 0)
What happens if count is zero? Do we need this test in NETFX?

2020-12-17 21:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                int currentIndex = _owningComboBox.Items.IndexOf(_owningItem);
Sounds like we should change ListBox to "set top" as well, please open a new issue.

2020-12-17 21:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                if (!_owningComboBox.IsHandleCreated || _owningComboBox.Items.Count == 0)
This file assumes that the _owningItem is in the list of items of this combobox, I don't see the reason to test for an empty list here.

2020-12-18 09:06 UTC, Tanya-Solyanik requested changes
Please wait with this change, I need to verify if we should sent set top message only after we validated that the item is not shown already.

2020-12-18 11:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                if (!_owningComboBox.IsHandleCreated || _owningComboBox.Items.Count == 0)
>  I.e. what happens if CB_SETTOPINDEX attempts to set index to -1?

`SendMessageW` returns "-1" as the result and do nothing.

> I don't see the reason to test for an empty list here.

I agree, I'll remove this.

2020-12-18 11:59 UTC, vladimir-krestov commented
> Please wait with this change, I need to verify if we should sent set top message only after we validated that the item is not shown already.

I think, you are right and we need to check if an item is visible and don't send a message, because a native ListBox works like that.

2020-12-20 00:56 UTC, Tanya-Solyanik requested changes

2020-12-20 00:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                User32.SendMessageW(_owningComboBox, (User32.WM)User32.CB.SETTOPINDEX, (IntPtr)currentIndex);
MSAAProxy was scrolling only if the item had not been already visible, we should match that behavior.

2020-12-21 04:58 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                User32.SendMessageW(_owningComboBox, (User32.WM)User32.CB.SETTOPINDEX, (IntPtr)currentIndex);
Testing different cases...

2020-12-21 05:28 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                User32.SendMessageW(_owningComboBox, (User32.WM)User32.CB.SETTOPINDEX, (IntPtr)currentIndex);
Thank you! Added `IntersectsWith` above

2020-12-21 21:04 UTC, Tanya-Solyanik reviewed
Looks good, I have a minor comment about checking the zero return value from MapWindowPoints. 
What is your plan for unit tests?

For the bounds change, please also add a manual test to `WinFormsControls` app

```
  internal class MyCombo : ComboBox
    {
        public MyCombo() : base()
        {
            DrawMode = DrawMode.OwnerDrawVariable;
            DropDownStyle = ComboBoxStyle.DropDownList;
            MaxDropDownItems = 7;
            ItemHeight = 13;
            IntegralHeight = false;

            for (int i = 0; i < 10; i++)
            {
                Items.Add($"Item {i}");
            }

            SelectedIndex = 0;
        }

        protected override void OnMeasureItem(MeasureItemEventArgs e)
        {
            e.ItemHeight = 13 + e.Index * 5;
        }

        protected override void OnDrawItem(DrawItemEventArgs e)
        {
            e.DrawBackground();

            using var brush = new SolidBrush(e.ForeColor);

            e.Graphics.DrawString(
                Items[e.Index].ToString(),
                e.Font,
                brush,
                e.Bounds);

            e.DrawFocusRectangle();
        }
    }
```

2020-12-21 22:59 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                        User32.MapWindowPoints(listHandle, IntPtr.Zero, ref itemRect, 2) == 0)
This is unreadable, there are multiple method calls and code paths. Break it up.

2020-12-21 23:00 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    if (User32.SendMessageW(listHandle, (User32.WM)User32.LB.GETITEMRECT,
A single PR is fine.

2020-12-21 23:00 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    if (User32.SendMessageW(listHandle, (User32.WM)User32.LB.GETITEMRECT,
A single PR with distinct commits is fine.

2020-12-21 23:05 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                        (IntPtr)currentIndex, ref itemRect).ToInt32() == User32.LB_ERR ||
❗  `.ToInt32()` will overflow on x86!

2020-12-21 23:05 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    if (User32.SendMessageW(listHandle, (User32.WM)User32.LB.GETITEMRECT,
Will do 2 commits in this PR

2020-12-21 23:06 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                        (IntPtr)currentIndex, ref itemRect).ToInt32() == User32.LB_ERR ||
Should I use `(int)(long)` cast here?

2020-12-24 21:08 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                    if (User32.SendMessageW(listHandle, (User32.WM)User32.LB.GETITEMRECT,
Added 3 commits (+2 temporary for review).
- Add ScrollItemPattern + tests
- Fixed Bounds + tests
- Add a UI test case to test ComboBoxes with scrollbars and different heights items

2020-12-24 21:09 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
> +                int currentIndex = _owningComboBox.Items.IndexOf(_owningItem);
https://github.com/dotnet/winforms/issues/4392

2020-12-24 21:19 UTC, vladimir-krestov commented
I didn't add a unit test that checks `ScrollIntoView` code path when the owning combobox doesn't have a Handle because `ComboBoxItemAccessibleObject` can't exist in this case.

2020-12-29 23:58 UTC, Tanya-Solyanik reviewed
Nice manual test!
In the unit tests, please consider introducing helper functions to avoid copy/pasted initialization and verification code where possible. 
Also the magic number 7  might stop working at some point on some machines. Consider re-doing tests to actually calculate the if the item is visible in the test body.

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +            if (e.Index < 0)
I don't think it's possible that the index in the event args is off. But if you want to check bounds, please check the upper bound as well.

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            comboBox.Items.AddRange(new string[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" });
Please run Ctrl-K + Ctrl-D on this file to apply the default formatting. I think there should not be a space between the brace and the first or last item.

Also I think `new string[]` can be simplified to `new[]`.

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +                result &= itemAccessibleObject.IsPatternSupported(UiaCore.UIA.ScrollItemPatternId);
I think that this operator short-circuits when `result` is `false`, so once you hit an item that does not support this pattern, you are no longer testing the rest of the items anyway. Also you don't report the failed items. So I don't see the reason to continue once the bad item is encountered. 
I think   
`Assert.True(itemAccessibleObject.IsPatternSupported(UiaCore.UIA.ScrollItemPatternId));`
is cleaner and will show the first failed item.

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +                result &= (bool)itemAccessibleObject.GetPropertyValue(UiaCore.UIA.IsScrollItemPatternAvailablePropertyId);
Assert.True(itemAccessibleObject.GetPropertyValue(UiaCore.UIA.IsScrollItemPatternAvailablePropertyId));

Or consider factoring out the foreach loop into a helper function and share it with the above test.

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +        public static IEnumerable<object[]> ComboBoxItemAccessibleObject_ScrollIntoView_DoNothing_IfControlIsNotEnabled_TestDate()
TestDate-> TestData

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            using ComboBox comboBox = new ComboBox();
FYI - in this context, i.e. explicit type in this declaration,  `new ComboBox()` could be simplified to `new()`. This applies to other changes in this file as well.

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            int topIndex = unchecked((int)(long)User32.SendMessageW(comboBox, (User32.WM)User32.CB.GETTOPINDEX));
Consider naming this variable `actual` or `actualTopIndex`

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            itemAccessibleObject.ScrollIntoView();
Consider formatting tests so that code that performs the main action is surrounded by empty lines. I.e. add blank line above and below the `ScrollIntoView` call.

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +                // In the tested comboboxes only 7 items are visible. It needs to scroll to see the rest
FYI - this assumes certain font height and HDPI scaling on the test machine. It might be more reliable to actually calculate if drop down rectangle intersects with the item rectangle. Another advantage of 'intersectsWith` approach is that you'd have a single test for the "do nothing" and "scroll" tests, instead of copy-pasting the test code.

2020-12-29 23:58 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +                // Get an index of the first item that is visible if to scroll a combobox to the bottom
if to scroll a combobox to the bottom -> if dropdown is scrolled to the bottom?

2020-12-30 08:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +            if (e.Index < 0)
I got "-1" Index a couple of times in my previous test app (not here), so I added this check. I would check the bounds. Thanks, I added upper bound as well

2020-12-30 09:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            comboBox.Items.AddRange(new string[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" });
1) The default formatting is applying when I'm saving files
2) `Ctrl-K` + `Ctrl-D` is my reflex 😊 (doing it after almost every change)
     So, here is the result of the default VS formatting.
     
Thanks, I simplified to `new[]`

2020-12-30 09:58 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            comboBox.Items.AddRange(new string[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" });
![DkJ8950mEt](https://user-images.githubusercontent.com/49272759/103344128-b3fe2e80-4a9e-11eb-8b3d-aba30a776993.gif)

2020-12-30 10:01 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +                result &= itemAccessibleObject.IsPatternSupported(UiaCore.UIA.ScrollItemPatternId);
Thank you, I agree, your approach is more readable. Have reworked it

2020-12-30 10:05 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +                result &= (bool)itemAccessibleObject.GetPropertyValue(UiaCore.UIA.IsScrollItemPatternAvailablePropertyId);
I think put `Assert` inside the cycle is more readable.
I think we don't need to create a new function for the sake of 2 places and 3 lines. It will complicate the tests

2020-12-30 10:12 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            using ComboBox comboBox = new ComboBox();
Yes, it is possible, but I think this change won't be consistent with the rest unit tests because many test files have explicit definitions of objects.
Actually, it may be changed later as a code refactoring. But not now.

2020-12-30 10:18 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            itemAccessibleObject.ScrollIntoView();
Make sense

2021-01-05 07:59 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +        private void ComboBoxesWithScrollBars_Load(object sender, EventArgs e)
Don't create an event handler, override `OnLoad` instead

2021-01-05 07:59 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +            useDifferentHeightsCheckBox3.CheckedChanged += useDifferentHeightsCheckBox3_CheckedChanged;
Any specific reason not to add them via the designer?

2021-01-05 07:59 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +                "\nIt is impossible to return DropDownList style for the combobox");
ditto

2021-01-05 10:23 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +            useDifferentHeightsCheckBox3.CheckedChanged += useDifferentHeightsCheckBox3_CheckedChanged;
1) If we add these event handlers in the designer, they will be invoked when we set the values above. We don't need these redundant invocations, I guess. We should invoke the handler when a user changes the values.
2) It's more readable, in my opinion. And it doesn't depend on the designer changes.

2021-01-05 11:29 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +        private void ComboBoxesWithScrollBars_Load(object sender, EventArgs e)
I can, but are there any specific reasons?

2021-01-05 18:36 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +                "\nIt is impossible to return DropDownList style for the combobox");
No, thanks. Moved it to the designer

2021-01-05 18:47 UTC, vladimir-krestov commented
I have changed the UI test app implementation in accordance with the `Designer`. Steps:
1) Created a new .NET 6.0 app
2) Copied my test code and pasted it to the new .NET 6.0 app
3) Opened the `Designer` in this app
4) Made a little change to make the `Designer` change the implementation as it wants
5) Saved the `Designer` changes and moved them to my test implementation

Now you can see the implementation created by the `Designer` in the `ComboBoxesWithScrollBars.Designer.cs` file.
All strange changes are its work.

2021-01-06 04:09 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +        private void ComboBoxesWithScrollBars_Load(object sender, EventArgs e)
Yes, event handlers cause extra allocations. Overriding a method doesn't.

2021-01-06 04:11 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +            useDifferentHeightsCheckBox3.CheckedChanged += useDifferentHeightsCheckBox3_CheckedChanged;
It is worth adding a comment explaining just that.

2021-01-06 04:16 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
> +            comboBox1.DropDownHeight = (int)((NumericUpDown)sender).Value;
```suggestion
            comboBox1.DropDownHeight = changeDDH_UpDown1.Value;
```

In fact, since there's only one instruction here, and the handler is exclusive to `changeDDH_UpDown1`, this all can be inlined, thus drastically reducing the code:
```cs
changeDDH_UpDown1.ValueChanged += (s, e) => comboBox1.DropDownHeight = changeDDH_UpDown1.Value;
```

ditto below

2021-01-06 13:05 UTC, vladimir-krestov commented
Waiting for results from CTI

2021-01-07 21:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +                if (e.Index < 0)
Consider testing the upper bound for sanity

2021-01-07 21:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +        public void ComboBoxItemAccessibleObject_Bounds_ReturnsCorrect_ForVisibleItems_IfComboBoxIsScrollable(ComboBoxStyle comboBoxStyle, int itemIndex, Point expectedPosition)
Why do you restrict this and the next test to visible items only? Bounds rectangle should be accurate even if the item is not visible. These tests would be applicable to OffScreen and Visible properties.

2021-01-08 09:31 UTC, vladimir-krestov commented
Testers approved the fix ✔️

2021-01-08 10:10 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +        public void ComboBoxItemAccessibleObject_Bounds_ReturnsCorrect_ForVisibleItems_IfComboBoxIsScrollable(ComboBoxStyle comboBoxStyle, int itemIndex, Point expectedPosition)
You are right. I wanted to prevent failing these tests after fixing Bounds for invisible items. But it will be another story and it may be fixed in another way.
Thank you, I have fixed it, and now the tests work for all items.

2021-01-08 21:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +        public void ComboBoxItemAccessibleObject_Bounds_ReturnsCorrect_ForVisibleItems_IfComboBoxIsScrollable(ComboBoxStyle comboBoxStyle, int itemIndex, Point expectedPosition)
I don't think we should return an empty rectangle to invisible items. This is not the behavior we see in other frameworks. Users(or automation tests) who work with applications that use both winforms and win32 controls would not expect that.

2021-01-08 21:36 UTC, Tanya-Solyanik approved these changes

2021-01-08 21:36 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +        public void ComboBoxItemAccessibleObject_ScrollIntoView_DoExpected(ComboBoxStyle comboBoxStyle, bool scrollingDown, int itemIndex, int itemsCount)
nit: `DoExpected` is not a descriptive name. All tests are supposed to do what is expected :) I would say `ComboBoxItemAccessibleObject_ScrollIntoView_EnsureVisible`

2021-01-08 21:36 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            int itemWidth = comboBoxStyle == ComboBoxStyle.Simple ? 79 : 81;
Could you please add a comment about where these items are coming from?

2021-01-11 15:08 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            int itemWidth = comboBoxStyle == ComboBoxStyle.Simple ? 79 : 81;
Thanks, I added little comments.
Actually, we get items rectangles from Windows.
It returns to us different widths values depending on a combobox drop-down style

2021-01-11 18:08 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            int itemWidth = comboBoxStyle == ComboBoxStyle.Simple ? 79 : 81;
I meant `where these widths are coming from?`

Are you sure it is based on the style and not on the DPI or font? I think it's sufficient to test that all widths are the same rather than are equal to a specific number.

2021-01-12 02:30 UTC, RussKie approved these changes

2021-01-12 02:34 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
> +            int itemWidth = comboBoxStyle == ComboBoxStyle.Simple ? 79 : 81;
All tests are currently run at 100% and with styles enabled. We currently have no ability to run automated tests with styles disabled.
In tests we currently have hardcoded values for styles on/off scenarios, so this is inline with the rest of tests. Not having these values hardcoded is probably not a bad idea, but this should be done separately and across all tests at the same time.

2021-01-12 02:34 UTC, merged