Fix NotifyIcon.Text limits text to 63 characters, but should be 127
dotnet/winforms pull request #4363
Opened 2020-12-15 02:03 UTC by paul1956

Fixes #4361

## Proposed changes

- Change character limit for text in NotifyIcon.Text from 63 to 127 characters.

## Customer Impact

- This matches the Windows Control that was changed in an OS released before .Net is supported.  
- 

## Regression? 

- No

## Risk

- Very low, all tests updated and all supported OS's support 127.

## Test methodology 

- Update all tests to of this code to use 127 instead of 63
- 
- 

## Accessibility testing 
The underlying windows control supports 127 characters and the testing now uses 127 allowing the text to support longer descriptions.  

## Test environment(s) 

- 5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]

2020-12-15 02:24 UTC, willibrandon commented
`NotifyIcon_Text_SetLongValue_ThrowsArgumentOutOfRangeException` test will need to updated as well.

2020-12-15 02:42 UTC, paul1956 commented
@willibrandon thanks good catch, fixed.

2020-12-15 07:43 UTC, RussKie requested changes
👍

2020-12-15 07:43 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
>                          throw new ArgumentOutOfRangeException(nameof(Text), value, SR.TrayIcon_TextTooLong);
The text of the error must be updated as well.

2020-12-15 07:43 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
> +                    if (value != null && value.Length > 127)
Suggest making it an `internal const`, and reference it everywhere.

2020-12-15 12:55 UTC, paul1956 commented on src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
>                          throw new ArgumentOutOfRangeException(nameof(Text), value, SR.TrayIcon_TextTooLong);
Fixed

2020-12-15 13:06 UTC, paul1956 commented on src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
> +                    if (value != null && value.Length > 127)
I make it "internal const int MaxNotifyIconTextSize = 127;"  but the line is in 2 places.

2020-12-15 23:59 UTC, RussKie commented on src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
> +        <target state="translated">텍스트 길이는 128 자 미만이어야 합니다.</target>
Looks like an extra space snuck in after the number

2020-12-15 23:59 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
> +        internal const int MaxNotifyIconTextSize = 127;
Since the const is in `NotifyIcon` having "NotifyIcon" again in the name doesn't add much value. 
```suggestion
        internal const int MaxTextLength = 127;
```

2020-12-15 23:59 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NotifyIconTests.cs
> +        internal const int MaxNotifyIconTextSize = 127;
We should be able to reference `NotifyIcon.MaxTextLength` here since it is marked as `internal` (that was the point of making it internal).

2020-12-16 00:17 UTC, paul1956 commented on src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
> +        internal const int MaxNotifyIconTextSize = 127;
Fixed

2020-12-16 00:18 UTC, paul1956 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NotifyIconTests.cs
> +        internal const int MaxNotifyIconTextSize = 127;
I noticed that but didn't know the correct way to do it.
 Thanks for the solution.

2020-12-16 00:20 UTC, paul1956 commented on src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
> +        <target state="translated">텍스트 길이는 128 자 미만이어야 합니다.</target>
I don't read Korean but all the other languages have a space after the number. I added one here to match what was there.

2020-12-16 00:48 UTC, RussKie commented on src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
> +        <target state="translated">텍스트 길이는 128 자 미만이어야 합니다.</target>
I don't either, but trust our loc team knows what they do. So if there wasn't a space we shouldn't add one.
Please revert.

2020-12-16 00:48 UTC, RussKie approved these changes

2020-12-16 00:50 UTC, merged

2020-12-16 00:51 UTC, RussKie commented
Thank you

2020-12-16 01:05 UTC, RussKie commented
Docs: https://github.com/dotnet/docs/issues/22018

2020-12-16 01:39 UTC, paul1956 commented on src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
> +        <target state="translated">텍스트 길이는 128 자 미만이어야 합니다.</target>
It is fixed in what was merged. Just highlighting the issue.