Enable nullability in Control.AmbientProperty, Control.Ime and Contro…
dotnet/winforms pull request #4396
Opened 2020-12-20 08:30 UTC by gpetrou

…l.ThreadMethodEntry

## Proposed changes

- Enable nullability in Control.AmbientProperty, Control.Ime and Control.ThreadMethodEntry.

2020-12-21 03:26 UTC, RussKie requested changes

2020-12-21 03:26 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.AmbientProperty.cs
> +            internal AmbientProperty(string? name, Ole32.DispatchID dispID)
I don't think this is correct, there are only 3 callsites and none of them supply `null`.

2020-12-21 03:26 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs
> +            internal ThreadMethodEntry(Control caller, Control marshaler, Delegate method, object[] args, bool synchronous, ExecutionContext? executionContext)
```suggestion
            internal ThreadMethodEntry(Control caller, Control marshaler, Delegate? method, object[]? args, bool synchronous, ExecutionContext? executionContext)
```

![image](https://user-images.githubusercontent.com/4403806/102736041-1157f880-4398-11eb-8f41-33fc56bd424f.png)
![image](https://user-images.githubusercontent.com/4403806/102735988-ed94b280-4397-11eb-8a28-8105d6f0de1a.png)

2020-12-21 03:26 UTC, RussKie commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> +System.Windows.Forms.Control.ImeModeChanged -> System.EventHandler!
This is a non-obvious change. How did we arrive to it?

2020-12-21 05:02 UTC, gpetrou commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> +System.Windows.Forms.Control.ImeModeChanged -> System.EventHandler!
I could not find cases where it could be null. Should I change it?

2021-01-27 00:20 UTC, RussKie submitted a review, later dismissed

2021-01-27 00:41 UTC, RussKie commented
Please rebase and resolve the conflict.

2021-01-27 23:54 UTC, RussKie approved these changes

2021-01-27 23:54 UTC, merged

2021-01-27 23:55 UTC, RussKie commented
Thank you