Adding the ability to get keyboard toolTips for TabPages of a TabControl
dotnet/winforms pull request #4421
Opened 2021-01-01 14:46 UTC by vladimir-krestov

Fixes #2717
Related Issue #4305
Based on PR #2719. But the changes were significantly reworked so I have created this new PR
Most of review points from #2719 were fixed here

## Proposed changes

- Notify `KeyboardToolTipStateMachine` about getting and losing a focus
- Inverted incorrect dependencies inside `ToolTip` class

## Customer Impact

- A user can see a TabPage toolTip when using a keyboard

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before
- TODO

### After
- TODO

## Test methodology 

- Manual testing
- Unit tests
- CTI

## Test environment(s) 
- .NET Version: 6.0.0-alpha.1.20554.7
- Microsoft Windows [Version 10.0.19042.685]

2021-01-04 04:01 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        }
I don't believe these method names are consistent with the established naming guidelines, i.e. "on"-methods are helper methods to raise associated events: `OnXyz(XyzEventArgs)`.
These methods, however, don't look like they raise events or take event args.

2021-01-04 04:07 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +            if (toolTip != null)
```suggestion
            if (toolTip is not null)
```
Ditto below

2021-01-04 04:07 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +            if (toolTip != null)
Invert to reduce nesting

2021-01-06 00:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
> +            // this tooltip always.
👍

2021-01-06 00:33 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
> +            User32.SetCursorPos(x, y);
This feel brittle. With styles on/off, dpi scaling, etc. - how can we be sure the mouse is hovering the expected control?

2021-01-06 00:33 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
> +            Assert.True(toolTip.Handle != IntPtr.Zero); // A workaroung to create the toolTip native window Handle
In other places we do either `control.CreateHandle()` or `Assert.NotEqual(IntPtr.Zero, control.Handle)`
Let's be consistent

2021-01-06 00:33 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
> +        public void ToolTip_RemoveAll_Invokes_RemoveToolTip() // Doesn't work
Let's chat

2021-01-06 04:09 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
> +            // this tooltip always.
Just copied from the removed `ToolTip.cs` implementation (line 671)

2021-01-06 04:44 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        }
I agree, renamed them to `RemoveToolTip` and `SetToolTip`

2021-01-06 04:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
> +            Assert.True(toolTip.Handle != IntPtr.Zero); // A workaroung to create the toolTip native window Handle
We use `CreateControl()` in other tests
`ToolTip` is not a `Control`, it's a `Component` and doesn't have `CreateControl()` method
`ToolTip` has **private** `CreateHandle()` and **private** `RecreateHandle()`, so `Assert.NotEqual(IntPtr.Zero, control.Handle)` is the best way to create its Handle without reflection.
Thank you for the point!

2021-01-06 04:58 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
> +        public void ToolTip_RemoveAll_Invokes_RemoveToolTip() // Doesn't work
It's an early prototype and will be reworked later

2021-01-06 06:12 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
> +            User32.SetCursorPos(x, y);
I have reworked the test to get 100% correct coordinates, but the test became more complicated

2021-01-06 06:24 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
> +            User32.SetCursorPos(x, y);
4f335837ef2281f8167f20b1421b62e2ebf96d93

2021-02-18 10:47 UTC, SergeySmirnov-Akvelon reviewed
Nice job!!! I have added several review points, most of which are cosmetic

2021-02-18 10:47 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +            }
This construct with a validation and tooltip display occurs several times. I think we can take it out in a separate method

2021-02-18 10:47 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +    public class TabPage : Panel, IKeyboardToolTip
Perhaps it is worth moving the implementation of the "IKeyboardToolTip" interface into a separate class

2021-02-18 10:47 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
> +        public void TabPage_IsHoveredWithMouse_ReturnsExpected(IsHoveredWithMouseTestMousePosition position, bool expected)
I think this test is too complex. It might be worth splitting it into multiple tests

2021-02-18 10:47 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBaseTests.cs
> +            string actualButton = toolTip.GetToolTip(upDownBase._upDownButtons);
It is not obvious from the names of the variables that it is a strings

2021-02-18 10:47 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
> +            string actual = ((IKeyboardToolTip)page).GetCaptionForTool(toolTip);
Please add a blank before the "Assert"

2021-02-18 10:47 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
> +            Assert.Equal(text, actual);
ditto

2021-02-18 10:47 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
> +            Assert.Null(actual);
ditto

2021-02-18 10:47 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +            if (ParentInternal is TabControl tabControl && tabControl.SelectedIndex >= 0)
Why are you using a `SelectedIndex` instead of a `SelectedTab`?

2021-02-19 07:27 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +    public class TabPage : Panel, IKeyboardToolTip
Thanks, I have reworked Control class and created virtual methods instead of the implementation of the interface here.

2021-02-19 07:35 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +            if (ParentInternal is TabControl tabControl && tabControl.SelectedIndex >= 0)
I send the index to `tabControl.GetTabRect` method next and I make sure its value is correct to avoid `ArgumentOutOfRangeException`

2021-02-19 17:52 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
> +        public void TabPage_IsHoveredWithMouse_ReturnsExpected(IsHoveredWithMouseTestMousePosition position, bool expected)
All test cases have the same implementation. I have reworked the test to make it simpler

2021-03-01 23:47 UTC, RussKie requested changes
👍 with few nits

2021-03-01 23:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        private protected virtual bool IsHoveredWithMouse() => ClientRectangle.Contains(PointToClient(MousePosition));
[nit] incorrect placement

2021-03-01 23:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        private protected virtual string GetCaptionForTool(ToolTip toolTip)
[nit] incorrect placement

2021-03-01 23:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        }
[nit] incorrect placement

2021-03-01 23:47 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
> +        public void TabPage_IsHoveredWithMouse_ReturnsExpected(int xPosition, int yPosition, bool expectedResult)
As discussed let's move this test in to the maui project as it manipulates the mouse, a system-wide singleton.
It is not entirely impossible that one day this test may become flaky because some other test decided to manipulate the mouse as well.

2021-03-02 18:45 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +        private void NotifyAboutFocusState(TabPage selectedTab, bool gotFocus)
Make sense, let's do like that, thanks.

2021-03-02 18:53 UTC, vladimir-krestov commented
Working on test issues...

2021-03-03 08:44 UTC, vladimir-krestov commented
Hi @merriemcgaw, could you please take a look at thу following cases:

We have a `TabControl` with 2 pages. 
`TabPage` has `ToolTipText` property that sets internal toolTip for the "tab".
Also, we can set an external `ToolTip` for a "page".
![image](https://user-images.githubusercontent.com/49272759/109773483-50b08a00-7c10-11eb-88c4-dc2176c8c542.png)

After my fix we have the following cases:

- Case 1:
`ToolTipText` is set for the `tabPage21` - "**Internal tooltip for TabPage1**" (an external toolTip is set too with "**External tooltip for TabPage1**" text) .
An external ToolTip is set (`toolTip.SetToolTip(...)`) for `tabPage22` (`ToolTipText` is not set) - "**External tooltip for TabPage2**".
So, keyboard toolTips look like that (using keyboard arrows):
![HEfVSt6qni](https://user-images.githubusercontent.com/49272759/109774672-aafe1a80-7c11-11eb-8fe7-0799703e3dbf.gif)

     Here `tabPage21` shows `ToolTipText`, not the external ToolTip text because `ToolTipText` has priority for keyboard.
     **Question 1:** is it correct?
- Case 2:
An external ToolTip is set for `tabPage22` (using the mouse):
![zKNQyYfaOx](https://user-images.githubusercontent.com/49272759/109775574-b7cf3e00-7c12-11eb-9afd-430e90da864f.gif)
     
     There is no a toolTip if the mouse hovers on "tab", and a toolTip appears if the mouse hovers on "page". This is native behavior. 
     But I made, that "tab" will show the toolTip if we select it using a keyboard:
![KDu91DCHpx](https://user-images.githubusercontent.com/49272759/109776191-62dff780-7c13-11eb-99f5-360f655501e2.gif)

     **Question 2:** is it correct?

- Case 3:
An external ToolTip is set for the TabControl - "External tooltip for TabControl":
![fo1mcCANzb](https://user-images.githubusercontent.com/49272759/109777464-cae30d80-7c14-11eb-8d56-a5f0f3b30a12.gif)

    Here the toolTip doesn't appear if the mouse hovers on "page". And the toolTip appears for "tabs" only. This is native behavior.
     I decided to make the following for keyboard toolTips:
     1) the toolTip doesn't appear if we select some tabs
     2) the toolTip appears if we focus on the TabControl from another one:
     ![5ePssuRLl6](https://user-images.githubusercontent.com/49272759/109778159-8c9a1e00-7c15-11eb-965a-07f42a3aac4c.gif)
     
     **Question 3:** is it correct?

2021-03-09 10:47 UTC, vladimir-krestov commented
Testers approved the fix ✔️

2021-03-10 09:55 UTC, RussKie requested changes
🚀  with few nits

2021-03-10 09:55 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +            List<Rectangle> neighbords = new List<Rectangle>();
```suggestion
            List<Rectangle> neighbors = new List<Rectangle>();
```

2021-03-10 09:55 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +            if (ParentInternal is TabControl tabControl && tabControl.SelectedIndex >= 0)
Probably worth leaving a comment?

2021-03-10 09:55 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            if (!ShowNodeToolTips || toolTip is null)
```suggestion
            if (toolTip is null || !ShowNodeToolTips)
```

2021-03-10 09:55 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTabControlTests/MauiTabControlTests.cs
> +using System.Drawing;
[nit] these seem to be out of order. Right click in VS should fix it

2021-03-10 09:55 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTabControlTests/MauiTabControlTests.cs
> +            Application.Run(new MauiTabControlTests(args));
Are we running with visual style on or off?

2021-03-10 12:34 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTabControlTests/MauiTabControlTests.cs
> +            Application.Run(new MauiTabControlTests(args));
We run it without visual styles here and in the rest places.
We use RemoteExecutor to run an Application with visual styles.
If we need it we should rework all tests.
Can I keep it here as is, like as in the rest maui tests?

2021-03-10 23:36 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTabControlTests/MauiTabControlTests.cs
> +            Application.Run(new MauiTabControlTests(args));
> We use RemoteExecutor to run an Application with visual styles.

We don't since #4197

2021-03-10 23:37 UTC, RussKie commented
Have you pushed the changes?

2021-03-16 21:41 UTC, RussKie approved these changes

2021-03-16 21:42 UTC, merged