[Accessibility] Tree node has no keyboard tooltip #4439
dotnet/winforms pull request #4466
Opened 2021-01-14 10:28 UTC by SergeySmirnov-Akvelon

Fixes #4439

## Proposed changes
- Added support for "IKeyboardToolTip" interface in "TreeNode" class.
- Added logic to show the tooltip for the focused TreeNode when the user switches between items 

## Customer Impact

## Regression? 
- No

## Risk

- Minimal

## Test methodology 
- Manually 

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core 5.0.100-rc.2.20479.15

2021-01-26 18:09 UTC, vladimir-krestov reviewed
Good work! But it needs to be reworked

2021-01-27 06:48 UTC, vladimir-krestov reviewed
Additional points

2021-01-27 06:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +            }
I would move it below. And I don't think that we need to do the cycle through children because we will be here when invoking line **2055** (`children[i].Remove(false);`)
And we check if TreeView is null in **2076** line (`if (tv is null || tv.IsDisposed)`), I would move the unhooking after this check only for the current node

2021-01-27 06:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        bool IKeyboardToolTip.AllowsChildrenToShowToolTips() => true;
Consider this way:
```suggestion
        bool IKeyboardToolTip.AllowsChildrenToShowToolTips() => TreeView is not null && TreeView.ShowNodeToolTips;
```

2021-01-27 06:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        bool IKeyboardToolTip.AllowsToolTip() => true;
ditto as above

2021-01-27 06:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        string IKeyboardToolTip.GetCaptionForTool(ToolTip toolTip) => treeView.ShowNodeToolTips ? ToolTipText : treeView.ControlToolTipText;
I think, it is not correct. The mouse toolTip works differently. It doesn't appear for nodes if `ShowNodeToolTips` is **false**.
So, I would prefer to see here `ToolTipText` only. `AllowsToolTip()` decides to show a toolTip or not.

2021-01-27 06:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        Rectangle IKeyboardToolTip.GetNativeScreenRectangle() => BoundsToScreen(Bounds);
We can use the exist method and we don't need to create one more method.
```suggestion
        Rectangle IKeyboardToolTip.GetNativeScreenRectangle() => treeView.RectangleToScreen(Bounds);
```

2021-01-27 06:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +            }
Consider using `treeView.RectangleToScreen(Bounds)`

2021-01-27 06:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        bool IKeyboardToolTip.CanShowToolTipsNow() => treeView is not null;
I would use `TreeView` property here and in other places that you have added, because `treeView` field will be null for sub-nodes. It will have some value only after `TreeView` property getting externally. But it may not happen. So, to be sure, that we use a correct treeView instance please switch it to the property using everywhere.

2021-01-27 06:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        private Rectangle BoundsToScreen(Rectangle bounds)
I would remove this method and use `TreeView.RectangleToScreen(Bounds)`
Moreover, using `treeView` field that can be **null** for sub-nodes may lead to NRE.

2021-01-27 06:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +        internal string ControlToolTipText => controlToolTipText;
Please remove it, due to my comment for TreeNode

2021-01-29 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            KeyboardToolTip.Dispose();
No, since `TreeView` creates and owns `KeyboardToolTip` it has to dispose it as well when the treeview is being disposed of.

2021-01-29 05:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +        internal ToolTip KeyboardToolTip = new ToolTip { ReshowDelay = 500, InitialDelay = 500 };
This looks like a field, and must reside at the top with the rest of fields, and match the naming guidelines

2021-01-29 05:26 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            }
`GetAllNodes` returns the `rootNode` and its children

2021-01-29 05:29 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            }
Looking at this snippet of code it is totally not obvious and unexpected.
I suggest rewriting this as something like this:
```cs
            foreach (TreeNode rootNode in Nodes)
            {
                KeyboardToolTipStateMachine.Instance.Unhook(rootNode, KeyboardToolTip);
                foreach (TreeNode childNode in rootNode.GetChildNodes())
                {
                    KeyboardToolTipStateMachine.Instance.Unhook(childNode, KeyboardToolTip);
                }
            }
```

2021-01-29 05:30 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +        internal ToolTip KeyboardToolTip = new ToolTip { ReshowDelay = 500, InitialDelay = 500 };
1) It used in `TreeNodeCollection` - a separate class, not nested in TreeView, needs to use `internal` modifier
2) If so, when do we use a field with the `internal` modifier? I think, we should keep it as a property

2021-01-29 05:31 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            }
Actually, you are right, thanks

2021-01-29 05:32 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +        internal ToolTip KeyboardToolTip = new ToolTip { ReshowDelay = 500, InitialDelay = 500 };
If this is a property then it should be like this:
```suggestion
        internal ToolTip KeyboardToolTip { get; } = new ToolTip { ReshowDelay = 500, InitialDelay = 500 };
```

2021-01-29 05:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +        internal ToolTip KeyboardToolTip = new ToolTip { ReshowDelay = 500, InitialDelay = 500 };
Also we should avoid magic numbers. Where did "500" come from?

2021-01-29 05:33 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +        internal ToolTip KeyboardToolTip = new ToolTip { ReshowDelay = 500, InitialDelay = 500 };
Sure, thanks
@SergeySmirnov-Akvelon, please rework it

2021-01-29 05:34 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +        internal ToolTip KeyboardToolTip = new ToolTip { ReshowDelay = 500, InitialDelay = 500 };
I would remove "500" magic numbers and just use a default `ToolTip`

2021-02-04 09:23 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
>          }
Using the recursion we maybe creating quite a few instances of `List<TreeNode>`.
Maybe worth considering a slightly different implementation where we create a single `List<TreeNode>` and pass it in instead.
E.g.
```cs
        internal void GetChildNodes(List<TreeNode> nodes)
        {
            foreach (TreeNode child in Nodes)
            {
                nodes.Add(child);
                child.GetChildNodes(nodes);
            }
        }
```

2021-02-08 08:17 UTC, RussKie requested changes
Tests for the changes? E.g. for `GetToolInfoWrapper`, `GetChildNodes`

2021-02-08 08:17 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                wrapper.Info.lpszText = (char*)(-1);
A comment?

2021-02-08 11:53 UTC, vladimir-krestov reviewed
Little refactoring notes

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> +        private protected Control TopLevelControl
It is not necessary now

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> +        private protected virtual unsafe ToolInfoWrapper<Control> GetTOOLINFO(Control control, string caption)
Please remove it too because it is not necessary

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.IKeyboardToolTip.cs
> +        Rectangle IKeyboardToolTip.GetNativeScreenRectangle() => TreeView.RectangleToScreen(Bounds);
TreeView can be null if a node doesn't belong to a TreeView
Please consider adding null-check here

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.IKeyboardToolTip.cs
> +        bool IKeyboardToolTip.HasRtlModeEnabled() => TreeView.RightToLeft == RightToLeft.Yes;
ditto - TreeView null-check
Please check if it is possible to get null here at all

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.IKeyboardToolTip.cs
> +        bool IKeyboardToolTip.IsHoveredWithMouse() => TreeView.AccessibilityObject.Bounds.Contains(Control.MousePosition);
ditto

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        }
A super unobvious method. I would say it is not correct. We shouldn't send a list to "GET" method and change it inside. It's not good. You create a list, send it as an argument and change it inside the method. 
![image](https://user-images.githubusercontent.com/49272759/107214815-88fee700-6a1b-11eb-9bb3-0d6af009620f.png)

I would rework it to:
```suggestion
        internal List<TreeNode> GetChildNodes()
        {
            List<TreeNode> nodes = new List<TreeNode>();

            foreach (TreeNode child in Nodes)
            {
                nodes.Add(child);
                nodes.AddRange(child.GetChildNodes());
            }

            return nodes;
        }
```

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
> +                foreach (TreeNode treeNode in nodes)
In addition to the comment above:

```suggestion
                foreach (TreeNode treeNode in node.GetChildNodes())
```

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
> +                foreach (TreeNode treeNode in nodes)
ditto

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +                foreach (TreeNode node in nodes)
ditto

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            List<TreeNode> result = new List<TreeNode>();
Please remove it

2021-02-08 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> -            if (associatedControl is TreeView treeView && treeView.ShowNodeToolTips)
Could you please say why did you remove this check here?
How will it affect setting a toolTip to a TreeView?

2021-02-09 00:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.IKeyboardToolTip.cs
> +        Rectangle IKeyboardToolTip.GetNativeScreenRectangle() => TreeView.RectangleToScreen(Bounds);
Must be `#nullable enable`

2021-02-09 00:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        }
I have requested this change in https://github.com/dotnet/winforms/pull/4466#discussion_r570066332

Your version will be allocating (possibly a lot of) new lists. With the current implementation we're allocating only once (though we will be resizing).

2021-02-09 00:59 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            List<TreeNode> result = new List<TreeNode>();
Good catch, this is unused. However `nodes` on line:3119 is more of a concern - we're allocating in a loop.
So this line must stay, but line:3119 must go.

2021-02-09 07:22 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.IKeyboardToolTip.cs
> +        bool IKeyboardToolTip.HasRtlModeEnabled() => TreeView.RightToLeft == RightToLeft.Yes;
I think that TreeView can be null only when accessed from the code. In general, for the tooltip to be displayed, the user should set focus to the TreeNode. This is possible only if the TreeView is displayed and the TreeNode is in it. In this case, the TreeView can't be null.

2021-02-09 07:36 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        }
Yes, I agree, we don't need billions of new lists. We decided to rename the method and add a comment to be consistent with common design patterns. In particular, this method should not be "GET"

2021-02-09 07:55 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> -            if (associatedControl is TreeView treeView && treeView.ShowNodeToolTips)
This condition was changed while investigating the interaction between external tooltip and keyboard navigation. Since we do not display an external tooltip in keyboard navigation, this change is unnecessary.

2021-02-09 08:51 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.IKeyboardToolTip.cs
> +        bool IKeyboardToolTip.HasRtlModeEnabled() => TreeView.RightToLeft == RightToLeft.Yes;
This makes sense 👍

2021-02-09 09:00 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        private void CollectChildNodesToList(List<TreeNode> nodes)
Turn this into a local static method of `GetChildNodes`

2021-02-15 10:21 UTC, RussKie reviewed
👍 with few nits

2021-02-15 10:21 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs
> +            Assert.False((bool)KeyboardToolTipStateMachine.Instance.TestAccessor().Dynamic.IsToolTracked(treeNode));
Given the number of `KeyboardToolTipStateMachine.Instance.TestAccessor().Dynamic.IsToolTracked` references, it is totally justified to add a typed test accessor.

2021-02-15 10:21 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
> +            //Assert.Equal method does not work because char* cannot be used as an argument to it
```suggestion
            // Assert.Equal method does not work because char* cannot be used as an argument to it
```
ditto below

2021-02-16 06:40 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs
> +            Assert.False((bool)KeyboardToolTipStateMachine.Instance.TestAccessor().Dynamic.IsToolTracked(treeNode));
Implemented "KeyboardToolTipStateMachineHelper" for it.

2021-02-16 12:39 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs
> +            Assert.False((bool)KeyboardToolTipStateMachine.Instance.TestAccessor().Dynamic.IsToolTracked(treeNode));
Nope, I meant to create a proper test accessor, similar to 
https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/TestAccessors.UiaTextRangeTestAccessor.cs#L13

2021-02-17 03:38 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
> +            Assert.True(KeyboardToolTipStateMachine.Instance.TestAccessor().IsToolTracked(treeNode1));
```suggestion
            var accessor = KeyboardToolTipStateMachine.Instance.TestAccessor();
            
            Assert.True(accessor.IsToolTracked(treeNode1));
```

2021-02-17 08:05 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TestAccessors.KeyboardToolTipStateMachineTestAccessors.cs
> +        internal class KeyboardToolTipStateMachineTestAccessors : TestAccessor<KeyboardToolTipStateMachine>
```suggestion
        internal class KeyboardToolTipStateMachineTestAccessor : TestAccessor<KeyboardToolTipStateMachine>
```

2021-02-17 08:14 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TestAccessors.KeyboardToolTipStateMachineTestAccessors.cs
> +        internal class KeyboardToolTipStateMachineTestAccessors : TestAccessor<KeyboardToolTipStateMachine>
Thank you. Fixed typos

2021-02-19 02:24 UTC, RussKie approved these changes

2021-02-19 09:37 UTC, SergeySmirnov-Akvelon commented
CTI approved

2021-02-22 09:29 UTC, merged