Adding Toggle pattern support for a PropertyGrid buttons
dotnet/winforms pull request #4586
Opened 2021-02-20 09:24 UTC by SergeySmirnov-Akvelon

Fixes #4428

## Proposed changes
- Added Toggle pattern support for a PropertyGrid buttons
- Added unit tests.

## Customer Impact

## Regression? 

- Yes

## Risk

- Minimal

## Test methodology 
- CTI team
- Unit tests

## Accessibility testing  
- Inspector 

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core SDK 6.0.0-alpha.1.21073.5

2021-02-22 10:09 UTC, RussKie submitted a review, later dismissed

2021-02-25 05:17 UTC, vladimir-krestov reviewed
Works well, but depending on base.Role doesn't look reliable.

2021-02-25 05:17 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObject.cs
> +                    UiaCore.UIA.TogglePatternId => base.Role == AccessibleRole.CheckButton,
Please try to find another way, the current implementation looks a little bit strange.
I see, it works, but it doesn't look reliable.

2021-02-25 05:17 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObject.cs
> +                    UiaCore.UIA.ControlTypePropertyId => UiaCore.UIA.ButtonControlTypeId,
Consider removing `ControlTypePropertyId` case from here. It should depend on `Role` value on the base level.

2021-02-25 05:17 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
> +            var accessibleObject = new PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObject(button);
Consider moving `PropertyGridToolStripButton` to the `using`s block.

2021-02-25 05:17 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
> +        public void PropertyGridToolStripButtonAccessibleObject_Role_ReturnsExpected()
I would rename it to "PropertyGridToolStripButtonAccessibleObject_Role_**`IsPushButton`**"

2021-02-25 05:17 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
> +        public void PropertyGridToolStripButtonAccessibleObject_GetPropertyValue_ReturnsExpected()
I would rename it too:
1) You check `GetPropertyValue` for only one case (ControlTypePropertyId), point it in the name
2) `...ReturnsButton` or `...IsButton`, to know what the test should return

My proposal is `PropertyGridToolStripButtonAccessibleObject_GetPropertyValue_ControlType_IsButton`

2021-02-25 05:17 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
> +            var accessibleObject = new PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObject(button);
What about using `AccessibleObject accessibleObject = button.AccessibilityObject;` here and in the rest tests?

2021-02-25 05:17 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
> +        public void PropertyGridToolStripButtonAccessibleObject_Toggle_WorksCorrectly()
"WorksCorrectly" is a too common name, please rename it to reflect the real results of the method

2021-02-25 05:17 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
> +        public void PropertyGridToolStripButtonAccessibleObject_ToggleState_WorksCorrectly()
ditto

2021-03-04 06:17 UTC, RussKie approved these changes

2021-03-11 05:23 UTC, vladimir-krestov reviewed
Nice work, add comments everywhere about changing "Check" to "Radio" button and why you didn't implement "Toggle" pattern

2021-03-11 05:23 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObject.cs
> +        internal class PropertyGridToolStripButtonAccessibleObject : ToolStripButtonAccessibleObject
Sort the class members alphabetically

2021-03-11 05:23 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObject.cs
> +                    UiaCore.UIA.SelectionItemPatternId => _owningPropertyGridToolStripButton.SelectItemEnabled,
The Issue is about "Toggle" pattern, the description too.
Please rework the PR description to point that we will use "CheckButton" type for Grid buttons and we need to have different patterns supporting.
Also, leave a comment about the conception changes in the Issue.
Because it's confusing now.

2021-03-11 05:23 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
> +                button.AccessibleRole = AccessibleRole.RadioButton;
Consider adding a unit test to PropertyGridTests to check this.

2021-03-11 05:23 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.cs
> +            => new PropertyGridToolStripButtonAccessibleObject(this);
You may add a unit test to check that an accessible object of this button is PropertyGridToolStripButtonAccessibleObject

2021-03-11 05:23 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
> +            Assert.False(propertyPagesButtonAccessibleObject.IsPatternSupported(UIA.SelectionItemPatternId));
Could you please describe, why "false"?
Add a comment here in the code

2021-03-11 05:23 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
> +        public void PropertyGridToolStripButtonAccessibleObject_InvokeInvoke_UpdatesCheckedStateAndPropertySort()
Looks strange: 
```suggestion
        public void PropertyGridToolStripButtonAccessibleObject_Invoke_UpdatesCheckedStateAndPropertySort()
```

I usually add tests using the following pattern: **`[className]`_`[methodName]`_`[whatItDoes]`_`[conditions (not necessary)]`**
So, I think, we don't need to add "Invoke" before methods in tests names.

2021-03-11 09:38 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObject.cs
> +                    UiaCore.UIA.SelectionItemPatternId => _owningPropertyGridToolStripButton.SelectItemEnabled,
I have renamed the PR, also added a [comment](https://github.com/dotnet/winforms/issues/4428#issuecomment-793856033) describing the new behavior

2021-03-16 03:26 UTC, RussKie requested changes
👍

2021-03-16 21:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
> +                // the "CheckBox" role was changed to "RadioButton" as it more closely matches the behavior of the button
❗  The link is incorrect

2021-03-17 06:58 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
> +                // the "CheckBox" role was changed to "RadioButton" as it more closely matches the behavior of the button
Thank you. Fixed incorrect link.

2021-03-17 07:28 UTC, RussKie approved these changes

2021-03-18 07:14 UTC, SergeySmirnov-Akvelon commented
CTI approved

2021-03-19 00:30 UTC, merged