Move sub-classes of "PropertyGrid"  classes to their own files
dotnet/winforms pull request #4602
Opened 2021-02-25 12:45 UTC by SergeySmirnov-Akvelon

## Proposed changes
- Moved sub-classes of "PropertyGrid"  classes to their own files
- Fixed unit tests

## Customer Impact
- No 

## Regression? 
- No

## Risk
- Minimal

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core SDK 6.0.0-alpha.1.21073.5

2021-03-01 02:09 UTC, RussKie commented
MC

2021-03-01 23:28 UTC, RussKie requested changes

2021-03-01 23:28 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridAccessibleObjectTests.cs
>          public void PropertyGridAccessibleObject_Ctor_Default()
Please adjust the file name as well.

2021-03-01 23:28 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridToolStripAccessibleObjectTests.cs
>          {
ditto

2021-03-01 23:28 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/AutomationMessages.cs
> +    internal static class AutomationMessages
@dreddy-work do you know anything about this class? This looks like MAUI test-related infra.

2021-03-03 18:06 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/AutomationMessages.cs
> +    internal static class AutomationMessages
No. I never touched it.

2021-03-11 04:00 UTC, RussKie approved these changes

2021-03-11 04:00 UTC, merged