Implement InitialDirectory and ClientGuid for FolderBrowserDialog
dotnet/winforms pull request #4645
Opened 2021-03-04 21:38 UTC by weltkante

Implements #3512

## Proposed changes

- Add `InitialDirectory` and `ClientGuid` to `FolderBrowserDialog` to match what `FileDialog` already has

## Customer Impact

- bring the modern (aka Vista) FolderBrowserDialog to parity with FileDialog
- as a side effect, also respect the initial directory for the classic folder dialog, by expanding the directory without selecting it
  - this is done for consistency, so that when future code is written to only set `InitialDirectory` it still works out of the box when the modern dialog is not available, which has been reported a while ago for some server machine setups that were still supported.

## Test methodology 

- manual testing
- (unit tests still to be added)

## Accessibility testing  

none required, the dialog already existed, the additional configuration options do not expose new elements to accessibility

2021-03-04 21:43 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                if (parent is null || !Directory.Exists(parent) || !string.IsNullOrEmpty(InitialDirectory))
If I have an `InitialDirectory` and `SelectedPath` the textbox needs to contain the full path, not a relative path.

This could be made nicer, the else branch wants to generate a relative path, but in order to implement this I would have to determine the common part of the `SelectedPath` and `InitialDirectory` so I can strip it from the selected path and only insert the non-common part into the text box.

As far as I know neither WinForms nor .NET have precedence of determining the common prefix of two paths, also the native implementation of the shell dialog didn't seem to consider it important enough to implement it "out of the box", so I'm not implementing it here either.

If I'm missing precedence or you want me to take an attempt anyways, I can take another look at it of course.

2021-03-04 22:31 UTC, RussKie reviewed
A quick review. I will review it more thoroughly next week.
👍

2021-03-04 22:31 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                // https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifiledialog-setclientguid#remarks
```suggestion
                // https://docs.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifiledialog-setclientguid#remarks
```

2021-03-04 22:31 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                if (parent is null || !Directory.Exists(parent) || !string.IsNullOrEmpty(InitialDirectory))
This should be a little more performant
```suggestion
                if (parent is null || !string.IsNullOrEmpty(InitialDirectory) || !Directory.Exists(parent))
```

2021-03-06 17:51 UTC, wjk requested changes
You should probably want to update the FolderNameEditor editor class to use the FolderBrowserDialog class instead of its hard-coded use of `SHBrowseForFolder()`.

2021-03-06 17:51 UTC, wjk commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        public string InitialDirectory
Use [`FolderNameEditor`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.cs) here?

2021-03-08 20:26 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                // https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifiledialog-setclientguid#remarks
This was copy-pasted from `FileDialog.Vista.cs`, I've also removed the language tag there

2021-03-08 20:28 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        public string InitialDirectory
Right now its just a copy of the `FileDialog` API. I agree that `FolderNameEditor` would be good to use, and also that it should be updated to use the modern dialog, but the change should probably be done on all dialogs at the same time.

@RussKie do you think thats appropriate for this PR or should I open a separate issue/PR for this change? It will affect designer behavior which I'm not able to test.

2021-03-08 20:31 UTC, weltkante commented
I added API tests to match what is being tested for FileDialog, but I couldn't find any automated interaction (integration?) tests. I did test manually. If you want more tests added I need some guidance to what they should look like, tests are not my strong side ;)

2021-03-08 22:12 UTC, dreddy-work reviewed
@weltkante , Did you play these changes with designer to make sure everything is serialized/deserialized properly?

2021-03-08 22:12 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
So this shows up in a different category than "SelectedPath"? Any justification for that?

2021-03-08 22:14 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
I see. matching with FileDialog.

2021-03-08 22:27 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
> Did you play these changes with designer to make sure everything is serialized/deserialized properly?

No I'm not able to test the designer. As far as I'm aware using a custom WinForms build with the designer is currently not possible?

2021-03-09 01:28 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
I agree that change is straight forward. however, in core designer, most of the serialization is moved around to run out of proc. It would be nice to cross check it in designer before merging. We have this [draft ](https://github.com/dotnet/winforms/blob/main/docs/debugging.md) explaining how to debug runtime change in the designer. Let me know if these instructions doesn't work for you.

2021-03-09 01:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                if (parent is null || !Directory.Exists(parent) || !string.IsNullOrEmpty(InitialDirectory))
I think it is ok to have the full path only. We can revisit this in the future if there is a sufficient demand for it.

Thank you

2021-03-09 01:34 UTC, RussKie commented
> You should probably want to update the FolderNameEditor editor class to use the FolderBrowserDialog class instead of its hard-coded use of `SHBrowseForFolder()`.

👍 
Please open a new issue for this.

2021-03-09 01:35 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        public string InitialDirectory
This is a great suggestion, but is outside the scope of this change, which is to add the new API.

2021-03-09 01:40 UTC, RussKie commented
> I added API tests to match what is being tested for FileDialog, but I couldn't find any automated interaction (integration?) tests. I did test manually. If you want more tests added I need some guidance to what they should look like, tests are not my strong side ;)

I'm having a hard time picturing what an integration test would look like... But we can add a new form to the WinformsControlsTest project to exercise the change manually.
We have a test for [`FolderBrowserDialog`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs#L81), but I think we can replace it with a new form with few buttons, with each opening a dialog, e.g. `FolderBrowserDialog`, `OpenFileDialog`, `SaveFileDialog`, etc. Since each dialog is a `Component` we can add those to the design surface (though it doesn't currently work for our solution, the issue is tracked but it's complicated).

What do you think?

2021-03-09 19:17 UTC, weltkante commented
> I'm having a hard time picturing what an integration test would look like... But we can add a new form to the WinformsControlsTest project to exercise the change manually.

Well, I imagined to test that the properties do what they claim to do, selecting the initial folder, by accessing the dialog via accesibility API to verify how it initialized. ClientGuid could be tested by repeatedly opening a dialog and changing the current folder in between. Both requires some accessibility API against the native dialog and I have no idea if what I imagine is reasonable. I have certainly no idea how to code it ;)

> We have a test for FolderBrowserDialog, but I think we can replace it with a new form with few buttons, with each opening a dialog, e.g. FolderBrowserDialog, OpenFileDialog, SaveFileDialog, etc. Since each dialog is a Component we can add those to the design surface

Not sure how you imagine the experience, i.e. what options to offer. Maximum flexibility would probably be just adding a property grid so the dialog is fully configurable to test out various combinations of properties, or would that be too much choice?

2021-03-11 06:30 UTC, RussKie commented
I imagine it something like this:
![image](https://user-images.githubusercontent.com/4403806/110745386-46853000-828f-11eb-8a82-be87b5ccd6fe.png)

Then we can consolidate all dialogs from tests on this form, and remove FileDialog.cs from the test project.

2021-03-12 15:06 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
Ok, tried option (2) from your link first and it doesn't work. The designer doesn't pick up the custom build referenced in the project, and Visual Studio kills itself shortly after (maybe 30-60 seconds into working with the designer), no error given, just disappears.

<details><summary>also the instructions are outdated</summary>

> error CS1705: Assembly 'System.Windows.Forms' with identity 'System.Windows.Forms, Version=42.42.42.42, Culture=neutral, PublicKeyToken=b77a5c561934e089' uses 'System.Windows.Forms.Primitives, Version=42.42.42.42, Culture=neutral, PublicKeyToken=b77a5c561934e089' which has a higher version than referenced assembly 'System.Windows.Forms.Primitives' with identity 'System.Windows.Forms.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Adding that other references (from the same folder) compiles, so you may update those notes to also reference that other assembly in the same path. Doesn't fix the designer though, not picking up the right version of WinForms. Also the VS killing itself thing.

</details>

---

Option (1) worked but it took a lot of effort, having to make sure to install the exact SDK used to make the custom WinForms build, no other 6.0 SDKs or runtimes being installed, and knowing exactly which files to copy, this is a lot of effort you have to put into testing designer changes. Not to speak of the high risk of breaking the installation. Took me several hours to go through all this.

Anyways, tested in designer now, and I agree copy/pasting the `Category` used in `FileDialog` makes no sense (the new property is the only entry in this category) so I changed it and put it into the category where the other stuff is.

The general designer behavior works as expected, but to make it user-friendly and open a folder selection instead of presenting a plain textbox #4665 needs to be also implemented.

2021-03-12 19:03 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
Thanks for trying this @weltkante . That helps on what should be updated for instructions. I will look into it soon.  Will you be picking up on #4665? I believe, without it/an editor to navigate to path, this feature is incomplete. In designer, the way model dialogs interact with the out of proc process has changed a bit and its worth verifying it in combination.

2021-03-12 19:25 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
Yes I'll also do #4665 but was asked to split it into a separate issue/PR

2021-03-12 19:43 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
If you like to get this PR merged independent of #4665, Can you add legacy editor attribute until then, to this property to make feature complete? Or is there any reason why you excluded editor attribute?

2021-03-12 20:02 UTC, weltkante commented
@RussKie yeah thats about what I imagined. Anything particular you want me to do in this PR beyond what you proposed? (I'm looking into how to offer the `ClientGuid` for testing, so there's that.)

2021-03-15 21:41 UTC, RussKie reviewed
LGTM with the comments

2021-03-15 21:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        private string _initialDir;
```suggestion
        private string _initialDirectory;
```

2021-03-15 21:41 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.cs
> +        private sealed class ClientGuidConverter : GuidConverter
Please move to Dialogs.ClientGuidConverter.cs

2021-03-15 21:41 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.cs
> +        private sealed class ExposedClientGuidMetadata
ditto

2021-03-15 21:44 UTC, RussKie commented
> Tell me if you want me to go further, like adding presets to replace the [already existing](https://github.com/dotnet/winforms/blob/b8014c7e3d454863169551b227f4843619dc3f44/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FileDialog.cs) preconfigured scenarios?

We'll need to move and refactor those into the new dialog form. It is outside the scope of this work, but if you keen on helping with this after this is done - I would say "Thank you!" ;)

2021-03-15 22:13 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        private string _initialDir;
also changed the occurrence in FileDialog since the implementation is partially copied from there

2021-03-15 22:16 UTC, RussKie submitted a review, later dismissed

2021-03-15 22:17 UTC, RussKie commented
@wjk do you have any more outstanding concerns?

2021-03-15 22:19 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
>  Can you add legacy editor attribute until then, to this property to make feature complete?

We [need](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectedPathEditor.cs) a separate subclass and localization then, to have parity with the `SelectedPath` property, since theres a description string to be filled in.

@RussKie whats your take on the separation of issues here? Should we do the editor attribute in this PR after all (since it affects designer behavior), and leave #4665 just for upgrading the dialog called by the attribute?

If so I need to look into whats necessary to add new localization strings, if you have any pointers to get me started that would be nice.

2021-03-15 22:21 UTC, weltkante commented
> do you have any more outstanding concerns?

there are some designer concerns [discussed](https://github.com/dotnet/winforms/pull/4645#discussion_r593408092) which still need to be resolved

2021-03-15 22:49 UTC, RussKie commented
Ah, missed those! Thank you

2021-03-15 22:52 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
Agree with @dreddy-work, we should make it "feature complete". 

New loc strings are added into respective SR file manually, like so: https://github.com/dotnet/winforms/pull/4297/files#diff-b54bd33e7614a8128ebb229be63cf824ce8ffd798d5c9e2032b47f7164ede642

2021-03-15 23:35 UTC, weltkante commented on src/System.Windows.Forms/src/AssemblyRef.cs
> +    internal const string SystemWindowsFormsDesign = "System.Windows.Forms.Design, Version=" + ThisAssembly.Version + ", Culture=neutral, PublicKeyToken=" + PlatformPublicKey;
This is the first time anyone is adding a new editor since Desktop Framework? How do I reference it? I don't think I'll want to add it to the Desktop Framework facade since its new and shouldn't have a redirection.

Desktop Framework also had more properties in `AssemblyRef` so I'm adding back `PlatformPublicKey` because its needed here.

Whats more worrying though is that `ThisAssembly` was apparently autogenerated in Desktop Framework and is totally missing in .NET Core? Any idea how to implement this? Obviously it cannot stay like this with a hardcoded version.

2021-03-15 23:38 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
Implemented, will follow up with a designer test, but we need to resolve [another problem](https://github.com/dotnet/winforms/pull/4645#discussion_r594761228) first. Leaving this discussion open until I actually tested it in the designer.

2021-03-16 00:00 UTC, RussKie commented on src/System.Windows.Forms/src/AssemblyRef.cs
> +    internal const string SystemWindowsFormsDesign = "System.Windows.Forms.Design, Version=" + ThisAssembly.Version + ", Culture=neutral, PublicKeyToken=" + PlatformPublicKey;
I had a chat with @DustinCampbell, and the advice was it is ok to hardcode the version:
```cs
    internal const string SystemWindowsFormsDesign = "System.Windows.Forms.Design, Version=6.0.0.0, Culture=neutral, PublicKeyToken=" + PlatformPublicKey;
```

Also if we add another editor in .NET 7.0 its decoration would be "_System.Windows.Forms.Design, Version=**7.0.0.0**, Culture=neutral...._", so may be it makes sense to not create a const for this.

2021-03-16 00:00 UTC, RussKie commented on src/System.Windows.Forms/src/AssemblyRef.cs
> +    internal const string SystemWindowsFormsDesign = "System.Windows.Forms.Design, Version=" + ThisAssembly.Version + ", Culture=neutral, PublicKeyToken=" + PlatformPublicKey;
This is where that type name gets resolved to a System.Type: https://source.dot.net/#System.ComponentModel.TypeConverter/System/ComponentModel/ReflectTypeDescriptionProvider.ReflectedTypeData.cs,338

2021-03-16 02:11 UTC, wjk approved these changes

2021-03-16 22:39 UTC, weltkante commented on src/System.Windows.Forms/src/AssemblyRef.cs
> +    internal const string SystemWindowsFormsDesign = "System.Windows.Forms.Design, Version=" + ThisAssembly.Version + ", Culture=neutral, PublicKeyToken=" + PlatformPublicKey;
> so may be it makes sense to not create a const for this

Sounds sensible, I've inlined the assembly name into the attribute to follow the plan of freezing the version. This is typically what users do also, they copy the string if they want to use the editor, so for compatibility neither the assembly name nor key can be made inaccessible and its fine if this literal string is never touched again.

It still doesn't feel great to use literals though and maybe I'm missing something, not sure _why_ we are freezing the assemblies where the editor originally was defined. Maybe we discussed it before but right now the only case I can think of is users copying the string and using it themselves, but that doesn't prevent _you_ from updating _your_ instances of the string, it just prevents you from ever _moving the editor around_ because that would break users referencing by its name/assembly pair (limited moving is possible with type forwards of course).

Anyways, probably out of scope for this PR, so just say whatever you settle on for now and I'll update again if I should have misunderstood. The literal string Roslyn puts into the assembly output will always be the same so if you want to change const vs. literal in source there is plenty time in a follow-up PR without changing how the attribute looks to consumers.

2021-03-16 22:51 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
Can't seem to get it to work under the designer; the editor works at runtime in the interactive property grid we added, but at VS design time its still just a text box. I did copy the `System.Windows.Forms.Designer.dll` into the SDK to the same place where I've put the other updated dlls previously, is thats how its supposed to work?

2021-03-17 09:09 UTC, weltkante commented on src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
> +            TestHelpers.SendTabKeysToProcess(process, 3);
This test isn't verifying what its testing, it just checks the process didn't crash after pressing buttons. It doesn't check that the buttons do what the test think they should do.

In other words the next time the new Dialog form is updated this test is probably going to break without reporting a test failure. Should I define a tab order enum for this dialog? This enum doesn't feel great to me since it doesn't really make any sense. I'd have expected the test helpers use accessibility APIs to verify what form is currently open.

2021-03-18 02:18 UTC, RussKie submitted a review, later dismissed
Ran it locally - every works including the designer for the `InitialDirectory` at runtime.

I was able to confirm the VS Designer as well, except for the designer as the local binaries are 42.42... and not 6.0.0 and not signed.
![image](https://user-images.githubusercontent.com/4403806/111563582-53a0a280-87ec-11eb-8fa9-6d3d33583994.png)

2021-03-18 02:24 UTC, RussKie commented
@weltkante could you please explain how to test `ClientGuid`?

2021-03-18 02:28 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
> +            TestHelpers.SendTabKeysToProcess(process, 3);
These tests are pretty dumb with a questionable value. Though once or twice they proved useful (e.g. when `TabControl` was hanging on paint).
I wouldn't worry about this for now, but if you have any thoughts on how to make these tests useful I'm happy to discuss and explore.

2021-03-18 02:34 UTC, RussKie commented on src/System.Windows.Forms/src/AssemblyRef.cs
> +    internal const string SystemWindowsFormsDesign = "System.Windows.Forms.Design, Version=" + ThisAssembly.Version + ", Culture=neutral, PublicKeyToken=" + PlatformPublicKey;
> it just prevents you from ever _moving the editor around_ because that would break users referencing by its name/assembly pair (limited moving is possible with type forwards of course).

I doubt we'll see another exodus of our designers in foreseeable future. I'm pretty certain we made up our minds, and the assembly names are set for good now.

2021-03-18 08:35 UTC, weltkante commented
> @weltkante could you please explain how to test `ClientGuid`?

Chose a `ClientGuid` and open the dialog, move it around and browse to a folder, then confirm.

Then test with a different `ClientGuid` (or blank), it should have reset folder and window location.

Then go back to the original one and it should restore the location and starting folder (assuming you have neither SelectedPath nor InitialDirectory configured, those take precedence, but window location should always be restored)

2021-03-18 08:41 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
Seems to be [not testable](https://github.com/dotnet/winforms/pull/4645#pullrequestreview-614872577) under the designer, but considering it works at runtime I'd assume after an official build the designer will load it as well. Needs follow-up once this goes into a nightly build, unless someone has ideas how to test it.

2021-03-18 16:58 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
Understand. Technically, we shouldn't need an updated designer here to pick up this property if this was coming from runtime. We do route editors in the designer. I can get to it ( may be tomorrow) to debug what is happening in the designer.

Q: How was the other 'SelectedPath' property editor working in designer?

2021-03-18 17:07 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        [SRCategory(nameof(SR.CatData))]
> How was the other 'SelectedPath' property editor working in designer?

The attribute is referring to the Desktop Framework assembly, which has a type forward. We cannot add new editors (or type forwards to new editors) to the Desktop Framework without beginning to version it again.

As far as I can tell from @RussKie comment the problem is either the the assembly key signature or the version being 42.42.42.42 instead of 6.0.0.0 which I'm referring to. SelectedPath refers to the Desktop Framework 4.0.0.0 version which has not been touched by this PR so its still working.

2021-03-19 01:51 UTC, RussKie commented
We had a chat with @dreddy-work, and it looks like VS may need its own copy of the editor to show it (it can't resolve it from the WF runtime as the editor is run by the VS process, and the designer is run as a separate process). This isn't something that can be addressed here in the runtime.

2021-03-19 02:07 UTC, RussKie reviewed
All good, few last comments

2021-03-19 02:07 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +            if (!string.IsNullOrEmpty(InitialDirectory))
```suggestion
            if (!string.IsNullOrWhiteSpace(InitialDirectory))
```

2021-03-19 02:07 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +            if (!string.IsNullOrEmpty(InitialDirectory))
We appear to be inconsistent in our use - here we use the property, and below we use the field.
```suggestion
            if (!string.IsNullOrEmpty(_initialDirectory))
```

2021-03-19 02:07 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        private string _initialDirectory;
I wondered how this PR was passing with seemingly incorrect NRTA, until I realised this type isn't fully annotated.

2021-03-19 10:19 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        private string _initialDirectory;
While NRTA is disabled note that FolderBrowserDialog normalizes its properties to empty string in the setters so these variables actually cannot be null. This is important for the correctness of the code and I had to adjust the code copy/pasted from FileDialog (which does not normalize in its setter, but rather in its getter)

2021-03-19 11:37 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +            if (!string.IsNullOrEmpty(InitialDirectory))
> We appear to be inconsistent in our use

Leftover from FileDialog because I wanted to keep code that didn't need to differ identical. In FileDialog the getter does normalization to empty string and its mandatory to use the property, FolderBrowserDialog does it the other way round and normalizes in the setter.

I've updated the PR to keep the usage in the file consistent, instead of across files.

> IsNullOrWhiteSpace

If I do this change we start becoming inconsistent, some properties ignore blank strings, some don't. I copied this from FileDialog so FolderDialog being different from FileDialog is going to be weird.

Personally I don't like treating whitespace in blank strings as insignificant when you are doing it inconsistently (only in some places). Also it adds a special case instead of generalizing, in my opinion it would be much more sensible to treat leading/trailing whitespace to be insignificant rather than special casing a blank string. In this case you would be trimming in the setter, not checking IsNullOrWhiteSpace in every call site.

In the end its your choice, if you can confirm that you want IsNullOrWhiteSpace in this specific location and only there then I'll update, otherwise I think updating existing call sites belongs in a separate PR (including tests for changed behavior) and maybe an issue to do this conistently in the codebase (and perhaps discuss trimming).

2021-03-22 01:23 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +            if (!string.IsNullOrEmpty(InitialDirectory))
> Leftover from FileDialog because I wanted to keep code that didn't need to differ identical. In FileDialog the getter does normalization to empty string and its mandatory to use the property, FolderBrowserDialog does it the other way round and normalizes in the setter.

Yes, I noted this during the review. It is indeed different to how we generally do it.

2021-03-22 01:24 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +            if (!string.IsNullOrEmpty(InitialDirectory))
> > IsNullOrWhiteSpace
> 
> If I do this change we start becoming inconsistent, some properties ignore blank strings, some don't. I copied this from FileDialog so FolderDialog being different from FileDialog is going to be weird.

Aye, let's keep as is.

2021-03-22 01:24 UTC, RussKie commented
/azp run

2021-03-22 01:25 UTC, RussKie approved these changes

2021-03-22 02:17 UTC, RussKie commented
/azp run

2021-03-22 23:13 UTC, weltkante commented
I don't know how that build error slipped into master, but I fixed it anyways

2021-03-23 07:22 UTC, RussKie commented
> I don't know how that build error slipped into the main branch, but I fixed it anyways

You need to rebase more often 😉 
It was fixed in https://github.com/dotnet/winforms/commit/03d1550f1d893fa964548df8a6f57b2fde892fc3. It slipped in likely because of a PR being opened and build before https://github.com/dotnet/winforms/pull/4689 was merged.

2021-03-23 07:27 UTC, weltkante commented
> You need to rebase more often

I used to, but I got the impression that github PRs don't like rebasing and force pushes.

2021-03-23 07:35 UTC, RussKie commented
I don't have any issues - I constantly rebases and f-pushes. Obviously don't do this with public branches like master, main, release/*, etc. But for own branches (especially on your fork) - go for your life :)
The only time GitHub has a problem if you close a PR, then f-push and try to re-open.

Tracking-merges are evil, then make reviews outside GitHub very difficult.

2021-03-24 05:08 UTC, RussKie approved these changes

2021-03-24 05:08 UTC, merged

2021-03-24 05:08 UTC, RussKie commented
Thank you!