Mdicontainer iconchanges
dotnet/winforms pull request #4650
Opened 2021-03-06 12:50 UTC by gero3

Fixes #4621

## Proposed changes

- The visibility of the Icon in the MDIControlStrip is dependent on the ShowIcon property on the target MDI child.
- When the icon gets updated in the target MDI child, the icon gets updated in the MDIControlStrip and its visibility is checked.
- 

## Customer Impact

- The icon will now change dependent on ShowIcon and the icon in the target MDI child.

## Regression? 

- No

## Risk

- Icon can not be used to open context menu when icon is hidden.

## Screenshots 

### Before

With showicon = false and the icon set to error icon after it is maximized.
![image](https://user-images.githubusercontent.com/155535/110207129-c66f5c80-7e81-11eb-94f2-a93c6bb3c01d.png)

### After

the icon set to error icon after it is maximized.
![image](https://user-images.githubusercontent.com/155535/110207294-db98bb00-7e82-11eb-8be3-da652464e89e.png)

With showicon = false
![image](https://user-images.githubusercontent.com/155535/110207319-f834f300-7e82-11eb-83e0-04ca92fb7dcb.png)

## Test methodology 

- manual testing
- Unit test 

## Accessibility testing

2021-03-07 08:34 UTC, dreddy-work requested changes

2021-03-07 08:34 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                if (WindowState == FormWindowState.Maximized && MdiParent != null && MdiParent.MdiControlStrip != null)
```suggestion
                if (WindowState == FormWindowState.Maximized && MdiParent?.MdiControlStrip != null)
```

2021-03-07 08:34 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
> +                ResumeLayout(false);
nit: alignment missing?

2021-03-07 08:34 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
> +        }
```suggestion
        private bool GetTargetWindowIconVisibility() => _target is not Form formTarget || formTarget.ShowIcon;
```

2021-03-07 08:34 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
> +            menuStrip.Location = new System.Drawing.Point(0, 0);
nit: please add parameter names for the constants passed. we have been enforcing this in other repos  winforms own.

2021-03-07 11:12 UTC, gero3 commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
> +                ResumeLayout(false);
I've resolved the misalignment.

2021-03-07 11:14 UTC, gero3 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
> +            menuStrip.Location = new System.Drawing.Point(0, 0);
I've removed the location en size property completely since this doesn't matter for the test.

2021-03-07 11:15 UTC, gero3 commented
@dreddy-work I think I've resolved all issues within the code.

2021-03-07 18:30 UTC, dreddy-work approved these changes
LGTM.

2021-03-09 01:34 UTC, merged

2021-03-09 01:34 UTC, dreddy-work commented
Thanks @gero3 for the fix.

2021-03-09 03:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                if (WindowState == FormWindowState.Maximized && MdiParent?.MdiControlStrip != null)
```suggestion
                if (WindowState == FormWindowState.Maximized && MdiParent?.MdiControlStrip is not null)
```

2021-03-09 03:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
> +        private bool GetTargetWindowIconVisibility() => _target is not Form formTarget || formTarget.ShowIcon;
Missing blank line

2021-03-09 03:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
> +            _system.Visible = GetTargetWindowIconVisibility();
I think it makes sense to enhance `GetTargetWindowIcon()` logic to check whether icon is visible before retrieving the icon. This would be a perf improvement.
```cs
        private (Image: Image, Visible: bool) GetTargetWindowIcon()
```

2021-03-09 03:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
> +        public void updateIcon()
❗ Incorrect casing

2021-03-09 21:53 UTC, gero3 commented
@RussKie 

I've added  PR #4664 to clean up the rest of the code.