Enable nullability in DrawListView EventArgs
dotnet/winforms pull request #4657
Opened 2021-03-07 09:40 UTC by gpetrou

## Proposed changes

- Enable nullability in DrawListView EventArgs.

2021-03-09 06:12 UTC, RussKie requested changes

2021-03-09 06:12 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewSubItemEventArgs.cs
> +            Color color = (ItemIndex == -1) ? Item!.ForeColor : SubItem!.ForeColor;
Argh this looks ugly...

2021-03-10 08:17 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewSubItemEventArgs.cs
>              }
```suggestion
            Graphics =  graphics  ?? throw new ArgumentNullException(nameof(graphics));
```

2021-03-10 08:17 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewSubItemEventArgs.cs
>              }
And remove line 44.

2021-03-11 05:51 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewColumnHeaderEventArgs.cs
> +            Graphics? graphics,
You mean you want to remove the ArgumentNullException?

2021-03-11 05:53 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewSubItemEventArgs.cs
> +            Color color = (ItemIndex == -1) ? Item!.ForeColor : SubItem!.ForeColor;
I know, but I assume it is correct since the nullability is depending on the ItemIndex value.

2021-03-11 06:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewColumnHeaderEventArgs.cs
> +            Graphics? graphics,
No, I mean this:
```suggestion
            Graphics graphics,
```

This implies `graphics` arg can never be null, as it would lead to the ANE

2021-03-11 06:39 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewSubItemEventArgs.cs
> +            Color color = (ItemIndex == -1) ? Item!.ForeColor : SubItem!.ForeColor;
It was a painful gasp on my part... I don't think there's a good way to express it any other way.
I looked at using `dynamic` keyword, but it resulted in significant perf overhead.

2021-03-12 05:58 UTC, RussKie approved these changes

2021-03-12 05:58 UTC, merged