fixes #1991 => remove disable warning SA1408
dotnet/winforms pull request #4659
Opened 2021-03-07 16:26 UTC by gero3

Fixes #1991

## Proposed changes

- Add parenthesizes around logical And operators that are in logical Or operators.  

## Customer Impact

- None

## Regression? 

- No

## Risk

- None

## Test methodology 

- manual testing
- existing unit tests

2021-03-07 18:44 UTC, dreddy-work requested changes

2021-03-07 18:44 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
> +                    if ((OwningColumn is not null && OwningColumn.SortMode != DataGridViewColumnSortMode.NotSortable) ||
```suggestion
                    if ((OwningColumn?.SortMode != DataGridViewColumnSortMode.NotSortable) ||
```

2021-03-07 18:44 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
> +                (keyData & Keys.KeyCode) == Keys.Enter)
can we cache '(keyData & Keys.KeyCode)' and reuse cached value in this method?

2021-03-07 18:44 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs
> +            if ((toolStrip.AutoSize && !toolStrip.IsInToolStripPanel && dock == DockStyle.Left) ||
I think this altered the condition. Can you please cross check it?

2021-03-07 21:18 UTC, gero3 commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
> +                    if ((OwningColumn is not null && OwningColumn.SortMode != DataGridViewColumnSortMode.NotSortable) ||
Doesn't this only work because `DataGridViewColumnSortMode.NotSortable` has value 0 since SortMode is an integer enum? 

When `OwningColumn` is `null`, then `OwningColumn?.SortMode` would be `0`. So `OwningColumn?.SortMode != DataGridViewColumnSortMode.NotSortable` is false.

2021-03-07 21:35 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
> +                    if ((OwningColumn is not null && OwningColumn.SortMode != DataGridViewColumnSortMode.NotSortable) ||
You are right.

2021-03-07 21:43 UTC, gero3 commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
> +                    if ((OwningColumn is not null && OwningColumn.SortMode != DataGridViewColumnSortMode.NotSortable) ||
I've needed to revert this change since it seems that the 2 lines of code aren't the same.

https://dotnetfiddle.net/stWNKJ

2021-03-07 21:56 UTC, gero3 commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs
> +            if ((toolStrip.AutoSize && !toolStrip.IsInToolStripPanel && dock == DockStyle.Left) ||
I've indeed changed it.

2021-03-07 21:56 UTC, gero3 commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs
> +            if ((toolStrip.AutoSize && !toolStrip.IsInToolStripPanel && dock == DockStyle.Left) ||
This is now fixed in commit d67e512.

2021-03-07 22:03 UTC, gero3 commented
@dreddy-work I've resolved all issues except the one that I've reverted. I've also rechecked all changes to make sure that I didn't change anything.

2021-03-07 22:13 UTC, dreddy-work approved these changes

2021-03-07 22:13 UTC, dreddy-work commented
> @dreddy-work I've resolved all issues except the one that I've reverted. I've also rechecked all changes to make sure that I didn't change anything.

Please check test failures.

2021-03-07 22:49 UTC, gero3 commented
@dreddy-work I can't simulate the test failing. I also don't see why it fails because I didn't change the code of the richTextBox.Text.

2021-03-08 22:04 UTC, dreddy-work commented
> @dreddy-work I can't simulate the test failing. I also don't see why it fails because I didn't change the code of the richTextBox.Text.

Release build was successful. it may be intermittent.  Rerunning them.

2021-03-09 00:48 UTC, merged

2021-03-09 00:51 UTC, dreddy-work commented
Thanks @gero3 . This is now merged.

2021-03-09 03:08 UTC, dreddy-work commented
@gero3 , Looking at the history of when these pragmas inserted, I think intention was, either we do not have complete understanding if these conditions are accurate or do not have test coverage in the unit tests to make sure this is authenticated.

2021-03-09 03:19 UTC, RussKie commented
Thank you @gero3 for the work, but this changes make me uncomfortable because it essentially cemented the existing possibly incorrect behaviours as "approved and correct". For each removed pragma I'd like to have an explanation why this logic is correct. 
When I enabled SA1408 I have found several bugs (e.g. [ComboBox.cs](https://github.com/dotnet/winforms/pull/1985/files#diff-a279bfceaf830444fc4318432b3387481fe38b4b5fdde61a216bdd3bf8a944fe) or [ScrollableControl.cs](https://github.com/dotnet/winforms/pull/1985/files#diff-29bc80569f6392cc8577d0cc4f1f2f91d3afd896609bc78479ed0fea1324d5d2)) in our logic. The remaining pragmas were put in place to flag the problematic spots, which require investigation and explanation why parenthesis must be placed one way or another.

2021-03-09 21:51 UTC, gero3 commented
@RussKie 

There are 3 statements that I'm not sure about =>
- https://github.com/dotnet/winforms/pull/4659/files#diff-dc17cf8f6ef4b80a13b2386597a72cd7ae36cab7375583a0a1e76a62f7f9238fR456-R457
- https://github.com/dotnet/winforms/pull/4659/files#diff-106272877a8c1da5243bd9eb714a106c253965f4909faea42805857e75262bf1R206-R207
- https://github.com/dotnet/winforms/pull/4659/files#diff-1ac2e23decb5937893921a95226f6c5299d1f36d5aa49b3c28fd3558bc0631a0R427-R428

For the other statements in the PR, I think I can write unit tests to confirm if they are correct.