Mdicontainer iconchanges
dotnet/winforms pull request #4664
Opened 2021-03-09 17:28 UTC by gero3

Fixes #4650

## Proposed changes

- cleanup code in accordance to @RussKie review in #4650

## Customer Impact

- None

## Regression? 

- No

## Risk

- None

2021-03-09 17:47 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
>          {
@RussKie , was comment about not querying for Icon incase it was not set visible?

2021-03-09 17:47 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
>          private bool GetTargetWindowIconVisibility() => _target is not Form formTarget || formTarget.ShowIcon;
nit: newline missing.

2021-03-09 17:47 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
> +            UpdateIcon();
nit: enforcing empty newline after closing braces in the repo. If existing code doesn't follow, please feel free to make those cleanup changes as well.

2021-03-09 20:31 UTC, gero3 commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
>          {
I've made it so it doesn't load/ generate the image if the image isn't visible in the next commit.

2021-03-09 20:37 UTC, gero3 commented
@dreddy-work 

I've updated the PR with the remarks you gave me and I've also updated the `UpdateIcon` method to make sure that the previous image is disposed of.

2021-03-10 04:18 UTC, dreddy-work reviewed
logically nothing should change but can you please do a integration test and confirm result with gif?

2021-03-10 04:18 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
> +        private (Image Image,bool Visible) GetTargetWindowIcon()
nit: missing format on this line.

2021-03-10 04:18 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
> +            if (_system.Image is not null) {
nit: braces always start on newline and a newline after closing braces

2021-03-18 02:48 UTC, RussKie requested changes

2021-03-29 01:57 UTC, RussKie commented
Please rebase, resolve the conflicts, and address the feedback.

2021-05-24 19:22 UTC, dreddy-work commented
@gero3, just want to make sure you are still on this.

2021-07-28 20:43 UTC, dreddy-work commented
closing as there were no recent activity on this.

2021-07-28 20:43 UTC, closed without merging