Enable nullability in some DataGridView EventArgs
dotnet/winforms pull request #4676
Opened 2021-03-11 17:35 UTC by gpetrou

## Proposed changes

- Enable nullability in some DataGridView EventArgs.

2021-03-12 05:53 UTC, RussKie requested changes

2021-03-12 05:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowDividerDoubleClickEventArgs.cs
>                  throw new ArgumentNullException(nameof(e));
We can simplify it further ;)

```suggestion
        public DataGridViewRowDividerDoubleClickEventArgs(int rowIndex, HandledMouseEventArgs e)
            : base((e ?? throw new ArgumentNullException(nameof(e))).Button, e.Clicks, e.X, e.Y, e.Delta, e.Handled)
        {
            if (rowIndex < -1)
            {
                throw new ArgumentOutOfRangeException(nameof(rowIndex));
```

2021-03-12 05:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowPostPaintEventArgs.cs
> +        public Graphics? Graphics { get; private set; }
This can't be null through the public API.
There's an `internal` flow (which is shady in the name of trying to reduce allocations of the eventargs class), but it sets all necessary parameters. It also asserts the graphics is set.

The same applies to `InheritedRowStyle` property, we just need to add a debug assert for it in `SetProperties` method.

2021-03-12 05:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowPostPaintEventArgs.cs
> +        public DataGridViewCellStyle? InheritedRowStyle { get; private set; }
As above - this can't be null

2021-03-12 05:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowStateChangedEventArgs.cs
> +        public DataGridViewRow? Row { get; }
This looks a pure omission, our API never pass null into here, nor we ever validate this property for null.
If anything we should throw a ANE in the .ctor. This is a breaking change, but in line with all the work with been doing.

2021-03-12 06:07 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowPostPaintEventArgs.cs
> +        public Graphics? Graphics { get; private set; }
I set it like that because the `internal DataGridViewRowPostPaintEventArgs(DataGridView dataGridView)` complains about it.

2021-03-15 23:30 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowPostPaintEventArgs.cs
> +        public Graphics? Graphics { get; private set; }
Our internal implementations mustn't affect the public API surface. If necessary, our internal implementation must be fixed to match the public API surface.

2021-03-29 01:00 UTC, RussKie approved these changes

2021-03-29 01:00 UTC, merged

2021-03-29 01:00 UTC, RussKie commented
Thank you!

2021-03-29 01:01 UTC, RussKie commented
Docs: https://github.com/dotnet/docs/issues/22021