Fix issue with showing groups in the Inspector when groups are disabled
dotnet/winforms pull request #4677
Opened 2021-03-12 11:20 UTC by SergeySmirnov-Akvelon

Fixes #4205

## Proposed changes
- Added conditions to ignore ListViewGroupAccessibleObjects when groups or visual styles are disabled
- Updated unit tests. 

## Customer Impact

## Regression? 
- Yes (from #3223) 

## Risk
- Minimal

## Test methodology 
- Unit tests
- CTI team

## Accessibility testing  
- Inspector

2021-03-15 23:28 UTC, RussKie requested changes
👍 with few comments

2021-03-15 23:28 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                => _owningListView.IsHandleCreated && _owningListView.GroupsEnabled && _owningListView.Groups.Count > 0;
```suggestion
                => _owningListView.IsHandleCreated && _owningListView.GroupsEnabled;
```
https://github.com/dotnet/winforms/blob/775aef04bf1f5d2c8af3ff01c622749438bc464f/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L1007-L1013

2021-03-15 23:28 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
> +                    ListViewGroup group = listView?.GroupsEnabled == false ? null : Group ?? listView.DefaultGroup;
This is rather difficult to read and comprehend. Let's unroll this.

2021-03-15 23:28 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
>          public void ListViewGroupAccessibleObject_ListWithTwoGroups_FragmentNavigateWorkCorrectly_IfHandleIsCreated()
```suggestion
        public void ListViewGroupAccessibleObject_ListWithTwoGroups_FragmentNavigateWorkCorrectly_IfHandleIsCreated_VisualStylesEnabled()
```

2021-03-16 21:47 UTC, RussKie submitted a review, later dismissed

2021-03-22 02:18 UTC, RussKie approved these changes

2021-03-22 02:18 UTC, RussKie commented
/azp run

2021-03-24 05:45 UTC, RussKie approved these changes

2021-03-25 09:41 UTC, SergeySmirnov-Akvelon commented
Approved by CTI team

2021-03-29 01:15 UTC, merged