Move sub-classes of "DataGridViewTopLeftHeaderCell", "FlatButtonAppearance" and "FontCacheEntry" classes to their own files
dotnet/winforms pull request #4695
Opened 2021-03-18 10:32 UTC by SergeySmirnov-Akvelon

## Proposed changes
- Moved sub-classes of "DataGridViewTopLeftHeaderCell", "FlatButtonAppearance" and "FontCacheEntry" classes to their own files 
- Enabled NRT
- Fixed Style issues and code sorting.

## Customer Impact
- No 

## Regression? 
- No

## Risk
- Minimal

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core SDK 6.0.0-alpha.1.21073.5

2021-03-22 01:39 UTC, RussKie commented
MC

2021-03-24 05:44 UTC, RussKie requested changes
Please clean up the history.

This is also a breaking change, please provide a snip for the breaking docs.

2021-03-24 05:44 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellRenderer.cs
> +                        visualStyleRenderer = new VisualStyleRenderer(s_headerElement);
Where does this come from?

2021-03-24 05:44 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellRenderer.cs
> +                VisualStyleRenderer.SetParameters(s_headerElement.ClassName, s_headerElement.Part, headerState);
ditto

2021-03-24 07:18 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellRenderer.cs
> +                        visualStyleRenderer = new VisualStyleRenderer(s_headerElement);
From [this change](https://github.com/dotnet/winforms/pull/4695/files?file-filters%5B%5D=.cs#diff-a9d2d56787df37d056bd0c1ca6b4b9ee2eebfb5f7c645221e9aa12f33187939aR15) to fix the naming

2021-03-24 08:56 UTC, SergeySmirnov-Akvelon commented
Fixed history and MC

2021-03-25 00:06 UTC, RussKie approved these changes

2021-03-25 00:06 UTC, merged

2021-03-29 03:02 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.cs
> +                }
Just realised - this check here is unnecessary and superficial, this is a private API invoked by `Navigate()` and `FragmentNavigate()` public API that _perform_ the validation.

2021-03-29 03:10 UTC, RussKie commented
Docs: https://github.com/dotnet/docs/issues/23529