Move sub-classes of "GridEntry" class to their own files
dotnet/winforms pull request #4700
Opened 2021-03-18 13:57 UTC by SergeySmirnov-Akvelon

## Proposed changes
- Moved sub-classes of "GridEntry" class to their own files 
- Enabled NRT
- Fixed value names. Fixed code sorting

## Customer Impact
- No 

## Regression? 
- No

## Risk
- Minimal

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core SDK 6.0.100-preview.2.21155.3

2021-03-18 23:00 UTC, RussKie reviewed
👍

2021-03-18 23:00 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.CategoryGridEntryAccessibleObject.cs
> +             // Category is in the first column.
It was at the different place

2021-03-18 23:00 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/AttributeTypeSorter.cs
> +        private static IDictionary? typeIds;
```suggestion
        private static IDictionary? s_typeIds;
```

2021-03-18 23:00 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
> +            protected GridEntry owner;
Can you please check if this has to be `protected`?

2021-03-22 01:12 UTC, RussKie commented
MC

2021-03-24 05:39 UTC, RussKie requested changes

2021-03-24 05:39 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.CategoryGridEntryAccessibleObject.cs
>                  PropertyGridView.PropertyGridViewAccessibleObject parent = (PropertyGridView.PropertyGridViewAccessibleObject)Parent;
A little cleaner would be write:
```suggestion
                if (Parent is not PropertyGridView.PropertyGridViewAccessibleObject parent)
                    return null;
```

2021-03-24 05:39 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
> +                    return Parent is null ? null : (PropertyGridView.PropertyGridViewAccessibleObject)Parent;
This looks awkward. I'm surprised the original version wasn't good enough....
How about this?
```suggestion
                    return Parent as PropertyGridView.PropertyGridViewAccessibleObject;
```

2021-03-24 05:39 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
>                  (PropertyGridView.PropertyGridViewAccessibleObject)Parent;
As above

2021-03-24 05:39 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
> +            // Used by UIAutomation
???

2021-03-24 05:39 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
> +            private delegate void SelectDelegate(AccessibleSelection flags);
This should be above the .ctor.

2021-03-24 06:44 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
> +                    return Parent is null ? null : (PropertyGridView.PropertyGridViewAccessibleObject)Parent;
Thank you. The original code did not pass verification after enabling the NRT

2021-03-25 02:55 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
> +                    return Parent is null ? null : (PropertyGridView.PropertyGridViewAccessibleObject)Parent;
Still not fixed in the correct commit.

2021-03-25 02:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.CategoryGridEntryAccessibleObject.cs
> +                if (Parent is not PropertyGridView.PropertyGridViewAccessibleObject parent)
This must be fixed in the previous commit

2021-03-25 02:58 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
> +                    return !_owningPropertyDescriptorGridEntry.IsPropertyReadOnly;
I can't see this either be "Fixed names" or "Fixed code sorting" type of change.
This can belong to the previous commit however.

2021-03-25 07:54 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.CategoryGridEntryAccessibleObject.cs
> +                if (Parent is not PropertyGridView.PropertyGridViewAccessibleObject parent)
Moved to [Enable NRT](https://github.com/dotnet/winforms/pull/4700/commits/86c536b62a85b67be4e21d48b770bd88644934fe) commit

2021-03-25 07:55 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
> +                    return Parent is null ? null : (PropertyGridView.PropertyGridViewAccessibleObject)Parent;
Moved to [Enable NRT](https://github.com/dotnet/winforms/pull/4700/commits/86c536b62a85b67be4e21d48b770bd88644934fe) commit

2021-03-25 08:07 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
> +                    return !_owningPropertyDescriptorGridEntry.IsPropertyReadOnly;
In this commit I made [these changes](https://github.com/dotnet/winforms/pull/4700/commits/afa511143678656037f1d09c145d4c51eb76cef9#diff-991aa53b47b349b66f72e5d2ff49684b0638d3eca0e7f6f089806c786f021be4R15) , which made the `owner` property unavailable and I replaced it with the `_owningPropertyDescriptorGridEntry` property. This change is safe, because `owner` and `_owningPropertyDescriptorGridEntry` property are the same object.

2021-03-29 01:17 UTC, RussKie approved these changes

2021-03-29 01:18 UTC, merged