Fixing issue #4112 Replace deprecated SHILCreateFromPath with SHParse…
dotnet/winforms pull request #4707
Opened 2021-03-20 18:15 UTC by wreuel

…DisplayName

Fixes #

Issue #4112 changed the deprecated as should be

## Proposed changes

- Rewrite the code to use the SHParseDisplayName 

## Customer Impact

- None

## Regression? 

-   No

## Risk

- No

## Screenshots 

### Before

### After

## Test methodology 

- 
- 
- 

## Accessibility testing  

 

## Test environment(s) 

-

2021-03-20 18:16 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4707) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4707) before we can accept your contribution.<br/><br/>:x: wreuel [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4707)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=4707) it.</sub>

2021-03-20 19:03 UTC, wreuel commented
@RussKie see, it failed on the same test that are failing if I just clone the repo and run the  _.\build -test_ command, should I do something else? Hope we can solve this.

2021-03-22 02:04 UTC, RussKie requested changes
Can you please describe how you tested the change?

2021-03-22 02:04 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHCreateShellItem.cs
> +            if (SHParseDisplayName(path, IntPtr.Zero, out IntPtr pidl, 0, out zero).Succeeded())
If you're doing it as an `out` param, you can do this:
```suggestion
            if (SHParseDisplayName(path, IntPtr.Zero, out IntPtr pidl, 0, out uint _).Succeeded())
```

2021-03-22 02:07 UTC, RussKie commented
> run the _.\build -test_ command, should I do something else? Hope we can solve this.

Depends on what tests failed. Locale specific tests are known to fail (e.g. https://github.com/dotnet/winforms/issues/2734). So as clipboard-related tests.
If you provide more info, we can look into it.

2021-03-24 20:27 UTC, wreuel commented
> Can you please describe how you tested the change?

@RussKie  About the tests, I just used the one that existed before, that was using the SHILCreateFromPath, the test is ShellItemTests.SHParseDisplayName_ValidPath() and it is passing, if I did wrong please LMK, trying to help. :)

2021-03-24 20:29 UTC, wreuel commented
> > run the _.\build -test_ command, should I do something else? Hope we can solve this.
> 
> Depends on what tests failed. Locale specific tests are known to fail (e.g. #2734). So as clipboard-related tests.
> If you provide more info, we can look into it.

@RussKie  I added the US-EN location to my computer, now some tests are being skipped. As you can see in the image below.


![image](https://user-images.githubusercontent.com/6828665/112379044-975d4580-8cdf-11eb-8e52-488404a09eb2.png)

2021-03-25 02:35 UTC, RussKie commented
> added the US-EN location to my computer, now some tests are being skipped. As you can see in the image below.

You're running tests in x64, and these are x86 specific tests. This is expected.

2021-03-25 02:49 UTC, RussKie commented
> > Can you please describe how you tested the change?
> 
> About the tests, I just used the one that existed before, that was using the SHILCreateFromPath, the test is ShellItemTests.SHParseDisplayName_ValidPath() and it is passing, if I did wrong please LMK, trying to help. :)

Our automated tests don't have an exhaustive coverage, so likely there are code paths that aren't covered by those.
You also need to do an exploratory testing, i.e. run `WinformsControlsTest` test app (`Dialogs` sample) to verify that all code paths are executed, and the behaviour is expected.

`SHParseDisplayName` is only invoked through `GetShellItemForPath` which is used in three places:
![image](https://user-images.githubusercontent.com/4403806/112411076-64af5d80-8d70-11eb-8f45-31a5265fba5e.png)

So the bare minimum you need to run `FolderBrowserDialog`, `OpenFileDialog` and `SaveFileDialog` samples to confirm they still work as expected.

2021-03-25 02:50 UTC, RussKie reviewed
👍

2021-03-28 11:10 UTC, wreuel commented
@RussKie  so, I did the exploratory test, as you explained. And the Dialog are working fine.
Every path that goes to the GetShellItemForPath was hit correctly and the dialog opened on the path that was provided before hand on the config options. 

Also it worked fine when the path wasn't provided.

Do you need anything else?

2021-03-28 11:15 UTC, wreuel reviewed
I have done in a new commit

2021-03-29 01:03 UTC, RussKie approved these changes

2021-03-29 01:03 UTC, merged

2021-03-29 01:03 UTC, RussKie commented
Thank you!