Add a new virtual property StatusStripBorder to ToolStripProfessional…
dotnet/winforms pull request #4739
Opened 2021-03-29 08:35 UTC by Balkoth

# Summary

Currently, if you want to theme your application with a `ToolStripProfessionalRenderer`, there is an issue with the `StatusStrip` border, as the drawing routine uses a hardcoded value for the border color. A new virtual property should be added to the `ProfessionalColorTable` to customize that color.

# Proposed API

```
public class ToolStripProfessionalRenderer : ToolStripRenderer
{
    private void RenderStatusStripBorder(ToolStripRenderEventArgs e)
    {
-        e.Graphics.DrawLine(SystemPens.ButtonHighlight, 0, 0, e.ToolStrip.Width, 0);
+        e.Graphics.DrawLine(ColorTable.StatusStripBorder, 0, 0, e.ToolStrip.Width, 0);
    }
}
```
```
public static class ProfessionalColors
{
        [SRDescription(nameof(SR.ProfessionalColorsSeparatorLightDescr))]
        public static Color SeparatorLight => ColorTable.SeparatorLight;

+        [SRDescription(nameof(SR.ProfessionalColorsStatusStripBorderDescr))]
+        public static Color StatusStripBorder => ColorTable.StatusStripBorder;

        [SRDescription(nameof(SR.ProfessionalColorsStatusStripGradientBeginDescr))]
        public static Color StatusStripGradientBegin => ColorTable.StatusStripGradientBegin;
}
```
```
public class ProfessionalColorTable
{
        [SRDescription(nameof(SR.ProfessionalColorsSeparatorLightDescr))]
        public virtual Color SeparatorLight => FromKnownColor(KnownColors.msocbvcrCBSplitterLineLight);

+        [SRDescription(nameof(SR.ProfessionalColorsStatusStripBorderDescr))]
+        public virtual Color StatusStripBorder => FromKnownColor(KnownColors.msocbvcrCBShadow);

        [SRDescription(nameof(SR.ProfessionalColorsStatusStripGradientBeginDescr))]
        public virtual Color StatusStripGradientBegin => FromKnownColor(KnownColors.msocbvcrCBGradMainMenuHorzBegin);
}
```

# Example
Create a custom color table deriving from 'ProfessionalColorTable' and overwrite the new virtual property 'StatusStripBorder' with the desired color:
```
public sealed class MyColorTable : ProfessionalColorTable
{
    public override Color StatusStripBorder => Color.FromArgb(50, 50, 50);
}
```
Create a custom renderer deriving from 'ToolStripProfessionalRenderer' feeding the base constructor an instance of the custom color table created earlier:
```
public sealed class MyRenderer : ToolStripProfessionalRenderer
{
    public MyRenderer() : base(new MyColorTable())
    {
    }
}
```
Now just set the created renderer to be the renderer of the 'StatusStrip' where desired:
```
StatusStrip statusStrip = new StatusStrip();
statusStrip.Renderer = new MyRenderer();
```

2021-03-29 08:35 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4739) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4739) before we can accept your contribution.<br/><br/>:x: Balkoth [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=4739)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=4739) it.</sub>

2021-04-07 00:13 UTC, RussKie reviewed
👀

2021-04-07 00:13 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ProfessionalColorTable.cs
> +        public virtual Color StatusStripBorder => FromKnownColor(KnownColors.msocbvcrCBShadow);
Is this the same colour as in `SystemPens.ButtonHighlight`?

2021-04-07 00:13 UTC, RussKie commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>Border color to use on the top edge of the StatusStrip.</value>
It should align with other strings in [`ProfessionalColors` docs](https://docs.microsoft.com/dotnet/api/system.windows.forms.professionalcolors)
```suggestion
    <value>Gets the border color to use with the <see cref="StatusStrip"/>.</value>
```

2021-04-07 05:46 UTC, Balkoth commented on src/System.Windows.Forms/src/System/Windows/Forms/ProfessionalColorTable.cs
> +        public virtual Color StatusStripBorder => FromKnownColor(KnownColors.msocbvcrCBShadow);
Not on my system:

ButtonHighlight: "{Name=ButtonHighlight, ARGB=(255, 255, 255, 255)}"
msocbvcrCBShadow: "{Name=ff3b619c, ARGB=(255, 59, 97, 156)}"

I thought the best default would be to match the color of the ToolStripBorder but this may be to ambitous. Perhaps another approach like this could be used:

`public virtual Color StatusStripBorder => (_usingSystemColors) ? SystemColors.ButtonHighlight: FromKnownColor(KnownColors.msocbvcrCBShadow);`

2021-04-07 05:49 UTC, Balkoth commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>Border color to use on the top edge of the StatusStrip.</value>
The string you mention is in the docs on the page, but not in the winforms project. I used a string similar to what is documented on ToolStripBorder.

2021-04-07 06:34 UTC, RussKie commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>Border color to use on the top edge of the StatusStrip.</value>
Makes sense. Is it _always_ "top edge"?

2021-04-08 05:45 UTC, Balkoth commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>Border color to use on the top edge of the StatusStrip.</value>
As per `e.Graphics.DrawLine(ColorTable.StatusStripBorder, 0, 0, e.ToolStrip.Width, 0);` i would say yes.

2021-04-15 04:13 UTC, RussKie requested changes
We also need to see whether we can add a rendering test to assert correct colours are applied (e.g. something similar to `ToolStrip_RendersBackgroundCorrectly`).

2021-04-15 06:41 UTC, Balkoth commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolstripProfessionalRenderer.cs
> +            e.Graphics.DrawLine(ColorTable.StatusStripBorder, 0, 0, e.ToolStrip.Width, 0);
Yes you are right. I did not catch this as i neither have a preview version of .NET6 nor a preview version of VisualStudio installed. In this case intellisense is not working and i can't even compile the project.

2021-04-15 18:44 UTC, RussKie commented
You can grab it here https://visualstudio.microsoft.com/vs/preview/ 😉

2021-04-23 06:59 UTC, Balkoth commented
Is there an updated developer guide, what i have to have installed on my system in order to build this. The one here https://github.com/dotnet/winforms/blob/main/docs/developer-guide.md is outdated...

2021-04-23 07:08 UTC, RussKie commented
> The one here [https://github.com/dotnet/winforms/blob/main/docs/developer-guide.md](https://github.com/dotnet/winforms/blob/main/docs/developer-guide.md?rgh-link-date=2021-04-23T06%3A59%3A45Z) is outdated.

What are you finding in the guide that appears outdated?

2021-04-23 07:17 UTC, Balkoth commented
> Windows Forms requires the following workloads and components be selected when installing Visual Studio 2019 (16.8+):
> 
> Required Workloads:
> 
> .NET Desktop Development
> Desktop development with C++

This does not match what you really need in order to build the project.

2021-06-11 02:25 UTC, RussKie commented
> This does not match what you really need in order to build the project.

What isn't matching, and what's missing?

2021-06-11 06:13 UTC, Balkoth commented
You need preview versions of .NET an Visual Studio. I don't know what the exact versions are.

2021-06-13 10:01 UTC, RussKie commented
[.NET 6.0 requires VS 16.11](https://dotnet.microsoft.com/download/dotnet/6.0).
Strictly speaking VS isn't not need to build from command line (I _think_ it is needed for VC++ projects, but C++ isn't essential for your changes). Both `build.cmd` and `restore.cmd` download the required version of .NET 6.0 nightlies. The build procedure is described in the [docs](https://github.com/dotnet/winforms/blob/main/docs/building.md).

2021-07-09 08:23 UTC, Balkoth commented
So today i took the chance to give building winforms another try, and finally succeeded....
I did the changes mentioned here earlier, so feel free to review now.

2021-07-14 01:38 UTC, RussKie reviewed
👍 
We just need to add a test. 

Please have a look at [the docs](https://github.com/dotnet/winforms/blob/791e5bb26dcaeb6b35efea84d8b76c5c88944e4b/docs/testing.md#rendering-tests) and at `ToolStrip_RendersBackgroundCorrectly`, it should be reasonably straight forward to add a test to assert the border colour.

2021-07-14 01:38 UTC, RussKie commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
>  static System.Windows.Forms.ProfessionalColors.RaftingContainerGradientEnd.get -> System.Drawing.Color
This file is only modified at release time. Any changes to API must be recorded in "unshipped" file. Please revert these changes, and use analyzer auto-fixers to update the correct file.

2021-07-14 08:10 UTC, Balkoth commented
Relocated the API changes, and added a rendering test for the border color.

2021-07-26 06:00 UTC, RussKie reviewed
🚀 LGTM

2021-08-16 02:30 UTC, RussKie commented
@Balkoth a friendly nudge. If you think it is ready, set it ready for review, so we can take it. The 6.0 branches are getting closed in few days.

2021-08-16 05:23 UTC, RussKie commented
Please rebase and resolve the MC. Thanks

2021-08-16 06:45 UTC, Balkoth commented
Rebased. What is the MC and how do i resolve it?

2021-08-16 07:39 UTC, RussKie commented
MC stands for "merge conflict". Looks like your rebase didn't quite work, the build is failing.
```
D:\workspace\_work\1\s\src\System.Windows.Forms\src\PublicAPI.Unshipped.txt(1,1): error RS0025: The symbol '~override System.Windows.Forms.TrackBar.CreateAccessibilityInstance() -> System.Windows.Forms.AccessibleObject' appears more than once in the public API files. [D:\workspace\_work\1\s\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
##[error]src\System.Windows.Forms\src\PublicAPI.Unshipped.txt(1,1): error RS0025: (NETCORE_ENGINEERING_TELEMETRY=Build) The symbol '~override System.Windows.Forms.TrackBar.CreateAccessibilityInstance() -> System.Windows.Forms.AccessibleObject' appears more than once in the public API files.

Build FAILED.
```

2021-08-16 08:51 UTC, Balkoth commented
Done.

2021-08-16 09:04 UTC, RussKie approved these changes

2021-08-16 09:04 UTC, merged

2021-08-16 09:04 UTC, RussKie commented
Thank you