Removed CA1838 warning suppressions on p/invokes for StringBuilders.
dotnet/winforms pull request #4751
Opened 2021-03-31 12:55 UTC by AraHaan

Fixes #3983

## Proposed changes

- Fixes rule violations on CA1838 on the p/invokes.

## Customer Impact

- Minimal, the changed code should be to the p/invokes only.

## Regression? 

- Yes / No
No

## Risk

- Minimal

## Test methodology 

TODO: Test.
- 
- 
- 
 

## Test environment(s) 

- 

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.3
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.2.21155.3/

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  6.0.100-preview.2.21155.3 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
(used my browser on my mac this time to make changes)

Note: the code to the StringBuilders was attempted to try to be a minimal change, however it may require changing all the callsites too and simply not having StringBuilder parameters for the methods that wrap the actual p/invokes, this is due to the fact that StringBuilder was used for the buffers instead of string.

Also VB still needs done on it however.

This is opened as a draft because I think it may require a bit more work and testing on a windows system.

2021-03-31 13:04 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shlwapi/Interop.SHLoadIndirectString.cs
> +            HRESULT result = SHLoadIndirectString(pszSource, buf, cchOutBuf, IntPtr ppvReserved);
😂 I typed the type of the parameter as well in the call.

2021-03-31 13:05 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            lpClassName.Append(buf);
😂 I forgot ``_ = `` on this.

2021-03-31 13:06 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            buffer.Append(buf);
😂 Also forgot ``_ = `` on this.

2021-03-31 13:06 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            sb.Append(buf);
And this.

2021-03-31 13:09 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            lpszFile.Append(buf)
This as well.

2021-03-31 13:09 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            string buf;
I should have set this equal to ``string.Empty``.

2021-03-31 13:09 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.FormatMessageW.cs
> +            lpBuffer.Append(buf);
This is also needing to be changed.

2021-03-31 13:54 UTC, hughbe requested changes

2021-03-31 13:54 UTC, hughbe commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            if ((resultValue = DragQueryFileWInternal(hDrop, iFile, buf, (uint)lpszFile.Capacity)) == lpszFile.Capacity)
Should we not rent an array and pin it, avoiding the need for StringBuilder anyway? /cc @JeremyKuhne

2021-03-31 13:54 UTC, hughbe commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            GetTempFileName(tempDirName, prefixName, unique, buf);
ditto for all of these. It seems we're kind of just working around the supression warning rather than improving the quality of the code itself

2021-03-31 14:54 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            if ((resultValue = DragQueryFileWInternal(hDrop, iFile, buf, (uint)lpszFile.Capacity)) == lpszFile.Capacity)
I mean maybe a way to Rent buffers for the calls might work (perhaps use ``Span<char>`` for these?)

2021-03-31 22:19 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            if ((resultValue = DragQueryFileWInternal(hDrop, iFile, buf, (uint)lpszFile.Capacity)) == lpszFile.Capacity)
IIRC, ref-types are not blittable, and it have to be marshalled to the native code. Which is an overhead.

![image](https://user-images.githubusercontent.com/4403806/113217427-ab014100-92c9-11eb-9cd9-8a6867790245.png)

I _think_ the right way to do this is to make a call with a `NULL` argument, to find out the size of the require buffer, then rent the buffer and call again.
Without the added goo for `StringBuilder`, it is totally superficial (see [`ReadFileListFromHandle`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs#L397)):
https://github.com/dotnet/winforms/blob/69a326a9345471c26c5c1e4b9881a7b43e5b587c/src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs#L405-L418

2021-03-31 22:24 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.FormatMessageW.cs
> +            StringBuilder lpBuffer,
`SetValue` must pass a `stackalloc char[256]` to this method instead.

2021-03-31 22:28 UTC, RussKie reviewed
None of these API must have a `StringBuilder` as an input parameter, instead it's likely be a `char*`. 
Each callsite must be reviewed individually, and updated to correctly allocate buffers either by `stackalloc char[...]` or by `ArrayPool<char>.Shared.Rent(...)`.

2021-03-31 22:29 UTC, RussKie commented
Please consider how each of the changes will be tested.

2021-04-01 18:34 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            if ((resultValue = DragQueryFileWInternal(hDrop, iFile, buf, (uint)lpszFile.Capacity)) == lpszFile.Capacity)
`Span<char>` is definitely blittable (well as long as `CharSet` is set correctly). You do need to pin it.

2021-04-30 06:09 UTC, AraHaan commented
Alright

2021-05-01 08:17 UTC, AraHaan commented
<img width="706" alt="image" src="https://user-images.githubusercontent.com/15173749/116775934-e2335100-aa33-11eb-93fe-b95765c329b8.png">
So I am confused, on 1 callsite it calls ``GetClassName`` with ``null``, and the nMaxSize of ``0``, but nowhere in the docs it said that it will return it's actual size. Is that some sort of documentation issue perhaps to ``GetClassName``?

2021-05-01 11:46 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.FormatMessageW.cs
> +            StringBuilder lpBuffer,
I tried to do that and then nuked that method and went with ``ArrayPool<char>.Shared.Rent`` instead, and when finished (after assigning the values to a string if needed) I done ``ArrayPool<char>.Shared.Return`` to return the rented buffers.

2021-05-01 17:32 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            string result = buf.AsSpan().ToString().Trim('\0');
Something is causing the last 2 tests to fail here.

2021-05-02 21:36 UTC, weltkante reviewed
Might or might not be related to test failures, but I don't like the usage of `Trim` here
- its used in cases where the Windows API should be returning the exact size, why is it trimming in those cases?
- `Trim` also removes leading zero bytes which makes no sense at all, maybe use `TrimEnd` instead?
  - In practice this probably only leads to errors when there is garbage behind an "empty" string, you'd trim the leading zero byte indicating the empty string and return the garbage behind it instead. Which leads to the next point:
- it has massively different semantics from C, which looks for the first zero byte. Removing trailing (not leading) zero bytes often is equivalent if you can guarantee that there is no garbage beyond the first zero byte. I'm not sure if all Windows APIs do guarantee that (its not in the contract and if Windows write a longer string into the buffer, then shortens it, there may be garbage beyond the first zero byte, which you would expose because you only trim trailing zero bytes)
- the way you're using it allocates a string and then allocates another string if trimming is necessary - this could be optimized by trimming the span before converting it into a string

I know I'm being nitpicky here, since in practice it probably always works, but why take risks on edge case failures by performing an operation which is more convenient but having the wrong semantics? If the cost of doing it "correctly" is too high I'd suggest doing a `TrimEnd('\0')` on the span (not the string) as compromise.

That said, fixing any bugs triggering test failures is probably more important than going for style issues about Trim

2021-05-02 22:21 UTC, AraHaan commented
So all of these including ``FormatMessage`` returns the actual size of the stuff?

2021-05-03 07:12 UTC, weltkante commented
> So all of these including `FormatMessage` returns the actual size of the stuff?

yes:

[FormatMessage](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage):

> If the function succeeds, the return value is the number of TCHARs stored in the output buffer, excluding the terminating null character.

[DragQueryFileW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-dragqueryfilew):

> When the function copies a file name to the buffer, the return value is a count of the characters copied, not including the terminating null character.

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +        public static extern unsafe void GetTempFileName(string tempDirName, string prefixName, int unique, char* str);
How do I know the actual size of the temp file name string here?

Also since it uses a shared buffer, I think I would need to clear it first, then call, then strip the null bytes (same for ``SHLoadIndirectString``).

But then again cant I just use ``Path.GetTempFileName`` to get a temp file name instead and then delete this p/invoke for that?

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shlwapi/Interop.SHLoadIndirectString.cs
> +        public static extern unsafe HRESULT SHLoadIndirectString(string pszSource, char* psZOutBuf, uint cchOutBuf, IntPtr ppvReserved);
I probably should clear the rented buffer first, then call into this as well so then I can strip the nulls since the docs is not clear how to get the actual size from the loaded string (since the end of it could have random stuff at the end that should have been cleared first).

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                    UnsafeNativeMethods.GetClassName(hRef, valueChars, buf.Length);
I should have stored the size returned by this then Slice into it by doing ``.Slice(0, length)``.

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                                errorInfo = TrimNewline(buf.AsSpan().ToString().Trim('\0'));
I should have called ``.Slice(0, result)`` (Where I should rename ``result`` to ``length``).

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                                UnsafeNativeMethods.GetClassName(new HandleRef(null, lastParentHandle), valueChars, buf.Length);
I should have set ``len`` here as well.

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            string result = buf.AsSpan().ToString().Trim('\0');
I should have called ``.Slice(0, len)`` here too before ``.ToString()``.

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                char[] buf = ArrayPool<char>.Shared.Rent(512);
Since I do not know the actual size of the string returned, I think the best option is to null every byte inside of the rented array, then call ``SHLoadIndirectString``. That way ``Trim`` would work to strip the extra bytes from the string.

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                backgroundImageFileName = buf.AsSpan().ToString().Trim('\0');
I think I should remove the rented buffer and the p/invoke here for ``Path.GetTempFileName`` (Why have to do the same work more than once if the Path class already has it since forever basically 😄).

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
> +                        if (Shell32.DragQueryFileW(endropfiles->hDrop, 0, Kernel32.MAX_PATH, out string path) != 0)
I guess another option is return path and such as a tuple but did not want to break all the callers of it in the codebase.

2021-05-03 10:50 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            string result = buf.AsSpan().ToString().Trim('\0');
Yep the issue with tests here is that I do not store the length returned by ``GetClassName`` to an ``length`` variable then Slice into it with ``.Slice(0, length)``.

2021-05-11 13:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                    if (res == HRESULT.S_OK)
```suggestion
                    if (Shlwapi.SHLoadIndirectString(layoutDisplayName, valueChars, (uint)buf.Length, IntPtr.Zero).Succeeded())
```

2021-05-11 13:42 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                char[] buf = ArrayPool<char>.Shared.Rent(512);
Why not `stackalloc char[512]`? This makes the point of non-zero-init'ed buffer moot.

Also, even the buffer contains garbage, successful call to `SHLoadIndirectString` **will** have a valid null-terminated value in it.

2021-05-11 13:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                        string? result = buf.AsSpan().ToString().Trim('\0');
```suggestion
                        string? result = buf.AsSpan().SliceAtFirstNull().ToString();
```

2021-05-11 17:49 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +        public static unsafe uint DragQueryFileW(IntPtr hDrop, uint iFile, int capacity, out string lpszFile)
Sorry, I'm not the one to ask about unit testing, not what I'm good at ;) I doubt unit testing global interactions like drag'n'drop is easy though.

I guess you could fire up explorer in a known folder of your repo (via command line, so it starts in a known state) and then use accessibility APIs to determine where you have to do the simulated click & drag operations.

However thats all theory, I have no practical experience with doing UI automation testing.

If you meant verifying that WinForms is calling the API the right way, that would be on the same level of mocking that registry access is, either via .NET profiler integration (which can do adhoc rewriting/injecting) or native API hooking via Detours.

2021-05-11 19:21 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                char[] buf = ArrayPool<char>.Shared.Rent(512);
True, but then there is another issue as well, and that is resizing the ``buf`` span that was ``stackalloc``'d and having it automatically reflect the changes on the pin.

2021-05-13 01:00 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +        public static unsafe uint DragQueryFileW(IntPtr hDrop, uint iFile, int capacity, out string lpszFile)
The question revolved around - would you know how to create a valid `hDrop`, so we can call this method from a unit test and assert all code paths. Once we have it - the rest is easy :)

2021-05-13 01:03 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            lpszFile = buf.AsSpan().Slice(0, (int)resultValue).ToString().Trim('\0');
❗  This applies universally

2021-05-13 10:42 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +        public static unsafe uint DragQueryFileW(IntPtr hDrop, uint iFile, int capacity, out string lpszFile)
Its not very well documented but the docs for [CF_HDROP](https://docs.microsoft.com/en-us/windows/win32/shell/clipboard#cf_hdrop) say it is a pointer to a [DROPFILES](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/ns-shlobj_core-dropfiles) struct which was placed in HGLOBAL shared memory, and you can pass it to [DragQueryFile](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-dragqueryfilew) to extract the filenames.

Given this documentation I'd expect this to work with manually constructed DROPFILES structs. I don't know if the _other_ helper functions will work, but I'd expect DragQueryFile to work since thats documented for CF_HDROP and you are allowed to implement CF_HDROP yourself by filling in a DROPFILES struct.

PS: I don't know if DragQueryFiles cares about the struct beeing allocated in HGLOBAL shared memory, maybe thats only relevant for IDataObject.

2021-07-15 17:12 UTC, AraHaan commented
With https://github.com/dotnet/runtime/pull/54006 I think all the allocations should be done through that (since it supports ``realloc`` to allocate bigger buffers when needed.

2021-07-15 18:19 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
>              const int MaxClassName = 256;
I think this should be inlined into the allocation since the variable is only used once.

2021-07-15 18:43 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
>              const int MaxClassName = 256;
```suggestion
```

2021-07-15 18:43 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            int length;
```suggestion
```

2021-07-15 18:43 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            char[] buf = ArrayPool<char>.Shared.Rent(MaxClassName);
```suggestion
            char[] buf = stackalloc char[256];
```

2021-07-15 18:43 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            string result = buf.AsSpan().Slice(0, length).ToString().Trim('\0');
```suggestion
            return buf.AsSpan().SliceAtFirstNull().ToString();
```

2021-07-15 18:43 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            ArrayPool<char>.Shared.Return(buf, true);
```suggestion
```

2021-07-15 18:43 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            return result;
```suggestion
```

2021-07-15 20:18 UTC, weltkante commented
> With [dotnet/runtime#54006](https://github.com/dotnet/runtime/pull/54006) I think all the allocations should be done through that (since it supports `realloc` to allocate bigger buffers when needed).

Dedicated pooling can be significantly faster than going through the general purpose C runtime allocator, especially if theres an additional interop transition since we're coming from .NET. Also note that the native allocator will also reallocate + copy if it doesn't happen to have free adjacent space for growing the buffer, so the "convenient" realloc API can be just as expensive as naive reallocation (no idea how commonly that happens). I don't have an opinion on which to prefer, but to me it using the native allocator doesn't look an obviously better choice over .NET memory management and probably needs a separate investigation to determine whether its actually a gain over other techniques.

2021-07-15 22:17 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +using System.Buffers;
```suggestion
```

2021-07-15 23:18 UTC, RussKie reviewed
Do we have an existing test coverage for the changed methods?

2021-07-15 23:18 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
> +                    if (charlen is 0)
We use `is` for `null` checks only.

2021-07-15 23:20 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                char[] buf = ArrayPool<char>.Shared.Rent(MaxClassName);
```suggestion
                char[] buf = stackalloc char[256];
```

2021-07-15 23:23 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                ArrayPool<char>.Shared.Return(buf, true);
```suggestion
```

2021-07-15 23:23 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                return result;
```suggestion
```

2021-07-15 23:23 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                string result = buf.AsSpan().Slice(0, length).ToString().Trim('\0');
```suggestion
                return buf.AsSpan().SliceAtFirstNull().ToString();
```

2021-07-15 23:23 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                int length;
```suggestion
```

2021-07-15 23:23 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +using System.Buffers;
```suggestion
```

2021-07-15 23:25 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
> +                    if (charlen is 0)
Alright will apply that to my next batch fix.

2021-07-15 23:27 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
> +                    if (charlen is 0)
```suggestion
                    if (charlen == 0)
```

2021-07-15 23:30 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                                errorInfo = TrimNewline(buf.AsSpan().Slice(0, (int)length).ToString().Trim('\0'));
```suggestion
                                errorInfo = TrimNewline(buf.AsSpan().Slice(0, (int)length).SliceAtFirstNull().ToString());
```

2021-07-15 23:30 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                        ArrayPool<char>.Shared.Return(buf, true);
```suggestion
```

2021-07-15 23:31 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +
```suggestion
```

2021-07-15 23:32 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                        char[] buf = ArrayPool<char>.Shared.Rent(256);
```suggestion
                        char[] buf = stackalloc char[256];
```

2021-07-15 23:32 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +using System.Buffers;
```suggestion
```

2021-07-15 23:34 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            string result = buf.AsSpan().Slice(0, len).ToString().Trim('\0');
```suggestion
                            string result = buf.AsSpan().Slice(0, len).SliceAtFirstNull().ToString();
```

2021-07-15 23:35 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            ArrayPool<char>.Shared.Return(buf, true);
```suggestion
```

2021-07-15 23:35 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +using System.Buffers;
```suggestion
```

2021-07-15 23:36 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            char[] buf = ArrayPool<char>.Shared.Rent(capacity);
```suggestion
                            char[] buf = stackalloc char[capacity];
```

2021-07-15 23:39 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                char[] buf = ArrayPool<char>.Shared.Rent(512);
```suggestion
                char[] buf = stackalloc char[512];
```

2021-07-15 23:40 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                        ArrayPool<char>.Shared.Return(buf, true);
```suggestion
```

2021-07-15 23:40 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +using System.Buffers;
```suggestion
```

2021-07-15 23:44 UTC, AraHaan commented
As for the changed methods, I think tests are lacking. Instead I think they are tested indirectly by the actual things they are used for to implement the things that are tested.

2021-07-16 02:50 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            char[] buf = ArrayPool<char>.Shared.Rent(Kernel32.MAX_PATH);
```suggestion
            Span<char> buf = ArrayPool<char>.Shared.Rent(Kernel32.MAX_PATH);
```

2021-07-16 02:51 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            fixed (char* valueChars = &buf[0])
```suggestion
            fixed (char* valueChars = buf)
```

2021-07-16 02:56 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                char[] buf = stackalloc char[256];
```suggestion
                Span<char> buf = stackalloc char[256];
```

2021-07-16 02:56 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                fixed (char* valueChars = &buf[0])
```suggestion
                fixed (char* valueChars = buf)
```

2021-07-16 02:57 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                        fixed (char* valueChars = &buf[0])
```suggestion
                        fixed (char* valueChars = buf)
```

2021-07-16 02:57 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                        char[] buf = stackalloc char[256];
```suggestion
                        Span<char> buf = stackalloc char[256];
```

2021-07-16 02:58 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            char[] buf = stackalloc char[capacity];
```suggestion
                            Span<char> buf = stackalloc char[capacity];
```

2021-07-16 02:58 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            fixed (char* valueChars = &buf[0])
```suggestion
                            fixed (char* valueChars = buf)
```

2021-07-16 02:59 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                fixed (char* valueChars = &buf[0])
```suggestion
                fixed (char* valueChars = buf)
```

2021-07-16 03:00 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                char[] buf = stackalloc char[512];
```suggestion
                Span<char> buf = stackalloc char[512];
```

2021-07-16 03:00 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
>                  {
```suggestion
```

2021-07-16 03:01 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                }
```suggestion
```

2021-07-16 03:02 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            fixed (char* valueChars = &buf[0])
```suggestion
            Span<char> buf = stackalloc char[256];
            fixed (char* valueChars = buf)
```

2021-07-16 03:04 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +using System.Buffers;
```suggestion
```

2021-07-16 03:08 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            return result;
```suggestion
            return buf.AsSpan().SliceAtFirstNull().ToString();
```

2021-07-16 03:10 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            int length;
```suggestion
```

2021-07-16 03:15 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +                }
```suggestion
                // Allocating a bigger buffer each time the function fails by MAX_PATH after starting
                // with MAX_PATH is not possible with stack allocations, as such we must allocate exactly
                // Kernel32.MAX_UNICODESTRING_LEN of memory so that way we never fail in the first place.
                _ = GetModuleFileName(hModule, valueChars, buf.Length);
                if (Marshal.GetLastWin32Error() == ERROR.INSUFFICIENT_BUFFER)
                {
                    // failure getting the module file names. Throw???
                }
```

2021-07-16 03:16 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +using System.Buffers;
```suggestion
```

2021-07-16 03:20 UTC, AraHaan commented
It seems that once cant stackalloc after doing an stackalloc inside of a fixed block to the actual pointer obtained from the span and then assign it to the span to ensure it's bigger so it seems all those calls that expects to grow every time it sees failure should instead be allocating exactly Kernel32.MAX_UNICODESTRING_LEN of memory and then calling the function a single time to avoid any failures. Anyone know if this would regress anything in particular if I make that change?

2021-07-16 03:32 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                return buf.AsSpan().SliceAtFirstNull().ToString();
```suggestion
                return buf.SliceAtFirstNull().ToString();
```

2021-07-16 03:33 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
>              int noOfTimes = 1;
```suggestion
```

2021-07-16 03:33 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            return buf.AsSpan().SliceAtFirstNull().ToString();
```suggestion
            return buf.SliceAtFirstNull().ToString();
```

2021-07-16 03:34 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                                errorInfo = TrimNewline(buf.AsSpan().Slice(0, (int)length).SliceAtFirstNull().ToString());
```suggestion
                                errorInfo = TrimNewline(buf.Slice(0, (int)length).SliceAtFirstNull().ToString());
```

2021-07-16 03:36 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            string result = buf.AsSpan().Slice(0, len).SliceAtFirstNull().ToString();
```suggestion
                            string result = buf.Slice(0, len).SliceAtFirstNull().ToString();
```

2021-07-16 03:37 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +
```suggestion
```

2021-07-16 03:37 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                        string? result = buf.AsSpan().SliceAtFirstNull().ToString();
```suggestion
                        string? result = buf.SliceAtFirstNull().ToString();
```

2021-07-16 03:38 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            return buf.AsSpan().SliceAtFirstNull().ToString();
```suggestion
            return buf.SliceAtFirstNull().ToString();
```

2021-07-16 03:52 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                    length = UnsafeNativeMethods.GetClassName(hRef, valueChars, buf.Length);
```suggestion
                    _ = UnsafeNativeMethods.GetClassName(hRef, valueChars, buf.Length);
```

2021-07-16 04:28 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +                length = UnsafeNativeMethods.GetClassName(new HandleRef(null, hWnd), valueChars, buf.Length);
```suggestion
                _ = UnsafeNativeMethods.GetClassName(new HandleRef(null, hWnd), valueChars, buf.Length);
```

2021-07-16 04:29 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
> +                        if (Shell32.DragQueryFileW(endropfiles->hDrop, 0, Kernel32.MAX_PATH, out string path) != 0)
```suggestion
                        if (Shell32.DragQueryFileW(endropfiles->hDrop, 0, out string path) != 0)
```

2021-07-16 04:30 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
> +                uint count = Shell32.DragQueryFileW(hdrop, 0xFFFFFFFF, 0, out string _);
```suggestion
                uint count = Shell32.DragQueryFileW(hdrop, 0xFFFFFFFF, out string _);
```

2021-07-16 04:30 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
> +                    uint charlen = Shell32.DragQueryFileW(hdrop, i, Kernel32.MAX_PATH, out string str);
```suggestion
                    uint charlen = Shell32.DragQueryFileW(hdrop, i, out string str);
```

2021-07-16 04:34 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            if (capacity == 0 || iFile == 0xFFFFFFFF)
```suggestion
            if (iFile == 0xFFFFFFFF)
```

2021-07-16 04:36 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +        public static unsafe uint DragQueryFileW(IntPtr hDrop, uint iFile, int capacity, out string lpszFile)
```suggestion
        public static unsafe uint DragQueryFileW(IntPtr hDrop, uint iFile, out string lpszFile)
```

2021-07-16 04:38 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            char[] buf = ArrayPool<char>.Shared.Rent(capacity);
```suggestion
            // Allocating a buffer with stackalloc cannot be resized later, as such we must allocate
            // the buffer with the size of Kernel32.MAX_UNICODESTRING_LEN.
            Span<char> buf = stackalloc char[Kernel32.MAX_UNICODESTRING_LEN];
```

2021-07-16 04:39 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            fixed (char* valueChars = &buf[0])
```suggestion
            fixed (char* valueChars = buf)
```

2021-07-16 04:40 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            uint resultValue;
```suggestion
```

2021-07-16 04:46 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
>                  {
```suggestion
                resultValue = DragQueryFileWInternal(hDrop, iFile, valueChars, (uint)buf.Length);
```

2021-07-16 04:47 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
>                  }
```suggestion
```

2021-07-16 04:48 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            ArrayPool<char>.Shared.Return(buf, true);
```suggestion
```

2021-07-16 04:49 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            lpszFile = buf.AsSpan().Slice(0, (int)resultValue).ToString();
```suggestion
            lpszFile = buf.AsSpan().Slice(0, (int)resultValue).SliceAtFirstNull().ToString();
```

2021-07-16 05:47 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +using System.Buffers;
```suggestion
```

2021-07-16 05:48 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            lpszFile = buf.AsSpan().Slice(0, (int)resultValue).SliceAtFirstNull().ToString();
```suggestion
            lpszFile = buf.Slice(0, (int)resultValue).SliceAtFirstNull().ToString();
```

2021-07-16 10:38 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            return buf.SliceAtFirstNull().ToString();
```suggestion
            string result = buf.SliceAtFirstNull().ToString();
            return result;
```

2021-07-16 10:40 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                return buf.SliceAtFirstNull().ToString();
```suggestion
                string result = buf.SliceAtFirstNull().ToString();
                return result;
```

2021-07-16 10:41 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            return buf.SliceAtFirstNull().ToString();
```suggestion
            string result = buf.SliceAtFirstNull().ToString();
            return result;
```

2021-07-16 11:54 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            Span<char> buf = stackalloc char[256];
```suggestion
            Span<char> buf = stackalloc char[256];
            string result;
```

2021-07-16 11:54 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +                _ = UnsafeNativeMethods.GetClassName(new HandleRef(null, hWnd), valueChars, buf.Length);
```suggestion
                _ = UnsafeNativeMethods.GetClassName(new HandleRef(null, hWnd), valueChars, buf.Length);
                result = buf.SliceAtFirstNull().ToString();
```

2021-07-16 11:55 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            string result = buf.SliceAtFirstNull().ToString();
```suggestion
```

2021-07-16 11:58 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +                }
```suggestion
                }

                result = buf.SliceAtFirstNull().ToString();
```

2021-07-16 11:59 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            string result = buf.SliceAtFirstNull().ToString();
```suggestion
```

2021-07-16 11:59 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            Span<char> buf = stackalloc char[Kernel32.MAX_UNICODESTRING_LEN];
```suggestion
            Span<char> buf = stackalloc char[Kernel32.MAX_UNICODESTRING_LEN];
            string result;
```

2021-07-16 12:01 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                Span<char> buf = stackalloc char[256];
```suggestion
                Span<char> buf = stackalloc char[256];
                string result;
```

2021-07-16 12:01 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                    _ = UnsafeNativeMethods.GetClassName(hRef, valueChars, buf.Length);
```suggestion
                    _ = UnsafeNativeMethods.GetClassName(hRef, valueChars, buf.Length);
                    result = buf.SliceAtFirstNull().ToString();
```

2021-07-16 12:01 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                string result = buf.SliceAtFirstNull().ToString();
```suggestion
```

2021-07-23 07:09 UTC, AraHaan commented
@RussKie mind helping point out the problematic part of the code that makes the 2 tests fail?

2021-07-23 07:38 UTC, RussKie commented
I'll try to have a look next week.
________________________________
From: AraHaan ***@***.***>
Sent: Friday, 23 July 2021 5:10 PM
To: dotnet/winforms ***@***.***>
Cc: Igor Velikorossov ***@***.***>; Mention ***@***.***>
Subject: Re: [dotnet/winforms] Removed CA1838 warning suppressions on p/invokes for StringBuilders. (#4751)


@RussKie<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRussKie&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7C0358c16886fe4b04349308d94da8e669%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637626210086208851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qImiimrqwv0DG7kQ1P7GKVi0dZK2RvO7bdVmbaSDhII%3D&reserved=0> mind helping point out the problematic part of the code that makes the 2 tests fail?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fpull%2F4751%23issuecomment-885445265&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7C0358c16886fe4b04349308d94da8e669%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637626210086208851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9QJFz6VTnw1VbWBeoBRwhiutZQFR%2BRcQwvc5vL%2BinsA%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABBTEXSW4GF3AG3KSCOLVGTTZEIU3ANCNFSM42ESXSFQ&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7C0358c16886fe4b04349308d94da8e669%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637626210086218805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=salfLNcEeMfl7WOd%2FHKNRo7dFGpNsaQr%2Fe1ZXnHIUa0%3D&reserved=0>.

2021-07-25 00:30 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +        public static extern unsafe int GetClassName(HandleRef hwnd, char* lpClassName, int nMaxCount);
This API is not imported for unicode, see [doc for DllImport](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.charset?view=net-5.0) - the default if nothing is specified is `CharSet.Ansi`

Previously the marshaling infrastructure would have translated the StringBuilder buffer from Ansi to Unicode.

Now `GetClassName` does have a unicode version so I think the `Charset = CharSet.Auto` (or `Unicode`) can be added to the `DllImport` - what do you think? Otherwise the caller needs to pass a byte buffer (instead of a char buffer) and translate from Ansi to Unicode using the current Ansi Codepage of Windows (I think WinForms has helper methods for that somewhere, it came up before as a breaking change in the dotnet runtime).

2021-07-25 01:48 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +        public static extern unsafe int GetClassName(HandleRef hwnd, char* lpClassName, int nMaxCount);
it should not be breaking to only use unicode p/invoke calls in winforms right?

2021-07-25 08:50 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +        public static extern unsafe int GetClassName(HandleRef hwnd, char* lpClassName, int nMaxCount);
> it should not be breaking to only use unicode p/invoke calls in winforms right?

It can break things because the HWND handles remember if they were created via Unicode or Ansi API, so when interacting with foreign handles you sometimes need to use `IsWindowUnicode` and switch based on that, but its very rare that this is necessary, most window APIs auto-translate everything.

I don't think `GetClassName` would cause issues when switched.

2021-07-25 09:01 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +        public static extern unsafe int GetClassName(HandleRef hwnd, char* lpClassName, int nMaxCount);
Alright I will see if it will fix this PR then.

2021-07-25 10:32 UTC, AraHaan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            return result;
```suggestion
            fixed (char* valueChars = buf)
            {
                _ = UnsafeNativeMethods.GetClassName(new HandleRef(null, hWnd), valueChars, buf.Length);
            }

            return buf.SliceAtFirstNull().ToString();
```

2021-07-25 10:32 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                return result;
```suggestion
                fixed (char* valueChars = buf)
                {
                    _ = UnsafeNativeMethods.GetClassName(hRef, valueChars, buf.Length);
                }

                return buf.SliceAtFirstNull().ToString();
```

2021-07-25 10:32 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            string result;
```suggestion
```

2021-07-25 10:32 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
>              }
```suggestion
                }
            }
```

2021-07-25 10:32 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            return result;
```suggestion
            return buf.SliceAtFirstNull().ToString();
```

2021-07-25 15:45 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +        public static extern unsafe int GetClassName(HandleRef hwnd, char* lpClassName, int nMaxCount);
It seems to make all the tests pass with the unicode version of ``GetClassName``.

2021-07-25 15:48 UTC, AraHaan commented
I think these changes are just about ready to merge with the exception of needing to test some of the changed P/Invokes directly. It looks like GetClassName however does get tested directly in tests however.

2021-09-01 07:08 UTC, AraHaan commented
@RussKie is this too late for .NET 6, or should it be fine for it?

2021-09-01 07:35 UTC, RussKie commented
We're currently in RC2 stage, and I don't think we'd be willing take this change into .NET 6.0 as there's very little runway left for testing and making sure we haven't inadvertently regressed. But we'll still gladly take this into .NET 7.0 :)

2021-11-15 06:27 UTC, AraHaan commented
@RussKie Ijust thought of it but should we consider porting all the manual interop code with TerraFX.Interop.Windows as an package for the internal implementation details?

However doing so may require marking more things with ``unsafe`` however it does have added benefits as well too of it using clangsharp for the bindings it has inside of it.

2021-11-15 06:47 UTC, RussKie commented
We can't take any external dependencies.

2021-11-15 09:44 UTC, AraHaan commented
I had to rebase it in codespaces for now.

2022-04-05 04:53 UTC, RussKie commented
@AraHaan gentle nudge to see if you planning to work on this. If you think it's ready - please take it out of the draft.

2022-04-07 20:48 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +                lpszFile = string.Empty;
this would confuse the use case. what are we gaining by making `lpszFile` non-nullable here? can't it be `out string?`

2022-04-07 20:48 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +                    // failure getting the module file names. Throw???
Given the assumption that we expect no further `INSUFFICIENT_BUFFER` error, we should throw error and fail fast or return appropriately.

2022-04-07 20:48 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +            return errorInfo.AsSpan().Slice(0, index + 1).ToString();
do we need this conversion here? or is it more performent?

2022-04-07 20:48 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            int capacity = 32;
This seems arbitrary number. `capacity = len +5;` seems good enough here. Better yet, go with max length `256` for `classname`  allocation and avoid calling the native method twice.

2022-04-07 20:48 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            if (result == "#32770")
A comment for this `class name  #32770`  would help.

2022-04-07 20:48 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
> +                    string fullPath = Path.GetFullPath(str);
An empty string here would throw exception. Should we update code to handle it?

2022-04-07 21:47 UTC, JeremyKuhne requested changes
A few key comments:

1. Don't use unbounded stackalloc or stackalloc in a loop. It's best to keep allocations relatively small (<1K) and prefer using ArrayPool for buffers if you're not in perf critical code and you're over 520 bytes (double MAX_PATH).
2. Use meaningful, unabbreviated variable names. The only place we don't follow that rule is in native signatures.

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            Span<char> buf = stackalloc char[Kernel32.MAX_UNICODESTRING_LEN];
Creating a 64K stack buffer is **not** good- you're likely to cause stack overflows. You shouldn't ever do this for more than 1K at most. Even that is pushing it a bit.

Just follow the original logic here and rent an array from `ArrayPool<char>.Shared`. Make sure you return the array when you're done getting the string out.

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +            Span<char> buf = stackalloc char[Kernel32.MAX_UNICODESTRING_LEN];
Same as before- do not stack alloc huge buffers. Rent/return from the shared ArrayPool and follow the same logic.

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +                    string str = UnsafeNativeMethods.GetModuleFileNameLongPath(NativeMethods.NullHandleRef);
nit: don't use 'str' for your variable names- a better choice would be `path`.

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                    _ = UnsafeNativeMethods.GetClassName(hRef, valueChars, buf.Length);
nit: fail here if it returns zero- throw `new Win32Exception()`

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                Span<char> buf = stackalloc char[256];
nit: don't use abbreviations like this- variable names should generally be full words: `buffer`

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                        Span<char> buf = stackalloc char[256];
nit: `buffer`

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                                255,
Should be `buffer.Length`, not a constant value.

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                            if (length == 0)
Really should test this code to see what it does with insufficient buffer sizes and handle growth if needed. Can't stack alloc in that case. Fine for that to be a follow up issue.

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
>              int index = errorInfo.Length - 1;
Much better to have a static array of these chars and just call `string.Trim(s_newlineCharacters)`.

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            int capacity = 32;
Yes, this is documented as having a max class name of 256, so just go with that and remove any looping. https://docs.microsoft.com/windows/win32/api/winuser/ns-winuser-wndclassw

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            Span<char> buf = stackalloc char[capacity];
Do not stackalloc inside a loop as that can also lead to stack overflows.

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
> +                    uint charlen = Shell32.DragQueryFileW(hdrop, i, out string str);
nit: don't use `str` use `fileName` (which has meaning) or when something like this is totally open-ended use `value`. `charlen` should be `length`.

2022-04-07 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
> +                    string fullPath = Path.GetFullPath(str);
Yes, just add the condition above. `if (length == 0 || string.IsNullOrEmpty(fileName))`

2022-04-21 18:20 UTC, dreddy-work commented
@AraHaan , can you take a look at the feedback and help get this closure?

2022-04-22 00:21 UTC, AraHaan commented
Sure, but this will need to be rebased to the tip of main as well.

2022-04-23 11:28 UTC, AraHaan commented
Sorry for the wait, just got back into rechecking out the branch on my computer (it seems I accidentally deleted the winforms repo locally).

2022-04-23 11:41 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
> +                    string fullPath = Path.GetFullPath(str);
Wait why do I set fullPath only to not use it in the next line? Is it possible I could have gotten it wrong here?

2022-04-23 11:56 UTC, AraHaan commented
I have made a few of the listed changes at the same time of the rebase using Visual Studio.

2022-04-23 12:04 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
> +                    _ = UnsafeNativeMethods.GetClassName(hRef, valueChars, buf.Length);
What would be the exception message here then?

2022-04-23 12:11 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +            return errorInfo.AsSpan().Slice(0, index + 1).ToString();
It might actually be just as performant (or slightly less, I have not tested it's performance really to compare them).

2022-04-23 12:22 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
>              int index = errorInfo.Length - 1;
It looks like I could have just done ``ReplaceLineEndings(string.Empty);`` to do the same thing.

2022-04-23 12:40 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +            return errorInfo.AsSpan().Slice(0, index + 1).ToString();
I have since discovered that the whole ``TrimNewline`` could be replaced with ``ReplaceLineEndings(string.Empty);`` that was added to string in .NET 6.

https://docs.microsoft.com/en-us/dotnet/api/system.string.replacelineendings?view=net-6.0

2022-04-23 15:48 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +                lpszFile = string.Empty;
I had problems with it being ``out string?`` so I had to change it to ``ref string?``.

2022-04-23 15:51 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
> +            Span<char> buf = stackalloc char[Kernel32.MAX_UNICODESTRING_LEN];
I decided to use arrays to convert implicitly to ``Span<char>`` which is then passed into the p/invoke.

This should *hopefully* avoid the stack buffer and the renting from ``ArrayPool``.

2022-04-23 16:31 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
> +                        string path = string.Empty;
for some reason nullable is disabled for this file.

2022-04-23 16:40 UTC, AraHaan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
> +                    // failure getting the module file names. Throw???
What would you think the error message should be in this case? ``"Error getting module file names."`` perhaps?

2022-04-23 23:22 UTC, AraHaan commented
cc: @RussKie I tried to fix the test failure.

2022-06-22 03:52 UTC, elachlan commented
There is a pretty extensive conversion on the performance and other implications in https://github.com/dotnet/msbuild/pull/7186

This might help if you need guidance.

2022-06-22 04:30 UTC, AraHaan commented
Yeah, I think I should migrate this to use the DllImport generator added in .NET 7 so It can help me with passing spans into the signatures of the p/invokes.

2022-06-24 01:46 UTC, elachlan commented
> Yeah, I think I should migrate this to use the DllImport generator added in .NET 7 so It can help me with passing spans into the signatures of the p/invokes.

@RussKie would the team be okay using: https://github.com/microsoft/CsWin32 ? It reduces the amount of code considerably.

2022-06-24 01:59 UTC, RussKie commented
IIRC, we'd discussed https://github.com/microsoft/CsWin32 and https://github.com/terrafx/terrafx.interop.windows (and maybe some other option) with @JeremyKuhne, and arrived to a conclusion that it was undesirable for few reasons. One is that it'd introduce external dependencies, which we'd have to ship (with all related issues such as payload size, packaing, signing, etc). Also, we strive to import only those definitions that we use (i.e., less code - less to compile - less to jit, etc.). And lastly, some of our imports are optimised (e.g., we use `IHandle` instead of `SafeHandle`).

As per https://github.com/dotnet/winforms/issues/4136 we do plan to use COM source generators when those are ready (.NET 8?), and replace the manual COM wrappers that @kant2002 has kindly built for us in .NET 7. 
@gpetrou is kindly helping us to [migrate to `LibraryImport` definitions from `DllImport`](https://github.com/dotnet/winforms/pulls?q=is%3Apr+sort%3Aupdated-desc+LibraryImport+is%3Amerged), and this is the recommended route for now.

2022-06-24 02:15 UTC, AraHaan commented
Technically what is unused in TerraFX.Interop.Windows can be trimmed, however how it is currently the WindowsDesktop profiles both do not support trimming at all yet to provide such a space savings.

Also as for external dependencies, wasn't TerraFX made a member of the DNF despite it staying in it's own github organization (it might be me misremembering and it being ClangSharp instead)?

If all else fails, winforms and wpf could manually use clangsharp instead if that route is desired as well.

2022-06-24 07:12 UTC, elachlan commented
> IIRC, we'd discussed https://github.com/microsoft/CsWin32 and https://github.com/terrafx/terrafx.interop.windows (and maybe some other option) with @JeremyKuhne, and arrived to a conclusion that it was undesirable for few reasons. One is that it'd introduce external dependencies, which we'd have to ship (with all related issues such as payload size, packaing, signing, etc). Also, we strive to import only those definitions that we use (i.e., less code - less to compile - less to jit, etc.). And lastly, some of our imports are optimised (e.g., we use `IHandle` instead of `SafeHandle`).

@AArnott - does using cswin32 result in a shippable dependency or is it just design/build time? Also would adding optimisations such as IHandle be possible?

@RussKie - as far as I can tell cswin32 only generates the definitions you use. which would keep the size down. Only problem I see would be relying on the CSWin32 team to update any bad definitions. But I think that they are keen to keep it updated.

2022-06-24 14:06 UTC, AArnott commented
@elachlan CsWin32 generates code directly into your compilation. The only (recommended) runtime dependency it adds is to System.Memory, which most compilations already have anyway. 
As for optimizations, I'm not familiar with `IHandle`. But I'll tell you that the code we emit it first and foremost designed to be as close to 'bare metal' perf as you can get. No one should ever have to avoid using CsWin32 for perf reasons. In _addition_ to the `extern` methods themselves which don't shy away from pointers and using native handle types (avoiding SafeHandles), we _also_ generate what I call 'friendly overloads' which use `SafeHandle`, `const char*` with `string`, etc. Most folks favor the friendly overloads, but the extern methods themselves are always there for those perf-critical paths. 

CsWin32 is opt-in per-API. If you ask for `CreateFile` the only thing you get is `CreateFile` and the enums to support its method signature. If you don't like how a particular supporting enum or struct type is generated, you can copy and paste it from generated code into your own source controlled code and change it all you want. CsWin32 will suppress generation of types that you declare yourself and emit references to yours. That is, if you don't use the `partial` modifier. If you *do* use the `partial` modifier, we assume you want to contribute more members to our generated type.

I'd love to see WinForms replace their interop code with CsWin32-generated code and would be happy to support you in doing so. There are bugs in some of the generated code, but we're working them down in a priority order and I think there are only a few left that don't block adoption except for those APIs that are impacted. I recommend folks start migration by adding a CsWin32 package reference and replace just a few APIs with generated ones to get a feel for it, then migrate gradually over time, so if you do need any of the APIs that may still be generated incorrectly, it only blocks adoption for those particular APIs, and we'd be happy to hear feedback on anything blocking.

CC: @russkie

2022-06-24 18:04 UTC, kant2002 commented
I'm personally for using CsWin32 instead of manually looking at the docs and writing PInvokes. I think that work may not start earlier then .NET 8 unless somebody really motivated can reduce risks by explaining how that would not be an issue.

Practical matters:
1. In this project interop declarations are split by DLLs in which function declared. Does CsWin32 support that way of code grouping?
2. To have buy-in from the team, would be interesting to see examples of codegen and compare with current `LibraryImport` code. LibraryImportGenreator gives ability to use very low overhead PInvoke. Also that maybe interesting for broader community as a whole.
3. `IHandle` is internal pattern which provide lightweight alternative to `SafeHandle`. See https://github.com/dotnet/winforms/blob/86eff93d9e48c45c411d3fb884e523300664125b/src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SendMessageW.cs#L18-L27 for the usage. Does CsWin32 support this kind of patterns. LibraryImportGenerator most likely would support that.

2022-06-24 18:44 UTC, JeremyKuhne commented
Tagging @tannergooding as we're talking about TerraFX here as well.

We have a few design principles we're trying to achieve with our interop code:

- Going close to bare metal to avoid performance issues (everything is blittable, no `SafeHandle`, etc.).
- Using stack based scopes (ref structs) to lightly and safely close out resources (`if def`'ed to classes in debug for tracking of proper usage).
- Adding wrappers (like the `IHandle` ones) to handle keeping objects alive and other safe usage related.
- Avoiding verbosity by removing redundancy in Windows "enums" (`COPY.COPY_FILE_NO_OFFLOAD` -> `COPY.FILE_NO_OFFLOAD`). This isn't a deal-breaker, but nice-to-have.
- No legacy COM interop (in progress)
- Expressing the documented dll location in the model `Interop.User32`

We're trying to find the right balance between making things fast and pushing contributors to the pit of success. If we could generate nearly the same interop surface area with a library that falls under Microsoft's ownership or the .NET Foundation I'd be very keen on making the jump for .NET 8.  For CsWin32 I think that would mean:

1. Being able to put the methods in the same layout we currently have (`Interop` static partial class with dll name partial classes within).
1. Being able to turn off "easy" wrapper generation, preferably per API.
1. Being able to say that we want generation with `private` so we can enforce using our wrappers in the main assembly.

@AArnott I'm happy to talk more about it with you whenever you want.

cc: @merriemcgaw

2022-06-24 20:36 UTC, AArnott commented
> In this project interop declarations are split by DLLs in which function declared. Does CsWin32 support that way of code grouping?

No. That is how the dotnet/pinvoke project divided it too, but CsWin32 uses namespaces from win32metadata that the SDK PM (@mikebattista) worked on for quite a while. All the pinvoke extern methods go into a single PInvoke class, and the types that support them are divided across the namespaces based on use case. This made the functions much easier to find for many customers that couldn't otherwise figure out that, for example, when they asked for CreateFile that would go off to some namespace and class while another method would go elsewhere. Folks in C++ don't tend to have to think about what module a function is exported from, so in C# we didn't require them to think about that either.

> To have buy-in from the team, would be interesting to see examples of codegen and compare with current LibraryImport code. LibraryImportGenreator gives ability to use very low overhead PInvoke. Also that maybe interesting for broader community as a whole.

It's there for you to try out. Or we could set up a meeting to review it together. As I mentioned earlier, we already have fairly low overhead, and I suspect the perf is comparable with the source generator you mentioned except perhaps when using AOT, and I don't know whether that is applicable to WinForms.

> IHandle is internal pattern which provide lightweight alternative to SafeHandle... LibraryImportGenerator most likely would support that

I'd have to see `IHandle`, and understand how it strikes a better balance between using native handles and SafeHandle. CsWin32 already supports both of these ends, so if you can help me understand how IHandle is better than either end, I can tell you what it would take to do so with CsWin32. That said, I'd be very surprised if LibraryImportGenerator could generate code that would work with a custom handle type that you defined.

> Going close to bare metal to avoid performance issues (everything is blittable, no SafeHandle, etc.).

CsWin32 can do that with a switch. In which case absolutely no marshaling occurs at all, and there are no SafeHandles. I would expect it to have better performance than LibraryImportGenerator which as I understand it still does marshaling... just in your own library code instead of leaving it to the runtime.

> Using stack based scopes (ref structs) to lightly and safely close out resources

That's an interesting idea that we've only spent a few minutes talking about. I'd like to learn more about where/when/how you would use this. Maybe CsWin32 can emit types to help you with this.

> Avoiding verbosity by removing redundancy in Windows "enums"

We made a design decision to emit APIs that exactly match those found in the docs and header files. This is optimized to make it easy to translate C++ code to C# and so that win32 API docs match your code, allowing you to translate and jump either direction. Trimming prefixes from enum values for example would make it much more difficult to jump around since symbols would have different names.

> No legacy COM interop

I'm not sure what you mean by this. When you turn marshaling off in CsWin32, any COM interfaces that CsWin32 generates are struct pointers instead of interfaces, which of course is much less convenient but completely avoids RCWs and the GC/finalization pressure that comes from that. Is that what you're looking for?

> Being able to turn off "easy" wrapper generation

You mean you want to suppress the friendly overloads? I could certainly see us adding that as an option if that's important to you.

> Being able to say that we want generation with private so we can enforce using our wrappers in the main assembly.

We offer `internal` by default with an option for `public`. I could see `private` being offered for the *methods*, but not the interop types to support them and still be a useful code generator. I guess you'd have to add your `internal` wrappers via partial class to the generated code in order to access the private members.

2022-06-24 21:26 UTC, AArnott commented
I'm playing around with your repo and seeing how `LibraryImport` works. Very interesting. And I can see how `IHandle` could potentially be supported by it.

2022-06-24 21:52 UTC, AArnott commented
Here's [an idea of what CsWin32 use in WinForms would look like](https://github.com/dotnet/winforms/compare/main...AArnott:cswin32). 

```
 eng/Versions.props                                 |  3 +-
 .../src/Interop/Gdi32/Interop.CombineRgn.cs        | 14 -------
 .../src/Interop/Gdi32/Interop.CreateRectRgn.cs     | 14 -------
 .../src/Interop/Gdi32/Interop.GetClipRgn.cs        | 14 -------
 .../src/Interop/Gdi32/Interop.GetRgnBox.cs         |  1 +
 .../src/Interop/Gdi32/Interop.HRGN.cs              | 47 ----------------------
 .../src/Interop/Gdi32/Interop.RegionScope.cs       | 22 +++++-----
 .../src/Interop/Gdi32/Interop.SelectClipRgn.cs     | 14 -------
 .../src/Interop/User32/Interop.GetUpdateRgn.cs     | 14 -------
 .../src/Interop/User32/Interop.GetWindowRgn.cs     | 21 ----------
 .../src/Interop/User32/Interop.InvalidateRgn.cs    | 21 ----------
 .../src/Interop/User32/Interop.RedrawWindow.cs     | 21 ----------
 .../src/Interop/User32/Interop.SetWindowRgn.cs     |  5 ++-
 .../UxTheme/Interop.GetThemeBackgroundRegion.cs    | 33 ---------------
 .../src/NativeMethods.json                         |  3 ++
 .../src/NativeMethods.txt                          |  9 +++++
 .../src/System.Windows.Forms.Primitives.csproj     |  5 ++-
 .../System/Windows/Forms/DeviceContextHdcScope.cs  |  5 ++-
 18 files changed, 36 insertions(+), 230 deletions(-)
```

Not bad. Just a few APIs moving over drops 194 lines of code from your repo, and deletes several files.
This example generates a bit more than is used (e.g. HDC). In order to curtail the otherwise explosive growth of adoption due to interop types, I cut it off with a few casts or adaptations to make your own structs or enums work with the CsWin32-generated ones. A more complete migration would drop your hand-written types altogether in favor of the CsWin32-generated ones.

2022-06-24 23:39 UTC, AraHaan commented
> Here's [an idea of what CsWin32 use in WinForms would look like](https://github.com/dotnet/winforms/compare/main...AArnott:cswin32).
> 
> ```
>  eng/Versions.props                                 |  3 +-
>  .../src/Interop/Gdi32/Interop.CombineRgn.cs        | 14 -------
>  .../src/Interop/Gdi32/Interop.CreateRectRgn.cs     | 14 -------
>  .../src/Interop/Gdi32/Interop.GetClipRgn.cs        | 14 -------
>  .../src/Interop/Gdi32/Interop.GetRgnBox.cs         |  1 +
>  .../src/Interop/Gdi32/Interop.HRGN.cs              | 47 ----------------------
>  .../src/Interop/Gdi32/Interop.RegionScope.cs       | 22 +++++-----
>  .../src/Interop/Gdi32/Interop.SelectClipRgn.cs     | 14 -------
>  .../src/Interop/User32/Interop.GetUpdateRgn.cs     | 14 -------
>  .../src/Interop/User32/Interop.GetWindowRgn.cs     | 21 ----------
>  .../src/Interop/User32/Interop.InvalidateRgn.cs    | 21 ----------
>  .../src/Interop/User32/Interop.RedrawWindow.cs     | 21 ----------
>  .../src/Interop/User32/Interop.SetWindowRgn.cs     |  5 ++-
>  .../UxTheme/Interop.GetThemeBackgroundRegion.cs    | 33 ---------------
>  .../src/NativeMethods.json                         |  3 ++
>  .../src/NativeMethods.txt                          |  9 +++++
>  .../src/System.Windows.Forms.Primitives.csproj     |  5 ++-
>  .../System/Windows/Forms/DeviceContextHdcScope.cs  |  5 ++-
>  18 files changed, 36 insertions(+), 230 deletions(-)
> ```
> 
> Not bad. Just a few APIs moving over drops 194 lines of code from your repo, and deletes several files. This example generates a bit more than is used (e.g. HDC). In order to curtail the otherwise explosive growth of adoption due to interop types, I cut it off with a few casts or adaptations to make your own structs or enums work with the CsWin32-generated ones. A more complete migration would drop your hand-written types altogether in favor of the CsWin32-generated ones.

That looks great, I wonder what all the other apis used would look like (except the ones that are currently bugged).

2022-06-24 23:45 UTC, elachlan commented
> Not bad. Just a few APIs moving over drops 194 lines of code from your repo, and deletes several files. This example generates a bit more than is used (e.g. HDC). In order to curtail the otherwise explosive growth of adoption due to interop types, I cut it off with a few casts or adaptations to make your own structs or enums work with the CsWin32-generated ones. A more complete migration would drop your hand-written types altogether in favor of the CsWin32-generated ones.

That is an impressive reduction. I think the positive here is that Winforms offloads a lot of the pinvoke interop effort to a project which is being used by many other projects. This would hopefully help improve the interop code more than doing it ourselves.

2022-06-25 01:43 UTC, elachlan commented
@JeremyKuhne CsWin32 can help with https://github.com/dotnet/winforms/issues/4135 as well.

2022-06-25 01:47 UTC, elachlan commented
> I suspect the perf is comparable with the source generator you mentioned except perhaps when using AOT

@AArnott, @kant2002 is very interested in NativeAOT for performance and all their work is centred around enabling that. Would you be able to expand on the performance implications you were eluding to here?

2022-06-25 02:00 UTC, AArnott commented
Well, in the default CsWin32 mode where marshaling is allowed, CsWin32 can generate functions that take structs as parameter types, which .NET will then potentially need to marshal, and do so within its own interop layer that I guess doesn't work in all runtime modes (e.g. AOT + trimming). It may be slower too, I don't know. 
You can turn CsWin32's setting to generate functions and structs that never require marshaling, but the user experience downgrades (e.g. struct fields are blittable `char*` instead of `string`). 
CsWin32 can certainly address that concern in the future, since it can potentially generate the same kind of code that you get today with `[LibraryImport]`, but that'll be some work.

2022-06-25 05:51 UTC, kant2002 commented
@AArnott form what I read bringing CsWin32 will negate small perf gains here and there across codebase. Each bullet points of @JeremyKuhne response is small decision which maintained across codebase for perf reasons, so that's unlikely they can be reversed.

> that I guess doesn't work in all runtime modes (e.g. AOT + trimming). It may be slower too, I don't know.

AOT works just fine with most marshaling except marshaling COM interfaces and marshaling COM objects inside VARIANT and SAFEARRAY. Would be curious to know does some primitives for VARIANT and SAFEARRAY provided so. Also while we talk about AOT, reflection in AOT supported, that's common misconception to not talk about it.

> but the user experience downgrades (e.g. struct fields are blittable char* instead of string).

For this repo, that's explicit decision which maintained by the team and contributors as well. That allow WinForms easier jump on board with runtime innovations/refactoring like https://docs.microsoft.com/en-us/dotnet/standard/native-interop/disabled-marshalling and being close to supporting `BuiltInComInteropSupport` from https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options#framework-features-disabled-when-trimming. 

And obviously perf reasons plays big role here. so I would not dismiss these concerns.

> CsWin32 can certainly address that concern in the future, since it can potentially generate the same kind of code that you get today with [LibraryImport], but that'll be some work.

I think item with "some work" is what I can help you with, at least I would like evaluate options, and take easiest task which will help this project.

Also if you have some simple, or not so simple showcase project which I can git clone and play with it, that would help me to better understand on what I sighing up for. :smile: 

> Folks in C++ don't tend to have to think about what module a function is exported from, so in C# we didn't require them to think about that either.

At least for me, having all native dependencies listed in single folder help with my ComWrappers work massively, since I can learn about dependencies easier. C# for me is all about easier learning of code structure, and having one big class looks like not very appealing. I do agree that knowing that CreateFile will go to some magic namespace is probably unintuitive, but what is namespace in which generate code can be derived from folder where TXT file store, or via additional Item metadata. That's just throwing ideas without really knowing how CsWin32 work.

2022-09-30 09:03 UTC, elachlan commented
@AraHaan did you want to reroll this against the current branch?

2022-09-30 13:47 UTC, AraHaan commented
I could yeah. However I will need to reclone as the original clone on my pc got deleted automatically.

2022-11-12 01:54 UTC, closed without merging

2022-11-12 01:54 UTC, AraHaan commented
Since this was implemented, I have closed this.