Fix incorrect behavior of ListViewSubItem
dotnet/winforms pull request #4761
Opened 2021-04-05 06:42 UTC by SergeySmirnov-Akvelon

Fixes #4679 

## Proposed changes
- Added missing conditions
- Added unit and maui tests

## Customer Impact

## Regression? 

- Yes

## Risk

- Minimal

## Test methodology 
- CTI team 
- Unit tests
- MAUI tests

## Accessibility testing  
- Narrator
- Inspector
 
## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core SDK: 6.0.0-preview.2.21154.2

2021-04-05 23:47 UTC, RussKie commented
/azp run

2021-04-07 07:26 UTC, RussKie reviewed
The first pass over the doc.

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +[ListView](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview) is a native controls is provided by Windows.
```suggestion
[ListView](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview) is a Win32 native control provided by Windows. 
```

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +propeties and actions to make ListView accessible for customers.
```suggestion
Windows Forms runtime provides a support for [UI Automation](https://docs.microsoft.com/dotnet/framework/ui-automation/ui-automation-overview) and, thus, responsible for 
providing required accessible objects with correct properties and actions to make all aspects of the ListView control accessible for customers.
```

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +ListView accessibility tree should contain all visible items depending on its [view](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.view).
```suggestion
ListView accessibility tree must contain all visible items based on the selected [`View` mode](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.view).
```

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +The ListView can always contain [ListViewGroup](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewgroup), but depending on the settings of the application and the ListView, these gro
```suggestion
The ListView always contains one or more [`ListViewGroup`](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewgroup), but depending on a configuration of the operating system, application and/or the ListView itself, these groups can be visible or not.
```

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +```
Here and everywhere else where applicable

```suggestion
```cs
```

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +When [visual styles](https://docs.microsoft.com/dotnet/api/system.windows.forms.application.enablevisualstyles) are enabled, ListViewGroup display is enabled ([ShowGroups](https://docs.microsoft.com/
This is too complex and convoluted. Try presenting it as a list, e.g.:
```suggestion
A `ListViewGroup` is display if the following conditions are met:
1. An application has [visual styles](https://docs.microsoft.com/dotnet/api/system.windows.forms.application.enablevisualstyles) are enabled.
2. A ListView is not in a [virtual mode](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.virtualmode).
3. ...
```

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +We do not show ListViewGroups when visual styles are disabled
```suggestion
ListViewGroups are not visible when visual styles are disabled.
```

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +We do not show ListViewGroups when [ShowGroups](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.showgroups) property has False value
```suggestion
ListViewGroups are not visible when [`ShowGroups`](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.showgroups) property is set to `false`.
```

The same approach below

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +The [ListViewItem](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewitem) can always contain [ListViewSubItem](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listv
Same as above

2021-04-07 07:26 UTC, RussKie commented on docs/accessibility/listview-expected-behavior.md
> +The [ListViewItem](https://docs.microsoft.com/dotnet/api/system.windows.forms.listviewitem) can always contain [ListViewSubItem](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listv
Here and below: a stray "en-us".

2021-04-08 09:02 UTC, vladimir-krestov reviewed
Big work! A lot of tests and doc info. Please check some pointed test cases

2021-04-08 09:02 UTC, vladimir-krestov commented on docs/accessibility/listview-expected-behavior.md
> +# ListViewAccessibleObject expected properties and behavior
Accessibility properties are not described here. You added info about views, so please rename the doc to reflect the real info.

2021-04-08 09:02 UTC, vladimir-krestov commented on docs/accessibility/listview-expected-behavior.md
> +of a [ListView](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview).
Rework it

2021-04-08 11:15 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +            if (View != View.Details && View != View.Tile)
Added missing conditions and comments

2021-04-08 12:26 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
>                  }
Removed this condition during refactoring

2021-04-08 13:27 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiListViewTests/MauiListViewTests.cs
> +            return new ScenarioResult(true);
It works :) great idea

2021-04-14 06:54 UTC, vladimir-krestov approved these changes
Nice! There is a couple of code-style points

2021-04-14 06:54 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
> +                private readonly ListViewItemAccessibleObject _internalParent;
nit: It seems, we use "ParentInternal" in the rest code, please check and rename, if so.
Also, I would move it down, after `_owningSubItem`

2021-04-14 06:54 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
> +                private int Index => _owningSubItem is null
nit: I would name it "CurrentIndex"

2021-04-14 06:54 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
> +                    => Index;
nit: It takes less than 120 characters
```suggestion
                internal override int Column => Index;
```

2021-04-14 06:54 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
> +                    => _internalParent;
nit: ditto - move to one line

2021-04-21 03:45 UTC, RussKie reviewed
A pass over the code. Yet to dig into the docs.

2021-04-21 03:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                    UiaCore.NavigateDirection.LastChild => GetChild(GetChildCount() - 1),
What happens if `GetChildCount()` returns a non-positive number?

2021-04-21 03:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +        // Getting the rectangle for a sub item only works for list view which are in "Details" and "Tile" views
```suggestion
        // Getting a rectangle for a sub item only works for a ListView in "Details" and "Tile" views
```

2021-04-21 03:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +                    && !GetSubItemBounds(index).IsEmpty)
Can't we leverage `_owningListView.SupportsListViewSubItems` here?

2021-04-21 03:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +            internal int GetFakeSubItemIndex(ListViewSubItem.ListViewSubItemAccessibleObject fakeAccessbileObject)
❕  Please provide comments explaining the purpose of this method

2021-04-21 03:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +            internal AccessibleObject? GetDetailsSubItemOrFake(int subItemIndex)
ditto

2021-04-21 07:06 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                    UiaCore.NavigateDirection.LastChild => GetChild(GetChildCount() - 1),
`GetChild` method contains validation for the `index`. If the `index` is less than 0 it will return `null`

2021-04-21 10:29 UTC, SergeySmirnov-Akvelon commented
Approved by CTI team

2021-05-04 17:18 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +            if (firstSelectedItem.Focused && _selectedItem != firstSelectedItem)
What is this extra condition for? what if user navigate from  this and came back to same selected item?

2021-05-04 17:18 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +                => _owningListView.IsHandleCreated
q: in general, want to understand when we call bounds without handle and what should be the expected behavior in those cases. I think i already left this comment  somewhere else.

2021-05-04 17:18 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
> +                private readonly ListViewSubItem? _owningSubItem;
Q: When is this null?

2021-05-05 09:07 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> -                int childCount = GetChildCount();
I removed this check to avoid re-getting the list of items for the "FirstChild" case. Inside the "GetChild" method, we check that the list is not empty, so in the old code we counted the number of elements, call the "GetChild" method and counted them again. We have a separate PR to optimize the work of ListView availability objects, but I want to prepare it for review when other (tested by CTI team) PRs will be merged

2021-05-05 09:34 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +            if (firstSelectedItem.Focused && _selectedItem != firstSelectedItem)
We have "OnGotFocus", "OnSelectedIndexChanged" and "WmMouseDown" methods, where we send a message about the selected item. Unfortunately, when the user clicks on the ListViewSubItem, the "OnSelectedIndexChanged" and "WmMouseDown" methods are executed simultaneously, which leads to an unexpected switch of the Inspect's focus. To avoid this situation, this condition has been added. The case described by you will work correctly by sending a message in the "OnGotFocus" method. I added missing comment about this case.

2021-05-05 09:42 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
> +                private readonly ListViewSubItem? _owningSubItem;
Such a case occurs when the ListView is in "Details" view. In this case, we are displaying cells based on the number of columns, rather than actually existing ListViewSubItems. Therefore, we create an accessibility object that is not associated with ListViewSubItem, but which allows the Inspect to work correctly and interact with the cell.

2021-05-05 09:42 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +                => _owningListView.IsHandleCreated
We adhere to the concept that accessibility objects should not be forced to create Handle (#3432). Therefore, if the Handle is not created, we consider it more correct to return the default data than to perform actions that will lead to its creation.

2021-05-05 10:12 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                    if (hitTestInfo.SubItem is not null && !(_owningListView.View == View.Tile && hitTestInfo.SubItem.Index == 0))
Thank you! I have reworked this code.

2021-05-05 10:12 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                        ListViewItem.ListViewItemAccessibleObject itemAccessibleObject =
Thank you. Fixed

2021-05-05 17:20 UTC, dreddy-work submitted a review, later dismissed
LGTM.

2021-05-11 12:38 UTC, RussKie requested changes

2021-05-11 12:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +        internal bool SupportsListViewSubItems => View == View.Details || (View == View.Tile && Application.ComCtlSupportsVisualStyles);
Any reason why you went with `Application.ComCtlSupportsVisualStyles` and not `Application.RenderWithVisualStyles`?

2021-05-11 12:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +                       _ => throw new NotImplementedException()
This is much safer. In a very unlikely scenario where Windows introduces a new mode we don't want to break consumers.
```suggestion
                       View.Details => _owningListView.Columns.Count,
                       View.Tile => GetChildCountTileView(),
                       _ => -1
```

2021-05-11 12:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +                    _ => throw new NotImplementedException()
ditto

2021-05-11 12:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +                ListViewSubItem.ListViewSubItemAccessibleObject fakeAccessbileObject = new(null, _owningItem);
Please use the named args:
```suggestion
                ListViewSubItem.ListViewSubItemAccessibleObject fakeAccessbileObject = new(whats_my_name: null, _owningItem);
```

2021-05-11 12:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +            private int GetChildCountTileView()
Judging by the name this method is "Tile mode" specific. However there is nothing inside the method that asserts or enforces that.
Suggest adding `Debug.Assert(_owningListView.View == View.Tile, "add some sensible message here, e.g. Must be called in Tile view only")`.

Ditto for other mode-specific methods.

2021-05-11 12:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
> +            {
```suggestion
            internal Rectangle GetSubItemBounds(int subItemIndex)
                =>
```

2021-05-11 12:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
> +                private readonly ListViewSubItem? _owningSubItem;
This may be worth adding as a comment in the code

2021-05-11 12:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
> +                        }
Why not?
```suggestion
                        if (index == 0 && _owningListView.Columns.Count > 1)
                        {
                            width = ParentInternal.GetSubItemBounds(subItemIndex: 1).X - bounds.X;
                        }
```

2021-05-11 13:17 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +        internal bool SupportsListViewSubItems => View == View.Details || (View == View.Tile && Application.ComCtlSupportsVisualStyles);
Consistency. In almost all places in `ListView` where we check for this, we use an `Application.ComCtlSupportsVisualStyles`.

2021-05-11 17:49 UTC, vladimir-krestov reviewed
Looks good!

2021-05-11 17:49 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
> +                internal override int Column => CurrentIndex;
What about the Tile view? CurrentIndex is row index there.
Also, please check if a subItem can support Grid and Table patterns if its ListView in the Tile view?

2021-05-11 22:54 UTC, RussKie approved these changes
👍 modulo @vladimir-krestov questions

2021-05-12 23:48 UTC, RussKie approved these changes

2021-05-12 23:48 UTC, RussKie commented
@msftbot merge if @vladimir-krestov approves

2021-05-13 14:01 UTC, vladimir-krestov approved these changes

2021-05-13 14:01 UTC, merged