Fix issue with displaying empty ListViewGroups
dotnet/winforms pull request #4789
Opened 2021-04-14 06:25 UTC by SergeySmirnov-Akvelon

Fixes #4779

## Proposed changes
- An ListViewItem is considered invisible when it is in a ListViewGroup but not added to the ListView. In this case, the ListViewGroup contains data about it, but the ListViewItem is not displayed in the list. To solve this problem, the "VisibleItems" property was added, which contains a list of only displayed ListViewItems, in which the property "ListView" is not empty. Now, when receiving data about the ListViewItems of a ListViewGroup, we use this property and not "Items" property of the ListViewGroup.
- if the ListViewGroup is empty or contains invisible ListViewItems (case above), then this ListViewGroup is also not displayed in the ListView. This issue was solved in the same way as the issue above, by adding the "VisibleGroups" property that contains a list of only the displayed ListViewGroups.
- Added unit tests for ListViewAccessibleObject, ListViewGroupAccessibleObject, ListViewItemAccessibleObject

## Customer Impact

## Regression? 

- Yes (regression from #3224)

## Risk

- Minimal

## Test methodology 
- Unit tests 
- CTI team

## Accessibility testing  
- Inspect

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core SDK: 6.0.100-preview.2.21155.3

2021-04-14 08:11 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
> +                _internalParent = (_owningListView.AccessibilityObject as ListView.ListViewAccessibleObject)!;
```suggestion
                if (_owningListView.AccessibilityObject is not ListView.ListViewAccessibleObject _internalParent)
                    throw ...;
```

2021-04-14 08:11 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
> +            private readonly ListViewAccessibleObject _internalParent;
What's an "ListViewGroupAccessibleObject  internal parent"?
```suggestion
            private readonly ListViewAccessibleObject _owningListViewAccessibilityObject;
```

2021-04-14 08:11 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                    List<ListViewGroup> list = new List<ListViewGroup>();
```suggestion
                    List<ListViewGroup> list = new();
```

2021-04-14 08:11 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                        if ((listViewGroup.AccessibilityObject as ListViewGroup.ListViewGroupAccessibleObject)!.VisibleItems.Count is not 0)
```suggestion
                        if (listViewGroup.AccessibilityObject is not ListViewGroup.ListViewGroupAccessibleObject listViewGroupAccessibleObject 
                            || listViewGroupAccessibleObject.VisibleItems.Count == 0)
                        	continue;
```

2021-04-14 08:11 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
> +                    List<ListViewItem> visibleItems = new List<ListViewItem>();
```suggestion
                    List<ListViewItem> visibleItems = new();
```

2021-04-14 09:42 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                        }
Clearly this is wrong now :) ...and obviously there's either no test covering it, or it is wrong

2021-04-14 10:23 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                        }
Yes :) Although this condition is not entirely correct, all our tests passed because they did not test that the accessibility object is correct. Condition is fixed, added test for this case

2021-04-14 10:36 UTC, vladimir-krestov submitted a review, later dismissed
Good work

2021-04-14 10:36 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
> +            return listView;
Please add a blank line

2021-04-14 10:36 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
> +            Assert.Null(accessibleObject.GetChild(1));
Please add "IsHandleCreated" assert here and in the rest tests to make sure, that we are doing everything correctly

2021-04-14 10:36 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +            internal List<ListViewGroup> VisibleGroups
It looks like a method that is used instead of LINQ
So, please consider reworking it to a method "GetVisibleGroups"

2021-04-14 10:36 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
> +            internal List<ListViewItem> VisibleItems
ditto, looks like a method indead of LINQ

2021-04-15 02:17 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                        if ((listViewGroup.AccessibilityObject as ListViewGroup.ListViewGroupAccessibleObject)!.VisibleItems.Count is not 0)
My preference to not use. Whilst it works, it looks odd. ...And it is longer than "!= 0" :)

2021-04-15 02:54 UTC, RussKie requested changes

2021-04-15 02:54 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                    : GetVisibleGroups()[index - 1].AccessibilityObject;
This syntax makes me very uncomfortable. Especially seeing that `GetVisibleGroups()` _can_ return an empty list.

2021-04-15 02:54 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                    return OwnerHasDefaultGroup ? GetVisibleGroups().Count + 1 : GetVisibleGroups().Count;
```suggestion
                    List<ListViewGroup> visibleGroups = GetVisibleGroups();
                    return OwnerHasDefaultGroup ? visibleGroups.Count + 1 : visibleGroups.Count;
```

2021-04-15 06:44 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +                    : GetVisibleGroups()[index - 1].AccessibilityObject;
Thank you. Refactored.

2021-04-15 07:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
>                  }
```suggestion
                if (!_owningListView.IsHandleCreated || index < 0)
                {
                    return null;
                }

                List<ListViewGroup> visibleGroups = GetVisibleGroups();
                if (index >= GetChildCount(visibleGroups))
                {
                    return null;
                }
```

2021-04-15 08:03 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +            internal List<ListViewGroup> GetVisibleGroups()
Consider `IReadOnlyList<T>` or `ReadOnlyCollection<T>`

2021-04-15 08:03 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
> +            internal List<ListViewItem> GetVisibleItems()
ditto

2021-04-15 08:35 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
> +            internal List<ListViewGroup> GetVisibleGroups()
Great idea!! Refactored.

2021-04-15 23:11 UTC, RussKie approved these changes

2021-04-16 00:20 UTC, merged