[Do not merge] Fix regression in ParkHandle method from .NET framework
dotnet/winforms pull request #4796
Opened 2021-04-15 21:11 UTC by dreddy-work

Seems this changes was missed from Day 1 and a regression from .NET  Framework.
Ex: https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Control.cs,8435

Without these changes, on PMv2 applications, We might be ending up with wrong DpiAwareness than the requested for windows being created  and some times, might end up failing to parent because of inconsistence DpiAwareness between parent and child.

https://github.com/dotnet/winforms/pull/2262  addressed for catching the failure in 'SetParent'  but applications may be still creating windows with incorrect DpiAwareness.

Need to check on how to add a Unit test.

2021-05-19 23:55 UTC, RussKie requested changes
A little more work needed.

Please rebase instead of tracking-merges
![image](https://user-images.githubusercontent.com/4403806/118899160-8896b600-b951-11eb-80e0-a0ee538a83f2.png)

2021-05-19 23:55 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +                var control = new Control();
Here and everywhere else
```suggestion
                using var control = new Control();
```

https://github.com/dotnet/winforms/blob/main/docs/testing.md#dispose-created-objects

2021-05-19 23:55 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +                var dpiContext = User32.GetWindowDpiAwarenessContext(parkingWindow.Handle);
Use `var` only where the type obvious, which isn't in this case

2021-05-19 23:55 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +                ParkingWindow parkingWindow = cxt.GetParkingWindowForContext(User32.DPI_AWARENESS_CONTEXT.UNAWARE);
ditto
```suggestion
                using ParkingWindow parkingWindow = cxt.GetParkingWindowForContext(User32.DPI_AWARENESS_CONTEXT.UNAWARE);
```

2021-05-19 23:55 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +            //set process awareness
```suggestion
            // Set process awareness
```
Same below

2021-05-19 23:55 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +namespace System.Windows.Forms.Tests.HDPI
File names and folder structure must mirror the name of the productions code

2021-05-20 00:00 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +namespace System.Windows.Forms.Tests.HDPI
you mean ' System.Windows.Forms.Tests.UnitTests.HDPI'? It seems that was not the case for this UnitTestsFolder.

2021-05-20 02:56 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +namespace System.Windows.Forms.Tests.HDPI
No. 
![image](https://user-images.githubusercontent.com/4403806/118900115-8cc3d300-b953-11eb-9fd3-bf5615ff79da.png)

So this should be named: src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Application.ParkingWindowTests.cs

https://github.com/dotnet/winforms/blob/main/docs/testing.md#therefore-you-just-need-to-put-your-tests-in-the-right-place-in-order-for-them-to-run

2021-05-20 02:58 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +            //set process awareness
```suggestion
            // set process awareness
```

2021-05-20 02:59 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +                //Checking PMv2 parking window still available.
```suggestion
                // check PMv2 parking window still available.
```

2021-05-20 02:59 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +                parkingWindow = cxt.GetParkingWindowForContext(User32.DPI_AWARENESS_CONTEXT.PER_MONITOR_AWARE_V2);
❗ `parkingWindow` is not disposed of

2021-05-20 03:00 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +                parkingWindow = cxt.GetParkingWindowForContext(User32.DPI_AWARENESS_CONTEXT.SYSTEM_AWARE);
❗  Previous `parkingWindow` is not disposed of

2021-05-20 03:01 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +namespace System.Windows.Forms.Tests.HDPI
I was planning on creating HDPI category all together and put tests under it.

2021-05-20 03:12 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +namespace System.Windows.Forms.Tests.HDPI
Let's follow the established convention.

2021-05-20 03:30 UTC, dreddy-work commented
Tests are failing random but there is a genuine issue. Will be investigating.

2021-05-20 14:16 UTC, RussKie commented
```
    System.Windows.Forms.Tests.AccessibleObjects.ErrorProviderAccessibleObjectTests.ErrorProvider_NameDoesntEqualControlTypeOrChildName [FAIL]
      System.ComponentModel.Win32Exception : Failed to set Win32 parent window of the Control.
      Stack Trace:
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs(10810,0): at System.Windows.Forms.Control.SetParentHandle(IntPtr value)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs(121,0): at System.Windows.Forms.Control.ControlCollection.Add(Control value)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.ControlCollection.cs(58,0): at System.Windows.Forms.Form.ControlCollection.Add(Control value)
        /_/src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ErrorProviderAccessibleObjectTests.cs(36,0): at System.Windows.Forms.Tests.AccessibleObjects.ErrorProviderAccessibleObjectTests..ctor()
           at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions) in System.Private.CoreLib.dll:token 0x6000644+0x66
```

2021-05-20 17:09 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +namespace System.Windows.Forms.Tests.HDPI
Eventually, we need to keep HDPI tests separate from regular tests. Grouping them together help.

2021-05-20 18:18 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +namespace System.Windows.Forms.Tests.HDPI
I am keeping HDPI test together but following the convention within it. I see value in grouping them.

2021-05-20 19:12 UTC, dreddy-work commented
> Tests are failing random but there is a genuine issue. Will be investigating.

Given that these failures are reproduced only in PR build and that too after adding new tests  for Parkingwindow that were setting process wide dpi awareness, I am guessing failure is because of incorrect DPI awareness of the threads within the test case execution. Replacing process wide DPI awareness with thread and resetting back after finishing the test. This helped resolve test issue. This change is core for control/handle creation and impact all DPI awareness modes. High risk change and would need to be validated thoroughly in this preview.

2021-05-20 23:02 UTC, RussKie approved these changes

2021-05-21 05:06 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/HDPI/ParkingWindowTests.cs
> +namespace System.Windows.Forms.Tests.HDPI
FWIW It would make sense to organize end-to-end tests into a named folder. Or integration tests. These are are unit tests, they will be more discoverable if the standard pattern is followed.

2021-05-21 06:00 UTC, Tanya-Solyanik reviewed
The port itself looks good.
What makes you say that the change is risky? It looks like a direct port from the FX, no?

Could yo please explain what the tests are doing?

2021-05-21 06:02 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/System/Windows/Forms/Application.ParkingWindowTests.cs
> +            IntPtr originalAwarenessContext = User32.SetThreadDpiAwarenessContext(User32.DPI_AWARENESS_CONTEXT.PER_MONITOR_AWARE_V2);
Scope does no-op if process DPI awareness is UNAWARE or SYSTEMAWARE. And that is by design. That was the reason here. will add comment.

2021-05-21 06:03 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/System/Windows/Forms/Application.ParkingWindowTests.cs
> +                IntPtr dpiContext = User32.GetWindowDpiAwarenessContext(parkingWindow.Handle);
I do not think we will be running any tests on Win7.

2021-05-21 06:04 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/System/Windows/Forms/Application.ParkingWindowTests.cs
> +            IntPtr originalAwarenessContext = User32.SetThreadDpiAwarenessContext(User32.DPI_AWARENESS_CONTEXT.PER_MONITOR_AWARE_V2);
explained above. Adding comment.

2021-05-21 06:11 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/System/Windows/Forms/Application.ParkingWindowTests.cs
> +                parkingWindow?.Dispose();
You are right. if we destroy then we should remove it from container.  I am not sure how these tests run ( single application for all tests  vs one application for test/fact).  In either case, destroying window without removing from container does not make sense.

2021-05-21 06:14 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/HDPI/System/Windows/Forms/Application.ParkingWindowTests.cs
> +                IntPtr dpiContext = User32.GetWindowDpiAwarenessContext(parkingWindow.Handle);
When we get on to the Helix infra we will be running tests on different OS versions.

2021-05-21 06:15 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/System/Windows/Forms/Application.ParkingWindowTests.cs
> +            // reset back to original awareness context.
its restoring to original value before we set to PMV2. That is what we want. Agree on resetting back in finalizer.

2021-05-21 06:18 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/HDPI/System/Windows/Forms/Application.ParkingWindowTests.cs
> +                IntPtr dpiContext = User32.GetWindowDpiAwarenessContext(parkingWindow.Handle);
APIs were designed to work on win7 (noop) but will cross check and may be better to skip these on anything <win10.

2021-05-21 06:21 UTC, dreddy-work commented
> What makes you say that the change is risky? It looks like a direct port from the FX, no?

It is risky because it was impacting all applications irrespective of DPI mode. Yes it does match with Framework but PMV2 mode usage in framework should very less comparatively.

2021-05-21 06:23 UTC, dreddy-work commented
> Could yo please explain what the tests are doing?

Tests were intended to validate that we indeed creating parking windows with expected DPI awareness on them. Setting the scope for control creation and expect the parking handle creation in same DPI awareness when control Handle is created.

2021-05-21 08:13 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
> +        internal IntPtr DpiAwarenessContext { get; } = User32.GetThreadDpiAwarenessContext();
I did not remember. That was existing code. Will see if we can replace.

2021-05-21 16:47 UTC, dreddy-work commented
/azp run

2021-05-21 17:10 UTC, merged

2021-05-22 02:43 UTC, Tanya-Solyanik reviewed
I seem to remember that SetThreadDpiAwarenessContext is a no-op in a SA or unaware process as well, had you tested that this API works better than scope does.

>Tests were intended to validate that we indeed creating parking windows with expected DPI awareness on them. Setting the scope for control creation and expect the parking handle creation in same DPI awareness when control Handle is created.

I don't think that each fact is a new Application, so parking windows created in any other test would persist through the test run, so you are not necessarily verifying creation of this window. These tests verify that appropriate parking window gets associates with each context. I think the first 2 tests can be merged into  theory.

>its restoring to original value before we set to PMV2. API returns the value it is replacing
I see it now,  :) I missed it the first time.

2021-05-22 03:20 UTC, dreddy-work commented
> I seem to remember that SetThreadDpiAwarenessContext is a no-op in a SA or unaware process as well, had you tested that this API works better than scope does.

Tested. It does set to the context passed. 

> I don't think that each fact is a new Application, so parking windows created in any other test would persist through the test run, so you are not necessarily verifying creation of this window. These tests verify that appropriate parking window gets associates with each context. I think the first 2 tests can be merged into theory.

Agree as our process is already running in UNAWARE and unaware parking window might have already been there.

2021-05-23 09:14 UTC, RussKie commented
Tests that alter/affect global singletons (e.g. `Application`) must be done as MAUI tests or run under `RemoteExecutor` (subject to https://github.com/dotnet/arcade/pull/7426)