Replace WindowsFormsUtils.EnumValidator.IsEnumWithinShiftedRange with SourceGenerated.EnumValidator.Validate.
dotnet/winforms pull request #4809
Opened 2021-04-19 05:25 UTC by AraHaan

Fixes #4639

## Proposed changes

- Replaces WindowsFormsUtils.EnumValidator.IsEnumWithinShiftedRange only usage inside of MessageBox.cs with the source generated validation.

## Customer Impact

- None

## Regression? 

- No

## Risk

- None

## Test methodology 

TODO: Testing is needed.

## Test environment(s) 

- 
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.21343
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

2021-04-19 12:06 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
> +            SourceGenerated.EnumValidator.Validate(icon, nameof(icon));
These must be tested to ensure we don't accidentally regress.
Please refer to https://github.com/dotnet/winforms/issues/4639#issuecomment-803716393

2021-04-20 21:57 UTC, AraHaan commented
Sorry about the wait, I am still trying to figure out how to properly unit test the source generated outputs and the added private static method named ``GetMessageBoxStyle``.

2021-04-21 02:35 UTC, RussKie commented
Here we're only interested in replacing hand-rolled enum validation with the source-generated one, and testing it. In https://github.com/dotnet/winforms/pull/4746 we'll add the missing test cases to accommodate the new API changes.

This would be a multi-step process:
1. In the first commit factor out the method (which we did), but leave the original enum validation logic - i.e.
```cs
            SourceGenerated.EnumValidator.Validate(buttons, nameof(buttons));

            // valid values are 0x0 0x10 0x20 0x30 0x40, chop off the last 4 bits and check that it's between 0 and 4.
            if (!WindowsFormsUtils.EnumValidator.IsEnumWithinShiftedRange(icon, /*numBitsToShift*/4, /*min*/0x0,/*max*/0x4))
            {
                throw new InvalidEnumArgumentException(nameof(icon), (int)icon, typeof(MessageBoxIcon));
            }

            // valid values are 0x0 0x100, 0x200, chop off the last 8 bits and check that it's between 0 and 2.
            if (!WindowsFormsUtils.EnumValidator.IsEnumWithinShiftedRange(defaultButton, /*numBitsToShift*/8, /*min*/0x0,/*max*/0x2))
            {
                throw new InvalidEnumArgumentException(nameof(defaultButton), (int)defaultButton, typeof(DialogResult));
            }
```
2. Write tests to cover `icon` and `defaultButton` validation paths. Have a look at https://github.com/dotnet/winforms/pull/4782 for an inspiration (aka "cut n'paste" :smile:)
3. (Bonus points) Add tests for `buttons` - it should be pretty trivial now.
4. Make sure the tests pass. Commit.
5. As a follow-up commit - replace original `WindowsFormsUtils.EnumValidator.IsEnumWithinShiftedRange` calls with `SourceGenerated.EnumValidator.Validate` and remove the now obsolete `WindowsFormsUtils.EnumValidator.IsEnumWithinShiftedRange` implementations.
6. Push
7. (Optional, but encouraged) Celebrate!

Hope this makes sense. If not - holler back, and I'll try harder making it clearer.

2021-04-27 05:05 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
> +            SourceGenerated.EnumValidator.Validate(icon, nameof(icon));
I think this method will have to be made internal for unit tests to be able to call it, or will they be able to call it even though it's ``private``?

2021-04-27 06:10 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
> +            SourceGenerated.EnumValidator.Validate(icon, nameof(icon));
Ah, yes, sorry forgot to mention - we have a "sneaky" way to test non-public API via `TestAccessor()`. 
It's briefly mentioned [here](https://github.com/dotnet/winforms/blob/main/docs/testing.md#unit-tests-should-be-part-of-the-same-pr-as-code-changes), but I'll make a note to myself to update the docs to explain this in more details.

The test code will look something like `MB style = MessageBox.TestAccessor().Dynamic.GetMessageBoxStyle(....)`.

2021-06-04 04:28 UTC, RussKie commented
@AraHaan with https://github.com/dotnet/winforms/pull/4782 merged, this should be good to go next.

2021-06-11 21:34 UTC, AraHaan commented
After thinking about this, should I do separate members for each validation step so each step is easier to test separately?

2021-06-11 21:37 UTC, AraHaan commented
Sorry for the wait, just getting back to this (I forgot to go onto my Windows PC for this LOL).

2021-06-11 21:59 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
> -            // options intentionally not verified because we don't expose all the options Win32 supports.
Cant we have the source generator generate a method that does these if checks and throws for options?

In this case a special ``SourceGenerated.EnumValidator.Validate`` that takes in ``owner``, ``showHelp``, ``options``, and ``nameof(options)`` (whenever the generator is told to generate for the ``MessageBoxOptions`` enum).

2021-06-11 23:45 UTC, AraHaan commented
@RussKie I rebased it and commented out the new code so the tests can be added to validate that the same functionality would be there, will add the tests on my Windows PC now.

2021-06-12 02:03 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
> +            SourceGenerated.EnumValidator.Validate(icon, nameof(icon));
Doing that on the tests resulted in compile error saying that ``TestAccessor()`` is not a member of ``MessageBox`` even when I tried to do it that way. I guess it needs a special overload extension for ``MessageBox``.

2021-06-12 06:36 UTC, AraHaan commented
Fixed the tests on my Windows PC as Rider on my Mac was no help, but running tests there and then I will amend the commit with the tests.

2021-06-12 10:59 UTC, AraHaan commented
While I am at removing EnumValidator from ``WindowsFormsUtils`` I noticed that ``AssertControlInformation`` inside that class is unused as well to now. Is that something left over from old code?

2021-06-12 11:16 UTC, AraHaan commented on src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
> +            SourceGenerated.EnumValidator.Validate(icon, nameof(icon));
I tried it with the TestAccessor and because it was ``private static`` and that the ``TestAccessor`` extension method operates on instances of the holding class it made the tests fail until I made it ``internal static`` and on the tests directly use it like any other code that calls the internal static members of the class it needs to use.

2021-06-13 09:40 UTC, RussKie requested changes
Almost there 👍

2021-06-13 09:40 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageBoxTests.cs
> +                () => MessageBox.GetMessageBoxStyle(
```cs
        public void MessageBox_MessageBoxButtons_ThrowsInvalidEnumArgumentException(MessageBoxButtons value)
        {
            Assert.Throws<InvalidEnumArgumentException>(
                "buttons",
                () => GetMessageBoxStyle(....));
        }

        private static MB GetMessageBoxStyle(IWin32Window owner, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, bool showHelp)
            => typeof(MessageBox).TestAccessor().Dynamic.GetMessageBoxStyle(owner, buttons, icon, defaultButton, options, showHelp);
```

2021-06-13 09:40 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
> +        internal static MB GetMessageBoxStyle(IWin32Window owner, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, bool showHelp)
Retain as `private`

2021-06-13 09:41 UTC, RussKie commented
> Is that something left over from old code?

Probably. If it isn't used - nuke it :)

2021-06-13 10:44 UTC, RussKie commented
Tests are failing
```
    System.Windows.Forms.Tests.MessageBoxTests.MessageBox_MessageBoxDefaultButton_ThrowsInvalidEnumArgumentException(value: 1) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ComponentModel.InvalidEnumArgumentException)
      Actual:   typeof(System.Reflection.TargetInvocationException): Exception has been thrown by the target of an invocation.
      ---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
      -------- System.ComponentModel.InvalidEnumArgumentException : The value of argument 'defaultButton' (1) is invalid for Enum type 'MessageBoxDefaultButton'. (Parameter 'defaultButton')
      Stack Trace:
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f0e+0x0
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in System.Private.CoreLib.dll:token 0x6004e12+0x0
        /_/src/System.Windows.Forms.Primitives/tests/TestUtilities/TestAccessor.cs(135,0): at System.TestAccessor`1.DynamicWrapper.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
           at CallSite.Target(Closure , CallSite , Object , IWin32Window , MessageBoxButtons , MessageBoxIcon , MessageBoxDefaultButton , MessageBoxOptions , Boolean )
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageBoxTests.cs(128,0): at System.Windows.Forms.Tests.MessageBoxTests.GetMessageBoxStyle(IWin32Window owner, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageBoxTests.cs(96,0): at System.Windows.Forms.Tests.MessageBoxTests.<>c__DisplayClass6_0.<MessageBox_MessageBoxDefaultButton_ThrowsInvalidEnumArgumentException>b__0()
        ----- Inner Stack Trace -----
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f0e+0x0
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in System.Private.CoreLib.dll:token 0x6004e12+0x0
        /_/src/System.Windows.Forms.Primitives/tests/TestUtilities/TestAccessor.cs(135,0): at System.TestAccessor`1.DynamicWrapper.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
           at CallSite.Target(Closure , CallSite , Object , IWin32Window , MessageBoxButtons , MessageBoxIcon , MessageBoxDefaultButton , MessageBoxOptions , Boolean )
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageBoxTests.cs(128,0): at System.Windows.Forms.Tests.MessageBoxTests.GetMessageBoxStyle(IWin32Window owner, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageBoxTests.cs(96,0): at System.Windows.Forms.Tests.MessageBoxTests.<>c__DisplayClass6_0.<MessageBox_MessageBoxDefaultButton_ThrowsInvalidEnumArgumentException>b__0()
        ----- Inner Stack Trace -----
        /_/src/System.Windows.Forms/src/System.Windows.Forms.PrivateSourceGenerators/System.Windows.Forms.PrivateSourceGenerators.EnumValidationGenerator/Validation.cs(860,0): at SourceGenerated.EnumValidator.ReportEnumValidationError(String parameterName, Int32 value, Type enumType)
        /_/src/System.Windows.Forms/src/System.Windows.Forms.PrivateSourceGenerators/System.Windows.Forms.PrivateSourceGenerators.EnumValidationGenerator/Validation.cs(511,0): at SourceGenerated.EnumValidator.Validate(MessageBoxDefaultButton enumToValidate, String parameterName)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs(79,0): at System.Windows.Forms.MessageBox.GetMessageBoxStyle(IWin32Window owner, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
```

2021-06-13 16:54 UTC, AraHaan commented
Oh so the fix is to have it check if it throws ``TargetInvocationException`` on those tests that are failing?

2021-06-13 17:45 UTC, AraHaan commented
Alright the tests now pass (other than some other unrelated failure).

2021-06-14 20:42 UTC, RussKie approved these changes

2021-06-14 20:42 UTC, merged

2021-06-14 20:43 UTC, RussKie commented
Thank you!