Adding UIA support for TrackBar
dotnet/winforms pull request #4939
Opened 2021-05-19 12:12 UTC by SergeySmirnov-Akvelon

Fixes #4914

## Proposed changes
- Updated `SupportsUiaProviders` flag.
- Added and implemented `TrackBarAccessibleObject`, `TrackBarFirstButtonAccessibleObject`,
`TrackBarLastButtonAccessibleObject` and `TrackBarThumbAccessibleObject` classes for working with the `TrackBar` and its elements.
- Added calls to `RaiseAutomationPropertyChangedEvent` and `RaiseAutomationEvent` methods for the correct announcing of the Narrator

## Customer Impact

## Regression? 

- No

## Risk
- Minimcal

## Test methodology 
- Unit tests 
- CTI team

## Accessibility testing  
- Inspect
- Narrator
- Accessibility Insights

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core SDK: 6.0.100-preview.3.21202.5

2021-05-27 12:48 UTC, vladimir-krestov reviewed
Nice! Good work!
Main points:
- Check Handle using
- Naming and indentation
- Methods and properties ordering in files
- Where are unit tests for TrackBar child base class?

2021-05-27 12:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TrackBars.cs
> +using System.Windows.Forms;
Extra usings

2021-05-27 12:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +                        : 2;
Looks strange, move it right

2021-05-27 12:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarFirstButtonAccessibleObjectTests.cs
> +
Move it right

2021-05-27 12:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarFirstButtonAccessibleObjectTests.cs
> +                : AccessibleStates.Invisible;
ditto

2021-05-27 12:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarFirstButtonAccessibleObjectTests.cs
> +            return trackBarAccessibleObject.FirstButtonAccessibleObject;
Add a blank line

2021-05-27 12:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarLastButtonAccessibleObjectTests.cs
> +                    && (trackBar.RightToLeft == RightToLeft.No || trackBarAccessibleObject.IsMirrored)
ditto

2021-05-27 12:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarLastButtonAccessibleObjectTests.cs
> +            return trackBarAccessibleObject.LastButtonAccessibleObject;
Add a blank line

2021-05-27 12:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarThumbAccessibleObjectTests.cs
> +            return trackBarAccessibleObject.ThumbAccessibleObject;
ditto

2021-06-07 07:42 UTC, RussKie requested changes
Concerned with the tests implementations. Tests should have cyclomatic complexity (CC) of 1, i.e. not `if...else...`.
In some instances (like `if (createControl) ...`) we decided to break this rule, but some tests seem to be really pushing it and have CC > 2. Please consider how the tests can be changed to reduce CC.

2021-06-07 07:42 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +                    ? (AccessibleStates)accState
Would this work?
```suggestion
                => GetSystemIAccessibleInternal()?.get_accState(GetChildId()) is AccessibleStates accState
                    ? accState
```

If works, the same below

2021-06-07 07:42 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObject.cs
> +            private protected readonly TrackBar _owningTrackBar;
Why `protected`???
Convert it to a readonly property

2021-06-07 07:42 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TrackBars.Designer.cs
> +            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
Is this at 100%?

2021-06-07 07:42 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TrackBars.cs
> +            AddTrackBars();
This is quite unconventional... The idea of dynamically generating controls is 👍, but manual specification of coordinates makes it very cumbersome to maintain.
Consider using either a `FlowLayoutPanel` or `TableLayoutPanel` to layout controls without hardcoded coordinates.

2021-06-07 07:42 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +                                        ? -1
This value depends on `createControl` so it would good to pass in...

2021-06-07 07:42 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +                    && accessibilityObject.LastButtonAccessibleObject.IsDisplayed;
Is this something that can be derived? E.g. are buttons shown if `createControl=true`?

2021-06-07 07:42 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarFirstButtonAccessibleObjectTests.cs
> +            }
This should really be independent tests

2021-06-07 07:42 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarFirstButtonAccessibleObjectTests.cs
> +                                    : SR.TrackBarLargeIncreaseButtonName;
ditto

2021-06-07 07:42 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarFirstButtonAccessibleObjectTests.cs
> +            }
ditto

2021-06-07 08:28 UTC, vladimir-krestov reviewed
Looks better

2021-06-07 08:28 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +                _owningTrackBar = owningTrackBar ?? throw new ArgumentNullException(nameof(owningTrackBar));
We don't need the null check here, because the base class makes this.

2021-06-07 08:28 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObject.cs
> +                => ParentInternal.GetSystemIAccessibleInternal()?.get_accRole(GetChildId()) is object accRole
Check `Role`s as `State`s, don't forget to change it, if necessary

2021-06-15 11:46 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +                    ? (AccessibleStates)accState
It doesn't work because we are getting an `int`, not a `AccessibleStates`. We have to forcibly cast the int to the `AccessibleStates`.

2021-06-21 11:57 UTC, vladimir-krestov reviewed
Good work

2021-06-21 11:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObject.cs
> +            internal TrackBar OwningTrackBar {get; private set;}
Here should be private fields only. Move the property below

2021-06-21 11:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObject.cs
> +                    return runtimeId;
Add a blank line

2021-06-21 11:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/TestUtilities/TrackBarTestHelper.cs
> +    public static class TrackBarTestHelper
Please add a little comment why do we need this

2021-06-21 11:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +            Assert.Equal(ownerControl.Size, accessibilityObject.Bounds.Size);
Add a blank line before Asserts here and in the other places

2021-06-21 11:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +        }
Doesn't `MemberData` work with TrackBarTestHelper directly? If so, please add comments about it if possible

2021-06-21 11:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +            Assert.Null(accessibleObject.GetChild(3));
Needs `IsHandleCreated` test too, check it for all the rest tests

2021-06-21 11:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +            trackBar.CreateControl();
Why do we need to create the control here?

2021-06-21 11:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +            trackBar.CreateControl();
ditto

2021-06-22 13:16 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TrackBars.cs
> +            AddTrackBars();
Test form is changed. Now, instead of several controls with different settings, we use one control with auxiliary elements to configure it.

2021-06-22 13:23 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +        }
Unfortunately, when using the method from the "TrackBarTestHelper" class directly, the studio throws an error. Therefore, we have to use an intermediate method to use the parameter list

2021-06-22 13:53 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +            trackBar.CreateControl();
Removed this code

2021-06-22 13:53 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +            trackBar.CreateControl();
Removed this code

2021-06-22 13:54 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
> +            Assert.Null(accessibleObject.GetChild(3));
Added missing validations

2021-06-23 00:45 UTC, RussKie commented
/azp run

2021-06-23 11:50 UTC, RussKie approved these changes

2021-06-23 13:01 UTC, SergeySmirnov-Akvelon commented
CTI approved

2021-06-29 00:51 UTC, RussKie commented
MC

2021-06-29 07:40 UTC, SergeySmirnov-Akvelon commented
@RussKie, thank you. Fixed MC

2021-06-30 01:15 UTC, Tanya-Solyanik reviewed
Looks good, my main question is if names match those in WPF or other framework. Other comments are nits.

2021-06-30 01:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +                => _firstButtonAccessibleObject ??= new TrackBarFirstButtonAccessibleObject(_owningTrackBar);
nit: Would `new (_owningTrackBar);` work?
The same applies to other changes in this PR

2021-06-30 01:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +                        ? 3
Please use 1 tab as indent, this looks like 2

2021-06-30 01:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +                    return runtimeId;
FYI: in other places you added a blank line before `return`.

2021-06-30 01:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObject.cs
> +                    UiaCore.UIA.IsEnabledPropertyId => OwningTrackBar.Enabled && IsDisplayed,
Just curious, does this match the MSAA proxy code? Control could be enabled but scrolled out of the view, I don't know what the expected value is...

2021-06-30 06:44 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>Large decrease</value>
In the course of researching the work of the TrackBar, we found that in some cases (when "RightToLeft" == RightToLeft.Yes and "RightToLeftLayout" = true), the names of button ("Left"/"Right") do not correspond to their actual location. Therefore, in discussion with the team and Guy Barker, it was decided to change their name to the action they perform.

2021-06-30 07:00 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +                    GetSystemIAccessibleInternal()?.accLocation(out left, out top, out width, out height, GetChildId());
The "GetChildId" method returns the id of the trackbar elements. Using this id, we can get the necessary data using standard methods (for example: accLocation, get_accState), which saves us from having to implement them ourselves.

2021-06-30 07:46 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +            ///  Gets the accessible state.
Yes. It works. But I checked, even if you delete `/// <summary>` and `/// <inheritdoc/>`, then the description from the based "AccessibleObject" class is used

2021-06-30 08:38 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObject.cs
> +                    UiaCore.UIA.IsEnabledPropertyId => OwningTrackBar.Enabled && IsDisplayed,
The control had the same behavior before the change:
![image](https://user-images.githubusercontent.com/23376742/123929472-859ed480-d997-11eb-8399-fe9bd6b8925b.png)

In the WPF, we also see similar behavior:
![image](https://user-images.githubusercontent.com/23376742/123929643-aff09200-d997-11eb-87de-05c40e01cc1d.png)

2021-06-30 09:44 UTC, SergeySmirnov-Akvelon commented
> If you open and close a form with a trackbar under inspect, is the trackbar still rooted?

Hi, Tanya. I have checked this case for Inspect and Narrator. TrackBar accessibility objects are removed from memory even if these accessibility tools are active

2021-07-01 07:41 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarFirstButtonAccessibleObjectTests.cs
> +        [MemberData(nameof(TrackBarAccessibleObject_FirstButtonIsDisplayed_TestData))]
Thank you so much!!!  Your approach makes it much easier to use the "TrackBarTestHelper" class.

2021-07-02 20:59 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +                    GetSystemIAccessibleInternal()?.accLocation(out left, out top, out width, out height, GetChildId());
I took another look, and I think that hardcoded  "SELF" id would be much more readable.

2021-07-02 21:01 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +            ///  Gets the accessible state.
>But I checked, even if we delete /// <summary> and /// <inheritdoc/>, then the description from the based "AccessibleObject" class is used.

Interesting. Maybe `inheritdocs` is used by the tools that generate docs?

2021-07-02 21:05 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObject.cs
> +                    UiaCore.UIA.IsEnabledPropertyId => OwningTrackBar.Enabled && IsDisplayed,
I was asking about the `offscreen == true` case though.

2021-07-05 20:57 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
> +            ///  Gets the accessible state.
> But I checked, even if we delete `/// <summary>` and `/// <inheritdoc/>`, then the description from the based "AccessibleObject" class is used.

Are you sure? If you don't have a `///` comment then you don't get intellisense nor docs for the given member.

https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/inheritdoc

2021-07-08 21:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObject.cs
> +                    UiaCore.UIA.IsEnabledPropertyId => OwningTrackBar.Enabled && IsDisplayed,
I see, the actuall "thumb" is off the screen, the OffScreen property was and is not correct. I'm ok with keeping the old behavior.

2021-07-08 21:23 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
> +            AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.AutomationPropertyChangedEventId);
Please open a bug to use IsAccessibilityObjectCreated across the codebase.

2021-07-08 21:24 UTC, Tanya-Solyanik approved these changes
Please see a comment about opening a bug to test if accessible object is created across the whole codebase.

2021-07-09 03:46 UTC, RussKie approved these changes

2021-07-09 03:46 UTC, merged