[WIP] Adding support for ContainerControls and MDI child windows scaling in PermonitorV2 mode
dotnet/winforms pull request #4946
Opened 2021-05-20 04:07 UTC by dreddy-work

Fixes #

Hosted Container controls or MDI child windows do not scale well in PMv2 mode on secondary monitors: 

## Proposed changes

**Root cause:** 

- Windows Operating System provide various DPI changed messages for applications/frameworks to subscribe and react accordingly to scale/render crisp UI. 

  - WM_DPICHANGED – received by top-level windows
  - WM_DPICHANGED_BEFOREPARENT – received by child windows
  - WM_DPICHANGED_AFTERPARENT – received by child windows 
 
 Winforms do subscribe to these messages and tries to scale windows. However, winforms assumed following while subscribing to these Operating System messages.

- ‘Form’ is always a top-level window. Hence respond to only WM_DPICHANGED message and ignore other.
-  ControlCollection contains all child controls. Hence, Only iterate over control collection to scale child controls.
- Font is not updated for certain controls that have wrapped native controls. Ex: Tabs in TabControl.

**Proposed solution:**

- ‘Form’ can be child window (ex: MDI) or may not be added to control collection (ex: Winforms designer). Hence, we need them (i.e ContainerControl) responding to  WM_DPICHANGED_BEFOREPARENT and WM_DPICHANGED_AFTERPARENT  as child windows wherever applicable.
- Explicit Font propagation to native windows while reacting to these OS messages.

**Implementation Details:**

“AutoScaleFactor’ is the key element in scaling the windows in winforms. This factor is calculated based on the DPI or Font metric depending on the ‘AutoscaleMode’ defined for the containing control. 

Existing infrastructure support windows scaling whenever there is a Font change. When control/window receives DPI changed message, control need to be scaled and its font need to be updated to match with the scaling being performed. As existing infrastructure support scaling using ‘AutoscaleFactor’ whenever Fontchange happen, We would be using same flow when there is a DPI change. We would scale the Font for the DPI received in DPI change message which intern cause the control scaling for that Font. 

## Regression? 

- No

## Risk

- High

## Screenshots 

### Before

TODO

### After

TODO

## Test methodology 

Manual validations on multi monitor setup and Unit tests wherever possible. Looking to enhanced testing given the risk of change.

2021-05-20 14:11 UTC, RussKie requested changes

2021-05-20 16:46 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        private static readonly object EVENT_DPI_CHANGED = new object();
@RussKie , i have not cleaned up code yet and these parts are moved around from existing code. Hold on any review.

2021-05-20 16:48 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            _scaledFont = new Font(Font.FontFamily, Font.Size * factor, Font.Style, Font.Unit, Font.GdiCharSet, Font.GdiVerticalFont);
its scope is same as process scope. just like Font property.

2021-06-02 19:38 UTC, dreddy-work commented
Messed up this branch while rebasing. And also code deviated lot from this. So, created a new PR #5032 and opening it for review. Closing this draft.

2021-06-02 19:38 UTC, closed without merging