Stop NativeImageList GDI leak
dotnet/winforms pull request #4952
Opened 2021-05-21 07:28 UTC by RussKie

Fixes #3567
Closes #4928

## Proposed changes

There are certain code paths where we are unable to track the lifetime of the object,
for example in the following scenarios:

     this.imageList1.ImageStream = (System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream"));

or

     resources.ApplyResources(this.listView1, "listView1");

In those cases the loose instances will be collected by the GC.

Undo the regression introduced in  #3526.

## Customer Impact

- Customer applications should no longer crash due to exhausted pool of GDI handles used by `NativeImageList` objects.

## Regression? 

- Yes

## Risk

- Minimal

## Test methodology 

- added unit and MAUI tests to verify both disposal and GC scenarios
- a lot of manual tests

### Manual tests harness:

```diff
diff --git a/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs b/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
index 02ed97ff4..68d0ef6db 100644
--- a/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
+++ b/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
@@ -123,7 +123,18 @@ namespace WinformsControlsTest
             },
             {
                 MainFormControlsTabOrder.ListViewButton,
-                new InitInfo("ListVew", (obj, e) => new ListViewTest().Show())
+                new InitInfo("ListVew", (obj, e) =>
+                {
+                    int gdiHandleCount = Interop.User32.GetGuiResources(Process.GetCurrentProcess().Handle, Interop.User32.GR.GDIOBJECTS);
+                    Debug.WriteLine($"before: {gdiHandleCount}");
+                    using ListViewTest form = new ();
+                    form.ShowDialog();
+                    GC.Collect();
+                    GC.WaitForPendingFinalizers();
+                    GC.Collect(0);
+                    gdiHandleCount = Interop.User32.GetGuiResources(Process.GetCurrentProcess().Handle, Interop.User32.GR.GDIOBJECTS);
+                    Debug.WriteLine($"after: {gdiHandleCount}");
+                })
             },
```

### Before

![gdi1](https://user-images.githubusercontent.com/4403806/119099123-eadade00-ba59-11eb-9cf3-3a0818db0279.gif)

### After

![gdi2](https://user-images.githubusercontent.com/4403806/119098556-49ec2300-ba59-11eb-8784-f5863737157e.gif)

2021-05-21 07:29 UTC, RussKie commented
/cc: @kirsan31 @weltkante

2021-05-21 07:59 UTC, kirsan31 commented on src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs
> +                // In those cases the loose instances will be collected by the GC.
Would it be helpful (and easy) to leave `Debug.Fail` here, but filter out all `known` problem areas?

2021-05-21 08:04 UTC, kirsan31 commented
I think this in scope of this PR (may I am wrong). Is it does anything?
https://github.com/dotnet/winforms/blob/706b64a0ebc2cf2fa023bc0570b516f505111641/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs#L529
Due to `ImageStream` property implementation:
https://github.com/dotnet/winforms/blob/706b64a0ebc2cf2fa023bc0570b516f505111641/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs#L197-L209

2021-05-21 10:21 UTC, weltkante commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/ImageListTests/MauiImageListTests.cs
> +            p.log.WriteLine($"GDI handles before: {startGdiHandleCount}");
You might want to check it being nonzero? [doc](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getguiresources) says failure returns zero (and can be distinguished from "no resource usage" with `GetLastError`) though I assume WinForms always will have _some_ resource usage after warmup, zero will probably always be in error.

If you don't do this you might miss `GetGdiHandles` failing twice and report a false-negative. Though I don't know when it can fail, maybe there is no failure scenario that is relevant for you.

2021-05-23 23:57 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/ImageListTests/MauiImageListTests.cs
> +            p.log.WriteLine($"GDI handles before: {startGdiHandleCount}");
Yes, thank you. I was meant to do it... and got carried away.

2021-05-24 05:27 UTC, RussKie commented
> I think this in scope (may be I am wrong). Was introduced in same PR #3526. Is it does anything?

Apologies, I am struggling to follow your train of thought/question. Could you please rephrase?

2021-05-24 06:27 UTC, kirsan31 commented
> > I think this in scope (may be I am wrong). Was introduced in same PR #3526. Is it does anything?
> 
> Apologies, I am struggling to follow your train of thought/question. Could you please rephrase?

The regression was introduced in #3526. Also in this PR this line of code was added to `ImageList.Dispose(bool disposing)` method:
https://github.com/dotnet/winforms/blob/706b64a0ebc2cf2fa023bc0570b516f505111641/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs#L529
and this line does nothing (_useful_), due to `ImageStream` property implementation:
https://github.com/dotnet/winforms/blob/706b64a0ebc2cf2fa023bc0570b516f505111641/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs#L197-L209

:hugs:

2021-05-24 07:51 UTC, RussKie commented
> The regression was introduced in #3526. Also in this PR this line of code was added to `ImageList.Dispose(bool disposing)` method: 
> ...
> and this line does nothing (_useful_), due to `ImageStream` property implementation:


Ah, yes! Thank you. Removed

2021-05-24 09:50 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs
> +                // In those cases the loose instances will be collected by the GC.
No, this is too unreliable.

2021-05-24 18:51 UTC, JeremyKuhne requested changes
It would be nice if we could avoid introducing more `BinaryFormatter` usage here (even in tests). We'll need an answer at some point for `ImageListStreamer`. I'd suggest adding an `internal void ImageListStreamer.ToStream(Stream stream)` and `internal ImageListStream(Stream stream)` to avoid the BF. Should be straight forward to implement and we can follow up with an API proposal for it.

Outside of that there are a few minor comments.

2021-05-24 18:51 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetGuiResources.cs
> +        public static extern int GetGuiResources(IntPtr hProcess, GR uiFlags);
This returns a `uint` (`DWORD`).

2021-05-24 18:51 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetGuiResources.cs
> +        public enum GR : int
While `int` works, we've been trying to follow the actual underlying type, which is `uint`. Also consider moving this to it's own file.

2021-05-24 18:51 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs
> +            private readonly string _callStack = new StackTrace().ToString();
This appears to no longer be used.

2021-05-24 19:15 UTC, kirsan31 commented on src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs
> +            private readonly string _callStack = new StackTrace().ToString();
> This appears to no longer be used.

https://github.com/dotnet/winforms/blob/2e47baf7d33ecd59d45ab1a49513dae90a708e0d/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs#L58
https://github.com/dotnet/winforms/blob/2e47baf7d33ecd59d45ab1a49513dae90a708e0d/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs#L110
?

2021-05-24 23:05 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs
> +            private readonly string _callStack = new StackTrace().ToString();
This was removed in the initial PR, then reintroduced, then removed again. Currently its indeed not used as far as I can tell.

2021-05-25 00:14 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs
> +            private readonly string _callStack = new StackTrace().ToString();
No, is used in other places as @kirsan31 pointed out. It has only been removed from the finalizer.

2021-05-25 01:53 UTC, RussKie commented
> It would be nice if we could avoid introducing more `BinaryFormatter` usage here (even in tests). We'll need an answer at some point for `ImageListStreamer`. I'd suggest adding an `internal void ImageListStreamer.ToStream(Stream stream)` and `internal ImageListStream(Stream stream)` to avoid the BF. Should be straight forward to implement and we can follow up with an API proposal for it.

I'm going to do this in a separate PR.

2021-05-25 02:59 UTC, merged

2021-05-25 03:05 UTC, RussKie commented
Reworked the BF in https://github.com/dotnet/winforms/pull/4966

2021-05-25 06:51 UTC, kirsan31 commented
![image](https://user-images.githubusercontent.com/17767561/119452062-988e0b80-bd3e-11eb-8e3e-e1567cb99fec.png)
@RussKie  Is this still _servicing-consider_ for `5.0.x`?

2021-05-25 06:55 UTC, RussKie commented
I've requested a permission to service, will find out soon.

2021-05-25 17:32 UTC, dreddy-work commented
Approved for servicing. We need a servicing PR.