Remove CoClass usages from System.Windows.Forms
dotnet/winforms pull request #4971
Opened 2021-05-25 13:06 UTC by kant2002

This helps make WinForms application more ILLink/NativeAOT-friendly

Fixes #4940

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/4971)

2021-05-26 00:00 UTC, RussKie commented
@JeremyKuhne @AaronRobinsonMSFT may I get you to review this one?

2021-05-26 00:23 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                    Ole32.CLSCTX.INPROC_SERVER,
I think you want `INPROC` (which is `INPROC_SERVER | INPROC_CLIENT`)

2021-05-26 00:29 UTC, weltkante requested changes
I've added a few coments with suggestions, note that these apply to all three locations but I only annotated the first occurence since the others are identical.

2021-05-26 00:29 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                Guid IID_FileOpenDialogCoClass = new Guid("DC1C5A9C-E88A-4dde-A5A1-60F82A20AEF7");
This is actually a class not an interface

```suggestion
                Guid CLSID_FileOpenDialog = new Guid("DC1C5A9C-E88A-4dde-A5A1-60F82A20AEF7");
```

2021-05-26 00:29 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                    Ole32.CLSCTX.INPROC_SERVER,
I think you want `INPROC` which is `INRPOC_SERVER | INPROC_HANDLER`

2021-05-26 00:29 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                Guid IID_IFileOpenDialog = new Guid("d57c7288-d4ad-4768-be02-9d969532d960");
Use `typeof(IFileOpenDialog).Guid` to have less hardcoded Guids around?

2021-05-26 00:57 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                    Ole32.CLSCTX.INPROC_SERVER,
The runtime activates through `CLSCTX_SERVER` in this case - which is what I would recommend. Using `INPROC_HANDLER` is likely fine but since we typically don't and this is WinForms I would defer to what the runtime has always done.

`CLSCTX_SERVER = (CLSCTX_INPROC_SERVER|CLSCTX_LOCAL_SERVER|CLSCTX_REMOTE_SERVER)`

2021-05-26 00:59 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                Guid IID_FileOpenDialogCoClass = new Guid("DC1C5A9C-E88A-4dde-A5A1-60F82A20AEF7");
Also apply this change in the other places.

2021-05-26 01:08 UTC, AaronRobinsonMSFT reviewed
Overall, I've no real issues with this change as it just makes the veneer over COM class activation explicit. I don't fully get why this needed. However, I'm not plugged into all the NativeAOT work so I could see a case for this change being cheaper than supporting how .NET has traditionally activated a COM class.

2021-05-26 01:08 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                    throw Marshal.GetExceptionForHR((int)hr);
Any specific reason to use `Marshal.GetExceptionForHR` instead of [`Marshal.ThrowExceptionForHR`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshal.throwexceptionforhr)?

2021-05-26 01:16 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                Guid IID_IFileOpenDialog = new Guid("d57c7288-d4ad-4768-be02-9d969532d960");
This is actually the trick to allow this code run without Reflection. Would be good if that capacity was preserved. I think string duplication can be removed by using shared const strings, but that may be overkill.

2021-05-26 01:22 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                    throw Marshal.GetExceptionForHR((int)hr);
No. Only lack of education.

2021-05-26 01:36 UTC, kant2002 commented
@AaronRobinsonMSFT I suspect that `new RCW` should be treated in different way by compiler and only for Windows, which is additional complexity. Second option is that `RhNewObject` would be aware about CoClass, so penalty for new objects would be applied across all object creation. Again, this is what I see from where I'm sitting. This is about only change which is required for WinForms. There exists CoClass in the Accessibility, but that's about it what is needed for making file dialogs works in NativeAOT.

2021-05-26 03:24 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                Guid IID_IFileOpenDialog = new Guid("d57c7288-d4ad-4768-be02-9d969532d960");
@kant2002 I don't see any reflection in `typeof(IFileOpenDialog).Guid`, at least not how I understand it. The `typeof` keyword is going to load the token in the metadata which is largely the same as what is going on a few lines lower when it is cast. The call to `Guid` is a static method on all `Type` instances. The `Guid` property does do some cleverness to compute the `Guid` value but I wouldn't call that "reflection" per se. Can you demonstrate how this statement isn't AOT friendly?

I would prefer to use the `Guid` property if possible.

2021-05-26 03:39 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                Guid IID_IFileOpenDialog = new Guid("d57c7288-d4ad-4768-be02-9d969532d960");
Boo. Okay. I've been educated here. This is reflection because the `Guid` property will first query if the `Type` has the `GuidAttribute` &ndash; that is definitely reflection &ndash; and if that isn't there query for additional metadata to compute a stable `Guid`. Even this querying of additional metadata is going to fall under that group. Well this is unfortunate but I see the reasoning now.

2021-05-26 03:48 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                Guid IID_IFileOpenDialog = new Guid("d57c7288-d4ad-4768-be02-9d969532d960");
Can we instead rely on the cast for performing the desired QI and use the hardcoded `NativeMethods.ActiveX.IID_IUnknown` for the requested interface during activation? This will avoid the interface ID duplication and avoid cluttering the activation with unnecessary details. We could do this throughout.

2021-05-26 07:54 UTC, weltkante requested changes
Looks good with the [open discussion](https://github.com/dotnet/winforms/pull/4971#discussion_r639380951) about removing the IIDs and calling CoCreateInstance with IID_IUnknown instead which already has a constant.

Also it may be worth moving the CLSID constants into the interop files, after all these are constants from the win32 API. Not sure where they would go though @RussKie

2021-05-26 07:54 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
> +        private static Guid CLSID_FileSaveDialogCoClass = new Guid("C0B4E2F3-BA21-4773-8DBA-335EC946EB8B");
```suggestion
        private static Guid CLSID_FileSaveDialog = new Guid("C0B4E2F3-BA21-4773-8DBA-335EC946EB8B");
```

nit: the others are named correctly, this forgot to remove the CoClass suffix (implied by `CLSID`, usually not part of the name)

2021-05-26 18:13 UTC, JeremyKuhne commented
> Also it may be worth moving the CLSID constants into the interop files, after all these are constants from the win32 API. Not sure where they would go though @RussKie

I'd say under the root in Interop.  Following the existing pattern of `Interop.CLSID.cs` with `CLSID` being a static class with `FileSaveDialog`, etc. as statics in it.

Note that there is cost to having these take strings (I don't think it gets optimized away). It might be worth changing these to `Guid(uint a, ushort b, ushort c, byte d, byte e, byte f, byte g, byte h, byte i, byte j, byte k)`, at least long term.

2021-05-27 06:58 UTC, weltkante submitted a review, later dismissed

2021-05-31 10:54 UTC, kant2002 commented
@JeremyKuhne can you take a look?

2021-06-01 06:26 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.CLSID.cs
> +        internal static Guid FileSaveDialog = new Guid("C0B4E2F3-BA21-4773-8DBA-335EC946EB8B");
```suggestion
        // C0B4E2F3-BA21-4773-8DBA-335EC946EB8B
        internal static Guid FileSaveDialog = new Guid(0xC0B4E2F3, 0xBA21, 0x4773, 0x8D, 0xBA, 0x33, 0x5E, 0xC9, 0x46, 0xEB, 0x8B);
```

2021-06-01 06:26 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.CLSID.cs
> +        internal static Guid FileOpenDialog = new Guid("DC1C5A9C-E88A-4dde-A5A1-60F82A20AEF7");
```suggestion
        // DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7
        internal static Guid FileOpenDialog = new Guid(0xDC1C5A9C, 0xE88A, 0x4DDE, 0xA5, 0xA1, 0x60, 0xF8, 0x2A, 0x20, 0xAE, 0xF7);
```

2021-06-01 06:28 UTC, RussKie commented
@kant2002 Jeremy is currently OOF, will be back next week.

2021-06-03 20:52 UTC, JeremyKuhne approved these changes
Looks good, thanks!

2021-06-04 02:14 UTC, RussKie approved these changes
🚀

2021-06-04 02:14 UTC, merged

2021-06-04 02:15 UTC, RussKie commented
Thank you all.