Enable nullability in DataGridViewColumn EventArgs
dotnet/winforms pull request #4995
Opened 2021-05-28 10:22 UTC by gpetrou

## Proposed changes

- Enable nullability in DataGridViewColumn EventArgs.

2021-05-31 02:52 UTC, RussKie requested changes

2021-05-31 02:52 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnStateChangedEventArgs.cs
>          {
```suggestion
        public DataGridViewColumnStateChangedEventArgs(DataGridViewColumn dataGridViewColumn, DataGridViewElementStates stateChanged)
        {
            if (dataGridViewColumn is null)
            {
                throw new ArgumentNullException(nameof(dataGridViewColumn));
            }
```

2021-07-28 20:41 UTC, dreddy-work commented
@gpetrou , checking back if you can take this to closure.

2021-08-02 17:36 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnStateChangedEventArgs.cs
> +        public DataGridViewColumn? Column { get; }
changes in this file seems contradicting. If column is expected be null then we shouldn't throw exception.

2021-08-02 18:31 UTC, dreddy-work approved these changes

2021-08-02 18:32 UTC, merged

2021-08-02 21:12 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnStateChangedEventArgs.cs
> +            }
@dreddy-work this needs to be raised as a breaking change in https://github.com/dotnet/docs/issues/22021

2021-08-02 21:24 UTC, dreddy-work commented
Thanks @gpetrou  for taking time and getting this closure.

2021-11-02 00:23 UTC, dreddy-work commented
tracking doc update here: https://github.com/dotnet/dotnet-api-docs/issues/7343