Refactoring scaling when received DPI changed events. This should hel…
dotnet/winforms pull request #5032
Opened 2021-06-02 19:36 UTC by dreddy-work

Fixes #3491

Hosted Container controls or MDI child windows do not scale well in PMv2 mode on secondary monitors: 

## Proposed changes

**Root cause:** 

Windows Operating System provide various DPI changed messages for applications/frameworks to subscribe and react accordingly to scale/render crisp UI. 

  - WM_DPICHANGED – received by top-level windows
  - WM_DPICHANGED_BEFOREPARENT – received by child windows
  - WM_DPICHANGED_AFTERPARENT – received by child windows 
 
 Winforms do subscribe to these messages and tries to scale controls/windows. However, winforms assumed following while subscribing to these messages.

- ‘Form’ is always a top-level window. Hence respond to only WM_DPICHANGED message and ignore other.
-  ControlCollection contains all child controls. Hence, Only iterate over control collection to scale child controls. Child relationship by other means ignored (ex: MDI child windows or Winforms designer in VS)
- Font is not updated for certain controls that have wrapped native controls. Ex: Tabs in TabControl or list items in ListView.

**Proposed solution:**

- ‘Form’ can be a child window (ex: winforms designer) or may not be added to control collection (ex: MDI). Hence, we need them responding to  WM_DPICHANGED_BEFOREPARENT and WM_DPICHANGED_AFTERPARENT  messages as child windows wherever applicable.
- Explicit Font propagation to native windows while reacting to these OS messages.

**Implementation Details:**

`AutoScaleFactor` is the key element in scaling the windows in winforms. This factor is calculated based on the DPI or Font metric depending on the `AutoscaleMode` defined for the containing control. 

`PerformAutoScale()` currently helps scaling controls in SystemAware mode using `AutoscaleFactor` while performing `ResumeLayout()` and  also when `OnFontChanged()` event occur.  Leveraging this for DPI changed messages and scale controls.

Top-level window will still be scaled by Windows ( therefore does not account `AutoScaleFactor`) and may have issues if it was set to `AutoScaleMode.Font`.  Windows scale it with DPI factor.

ContainerControls will respond to all three DPI changed messages and trigger scaling of the controls.  This happen in two steps. 

1. Scale the control font  according the DPI received from DPI changed message.

2. Trigger `OnFontChanged` event with this scaled font. This calls into `PerformAutoScale() `that helps scaling the controls and its children with appropriate `AutoScaleFactor`.

## Regression? 

- No

## Risk

- High

## Screenshots 

**Moving from 200% screen to 100% screen.**

### Before

**Top-Level window:**
![image](https://user-images.githubusercontent.com/36968667/120540791-eee1f680-c39d-11eb-9bd5-90ff6f74ca11.png)

**MDI child window:**
![image](https://user-images.githubusercontent.com/36968667/120541506-d45c4d00-c39e-11eb-8d2c-ebae239ab23b.png)

### After
**Top-Level window:**
![image](https://user-images.githubusercontent.com/36968667/120540853-fef9d600-c39d-11eb-8a1e-64612199b04d.png)

**MDI child window:**
![image](https://user-images.githubusercontent.com/36968667/120540993-2650a300-c39e-11eb-8856-279dd2342485.png)

## Test methodology 

Manual validations on multi monitor setup and Unit tests wherever possible. Looking to enhanced testing given the risk of change.

Looking to get unit tests added. 
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/4946)

2021-06-04 04:33 UTC, Tanya-Solyanik submitted a review, later dismissed
Looks good. I added some nits. I think the most difficult thing here is to test variety of controls and variate of layouts.

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +            // 'AutoscaleMode' into account while scalign the controls.
typo: scalign

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                new HandleRef(this, HandleInternal),
please indent

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                // factor is used only to scale Font. After that, AutoscaleFactor kicks in to scale controls.
Please capitalize comments

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                    Font = new Font(Font.FontFamily,
where is the previous font object disposed

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                    // scaling font and caching it locally. Propertybag is not updated.
Please capitalize comments

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            _scaledControlFont = new Font(Font.FontFamily, Font.Size * factor, Font.Style, Font.Unit, Font.GdiCharSet, Font.GdiVerticalFont);
I would cache Control.Font into a local var.

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        // ToDO: Look into caching Dpi and control bounds for each Dpi to improve perf.
Add a GH issue and link it here

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        private FontHandleWrapper _sclaedFontWrapper;
typo: _sclaedFontWrapper

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +            if (Properties.GetObject(s_fontProperty) is not null)
It might make sense to factor out this check into a helper method, you have it in multiple places. TryGetLocalFont?

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> -            if (IsHandleCreated && !GetStyle(ControlStyles.UserPaint))
Had this change been tested on all "native" controls?

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // ceratin controls like 'PropertyGrid' does special scalling. Differing scaling to their own methods.
spelling and capitalization: ceratin

2021-06-04 04:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            _scaledControlFont = new Font(Font.FontFamily, Font.Size * factor, Font.Style, Font.Unit, Font.GdiCharSet, Font.GdiVerticalFont);
I would use Math.Round when scaling size.

2021-06-04 17:44 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                    Font = new Font(Font.FontFamily,
In Font 'set()' we dispose Font and handle before assigning new value.

2021-06-04 21:40 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            _scaledControlFont = new Font(Font.FontFamily, Font.Size * factor, Font.Style, Font.Unit, Font.GdiCharSet, Font.GdiVerticalFont);
Font object expect float/double. It seems Native font creation handle that.

2021-06-04 21:41 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> -            if (IsHandleCreated && !GetStyle(ControlStyles.UserPaint))
Attached screenshots have some native controls. Will be testing extensively in this preview.

2021-06-07 07:56 UTC, RussKie commented on src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> +*REMOVED*override System.Windows.Forms.PropertyGrid.RescaleConstantsForDpi(int deviceDpiOld, int deviceDpiNew) -> void
It's fine.

2021-06-07 08:36 UTC, RussKie reviewed
1st pass, haven't had a chance to review everything yet.

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        // We use this flag to indicate its top-level window and is already scaled.
I'm struggling to correctly interpret the comment - is the top window _scaled by Windows to the suggested rectangle_, or we scale it to _the rectangle suggested by Windows_?
If it is the former, perhaps word this as:
```suggestion
        // Top-level window is scaled by Windows during WM_DPICHANGED event.
        // We use this flag to detect a top-level window, and that it is already been scaled.
```

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        // property 'AutoScaleFactor' as it computes with already updated Font and Dpi of the parent.
```suggestion
        // Children container controls that inherit the autoscale mode from their parents (and do not store their own) would need
        // AutoscaleFactor from their parents to scale during DPI changed events. We cannot use AutoScaleFactor property
        // because it get computed with already updated Font and Dpi of their parent.
```

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +            // 'AutoScaleMode' into account while scaling the controls.
```suggestion
            // Font may be updated for container controls that are set to scale in DPI mode (during WM_DPICHANGED event).
            // This may require scaling/relayout of the form. AutoScaleFactor will take AutoScaleMode into account 
            // while scaling the controls.
```

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        /// child container controls as they receive their own 'OnFontChanged' message.
Use [correct xml-doc](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/param), `<param name="scalingByFontChanged">...</param>`
```suggestion
        /// <param name="scalingByFontChanged">Indicates whether the scaling was caused by 'ResumeLayout'
        /// or 'OnFontChanged' event. Scaling by 'OnFontChanged' event does not need to scale
        /// child container controls as they receive their own 'OnFontChanged' message.</param>
```

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        /// child container controls as they receive their own 'OnFontChanged' message.
We don't use `'` around members. If you want to link to members please use correct xml-doc tags, e.g. [`see`](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/see)

```suggestion
        /// scalingByFontChanged parameter helps to distinguish the scaling by ResumeLayout
        /// or OnFontChanged event. Scaling by OnFontChanged event does not need to scale
        /// child container controls as they receive their own OnFontChanged message.
```

This applies universally.

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        private void PerformAutoScale(bool includedBounds, bool excludedBounds, bool scalingByFontChanged = false)
I'm struggling with this name, suggesting `causedByFontChanged`. Or even something like `isFontScaling`.

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        private bool _scaledByDpiChangedEvent;
```suggestion
        private bool _isScaledByDpiChangedEvent;
```

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +            // need to scale explicitly with new scaled font. (ex scenario: Winforms designer in VS)
We need to scale what?
```suggestion
            // Check if Font is inherited from Parent and is not being scaled by Parent (e.g. the designer in VS).
            // In this case we need to scale <scale what????> explicitly with new scaled font. 
```

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +            // need to scale explicitly with new scaled font. (ex scenario: Winforms designer in VS)
I'm struggling to make a connection between this comment and `if TryGetExplicitlySetFont(..) return`.

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                // If this container is a top-level window, We would receive WM_DPICHANGED message that
Here and in multiple other places incorrect capitalisation of words in comments. Please proof read all comments to have the correct sentence case (with exception for type member names, if/where necessary), and correct spacing between words and punctuation.

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                // Factor is used only to scale Font. After that, AutoscaleFactor kicks in to scale controls.
```suggestion
                // Factor is used only to scale Font. After that AutoscaleFactor kicks in to scale controls.
```

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                    // Scaling font and caching it locally. Propertybag is not updated.
```suggestion
                    // Scale the font and cache it locally. Propertybag is not updated.
```

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        // Stores scaled font from Dpi changed values. This is required to distinguish the Font change from
There are multiple version of casing for `DPI`. Please pick one version and use it consistently.

2021-06-07 08:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    _scaledControlFont = value;
This appears to be a recurring pattern. Suggest creating a property that encapsulates disposal and assignment to reduce the risk of not disposing when dealing with the field.

2021-06-07 17:20 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        // We use this flag to indicate its top-level window and is already scaled.
Its the later. reworded.

2021-06-07 18:18 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                // Factor is used only to scale Font. After that, AutoscaleFactor kicks in to scale controls.
Is that really wrong?

2021-06-07 18:52 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +            // need to scale explicitly with new scaled font. (ex scenario: Winforms designer in VS)
If font is explicitly set on control, we would update property bag.  This is checking for that. If it was set to inherit, then we need to respond for parent Font change event.

2021-06-08 06:47 UTC, RussKie requested changes

2021-06-08 06:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                    User32.SWP.NOZORDER | User32.SWP.NOACTIVATE);
I think this can be simplified to:
```suggestion
                User32.SetWindowPos(
                    this,
                    User32.HWND_TOP,
                    suggestedRectangle.X,
                    suggestedRectangle.Y,
                    suggestedRectangle.Width,
                    suggestedRectangle.Height,
                    User32.SWP.NOZORDER | User32.SWP.NOACTIVATE);
```

2021-06-08 06:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        ///  AutoScaleDimensions represents the Dpi or Font setting that the control has been scaled
Arguably it should be the way around :) `DPI` is an acronym.

2021-06-08 06:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
> +                    // child controls. These are not scaled by their parent when Dpi/Font changed events
```suggestion
                    // child controls. These are not scaled by their parent when Dpi/Font change.
```

2021-06-08 06:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                _scaledControlFont = value;
What about `_scaledControlFont?.Dispose()`?

2021-06-08 06:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        // checks if this is a container control and will be scaled by parent.
```suggestion
        // Checks if this is a container control and will be scaled by parent.
```

2021-06-08 06:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                    var scaledFont = localFont.WithSize(localFont.Size * factor);
```suggestion
                    Font scaledFont = localFont.WithSize(localFont.Size * factor);
```

2021-06-08 06:47 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/FormDpiTests.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
Please move to src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ and rename to FormTests.Dpi.cs. 
This way we have all tests related to the same type grouped together (and [nested](https://docs.microsoft.com/visualstudio/ide/file-nesting-solution-explorer?view=vs-2019)), and follow the established naming convention (e.g. ControlPaintTests.Rendering.cs, DataGridViewTests.Rendering.cs, etc.)

2021-06-08 06:47 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/FormDpiTests.cs
> +        }
We avoid using `Marshal` as it introduces unnecessary overhead. 
`SendMessageW` takes care of blittable structs:
https://github.com/dotnet/winforms/blob/9c75beabab4eb6be306ea63ef2d8396c4e185cc2/src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SendMessageW.cs#L89-L99

...all you you need to write is this:

```suggestion
            RECT suggestedRect = new(0, 0, (int)Math.Round(control.Width * factor), (int)Math.Round(control.Height * factor));
            User32.SendMessageW(control, message, wParam, ref suggestedRect);
            return suggestedRect;
        }
```

2021-06-08 06:47 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/FormDpiTests.cs
> +        }
Also do we need to check the result of SendMessage: _If an application processes this message, it should return zero_?

2021-06-08 06:52 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +        ///  AutoScaleDimensions represents the Dpi or Font setting that the control has been scaled
This was discussed. We have  APIs this way. If this is something we want to alter, happy to bring that up for discussion but not in this PR>

2021-06-08 07:00 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/FormDpiTests.cs
> +        }
I think return value check is an overhead in this test and in either case test fails. 
Constructed SendMessageW with MSDN suggested pattern. Did you test you test your suggestion?

2021-06-08 07:04 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/FormDpiTests.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
I don't feel good about this suggestion. You will be seeing FormTest.Dpi.cs , ButtonTests.Dpi.cs, ControlTests.Dpi.cs etc. I see current approach of grouping them under one folder is easy to navigate.

2021-06-08 07:09 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                    User32.SWP.NOZORDER | User32.SWP.NOACTIVATE);
This was an existing call moved around and consistence with other use cases . HandleRef supposed to keep track of ref count before disposing. I will have to  understand this more before changing. May look into it in the next PR.

2021-06-08 07:24 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/FormDpiTests.cs
> +        }
We've been removing `Marshal` from the codebase for the past few years.

2021-06-08 07:27 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                    User32.SWP.NOZORDER | User32.SWP.NOACTIVATE);
`new HandleRef(this, HandleInternal)` is an overhead, which we deal with via `IHandle` interface.
Also `this, HandleInternal` is the same as `this.HandleInternal` which is the same as `this.Handle`, which is handled by `IHandle` :)

2021-06-08 08:12 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                _scaledControlFont = value;
Considered this earlier but i was facing some runtime issues with explicit dispose. Will revisit once i narrow down the root cause of those runtime failures.

2021-06-08 08:17 UTC, RussKie approved these changes

2021-06-08 08:26 UTC, merged

2021-06-09 00:40 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                _scaledControlFont = value;
What sort of issues did you have?