Moving sub-classes to separate files
dotnet/winforms pull request #5136
Opened 2021-06-21 13:01 UTC by lisoenot

Fixes #4571

## Proposed changes

- 
- 
- 

## Customer Impact

- 
- 

## Regression? 

- Yes / No

## Risk

-

## Screenshots 

### Before

### After

## Test methodology 

- 
- 
- 

## Accessibility testing  

 

## Test environment(s) 

-

2021-06-21 13:01 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=5136) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=5136) before we can accept your contribution.<br/><br/>:x: lisoenot [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=5136)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=5136) it.</sub>

2021-06-22 03:37 UTC, vladimir-krestov requested changes
Needs refactoring

2021-06-22 03:37 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.SpanComparer.cs
> +}
Incorrect indentation

2021-06-22 03:37 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.RowSpanComparer.cs
> +}
Incorrect indentation

2021-06-22 03:37 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ColumnSpanComparer.cs
> +}
ditto

2021-06-22 03:37 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.PostAssignedPositionComparer.cs
> +        private class PostAssignedPositionComparer: IComparer
Add a missed space
```suggestion
        private class PostAssignedPositionComparer : IComparer
```

2021-06-22 03:37 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.PreAssignedPositionComparer.cs
> +        public static PreAssignedPositionComparer GetInstance
Incorrect indentation

2021-06-22 03:37 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.PreAssignedPositionComparer.cs
> +        private class PreAssignedPositionComparer: IComparer
ditto
```suggestion
        private class PreAssignedPositionComparer : IComparer
```

2021-06-22 03:37 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.SpanComparer.cs
> +#nullable disable
Check if we need this here and in the rest files

2021-06-23 01:11 UTC, RussKie reviewed
👍

2021-06-24 06:53 UTC, RussKie commented
@lisoenot if you think it is ready to go, please make it ready for review.

2021-06-24 08:30 UTC, vladimir-krestov approved these changes

2021-06-24 10:24 UTC, RussKie approved these changes

2021-06-24 10:24 UTC, merged