First stab at ComWrappers
dotnet/winforms pull request #5174
Opened 2021-06-30 09:10 UTC by kant2002

As per discussed in #5163 draft PR for IPicture support.
This change does not affect other usages of OleCreatePictureIndirect which are public in AxHost, since it require a bit more work and complicate matter.

2021-06-30 15:09 UTC, kant2002 commented
I do not get why it is failing, probably too tired. I borrow implementation from here https://github.com/dotnet/runtime/pull/54636/files#diff-e7b2c40763cc84609b47e81020ca8626ef51f475a1eb62e06c753d5500bdee76R43 Nothing fancy. Maybe fresh eyes catch issue.

2021-07-01 02:42 UTC, RussKie reviewed
Few comments on structure and styles. 

Have a look at MockAxHost, do you think you could add tests for `OleCreatePictureIndirect(ref Guid refiid)` method?

2021-07-01 02:42 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +        internal static readonly Guid IID_IPicture = new Guid(0x7BF80980, 0xBF32, 0x101A, 0x8B, 0xBB, 0x00, 0xAA, 0x00, 0x30, 0x0C, 0xAB);
Move these into Interop.CLSID

2021-07-01 02:42 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            Debug.Assert(s_wrapperEntry != null);
```suggestion
            Debug.Assert(s_wrapperEntry is not null);
```

2021-07-01 02:42 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +                if (ppstm == null)
```suggestion
                if (ppstm is null)
```

2021-07-01 02:42 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +                catch (Exception e)
By convention `e` is generally used for `EventArgs`, and `ex` for exceptions
```suggestion
                catch (Exception ex)
```

Ditto everywhere else

2021-07-01 02:42 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +        internal static class IStreamVtbl
One type per file, move to WinFormsComWrappers.IStreamVtbl.cs

2021-07-01 02:42 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            private static int Read(IntPtr thisPtr, byte* pv, uint cb, uint* pcbRead)
Keep members alphabetized, https://docs.microsoft.com/en-us/archive/blogs/brada/internal-coding-guidelines#28-file-organization

2021-07-01 02:42 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +        private class PictureWrapper : Ole32.IPicture, Ole32.IPersistStream
ditto

2021-07-01 02:42 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +                    int errorCode = ((delegate* unmanaged<IntPtr, int*, int>)(*(*(void***)_wrappedInstance + 3 /* IPicture.get_Handle slot */)))
I suggest creating a const for each of these slots, e.g. `private const int IPicture_get_Handle_slot = 3;`.

2021-07-01 02:43 UTC, RussKie commented
Tests fail with 
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.Release(IntPtr)
   at Interop+WinFormsComWrappers+PictureWrapper.Load(IStream)
   at System.Windows.Forms.Cursor.LoadPicture(IStream, System.String)
   at System.Windows.Forms.Cursor..ctor(System.IO.Stream)
   at System.Windows.Forms.Cursor..ctor(System.Type, System.String)
   at System.Windows.Forms.Cursors.get_HSplit()
```

2021-07-01 02:45 UTC, RussKie commented
@eerhardt may I get you to review please?

2021-07-01 02:59 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
> +                int errorCode = OleCreatePictureIndirectRaw(null, piid, BOOL.TRUE, &lpPicture);
>int errorCode =  [](http://example.com/codeflow?start=16&length=16)

This no longer throws. The other version throws. We should determine the desired semantics here.

2021-07-01 03:02 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            GetIUnknownImpl(out IntPtr fpQueryInteface, out IntPtr fpAddRef, out IntPtr fpRelease);
>fpQueryInteface [](http://example.com/codeflow?start=39&length=15)

~~`fpQueryInteface`~~ -> `fpQueryInterface`

2021-07-01 03:05 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            private static int Read(IntPtr thisPtr, byte* pv, uint cb, uint* pcbRead)
Not trying to rock the boat here, but this order is the vtable order and makes look up easier for COM devs. The interface definition is the one that matters so this can be reordered but I think an exemption for COM implementations should at least be considered.

2021-07-01 03:08 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +                    Marshal.ThrowExceptionForHR(((delegate* unmanaged<IntPtr, IntPtr, int>)(*(*(void***)_wrappedInstance + 5 /* IPersistStream.Load slot */)))
>Marshal.ThrowExceptionForHR( [](http://example.com/codeflow?start=20&length=28)

I prefer the same pattern above with an explicit `if (errorCode < 0)` check.

2021-07-01 03:16 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            GetIUnknownImpl(out IntPtr fpQueryInteface, out IntPtr fpAddRef, out IntPtr fpRelease);
Thanks. https://github.com/dotnet/runtime/pull/54989 :)

2021-07-01 05:55 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            private static int Read(IntPtr thisPtr, byte* pv, uint cb, uint* pcbRead)
Sure

2021-07-01 06:58 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +        internal static readonly Guid IID_IPicture = new Guid(0x7BF80980, 0xBF32, 0x101A, 0x8B, 0xBB, 0x00, 0xAA, 0x00, 0x30, 0x0C, 0xAB);
CLSIDs are used in different context than IIDs, if this is to be moved it needs to be in its own Interop.IID file/class to avoid confusion

2021-07-01 06:58 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
> +                        disposable.Dispose();
Am I missing something? while you implement `Dispose` in PictureWrapper you don't seem to implement `IDisposable` so this never gets called?

2021-07-01 06:58 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +        internal static readonly Guid IID_IPicture = new Guid(0x7BF80980, 0xBF32, 0x101A, 0x8B, 0xBB, 0x00, 0xAA, 0x00, 0x30, 0x0C, 0xAB);
CLSIDs are used in different context than IIDs, if this is to be moved it needs to be in its own Interop.IID file/class to avoid confusion

2021-07-01 10:10 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +        internal static readonly Guid IID_IPicture = new Guid(0x7BF80980, 0xBF32, 0x101A, 0x8B, 0xBB, 0x00, 0xAA, 0x00, 0x30, 0x0C, 0xAB);
Thanks! Let's move to IID file then, I sense we'll have more of those.

2021-07-01 11:31 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                _wrappedInstance = wrappedInstance;
Would it make sense to add a null-check here to detect errors early?

2021-07-01 11:31 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                Marshal.Release(_wrappedInstance);
Would it make sense to exchange `_wrappedInstance` with null to prevent use-after-release issues or double-releases?

2021-07-01 11:38 UTC, RussKie commented
Please make sure you have it built and run tests locally.

2021-07-01 18:30 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
> +                    if (picture is not null && picture.Type == (short)Ole32.PICTYPE.ICON)
>picture is not null [](http://example.com/codeflow?start=24&length=19)

This makes no sense. We use `picture` prior to this check. I see it was originally like this though. Someone should confirm the logic here.

2021-07-01 19:02 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
> +                    if (picture is not null && picture.Type == (short)Ole32.PICTYPE.ICON)
Considering the check was about throwing an "InvalidPictureType" exception I believe the check is more about the type than about being null.

2021-07-06 20:07 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
> +                if (errorCode < 0)
You don't need to check `errorCode < 0` here. Marshal.ThrowExceptionForHR will do it for you.

[https://github.com/dotnet/runtime/blob/971d204a54e3e3b57b0640fe34fad30185701d0d/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L901-L907](https://github.com/dotnet/runtime/blob/971d204a54e3e3b57b0640fe34fad30185701d0d/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L901-L907)

2021-07-06 20:09 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
> +            fixed (Guid* piid = &refiid)
If you changed the signature to `unsafe static object OleCreatePictureIndirect(Guid* refiid)`, you wouldn't need to pin anything.

2021-07-06 20:10 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
>          public unsafe static object OleCreatePictureIndirect(ref Guid refiid)
Would it make sense for this to return `IPicture`? So the caller doesn't need to cast.

2021-07-06 20:19 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                    if (errorCode < 0)
No need to compare the errorCode here and below. `Marshal` will take care of that for you.

2021-07-06 20:23 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                    streamPtr = WinFormsComWrappers.Instance.GetOrCreateComInterfaceForObject(pstm, CreateComInterfaceFlags.None);
Do you need to call QueryInterface on the returned IntPtr of this call? From my experience, it needs to be done.

[https://github.com/dotnet/runtime/blob/971d204a54e3e3b57b0640fe34fad30185701d0d/src/libraries/System.Drawing.Common/src/System/Drawing/DrawingCom.COMWrappers.cs#L69-L76](https://github.com/dotnet/runtime/blob/971d204a54e3e3b57b0640fe34fad30185701d0d/src/libraries/System.Drawing.Common/src/System/Drawing/DrawingCom.COMWrappers.cs#L69-L76)

2021-07-06 20:26 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +                    Marshal.ThrowExceptionForHR(((delegate* unmanaged<IntPtr, IntPtr, int>)(*(*(void***)_wrappedInstance + 5 /* IPersistStream.Load slot */)))
I see I commented on the exact opposite thing.

@AaronRobinsonMSFT - why duplicate code?

2021-07-07 06:17 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
> +            fixed (Guid* piid = &refiid)
Are you mean `unsafe static object OleCreatePictureIndirect(ref Guid refiid)` ?

2021-07-07 06:19 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                    streamPtr = WinFormsComWrappers.Instance.GetOrCreateComInterfaceForObject(pstm, CreateComInterfaceFlags.None);
Yes. You are right. `GetOrCreateComInterfaceForObject` return `IUnknown`. Will change.

2021-07-07 06:36 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
> +            fixed (Guid* piid = &refiid)
Isn't I need to pin on the caller side then?

2021-07-07 07:12 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
> +            fixed (Guid* piid = &refiid)
Yes, it pushes more work to the call site. Wondering what the others think.

Since GUID is a struct, it probably will be on the stack so pinning is likely very cheap anyways. The C# syntax makes it look like it has to actually do work but if I remember right it just flags the variable for the GC?

2021-07-07 18:18 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
> +            fixed (Guid* piid = &refiid)
If you look at the only caller of this method, the GUID is on the stack. Thus nothing needs to be pinned, you can just get the address of the variable on the stack:

https://github.com/dotnet/winforms/blob/d46ad2e8dc76248739d9ae22b28b399a6a6b299e/src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs#L426-L427

Yes, it means the "LoadPIcture" method needs to be marked `unsafe`, so it can say `&iid` instead of `ref iid`. But we are doing COM here, marking something as `unsafe` isn't a huge deal.

2021-07-07 19:07 UTC, wjk requested changes

2021-07-07 19:07 UTC, wjk commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
> +        private unsafe static extern int OleCreatePictureIndirectRaw(PICTDESC* pictdesc, Guid* refiid, BOOL fOwn, IntPtr* lplpvObj);
This needs `PreserveSig`.

2021-07-07 20:29 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
> +        private unsafe static extern int OleCreatePictureIndirectRaw(PICTDESC* pictdesc, Guid* refiid, BOOL fOwn, IntPtr* lplpvObj);
`PreserveSig` on `DllImport` [defaults to true](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.preservesig?view=net-5.0) so it doesn't need it, on interfaces the defaults are reversed.

2021-07-13 15:24 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
>          public unsafe static object OleCreatePictureIndirect(ref Guid refiid)
The caller cast not only to `Ole32.IPicture`, to to `Ole32.IPersistStream`. That means that most likely I need to return whole wrapper, which seems couple to implementation too much. Do you still think this is good idea, do not cast?

2021-07-13 15:26 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +                    Marshal.ThrowExceptionForHR(((delegate* unmanaged<IntPtr, IntPtr, int>)(*(*(void***)_wrappedInstance + 5 /* IPersistStream.Load slot */)))
What variant should I choose? I prefer `if (errorCode < 0)` for readability. but maybe is up to people who work here decide? @RussKie

2021-07-14 03:03 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            throw new NotImplementedException();
This looks odd... Why are we throwing NIE?

2021-07-14 04:03 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            throw new NotImplementedException();
My understanding that this is due to fact that we return only limited amount of objects from this wrapper, and this is to state that other objects not supported and require additional work (if needed). That point shouldn't be reached and as such great helps in debugging.

2021-07-14 04:07 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                _wrappedInstance = wrappedInstance;
Maybe just add `Debug.Assert(wrappedInstance != IntPtr.Zero)`? This is clearly debug time check, and unnescessary in release builds.

2021-07-14 15:36 UTC, wjk commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                IntPtr streamUnkPtr = IntPtr.Zero;
That's `streamUnknownPtr`, with an N.

2021-07-14 16:30 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                Marshal.Release(_wrappedInstance);
yes, `IntPtr.Zero` is the equivalent of a null pointer; I think its reasonable to clear the reference since otherwise any use-after-release or double-releases are passing through undetected and carry potential of memory corruption

2021-07-14 16:32 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                _wrappedInstance = wrappedInstance;
well, most people don't run debug builds of WinForms, so this has only limited use, but I agree its probably sufficient here

2021-07-15 02:30 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                IntPtr streamUnkPtr = IntPtr.Zero;
🤦‍♂️

2021-07-15 02:31 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                _wrappedInstance = wrappedInstance;
We ship the release build, so debug asserts won't help.

2021-07-15 02:36 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +                    Marshal.ThrowExceptionForHR(((delegate* unmanaged<IntPtr, IntPtr, int>)(*(*(void***)_wrappedInstance + 5 /* IPersistStream.Load slot */)))
@eerhardt the API name is somewhat vague, it's not obvious that it performs the check.
I don't think the extra check will have a material impact, so I'd keep it for clarity. But I'm happy either way.

2021-07-15 04:54 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                _wrappedInstance = wrappedInstance;
But this wrapper is implementation details, and it always instantiated via `ComWrappers.GetOrCreateObjectForComInstance` and that throw on `IntPtr.Zero`

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.cs#L234-L243

So even first `Debug.Assert` is redundant.
This is my last attempt to persuade you against unneeded checks. But this is not a hill I would die on today. Tell me your final decision and I will change accordingly.

2021-07-15 10:55 UTC, weltkante commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                _wrappedInstance = wrappedInstance;
> But this wrapper is implementation details, and it always instantiated via ComWrappers.GetOrCreateObjectForComInstance and that throw on IntPtr.Zero

Thats the intended usage but nothing is there to preserve correctness if anything changes in the runtime or someone tries to invoke the constructor directly for a quick one-off method call, or any other creative usage. If we have test coverage a `Debug.Assert` can probably detect any change in usage, or new unintended usage when new code is added with test coverage (as it should). As long as its not public API I'm not terribly concerned about checks that throw exceptions, but of course they would provide more coverage than debug-only tests which basically only ever run in WinForms unit tests.

I have some concerns on not having any checks in place because it bases correctness on assumptions that currently hold but nobody verifies (neither tests nor code). I'll leave the final decision to the team, I just wanted to point it out that as written this code is fragile.

2021-07-15 11:31 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
> +                _wrappedInstance = wrappedInstance;
I agree in principle about checks, personally on my project I would do the same most likely, but recently contributing to runtime repo, I was educated about slightly different priorities. And how people fight for performance maintaining correctness. I see no way how I can better understand current priorities, then asking questions which I do not understand, and core rationale behind them. 

> it bases correctness on assumptions that currently hold but nobody verifies (neither tests nor code)

I think that's hit nail for me, since tests here concentrated on different aspects. My underlying assumption is that .NET is rock solid, and that's true, but I can imagine that you have different view if you switch .NET 4.X => .NET Core 3.1 for WinForms. "when in Rome"...

2021-07-15 15:43 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +                    Marshal.ThrowExceptionForHR(((delegate* unmanaged<IntPtr, IntPtr, int>)(*(*(void***)_wrappedInstance + 5 /* IPersistStream.Load slot */)))
I'm totally fine either way. Just calling out the way I would write the code.

2021-07-15 15:45 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
>          public unsafe static object OleCreatePictureIndirect(ref Guid refiid)
It's fine to keep it returning `object`. I just thought casting it here could help the caller, but it doesn't really matter either way.

2021-07-15 15:49 UTC, eerhardt commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +    /// The ComWrappers implementation for System.Drawing.Common's COM interop usages.
`System.Drawing.Common's COM interop usages` => `System.Windows.Forms.Primitive's COM interop usages`

2021-07-15 15:53 UTC, eerhardt commented on src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
> +                    if (picture is IDisposable disposable)
I think we should just straight cast here. We always expect `picture` to implement IDisposable. We straight cast to `IPersistStream` above. We should do the same here.

2021-07-15 15:54 UTC, eerhardt reviewed
Overall, this LGTM. Nice work @kant2002!

2021-07-16 01:31 UTC, RussKie approved these changes

2021-07-16 01:31 UTC, merged

2021-07-16 01:32 UTC, RussKie commented
Thank you @kant2002, and everyone for your reviews.