Rework bolded dates collections to HashSet in MonthCalendar
dotnet/winforms pull request #5201
Opened 2021-07-05 10:50 UTC by lisoenot

Fixes #4647

## Proposed changes

- Change type of _arrayOfDates, _annualArrayOfDates, _monthlyArrayOfDates collections from List to HashSet in MonthCalendar
- Rework related properties

## Customer Impact

- Due to HashSet can't store duplicates of items, our collections will store only unique dates. So, if a user set some array with duplicate items to BoldedDates property, HashSet remove duplicates, and getter of BoldedDates property will return lesser collection to the user. This returned collection will be different from the initial user array.

## Regression? 

- No

## Risk

- Minimal

## Test methodology 

- Manually
- Unit tests
- 

## Test environment(s) 

-

2021-07-07 11:31 UTC, vladimir-krestov requested changes
You should rework set and add bolded dates. They should be added correctly without duplicates.

2021-07-07 11:31 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            foreach (DateTime d in _annualArrayOfDates)
The second sycle looks useless. Check it and remove, if so.

2021-07-07 11:31 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                break;
It's incorrect, because exit from the cycle after the first step. Move it inside the condition. Moreover, bit offset should be moved there too:
```cs
public void RemoveAnnuallyBoldedDate(DateTime date)
        {
            foreach (DateTime item in _annualArrayOfDates)
            {
                if (CompareDayAndMonth(item, date))
                {
                    _annualArrayOfDates.Remove(item);
                    _monthsOfYear[date.Month - 1] &= ~(0x00000001 << (date.Day - 1));

                    return;
                }
            }
        }
```

2021-07-07 11:31 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                if (CompareDayAndMonth(item, date))
It's not correct. Because we should compare years too:
```cs
public void RemoveBoldedDate(DateTime date)
        {
            foreach (DateTime item in _arrayOfDates)
            {
                if (item.Date == date.Date)
                {
                    _arrayOfDates.Remove(item);

                    return;
                }
            }
        }
```

2021-07-07 11:31 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                return;
Incorrect, it should be inside the condition

2021-07-07 11:31 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            foreach (DateTime d in _monthlyArrayOfDates)
Looks useless too

2021-07-07 11:31 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                break;
It should not break the cycle after the first step

2021-07-07 11:31 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                if (CompareDayAndMonth(item, date))
We should check Days only because there are **MonthlyBoldedDates**

2021-07-07 11:31 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            foreach (DateTime item in _monthlyArrayOfDates)
```cs
public void RemoveMonthlyBoldedDate(DateTime date)
        {
            foreach (DateTime item in _monthlyArrayOfDates)
            {
                if (item.Day == date.Day)
                {
                    _annualArrayOfDates.Remove(item);
                    _datesToBoldMonthly &= ~(0x00000001 << (date.Day - 1));

                    return;
                }
            }
        }
```

2021-07-13 09:39 UTC, vladimir-krestov requested changes

2021-07-13 09:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                return;
It's not correct. 
1) move it inside the condition
2) add a blank line before `return`

2021-07-13 09:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            foreach (DateTime item in _monthlyArrayOfDates)
@DmitryGorokhov, you haven't fixed that. Don't forget to do that.
PS. Like a review comment after fixing

2021-07-13 09:57 UTC, vladimir-krestov requested changes
Rework tests.
Rename test datas

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +        public void MonthCalendar_AnnuallyBoldedDates_Set_GetReturnsExpected_IfControlNotCreated(DateTime[] value, DateTime[] expected)
Creating of Handle doesn't affect `AnnuallyBoldedDates` setter. So just keep one test when Handle is not created.
Name it "MonthCalendar_AnnuallyBoldedDates_Set_GetReturnsExpected".
Remove `MonthCalendar_AnnuallyBoldedDates_Set_GetReturnsExpected_IfControlCreated` at all because it's just a clone.

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +        public static IEnumerable<object[]> AnnuallyBoldedDates_RemoveItem_TestData()
If a test data is used once, name it like a test + TestData.
```suggestion
        public static IEnumerable<object[]> MonthCalendar_AnnuallyBoldedDates_RemoveItem_GetReturnsExpected_TestData()
```

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +        public static IEnumerable<object[]> AnnuallyBoldedDates_RemoveAll_TestData()
All `expected` are `Array.Empty<DateTime>()`. So remove it from here.
And use `Assert.Empty` in the test body.

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +        public void MonthCalendar_BoldedDates_Set_GetReturnsExpected_IfControlNotCreated(DateTime[] value, DateTime[] expected)
ditto, keep one test when Handle is not created.

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
>          [MemberData(nameof(BoldedDates_Set_TestData))]
ditto, name the test data like a test name + TestData

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +        public static IEnumerable<object[]> BoldedDates_RemoveItem_TestData()
ditto

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +        public static IEnumerable<object[]> BoldedDates_RemoveAll_TestData()
ditto, use Assert.Empty instead

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +        public void MonthCalendar_MonthlyBoldedDates_Set_GetReturnsExpected_IfControlNotCreated(DateTime[] value, DateTime[] expected)
ditto

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            yield return new object[] { null, Array.Empty<DateTime>() };
don't forget to do the same as above here

2021-07-13 09:57 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            Assert.Equal(expected, calendar.MonthlyBoldedDates);
Assert.Empty

2021-07-19 12:53 UTC, vladimir-krestov approved these changes
Looks good to me

2021-07-19 14:50 UTC, kirsan31 commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
>          /// </summary>
May be update comments?

2021-07-19 14:54 UTC, kirsan31 commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
>          /// </summary>
```cs
// comparing dates, only the **day and month** are used.
```
Here too, may be other places?

2021-07-19 15:12 UTC, kirsan31 commented
I thought that main motivation for this change is add/remove performance. Any one checked this?
Performance gain of `AddBoldedDate` is obvious. And what about `AddAnnuallyBoldedDate` and `AddMonthlyBoldedDate`? I'm worried about the added loop:
https://github.com/dotnet/winforms/blob/b65cc60cac67c09902d0b5750bd0b1d372bb2029/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L990-L996

In theory, we can avoid it. 
But honestly I don't know if it's worth messing around with this :)

2021-07-20 07:27 UTC, vladimir-krestov commented
@kirsan31, actualy, reworking is necessary anyway, because `_annualArrayOfDates` and `_monthlyArrayOfDates` could keep a lot of dates. We can add several dates with the same Dates or Dates and Months there, and a calendar will bold the dates until you remove all of them.
In the **main** branch:
- `RemoveMonthlyBoldedDate` works incorrectly at all. If you add some monthly bolded dates (eg. `DateTime(2021, 7, 20), DateTime(2021, 2, 20)`) and try to remove `DateTime(1996, 3, 20)`, the dates won't be removed, because `RemoveMonthlyBoldedDate` checks Day and Month, that is not correct, we should check a Day only.
- `RemoveAnnuallyBoldedDate` requires to remove all bolded dates. If you add 3 dates: eg. `DateTime(2021, 7, 20), DateTime(2013, 7, 20),  DateTime(1983, 7, 20)` to `AnnuallyBoldedDates`, you will have to call `RemoveAnnuallyBoldedDate(new DateTime(1996, 7, 20))` 3 times.
- `RemoveBoldedDate` requires to remove all bolded dates. If you add 3 same dates: eg. `DateTime(2021, 7, 20)` - 3 times, then you will have to call `RemoveBoldedDate(new DateTime(2021, 7, 20))` 3 times to remove the bolded date.

But there is one important point. Our change may affect developers, because set/add/remove bolded dates are public API action. Our change may break their internal workarounds and logic.
@merriemcgaw, should we fix the incorrect work of MonthCalendar bolded dates actions, even if it may affect public API?

2021-07-20 07:34 UTC, vladimir-krestov commented
I did a benchmark of the methods using BenchmarkDotNet Nuget. I compared all the methods of **main** branch and this PR implementation. Here are results:

![image](https://user-images.githubusercontent.com/49272759/126279693-696cda14-5788-4234-9282-801f8ed35e9e.png)

As you can see, `HashSet` is not faster.
`RemoveMonthlyBoldedDate` and `RemoveAnnuallyBoldedDate` are faster for HashSet due to reworked alghoritms. With `List` it would be faster.

2021-07-20 07:43 UTC, kirsan31 commented
@vladimir-krestov my point 

> But honestly I don't know if it's worth messing around with this :)

was not about whole this PR, but about eliminating performance loss on new added loop.

> But there is one important point. Our change may affect developers, because set/add/remove bolded dates are public API action. Our change may break their internal workarounds and logic.

One more thing, after this change, in general case all three public collection property will be:
` SET AnnuallyBoldedDates` **!=** `GET AnnuallyBoldedDates`

2021-07-20 07:58 UTC, kirsan31 commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
>              }
```cs
_arrayOfDates.Remove(date);
```
?

2021-07-22 20:26 UTC, JeremyKuhne commented
I wouldn't mess with the collections without a clear, measured win. This class originally was using `ArrayList`. `List<DateTime>` is significantly more performant, so we're already way better.  Generally speaking the class is way more performant than it used to be as the interop has been cleaned up. The comment in the code should probably be removed.

There are other things that could be done here if you want to make an improvement:

- Setting `BoldedDates` should use `AddRange`.
- WmDateBold could be significantly faster.
  - There is no need to create a wrapper DateBoldEventArgs class.
  - BoldDates could also write directly into the buffer being used (don't allocate arrays you don't need).
  - The buffer has no need to use Marshal.
    - Can use a pinning `GCHandle` kept in the class with a normal `int[]` array.
    - Better yet, allocate a pinned array up front using [`GC.AllocateArray`](https://docs.microsoft.com/en-us/dotnet/api/system.gc.allocatearray?view=net-5.0) and just use `fixed` to get the address.

2021-08-24 06:43 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> -        private readonly List<DateTime> _arrayOfDates = new List<DateTime>();
Please remove word `array` from names when you make them lists again.

2021-09-01 06:29 UTC, Tanya-Solyanik commented
@vladimir-krestov and @DmitryGorokhov  - I suggest closing this PR. This PR discussed 2 issues:
1. Add/Remove bold dates is messy.  - I think this is not a customer blocking issue. Devs can define canonical form for dates to be "bolded" if they are constantly adding/removing them. We can also wait for customer to request changes in the future. If you disagree, please file a dedicated workitem.
2.  Jeremy's suggestion on perf is done -  https://github.com/dotnet/winforms/pull/5561, please review this change because this is an important pattern to follow.

2021-09-01 08:31 UTC, vladimir-krestov commented
@Tanya-Solyanik, I agree, let's close this.

2021-09-01 08:31 UTC, closed without merging

2021-09-01 14:36 UTC, kirsan31 commented
@vladimir-krestov and what to do with https://github.com/dotnet/winforms/issues/4647?