Rework casting IntPtr by using ParamToInt
dotnet/winforms pull request #5203
Opened 2021-07-06 10:00 UTC by lisoenot

Fixes #

## Proposed changes

- Rework cast using `(int)` and `ToInt32` constructions to `PARAM.ToInt` method

## Customer Impact

- No

## Regression? 

- No

## Risk

- Minimal

2021-07-07 07:37 UTC, RussKie requested changes
👍

2021-07-07 07:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                if (PARAM.ToInt(User32.SendMessageW(this, (User32.WM)MCM.SETRANGE, (IntPtr)flags, ref sa[0])) == 0)
```suggestion
                if (User32.SendMessageW(this, (User32.WM)MCM.SETRANGE, (IntPtr)flags, ref sa[0]) == IntPtr.Zero)
```

2021-07-07 07:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +                if (PARAM.ToInt(User32.SendMessageW(tv, (User32.WM)TVM.GETITEMRECT, (IntPtr)1, ref rc)) == 0)
ditto

2021-07-07 07:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +                if (PARAM.ToInt(User32.SendMessageW(tv, (User32.WM)TVM.GETITEMRECT, IntPtr.Zero, ref rc)) == 0)
ditto

2021-07-07 07:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +                bool visible = (PARAM.ToInt(User32.SendMessageW(tv, (User32.WM)TVM.GETITEMRECT, (IntPtr)1, ref rc)) != 0);
ditto

2021-07-07 07:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +                int style = unchecked(PARAM.ToInt(User32.GetWindowLong(this, User32.GWL.STYLE)));
```suggestion
                int style = PARAM.ToInt(User32.GetWindowLong(this, User32.GWL.STYLE));
```

2021-07-07 07:53 UTC, vladimir-krestov submitted a review, later dismissed

2021-07-08 18:43 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +                bool visible = (PARAM.ToInt(User32.SendMessageW(tv, (User32.WM)TVM.GETITEMRECT, (IntPtr)1, ref rc)) != 0);
Compare with IntPtr.Zero

2021-07-08 18:44 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +                int style = unchecked(PARAM.ToInt(User32.GetWindowLong(this, User32.GWL.STYLE)));
remove `unchecked`

2021-07-09 00:23 UTC, RussKie reviewed
👍 modulo the outstanding comments

2021-07-09 07:44 UTC, RussKie approved these changes

2021-07-09 08:05 UTC, merged