Implementing-invoke-action-of-UpDown-button
dotnet/winforms pull request #5206
Opened 2021-07-07 09:52 UTC by DmitryGorokhov

Fixes #

## Proposed changes

- Overrided `DoDefaultAction` method in `DirectionButtonAccessibleObject` class
- Adding unit tests (in progress)

## Customer Impact

- 
- 

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before

If you trigger the Invoke action, the value is not updated

### After

![invokeUpDownButton](https://user-images.githubusercontent.com/58004471/124738432-96b08e00-df21-11eb-8f09-3174239223a8.gif)

## Test methodology 

- Manually
- Unit tests
- Accessibility tests

## Accessibility testing  

- Inspect
- Accessibility Insights

## Test environment(s) 

-

2021-07-08 19:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs
> +            foreach (string item in new string[] { "First", "Second", "Third", "Fourth" })
Designer will not be able to support `foreach` anytime soon, standard method for the designer to use would be `AddRange(new[]{"a","b"})`, but it is not supported yet due to a bug. 
Could you please replace the loop with multiple `Add`s or `AddRange`?

2021-07-08 19:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DomainUpDownAccessibleObjectTests.cs
> +            domainUpDown.Items.Add(testValue1);
Please replace multiple Add calls with an `AddRange`, and the same in the next test

2021-07-08 19:52 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
> +
Move the method above in alphabet order

2021-07-08 19:52 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
> +                    public override void DoDefaultAction()
Implement `IsPatternSupported` for `LegacyIAccessible` and `Invoke` patterns.
Add the corresponding cases to `GetPropertyValue` (see the rest objects for example)
Implement `Invoke` method and put your code implementation there.
Rework `DoDefaultAction` like this:
```cs
public override void DoDefaultAction() => Invoke();
```

2021-07-08 19:52 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
>                      public override AccessibleObject Parent => _parent;
Make the forllowing for `_parent` while we here:
```cs
_parent = parent ?? throw new ArgumentNullException(nameof(parent));
```

2021-07-08 19:52 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DomainUpDownAccessibleObjectTests.cs
> +        }
You don't test `DomainUpDownAccessibleObject`, you are testing `DirectionButtonAccessibleObject`, so create a separate test file and add these tests there.
Make the same for `NumericUpDown` (you can rework the tests to have `MemberData` with NumericUpDown and DomainUpDown types)
```suggestion
        [WinFormsTheory]
        [InlineData(0)]
        [InlineData(1)]
        public void DirectionButtonAccessibleObject_Invoke_DoesNothing_IfControlIsNotCreated(int childId)
        {
            using DomainUpDown domainUpDown = new();
            domainUpDown.Items.AddRange(new string[] { "First", "Second", "Third" });
            domainUpDown.SelectedIndex = 1; // Select the second item

            // UpButton has 0 childId, DonwButton has 1 childId
            AccessibleObject directionButton = domainUpDown.AccessibilityObject.GetChild(1).GetChild(childId);
            directionButton.Invoke();

            // The selected index is not changed
            Assert.Equal(1, domainUpDown.SelectedIndex);
            Assert.False(domainUpDown.IsHandleCreated);
        }

        [WinFormsTheory]
        [InlineData(0, 0)]
        [InlineData(1, 2)]
        public void DirectionButtonAccessibleObject_Invoke_ChangesValue(int childId, int expectedIndex)
        {
            using DomainUpDown domainUpDown = new();
            domainUpDown.Items.AddRange(new string[] { "First", "Second", "Third" });
            domainUpDown.SelectedIndex = 1; // Select the second item
            domainUpDown.CreateControl();

            // UpButton has 0 childId, DonwButton has 1 childId
            AccessibleObject directionButton = domainUpDown.AccessibilityObject.GetChild(1).GetChild(childId);
            directionButton.Invoke();

            // The selected index is not changed
            Assert.Equal(expectedIndex, domainUpDown.SelectedIndex);
            Assert.True(domainUpDown.IsHandleCreated);
        }
```

2021-07-09 18:35 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
> +                    public override void DoDefaultAction()
Please clarify why this comment was resolved and yet the legacy patter had not been added?

2021-07-11 14:33 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
> +                    public override void DoDefaultAction()
Main idea: The `Invoke` method is realized in the base class (`AccessibleObject`) that calls `DoDefaultAction` method. So, if we override `DoDefaultAction` in child class, we don't need to do any action

2021-07-12 11:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
> +                    public override void DoDefaultAction()
Approved.
- `AccessibleObject.cs` implements `Invoke` pattern for an AO with `PushButton` `Role` (see `IsInvokePatternAvailable` property)
- `AccessibleObject's` implementation:
![image](https://user-images.githubusercontent.com/49272759/125279047-22f4f380-e31c-11eb-82d8-b7bc1c7f1e90.png)

2021-07-13 00:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
> +                    public override void DoDefaultAction()
Makes sense, we need to move more methods to this model

2021-07-13 00:23 UTC, Tanya-Solyanik submitted a review, later dismissed

2021-07-13 00:23 UTC, Tanya-Solyanik commented
/azp run

2021-07-13 00:31 UTC, Tanya-Solyanik commented
@DmitryGorokhov - could you please provide privates and test info to @Olina-Zhang

2021-07-13 05:35 UTC, vladimir-krestov commented
> @DmitryGorokhov - could you please provide privates and test info to @Olina-Zhang

I'll do it.

2021-07-13 11:51 UTC, vladimir-krestov requested changes
Waiting for fixing test issues

2021-07-15 17:31 UTC, dreddy-work commented
@vladimir-krestov and @DmitryGorokhov , are the test issues raised by CTI covered?

2021-07-16 06:21 UTC, DmitryGorokhov commented
> @vladimir-krestov and @DmitryGorokhov , are the test issues raised by CTI covered?

Yes, it's done. The branch is rebased on main and prepared to merge

2021-07-16 19:36 UTC, Tanya-Solyanik approved these changes
Looks good to me, @vladimir-krestov, are all your concerns addressed now?

2021-07-19 07:24 UTC, vladimir-krestov approved these changes
Looks much better

2021-07-19 17:42 UTC, dreddy-work approved these changes

2021-07-19 17:42 UTC, merged

2021-07-28 02:38 UTC, Zheng-Li01 commented
Verified the function in the 6.0.100-rc.1.21377.28, the invoke action of NumericUpDown & DomainUpDown controls has been implemented that working well in the Inspect & AccessibilityInsight tools. see below GIF.
![pull5296](https://user-images.githubusercontent.com/38325459/127254771-577cc231-c51c-4d7f-9e2d-9ddf564b0a6b.gif)