Possibility to align minimized MDI child to default location (TOP LEFT)
dotnet/winforms pull request #5221
Opened 2021-07-09 09:14 UTC by kirsan31

### Draft.

Fix https://github.com/dotnet/winforms/issues/4720.

## Proposed changes

- Add public bool property `MdiChildrenMinimizedAnchorTop` to `Form` class.

## Customer Impact

WinForms override standard MDI behavior without option to use original one. It's lead to all child windows layout (with minimized windows) are mess up after main window resize. This can happened after simple resize, or after resolution changed (for example if your connect by rdp from other device), etc... Customer can use `MdiChildrenMinimizedAnchorTop` to revert for Windows default behavior.

## Regression? 

No

## Risk

Minimal.

## Screenshots
![Designer](https://user-images.githubusercontent.com/17767561/125053907-49adf280-e0ae-11eb-8fb0-d6679d6de71d.jpg)

https://user-images.githubusercontent.com/17767561/125053862-3e5ac700-e0ae-11eb-8ff1-3b5f72500f9d.mp4

## Test methodology

Manual.

## Accessibility testing  

ToDo?

## To do.
1. Discuss a name for the property.
2. Discuss a description for the property. Translations?
3. Category: Style or may be Layout?

2021-07-09 09:14 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=5221) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=5221) before we can accept your contribution.<br/><br/>:x: kirsan31 [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=5221)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=5221) it.</sub>

2021-07-13 17:47 UTC, kirsan31 commented
> @kirsan31, Good news - API is approved with suggestions. Details are in the associated issue. Can you please update this PR and mark it ready for review?

Excellent. I'll do it as soon as I can.

2021-07-14 18:49 UTC, dreddy-work reviewed
@Tanya-Solyanik

2021-07-14 18:49 UTC, dreddy-work commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>true - anchoring minimized MDI children to the BottomLeft of the parent form (WinForms default). false - anchoring minimized MDI children to the TopLeft of the parent form (windows default
I would change this description to something like, "Anchoring minimized MDI children to the BottomLeft of the parent Form (WinForms default). Disabling this flag will result in Windows default (i.e. TopLeft)"

2021-07-15 02:27 UTC, RussKie requested changes

2021-07-15 02:27 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        /// </summary>
Please have a look how all other properties are described. The summary wording must start with something like "Gets or sets...", and it mustn't contain value's information.


```suggestion
        /// <summary>
        /// Gets or sets the anchoring for minimized MDI children.
        /// </summary>
        /// <value><see langword="true" /> to anchor minimized MDI children to the bottom left of the parent form; <see langword="false" /> to anchor to the top left of the parent form (Windows default).</value>
```

2021-07-15 02:27 UTC, RussKie commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>true - anchoring minimized MDI children to the BottomLeft of the parent form (WinForms default). false - anchoring minimized MDI children to the TopLeft of the parent form (windows default
```suggestion
    <value>Gets or sets the anchoring for minimized MDI children.</value>
```

2021-07-15 02:27 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        public bool MdiChildrenMinimizedAnchorBottom { get; set; } = true;
Default `true` is this consistent with the behaviour in .NET Framework?

2021-07-15 07:02 UTC, kirsan31 commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        public bool MdiChildrenMinimizedAnchorBottom { get; set; } = true;
Yes - BottomLeft.

2021-07-15 07:05 UTC, kirsan31 commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        /// </summary>
Got it, thanks.

2021-07-15 08:25 UTC, RussKie requested changes
How can we test the change?

1. Please update our manual [MDI sample](https://github.com/dotnet/winforms/blob/e0c821b17863458611e4e056c16eb1ad65f9ce9a/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs#L116-L119) in a way that we can toggle the property on and off and see the result.
2. We'll also need an automated test, have a look at our maui tests and add a new test project for MDI. Maybe [MauiPrintPreviewDialogTests](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiPrintPreviewDialogTests/MauiPrintPreviewDialogTests.cs) be a good start?

2021-07-15 08:25 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        /// <value><see langword="true" /> to anchor minimized MDI children to the bottom left of the parent form (WinForms default); <see langword="false" /> to anchor to the top left of the parent
```suggestion
        /// <value><see langword="true" /> to anchor minimized MDI children to the bottom left of the parent form; <see langword="false" /> to anchor to the top left of the parent form.</value>
```

The platform defaults need to be placed under `remarks`, e.g. https://docs.microsoft.com/dotnet/api/system.windows.forms.mdiclient.backgroundimage
Something like:
```xml
<remarks>
By default Windows Forms anchors MDI children to the bottom left of the parent form, whilst the Windows default is top left.
</remarks>
```

2021-07-15 08:26 UTC, RussKie commented
Rebase is generally better than tracking merges
![image](https://user-images.githubusercontent.com/4403806/125755227-c01b8088-ccec-44cf-92fa-e14cad7ac962.png)

2021-07-15 09:10 UTC, kirsan31 commented
> How can we test the change?
> 
> 1. Please update our manual [MDI sample](https://github.com/dotnet/winforms/blob/e0c821b17863458611e4e056c16eb1ad65f9ce9a/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs#L116-L119) in a way that we can toggle the property on and off and see the result.
> 2. We'll also need an automated test, have a look at our maui tests and add a new test project for MDI. Maybe [MauiPrintPreviewDialogTests](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiPrintPreviewDialogTests/MauiPrintPreviewDialogTests.cs) be a good start?

I will look into it...

2021-07-15 12:13 UTC, kirsan31 commented
> 1. Please update our manual [MDI sample](https://github.com/dotnet/winforms/blob/e0c821b17863458611e4e056c16eb1ad65f9ce9a/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs#L116-L119) in a way that we can toggle the property on and off and see the result.

@RussKie designer not working with this error:
![image](https://user-images.githubusercontent.com/17767561/125786002-94e552ef-9d32-4629-b519-d96cee6515ed.png)
Any advice?

2021-07-15 13:06 UTC, RussKie commented
Hmm... We don't use assembly, at least directly anywhere... 
"Works on my machine" 😃 Though I'm on 17preview2
![image](https://user-images.githubusercontent.com/4403806/125792716-492e38ce-089b-4678-8e28-3eddfaee7520.png)


Maybe try deleting artifacts folder, then .\build.cmd, followed by .\start-vs.cmd?

2021-07-15 13:25 UTC, kirsan31 commented
> Maybe try deleting artifacts folder, then .\build.cmd, followed by .\start-vs.cmd?

Not helped sadly :( So I have 2 options here:
 - Uninstall 16.11 and install 17.
 - Manually edit `MdiChild.Designer.cs`.
 ...

2021-07-15 13:47 UTC, RussKie commented
I'm sure it worked in v16 as well.
There's a 3rd option as well - make a quick project copy these files on it, make changes, copy back.

I don't think the extent of changes that require the designer is significant.

2021-07-15 13:51 UTC, kirsan31 commented
> I'm sure it worked in v16 as well.
> There's a 3rd option as well - make a quick project copy these files on it, make changes, copy back.
> 
> I don't think the extent of changes that require the designer is significant.

I've already install vs17p2 and it's worked :)
![image](https://user-images.githubusercontent.com/17767561/125799291-70bcd219-bd37-4157-8363-4bd32391f4f1.png)
Strange...

2021-07-15 17:28 UTC, dreddy-work commented
@kirsan31 , for VS 2022 crash, was it simple scenario of opening designer from your test application? or did you perform any other actions?

2021-07-15 17:40 UTC, kirsan31 commented
> @kirsan31 , for VS 2022 crash, was it simple scenario of opening designer from your test application? or did you perform any other actions?

@dreddy-work 
I was able normally open `src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MdiChild.cs` in VS2022 (in VS2019 it was failing with error above).
But VS2022 was not displaying control's properties. And when I was trying to see some of them (selecting different controls on the form and click properties menu), VS crashed a lot. It was crashed also when I was trying to select control in this dropdown:
![image](https://user-images.githubusercontent.com/17767561/125832039-88e560b1-d2c1-4dae-83f0-1ea0abc5a22a.png)

2021-07-16 00:01 UTC, RussKie commented
It may be that the latest .NET requires the newer version...
________________________________
From: kirsan31 ***@***.***>
Sent: Thursday, 15 July 2021 11:51 PM
To: dotnet/winforms ***@***.***>
Cc: Igor Velikorossov ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [dotnet/winforms] Possibility to align minimized MDI child to default location (TOP LEFT) (#5221)


I'm sure it worked in v16 as well.
There's a 3rd option as well - make a quick project copy these files on it, make changes, copy back.

I don't think the extent of changes that require the designer is significant.

I've already install vs17p2 and it's worked :)
[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F17767561%2F125799291-70bcd219-bd37-4157-8363-4bd32391f4f1.png&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7Cc89ded3c3d654a7e0d6608d94797a244%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637619538879074684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RzHXZJM8kPuNPzsFp1obvAcRtLc17H2fJK3hbnI%2FGuA%3D&reserved=0>
Strange...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fpull%2F5221%23issuecomment-880711765&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7Cc89ded3c3d654a7e0d6608d94797a244%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637619538879084680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y46eUGfgPfci49KH329hgfgLa0XM7LdWMdBNFhctdLg%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABBTEXVU4PVJMOX5O4D2C23TX3RVXANCNFSM5ACMCEDA&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7Cc89ded3c3d654a7e0d6608d94797a244%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637619538879094699%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N3iFVYBpk3768wRODETwJg9l%2B7keTUAouT3si7KP7cM%3D&reserved=0>.

2021-07-16 07:26 UTC, kirsan31 commented
> 1. Please update our manual MDI sample in a way that we can toggle the property on and off and see the result.

Done:

https://user-images.githubusercontent.com/17767561/125908938-4e7904ca-9667-4490-b014-c7ed39eb036b.mp4

2021-07-19 08:01 UTC, RussKie requested changes
Almost there! 👍

2021-07-19 08:01 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +            int Posdiff = ClientSize.Height - frm.Top;
1. Give variables meaningful name, e.g. `childFormMinimizedPositionY`
2. Local variable names must be in camelCase.

2021-07-19 08:13 UTC, kirsan31 commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +            var frm = new Form
I don't know your Maui tests infrastructure. Is it safe to call `Dispose` on child form before it was closed? Or is it just necessary?

2021-07-19 10:18 UTC, RussKie approved these changes

2021-07-19 17:37 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +                return new ScenarioResult(false, $"MDI child changed bottom relative position with {nameof(MdiChildrenMinimizedAnchorBottom)} == true!", p.log);
```suggestion
                return new ScenarioResult(false, $"MDI child changed bottom relative position with {nameof(MdiChildrenMinimizedAnchorBottom)} == {MdiChildrenMinimizedAnchorBottom}!", p.log);
```

2021-07-19 17:37 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +                return new ScenarioResult(false, $"MDI child changed top relative position with {nameof(MdiChildrenMinimizedAnchorBottom)} == false!", p.log);
```suggestion
                return new ScenarioResult(false, $"MDI child changed top relative position with {nameof(MdiChildrenMinimizedAnchorBottom)} == {MdiChildrenMinimizedAnchorBottom}!", p.log);
```

2021-07-19 17:39 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +        public ScenarioResult Resize_When_MdiChildrenMinimizedAnchorBottom_True(TParams p)
```suggestion
        public ScenarioResult Resize_When_MdiChildrenMinimizedAnchorBottom_Deafult(TParams p)
```

2021-07-19 17:40 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +            MdiChildrenMinimizedAnchorBottom = true;
This is default value.

2021-07-19 18:44 UTC, kirsan31 commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +            MdiChildrenMinimizedAnchorBottom = true;
Yes, but as I understand currently Maui test scenarios run on the same instance. And it seems that order of scenarios the same as in code. So, if I simple remove this line `MdiChildrenMinimizedAnchorBottom = true;` the test will fail. Overall I think that rely on position in code it's not right thing to do. Do you want me to use reflection to get `DefaultValueAttribute` here?

2021-07-19 18:46 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +            MdiChildrenMinimizedAnchorBottom = true;
Nope. In this case, I would add this comment there for reference.

2021-07-19 19:42 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +            MdiChildrenMinimizedAnchorBottom = true;
Did you forget to add comment?

2021-07-19 19:52 UTC, kirsan31 commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +            MdiChildrenMinimizedAnchorBottom = true;
Ahhh, I misunderstand your again lol :)))  Iwas thinking that this is your comment to explain method rename :man_facepalming:

2021-07-19 20:03 UTC, kirsan31 commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +            MdiChildrenMinimizedAnchorBottom = true;
I hope it's done on second try 😊

2021-07-19 20:25 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs
> +            // This is default value.
```suggestion
            // Currently Maui test scenarios run on the same instance and this flag might have been set to a non-default values in the previous tests. So, explicitly setting it to `default' value `true` to make tests reliable.
```

2021-07-19 20:26 UTC, dreddy-work approved these changes

2021-07-19 20:26 UTC, merged

2021-07-22 11:03 UTC, RussKie commented
> But VS2022 was not displaying control's properties. And when I was trying to see some of them (selecting different controls on the form and click properties menu), VS crashed a lot. It was crashed also when I was trying to select control in this dropdown:
> ![image](https://user-images.githubusercontent.com/17767561/125832039-88e560b1-d2c1-4dae-83f0-1ea0abc5a22a.png)

@kirsan31 have you reported those via the VS Feedback? We're actively working through the user feedback to ensure things like that don't happen.

@merriemcgaw @JeremyKuhne FYI

2021-07-22 11:15 UTC, kirsan31 commented
@RussKie 

> @kirsan31 have you reported those via the VS Feedback? We're actively working through the user feedback to ensure things like that don't happen.

Sadly no, at that moment I was frantically trying to find a way to open your form in the designer to write a test :)
P.s. In the end I wrote everything manually anyway :)
P.p.s. Your suggestion

> There's a 3rd option as well - make a quick project copy these files on it, make changes, copy back. 

naturally worked, but after small trivial change and save it in designer, whole `MdiChild.Designer.cs` was totally messed up with lots of unnecessary changes :(