Add support for IFileOpenDialog
dotnet/winforms pull request #5319
Opened 2021-07-22 13:24 UTC by kant2002

CCW Wrapper in the PR was autogenerated using source generator
and tailored based on my previous experience.
As such I have strange local variables sometimes.
Also I do not implemented anything yet for following interfaces
- `Shell32.IFileDialogEvents` (CCW needed)
- `Shell32.IShellItem` (RCW from built-in COM)
- `Shell32.IShellItemArray` (RCW from built-in COM)

I plan to implement them, when collect all feedback on quality of this PR, so all improvements would be passed to next work.

What to do with code which maybe never called. How to detect that code?  or should I bother with that and provide implementation for all methods?
For example I do not see errors in tests from `Shell32.IFileDialogEvents`, even if this interface used by `VistaDialogEvents` and passed to `IFileOpenDialog.Advise` method. So removing code and look where it fails in tests would be not practical.

Would like to ask question about `IShellItem` and `IShellItemArray` relationships. I will lookup on MSDN, but maybe collective conscionesness maybe help me better.
So question: Does these completely unrelated interfaces, or there some `IShellItem` implementation which implement `IShellItemArray` as well. Answer affects how I implement RCW for these interfaces.

Contributes to #5163

2021-07-23 17:16 UTC, dreddy-work commented
@kant2002 , how do we test these changes?

2021-07-23 17:57 UTC, kant2002 commented
@dreddy-work I assume some manual smoke test and writing more automated tests in separate PRs if needed. I would like to know what tests do you need to feel confident in the change?

2021-07-23 18:01 UTC, kant2002 commented
MAybe problem that we do not detect issue lies in the fact that tests do not create `IFileDialog` See 
https://github.com/dotnet/winforms/blob/94e03c4529b3f766c2d164d20681947038d8a2a3/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs#L701

2021-07-24 14:02 UTC, kant2002 commented
List of cases which are not covered right now and which will fails at runtime.
```
FolderBrowserDialog dlg = new();
dlg.UseDescriptionForTitle = false;
dlg.Description = "some desc";
dlg.Show();
```
In general I do not see any tests which exercise opening actual `FolderBrowserDialog`.
Other case which I found
1. launch `WinformsControlsTest` 
2. Press `Dialogs`
3. Press 'Open dialogs' 
Crash immediately since it is set default folder, I do not cover that path.

I would like add these small tests somehere, but not sure what location best suited for that.

2021-07-26 05:37 UTC, kant2002 commented
I do not get why Debug tests succeed. Release fails as expected in the new test which I add in #5344

2021-07-26 05:44 UTC, RussKie commented
```
    System.Windows.Forms.IntegrationTests.WinformsControlsTest.WinformsControlsTest_OpenFolderBrowserDialogTest [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs(166,0): at System.Windows.Forms.IntegrationTests.WinformsControlsTest.WinformsControlsTest_OpenFolderBrowserDialogTest()
```

2021-07-26 05:44 UTC, RussKie commented
Have you tried running tests locally under Release?

2021-07-26 06:03 UTC, kant2002 commented
Failure is expected, success is not. I rebase with test commit to test that we catch issue with prev implementation. I run under Debug locally and it fails, that's how I check that test catch what I want. Did not run under Release locally.

2021-07-27 16:59 UTC, dreddy-work commented
@JeremyKuhne can you take a quick look at this change and share your feedback?

2021-07-27 18:44 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                var local_0 = Marshal.StringToCoTaskMemUni(pszTitle);
This allocation isn't necessary. Just pin `pszTitle`. Same goes for the other methods using `CoTaskMem`..

2021-07-27 18:49 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemWrapper.cs
> +                ppszName = Marshal.PtrToStringUni(local_1)!;
You're not freeing the returned memory after converting it to a string. `PtrToStringUni` does not free the pointer it is given.

2021-07-27 18:50 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemWrapper.cs
> +                int local_1;
This should be `SFGAOF`, not int.

2021-07-27 18:51 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemWrapper.cs
> +            Interop.HRESULT Interop.Shell32.IShellItem.BindToHandler(IntPtr pbc, ref Guid bhid, ref Guid riid, out IntPtr ppv)
You shouldn't need to use `Interop.` in these files.

2021-07-27 18:54 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemWrapper.cs
> +    internal unsafe partial class WinFormsComWrappers
As with our other class/folders, this should be under "Interop\WinFormsComWrappers\". Or better yet change the static class to `ComWrappers` and put it in "Interop\ComWrappers". We don't need "WinForms" in the class names.

2021-07-27 18:58 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                    result = Marshal.QueryInterface(local_0_unk, ref local_psi_IID, out local_0);
You're not releasing the `local_0`.

2021-07-27 19:01 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                IntPtr local_0;
Can we please use the actual parameter name for the locals? This one should be `ppv`.

2021-07-27 23:22 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemWrapper.cs
> +    internal unsafe partial class WinFormsComWrappers
Eh, don't rename to `ComWrappers`. Too painful. :)

2021-07-27 23:24 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
> +        internal static Guid IShellItem = new Guid(0x43826D1E, 0xE718, 0x42EE, 0xBC, 0x55, 0xA1, 0xE2, 0x61, 0xC3, 0x7B, 0xFE);
Can you change these to `internal static Guid IShellItem { get } = new();` please?

2021-07-27 23:30 UTC, JeremyKuhne commented
We probably shouldn't be taking changes of this nature into v6 at this point. We'll discuss the best way to handle making progress for v7 as a team and come back with info.

If you can clean up the local variable names and double check ref counting and allocations I'll take another look. Thanks!

2021-07-27 23:31 UTC, JeremyKuhne requested changes
Please clean up the local variable names and take a look at the other feedback.

2021-08-12 16:56 UTC, dreddy-work commented
@kant2002 , this one also needs your attention.

2021-08-14 19:12 UTC, kant2002 commented
@dreddy-work I did not forgot about that one. I trying to find single time slot where I can sit and cleanup all recommendations from Jeremy. I will finish with them till Friday I think.

2021-08-25 10:23 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                IntPtr local_0;
I do not sure how to name these parameters. If possible, I prefer change `psi` to `shellItem` for example. Then I can use `psi` for actual parameters passed to native side. does that works for you? Should I change definitions for `Shell32.IFileOpenDialog` too then?

2021-08-25 12:00 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemWrapper.cs
> +            Interop.HRESULT Interop.Shell32.IShellItem.BindToHandler(IntPtr pbc, ref Guid bhid, ref Guid riid, out IntPtr ppv)
Done.

2021-09-07 23:39 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.COMDLG_FILTERSPEC_native.cs
> +        internal struct COMDLG_FILTERSPEC_native
We already have `Interop.COMDLG_FILTERSPEC` struct. Can't we reuse it? We can make it blittable by changing `string?` to `char*`

2021-09-07 23:46 UTC, RussKie reviewed
There are few other comments that are outstanding

2021-09-07 23:46 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                    throw new ArgumentNullException(nameof(wrappedInstance));
```suggestion
                    ArgumentNullException.ThrowIfNull(argument: null, nameof(wrappedInstance));
```

2021-09-07 23:46 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                IntPtr local_0;
I think @JeremyKuhne meant naming args as per https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshal.queryinterface
![image](https://user-images.githubusercontent.com/4403806/132423898-4b59744d-e9da-45a9-b754-67bdd80f3771.png)

2021-09-14 03:23 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemWrapper.cs
> +                    throw new ArgumentNullException(nameof(wrappedInstance));
`ArgumentNullException.ThrowIfNull`

2021-10-04 18:59 UTC, dreddy-work commented
Pinging @kant2002 ,  to get this closure.

2021-12-02 13:33 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                IntPtr local_0;
I take a bit of liberty and name local variables like that `ppv_local`, basically just append `_local` to the name of the parameters. I take this to preserve original names in the interface declaration, and very often I need two variables with same name. Hope this will works.

2021-12-02 13:55 UTC, kant2002 commented
@dreddy-work I deeply apologize for dragging this so long. I finally allocate time to put a closure on this. Please expect reasonable response times from now on.

2021-12-29 05:50 UTC, kant2002 commented
@RussKie now it's my trun ask for time slot from some team member.

2021-12-30 22:46 UTC, RussKie commented
Apologies for the delay. I'm on a vacation, will be back in a few weeks.
________________________________
From: Andrii Kurdiumov ***@***.***>
Sent: Wednesday, 29 December 2021 4:50 PM
To: dotnet/winforms ***@***.***>
Cc: Igor Velikorossov ***@***.***>; Mention ***@***.***>
Subject: Re: [dotnet/winforms] Add support for IFileOpenDialog (#5319)


@RussKie<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRussKie&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7C29efdddbdf4b4536df6108d9ca8f2b27%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763538538426410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MOqScyLc%2BWtaNtgmFSPccJztGbBh4JupG6BSJYJNzFY%3D&reserved=0> now it's my trun ask for time slot from some team member.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fpull%2F5319%23issuecomment-1002408367&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7C29efdddbdf4b4536df6108d9ca8f2b27%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763538538426410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JhAuPvNGeyZKwEFCg6Xtgc3pGDlx7fBRgjfSHdXz9xw%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABBTEXVIHCY2M2DUZPUA74TUTKOTVANCNFSM5A2AE7HQ&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7C29efdddbdf4b4536df6108d9ca8f2b27%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637763538538426410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FgpflC2%2Bg8JNzffn3yq4xy%2FY6NB9ShMjlXRKN4ZKRNQ%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-01-14 20:32 UTC, JeremyKuhne requested changes
Did another pass. Error checking in particular needs to be corrected. I'll look again once there is another update.

2022-01-14 20:32 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
> +                        extension.pszSpec = Marshal.StringToCoTaskMemUni(tokens[i]);// This may be a semicolon delimited list of extensions (that's ok)
I really don't like adding new native memory allocations, but we don't have a simple way for you to pin this at the moment. Doing something like `filter = filter.Replace('|', '\0');` , pinning it, and looping through with `filter.IndexOf()` to get your start pointers to populate an array of pointers would make this much less heavy and less risky for leaks. It would also need to be moved inline to be able to pin.

Something roughly like:

``` C#
List<int> indices = new(); 
filter = filter.Replace('|', '\0');
int index = 0;
while ((index = filter.IndexOf(`\0`, index)) > 0)
{
    indices.Add(index);
}

Span<IntPtr> strings = stackalloc IntPtr[indices.Count];

fixed (char* f = filter)
{
    // Populate strings from indices and pass &strings to SetFileTypes
}
```

You don't have to do this in this change, but we should create a follow-up issue to get rid of the StringToCoTaskMemUni();

2022-01-15 04:35 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
> +        public static Guid IShellItem = new Guid(0x43826D1E, 0xE718, 0x42EE, 0xBC, 0x55, 0xA1, 0xE2, 0x61, 0xC3, 0x7B, 0xFE);
Aah, that's me deliberately do that during rebase. My bad.

2022-01-15 04:40 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
> +        public static Guid IShellItem = new Guid(0x43826D1E, 0xE718, 0x42EE, 0xBC, 0x55, 0xA1, 0xE2, 0x61, 0xC3, 0x7B, 0xFE);
Please keep definitions in alphabetical order.

2022-01-15 04:46 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
>              COMDLG_FILTERSPEC[] filterItems = FilterItems;
Gladly.

2022-01-15 04:57 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
> +                        extension.pszSpec = Marshal.StringToCoTaskMemUni(tokens[i]);// This may be a semicolon delimited list of extensions (that's ok)
I probably can handle that, and it does make sense to me why you don't want to have native memory allocations. Also willing to do that in subsequent PR.

2022-01-17 05:16 UTC, kant2002 commented
@JeremyKuhne I think I address all your remarks.

2022-01-18 04:24 UTC, RussKie reviewed
Few comments.

2022-01-18 04:24 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                }
We seem to be doing this in several places. Should we create a helper method? E.g., something like:
```cs
        private IntPtr GetComPoninter<T>(T obj, Guid iid) where T : class
        {
            IntPtr pobj_local;
            if (obj is null)
            {
                pobj_local = IntPtr.Zero;
            }
            else
            {
                IntPtr pUnk_local = WinFormsComWrappers.Instance.GetOrCreateComInterfaceForObject(obj, CreateComInterfaceFlags.None);
                Guid local_IID = iid;
                result = (HRESULT)Marshal.QueryInterface(pUnk_local, ref local_IID, out pobj_local);
                Marshal.Release(pUnk_local);

                if (result.Failed())
                {
                    Marshal.ThrowExceptionForHR((int)result);
                }
            }

            return pobj_local;
        }
```

2022-01-18 04:24 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +            void Shell32.IFileOpenDialog.GetFileName(out string pszName)
I think this should be 
```suggestion
            void Shell32.IFileOpenDialog.GetFileName(out string? pszName)
```

2022-01-18 04:24 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                pszName = Marshal.PtrToStringUni(pszName_local)!;
The [remarks in the docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostringuni?view=net-6.0#system-runtime-interopservices-marshal-ptrtostringuni(system-intptr)) state that we need to free the original string:
![image](https://user-images.githubusercontent.com/4403806/149869895-0d551c12-37da-4b32-89ee-7bee0bfcc2ab.png)

2022-01-18 04:25 UTC, RussKie commented
@AaronRobinsonMSFT do you think you can review this?

2022-01-18 13:27 UTC, AaronRobinsonMSFT reviewed
This LGTM. Hopefully, the COM interop source generator will generate largely the same code. /cc @jkoritzinsky @elinor-fung

2022-01-18 13:27 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +                pobj_local = IntPtr.Zero;
I would return here and remove the need for nested `else` clause.

2022-01-18 19:05 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                pszName = Marshal.PtrToStringUni(pszName_local)!;
To be super clear, only "as appropriate". In this case, it is appropriate: [`IFileDialog::GetFileName`](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifiledialog-getfilename)  :)

2022-01-18 19:08 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
> +        internal static Guid IShellItem = new Guid(0x43826D1E, 0xE718, 0x42EE, 0xBC, 0x55, 0xA1, 0xE2, 0x61, 0xC3, 0x7B, 0xFE);
You still haven't changed these to properties as requested.

2022-01-18 19:15 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                pszName = Marshal.PtrToStringUni(pszName_local)!;
Hey. I thought that I do stupid mistake, but seems to be I fix that one before you wrote you comment. Still left "properties" remark, but this one probably ok. ;)

2022-01-18 19:52 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
> +        internal static Guid IShellItem = new Guid(0x43826D1E, 0xE718, 0x42EE, 0xBC, 0x55, 0xA1, 0xE2, 0x61, 0xC3, 0x7B, 0xFE);
I change only these who I add in this PR, should I modify others too?

2022-01-19 01:59 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
> +        internal static Guid IShellItem = new Guid(0x43826D1E, 0xE718, 0x42EE, 0xBC, 0x55, 0xA1, 0xE2, 0x61, 0xC3, 0x7B, 0xFE);
If you could apply the change to all of these - it'd be great.

2022-01-19 02:15 UTC, RussKie reviewed
👍

2022-01-19 02:15 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
>              throw new NotImplementedException();
Would we not want to call `Marshal.Release(externalComObject);` before throwing the exception?
Should we do this:
```cs
try
{
    // if (..) return ...
}
finally 
{
    Marshal.Release(externalComObject);
}

throw new NotImplementedException();
```

2022-01-19 02:15 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                pszName = Marshal.PtrToStringUni(pszName_local)!;
To confirm, even when the call fails we still get a non-null `pszName_local` buffer and we never return `pszName` as null?

2022-01-19 04:03 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
>              throw new NotImplementedException();
I think we should not do that. If we reach this path, that's mean something within WinForms pass to internal ComWrappers borked value. That should not happens. That means serious bug for me which should be fixed.

2022-01-19 04:08 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
>              throw new NotImplementedException();
Indeed we have a bug, we thrown and the app crashed... But would we not leak the COM object in this situation? I'm genuinely curious.

2022-01-19 05:06 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
>              throw new NotImplementedException();
We can leak COM object if it is created out-of-process. That may happens only if we work with WebBrowser or DataObject probably. All of them are problematic even for this approach and better discuss that problem when we implement this parts.

What if COM object would be passed by the user(this is how I think we end-up in this hypotetical scenario) if we release his object during exception(our bug) he maybe unhappy since that's leave him without workaround. I'm more in the camp let it fail since that means major screwup on our side.

2022-01-19 05:07 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
> +        internal static Guid IShellItem = new Guid(0x43826D1E, 0xE718, 0x42EE, 0xBC, 0x55, 0xA1, 0xE2, 0x61, 0xC3, 0x7B, 0xFE);
Only IAccessible left,  because it is used for `ref Guid` parameters. I think that maybe changed in follow-up PR if needed.

2022-01-19 05:10 UTC, kant2002 commented
> To confirm, even when the call fails we still get a non-null pszName_local buffer and we never return pszName as null?

@RussKie now yes.

2022-01-20 23:19 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
>          public static Guid IAccessible = new Guid(0x618736E0, 0x3C3D, 0x11CF, 0x81, 0x0C, 0x00, 0xAA, 0x00, 0x38, 0x9B, 0x71);
We should have a follow up issue/PR to get this one fixed. Part of the idea here with using static properties is to avoid accidentally modifying these values. :)

2022-01-20 23:20 UTC, JeremyKuhne approved these changes
Looks good. If the dialog hasn't been manually tested it should be before checking in.

2022-01-21 08:24 UTC, kant2002 commented
@JeremyKuhne Take a look at ac142c4 that's important point to consider. Also because `System.Windows.Forms.IntegrationTests` project seems to be did not run, it fails to catch crash. I do know what to do, and will fix it in subsequent commit. Please do not merge meanwhile.

2022-01-21 17:47 UTC, kant2002 commented
@JeremyKuhne @RussKie in last commit I add unwrapping RCW and that make things working. I validate changes manually by running `WinformsControlsTest` and opening dialog, made a selection and changing properties a bit. I cannot say that I test exhausively. I would like to add test coverage in form of E2E tests, so I file #6532 . In additional to other small work-items in this PR, I think nothing blocks this from landing (unless you raise concerns over last 2 commits)

2022-01-24 00:25 UTC, RussKie commented
/azp run

2022-01-25 16:33 UTC, kant2002 commented
@RussKie anything else left?

2022-01-25 21:04 UTC, RussKie commented
I'm OOF. @dreddy-work @JeremyKuhne please merge , if you have no further feedback. Thanks.

2022-01-26 19:10 UTC, JeremyKuhne approved these changes

2022-01-26 19:12 UTC, merged

2022-01-26 19:23 UTC, kant2002 commented
Ooh!! Yeah!!! Thanks you guys a lot!!!