cleanup in MonthCalendar
dotnet/winforms pull request #5561
Opened 2021-08-27 00:55 UTC by Tanya-Solyanik

Initially this ws based on @JeremyKuhne suggestion made in https://github.com/dotnet/winforms/pull/5201#issuecomment-885210059
> I wouldn't mess with the collections without a clear, measured win. This class originally was using `ArrayList`. `List<DateTime>` is significantly more performant, so we're already way better. Generally speaking the class is way more performant than it used to be as the interop has been cleaned up. The comment in the code should probably be removed.
> 
> There are other things that could be done here if you want to make an improvement:
> 
> * Setting `BoldedDates` should use `AddRange`.
> * WmDateBold could be significantly faster.
>   
>   * There is no need to create a wrapper DateBoldEventArgs class.
>   * BoldDates could also write directly into the buffer being used (don't allocate arrays you don't need).
>   * The buffer has no need to use Marshal.
>     
>     * Can use a pinning `GCHandle` kept in the class with a normal `int[]` array.
>     * Better yet, allocate a pinned array up front using [`GC.AllocateArray`](https://docs.microsoft.com/en-us/dotnet/api/system.gc.allocatearray?view=net-5.0) and just use `fixed` to get the address.

However, it is not needed to allocate the buffer in winforms becasue it is already allocated in the comctls calendar control code before this notification is called.
https://docs.microsoft.com/en-us/cpp/mfc/setting-the-day-state-of-a-month-calendar-control?view=msvc-160

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/5561)

2021-08-31 03:28 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                _pinnedBuffer = GC.AllocateArray<int>(actualSize, pinned: true);
I double checked both implementations and they do allocate an array. It isn't stated on docs, but appears to be written up in the header.

@Tanya-Solyanik is correct, if we were passing back a pointer to a buffer it would have to be pinned as that is a return value, we're not calling out to native code. And the new pinned heap in specifically designed for this scenario, when you have to pin for something longer than the duration of the current method it is the best choice.

2021-08-31 03:34 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                _pinnedBuffer = GC.AllocateArray<int>(actualSize, pinned: true);
For the duration of the call, not for the lifetime of the instance. 👍

2021-08-31 03:35 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            int[] boldDates = CollectBoldDates(monthCount);
Better choice here is to just pass a `Span<int>` around the output `prgDayState` to `CollectBoldDates` and have it fill it in directly.

2021-08-31 03:45 UTC, RussKie approved these changes

2021-08-31 17:53 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +                _pinnedBuffer = GC.AllocateArray<int>(actualSize, pinned: true);
@RussKie To be absolutely clear, if someone calls you and you pass back a buffer that needs to be pinned, the only practical thing to do is pin it for the lifetime of your instance. You can't unpin it before you return from your invocation, of course. You could unpin on the next Windows message I suppose, but that adds complexity and is a risk that isn't worth taking for such a small amount of memory. We have to assume that the native implementation here could change so that additional messages get sent before it finishes copying out of the buffer we pass back.

2021-08-31 18:54 UTC, JeremyKuhne requested changes
Please see the comment regarding using Span<int>.

2021-08-31 22:45 UTC, JeremyKuhne approved these changes
Nice!

2021-08-31 22:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            boldDates.Clear();
nit: It might be clearer to have the .Clear() in the method so if it ever becomes unnecessary it will be more obvious.

2021-08-31 22:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            boldDates.Clear();
Yeah, I first put it in the method, so that all "writing" is in one place, and then thought that allocation and initialization should go together. I guess your vote is a tie breaker.

2021-08-31 23:09 UTC, JeremyKuhne approved these changes

2021-09-01 00:01 UTC, merged

2021-09-01 08:29 UTC, vladimir-krestov reviewed
✔️