Issue 5670 tool strip buttons rendering tests
dotnet/winforms pull request #5700
Opened 2021-09-06 07:26 UTC by ArtemTatarinov

Fixes #5670

## Proposed changes

- Added rendering tests for ToolStrip buttons

## Customer Impact

- No

## Regression? 

- No

## Risk

- Minimal

## Test environment(s) 
Microsoft Windows [Version 10.0.19043.1165]
.NET SDK 6.0.100-rc.1.21416.15

2021-09-07 12:57 UTC, RussKie requested changes
I'm struggling to reconcile the "fixes 5670" + the subject against the actual implementation. That is, changes under .\tests folder are expected, but changes under .\src folder are not.

2021-09-07 12:57 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
> +                    // If system in high contrast mode 'false' flag should be passed to render filled selected button background. This is in consistence with ToolStripProfessionalRenderer.
```suggestion
                    // If system in high contrast mode 'false' flag should be passed to render filled selected button background.
                    // This is in consistence with ToolStripProfessionalRenderer.
```

2021-09-07 12:57 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.Rendering.cs
> +            PaintEventArgs e = new(emf, bounds);
```suggestion
            using PaintEventArgs e = new(emf, bounds);
```
ditto below

2021-09-07 12:57 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.Rendering.cs
> +            var details = emf.RecordsToString();
This is not necessary in automated tests.
Ditto below

2021-09-07 12:57 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.Rendering.cs
> +    class ToolStripSystemHighContrastRenderer : ToolStripSystemRenderer
```suggestion
    private class ToolStripSystemHighContrastRenderer : ToolStripSystemRenderer
```

2021-09-07 12:57 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.Rendering.cs
> +        public void ToolStrip_Button_RendersTextCorrectly()
Tests that test `ToolStripButton` painting (as opposed to `ToolStrip` painting) should be located in `ToolStripButtonTests.Rendering` as these tests test the button's implementations and not the toolstip.

2021-09-08 16:25 UTC, dreddy-work reviewed
LGTM.

2021-09-08 16:25 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.Rendering.cs
> +
nit: extra lines not consistent with other tests.

2021-09-08 23:31 UTC, RussKie approved these changes
👍

2021-09-08 23:42 UTC, merged