Fixing EditTextBox AO position in the PropertyGrid tree
dotnet/winforms pull request #5724
Opened 2021-09-09 08:42 UTC by vladimir-krestov

Fixes #5656

The bug repro-steps:
- Create a `PropertyGrid` with `Form` as `SelectedObject`
- Run the app - don't click on the `PropertyGridView`
- Check the Text entry using Inspect - there will be an edit accessible object as a child (incorrect)
- Click any entry (thereby create the edit control) - after that everything is good, the edit acc obj has correct position in the tree and correct properties values.

The fix doesn't allow to create and put EditAccessibleObject to the accessibility tree, if the TextBox control is not created,
because otherwise EditAccessibleObject doesn't get correct native properties, and a user see some AO of not created control.

PropertyGridView EditTextBox creates on the first click on the GridView and if there is a selected GridEntry.

I tried just to implement correct values of the necessary accessibility properties (`Bounds`, `Role`, `State`), but the implementation looks horrible and unsafe. Also, there is no way to get a correct Bounds without a TextBox `Handle`, because we have to send Win messages, that require the `Handle` (`RectangleToScreen` method). And this implementation just fixes symptoms of the bug. So not using AO for not created Control is better, I guess.

## Proposed changes

- Return null in FragmentNavigate of an entry if a entry TextBox is not created thereby remove it from the accessibility tree.
You can try to select some entry, but check another one with Inspect/AI. You will see, that only the selected entry has the edit sub-item. The rest entries don't have this child in the accessibility tree. And if a PropertyGridView doesn't have a selected entry, there should not be a edit child for any entry (because this edit text box is not created yet). 

## Customer Impact

- A user doesn't see an edit accessible object for not created control.

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before

- There is an edit accessible object of a not created control, so its properties values are incorrect:
![image](https://user-images.githubusercontent.com/49272759/132652782-705800c8-9ea8-4b19-9b3a-cb48e8a54910.png)

### After

- There is no an edit accessible object, because its control is not created:
![image](https://user-images.githubusercontent.com/49272759/132651737-20afa679-0703-48d6-bd1d-5f5ce8f4cb3c.png)

- There is an edit accessible object with correct accessible properties values after click on the entry
(thereby creating the edit control):
![image](https://user-images.githubusercontent.com/49272759/132652126-58809396-07cf-463b-99ee-5183a218874f.png)

## Test methodology 

- CTI
- Manual testing

## Accessibility testing  
- Using Inspect and Accessibility Insights

## Test environment(s) 

- .NET 6.0-rc2
- Windows 10

2021-09-09 17:35 UTC, dreddy-work commented
tests need attention.

2021-09-09 17:36 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
> +                    if (propertyGridView.IsEditTextBoxCreated)
why is this check missing at line 203?

2021-09-09 17:39 UTC, dreddy-work requested changes
Porting PR  is out of synch with this. Please check or explain the difference.

2021-09-09 20:07 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
> +                    if (propertyGridView.IsEditTextBoxCreated)
Sorry, I forgot to add this. I have added it for now.

2021-09-09 20:17 UTC, vladimir-krestov commented
@dreddy-work, the PRs are synced, please check.

2021-09-10 01:18 UTC, dreddy-work commented
IF same change is validated with 6.0 bits, I do not see a need to do a PR level validation in main. That can be done as part of regular testing.

2021-09-10 01:18 UTC, dreddy-work approved these changes
LGTM.

2021-09-10 17:34 UTC, merged