Move duplicate logic of "GetPropertyValue" method to base classes
dotnet/winforms pull request #5745
Opened 2021-09-13 09:39 UTC by ArtemTatarinov

Fixes #5494

## Proposed changes

Moving switch cases with these properties to base classes with the same logic.

Moved to AccessibleObject:
- RuntimeIdPropertyId
- NamePropertyId
- IsOffscreenPropertyId
- IsLegacyIAccessiblePatternAvailablePropertyId 
- HelpTextPropertyId 
 
Moved to ControlAccessibleObject:
- NativeWindowHandlePropertyId
- IsEnabledPropertyId

## Customer Impact

- No

## Regression? 

- No

## Risk

- Minimal

## Test methodology 

- Manually checking
- Unit tests

## Test environment(s) 
Microsoft Windows [Version 10.0.19043.1165]
.NET SDK 7.0.0-alpha.1.21461.7

2021-09-13 17:20 UTC, dreddy-work commented
@ArtemTatarinov. please take a look at test failure. Impact of this is broad. Can you put some test instructions for CTI team to validate this change thoroughly before we do a final review on this?

2021-09-14 03:17 UTC, RussKie commented
```
##[error]src\System.Windows.Forms\src\System\Windows\Forms\MenuStrip.MenuStripAccessibleObject.cs(5,1): error IDE0005: (NETCORE_ENGINEERING_TELEMETRY=Build) Using directive is unnecessary.
```

2021-09-14 21:31 UTC, dreddy-work commented
@ArtemTatarinov, please share instructions to exercise these code paths specifically.

2021-09-16 00:26 UTC, RussKie commented
Have the tests been written _before_ the changes were made? If not, I suggest to reshuffle commits to add tests first, make sure they are green, then apply changes and confirm the tests are still green.

2021-09-16 11:49 UTC, ArtemTatarinov commented
> Have the tests been written _before_ the changes were made? If not, I suggest to reshuffle commits to add tests first, make sure they are green, then apply changes and confirm the tests are still green.

That's great idea, thank you very much! Did it, ran tests before and after the fix, both times they're green.

2021-09-17 17:46 UTC, dreddy-work commented
@Olina-Zhang for testing.

2021-10-01 17:14 UTC, dreddy-work requested changes
Holding until we get chance to validate against 7.0 builds on this.

2021-10-12 07:33 UTC, Olina-Zhang commented
@dreddy-work we tested the private 6.0 binaries based on 6.0, and confirmed regression issue we found is expected. But the private binaries for 7.0 is broken again based on .Net 7.0 SDK, need to wait until it'll be repaired.

2021-11-01 16:57 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
> +                UiaCore.UIA.HelpTextPropertyId => Help ?? string.Empty,
`Help `is a nullable string. why are we passing string.Empty? and if we do, why did we make `Help `nullable string?

2021-11-01 17:00 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxItemAccessibleObject.cs
>                      UiaCore.UIA.IsValuePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.ValuePatternId),
Why remaining patterns not moved to base? I see `IsPatternSupported `is virtual and should be able to move them.

2021-11-01 17:02 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxItemAccessibleObject.cs
>                      UiaCore.UIA.IsValuePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.ValuePatternId),
Good point, `IsPatternSupported` will work for inherited objects.
@ArtemTatarinov, please move the rest

2021-11-01 17:03 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs
>                          return BoundingRectangle;
From overview some of these properties ( ex: `BoundingRectangle `) are also virtual and candidates to move to base class. Are you planning a second PR here?

2021-11-01 17:07 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
> +                UiaCore.UIA.HelpTextPropertyId => Help ?? string.Empty,
I would move it and make not-nullable as another PR. Because we need to think, what we should to do with `DefaultAction`, `Description`, `Help`, `KeyboardShortcut`, `Name`, `Value`, etc. Maybe we will make them non-nullable. So I would keep it as is until a new fix. @dreddy-work, do you agree?

2021-11-01 17:07 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
>                          return KeyboardShortcut ?? string.Empty;
Same for other nullable properties. If we always want to pass a empty string, then define the property as such.

2021-11-01 17:09 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
> +                UiaCore.UIA.HelpTextPropertyId => Help ?? string.Empty,
I am fine with a new PR on that but please open a tracking issues and link it to this comment so that people reviewing will know that this is coming.

2021-11-01 17:10 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
> +                UiaCore.UIA.HelpTextPropertyId => Help ?? string.Empty,
@ArtemTatarinov, please do it

2021-11-01 17:19 UTC, dreddy-work reviewed
RLGTM.

2021-11-02 14:42 UTC, ArtemTatarinov commented on src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
> +                UiaCore.UIA.HelpTextPropertyId => Help ?? string.Empty,
Created an issue: https://github.com/dotnet/winforms/issues/6103

2021-11-02 14:46 UTC, ArtemTatarinov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs
>                          return BoundingRectangle;
Yes, I guess it's better to make another PR with other properties (except for the *PatternAvailablePropertyId), it requires some thinking and discussion, and also this PR already has a lot of changes and more to come with moving *PatternAvailablePropertyId properties to the base `AccessibleObject` class.

2021-11-09 11:44 UTC, ArtemTatarinov commented
Hi, @merriemcgaw, @dreddy-work, @Tanya-Solyanik! I got a question about moving some property patterns. The `GetPropertyValue` method for some properties had returned `false` before cases of those properties were moved to the base `AccessibleObject` class, now it returns `true`.

This is happening due to the following reason: some classes - `ComboBoxAccessibleObject`, `DataGridViewCellAccessibleObject`, `LinkAccessibleObject`, `ListBoxItemAccessibleObject`, `ScrollBarAccessibleObject`, `TrackBarAccessibleObject`, `UpDownButtonsAccessibleObject` - don't have `IsLegacyIAccessiblePatternAvailablePropertyId` cases at the `GetPropertyValue` method. `DataGridViewCellAccessibleObject` also doesn't have `IsValuePatternAvailablePropertyId` case (maybe even more classes have the same situation). Yet they (or their parent class `ControlAccessibleObject`) do have the `IsPatternSupported` method where those patterns are supported.

For example, lets take **DataGridViewCellAccessibleObject**.
**GetPropertyValue** method (no `IsLegacyIAccessiblePatternAvailablePropertyId` or `IsValuePatternAvailablePropertyId` cases):
![image](https://user-images.githubusercontent.com/87859299/140915852-824ceacc-d51c-44ee-9174-e38f1ce5a98c.png)

**IsPatternSupported** method (both patterns are supported):
![image](https://user-images.githubusercontent.com/87859299/140918193-6a22f7dc-6a8e-450c-a999-fad428a747fc.png)

So, if we pass `IsLegacyIAccessiblePatternAvailablePropertyId` argument to the `GetPropertyValue` method before the fix, we'll get `false` value, because  `IsPatternSupported` won't be called at all, because there's no such case at the `GetPropertyValue` method. After the fix the `IsPatternSupported` method will be called from the `GetPropertyValue` method at the `AccessibleObject` class and `GetPropertyValue` will return `true`.

My opinion is that `GetPropertyValue` behavior should be consistent with the `IsPatternSupported` method and we should keep new `true` values and consider them expected. Also, it makes sense because all these classes are supporting UIA and the `IsLegacyIAccessiblePatternAvailableProperty` in fact. What do you think about it?

2021-11-10 18:37 UTC, dreddy-work commented
Lets chat about this in next meeting briefly.

2021-11-17 21:23 UTC, Tanya-Solyanik commented
>My opinion is that GetPropertyValue behavior should be consistent with the IsPatternSupported method and we should keep new true values and consider them expected. 

This makes sense to me. I believe you are uncovering existing bugs, and this was exactly the goal of this change.

2021-11-25 08:25 UTC, ArtemTatarinov commented
CTI team has tested the latest changes with all Pattern Available Properties moved to the base class, found no issues.

2021-11-26 09:11 UTC, ArtemTatarinov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs
>                          return BoundingRectangle;
Created an issue: https://github.com/dotnet/winforms/issues/6236

2021-12-03 05:00 UTC, Tanya-Solyanik approved these changes

2021-12-03 05:02 UTC, Tanya-Solyanik commented
@vladimir-krestov - Please take another look, it seems that your comments are resolved.
@dreddy-work  - putting this PR on your radar for when you are back.

2021-12-06 08:39 UTC, vladimir-krestov reviewed
Awesome work!
Main point - `InvokePattern`

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxItemAccessibleObject.cs
>                      UiaCore.UIA.IsInvokePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.InvokePatternId),
Check if we can move `IsInvokePatternAvailablePropertyId` case to the base class as well.
If it's possible, please check all patterns and move them into the base class. But, actually, it's a big task too, so I would do it as a next PR.

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
>                          return true;
I would move it to `IsPatternSupported` as well. But as a part of the next PR, as I mentioned above.

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs
> +                        UiaCore.UIA.IsInvokePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.InvokePatternId),
I would move it to the base class, as the rest

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
>                      UiaCore.UIA.IsInvokePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.InvokePatternId),
ditto

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.NumericUpDownAccessibleObject.cs
>                      case UiaCore.UIA.LegacyIAccessibleStatePropertyId:
Check if we can move:
- `LegacyIAccessibleStatePropertyId`
- `LegacyIAccessibleValuePropertyId`
- `LegacyIAccessibleRolePropertyId` and etc. 
 to the base class. Do it as a separate task and make changes as a separate PR.

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObject.cs
>                  UiaCore.UIA.IsLegacyIAccessiblePatternAvailablePropertyId => true,
Use `IsPatternSupported`

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
>                      UiaCore.UIA.IsGridPatternAvailablePropertyId => true,
Use `IsPatternSupported`

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarAccessibleObject.cs
>                      UiaCore.UIA.IsOffscreenPropertyId => (State & AccessibleStates.Offscreen) == AccessibleStates.Offscreen,
You can delete it as well

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabControlAccessibleObject.cs
>                      UIA.IsOffscreenPropertyId => (State & AccessibleStates.Offscreen) == AccessibleStates.Offscreen,
ditto

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
>                      UiaCore.UIA.IsInvokePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.InvokePatternId),
ditto

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabPageAccessibleObject.cs
>                      UiaCore.UIA.IsOffscreenPropertyId => (State & AccessibleStates.Offscreen) == AccessibleStates.Offscreen,
ditto

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
>                          return (object)IsPatternSupported(UiaCore.UIA.ExpandCollapsePatternId);
I would remove it as well

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
>                      UiaCore.UIA.IsOffscreenPropertyId => (State & AccessibleStates.Offscreen) == AccessibleStates.Offscreen,
ditto

2021-12-06 08:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
> +                        UiaCore.UIA.IsInvokePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.InvokePatternId),
ditto

2021-12-07 00:26 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxItemAccessibleObject.cs
>                      UiaCore.UIA.IsInvokePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.InvokePatternId),
Yes, please create new task.

2021-12-09 05:42 UTC, ArtemTatarinov commented
My today's push includes only the most trivial cases of the `IsOffscreenPropertyId` property (when the code at the child and the base class is identical, so no additional testing is needed). For the rest of the review points, I've created a new issue #6324, When this PR will be reviewed by @dreddy-work and merged, I will create a new PR with the rest of the cases.

2021-12-09 06:53 UTC, vladimir-krestov approved these changes
Approved this PR ✔️ and waiting for the next one.

2021-12-09 08:04 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
>                                                          || (State & AccessibleStates.Offscreen) == AccessibleStates.Offscreen,
The second condition is base,GetPrpertyValue(UiaCore.UIA.IsOffscreenPropertyId)

2021-12-09 18:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs
> +                        UiaCore.UIA.IsInvokePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.InvokePatternId),
Why is this line - 
>UiaCore.UIA.IsInvokePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.InvokePatternId),

not deferred to the base class?

2021-12-10 06:20 UTC, ArtemTatarinov commented on src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs
> +                        UiaCore.UIA.IsInvokePatternAvailablePropertyId => IsPatternSupported(UiaCore.UIA.InvokePatternId),
The base class is using a large switch to check if the `Invoke` pattern is supported. To refactor the children classes we need to check every case at the child class to make sure the logic of its `IsPatternSupported` method is the same as in the base class, and then test all of these cases. As I discovered from this discussion https://github.com/dotnet/winforms/pull/5745#discussion_r762779682 we decided to make it in a new PR to reduce the number of code changes in this PR and split testing.

![image](https://user-images.githubusercontent.com/87859299/145525509-4a132b3a-e8b1-4843-9549-9ed431534e2a.png)

2021-12-11 01:53 UTC, Tanya-Solyanik approved these changes

2021-12-14 19:55 UTC, dreddy-work approved these changes
LGTM.

2021-12-14 19:56 UTC, merged