Updating NativeHost.PlatformToolset version
dotnet/winforms pull request #5797
Opened 2021-09-17 07:29 UTC by SergeySmirnov-Akvelon

## Proposed changes
- Updated NativeHost.PlatformToolset version

## Customer Impact
-  No

## Regression? 
- No

## Risk
- Minimal

## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.388]
- .NET Core SDK 6.0.100-rc.1.21430.12

2021-09-17 17:44 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
Isn't this restrict VS to VS 2022? can we still use older VS versions here?

2021-09-20 04:14 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
.NET 6.0 is only supported in VS 2022

2021-09-20 04:16 UTC, RussKie requested changes
Docs must also be updated to reflect all necessary workloads and tools.
E.g. https://github.com/dotnet/winforms/blob/main/docs/developer-guide.md, but mya be other ones as well.

2021-09-20 08:26 UTC, SergeySmirnov-Akvelon commented
@RussKie. Added necessary changes to the documentation

2021-09-20 08:27 UTC, RussKie approved these changes

2021-09-20 16:43 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
Are we saying community can't build our repo without VS 2022? @SergeySmirnov-Akvelon, Did you try building repo with this change but no VS 2022?

2021-09-20 23:59 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
That is correct, and it has been the case for some months.

2021-09-21 16:50 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
> +    <PlatformToolset>v143</PlatformToolset>
Will take this discussion offline.

2021-09-21 16:51 UTC, dreddy-work approved these changes

2021-09-21 16:56 UTC, merged