Fixed getting an month index of a bolded date of a MonthCalendar
dotnet/winforms pull request #5869
Opened 2021-09-27 08:16 UTC by vladimir-krestov

Fixes #5853

The regression came from #4317, the previous implementation didn't not take into account gray dates of a display range. So the max index was 11, but in real, 13 is the max month index (including the first and last gray months).

## Proposed changes

- Rework getting current month index when setting a new bolded date

## Customer Impact

- A user can bold a MonthCalendar date correctly

## Regression? 

- Yes (from #4317)

## Risk

- Minimal

## Screenshots (TODO)

### Before

### After

## Test methodology 

- CTI
- Unit tests
- Manual testing

## Test environment(s) 

- .NET 7.0-alpha
- Windows 10

2021-09-27 08:18 UTC, vladimir-krestov commented
In plans:
- Add gifs to the description
- Add unit tests
- Ask CTI to test the fix

2021-09-27 13:35 UTC, RussKie commented
LGTM

2021-09-27 13:43 UTC, kirsan31 commented
Yea, I think allis ok too.

2021-09-28 01:03 UTC, dreddy-work requested changes
Waiting on unit tests.

2021-09-28 09:27 UTC, vladimir-krestov commented
@dreddy-work, I have implemented a unit test. There is no way to check something because we don't keep anything in `SetMonthViewBoldedDates` method. So I see the following way - handle `MCM_SETDAYSTATE` message sending. But I'm not sure, that it works correctly. Could you please check the approach?

2021-09-28 10:26 UTC, vladimir-krestov commented
@RussKie, could you please say too, why does the test not work?

2021-09-29 01:18 UTC, RussKie commented
Surprisingly some pipelines succeeded whilst other failed with:
```
    System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_UpdateBoldedDates_SetCorrectBoldedDate_ForLastMonth(currentDate: 2021-08-31T00:00:00.0000000) [FAIL]
      Assert.Equal() Failure
      Expected: 1073741824
      Actual:   0
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs(4215,0): at System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_UpdateBoldedDates_SetCorrectBoldedDate_ForLastMonth(DateTime currentDate)
```

To make the code testable perhaps split `SetMonthViewBoldedDates` into two - one that performs all calculations and the other that takes the array and performs the interop call.

2021-09-29 07:29 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            int monthsCount = (displayRange.End.Year - displayRange.Start.Year) * MonthsInYear + displayRange.End.Month - displayRange.Start.Month + 1;
nit: store `displayRange.End` and `Start` in local variables

2021-09-29 12:54 UTC, vladimir-krestov commented
@RussKie, we can't split `SetMonthViewBoldedDates` into two, because:
- We should not change a functional code for the sake of tests
- We can't create ` private Span<uint> GetMonthViewBoldedDates()` method and return `Span<uint>` because of:
![image](https://user-images.githubusercontent.com/49272759/135264440-4914d3ae-8aee-4b63-a80b-d7c7b23a9f0a.png)
- We can't do like this with `private FillMonthDayStates` method, that runs through displayed bolded dates:
```cs
        private unsafe void SetMonthViewBoldedDates()
        {
            ...
            // Create a special collection for storage states of dates of some displayed month.
            // This collection will be send to Windows to update displayed dates states - bolded/unbolded.
            Span<uint> monthDayStates = stackalloc uint[monthsCount];
            // Run through all bolded dates and fill the Span collection
            FillMonthDayStates(monthDayStates, displayRange);

            fixed (uint* arr = monthDayStates)
            {
                // Update display dates states.
                // For more info see docs: https://docs.microsoft.com/windows/win32/controls/mcm-setdaystate
                User32.SendMessageW(Handle, (User32.WM)ComCtl32.MCM.SETDAYSTATE, (nint)(void*)monthsCount, (nint)arr);
            }
        }
```
because we will have the following in the unit test:
![image](https://user-images.githubusercontent.com/49272759/135270549-c80c4bfb-93e5-408b-bcc7-1e38e5da0ef5.png)


So one working way - use `internal FillMonthDayStates` method, that you can see in file changes of this PR.
@RussKie, @dreddy-work do we really can do like that  for the sake of a unit test?

2021-09-29 13:33 UTC, vladimir-krestov commented
@dreddy-work, should I prepare a port to .NET 6.0? If so, it is here: #5880. If no, please close it.

2021-09-29 13:36 UTC, kirsan31 commented
> should I prepare a port to .NET 6.0? If so, it is here: #5880. If no, please close it.

I very hope your should 🙏

2021-09-29 20:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            yield return new object[] { new DateTime(2021, 8, 31) }; // Make a gray date of the previous month bold
I don't think "grey" date is descriptive. Also it might be helpful to mention that this data set is designed for calendar control that displays certain set of months.

2021-09-29 20:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            using BoldedMonthCalendar calendar = new() { Size = new Size(1000, 1000), FirstDayOfWeek = Day.Sunday };
Does 1000x1000 display only 2 months?

2021-09-29 20:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            SelectionRange displayRange = calendar.GetDisplayRange(false);
nit: `visible: false`

2021-09-29 20:25 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            public IntPtr SetDayStatePtr { get; set; }
I did not see where this property is used...

2021-09-29 20:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            int currentMonthIndex = (currentDate.Year - displayRange.Start.Year) * MonthsInYear + currentDate.Month - displayRange.Start.Month;
This logic could be factored out into a local function.

2021-09-29 22:46 UTC, dreddy-work commented
> @dreddy-work, should I prepare a port to .NET 6.0? If so, it is here: #5880. If no, please close it.

I sent this out for approval. Given that this regression, we should be able to.

2021-09-29 22:52 UTC, dreddy-work commented
> @RussKie, @dreddy-work do we really can do like that for the sake of a unit test?

In general, restructuring code to be able to test it should be fine. I did this in HDPI (ex: WMDPICHANGED_BEFOREPARENT). I didn't fully get why the tests failed only on specific pipeline here but the change LGTM.

2021-09-29 23:24 UTC, RussKie commented
> * We should not change a functional code for the sake of tests

That's not entirely correct. We should not create test-only API or increase visibility of API for test-only purposes. However structuring the code in a way that it can be tested is completely acceptable.

> * We can't create ` private Span<uint> GetMonthViewBoldedDates()` method and return `Span<uint>` because of:

Then we can return a `uint[]`.

2021-10-01 09:36 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            int currentMonthIndex = (currentDate.Year - displayRange.Start.Year) * MonthsInYear + currentDate.Month - displayRange.Start.Month;
Added`GetMonthsCountOfRange` to get `monthsCount`. 
We are testing `currentMonthIndex` value correctness via testing `FillMonthDayStates`.

2021-10-01 09:37 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            public IntPtr SetDayStatePtr { get; set; }
It's not necessary after refactoring. So I just removed this type at all.

2021-10-01 09:38 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            using BoldedMonthCalendar calendar = new() { Size = new Size(1000, 1000), FirstDayOfWeek = Day.Sunday };
1000x1000 display 14 months (2 not fully visible)
But 600x600 is better - a calendar has 3 coluns and 4 rows of months

2021-10-01 09:39 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            int monthsCount = (displayRange.End.Year - displayRange.Start.Year) * MonthsInYear + displayRange.End.Month - displayRange.Start.Month + 1;
I guess, after refactoring it's not necessary anymore. We won't improve the performance, just add extra lines

2021-10-01 16:50 UTC, dreddy-work submitted a review, later dismissed
LGTM.

2021-10-02 00:34 UTC, Tanya-Solyanik reviewed
Looks good! Please make the helper static and I'll approve

2021-10-02 00:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +            => (displayRange.End.Year - displayRange.Start.Year) * MonthsInYear + displayRange.End.Month - displayRange.Start.Month + 1;
If the helper method calculated the diff, or index, then you can reuse it to calculate length by adding 1 to the last index.
```
        private static int GetIndexInMonths(int currentYear, int currentMonth, DateTime start)
            => (currentYear - start.Year) * MonthsInYear + currentMonth - start.Month;
```

2021-10-02 00:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
> +            // Set the first day of week to have a stable test case in different environments.
To make it really stable, you might want to control the locale. But this is out of scope for this fix.

2021-10-05 05:15 UTC, Tanya-Solyanik submitted a review, later dismissed
Looks good!

2021-10-05 10:26 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
> +        private static int GetMonthsCountOfRange(SelectionRange displayRange)
[nit] A-Z

2021-10-05 17:50 UTC, Tanya-Solyanik approved these changes

2021-10-05 18:09 UTC, merged