Fixing too large up and down arrows at ToolStripScrollButton
dotnet/winforms pull request #5976
Opened 2021-10-14 14:52 UTC by ArtemTatarinov

Fixes #5413

## Proposed changes

- Images for these buttons are created from the icons by the `GetBitmapFromIcon` method from the `DpiHelper` class. Icon `ScrollButtonUp.ico`, for example, has different sizes (16x16, 24x24, 32x32, etc). The icon constructor is choosing the size that is the closest match to the default size and that default size for 100% DPI scaling is 32x32 (returned by the `GetSystemMetrics` method with parameters `SM_CXICON` and `SM_CYICON`). That's the reason why up and down images are so big.
- Also, the icons are square, and up and down images have a lot of empty space above and below the arrow, like this:
![image](https://user-images.githubusercontent.com/87859299/137339356-90369168-e0d0-4f19-9a69-2238d743d214.png)
- We can change the way of creating these pictures by setting the default start size and scaling it for every DPI mode (see the screenshots below for different modes, starting size is 16x16), which will give us a smooth transition between different scaling factors.
- We can also set the default start size a bit larger to make the buttons bigger (proportionally at every DPI scaling mode):
Start sizes 20x20 & 24x24 (I haven't tried 28x28 and 30x30, because they're looking rather close to the button size of the original issue)
![startSize20](https://user-images.githubusercontent.com/87859299/137341046-2d1cefb1-4731-4833-ad0b-f94c07e412fb.png) ![startSize24](https://user-images.githubusercontent.com/87859299/137341080-75173813-1cf4-413d-8e6f-459e815aff22.png)

## Customer Impact

**Before the fix**
![beforeTheFix](https://user-images.githubusercontent.com/87859299/137338435-792463cc-f2fc-4f19-8a0d-00e5e6ea79f3.png)

**After the fix**
![afterTheFix](https://user-images.githubusercontent.com/87859299/137338461-3f7375db-bb99-4640-b9f3-340a88367b5f.png)

## Regression? 
- No

## Risk
- Minimal

## Test methodology 

- Manual testing (tested 100%, 125%, 150%, 175% scaling modes - see the screenshots above)
- CTI team

## Test environment(s) 
Microsoft Windows [Version 10.0.19043.1237]
.NET SDK 7.0.100-alpha.1.21512.13

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/5976)

2021-11-01 07:33 UTC, RussKie commented
/azp run

2021-11-01 09:15 UTC, ArtemTatarinov commented
Hi, @dreddy-work, @Tanya-Solyanik, could you please review it?

The CTI team has found two regression issues:
- Different sizes of up and down arrows at 100% DPI:
![image](https://user-images.githubusercontent.com/87859299/139632941-b3e3bb85-e7de-4a73-a5f1-fbbb0c6c2a27.png)
- Blurry `down` arrow side at 300% DPI:
![image](https://user-images.githubusercontent.com/87859299/139633026-c84ac3e5-b77c-49c0-b6b2-c1570af2e3e7.png)

I fixed them by doing the following:
- For some reason, `ScrollButtonDown.ico` has a set of sizes different from `ScrollButtonUp.ico`. 15x15, 23x23, etc at `down` arrow versus 16x16, 24x24, etc at `up` arrow. This was leading to different start sizes of pictures to be scaled and as a result arrow buttons looked different. I made sizes of `ScrollButtonDown.ico` similar to `ScrollButtonUp.ico` (took `up` arrow icon as a base and flipped vertically all the icons to make them `down` arrows). Now they have the same set of sizes. This icon is used only at the `ToolStripScrollButton` class, so no other controls should be affected
![image](https://user-images.githubusercontent.com/87859299/139633901-c255763b-02c3-4c11-837c-4c8ebcc15079.png)

- At 300% DPI starting icon to scale was too small and that was leading to a blurry image. Now we are using an icon constructor with a default icon and desired size as parameters, so the constructor would choose the size closest to the specified one from the icon set - but we can't stop at this step, because the icon may not have the exact size we needed, so we need to scale it too, but now from a larger picture as a starting point to avoid blurry images at the big scaling coefficients.
![image](https://user-images.githubusercontent.com/87859299/139634960-119d9d2d-a339-4180-a1b4-96f03c0552ef.png)

2021-11-01 09:48 UTC, Olina-Zhang commented
Tested the updated fixing with no new issue found, previous found regression issues are fixed.

2021-11-01 17:30 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
> +                // Icon constructor chooses the closest size to the specified one from the icon set - but we can't stop at this step,
Do we really need this else section? this is not limited to this Icon but any winforms Icon. Idea of carrying the different sizes in the Icon is to get closest matching size. We should eb consistent for all of our Icons. I agree that this will give more accurate size of bitmap but we do have sizes that satisfy 100, 150, 200, 250, 300 etc. If user DPI is not at this standard DPI settings,  they may see little size off relatively.  If this is something we should take, then it has to be for all winforms Icons and should be done at control level. @Tanya-Solyanik

2021-11-02 06:07 UTC, ArtemTatarinov commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
> +                // Icon constructor chooses the closest size to the specified one from the icon set - but we can't stop at this step,
Without an `else` section we would have the same picture sizes for different DPI modes. For example, 125% DPI gives us 20x20 scaled size, but the closest size in the icon file is 24x24. If we don't call the `CreateResizedBitmap` method, we'll get the picture with size 24x24. But for 150% DPI the scaled size itself is 24x24, so without the `CreateResizedBitmap` method, the picture will be still 24x24.  
![image](https://user-images.githubusercontent.com/87859299/139792977-c498f1c0-b574-486b-9863-f54bfae83fdb.png)

2021-11-02 09:10 UTC, vladimir-krestov approved these changes
LGTM ✔️

2021-11-02 17:08 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
> +                // Icon constructor chooses the closest size to the specified one from the icon set - but we can't stop at this step,
Right. Our current scaling on Icons do not differentiate between 126% and 150%. We try to round it off to nearest standard DPI size in these cases. Concern here is, this is not limited to Toolstrip* icons but all winforms icons. If we want to be specific and try to scale accurately, it should be done for all winforms controls.

2021-11-03 03:31 UTC, Tanya-Solyanik reviewed
I agree with Devendar's comment about scaling all icons using the same method. We don't have to implement the bigger change within this PR though.

2021-11-03 03:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
> +                // Icon constructor chooses the closest size to the specified one from the icon set - but we can't stop at this step,
> If we want to be specific and try to scale accurately, it should be done for all winforms controls.

I think it's a good idea to put this new method into DpiHelper and use on all icons. But we can start with this case in the toolstrip and apply to other places in other PRs. I guess this one was the most noticeable.

2021-11-03 03:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
> +            if (scaledIcon.Size == scaledSize)
This does not have to be an equality, it could be "close enough", i.e. diff in width and height is less than certain percentage of the desired dimension.

2021-11-03 06:28 UTC, ArtemTatarinov commented
> In principle i am fine reusing it ( alternatively, we can request design team to get new Icon to matches size). My concern is what to do with unused Icon. Removing it from code base may break people. @Tanya-Solyanik

@dreddy-work No icon will be removed from code base, I've just edited `ScrollButtonDown.ico` so it would have the same set of sizes as `ScrollButtonUp.ico`.

2021-11-03 07:37 UTC, ArtemTatarinov commented
@dreddy-work @Tanya-Solyanik If we narrow down the case only to the `ToolStripScrollButton` right now, looks like we have two approaches:

1. **Exact scaling**
Performed with the code:
![image](https://user-images.githubusercontent.com/87859299/140022614-f66943c5-ea5e-4fb6-abc8-22ef28164961.png)
Gives us these icon sizes for DPI modes (all sizes are unique):
100% - 16x16
125% - 20x20
150% - 24x24
175% - 28x28
300% - 48x48

2. **Approx. scaling**
Performed with the code:
![image](https://user-images.githubusercontent.com/87859299/140022791-d6c08ce0-dd59-4e5c-a2a3-2438ccc4f11f.png)
Gives us these icon sizes for DPI modes (some sizes are the same for different DPIs):
100% - 16x16
125% - 24x24
150% - 24x24
175% - 32x32
300% - 48x48

Am I getting it right that the second approach is more preferable, because that precision isn't needed? And in the case of choosing the second option we should resend PR to CTI with a warning that equal sizes for different DPIs are expected behavior?

2021-11-03 18:48 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
> +                // Icon constructor chooses the closest size to the specified one from the icon set - but we can't stop at this step,
@ArtemTatarinov , Can you move this resizing Bitmap logic to `DpiHelper` class and create a new issue to track it for remaining Icons in winforms?

2021-11-03 18:50 UTC, dreddy-work commented
> Am I getting it right that the second approach is more preferable, because that precision isn't needed? And in the case of choosing the second option we should resend PR to CTI with a warning that equal sizes for different DPIs are expected behavior?

Right. We just want to move the logic is precision into DpiHelper class so that it can be used for any Icon in winforms.

2021-11-08 07:56 UTC, ArtemTatarinov commented
> > Am I getting it right that the second approach is more preferable, because that precision isn't needed? And in the case of choosing the second option we should resend PR to CTI with a warning that equal sizes for different DPIs are expected behavior?
> 
> Right. We just want to move the logic is precision into DpiHelper class so that it can be used for any Icon in winforms.

Did it. @dreddy-work @Tanya-Solyanik could you please look at it?

2021-11-08 08:08 UTC, ArtemTatarinov commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
> +                // Icon constructor chooses the closest size to the specified one from the icon set - but we can't stop at this step,
Created a new issue: https://github.com/dotnet/winforms/issues/6137

2021-11-08 19:28 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +            if (icon.Size == scaledSize)
here the sizes are rounding off. as @Tanya-Solyanik mentioned, this doesn't need to be equal in a hard way but can be within some delta. Mat be we can use modulo and check for 1-2 pixel diff?

2021-11-09 07:29 UTC, ArtemTatarinov commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +            if (icon.Size == scaledSize)
@dreddy-work, thank you! I've added checking a two-pixel delta.

2021-11-10 18:35 UTC, dreddy-work commented
@ArtemTatarinov , please check tests.

2021-11-11 13:22 UTC, ArtemTatarinov commented
> @ArtemTatarinov , please check tests.

Looks like there was some concurrency race problem: I'm setting the `DeviceDpi` property of the `DpiHelper` class at my test and then reset it back to its original value at the `finally` block. But it seems that this DPI value affects parallel tests at another class. After re-running the failed jobs all tests have passed now, but I'm looking for a way to avoid this situation in the future: I'll move it the MAUI integration test or maybe move it to a separate unit test class and mark it and the `ToolStripDropDownTests` class with `[Collection("Sequential")]` attribute.

2021-11-15 19:54 UTC, dreddy-work commented
> > @ArtemTatarinov , please check tests.
> 
> Looks like there was some concurrency race problem: I'm setting the `DeviceDpi` property of the `DpiHelper` class at my test and then reset it back to its original value at the `finally` block. But it seems that this DPI value affects parallel tests at another class. After re-running the failed jobs all tests have passed now, but I'm looking for a way to avoid this situation in the future: I'll move this test to the MAUI integration test or maybe move it to a separate unit test class and mark it and the `ToolStripDropDownTests` class with the `[Collection("Sequential")]` attribute which will prevent running these test in parallel mode.

We would need to track that down before we take this. uncertainty in tests success cost lot of manual efforts in CI pipeline. Can you please track down that issue and make sure tests pass reliably?

2021-11-15 23:09 UTC, RussKie commented
Tests that affect the global state must not be the part of the "unit" test collection, and must reside in the UI integration test suite.
Have a chat with @SergeySmirnov-Akvelon and @Danil-Andrianov as they are currently porting the MAUI tests.

2021-11-16 06:57 UTC, ArtemTatarinov commented
@dreddy-work @RussKie Thanks for your answers! I have converted this unit test to the MAUI test and pushed it at this PR. We have discussed porting of this MAUI test to the new UI integration test with the team, and, because porting is still in progress, it will be done later with the other MAUI tests.

Also, the CTI team has tested the latest version of this fix and found no problems.

2021-11-17 00:34 UTC, RussKie requested changes
👍

2021-11-17 00:34 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiToolStripTests/MauiToolStripDropDownTests.cs
> +            var toolStripScrollButtonType = formsAssembly.GetType("System.Windows.Forms.ToolStripScrollButton");
Please decorate System.Windows.Forms project with the `InternalsVisibisleTo` to expose internals to this test project instead.

2021-11-17 19:47 UTC, dreddy-work submitted a review, later dismissed

2021-11-17 19:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        /// Creates a new bitmap scaled to the closest size from the icon set according to the current DPI mode
nit: we leave 2 whitespaces between `///` and the text
```
/// <summary>
///  AAAA
````

2021-11-18 23:03 UTC, RussKie approved these changes

2021-11-18 23:03 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
> +        private static readonly Size defaultBitmapSize = new(16, 16);
OT: it would be good to fix the naming

2021-11-18 23:03 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiToolStripTests/MauiToolStripDropDownTests.cs
> +            dpiTestData.Add(new DpiTestData() { ResourceName = "ScrollButtonUp", Dpi = 288, ExpectedSide = 48 });
@Danil-Andrianov we'd want to change this into a theory when port this into the new UI test framework.

2021-11-18 23:04 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        /// Creates a new bitmap scaled to the closest size from the icon set according to the current DPI mode
```suggestion
        ///  Creates a new bitmap scaled to the closest size from the icon set according to the current DPI mode.
```

2021-11-18 23:05 UTC, merged