Enable nullability in CheckBox adapters
dotnet/winforms pull request #6106
Opened 2021-11-02 20:36 UTC by gpetrou

## Proposed changes

- Enable nullability in CheckBox adapters

2021-11-02 22:35 UTC, RussKie requested changes

2021-11-02 22:35 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxBaseAdapter.cs
> +        private static Color s_checkImageIndeterminateBackColor = Color.Empty;
Thread static must have `t_` prefix

2021-11-03 05:33 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxBaseAdapter.cs
> +        private static Color s_checkImageIndeterminateBackColor = Color.Empty;
I have reverted this. It is showing up as a suggestion.
![image](https://user-images.githubusercontent.com/4172445/140013963-b69d4ccd-de64-49b6-9434-96e1160f73bf.png)

2021-11-08 07:07 UTC, RussKie approved these changes

2021-11-08 07:07 UTC, merged