Enable nullability in some Indexer classes
dotnet/winforms pull request #6111
Opened 2021-11-03 05:41 UTC by gpetrou

## Proposed changes

- Enable nullability in some Indexer classes

2021-11-03 18:42 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeImageIndexer.cs
> +                _owner = node;
validate and throw if null?

2021-11-10 03:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelImageIndexer.cs
> -                    if (_useIntegerIndex)
I think it would be better if we'd write it as 
```cs
                    if (ImageList is null)
                    {
                        return -1;
                    }

                    if (_useIntegerIndex)
                    {
                        // The behavior of label is to return the last item in the Images collection
                        // if the index is currently set higher than the count.
                        return (Index < ImageList.Images.Count) ? Index : ImageList.Images.Count - 1;
                    }

                    return ImageList.Images.IndexOfKey(Key);
```

2021-11-10 03:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelImageIndexer.cs
>                  get { return _owner?.ImageList; }
This looks strange - the `owner`  isn't annotated as nullable, yet we test for nullability...

2021-11-10 03:51 UTC, RussKie requested changes

2021-11-10 03:51 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelImageIndexer.cs
>                  get { return _owner?.ImageList; }
The `owner` can never be `null`, however the image list instance - can.

2021-11-10 03:51 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemImageIndexer.cs
>                  get => _item?.Owner?.ImageList;
ditto here - `item` can never been `null`.

2021-11-10 03:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeImageIndexer.cs
> +                _owner = node;
I don't think it is strictly necessary - this type (and others) are `internal`. Extra checks are essentially an overhead which _may_ (but not necessarily) be optimised away by the compiler.
I think `Debug.Assert(not null)` would sufficient in this situation.

2021-11-15 01:39 UTC, RussKie approved these changes

2021-11-15 01:39 UTC, merged

2021-11-15 01:39 UTC, RussKie commented
Thank you