Fix anchored controls mis-alignment when DPI of the display is higher than 100%
dotnet/winforms pull request #6122
Opened 2021-11-04 20:55 UTC by dreddy-work

This issue was introduced in .NET Framework 4.8.  Control `AnchorInfo `is used in the determination of `Location `of the `Control`.  AnchorInfo was miscalculated (ignored `AnchorStyle `property) when controls scaled on higher DPI settings.

Fixes #5774

2021-11-04 22:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +            if (!_state[s_stateScalingChild]
This could use a lot more commentary. Why do we need to flag for recursion `s_stateScalingChild`? Why don't we scale with `Inherit`?

2021-11-04 22:18 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +            if (!_state[s_stateScalingChild]
That is an existing condition and i simply break the line to more readable format. Only extra condition added here is `AutoscaleFactor `being not equal to `1.0` to improve performance.

2021-11-04 22:32 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +            if (!_state[s_stateScalingChild]
I understand that you didn't change those lines. They are related to the fix- you're changing a condition block that is difficult to understand. At the _very least_ you should be explaining why a "no-op"(?) `Control.Scale` should be avoided. I can't look at this and understand why this additional line changes anything.

2021-11-04 22:33 UTC, JeremyKuhne requested changes
Please clarify why skipping for a 100% scale operation is needed/desired.

2021-11-04 23:56 UTC, JeremyKuhne approved these changes

2021-11-05 17:11 UTC, merged

2021-11-05 22:35 UTC, RussKie commented
@dreddy-work  please raise servicing requests for 3.1, 5.0 and 6.0.