Fixing DPiAwarenessContext cache value for the controls in mixed Dpi mode applications.
dotnet/winforms pull request #6223
Opened 2021-11-24 20:38 UTC by dreddy-work

Currently, we are evaluating the `DpiAwarenessContext `on the fly thus could result in incorrect
evaluation if the application is running in a mixed Dpi mode and we call this property from a wrong thread.

Fixes #6215

2021-11-25 00:53 UTC, RussKie requested changes

2021-11-25 00:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
> +        internal readonly IntPtr DpiAwarenessContext;
These are equivalent.  
Non private fields are a code smell and should be avoided.

2021-11-25 00:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        internal readonly IntPtr DpiAwarenessContext;
```suggestion
        internal IntPtr DpiAwarenessContext { get; } = _window.DpiAwarenessContext;
```

2021-12-14 00:07 UTC, dreddy-work commented
Original issue was misunderstood. This change is not needed.

2021-12-14 00:07 UTC, closed without merging