Add missing feasible file and folder dialog options
dotnet/winforms pull request #6244
Opened 2021-11-28 05:49 UTC by willibrandon

Fixes #5405 

## Proposed changes

- Add the missing feasible file and folder dialog options.

## Customer Impact

- An improved file dialog experience.

## Regression? 

- No.

## Risk

- Minimal.

## Videos 

**OkRequiresInteraction**

Gets or sets a value indicating whether the OK button of the dialog box is disabled until the user navigates the view or edits the filename (if applicable). Note: Disabling of the OK button does not prevent the dialog from being submitted by the Enter key.

https://user-images.githubusercontent.com/5017479/137844523-a2b15923-c496-4481-9941-6518909b46ea.mp4

**ShowPinnedPlaces**

Gets or sets a value indicating whether the items shown by default in the view's navigation pane are hidden.

https://user-images.githubusercontent.com/5017479/137844557-575f1bba-7e47-4db0-b0a5-dd7c6d61cea7.mp4

**ShowHiddenFiles**

Gets or sets a value indicating whether the dialog box displays hidden and system files.

https://user-images.githubusercontent.com/5017479/137844598-8fe5334d-7d29-4c25-acca-58f5d3bfbda4.mp4

**AddToRecent**

Gets or sets a value indicating whether the dialog box adds the folder being selected to the recent list.

https://user-images.githubusercontent.com/5017479/137843944-f00e8399-dd5b-41b8-8943-bfd0be76de10.mp4

**ExpandedMode**

Gets or sets a value indicating whether the dialog box is always opened in the expanded mode.

https://user-images.githubusercontent.com/5017479/137844642-7765180b-0a23-4248-b350-76a7c55c6626.mp4

**CheckWriteAccess**

Gets or sets a value indicating whether the dialog box verifies whether creation of the specified file will be successful. If this flag is not set, the calling application must handle errors, such as denial of access, discovered when the item is created.

https://user-images.githubusercontent.com/5017479/137844713-1ab80c5b-1d1b-4de1-971d-705fe0074c8d.mp4

**ShowPreview**

Gets or sets a value indicating whether the dialog box shows a preview for selected files.

https://user-images.githubusercontent.com/5017479/137844744-c93c7007-9411-41cb-b01a-2b8acb9a62b3.mp4

**SelectReadOnly**

Gets or sets a value indicating whether the dialog box allows to select read-only files.

https://user-images.githubusercontent.com/5017479/137844790-4e40ba95-ef1f-459e-819f-a2900e99b452.mp4

## Test methodology 

- Added unit tests.
- Manual (see videos).

## Accessibility testing  

TODO

## Test environment(s) 

- Windows 10.0.22000
- .NET Core SDK 6.0.100

2021-11-29 00:32 UTC, RussKie reviewed
👍

2021-11-29 22:24 UTC, hughbe approved these changes

2021-11-30 00:56 UTC, RussKie submitted a review, later dismissed

2021-12-13 22:00 UTC, dreddy-work requested changes

2021-12-13 22:00 UTC, dreddy-work commented on src/System.Windows.Forms/src/Resources/SR.resx
> +  <data name="FDaddToRecentDescr" xml:space="preserve">
To be consistent, change FD -> FolderDialog.

2021-12-13 22:00 UTC, dreddy-work commented on src/System.Windows.Forms/src/Resources/SR.resx
> +  <data name="FDokRequiresInteractionDescr" xml:space="preserve">
ok ->Ok?

Same for other strings below.

2021-12-14 01:51 UTC, willibrandon commented on src/System.Windows.Forms/src/Resources/SR.resx
> +  <data name="FDaddToRecentDescr" xml:space="preserve">
Consistent with what? FD stands for File Dialog. If I change it to start with 'FolderDialog' then it would no longer mean what it is. Also the rest of the File Dialog names start with "FD" so if we change it then that means it would now be inconsistent with the other File Dialog names, e.g. FDcheckFileExistsDescr, FDcheckPathExistsDescr, FDdefaultExtDescr, FDshowHelpDescr...

2021-12-14 01:54 UTC, dreddy-work commented on src/System.Windows.Forms/src/Resources/SR.resx
> +  <data name="FDaddToRecentDescr" xml:space="preserve">
Sorry, I mean by FileDialog instead of FD. just like we say FileSaveDialog but not FSD. Use full name instead of abbreviation.

2021-12-14 03:02 UTC, willibrandon commented on src/System.Windows.Forms/src/Resources/SR.resx
> +  <data name="FDaddToRecentDescr" xml:space="preserve">
That should help clear up some confusion.

2021-12-14 17:48 UTC, dreddy-work approved these changes
LGTM.

2021-12-15 00:43 UTC, merged

2021-12-15 00:43 UTC, dreddy-work commented
Thank you @willibrandon .