Rewrite ListViewMAUI tests
dotnet/winforms pull request #6257
Opened 2021-12-02 15:17 UTC by Danil-Andrianov

Fixes #3617 

## Proposed changes

- Replaced ListViewMAUI tests into UI IntegrationTests project

2021-12-03 21:08 UTC, Tanya-Solyanik reviewed
I'm not approving because I'd like someone more familiar with these tests to review it. @vladimir-krestov, @SergeySmirnov-Akvelon, please take a look.

Questions 
- most tests do not have the any input, why are they not in the unit test project? 
- where are the forms disposed?

2021-12-03 21:08 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +
nit: do not separate initialization calls with the blank line

2021-12-03 21:08 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +
nit: do not separate validations with a blank line, but add a blank line after validations are done

2021-12-03 21:08 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                listView.AccessibilityObject.HitTest(point.X, point.Y)!;
nit: indent this line

2021-12-03 21:08 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                        Size = new Size(439, 103)
How did you determine sizes? Just copied from the old tests?

2021-12-05 08:24 UTC, vladimir-krestov submitted a review, later dismissed
Looks good ✔️, rework Tanya's points.

2021-12-06 02:17 UTC, RussKie requested changes

2021-12-06 02:17 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +    public class ListViewTests : ControlTestBase
There are a lot of duplicated tests that only differ on input parameters. Such tests must be converted into "theory" tests. Please work with @SergeySmirnov-Akvelon to reconcile those.

2021-12-06 02:17 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +    public class ListViewTests : ControlTestBase
There are a lot of tests that look like "unit" tests, i.e. they don't require user input (i.e. keyboard/mouse). If there is a reason for them to be here, the reason must be noted in comments.

2021-12-06 09:08 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                        Size = new Size(439, 103)
You're right: there is no necessity in such accuracy. Nevertheless, we can't omit `Size` initialization: it causes tests fail. I could suggest round the values, e.g. (400, 100). What do you think about it?

2021-12-06 09:37 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                        Size = new Size(439, 103)
Sure

2021-12-08 09:54 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +    public class ListViewTests : ControlTestBase
Now duplicated tests are united

2021-12-08 11:55 UTC, Danil-Andrianov commented
@Tanya-Solyanik @RussKie 
Definitely the point about moving some tests to unit tests project not as simple as it appears at the first sight. I left commentary in the code about that point. Please, see the screen.
![image](https://user-images.githubusercontent.com/74228865/145204382-a0dddfc1-edb7-4536-839e-a76e7942647a.png)

2021-12-09 07:29 UTC, RussKie reviewed
Looking better 👍

2021-12-09 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +    // Unit tests don't support the "Tile" mode, so all those tests belong here.
```suggestion
    // NOTE: This class contains many tests which don't require user input. Although they arguably belong to the unit
    // tests project, these tests assert behaviours of ListView.View=View.Tile, which doesn't work correctly unless
    // we ran an app.
```

2021-12-09 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                Assert.Equal(expected, listView.Items[0].Checked);
A typical test consists of three "A"s:
1. Arrange
2. Act
3. Assert

And it is helpful when these three "A"s are visually separated:
```suggestion
                InitializeItems(listView, View.Details, virtualModeEnabled, checkBoxesEnabled);

                Point itemCenter = GetCenter(listView.RectangleToScreen(listView.Items[0].Bounds));
                await MoveMouseAsync(form, itemCenter);
                await InputSimulator.SendAsync(
                    form,
                    inputSimulator => inputSimulator.Mouse.LeftButtonDoubleClick());

                Assert.Equal(expected, listView.Items[0].Checked);
```

Ditto below

2021-12-09 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                Application.DoEvents();
Why do we need this?

2021-12-09 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +        public async Task Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync()
[naming] https://github.com/dotnet/winforms/blob/main/docs/testing.md#naming

2021-12-09 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                }
Any reason why these couldn't be joined?

2021-12-09 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                    inputSimulator => inputSimulator.Mouse.LeftButtonClick());
I suspect these can be amalgamated together:
```suggestion
                await InputSimulator.SendAsync(
                   form,
                   inputSimulator => 
                       inputSimulator.Keyboard.KeyDown(VirtualKeyCode.SHIFT))
                                     .Mouse.LeftButtonClick());
```

2021-12-09 07:30 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +    // Unit tests don't support the "Tile" mode, so all those tests belong here.
If you haven't installed https://marketplace.visualstudio.com/items?itemName=PaulHarrington.EditorGuidelinesPreview, I strongly encourage to do so.
You'll need install "Developer Analytics tools" too, see https://github.com/pharring/EditorGuidelines/issues/87#issuecomment-965794495 for more details.

2021-12-09 07:40 UTC, RussKie commented
> * where are the forms disposed?

Here
https://github.com/dotnet/winforms/blob/8ea3dfb805969d66fc0d96b5911c8a2d797d99f1/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs#L235

2021-12-09 11:25 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                Assert.Equal(expected, listView.Items[0].Checked);
@Tanya-Solyanik On what test style should I focus?
https://github.com/dotnet/winforms/pull/6257#discussion_r762255582

2021-12-09 13:15 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                Application.DoEvents();
This method let us wait while all form's elements will drawn to interact with them correctly.

2021-12-09 23:36 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                Application.DoEvents();
I'm still unconvinced, `InitializeTileList` executes synchronously and it isn't doing any long-running or CPU-intensive work.

2021-12-10 07:44 UTC, Danil-Andrianov commented
> * where are the forms disposed?

Thanks for the question, now form can be disposed. Please, check my last commit.

2021-12-15 01:12 UTC, RussKie approved these changes

2021-12-15 01:16 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                });
We probably want to be more explicit about the size of the form. E.g., what would happen if the test form was somehow narrower or shorter than (400, 100)? 
```suggestion
                createControl: () =>
                {
                    ListView control = new()
                    {
                       Dock = DockStyle.Fill
                    };

                    return control;
                },
                createForm: () =>
                {
                    return new()
                    {
                        Size = new Size(500, 400)
                    };
                });
```

2021-12-15 23:00 UTC, RussKie approved these changes

2021-12-15 23:00 UTC, merged