Rewrite MauiComboBox tests
dotnet/winforms pull request #6261
Opened 2021-12-03 11:38 UTC by Danil-Andrianov

Fixes #3617

## Proposed changes

- Replaced ComboBoxMAUI tests into UI IntegrationTests project

2021-12-05 09:24 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                //scroll items using the up arrow key
Remove blank lines between Aserts
```suggestion
                Assert.True(AddItems(comboBox, szItems, NumItems));
                //scroll items using the down arrow key
                Assert.True(SelectItemWithKeyboard(comboBox, "{DOWN}", numKeyPresses));
                Assert.Equal(_numEvents, numKeyPresses);
                //scroll items using the up arrow key
```

2021-12-05 09:24 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
> +  </ItemGroup>
Why do we need it? Where did you get it?

2021-12-06 02:08 UTC, RussKie requested changes

2021-12-06 02:08 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +            _numEvents = 0;
This is redundant, value types are automatically initialised to 0.

2021-12-06 02:08 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +        public async Task Select_Item_By_KeyboardAsync()
All other tests except this look like unit tests. Unless there is a good reason they must be moved (or removed if we already have tests for the matching functionality) to the unit tests project.

2021-12-06 02:08 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                //scroll items using the down arrow key
All comments must be in sentence case
```suggestion
                // Scroll items using the down arrow key
```

2021-12-06 02:08 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +        private bool SelectItemWithKeyboard(ComboBox comboBox, string key, int numKeyPresses)
https://github.com/dotnet/winforms/pull/6262#discussion_r762652712

2021-12-06 02:08 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
> +  </ItemGroup>
No external dependencies, unless there's a clear justification.

2021-12-09 13:58 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +            bool result = RemoveItems(comboBox, false, 5);
It seems to me that this is a bad approach, when instead of `Assert` for a specific condition, we use a method that checks some conditions inside itself and returns only `true`/`false`.
Firstly, we cannot immediately understand which condition has not been met in the logs of CI build.  
Secondly, even locally, only debugging can help you understand which condition was not met.

2021-12-09 13:58 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        public void ComboBox_SelectedIndex_Changes_SelectedItem_And_Fires_OnSelectedIndexChanged()
I think this test is too difficult to understand. In fact, we get a random `index` and set it as `SelectedIndex` property. If the `index` is already equal to the `SelectedIndex` property, then we consider that the event should not be triggered, otherwise it should.

Firstly, it is difficult to understand and not obvious from the name of the test.
Secondly, the condition when the `index` is already equal to the `SelectedIndex` property may not be met, since we are using random values.

I believe there should be two separate tests that will test both cases. We shouldn't have one test in which checking both cases depends on luck.

2021-12-09 13:58 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        private bool AddItems(ComboBox c, string[] items, int numToAdd)
For me, this is also a very bad approach. When in the name of the method we see just adding items, but in fact we do a lot of manipulations and checks for different conditions. I would create a separate test that checks what is happening here if really necessary. In other tests, I would just add items without additional checks.

2021-12-09 13:58 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        private bool RemoveItems(ComboBox comboBox, bool isByIndex, int numToRemove)
I don't like this approach. As I said above, here we rely on random actions (random `index`) and make checks that are not available for checking in the logs. It is also possible that a random combination will indeed give some kind of error, but we will never be able to reproduce this, since this is a random actions. I would write a simple few tests to cover what is going on here.

2021-12-09 13:58 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        private bool FindItem(ComboBox comboBox, bool isExactMatch)
I would also add some tests that check specific cases, rather than operate on random indices.

2022-01-03 20:47 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +            int actual = comboBox.FindString(value, index);
Given that `FindString `returns insensitive substring matching,  I would add `inlinedata` for substring match aswell.

2022-01-03 20:52 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        private int GetRange(int nMin, int nMax)
This is a private method and called once. Necessary?

2022-01-10 13:59 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +        private int _numEvents;
Please add blank line

2022-01-10 13:59 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                Assert.Equal(numKeyPresses, _numEvents);
```suggestion
                comboBox.SelectedIndexChanged += (x, y) => _numEvents++;
                AddItems(comboBox, 6);
                int numKeyPresses = 5;

                comboBox.SelectedIndex = comboBox.Items.Count - 1;
                _numEvents = 0;

                // Scroll items using the up arrow key
                for (int i = 0; i < numKeyPresses; i++)
                {
                    await InputSimulator.SendAsync(
                        form,
                        inputSimulator => inputSimulator.Keyboard.KeyPress(WindowsInput.Native.VirtualKeyCode.UP));
                }

                Assert.Equal(numKeyPresses, _numEvents);
```

Despite the fact that the test passes, it has two incorrect places that compensate for each other.

First, we execute `comboBox.SelectedIndex = comboBox.Items.Count - 1;` code that changes the value of the `_numEvents` property even before we get into the check loop.

In the cycle itself, we press the `Up` button 5 times, but we are already on the 5th element. In 4 clicks we reach the first element and the last (fifth) pressing of the `Up` button does not affect anything.

Thus, we have a check loop that works as expected only 4 out of 5 times and a change in the value outside the check loop, which leads to the correct, but not expected result.

2022-01-10 13:59 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +                var index = GetRange(0, count - 1);
```suggestion
                var index = GetRange(0, comboBox.Items.Count - 1);
```

2022-01-10 13:59 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +            InitializeItems(comboBox, numberOfItems);
Please add blank line

2022-01-10 13:59 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +            InitializeItems(comboBox, numberOfItems);
Please add blank line

2022-01-10 13:59 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +            int numItems = 200;
Please add blank line

2022-01-10 13:59 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +                Assert.True(result);
```suggestion
                Assert.True(items[i].Equals(comboBox.Items[i]));
```

2022-01-10 13:59 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +            InitializeItems(comboBox, 10);
Please add blank line

2022-01-10 13:59 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +            comboBox.SelectedIndex = index;
```suggestion
            comboBox.SelectedIndex = index;
            int numEvents = 0;
            comboBox.SelectedIndexChanged += (x, y) => numEvents++;
            comboBox.Sorted = false;
            int selectedIndex = comboBox.SelectedIndex;

            comboBox.SelectedIndex = index;
```

2022-01-10 14:45 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                Assert.Equal(numKeyPresses, _numEvents);
That's tricky moment. Thanks for explanation.

2022-01-10 20:38 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                Assert.Equal(numKeyPresses, _numEvents);
>First, we execute comboBox.SelectedIndex = comboBox.Items.Count - 1; code that changes the value of the _numEvents property even before we get into the check loop.

Please add a comment about it to the code.

2022-01-10 20:46 UTC, sharwell commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +                Assert.True(result);
Any reason to not use `Assert.Equal` instead?

2022-01-11 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +        private int _numEvents;
Please remove the field, and use local variables where appropriate/required.

2022-01-11 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +                bool result = item.Equals(comboBox.Items[index]) && comboBox.Items.Count == ++count;
Please don't do this, this is very difficult to read.

2022-01-11 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +        public void ComboBox_Remove_Items_By_Index(int numberOfItems, int index, int number)
```suggestion
        public void ComboBox_Remove_Items_By_Index(int numberOfItems, int index, int numberOfItemsToRemove)
```

2022-01-11 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +                var item = (GetInt(true) % 26 + 97).ToString();
`GetInt` method is not needed. it can be simplified and inlined.
Also please avoid magic numbers (not everyone remembers ASCII table by heart 😃), i.e. `97 -> (char)'a'`

2022-01-11 07:29 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +                Assert.Equal(0, e.ItemWidth);
Keep similar actions together
```suggestion
                Assert.NotNull(e.Graphics);
                Assert.Equal(e.Index, i);
                Assert.Equal(18, e.ItemHeight);
                Assert.Equal(0, e.ItemWidth);
```

2022-01-13 10:02 UTC, SergeySmirnov-Akvelon commented
azp /run

2022-01-17 04:52 UTC, RussKie requested changes

2022-01-17 04:52 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                numEvents = 0;
We already initialised this earlier.

2022-01-17 04:52 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                form.Focus();
The dialog is already shown and is focused.

2022-01-17 04:52 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                Application.DoEvents();
Why is this needed?

2022-01-17 04:52 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                int numKeyPresses = 9;
Move it down where it is used.

2022-01-17 04:52 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                comboBox.SelectedIndexChanged += (x, y) => numEvents++;
This can be wired after the combobox is fully initialised, i.e. after `AddItems` is called.

2022-01-17 04:52 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
> +            };
Why do we need `Location` in the unit tests?

2022-01-17 13:49 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                numEvents = 0;
Yes, but after line 30 `numEvents` is equal 1 and we should nullify it.

2022-01-18 05:50 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                numEvents = 0;
What is the reason to init it before line:30?

2022-01-18 05:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                numEvents = 0;
```suggestion
                AddItems(comboBox, 10);
                comboBox.SelectedIndex = comboBox.Items.Count - 1;

                int numEvents = 0;
                comboBox.SelectedIndexChanged += (x, y) => numEvents++;
```

2022-01-19 02:43 UTC, RussKie reviewed
I see several feedback comments thumbed up but not corresponding changes. Have those changes been pushed?

2022-01-19 02:43 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                },
I'm pretty certain this would work:

```suggestion
        private async Task RunComboBoxTestAsync(Func<Form, ComboBox, Task> runTest, int numberOfItemsToAdd, int selectedIndex)
        {
            await RunSingleControlTestAsync(
                testDriverAsync: runTest,
                createControl: () =>
                {
                    ComboBox control = new();
                    AddItems(comboBox, numberOfItemsToAdd);
                    comboBox.SelectedIndex = selectedIndex;

                    return control;
                },
```

```cs
        [WinFormsFact]
        public async Task ComboBox_Select_Item_By_DownArrowKeyAsync()
        {
            await RunComboBoxTestAsync(async (form, comboBox) =>
            {
                int numEvents = 0;
                comboBox.SelectedIndexChanged += (x, y) => numEvents++;

                // ...
            },
            numberOfItemsToAdd: 10,
            selectedIndex: 0);
        }
```

2022-01-19 08:47 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
> +                },
Sorry, I forgot about one amendment.

2022-01-24 01:43 UTC, RussKie commented
Some tests are failing fairly consistently. Setting as draft until the failures are investigated.

2022-05-24 20:15 UTC, closed without merging