Rewrite printPreviewDialog, label and DataGridView MAUI tests
dotnet/winforms pull request #6262
Opened 2021-12-03 12:18 UTC by Danil-Andrianov

Fixes #3617

## Proposed changes

- Replaced DataGridViewMAUI tests into UI IntegrationTests project
- Replaced LabelMAUI tests into UI IntegrationTests project
- Replaced PrintPreviewDialogMAUI tests into UI IntegrationTests project

2021-12-05 09:26 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/LabelTests.cs
> +                Assert.Equal(newSize, oldSize);
Add a blank line before the Assert here and for the rest test as well

2021-12-05 09:26 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PrintPreviewDialogTests.cs
> +
Remove blank lines between Asserts

2021-12-06 02:03 UTC, RussKie requested changes

2021-12-06 02:10 UTC, RussKie commented
Please review this doc as well: https://github.com/dotnet/winforms/blob/main/docs/testing.md and correct the naming as per https://github.com/dotnet/winforms/blob/main/docs/testing.md#naming section.

2021-12-12 10:46 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/LabelTests.cs
> +        public LabelTests(ITestOutputHelper testOutputHelper)
`AutoSize` property doesn't work correctly without the form, therefore I suggest to remain things as it is.

2021-12-16 02:44 UTC, RussKie reviewed
Almost there :)

2021-12-16 02:44 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +        // We need to show this Form ourselves, the issue won't reproduce with ReflectBase-inherited Form which is shown automatically while scenarios is being run.
This comment is no longer relevant

2021-12-16 02:44 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +                form.Close();
We need a comment for this line, as it's not generally expected to close the dialog in the body of the test.

2021-12-16 02:44 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +                // Create DataGridView with DataSource set to dataTable.
This comment is largely redundant - it's pretty obvious what it's doing.

2021-12-20 09:24 UTC, Danil-Andrianov commented
@RussKie https://github.com/dotnet/winforms/pull/6262/#discussion_r770104067
Do we really needed to have commentary there? What kind of commentary do you expect there?

2021-12-20 09:27 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +        // We need to show this Form ourselves, the issue won't reproduce with ReflectBase-inherited Form which is shown automatically while scenarios is being run.
Do we really needed in any comment there? What kind of comment do you expect?

2021-12-24 09:01 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/LabelTests.cs
> +        public LabelTests(ITestOutputHelper testOutputHelper)
I made a mistake: those label tests could be moved to the unit tests project if we merely add label to the form. So I just did it.

2022-01-03 21:00 UTC, dreddy-work commented
LGTM.

2022-01-06 03:51 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +                // We need to close the form and then check whether dataTable works fine or it doesn't
```suggestion
                // Close the form to verify no exceptions thrown while showing the tooltip.
                // Regression test for https://github.com/dotnet/winforms/issues/5496
```

2022-01-06 03:51 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +                // Move mouse cursor over any cell of the first row.
```suggestion
                // Move mouse cursor over any cell of the first row to trigger a tooltip.
```

@vladimir-krestov  @ArtemTatarinov is there a way to check a tooltip is shown?

2022-01-06 03:51 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +                Assert.False(exceptionThrown);
```suggestion
                dataTable.AcceptChanges();
```

If there's an exception - the test will fail.

2022-01-06 03:51 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +                    dialog!.Close();
The dialog must be disposed of. Please see `RunFormAsync` above.

2022-01-06 03:51 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs
> +        }
I think these two can be combined into a theory test, something like
```suggestion
        [WinFormsTheory]
        [InlineData(false, false)]
        [InlineData(true, true)]
        public void Label_AutoSize_BehavesExpected(bool autoSize, bool expected)
        {
            using Form form = new Form();
            using Label label = new()
            {
                AutoSize = autoSize,
                Size = new(10, 10),
                Text = "Hello",
            };
            Size oldSize = label.Size;
            form.Controls.Add(label);
            form.Show();

            label.Text = "Say Hello";
            Size newSize = label.Size;

            Assert.Equal(expected, newSize == oldSize);
        }

```

2022-01-10 22:27 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +                // Close the form to verify no exceptions thrown while showing the tooltip.
We're meant to close, right?

2022-01-11 07:44 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +        protected async Task RunFormWithoutControlAsync(Func<PrintPreviewDialog> createForm, Func<PrintPreviewDialog, Task> testDriverAsync)
No, no, no... This is a general purpose class and we mustn't hardcode any specific types here.
```suggestion
        protected async Task RunFormWithoutControlAsync<TForm>(Func<TForm> createForm, Func<TForm, Task> testDriverAsync) where TForm: Form
```

2022-01-11 16:37 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +                // Close the form to verify no exceptions thrown while showing the tooltip.
Could you clarify what do you mean, please?

2022-01-12 03:13 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +                // Close the form to verify no exceptions thrown while showing the tooltip.
According to the comment we're meant to close the dialog _before_ we accept changes. This what the original test was doing.

2022-01-12 08:55 UTC, Danil-Andrianov commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
> +                // Close the form to verify no exceptions thrown while showing the tooltip.
Oh, I hope now I got you.

2022-01-12 09:03 UTC, RussKie approved these changes

2022-01-13 03:11 UTC, merged