Enable nullability in ChildAccessibleObject
dotnet/winforms pull request #6287
Opened 2021-12-04 18:32 UTC by gpetrou

## Proposed changes

- Enable nullability in ChildAccessibleObject

2021-12-06 00:51 UTC, RussKie requested changes
@vladimir-krestov @SergeySmirnov-Akvelon please review whether `[in] owner` can be `null` at all. If not - then we must throw ANE like we do in other places.

2021-12-06 00:51 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ChildAccessibleObject.cs
This doesn't look correct - if `[in] owner` is nullable, then the backing field must be nullable as well.

2021-12-06 07:51 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ChildAccessibleObject.cs
> +            public ChildAccessibleObject(ComboBox? owner, IntPtr handle)
The `owner` **can't** be `null` in the current implementation.
Check the constructor links. It's used for `ComboBoxChildEditUiaProvider` and `ComboBoxChildListUiaProvider` classes. Their constructors are used once, and `owner` argument is a ComboBox (check links, there are `this` is used).
Moreover, `ComboBoxChildEditUiaProvider` and `ComboBoxChildListUiaProvider` use `_owningComboBox` and `_owner` fields without nullablity checks. So we are sure, that they can't be null. And in the end we should mark `owner` as non-nullable argument.
```suggestion
            public ChildAccessibleObject(ComboBox owner, IntPtr handle)
```

@gpetrou, please:
- remove `?` from this file and make `owner/_owner` as non-nullable. 
- remove `PublicAPI.Shipped.txt` changes.
- throw `ArgumentNullException`, if `owner` is `null`, like we do in `ControlAccessibleObject`:
![image](https://user-images.githubusercontent.com/49272759/144807539-bc9056e3-bdcd-463e-ac11-e7bcfd0d5a79.png)

- enable nullablility for `ComboBoxChildEditUiaProvider` and `ComboBoxChildListUiaProvider` as well, if it's possible.
- add a unit test for `ChildAccessibleObject` that the constructor throws ANException, if `owner` is `null`.

2021-12-06 16:55 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ChildAccessibleObject.cs
> +            public ChildAccessibleObject(ComboBox? owner, IntPtr handle)
I will do a separate PR when I have time for `ComboBoxChildEditUiaProvider` and `ComboBoxChildListUiaProvider`. For the rest of the comments, I will update the current PR.

2021-12-06 16:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ChildAccessibleObject.cs
> +            public ChildAccessibleObject(ComboBox? owner, IntPtr handle)
Thank you!

2021-12-06 22:27 UTC, RussKie submitted a review, later dismissed

2021-12-06 22:31 UTC, RussKie reviewed
👍 with few nits

2021-12-06 22:31 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ChildAccessibleObject.cs
> +                Debug.Assert(owner.IsHandleCreated is true, "ComboBox's handle hasn't been created");
```suggestion
                Debug.Assert(owner.IsHandleCreated, "ComboBox's handle hasn't been created");
```

2021-12-06 22:31 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ChildAccessibleObject.cs
> +                if (owner.IsHandleCreated is true)
```suggestion
                if (owner.IsHandleCreated)
```

2021-12-06 22:32 UTC, RussKie commented
Docs: https://github.com/dotnet/docs/issues/26720

2021-12-08 02:38 UTC, Tanya-Solyanik approved these changes

2021-12-08 07:40 UTC, vladimir-krestov approved these changes
Looks good ✔️

2021-12-08 19:06 UTC, merged