Enable nullability in ArraySubsetEnumerator
dotnet/winforms pull request #6328
Opened 2021-12-11 09:05 UTC by gpetrou

## Proposed changes

- Enable nullability in ArraySubsetEnumerator.

2021-12-14 22:00 UTC, dreddy-work approved these changes

2021-12-15 01:26 UTC, RussKie requested changes

2021-12-15 01:26 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ArraySubsetEnumerator.cs
> +        public ArraySubsetEnumerator(object[]? array, int count)
I would say that this is a non-nullable.
Also looking at how it is used - `ListViewSubItemCollection.GetEnumerator()` has a null-check before invoking this API, whilst `TreeNodeCollection.GetEnumerator()` doesn't - and this is a deficiency would need to address in the future.

2021-12-15 01:54 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ArraySubsetEnumerator.cs
> +        public ArraySubsetEnumerator(object[]? array, int count)
We don't stop or check for null. `Movenext ` handle passing null value.

2021-12-15 02:16 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ArraySubsetEnumerator.cs
> +        public ArraySubsetEnumerator(object[]? array, int count)
This is an `internal` API so we control the input parameters. We also have an assertion that the array isn't null. We don't check however anywhere that the array's elements aren't null, though looking at how we use the API we never expect neither a null array or null elements.
The use of `!` is generally an indication of a code smell.

We could add a null check to the .ctor - `array.ThrowIfNull();`, but I don't really see a value in this.

2021-12-21 18:17 UTC, dreddy-work approved these changes

2021-12-22 18:42 UTC, merged