Enable nullability in ToolStripItemAccessibleObject
dotnet/winforms pull request #6358
Opened 2021-12-16 17:58 UTC by gpetrou

## Proposed changes

- Enable nullability in ToolStripItemAccessibleObject.

2021-12-17 22:09 UTC, dreddy-work requested changes

2021-12-17 22:09 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
> +            public override string? Name
I don't see this can be null. It can be `string.empty` but not null.

2021-12-21 09:22 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
> +            public override string? Name
I other places such as ControlAccessibleObject this is nullable, I guess because TextWithoutMnemonics can return null.

2021-12-21 18:56 UTC, dreddy-work approved these changes

2021-12-22 18:47 UTC, merged