Enable nullability in some COM2 handlers
dotnet/winforms pull request #6384
Opened 2021-12-21 17:35 UTC by gpetrou

## Proposed changes

- Enable nullability in some COM2 handlers.

2022-01-11 20:35 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                string?[] strs = new string[cStrings];
I do not see why this would be nullable array.  `bstr` checked for non-null pointer before querying for string.

2022-01-11 20:35 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +            string?[] attrTypeNames = GetStringsFromPtr(pbstrs, cItems);
see comment in`GetStringsFromPtr` method. It may return array of empty strings but should not return null strings.

2022-01-11 20:35 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                string? attrName = attrTypeNames[i];
won't be null?

2022-01-11 20:35 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                if (attrName is not null)
may just need check for empty string.

2022-02-07 21:21 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IPerPropertyBrowsingHandler.cs
> +                string?[] names = caStrings.ConvertAndFree();
this isn't clear. Why names should be nullable and not cookies.

2022-02-07 21:29 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                                attr = (Attribute?)Activator.CreateInstance(t, new object[] { varParams[i]! });
should `attrs `be nullable array then here?

2022-02-15 18:29 UTC, dreddy-work commented
@gpetrou , please take a look at last feedback.

2022-02-27 09:17 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IPerPropertyBrowsingHandler.cs
> +                string?[] names = caStrings.ConvertAndFree();
Inside ConvertAndFree that returns a string array, we use Marshal.PtrToStringUni.

2022-03-02 01:22 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                Attribute[] attrs = GetComponentAttributes(browsing, sender.DISPID);
null check is not needed at below line.

2022-03-02 01:22 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ICategorizePropertiesHandler.cs
>              if (cat is not null && cat.Length > 0)
change condition to -> cat?.length > 0 ?

2022-03-02 01:24 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                Assembly? a = null;
simplify to Assembly? a = t?.Assembly ?

2022-03-02 01:25 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                if (t is null && attrName is not null)
why this extra condition? if `attrName `can be null why is it not defined so?

2022-03-02 01:30 UTC, dreddy-work requested changes
@gpetrou , i see there is potential to further cleanup code here. Do you mind take another look?

2022-03-07 08:12 UTC, gpetrou commented
@dreddy-work any more feedback on this or could we merge it?

2022-03-07 08:55 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                        if (pis.Length == 1 && pis[0].ParameterType.IsAssignableFrom(varParams[i]!.GetType()))
Why do we need `!` here?
![image](https://user-images.githubusercontent.com/4403806/156997641-4de06fb4-fd76-4a1b-b497-59e4ea3d4065.png)

2022-03-07 08:55 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IVsPerPropertyBrowsingHandler.cs
> +                    BOOL pfHide = sender.Attributes[typeof(BrowsableAttribute)]!.Equals(BrowsableAttribute.No) ? BOOL.TRUE : BOOL.FALSE;
`sender.Attributes[Type]` is marked as nullable, so we should do something like this:
```suggestion
                    BOOL pfHide = sender.Attributes[typeof(BrowsableAttribute)] is Attribute browsableAttribute
                                && browsableAttribute.Equals(BrowsableAttribute.No) ? BOOL.TRUE : BOOL.FALSE;
```

2022-03-08 07:44 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                        if (pis.Length == 1 && pis[0].ParameterType.IsAssignableFrom(varParams[i]!.GetType()))
I pulled your branch, and indeed it's giving a warning.
In this case I suggest we refactor as follows:
```diff
diff --git a/src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs b/src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
index 7761614d6..a7e2950bc 100644
--- a/src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
+++ b/src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
@@ -164,19 +164,20 @@ namespace System.Windows.Forms.ComponentModel.Com2Interop
                 // okay, if we got here, we need to build the attribute...
                 // get the initializer value if we've got a one item ctor
 
-                if (!Convert.IsDBNull(varParams[i]) && varParams[i] is not null)
+                var varParam = varParams[i];
+                if (!Convert.IsDBNull(varParam) && varParam is not null)
                 {
                     ConstructorInfo[] ctors = t.GetConstructors();
                     for (int c = 0; c < ctors.Length; c++)
                     {
                         ParameterInfo[] pis = ctors[c].GetParameters();
-                        if (pis.Length == 1 && pis[0].ParameterType.IsAssignableFrom(varParams[i]!.GetType()))
+                        if (pis.Length == 1 && pis[0].ParameterType.IsAssignableFrom(varParam.GetType()))
                         {
                             // found a one-parameter ctor, use it
                             // try to construct a default one
                             try
                             {
-                                attr = (Attribute?)Activator.CreateInstance(t, new object?[] { varParams[i] });
+                                attr = (Attribute?)Activator.CreateInstance(t, new object[] { varParam });
                                 attrs.Add(attr);
                             }
                             catch
```

2022-03-08 07:45 UTC, RussKie commented
Once https://github.com/dotnet/winforms/pull/6384#discussion_r821397771 is addressed this is ready to merge.
Thank you

2022-03-09 00:20 UTC, RussKie approved these changes

2022-03-09 00:21 UTC, merged