Enable nullability in MouseHoverTimer
dotnet/winforms pull request #6395
Opened 2021-12-22 10:03 UTC by gpetrou

## Proposed changes

- Enable nullability in MouseHoverTimer.

2021-12-22 19:41 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MouseHoverTimer.cs
> +        private Timer? _mouseHoverTimer = new Timer();
why?

2021-12-22 19:43 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MouseHoverTimer.cs
>              _currentItem = item;
`item `should be nullable here.

2022-01-05 06:57 UTC, Tanya-Solyanik approved these changes
Thank you!

2022-01-12 00:49 UTC, dreddy-work requested changes

2022-01-12 00:49 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/MouseHoverTimer.cs
> +        private Timer? _mouseHoverTimer = new Timer();
@gpetrou , the way this is initialized, we do not expect `_mouseHoverTimer` to be null in any practical scenarios here. I understand that `null` assignment statement in the `dispose ` method is forcing this.  We think the right thing to do here is remove the `null `assignment statement in the dispose method and keep this non-nullable.

2022-01-14 19:11 UTC, dreddy-work approved these changes

2022-01-14 19:46 UTC, Tanya-Solyanik approved these changes
Thank you!

2022-01-14 21:48 UTC, merged