ComboBox: fix SelectedItem/SelectedIndex when SelectedItem removed from Items
dotnet/winforms pull request #6406
Opened 2021-12-22 18:13 UTC by jbhensley

Fixes #6304.

## Proposed changes

Fixes `ArgumentOutOfRangeException` when `SelectedItem` removed from `ComboBox.Items` and then `SelectedItem` property is subsequently accessed.

## Customer Impact

No more `ArgumentOutOfRangeException`

## Regression? 

- Fixes bug in .NET Core 7 alpha

## Risk

## Test methodology 

Unit test added. Fails on unpatched code. Passes on patched.

2021-12-22 19:54 UTC, dreddy-work reviewed
LGTM. @SergeySmirnov-Akvelon , can you guys take a look as well?

2021-12-23 14:07 UTC, WPMGPRoSToTeMa requested changes
👍

2021-12-23 14:07 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
> +                        _owner.UpdateText();
Probably events should also be triggered:
https://github.com/dotnet/winforms/blob/e83b710bb8bbf9c9c40395e2d070ff7d5f3e80b4/src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs#L1035-L1036
```suggestion
                        // Update ComboBox text and trigger selection changed events
                        _owner.SelectedIndex = -1;
```

2021-12-24 06:01 UTC, ArtemTatarinov commented
LGTM

2021-12-24 10:45 UTC, vladimir-krestov approved these changes
LGTM ✔️ 
PS. @jbhensley, please clean up the PR commits history.

2021-12-24 16:31 UTC, jbhensley commented
> LGTM ✔️ PS. @jbhensley, please clean up the PR commits history.

Rebased

2021-12-27 17:40 UTC, dreddy-work approved these changes

2021-12-27 17:40 UTC, merged