Enable nullability in EnumUnknown
dotnet/winforms pull request #6407
Opened 2021-12-23 06:19 UTC by gpetrou

## Proposed changes

- Enable nullability in EnumUnknown.

2021-12-27 17:58 UTC, dreddy-work requested changes

2021-12-27 17:58 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.EnumUnknown.cs
> +                _arr = arr;
seems `arr `can be null

2022-01-25 21:32 UTC, dreddy-work approved these changes

2022-01-30 07:00 UTC, gpetrou commented
@dreddy-work maybe we could merge this now that the build completed successfully?

2022-01-30 07:32 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.EnumUnknown.cs
> +                    if (_array is not null)
This is unnecessary check. If location < _size,   why would _array be null. Old code was not checking for it either.

2022-01-30 07:38 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.EnumUnknown.cs
> +                    if (_array is not null)
I used `!` instead.

2022-01-30 08:07 UTC, dreddy-work approved these changes

2022-01-31 00:33 UTC, merged