Enable nullability in NativeWindow
dotnet/winforms pull request #6410
Opened 2021-12-23 07:09 UTC by gpetrou

## Proposed changes

- Enable nullability in NativeWindow.

2022-01-05 06:18 UTC, Tanya-Solyanik submitted a review, later dismissed
:shipit:

2022-01-07 18:39 UTC, dreddy-work requested changes

2022-01-07 18:39 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.WindowClass.cs
> +                    if (User32.GetClassInfoW(NativeMethods.NullHandleRef, _className!, ref windowClass).IsFalse())
in order to avoid `!` on `localClassName `in this method, you may want to change condition at line # 137 to if ( _className is null)

2022-01-24 03:20 UTC, dreddy-work commented
azp /run

2022-01-25 21:33 UTC, dreddy-work approved these changes

2022-01-25 21:33 UTC, merged