Implementing support UIA Provider for TreeView control
dotnet/winforms pull request #6432
Opened 2021-12-27 23:12 UTC by DmitryGorokhov

Implemented accessible objects for TreeView and TreeNode. Added needed automation events and unit tests.

Fixes #3421

## Proposed changes

- Switched on `SupportsUiaProviders` property of `TreeView` class.
- Implemented accessible objects for `TreeView` and `TreeNode` classes.
- Added needed automation events and unit tests.

## Customer Impact

- Improving development experience for `TreeView` control accessibility.

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Inspect

#### `TreeView` before and after

![treeInspect](https://user-images.githubusercontent.com/58004471/147510526-ea1fd609-cb83-48c0-9a62-343d669e8d0b.png)

#### Default `TreeNode` before and after

![nodeInspect](https://user-images.githubusercontent.com/58004471/147510598-3d6c6aa4-d689-4096-8b42-76aaeadf2d60.png)

#### Expanded `TreeNode` before and after

![nodeExpandedInspect](https://user-images.githubusercontent.com/58004471/147510641-ed1a6b4e-2f89-49c4-a1b0-d4328163d19a.png)

#### Leaf `TreeNode` before and after

![nodeLeafInspect](https://user-images.githubusercontent.com/58004471/147510740-5338f9df-acaf-4a61-92c8-639661f2b5ba.png)

#### CheckBox `TreeNode` before and after

![NodeIsCheckBox](https://user-images.githubusercontent.com/58004471/147510784-e73d3152-cadc-404c-a436-1ab137356a67.png)

#### Invisible `TreeNode` before and after

![invisibleNode](https://user-images.githubusercontent.com/58004471/147510820-2732e09f-fec2-402e-8e5d-5c8f99c6a2ee.png)

#### Editable `TreeNode` before and after

![nodeEditable](https://user-images.githubusercontent.com/58004471/147510856-16c4a0eb-291d-4bfb-a2ae-c3b8650543a3.png)

### Accessibility Insights

There is no specific errors. You can see errors on next image, but they are not about accessibility changes were created in this PR.

![AI](https://user-images.githubusercontent.com/58004471/147511075-7519afab-29c3-4714-9b03-3533fe8da74c.png)

### Narrator

#### Expand and collapse default node before and after

![NBExpandCollapse](https://user-images.githubusercontent.com/58004471/147511138-ec17d1dd-9f19-42a3-b44e-900dd1a8e038.png)

#### Check and uncheck node before and after

![NBCheckedBox](https://user-images.githubusercontent.com/58004471/147511169-b1ca4ecd-545f-443c-8dff-129982fea28f.png)

#### Edit default node before and after

![NBEdit](https://user-images.githubusercontent.com/58004471/147511183-ac62934d-29cb-4ab5-b32c-6f91e78e3f05.png)

### `ScrollIntoView` method comparison

#### `ScrollIntoView` method before

![ScrollIntoViewBefore](https://user-images.githubusercontent.com/58004471/147511275-2caad097-acb4-46f0-8aa2-4b115a934890.gif)

#### `ScrollIntoView` method after

![ScrollIntoViewAfter](https://user-images.githubusercontent.com/58004471/147511279-557713bb-3539-4801-b81a-dc80e1215ed3.gif)

This realization sets calling node as `TopNode`  of `TreeView` if the node is invisible. Looks like it works the same. 

### Focus on `TreeView` issue

By default, when we focus on a `TreeView` control, Inspect and Narrator highlight the `SelectedNode` of
 this control. As I know it takes raise an events for a selected node accessible object to notify it was focused. But calling AccessibilityObject forces creation the object. It takes accessible object of the tree, so forces creating the object if it doesn't exist yet.
 To avoid force creation if this is not needed should use check `IsAccessibilityObjectCreated`. But I found next problem when I try to add this check. Highlight after focus doesn't work for the first time if the control has first `TabIndex` on form.  You can see this issue behavior below.
 
 #### Focus on the control with check `IsAccessibilityObjectCreated`
 
It works incorrect.
 

![BrokenFocusOnTreeView](https://user-images.githubusercontent.com/58004471/147512386-b429de63-9bda-4498-bc64-5bd25076beaa.gif)

 #### Focus on the control without check `IsAccessibilityObjectCreated`

It works great, but not safety due to forcing the object creating.

![FocusOnTreeView](https://user-images.githubusercontent.com/58004471/147512415-1f71ba67-4201-43e7-b7db-1c6381e94b05.gif)

It was not so easy for me to resolve it in the fix. So I skipped this problem and took implementation without the check. I guess this problem needs to be investigated and resolved in out of scope issue. 
 
 ### Additional note

I take it if node is check box it has `DefaultAction` equals `Check` or `Uncheck` but before the fix `DoDefaultAction` does nothing in this case. I configured this method, so it performs `Toggle` method of `TreeNodeAccessibleObject` in this case.

## Test methodology 

- Manually
- Unit testing
- CTI

## Accessibility testing  

- Inspect
- Accessibility Insights
- Narrator
 

## Test environment(s) 

- .Net version: 6.0.100
- OS version: 10.0.19044

2021-12-28 13:13 UTC, vladimir-krestov reviewed
Great work!
Awesome description!

2021-12-28 14:49 UTC, WPMGPRoSToTeMa reviewed
Thank you, you've done an amazing work!

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    base.IsPatternSupported(patternId);
Consider:
```suggestion
                => patternId switch
                {
                    UiaCore.UIA.ExpandCollapsePatternId => true,
                    UiaCore.UIA.LegacyIAccessiblePatternId => true,
                    UiaCore.UIA.ScrollItemPatternId => true,
                    UiaCore.UIA.SelectionItemPatternId => true,
                    UiaCore.UIA.TogglePatternId when _owningTreeView.CheckBoxes => true,
                    UiaCore.UIA.ValuePatternId when _owningTreeView.LabelEdit => true,
                    _ => base.IsPatternSupported(patternId),
                };
```

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    : null;
```suggestion
            public override AccessibleObject? Parent => _owningTreeNode.Parent?.AccessibilityObject;
```

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    (int)(long)_owningTreeView.InternalHandle,
```suggestion
                    PARAM.ToInt(_owningTreeView.InternalHandle),
```

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    UiaCore.NavigateDirection.LastChild => GetChild(GetChildCount()-1),
nit:
```suggestion
                    UiaCore.NavigateDirection.LastChild => GetChild(GetChildCount() - 1),
```

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                => child is not null && child is TreeNodeAccessibleObject node ? node.Index : -1;
`child is TreeNodeAccessibleObject node` implies that `child is not null`:
```suggestion
                => child is TreeNodeAccessibleObject node ? node.Index : -1;
```

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    (int)(long)_owningTreeView.InternalHandle,
```suggestion
                    PARAM.ToInt(_owningTreeView.InternalHandle),
```

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    base.IsPatternSupported(patternId);
Ditto.

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +            }
Consider:
```suggestion
            internal override UiaCore.IRawElementProviderSimple[]? GetSelection()
            {
                if (_owningTreeView.IsHandleCreated && GetSelected() is UiaCore.IRawElementProviderSimple selected)
                {
                    return new[] { selected };
                }

                return Array.Empty<UiaCore.IRawElementProviderSimple>();
            }
```

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +                    UiaCore.ExpandCollapseState.Collapsed);
Consider:
```suggestion
                    oldValue: UiaCore.ExpandCollapseState.Expanded,
                    newValue: UiaCore.ExpandCollapseState.Collapsed);
```

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +                    UiaCore.ExpandCollapseState.Expanded);
Ditto.

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +                    nodeAccessibleObject.IsItemSelected);
Ditto.

2021-12-28 14:49 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeView.TreeViewAccessibleObjectTests.cs
> +            AccessibleObject expected = control.Nodes[^1].AccessibilityObject;
Nice!

2022-01-04 03:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                else
nit: use ternary conditional operator to match code above this function

2022-01-04 03:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    //
nit: we are removing empty commented out lines elsewhere. Also comment on line187 is not adding context to the code below

2022-01-04 03:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    //
nit: please remove the empty line

2022-01-04 03:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    //
nit: please remove the empty line

2022-01-09 11:21 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                else
I can't do this.
![image](https://user-images.githubusercontent.com/58004471/148680068-2871fa25-d407-428f-881e-ab812d7dbbfc.png)

2022-01-09 11:39 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    UiaCore.UIA.IsOffscreenPropertyId => (State & AccessibleStates.Offscreen) == AccessibleStates.Offscreen,
Do you mean line 111 `UiaCore.UIA.IsEnabledPropertyId => _owningTreeView.Enabled`? Done if so.

2022-01-09 12:24 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            SelectedNode?.AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.AutomationFocusChangedEventId);
Ok, but I see described problem again.

![IncorrectTreeViewFocus](https://user-images.githubusercontent.com/58004471/147512386-b429de63-9bda-4498-bc64-5bd25076beaa.gif)

2022-01-09 15:05 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                _owningTreeView = owningTreeView ?? throw new ArgumentNullException(nameof(owningTreeView));
Maybe use `.OrThrowIfNull();` as we do in other places?

2022-01-09 15:08 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +            public TreeNodeAccessibleObject(TreeNode owningTreeNode, TreeView owningTreeView) : base()
Is `: base()` needed?

2022-01-10 09:36 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    UiaCore.UIA.IsOffscreenPropertyId => (State & AccessibleStates.Offscreen) == AccessibleStates.Offscreen,
I asked the team about this comment. I take it is about removing `UiaCore.UIA.IsOffscreenPropertyId` case. Removed this, restored `UiaCore.UIA.IsOffscreenPropertyId`.

2022-01-10 09:38 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                _owningTreeView = owningTreeView ?? throw new ArgumentNullException(nameof(owningTreeView));
Yes, it looks better. Thank you

2022-01-10 09:40 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +            public TreeNodeAccessibleObject(TreeNode owningTreeNode, TreeView owningTreeView) : base()
Seems no, because the base ctor of AccessibleObject is empty. So I remove them.

2022-01-10 09:45 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +            public TreeNodeAccessibleObject(TreeNode owningTreeNode, TreeView owningTreeView) : base()
I also searched for the same places throughout the project. We use  base empty ctor of AccessibleObject in following AO classes:
- DataGridViewTopRowAccessibleObject
- DomainItemAccessibleObject
- DomainItemListAccessibleObject
- LinkAccessibleObject
- GridEntryAccessibleObject

I think we can check and rework this cases in out of scope issue.

2022-01-10 21:12 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            SelectedNode?.AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.AutomationFocusChangedEventId);
Test is AO for the parent tree view control is created instead.

2022-01-10 21:17 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                else
Consider:
```
return _owningTreeNode.IsExpanded ? Collapse() : Expand();
```

2022-01-10 21:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                else
How about: `return _owningTreeNode.IsExpanded ? Collapse() : Expand();`

2022-01-10 21:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +            public TreeNodeAccessibleObject(TreeNode owningTreeNode, TreeView owningTreeView) : base()
>I think we can check and rework this cases in out of scope issue.

Great idea!

2022-01-11 01:48 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            SelectedNode?.AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.AutomationFocusChangedEventId);
> Test if AO for the parent tree view control is created instead.

As I can see it is possible to check the root form (that has buttons). It can be found via `Control.TopLevelControl` and `Form.Owner`. But the problem is that the form where TreeView is located has `IsAccessibilityObjectCreated == false`. So if we have only a single form this won't work.

2022-01-11 03:35 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            SelectedNode?.AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.AutomationFocusChangedEventId);
It's unlikely that accessibility tool has access to a tree node that is not contained in the TreeView's nodes collection. If it does, we can return null. I don't see why we need to look for the form.

2022-01-11 03:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            SelectedNode?.AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.AutomationFocusChangedEventId);
Ignore my comment

2022-01-11 03:47 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            SelectedNode?.AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.AutomationFocusChangedEventId);
>, but I see described problem again.

Please open a dedicated issue for this problem.  Does the same reproduce in JAWS? Does JAWS announce selection as the treeview is focused for the first time?

I would rather not show narrator focus on the first access than create an accessible object unnecessarily

2022-01-11 03:48 UTC, Tanya-Solyanik approved these changes
Looks good, please send to testing!

2022-01-11 09:50 UTC, DmitryGorokhov commented
I've sent it for testing.

2022-01-12 09:29 UTC, DmitryGorokhov commented
One regression and one not regression have been found. So still WIP status, I am working on this.

2022-01-27 11:25 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
> +            SelectedNode?.AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.AutomationFocusChangedEventId);
Created an out-of-scope issue: #6559

2022-01-27 11:29 UTC, DmitryGorokhov commented
We decided open out of scope issue for regression, because this error reproduces only in the Inspect. Narrator works good and tree view has correct hierarchy in AI. Created issue #6558

2022-01-27 13:23 UTC, WPMGPRoSToTeMa requested changes

2022-01-27 13:23 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +
Sorry for the late, but I've found how to fix #6558 - you need to provide an implementation for `ElementProviderFromPoint` method. It is usually implemented to call `HitTest`:
```suggestion

            internal override IRawElementProviderFragment? ElementProviderFromPoint(double x, double y)
                => HitTest((int)x, (int)y) ?? base.ElementProviderFromPoint(x, y);

```

2022-01-27 15:39 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +
Just in time, before closing it :) Great investigation! Thanks, it works

2022-01-27 15:42 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +
It doesn't affect the above described problem with focus on selected node first time, I've checked it

2022-01-27 15:43 UTC, DmitryGorokhov commented
Send it for retest

2022-01-27 15:53 UTC, WPMGPRoSToTeMa approved these changes
🚀

2022-01-28 15:45 UTC, DmitryGorokhov commented
CTI has retested it. Regression issue was fixed and no new issue was found. So, I close #6558.

2022-01-28 17:44 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +            public TreeNodeAccessibleObject(TreeNode owningTreeNode, TreeView owningTreeView) : base()
Fixed in pr #6571

2022-01-28 23:52 UTC, RussKie submitted a review, later dismissed

2022-02-08 22:56 UTC, Tanya-Solyanik reviewed
Please see my questions, otherwise looks good.

2022-02-08 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    UiaCore.NavigateDirection.NextSibling => _owningTreeNode.NextNode?.AccessibilityObject,
nit: I would prefer if the whole statement were formatted uniformly. I.e. all `=>` on the  new line., like the first 3 cases

2022-02-08 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    UiaCore.UIA.HasKeyboardFocusPropertyId => (State & AccessibleStates.Focused) == AccessibleStates.Focused,
nit: move `=>` to new lines

2022-02-08 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    UiaCore.UIA.IsEnabledPropertyId => _owningTreeView.Enabled,
FYI - @ArtemTatarinov potential conflict with your PRs

2022-02-08 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    UiaCore.UIA.ValuePatternId when _owningTreeView.LabelEdit => true,
Do we get `TextPatterns` supported for treeviews with `LabelEdit` style?

2022-02-08 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                set => _owningTreeNode.Text = value;
This setter does not propagate new name value to the system accessible object. Is this because there is no system acc obj?

I don't think it's correct to modify the node text.

2022-02-08 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                set => _owningTreeNode.Text = value;
Is this correct that we are overriding the text?

2022-02-08 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    UiaCore.UIA.HasKeyboardFocusPropertyId => _owningTreeView.Nodes.Count == 0,
I assume that if there were nodes in the collection then one of them would steal the focus? What about a disabled control? Would it still get focus?

2022-02-08 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    UiaCore.UIA.HasKeyboardFocusPropertyId => _owningTreeView.Nodes.Count == 0,
Why is this code not looking at AccessibleState.Focused

2022-02-08 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    return new[] {  selected };
nit: you have 2 spaces between the opening brace and the contect.

2022-02-17 09:56 UTC, vladimir-krestov reviewed
Looks good!

2022-02-17 09:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    UiaCore.UIA.ValuePatternId when _owningTreeView.LabelEdit => true,
The native edit field of a TreeView node supports native TextPattern and works well

2022-02-17 09:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                set => _owningTreeNode.Text = value;
A user can't set `Name` for TreeNode AO, so I would keep the following:
```cs
public override string? Name => _owningTreeNode.Text;
```

2022-02-17 09:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    AccessibleStates state = AccessibleStates.Selectable | AccessibleStates.Focusable;
Please check, if a node really selectable and focusable if its TreeView control is disabled. If no, please add a condition

2022-02-17 09:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                if (_owningTreeNode.IsVisible)
Please add a little comment, that we don't need to scroll if the item is visible.
Just for there to be no doubt

2022-02-17 09:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                set => _owningTreeNode.Text = value;
I think, no. Anyway, a user can't change it. So I would keep it like this:
```cs
 public override string? Value => _owningTreeNode.Text;
```

2022-02-17 09:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    AccessibleStates state = AccessibleStates.Focusable;
Please add `Enabled` check for it

2022-02-17 09:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +            internal override bool IsSelectionRequired => true;
I'm not sure. If a TreeView can have noone selected item, it's may not be true. Please check it.

2022-02-17 09:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
> +            var expected = UiaCore.UIA.TreeItemControlTypeId;
`var`: please explicit some `vars` in tests, if types are unclear.

2022-02-21 16:38 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
> +                    AccessibleStates state = AccessibleStates.Selectable | AccessibleStates.Focusable;
Tree Node is really selectable and focusable and it is "unavailable" in this case. So I will add this state.

![2](https://user-images.githubusercontent.com/58004471/154995674-ecee74ee-afb0-4fab-af7a-738a9c569f9c.png)

2022-02-21 16:40 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    AccessibleStates state = AccessibleStates.Focusable;
Tree View is "unavailable" too, if it is disabled.

![1](https://user-images.githubusercontent.com/58004471/154996044-001c94ea-8673-4bd8-b9e7-728a9f5184aa.png)

2022-02-21 16:41 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +            internal override bool IsSelectionRequired => true;
Yes, this is wrong. It must be false, if it has no items. Thanks

![1](https://user-images.githubusercontent.com/58004471/154996188-5ef62bde-651e-490f-bca9-5504fe5e83f5.png)

2022-02-22 12:23 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
> +                    UiaCore.UIA.HasKeyboardFocusPropertyId => _owningTreeView.Nodes.Count == 0,
If control is disable, it has no keyboard focus, so I will rework it.

> Why is this code not looking at AccessibleState.Focused
I don't always see these properties match. May be they are not related in this case.

2022-02-22 19:54 UTC, Tanya-Solyanik submitted a review, later dismissed
Looks good. 
@DmitryGorokhov  - please investigate if providers are disconnected properly on containing window close. @ArtemTatarinov might be able to help with this investigation.
@vladimir-krestov  - looks like all you comments were addressed, please take another look.

2022-03-08 22:41 UTC, merged

2022-04-06 10:03 UTC, Cassie-Li01 commented
Verified on build dotnet-sdk-7.0.100-preview.3.22179.4-win-x64, screenshot as below.
TreeView:
![image](https://user-images.githubusercontent.com/96758262/161945214-99bb0070-54af-4623-b781-456e834bdb81.png)
Default TreeNode:
![image](https://user-images.githubusercontent.com/96758262/161945333-dc568ea3-6b88-4394-bd9c-3285f6b54b4e.png)
Expanded TreeNode:
![image](https://user-images.githubusercontent.com/96758262/161945421-9dd69678-e3ac-4e92-bd99-ece7148dc014.png)
Leaf TreeNode: 
![image](https://user-images.githubusercontent.com/96758262/161945516-4b26db75-dccb-4a49-9573-c8e2d4a63a26.png)
CheckBox TreeNode: 
![image](https://user-images.githubusercontent.com/96758262/161945566-9af6b12c-93a3-4921-8ba7-c9f16aac0f14.png)