Enable nullability in ContainerInfo
dotnet/winforms pull request #6473
Opened 2022-01-06 10:44 UTC by gpetrou

## Proposed changes

- Enable nullability in ContainerInfo.

2022-01-10 20:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ContainerInfo.cs
> +                    if (HasChildWithAbsolutePositioning && _childInfo is not null)
I'm not sure that it's valid to have `_childInfo == null` when we know that we have ` _countFixedChildren > 0`.  I would prefer an exception in this case.

2022-01-14 21:50 UTC, dreddy-work submitted a review, later dismissed

2022-01-17 04:43 UTC, RussKie requested changes

2022-01-17 04:43 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ContainerInfo.cs
> +                        for (int i = 0; i < _childInfo!.Length; i++)
Please don't do this.

I believe this should address this:
```cs
            [MemberNotNullWhen(true, nameof(_childInfo))]
            public bool HasChildWithAbsolutePositioning
            {
                get { return _countFixedChildren > 0; }
            }
```

2022-01-17 06:13 UTC, RussKie submitted a review, later dismissed

2022-01-17 06:49 UTC, RussKie commented
/azp run

2022-01-19 16:34 UTC, gpetrou commented
@RussKie perhaps you need to manually merge this since the PrintPreviewDialogTests cause too many failures?

2022-01-28 18:43 UTC, merged