Fixing incorrect rendering of button rounded borders for Windows 11
dotnet/winforms pull request #6497
Opened 2022-01-13 12:12 UTC by SergeySmirnov-Akvelon

Fixes #6187

## Proposed changes
- The issue is reproduced because we have always drawn rectangular borders, although Windows 11 uses rounded borders.
- Added logic for drawing a rounded border.
- Added logic to draw a line at the bottom to simulate a gradient effect

## Customer Impact
**Before fix:**
![image](https://user-images.githubusercontent.com/23376742/149326045-cf625099-03e1-45f3-b17d-40df5bd8635c.png)

**After fix:**
![image](https://user-images.githubusercontent.com/23376742/149326114-c0e4dcf7-6ab9-47ae-96b0-c1c7741b718f.png)
![image](https://user-images.githubusercontent.com/23376742/149326175-7c0c01e8-9880-4fa4-b0ac-c2e643781ab5.png)
![image](https://user-images.githubusercontent.com/23376742/149328158-d9d9e618-49ac-4918-a5ae-4f7e0d6d3ff4.png)

## Regression impact
**Before fix:**
Rendering 500 standard buttons on local machine takes an average of **2208** seconds.
Rendering 500 standard buttons on a virtual machine takes an average of **1.999** seconds.

**After fix:**
Rendering 500 standard buttons on local machine takes an average of **2229** seconds.
Rendering 500 standard buttons on a virtual machine takes an average of **1.879** seconds.

## Regression? 
- Yes (from #6059)

## Risk
- Minimal

## Test environment(s) 
- Microsoft Windows [Version 10.0.22000.434]
- .NET Core SDK: 7.0.0-alpha.1.22061.11

2022-01-13 18:13 UTC, merriemcgaw commented
How are you isolating this to Win11 machines? That would be required for both Core and NetFX.

2022-01-13 18:14 UTC, merriemcgaw commented
@JeremyKuhne can you take a look at this one too?

2022-01-13 19:07 UTC, Tanya-Solyanik reviewed
I added some nits, and I'm not clear why buttons with custom back color are excluded, otherwise looks good. 

Do we have additional issues about selected/focused/etc borders?

2022-01-13 19:07 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
> +        internal static void DrawRoundedRectangle(this Graphics graphics, Pen pen, Rectangle bounds, int cornerRadius)
Would be nice to have "windows11" in the function name or in a comment

2022-01-13 19:07 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonStandardAdapter.cs
> +                && Control.BackColor == SystemColors.Control)
How do buttons with non-default background look?

2022-01-13 19:10 UTC, Tanya-Solyanik commented
@merriemcgaw  -
>How are you isolating this to Win11 machines? That would be required for both Core and NetFX.

We look up the version using windows API that does not depend on the manifest version

2022-01-13 21:07 UTC, JeremyKuhne requested changes

2022-01-13 21:07 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonStandardAdapter.cs
> +                && ButtonRenderer.RenderWithVisualStyles
Why are you adding all these extra cases to `DrawBorderSimple`? Shouldn't they be included with `if (OsVersion.IsWindows11_OrGreater)`?

2022-01-13 21:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
> +        private static GraphicsPath RoundedRect(Rectangle bounds, int radius)
If the only caller is DrawRoundedRectangle it shouldn't be a separate method. Move it inline for clarity and to avoid the extra call frame.

2022-01-13 21:24 UTC, JeremyKuhne commented
This needs a lot more testing and documentation. There should be screenshots of Windows 11 buttons at different DPIs, with different high contrast settings, and anything else that can be modified with comparisons against our implementation. I'd want to see actual color values as well.

2022-01-13 21:39 UTC, JeremyKuhne commented
Was our initial rendering actually different than what Windows draws directly? If not, I don't like the idea of trying to "improve" Windows rendering- we're just asking for major headaches trying to keep in line with Windows changes. If they don't render at a contrast that meets accessibility guidelines that shouldn't be something we should be "patching".

I'll try and get some shots of actual direct Win32 renders and add them.

2022-01-14 08:24 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs
> +        protected const float ButtonBottomBorderDarkerOffset = 0.6f;
This coefficient was added to simulate the original gradient. The contrast ratio in the original is **1.252**, we have a contrast ratio of **1.253**.

2022-01-14 10:12 UTC, SergeySmirnov-Akvelon commented
> How are you isolating this to Win11 machines? That would be required for both Core and NetFX.

Hi @merriemcgaw. We use the `OsVersion.IsWindows11_OrGreater` flag to check the operating system. Depending on the value of the flag, we draw either rectangular or rounded borders. It is available in both frameworks.

2022-01-14 13:57 UTC, SergeySmirnov-Akvelon commented
Thanks @Tanya-Solyanik  for your questions.

> I added some nits, and I'm not clear why buttons with custom back color are excluded, otherwise looks good.

By default, we have the following colors for the system button border:
Windows 10 - RGB(173, 173, 173)
Windows 11 - RGB(201, 201, 201)

These colors are not system colors. Should we keep the border colors stored in properties? Or should we get the border colors each time from the button to ensure it's correct?

If we want to support custom colors, then what color should we rely on when calculating a new color for the button border? `Parent.BackColor` or `Button.BackColor`?

> Do we have additional issues about selected/focused/etc borders?

By default, the **selected** and **hovered** button borders have acceptable contrast on Windows 10 and Windows 11.

For **Windows 10**:
![image](https://user-images.githubusercontent.com/23376742/149520869-060bef75-a21c-4822-a30a-9a7953e9eff7.png)
**Selected** state (yellow rectangle): `Button.BackColor` - **3.44**; `Form.BackColor` - **3.947**
**Hovered** state (rose rectangle): `Button.BackColor` - **3.921**; `Form.BackColor` - **3.947**

For **Windows 11**:
![image](https://user-images.githubusercontent.com/23376742/149522539-200f7fae-abd3-4d09-a2b2-a6e886199d15.png)
**Selected** state (yellow rectangle): `Button.BackColor` - **4.338**; `Form.BackColor` - **3.973**
**Hovered** state (rose rectangle): `Button.BackColor` - **3.559**; `Form.BackColor` - **3.973**

By default, the checked and pressed button borders have low contrast on Windows 11.
For **Windows 10**:
![image](https://user-images.githubusercontent.com/23376742/149524191-61088f54-f0b8-4bce-8f15-96e8f3237411.png)
**Unchecked** state: `Button.BackColor` - **3.02**; `Form.BackColor` - **3.465**
**Checked** state: `Button.BackColor` - **5.867**; `Form.BackColor` - **3.754**
**Pressed** state: `Button.BackColor` - **3.921**; `Form.BackColor` - **3.947**

For **Windows 11**:
![image](https://user-images.githubusercontent.com/23376742/149523425-f1ad3adc-07b5-4a5d-84b6-9a44cce50ad7.png)
**Unchecked** state: `Button.BackColor` - **3.783**; `Form.BackColor` - **3.465**
**Checked** state: `Button.BackColor` - **1.167**; `Form.BackColor` - **1.136**
**Pressed** state: `Button.BackColor` - **1.167**; `Form.BackColor` - **1.136**

I plan on Monday to fix pressed and checked states for Windows 11

2022-02-01 20:58 UTC, Tanya-Solyanik commented
@SergeySmirnov-Akvelon  - I thought we decided to close this PR and pursue a windows fix?

2022-02-09 06:26 UTC, closed without merging