Fixing announcement of information about hidden columns and rows for DGV
dotnet/winforms pull request #6498
Opened 2022-01-13 12:51 UTC by SergeySmirnov-Akvelon

Fixes #6471

## Proposed changes
- The issue is reproduced because properties `RowCount` and `ColumnCount` do not take into account that columns and rows can be hidden. In addition, other properties also have problems if `DataGridView` elements are hidden.
- Fixed methods and properties of `DataGridViewAccessibleObject`.
- Unit tests have been added as a check to ensure that methods and properties work correctly even if rows/columns are hidden.

## Customer Impact
**Before fix:**
![image](https://user-images.githubusercontent.com/23376742/149331974-8263eda4-ee7f-49ac-83e8-cf39f44fd309.png)
 
**After fix:** 
![image](https://user-images.githubusercontent.com/23376742/149333251-949b9f9f-04c9-4a70-bdaa-83be8a97d76b.png)

## Regression? 
- No

## Risk
- Minimal

## Test methodology 
- CTI team
- Unit tests

## Accessibility testing  
- Inspect
- Narrator
- Accessibility Insights
 
## Test environment(s) 
- Microsoft Windows [Version 10.0.19041.1348]
- .NET Core SDK: 7.0.0-alpha.1.22061.11

2022-01-31 10:53 UTC, vladimir-krestov approved these changes
Approved, didn't find any critical things ✔️

2022-01-31 10:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.cs
> -                    case AccessibleNavigation.FirstChild:
Why did you romoved this?

2022-01-31 10:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.cs
> +                    // Add 1 because the top header row accessible object has the top left header cell accessible object at the beginning
Is it better?
```suggestion
                    // Subtract 1 because the top header row accessible object has the top left header cell accessible object at the beginning
```

2022-01-31 10:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewAccessibleObjectTests.cs
> +        }
Please add IsHandleCreated checks in all your tests

2022-01-31 10:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowAccessibleObjectTests.cs
> +        [Fact]
Looks like we need [WinformsFact] because we create a control

2022-01-31 13:11 UTC, WPMGPRoSToTeMa reviewed
Haven't reviewed the unit-tests part yet.

2022-01-31 13:11 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
> +                            return owner.DataGridView.AccessibilityObject.GetChild(ActualDisplayIndex + 1);
❗  `ActualDisplayIndex` may potentially return `-1` and in this case we will get `0` here.

2022-01-31 13:11 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.cs
> +                        : Owner.DataGridView.Columns.GetActualDisplayIndex(Owner.OwningColumn);
ditto to invert the condition.

2022-01-31 13:11 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
> +                => _owner?.OwningColumn is null || _owner.OwningColumn.Visible is false || _owner.DataGridView is null
ditto: consider invert the condition and `Visible` is not nullable.

2022-01-31 13:11 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
> +                => _owner?.OwningRow is null || _owner.OwningRow.Visible is false || _owner.DataGridView is null
ditto: consider invert the condition and `Visible` is not nullable.

2022-01-31 13:11 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
> +                            : null;
Consider using a variable to not call `GetChildCount` twice.

2022-02-01 07:33 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
> +                if (index > GetChildCount() - 1)
I find it strange that we're throwing `Exceptions` here because in most of such cases we return `null` if the `Index` doesn't match an existing element.

For example, the `DataGridView` does not throw `Exceptions` if the `Index` is greater than the number of elements, but here we throw an `Exception`, but not because we have a special handler, but because we get an `Exception` from the `Control`.

2022-02-01 08:09 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
> +                        ? -1
If the `DataGridViewRow` does not have a `DataGridView`, it returns -1 as an `Index`. Perhaps we can replace this line with:
`int rowIndex = _owner.DataGridView?.Rows.GetActualDisplayIndex(_owner.OwningRow) ?? -1;`
or
`int rowIndex = _owner.DataGridView?.Rows.GetActualDisplayIndex(_owner.OwningRow) ?? _owner.OwningRow.Index;`

2022-02-01 08:29 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
> +                            : null;
Perhaps this is a contrived case. But if the user caches an `AccessibleObject` for the `DataGridViewTopRow`, makes all `DataGridViewColumns` invisible, and tries to get the first or last child, an `Exception` will be returned instead of `null`

2022-02-01 09:16 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.cs
> -                    case AccessibleNavigation.FirstChild:
The ColumnHeader has no children in our implementation. In addition, the old code, if the RowHeaders are hidden, will return the first ColumnHeader as a child of the first ColumnHeader. The current logic seems redundant and incorrect.

2022-02-01 17:00 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
> +                => _owner?.OwningRow?.Visible is true && _owner.DataGridView is not null
Consider using a nested property pattern:
```suggestion
                => _owner is { OwningRow.Visible: true, DataGridView: { } }
```

2022-02-02 00:04 UTC, JeremyKuhne requested changes
I'd follow along with the enum naming (VisibleIndex) and add XML comments for clarity.

2022-02-02 00:04 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.cs
> +                => Owner is { OwningColumn: { }, DataGridView: { } }
This syntax is pretty opaque. I'd prefer clearer `Owner?.DataGridView is not null && Owner?.OwningColumn is not null`.

2022-02-02 00:04 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs
> +        internal int GetActualDisplayIndex(DataGridViewColumn column)
As elsewhere, `GetVisibleIndex()` and comments.

2022-02-02 00:04 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
> +                => _owner?.OwningRow?.Visible is true && _owner.DataGridView is not null
I'm not keen on that syntax. @RussKie / @dreddy-work

2022-02-02 07:22 UTC, SergeySmirnov-Akvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
> +                => owner is { DataGridView: { } }
This check is equivalent to: `owner?.DataGridView is not null`

2022-02-02 23:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
> +                => _owner?.OwningRow?.Visible is true && _owner.DataGridView is not null
I don't mind this syntax. I don't really like it where it is used as a replacement for null check, but in this situation I think it's ok.

2022-02-02 23:35 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
> +                => owner is { DataGridView: { } }
As per my comment here https://github.com/dotnet/winforms/pull/6498/files#r798100886 I don't mind it in compound scenarios, but in situations like this `owner?.DataGridView is not null` I prefer.

2022-02-04 01:45 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
> +                => _owner?.OwningRow?.Visible is true && _owner.DataGridView is not null
I don't think it adds value for the extra cognitive overhead.

2022-02-04 01:45 UTC, JeremyKuhne approved these changes

2022-02-04 03:21 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
> +                => _owner?.OwningRow?.Visible is true && _owner.DataGridView is not null
I agree, it takes time to get used to. This goes for many Rsolyn features we saw over the years. 😄 
I don't have a particularly strong preference in this case (unlike direct null check), so happy either way.

2022-02-04 03:22 UTC, RussKie approved these changes

2022-02-04 03:23 UTC, RussKie commented
@SergeySmirnov-Akvelon has this been tested?

2022-02-04 12:38 UTC, SergeySmirnov-Akvelon commented
@RussKie, I sent this to the CTI team. I hope they test it on Monday

2022-02-07 09:02 UTC, Olina-Zhang commented
Tested this PR with no new issue found.

2022-02-07 17:33 UTC, merged

2022-02-07 20:22 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs
> +            return dataGridViewColumn?.Index ?? -1;
nit: name this method similarly to the corresponding method for row collection (remove the word Actual)

2022-02-07 20:28 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
> +                    string name = string.Format(SR.DataGridView_AccDataGridViewCellName, _owner.OwningColumn.HeaderText, rowIndex);
This line will generate name "column A row -1" in corner cases....