Replaces deprecated build image
dotnet/winforms pull request #6526
Opened 2022-01-20 01:09 UTC by RussKie

2022-01-20 01:47 UTC, mmitche approved these changes

2022-01-20 01:49 UTC, mmitche commented on azure-pipelines.yml
> +          vmImage: windows-2019
Actually, this needs to be replaced with the 1ES pool like the email indicated.

2022-01-20 01:49 UTC, mmitche commented on azure-pipelines.yml
> +          vmImage: windows-2019
name: NetCore1ESPool-Internal
demands: ImageOverride -equals Build.Server.Amd64.VS2019

2022-01-20 01:50 UTC, mmitche requested changes
We should use the 1ES pools here.

2022-01-25 05:17 UTC, RussKie commented on azure-pipelines.yml
> +          vmImage: windows-2019
Updated

2022-01-25 16:15 UTC, mmitche approved these changes

2022-02-02 01:30 UTC, merged