Enable nullability in ButtonBase
dotnet/winforms pull request #6545
Opened 2022-01-25 06:13 UTC by gpetrou

## Proposed changes

- Enable nullability in ButtonBase.

2022-01-31 03:16 UTC, RussKie requested changes

2022-01-31 03:16 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                ImageAnimator.UpdateFrames(Image!);
This at least deserves a comment that [`ImageAnimator`](https://github.com/dotnet/runtime/blob/bc6d349ecd72eec162f0532e6b6218fdbaa07ddb/src/libraries/System.Drawing.Common/src/System/Drawing/ImageAnimator.cs#L103-L108) isn't NRTA'ed, and accepts nulls.

So maybe we should just add a null check and avoid the bang operator at all.

2022-01-31 03:16 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                _imageIndex.Key = value!;
`Indexer` type isn't annotated correctly, as `Key` accepts nulls:
https://github.com/dotnet/winforms/blob/6365af0d23685c467a74bbfeb9363d3ddec3d50c/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Indexer.cs#L29-L35

2022-01-31 15:15 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                ImageAnimator.UpdateFrames(Image!);
I see in https://github.com/dotnet/runtime/blob/7d30da68a91d1cced11a0302cc7a8aa9a0ea9af1/src/libraries/System.Drawing.Common/src/System/Drawing/ImageAnimator.cs#L103 there is already a null check and that nullability is enabled in https://github.com/dotnet/runtime/blob/7d30da68a91d1cced11a0302cc7a8aa9a0ea9af1/src/libraries/System.Drawing.Common/src/System/Drawing/ImageAnimator.cs#L103.

2022-01-31 22:58 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                ImageAnimator.UpdateFrames(Image!);
The actual type doesn't look like it was annotated (correctly). @jeffhandley would you know the story behind it?

2022-02-02 06:36 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                ImageAnimator.UpdateFrames(Image!);
Perhaps I should just add the null check on our side to unblock this PR?

2022-02-03 09:57 UTC, jeffhandley commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                ImageAnimator.UpdateFrames(Image!);
Sorry; I'm overlooking the issue. It looks to me like ImageAnimator.UpdateFrames expects a non-null Image, but it gracefully no-ops if null is passed in; that seems OK to me--is there an issue with that approach?

My recommendation would be to add the null check on this call site.

2022-02-07 21:32 UTC, dreddy-work approved these changes
LGTM.

2022-02-08 18:01 UTC, merged

2022-02-09 01:09 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                ImageAnimator.UpdateFrames(Image!);
@jeffhandley my understanding of NRTA is that if a method accepts nulls (like in this situation) it should be annotated as nullable.

2022-02-28 06:24 UTC, jeffhandley commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                ImageAnimator.UpdateFrames(Image!);
> @jeffhandley my understanding of NRTA is that if a method accepts nulls (like in this situation) it should be annotated as nullable.

Sorry for the delayed response, @RussKie. OK, I'm convinced. :wink:. I'll submit a PR to change it to `public static void ImageAnimator.UpdateFrames(Image? image)`.

2022-02-28 07:34 UTC, jeffhandley commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                ImageAnimator.UpdateFrames(Image!);
Created https://github.com/dotnet/runtime/pull/65949 to change the annotation.

2022-02-28 07:35 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +                ImageAnimator.UpdateFrames(Image!);
Thank you!