Remove using empty base AO ctor
dotnet/winforms pull request #6571
Opened 2022-01-28 17:42 UTC by DmitryGorokhov

Fixes comment from pr #6432 

## Proposed changes

- Remove call empty ctor of Accessible Object class in inherited classes.

## Customer Impact

- No

## Regression? 

- No

## Risk

- No

2022-01-28 23:49 UTC, RussKie commented
/azp run

2022-01-29 14:11 UTC, WPMGPRoSToTeMa approved these changes

2022-01-29 14:11 UTC, WPMGPRoSToTeMa commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
>              }
Can we also remove the parameterless constructor?

2022-01-29 14:12 UTC, WPMGPRoSToTeMa commented
It's safe to remove `: base()` even when it calls non-empty parameterless constructor because it's called implicitly:
> In a derived class, if a base-class constructor is not called explicitly by using the base keyword, the parameterless constructor, if there is one, is called implicitly.
https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/using-constructors

The only question whether we want be explicit about calling base parameterless constructors or not.

cc: @RussKie

2022-01-29 14:14 UTC, vladimir-krestov submitted a review, later dismissed
Approved ✔️

2022-01-31 03:48 UTC, RussKie commented
The default .ctors are called implicitly if those are present and no other .ctor is explicitly called.

2022-01-31 03:48 UTC, RussKie reviewed
:shipit: once the comment is addressed.

2022-01-31 12:35 UTC, WPMGPRoSToTeMa commented
> The default .ctors are called implicitly if those are present and no other .ctor is explicitly called.

I mean is there a code style rule that will warn when the base parameterless .ctor is called explicitly? (to avoid this in future)

2022-01-31 18:17 UTC, vladimir-krestov submitted a review, later dismissed

2022-01-31 21:53 UTC, Tanya-Solyanik approved these changes

2022-01-31 21:55 UTC, Tanya-Solyanik commented
/azp run

2022-01-31 22:38 UTC, RussKie commented
> > The default .ctors are called implicitly if those are present and no other .ctor is explicitly called.
> 
> I mean is there a code style rule that will warn when the base parameterless .ctor is called explicitly? (to avoid this in future)

The compiler will tell you :)

If there is no .ctor defined - one is implicitly added and called. If there is a non-default .ctor (i.e. with parameters) - it will always be called, no default .ctor will be generated.

2022-01-31 22:39 UTC, RussKie requested changes

2022-01-31 22:39 UTC, RussKie commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> -System.Windows.Forms.DataGridView.DataGridViewTopRowAccessibleObject.DataGridViewTopRowAccessibleObject() -> void
We must not alter the public API surface. See https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridview.datagridviewtoprowaccessibleobject.-ctor

2022-01-31 23:13 UTC, WPMGPRoSToTeMa commented
> 
> The compiler will tell you :)
> 
> If there is no .ctor defined - one is implicitly added and called. If there is a non-default .ctor (i.e. with parameters) - it will always be called, no default .ctor will be generated.

This is what I actually meant:
```
public DataGridViewTopRowAccessibleObject() : base()
                                              ^~~~~~
                                              |
                                              Warning: base parameterless constructor is called explicitly, please don't do that
```
And as I can see there is no rule for that :(

2022-02-01 06:21 UTC, DmitryGorokhov commented on src/System.Windows.Forms/src/PublicAPI.Shipped.txt
> -System.Windows.Forms.DataGridView.DataGridViewTopRowAccessibleObject.DataGridViewTopRowAccessibleObject() -> void
Ok, restored paramless ctor and tis file. Thanks

2022-02-01 11:02 UTC, RussKie approved these changes

2022-02-01 11:27 UTC, merged