Add support for DropTarget drag images and drop descriptions
dotnet/winforms pull request #6576
Opened 2022-01-29 20:33 UTC by willibrandon

Allow drop targets to display the drag image while the cursor is over the target and add support for drop description icons and text.

A possible implementation for #5884.

## Proposed changes

- Keep the scope to just drop targets with support for drop icons and text, for now.

- Maintain the default DropTarget behavior with a last flag.

- If the application specifies a DropIcon other than DropIcon.Invalid (default), display the drag image, drop icon, and text.

- Add a DragDropHelper class to interface with the drag-image manager and provide methods to get and set the drop description.

- Add a DragDrop functional test form to WinformsControlsTest with files for testing drag-and-drop operations.

## Customer Impact

- An improved drag-and-drop experience.

## Regression? 

- No

## Risk

- I haven't had to work with pointers or allocate/de-allocate memory in the last 13 years so the risk is quite high. Please do not assume that I know what I'm doing. I've studied the documentation as closely as possible and I believe I've done things correctly but there are a lot of topics covered here and I could be making some incorrect assumptions in certain cases. A real Windows programmer should take a look at this to make sure there isn't anything glaringly wrong.

## Screenshots 

### Before

TODO

### After

TODO

## Test methodology 

- Ran unit and integration tests.
- Added a DragDrop functional test form to WinformsControlsTest with files for testing drag-and-drop operations.
- TODO: [Add UIIntegration tests](https://github.com/dotnet/winforms/issues/5884#issuecomment-998387359) as suggested by @RussKie .

## Accessibility testing  

TODO
 

## Test environment(s) 

-  .NET 6.0.1

2022-01-30 03:37 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                HRESULT hr = Ole32.CoCreateInstance(
Is it possible that you implement COM object creation using ComWrappers, so the code would be trimmable and behave well in AOT scenarios? Examples how it is done for RCW and CCW related to FoledBrowserDialog is here https://github.com/dotnet/winforms/pull/5319 . Other example for CCW which easier to understand is https://github.com/dotnet/winforms/pull/6574 (probably you need create RCW) and I do not have self-contained example yet.

If that seems to be too complicated, I can make change which enable trimming after this PR ends.

2022-01-30 03:53 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                HRESULT hr = Ole32.CoCreateInstance(
I was just looking at those PRs. I can learn how to implement COM object creation using ComWrappers and I'll take a closer look at your examples now.

2022-01-30 06:00 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                HRESULT hr = Ole32.CoCreateInstance(
@kant2002 - Oh I see now yeah that is a stretch for me. I might need your help. I'll see if I can bring myself up to speed.

2022-01-30 07:11 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                HRESULT hr = Ole32.CoCreateInstance(
I think it is better work in pieces. When you pass code review for this change we can start follow-up PR with the changes for ComWrappers. I utilize my project WinFormsComInterop for boilerplate codegen. Mostly I copy what my source gen produce and augment based on this project code style. I wrote article about how to write ComWrappers from scratch https://codevision.medium.com/using-com-in-nativeaot-131dbc0d559e I'm mostly care about NativeAOT, but ComWrappers is enabler technology for R2R as well, so article can be directly applied here.

2022-02-20 23:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +        private static bool TryGetDropTargetHelper(out IDropTargetHelper? dropTargetHelper)
```suggestion
        private static bool TryGetDropTargetHelper([NotNullWhen(true)] out IDropTargetHelper? dropTargetHelper)
```

2022-02-20 23:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                || dropTargetHelper is null)
```suggestion
            if (!TryGetDropTargetHelper(out IDropTargetHelper? dropTargetHelper))
```

2022-02-20 23:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                }
```suggestion
                hr.ThrowIfFailed()
```

2022-02-20 23:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                if (dropTargetHelper is not null)
How could this be null?

2022-02-20 23:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                if (dataObject.QueryGetData(ref formatEtc) != (int)HRESULT.S_OK)
Should we be using `hr.Failed()` instead?

2022-02-20 23:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                Kernel32.GlobalUnlock(medium.unionmember);
We have two exist scenarios after we lock. Should we call unlock in the finally clause?

2022-02-20 23:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                return false;
Incorrect null annotations. Also don't skip on curlies.
```suggestion
        public static bool GetDropDescriptionPresent(IComDataObject? dataObject)
        {
            if (dataObject is null)
            {
                return false;
            }
```

2022-02-24 02:46 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                if (dropTargetHelper is not null)
Good point. I think it's my inexperience with COM and me not being exactly sure how the COM method calls could fail. I also could be overly paranoid since the next line calls Marshal.FinalReleaseComObject(object o) which can throw an ArgumentNullException. I agree, the check probably overkill.

2022-02-25 02:45 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                if (dataObject.QueryGetData(ref formatEtc) != (int)HRESULT.S_OK)
`QueryGetData(ref FORMATETC format)` returns `S_OK` if a subsequent call to `GetData(ref FORMATETC format, out STGMEDIUM medium)` would most likely succeed. This call to _IDataObject::QueryGetData_ checks for the existence of a drop description format in the data object prior to obtaining it using _IDataObject::GetData_. Any return value other than `S_OK` and I assume a drop description format is not present in the data object and bail out. Is it correct that hr.Failed() is hr < 0?

2022-02-25 03:00 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                if (dataObject.QueryGetData(ref formatEtc) != (int)HRESULT.S_OK)
If the result is < 0 I believe we're still doing the right thing by bailing out and returning false.

2022-02-25 03:53 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                Kernel32.GlobalUnlock(medium.unionmember);
I had the same thought. This is an area I could use some help in.

2022-02-25 04:10 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                Kernel32.GlobalUnlock(medium.unionmember);
It was tough for me to get to this point and the error handling so far has been an afterthought. I need to take a closer look at the docs and precisely how we handle this in other areas.

2022-03-06 06:45 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                HRESULT hr = Ole32.CoCreateInstance(
@kant2002 - I've taken a look at your article and ComWrappers samples, as well as the ComWrappers documentation, and it makes sense now. I agree, we should implement the COM object creation using ComWrappers if possible so that it is AOT-friendly. I think it is worth including in this PR if possible, or as a follow-up PR. I'll start with IDropTargetHelper creation using ComWrappers and will report back the results.

2022-03-06 14:13 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                HRESULT hr = Ole32.CoCreateInstance(
I think functionality of this PR valuable as it is and follow up PR for ComWrappers would be better, since the longer code in PR, the more maintenance potentially needed from you (rebase, re-remembering things). ComWrappers is slightly different mentality, rather mechanical changes if you like, and I think adding it here can pollute review. But that's my take on things. Maybe team does not care that much about split.

2022-03-06 18:06 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                HRESULT hr = Ole32.CoCreateInstance(
I agree. Lets do it in a follow up PR and I'm looking forward to it.

2022-03-07 02:21 UTC, RussKie reviewed
👍

2022-03-07 02:21 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.CLSID.cs
> +        internal static Guid DragDropHelper = new Guid(0x4657278A, 0x411B, 0x11D2, 0x83, 0x9A, 0x0, 0xC0, 0x4F, 0xD9, 0x18, 0xD0);
Please keep in alphabetical order

2022-03-10 05:45 UTC, willibrandon commented
/azp help

2022-03-10 11:00 UTC, willibrandon reviewed
Consider including the cursor offset in the proposal.

2022-03-10 11:22 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                    ptOffset = new Point(0, 0),
It seems to be you are driving API so you can add what you like IMO.

2022-03-10 12:07 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                    ptOffset = new Point(0, 0),
yes i’m writing it here so I don’t forget.

2022-03-15 20:51 UTC, dreddy-work commented
@weltkante appreciate your feedback as well here. I think this will remove the need to expose interfaces publicly as discussed here: https://github.com/dotnet/winforms/issues/457.

@willibrandon, We decided to take this forward and will work with you to get this ready for API review board.

2022-03-15 21:43 UTC, willibrandon commented
> @willibrandon, We decided to take this forward and will work with you to get this ready for API review board.

I have one last part I'd like to include in this draft before taking it to the API review board and would like a chance to first get some feedback from the team. Specifically, specifying the drag image bitmap itself when calling DoDragDrop().

I'll try to get this last part pushed this evening. The only thing holding me up is I need to implement a function to copy an STGMEDIUM since I've previously been using `CopyStgMedium()` in Urlmon.lib and I don't think I'm able to use that function here. I should be able to implement it fairly easily using the [OleDuplicateData](https://docs.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-oleduplicatedata) function and will have some time to work on it this evening.

2022-03-15 21:56 UTC, weltkante commented
Thanks for the ping, looks promising, though I'm surprised this approach works considering WinForms doesn't implement SetData on its DataObject. I'll have a closer look at the proposed implementation and API over the next few days.

2022-03-15 22:08 UTC, willibrandon commented
@weltkante - The **IDataObject::SetData** and **IDataObject::GetDataHere** changes will be included in my next push, hopefully this evening.

2022-03-16 05:47 UTC, willibrandon commented
@weltkante - I've pushed what I believe is the last part required for this issue. I am very interested in what your thoughts are. 

Further work needs to be done in order to add in the support for `RichTextBox.OleCallback` and `ToolStripDropTargetManager`, but this is the gist of it.

2022-03-16 07:47 UTC, willibrandon commented
I'll start looking at `ToolStripItem`, which might have it's own `DoDragDrop` method, and `ToolStripDropTargetManager`.

I have `RichTextBox.OleCallback` mostly figured out although it seems to lack a reliable way for me to know when to call `IDropTargetHelper.DragLeave()` which is needed in certain scenarios in order to hide the drag image and not leave it dangling on the screen when it shouldn't be. There is at least one undesirable scenario with the `RichTextBox` that I haven't completely solved yet.

2022-03-16 08:31 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                dataStore.SetData(dragDropFormat, new KeyValuePair<FORMATETC, STGMEDIUM>(pFormatetcIn, pmedium));
Can we use a specific class for this? Or at least a tuple? KVP feels like misuse, its designed for dictionaries.

Currently the class needs to be BinaryFormatter-serialilzable, but this is to be replaced eventually with a different serialization mechanism when BF is staged out.

Theres also consideration to be done about cross-framework serialization, when you drag between different applications they may be running different versions of .NET - so the more compatibility we get here the better. Having a dedicated class for it seems most flexible to work around emerging issues.

2022-03-17 02:41 UTC, willibrandon commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CopyStgMedium.cs
> +        public static extern int CopyStgMedium(ref STGMEDIUM pcstgmedSrc, ref STGMEDIUM pstgmedDest);
My hope is to implement this method from scratch to eliminate the dependency on _urlmon.dll_ but my initial attempts have failed. I'm unsure how the function handles copying the _DragContext_ data format which is of type `TYMED_ISTREAM`. If someone perhaps has the code for this function and would like to share it, it would save me some time.

2022-03-17 04:37 UTC, willibrandon commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CopyStgMedium.cs
> +        public static extern int CopyStgMedium(ref STGMEDIUM pcstgmedSrc, ref STGMEDIUM pstgmedDest);
Never mind, just got it working and I no longer need to use this function. I'll push an update after a bit more testing.

2022-03-17 05:45 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                dataStore.SetData(dragDropFormat, new KeyValuePair<FORMATETC, STGMEDIUM>(pFormatetcIn, pmedium));
Thank you for your insight and I agree, I picked KVP for no good reason other than I needed to store the format and storage medium together. I also had not considered the serialization cases and dragging between different applications. I'll start looking at this right now and will circle back here with an update or any questions that I might have.

2022-03-17 08:34 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                dataStore.SetData(dragDropFormat, new KeyValuePair<FORMATETC, STGMEDIUM>(pFormatetcIn, pmedium));
Thinking about it again, the situation is probably different than I first assumed. I was only looking at your calling of SetData, but never considered that you were doing so for _implementing_ SetData in the first place, so external callers will go through your implementation first and not directly to the DataStore I think?

So I don't think any (de-)serialization is invoked after all. Sorry for the mistake.

2022-03-18 05:05 UTC, willibrandon commented
I'm taking a look at `ToolStripItem` now. Not sure how I'm going to top the cat demo, we'll see. Any ideas regarding a demo for `ToolStripItem` drag images and drop descriptions would be greatly appreciated, especially a good practical real-use demo.

2022-03-18 05:18 UTC, willibrandon commented
Also, any feedback regarding the `Control.DoDragDrop` methods provided to specify the drag image bitmap is greatly appreciated. This could be expanded on to allow the drag image to specified at other times, such as from a drop target. I chose not to do this just to keep things separate; drop targets **display** drag images and **set** drop descriptions, and drag sources **set** the drag image bitmap itself. In my testing, it's possible to also **set** the drag image bitmap from a drop target in the same way I've done with drop descriptions, however, I feel like that is not how the system was designed to work and so I've kept the responsibilities separate for now. This is where things could get out of control and the next thing you know we are setting drag images and drop descriptions from everywhere and everywhere we look.. rainbow cats.

2022-03-18 06:58 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public DragDropEffects DoDragDrop(object data, DragDropEffects allowedEffects, Bitmap dragImage, Point cursorOffset, bool usingDefaultDragImage)
Allows the application to set the drag image bitmap, cursor offset, and UsingDefaultDragImage flag into the IComDataObject. I'm curious if other people envision setting the drag image bitmap this way.

2022-03-18 07:02 UTC, RussKie reviewed
Incomplete feedback

2022-03-18 09:15 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public DragDropEffects DoDragDrop(object data, DragDropEffects allowedEffects, Bitmap dragImage, Point cursorOffset, bool usingDefaultDragImage)
I would also take this https://github.com/dotnet/winforms/issues/6745 into consideration. Having `object` would be bad for AOT scenarios.

2022-03-19 22:12 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public DragDropEffects DoDragDrop(object data, DragDropEffects allowedEffects, Bitmap dragImage, Point cursorOffset, bool usingDefaultDragImage)
We should coordinate our changes if either one of the APIs are approved. For this change I'm concerned with the proposed additional `Bitmap dragImage, Point cursorOffset, bool usingDefaultDragImage` parameters but if there is a change to the `object` parameter or additional `DoDragDrop` methods added as a result from #6745, I will accommodate for that.

2022-03-19 22:41 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                dataStore.SetData(dragDropFormat, new KeyValuePair<FORMATETC, STGMEDIUM>(pFormatetcIn, pmedium));
Yes, you understand that correctly I think.

When the drag image bitmap is set using DragDropHelper.SetDragImage(), and ultimately when IDragSourceHelper2.InitializeFromBitmap() is called, the drag and drop helper used internally by Windows then starts calling SetData and GetDataHere repeatedly to store and then later retrieve the private drag and drop data formats. I simply store the formats and storage mediums here and then pluck them back out in GetDataHere when the drag and drop helper later asks for them back. You should have seen how I reacted the first time I got it to work.

2022-03-20 03:21 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                dataStore.SetData(dragDropFormat, new KeyValuePair<FORMATETC, STGMEDIUM>(pFormatetcIn, pmedium));
With that said I think you're correct and a specific class should be used instead of KVP. It would allow for a more specific type check in GetDataHere, rather than checking for a KVP of FORMATETC and STGMEDIUM.

2022-03-20 05:28 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public DragDropEffects DoDragDrop(object data, DragDropEffects allowedEffects, Bitmap dragImage, Point cursorOffset, bool usingDefaultDragImage)
Another possible option is to allow the application to specify the drag image bitmap via the `GiveFeedback` event and `GiveFeedbackEventArgs`, instead of `Control.DoDragDrop()`.

2022-03-20 20:15 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                dataStore.SetData(dragDropFormat, new KeyValuePair<FORMATETC, STGMEDIUM>(pFormatetcIn, pmedium));
This could be a private drag and drop data format class consisting of the drag and drop specific formats and storage mediums.

2022-03-20 21:52 UTC, weltkante commented
@willibrandon I didn't get around to do much testing yet, one thing I note is that the provided example in WinFormsControlsTest doesn't update the cursor properly (which may be a bug in the example or in the infrastructure)

The cursor is basically stuck at whatever it was using last, so if I drag an image from the test window out to some other application it switches from arrow to "no" (expected) and when I drag back over the RTF control it remains "no" even though I can drop (wrong).

I'll try writing a few tests of my own over the coming week to see how well it works in general.

2022-03-20 23:08 UTC, willibrandon commented
> @willibrandon I didn't get around to do much testing yet, one thing I note is that the provided example in WinFormsControlsTest doesn't update the cursor properly (which may be a bug in the example or in the infrastructure)

@weltkante - Good find and I can reproduce the issue you describe. I'll take a look.

2022-03-21 01:18 UTC, willibrandon commented
@weltkante - An interesting behavior of the cursor I haven't seen before when `UseDefaultCursors` is set to false in the `Control.GiveFeedback` event. I'll push a change that fixes the undesirable behavior but this might require more thought.

2022-03-21 06:13 UTC, RussKie commented
Dropping by to say huge thank you to all involved, this is a really cool feature and you're all making it a reality.

@willibrandon are you still iterating over the API surface? If not, i.e., you think you decided what API you need for this feature to work - we start the next step in the process and engage the API Review Board.

2022-03-21 09:00 UTC, weltkante commented
> @weltkante - An interesting behavior of the cursor I haven't seen before when `UseDefaultCursors` is set to false in the `Control.GiveFeedback` event. I'll push a change that fixes the undesirable behavior but this might require more thought.

Isn't this the expected behavior? When you don't use the default cursor you are supposed to call SetCursor (which in WinForms is equivalent to assigning the static cursor property). Maybe could be documented better, I couldn't see it spelled out explicitly.

2022-03-21 23:38 UTC, willibrandon commented
> > @weltkante - An interesting behavior of the cursor I haven't seen before when `UseDefaultCursors` is set to false in the `Control.GiveFeedback` event. I'll push a change that fixes the undesirable behavior but this might require more thought.
> 
> Isn't this the expected behavior? When you don't use the default cursor you are supposed to call SetCursor (which in WinForms is equivalent to assigning the static cursor property). Maybe could be documented better, I couldn't see it spelled out explicitly.

Yes I believe that's correct. `UseDefaultCursors` isn't something I had previously used and so that behavior is new to me. I originally added the `GiveFeedback` event and set `UseDefaultCursors` to `false` to demonstrate the difference in appearance of the cursor when a drop description is set and hadn't realized that I also needed to set the static cursor property.

`e.UseDefaultCursors = true;`

![UseDefaultCursorsTrue](https://user-images.githubusercontent.com/5017479/159379503-5591944e-1b0b-4d5e-ad89-eba4f6f7c401.png)

`e.UseDefaultCursors = false;`

![UseDefaultCursorsFalse](https://user-images.githubusercontent.com/5017479/159379522-edc9c416-554c-4895-a99b-ff0f3632b179.png)

2022-03-22 00:22 UTC, willibrandon commented
> Dropping by to say huge thank you to all involved, this is a really cool feature and you're all making it a reality.

You are very welcome @RussKie and I too would like to thank you and everyone else on the team and community for providing such a good opportunity to contribute to Winforms. It has been a tremendous learning opportunity for me and I can't believe I'm working on drag and drop. Are you kidding me? Is this real life?

2022-03-22 01:04 UTC, willibrandon commented
> @willibrandon are you still iterating over the API surface? If not, i.e., you think you decided what API you need for this feature to work - we start the next step in the process and engage the API Review Board.

I'm still a little torn on the API surface, specifically the `Control.DoDragDrop` and `ToolStripItem.DoDragDrop` methods to specify the drag image bitmap. I'm currently experimenting with another approach by setting the drag image bitmap via additional `GiveFeedbackEventArgs` to see what that might look like. After this I think I'll be ready to formally propose the API.

2022-03-22 10:17 UTC, willibrandon commented
I’m starting to feel pretty good about this.

2022-03-24 13:20 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public DragDropEffects DoDragDrop(object data, DragDropEffects allowedEffects, Bitmap dragImage, Point cursorOffset, bool usingDefaultDragImage)
> We should coordinate our changes if either one of the APIs are approved

In your case it is easier to play along with my idea, since you create new API which nobody use before. That's not true in the linked issue, since there consequences for the consumers. I think you are in more safe position to have typed version of methods.

2022-03-27 06:28 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public DragDropEffects DoDragDrop(object data, DragDropEffects allowedEffects, Bitmap dragImage, Point cursorOffset, bool usingDefaultDragImage)
I've decided to take a different approach and not use the DoDragDrop methods as part of this API surface for now. I'll be proposing new GiveFeedbackEvent arguments instead for this same purpose.

2022-03-27 22:48 UTC, weltkante reviewed
Did some basic tests which went fine, and a review which found several issues. I'm not quite sure if GiveFeedback is the right place for this API, but I'll leave that to the API review - I did comment on required improvements of this API though, if its decided to keep it.

2022-03-27 22:48 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +            }
Multiple issues here

* Copying a `FormatETC` unconditionally is nontrivial because it may contain a raw pointer `DVTARGETDEVICE *ptd`. This usually is null but doesn't have to be, so you need to follow that pointer and copy its associated data, or you risk access violations later on when the format is passed back to Windows. This copying needs to be done independently of the `fRelease` flag, which only adresses ownership of the medium.

  If none of the formats you're interested in needs this data field you might want to reject `SetData` calls which have this pointer non-NULL.

* You don't handle `fRelease == false` when the caller retains ownership of the medium and you have to copy anything you want to keep beyond the method call.

* Who is going to release that format & medium structures you were keeping? As mentioned before, properly copying the format may need copying a pointer, so that copy needs to be released. A copied medium needs to release its handle, decrement reference counts, and other complex things (usually you'd just call `ReleaseStgMedium` and let Windows clean it up).

  You may need a container object with a finalizer instead of using a KeyValuePair to properly release the native resources.

2022-03-27 22:48 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +            mediumDest.pUnkForRelease = mediumSrc.pUnkForRelease;
You're setting the variables eagerly, probably should clear those in all branches returning false, to avoid issues when caller is using `ReleaseStgMedium` API for cleanup e.g. in a finally block without discrimination.

2022-03-27 22:48 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                SetIsShowingText(dataObject, true);
bug: If this throws you release the medium for which you passed ownership to the DataObject

2022-03-27 22:48 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                    hbmpDragImage = dragImage.GetHBITMAP(),
Who owns this handle? Unfortunately the doc is silent about handle ownership for this API, but a quick test I did by deleting the bitmap before returning from this method seems it keeps functioning, which to me is a strong indicator that the shell copies the bitmap and you're leaking the handle.

2022-03-27 22:48 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                        sizeof(uint))
how about using `sizeof(BOOL)` since thats what you're casting to?

obviously its all the same as long as its 4 byte, so its mostly a stylistic question

2022-03-27 22:48 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                DragDropHelper.SetDragImage(_dataObject, gfbevent.DragImage, gfbevent.CursorOffset, gfbevent.UseDefaultDragImage);
I don't know the shell API you're using here very well. Is it documented you should be doing this from GiveFeedback calls every single time?

If the documentation doesn't specifically ask you to do that, I'd be weary doing this unconditionaly, GiveFeedback calls are medium to high frequency if my memory doesn't betray me, and transferring an image on high frequency is not nice for performance. You might want to detect changes in arguments and only call the API if something changes?

2022-03-27 22:48 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +                    DragDropHelper.DragOver(ref pt, pdwEffect);
DragEnter/DragOver should be symmetrical in API to support controls which have "complex internal structure" (sometimes called "windowless" controls) which don't create separate Control instances for their subcomponents, which is an important performance optimization for certain complex controls. There you decide based on the cursor position what subcomponent your cursor is over, and need to do the same things you are doing in DragEnter when moving across the internal structure of the control.

2022-03-28 02:55 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                DragDropHelper.SetDragImage(_dataObject, gfbevent.DragImage, gfbevent.CursorOffset, gfbevent.UseDefaultDragImage);
Yes I agree and in DragDropHelper.SetDragImage I first check if a drag image is present in the data object and if so, I do not proceed with setting the drag image into the data object. Perhaps I could be more explicit about that check and perform it here. To be precise, I only set the drag image if one is not already present in the data object.

I too had the same thought about being able to detect changes in the arguments and only call the API if something has changed. I'll start working on a potential solution for this.

2022-03-28 03:17 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                DragDropHelper.SetDragImage(_dataObject, gfbevent.DragImage, gfbevent.CursorOffset, gfbevent.UseDefaultDragImage);
I was also conflicted on precisely where I should be allowing the drag image to be set from. The documentation is both clear and unclear on precisely where this should occur. From [Shell Data Object](https://docs.microsoft.com/en-us/windows/win32/shell/dataobject).

> While the cursor is over the target window, the target can use the drag-and-drop helper object to specify the drag image.

While the cursor is over the target window? So does that mean DragEnter, DragOver, or both?

> The source must create an object that exposes an IDropSource interface. This interface allows the source to update the drag image that indicates the current position of the cursor and to provide feedback to the system on how to terminate a drag-and-drop operation. IDropSource has two methods: GiveFeedback and QueryContinueDrag.

I ultimately chose Control.GiveFeedback as the place to set the drag image but have wondered if Control.DoDragDrop might be a more appropriate place. I've also wondered if we should add new DragImage, CursorOffset, and UseDefaultDragImage DragEventArgs to allow drop targets to also set the drag image.

2022-03-28 03:57 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                    hbmpDragImage = dragImage.GetHBITMAP(),
Thank you for pointing this out. I've wondered if I need to call GDI `DeleteObject` when I'm done. I'll take a closer look at this right now and will circle back here with an update.

2022-03-28 04:28 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +                    DragDropHelper.DragOver(ref pt, pdwEffect);
Thank you for the insight. I'm worried about other scenarios such as this I haven't considered yet. I'll update DragOver to be symmetrical with DragEnter and ditto on the only update if something changes.

2022-03-28 08:00 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                DragDropHelper.SetDragImage(_dataObject, gfbevent.DragImage, gfbevent.CursorOffset, gfbevent.UseDefaultDragImage);
> While the cursor is over the target window? So does that mean DragEnter, DragOver, or both?

WinForms is a bit misleading here because it allows you to implement events individually, in native APIs you always implement the whole interface - so being "over the target window" means the time span between DragEnter and DragLeave, which includes all intermediate DragOver calls.

> I ultimately chose Control.GiveFeedback as the place to set the drag image but have wondered if Control.DoDragDrop might be a more appropriate place.

I liked the DoDragDrop arguments a bit more because it makes one-off calls easier where you set the image once for the whole operation and don't need to update it (the most common case). Normally the default implementation of GiveFeedback in WinForms is sufficient and I tend to not handle the event at all. Having to implement it to get to the new APIs seems a bit bothersome, but it does give the advantage of being able to update the image if needed.

In an ideal design I'd probably want both, being able to set the initial image when starting the operation, and optionally updating it in the GiveFeedback/QueryContinueDrag calls. But given the amount of work involved implementing all that I'm fine with settling with a simpler API.

> I've also wondered if we should add new DragImage, CursorOffset, and UseDefaultDragImage DragEventArgs to allow drop targets to also set the drag image.

Thats probably against the design of the (native) API, given the wording in the docs. Might work, but also might have unintended edge cases. I'd avoid doing so because it invites fighting between both APIs, you have to consider when source and target are implemented by different people (third party controls in the same app, or two completely different apps). Inviting fights over "who set it last" will just cause annoying flicker, and people will blame WinForms because it allows both sides to change state without coordinating them.

2022-03-28 08:20 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                    hbmpDragImage = dragImage.GetHBITMAP(),
You should be able to monitor the number of GDI handles in task manager or similar tooling, as an alternative approach to figuring out if something is leaking.

2022-03-29 02:50 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                DragDropHelper.SetDragImage(_dataObject, gfbevent.DragImage, gfbevent.CursorOffset, gfbevent.UseDefaultDragImage);
I agree with every point you've made here. I was a little unclear on exactly what the implementation should look like but this clears things up for me. A change detection mechanism is needed to properly implement this and I'll start working on a possible solution now.

If your ideal design for setting the drag image is both DoDragDrop and GiveFeedback then I'm very inclined to propose that. It's not much work and I'd rather get this right than propose something half-baked. Thank you very much for your help on this.

2022-03-29 04:05 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                return;
If we let this fall through we get a COMException, Invalid FORMATETC structure DV_E_FORMATETC in GetDataIntoOleStructs. Returning here avoids that and unnecessary memory allocations/deallocations in the try-catch, but I also understand if we need to let it behave like previously and let it try the other options.

2022-03-29 05:00 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                        sizeof(uint))
I can't think of a logical reason why I chose anything other than `sizeof(BOOL)`.

2022-03-30 02:55 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +            }
- So far the formats I've observed the drag-image manager set and get have a NULL target device pointer. With that said, I highly suspect there are other formats I haven't seen yet. I'll add a check to reject formats which have a non-NULL target device pointer.
- So far I've only observed the drag-image manager pass `fRelease == true` when it calls `IDataObject::SetData`.
- I had the same thought regarding the formats & medium structures used by the drag-image manager and whether they need to be released. I've also wondered if I need to release the drop description format and medium in certain scenarios, such as DragLeave.

2022-03-30 07:16 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                return;
erm, you want to return a failure HRESULT when you don't find the format, not success, so you need to throw anyways since the signature isn't `PreseveSig` throwing is the only way to return a failure code.

throwing DV_E_FORMATETC is the right return code I think? so falling through would do the right thing

(also are you _sure_ you'd always fail the fallback code to look things up? couldn't someone have put these formats in there manually? probably not an expected case, but if there's no effort to support it via fallthrough, why not)

2022-03-31 06:12 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +                    DragDropHelper.DragOver(ref pt, pdwEffect);
I've implemented change detection for drop descriptions in DragEnter and DragOver and made them symmetrical in API.

2022-03-31 06:25 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +                    DragDropHelper.DragOver(ref pt, pdwEffect);
For detecting when a new drag image has been specified, I think first we can compare the bitmap sizes. If the bitmap sizes are different, its a new drag image. If the bitmap sizes are equal then perhaps we compare with a stored bitmap hash, or compare every pixel, but this starts to get into some areas of bitmaps that I'm not super familiar with. I'll start experimenting with this now.

2022-03-31 06:40 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                DragDropHelper.SetDragImage(_dataObject, gfbevent.DragImage, gfbevent.CursorOffset, gfbevent.UseDefaultDragImage);
For detecting when a new drag image has been specified, I think first we can compare the bitmap sizes. If the bitmap sizes are different, its a new drag image. If the bitmap sizes are equal then perhaps we compare with a stored bitmap hash, or compare every pixel, but this starts to get into some areas of bitmaps that I'm not super familiar with. I'll start experimenting with this now.

2022-04-01 02:47 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                return;
My only remaining concern with letting it fall through as is, is that it results in a jittery drag experience with the repeated thrown exceptions. My machine is fast, but I think the jitterness would be more pronounced on a slower machine.

2022-04-01 07:15 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +                return;
Unfortunately exceptions are the default way to return error codes in classic .NET COM. Drag'n'drop always has been defined this way in WinForms and always has been returning via exceptions, this is nothing new to this PR.

Every time you drag something over a process that queries for something the app doesn't provide there are error codes returned via exceptions, in my experience it works well enough. Note that exceptions with a debugger attached are orders of magnitude slower than exceptions in normal execution without debugger present.

The only way to optimize it is by changing the interface definitions to either be PreserveSig in classic COM or the "new style" COM interop and rewriting the code to return instead of throw.

I think if there's a performance issue that warrants optimizing it should be in a separate issue.

2022-04-01 07:25 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                DragDropHelper.SetDragImage(_dataObject, gfbevent.DragImage, gfbevent.CursorOffset, gfbevent.UseDefaultDragImage);
I don't think comparing image content is a useful operation, in my opinion comparing image references should be enough. Think of what the "common case" would be: the consumer already has an image reference he is passing. This would always be the same reference so the image copy can easily be optimized away by comparing references. If the API consumer is regenerating the image every call he has a much worse performance issue than what you're optimizing away in an image copy.

In other words, I think comparing image content optimizes for a case that already is inherently slower and needs to be optimized in the users code, so don't bother with comparing by content.

2022-04-01 07:31 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                DragDropHelper.SetDragImage(_dataObject, gfbevent.DragImage, gfbevent.CursorOffset, gfbevent.UseDefaultDragImage);
A much simpler solution, I like it.

2022-04-01 08:49 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +            }
I just inched a little closer to addressing most of these issues although I suspect there is still room for improvement.

2022-04-04 07:59 UTC, kant2002 reviewed
Small suggestions

2022-04-04 07:59 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                Marshal.FinalReleaseComObject(dropTargetHelper);
Do not use `Marshal.FinalReleaseComObject` where you can use simply `Marshal.ReleaseComObject`, When conversion to ComWrappers happens it would be much easier and mechanical change. 
```suggestion
                Marshal.ReleaseComObject(dropTargetHelper);
```

2022-04-04 07:59 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                Marshal.FinalReleaseComObject(dropTargetHelper);
```suggestion
                Marshal.ReleaseComObject(dropTargetHelper);
```

2022-04-04 07:59 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                Marshal.FinalReleaseComObject(dropTargetHelper);
```suggestion
                Marshal.ReleaseComObject(dropTargetHelper);
```

2022-04-04 07:59 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                Marshal.FinalReleaseComObject(dragSourceHelper);
```suggestion
                Marshal.ReleaseComObject(dragSourceHelper);
```

2022-04-05 17:56 UTC, willibrandon commented
I will start writing tests now and verify the system is behaving as expected.

2022-04-06 02:36 UTC, RussKie commented
We still need to do a formal API review, and get an official blessing from the API Review Board. Are you still iterating over the public API surface?

2022-04-06 03:33 UTC, willibrandon commented
I am finished with iterating over the public API surface and have updated the proposal in #5884.

2022-04-07 10:24 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +            }
With the last push I'm now releasing the storage mediums when they are no longer in use and handle the scenario when `fRelease == false`.

2022-04-07 10:42 UTC, willibrandon commented
Can't believe I felt good about this 16 days ago, what a mess. As of right now, I'm not aware of any significant bugs and I think the logic is almost perfect. Thank you everyone for your help on this.

2022-04-07 12:13 UTC, willibrandon commented
@roland5572 - You should check this out. It's starting to look awesome.

2022-04-07 18:04 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +            }
I'm no longer copying the `FormatETC` at all since I only need to store the private application clipboard format `cfFormat` along with the associated storage medium in the `DragDropFormat` class.

2022-04-07 21:23 UTC, weltkante commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            }
Returning early does not reset the "InDragLoop" value? What about exceptions? I don't see any obvious exceptions unless DropSource constructor could throw, but maybe you still want to prefer to write it more reliably by putting it in a finally block? That would cover both early return and exceptions.

2022-05-05 09:18 UTC, gpetrou commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IDropSourceNotify.cs
> +        public interface IDropSourceNotfiy
`IDropSourceNotfiy` -> `IDropSourceNotify`?

2022-05-06 02:02 UTC, willibrandon commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IDropSourceNotify.cs
> +        public interface IDropSourceNotfiy
Thank you!

2022-05-06 22:24 UTC, dreddy-work commented
@kirsan31 thank you for making time here. Can this be open for review now?

2022-05-06 22:32 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropFormat.cs
> +            if (!cfFormat.Equals(_cfFormat))
shouldn't this be equal condition?

2022-05-06 22:34 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropFormat.cs
> +            return medium;
```suggestion
            return fRelease ? pMedium : CopyMedium(cfFormat, pMedium);
```

2022-05-06 22:37 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +            finally
nit: empty catch block

2022-05-06 22:39 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                dropTargetHelper.DragOver(ref ppt, dwEffect).ThrowIfFailed();
btw, why throw and catch pattern in all these places?

2022-05-06 22:41 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +            mediumDest = new();
can we name with no short forms. `mediumDest `-> `mediumDestination`. same for others in the PR.

2022-05-06 22:50 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                    return *pValue == BOOL.TRUE;
```suggestion
                    return basePtr == IntPtr.Zero ? false : (BOOL*)basePtr == BOOL.TRUE;
```

2022-05-06 22:50 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                return *pValue == BOOL.TRUE;
same here with conditional return?

2022-05-06 22:53 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                *pValue = value.ToBOOL();
Any better way to update value at the pointer.

2022-05-06 22:56 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +            var gfbevent = new GiveFeedbackEventArgs((DragDropEffects)dwEffect, _lastDragImage is null, _lastDragImage!, _lastCursorOffset, _lastUseDefaultDragImage);
Two parameters here with `_lastDragImage` contradicting with `!` notion.  I do not have a better suggestion though.

2022-05-06 22:58 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +                && toolStrip.IsHandleCreated)
```suggestion
            else if (_owner is ToolStripDropTargetManager toolStripTargetManager
                && toolStripTargetManager?.Owner is ToolStrip toolStrip
                && toolStrip.IsHandleCreated)
```

2022-05-06 22:59 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.OleCallback.cs
> +                                string message = e.Message is not null ? e.Message : string.Empty;
```suggestion
                                string message = e.Message ?? string.Empty;
```

2022-05-06 23:00 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.OleCallback.cs
> +                                string messageReplacementToken = e.MessageReplacementToken is not null ? e.MessageReplacementToken : string.Empty;
```suggestion
                                string messageReplacementToken = e.MessageReplacementToken ?? 
 string.Empty;
```

2022-05-06 23:00 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.OleCallback.cs
> +                                string messageReplacementToken = e.MessageReplacementToken is not null ? e.MessageReplacementToken : string.Empty;
there are other places similar to this in the PR.

2022-05-06 23:01 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.OleCallback.cs
> +                            if (e.DropImageType > DropImageType.Invalid && _lastComDataObject is not null && owner.IsHandleCreated)
when different operands in the if statement, it would be better to enclose the operation for readability.

2022-05-07 04:03 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropFormat.cs
> +            if (!cfFormat.Equals(_cfFormat))
This check can be removed. It's a way to prevent a format from getting refreshed with a format identifier other than it's original, but from my testing, I don't think it's possible.

2022-05-07 05:21 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                dropTargetHelper.DragOver(ref ppt, dwEffect).ThrowIfFailed();
It was to help me bail out early if the method call failed and to not execute any statements after the finally block. With that said, I no longer have any statements after the finally block so the catches can be removed here.

2022-05-07 18:53 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                *pValue = value.ToBOOL();
I've condensed these 2 lines down into 1 if that helps?

`*(BOOL*)basePtr = value.ToBOOL();`

2022-05-07 19:17 UTC, willibrandon commented
> Can this be open for review now?

It's getting close. I have an issue I'm looking into after recently pulling from main.

After that, my plan is to mark this Ready for review and write UITests in DragDropTests.cs.

2022-05-08 23:45 UTC, RussKie commented
Can you please update the first post with the final reviewed API version?

2022-05-09 00:41 UTC, RussKie reviewed
👀

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +        private static bool TryGetDropTargetHelper([NotNullWhen(true)] out IDropTargetHelper? dropTargetHelper)
This method looks identical to `TryGetDragSourceHelper`. Is there any reason we can't generalise with generics, i.e., `TryGetDropTargetHelper<TDropTargetHelper>([NotNullWhen(true)] out TDropTargetHelper? dropTargetHelper)`?

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +            if (comDataObject is IDataObject iDataObject)
Please invert `if` to reduce nesting

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +            if (comDataObject is IDataObject iDataObject)
```suggestion
            if (comDataObject is IDataObject dataObject)
```

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +            }
We generally throw various argument exceptions. E.g.:
- `ANE.ThrowIfNull(nameof(dataObject)`
- We use source generators to validate enumerations, i.e., `SourceGenerated.EnumValidator.Validate(dropImageType, nameof(dropImageType));`
- AOOR for the other two.

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                    return;
Probably worth throwing here instead: `throw new Win32Exception(Marshal.GetLastPInvokeError(), SR.<error message>);`
https://docs.microsoft.com/windows/win32/api/winbase/nf-winbase-globallock#return-value
https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.dllimportattribute.setlasterror#remarks

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +            }
Which statements from above do you expect to throw?

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +        public static unsafe bool GetInDragLoop(IDataObject dataObject)
```suggestion
        public static unsafe bool IsInDragLoop(IDataObject dataObject)
```

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +        public static bool GetInDragLoopFormat(FORMATETC formatEtc)
```suggestion
        public static bool IsInDragLoopFormat(FORMATETC formatEtc)
```

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                medium = new();
Does it need to be disposed of?

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +        /// </summary>
This comment (and several others) reiterates the method name, but doesn't add any clarity to the purpose of the method - i.e., _why_ it is needed and _why_ it is doing what it does. It would be great if you could revise the xml-docs to explain the purposes of the methods, and may be add some comments (where appropriate) to explain why we're doing these things.

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                    return;
[`GlobalAlloc`](https://docs.microsoft.com/windows/win32/api/winbase/nf-winbase-globalalloc#return-value) sets the last error, so I think we should throw here too.

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +            if ((ParentInternal is not null) && ParentInternal.AllowItemReorder && (ParentInternal.ItemReorderDropSource is not null))
[nit] parens are redundant

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
> +                            e.DropImageType = !dropImageType.Equals(e.DropImageType) ? dropImageType : e.DropImageType;
Any reason these checks aren't implemented in the eventargs? We can't expect all consumers to remember to add such checks in their codebases.

2022-05-09 00:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +        }
Are these used? I couldn't find callsites for these....

2022-05-09 00:52 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.OleCallback.cs
> +                            if (e.DropImageType > DropImageType.Invalid && _lastComDataObject is not null && owner.IsHandleCreated)
We shouldn't use unnecessary parens. It adds clutter and causes analyzer noise.

2022-05-10 06:02 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +        }
Ha! These were working until my last pull from main and then bumped into ComWrappers..

Since `DropSource` will now implement both `Ole32.IDropSource` and `Ole32.IDropSourceNotify`, ComWrappers needs to account for a managed type that implements two interfaces. Lucky me this scenario is covered in [Tutorial: Use the ComWrappers API](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/tutorial-comwrappers) and I just got the `Ole32.IDropSourceNotify` methods working again locally. I can include those changes in my next push but @kant2002 should probably take a look at it.

2022-05-10 06:46 UTC, willibrandon commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            return entries;
@kant2002 - Thoughts?

2022-05-10 07:11 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
> +            return entries;
Be explicit about indexes. It’s not that your object has different number of interfaces.

2022-05-10 07:37 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropSourceNotifyVtbl.cs
> +                var inst = ComInterfaceDispatch.GetInstance<Ole32.IDropSourceNotify>((ComInterfaceDispatch*)thisPtr);
Wrap in the try/catch and return HResult of exception. Same for other metogds

2022-05-10 08:26 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +        private static bool TryGetDragSourceHelper([NotNullWhen(true)] out IDragSourceHelper2? dragSourceHelper)
I'll better familiarize myself with the guidelines. thanks for the link.

2022-05-10 08:27 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +        private static bool TryGetDropTargetHelper([NotNullWhen(true)] out IDropTargetHelper? dropTargetHelper)
Good idea.

2022-05-10 08:45 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +                medium = new();
Yes.

2022-05-11 02:13 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
> +                            e.DropImageType = !dropImageType.Equals(e.DropImageType) ? dropImageType : e.DropImageType;
These checks don't need to be here at all.. I don't know what I could've been thinking here. Proof that I need to write tests.

2022-05-12 17:15 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropSourceNotifyVtbl.cs
> +                    var inst = ComInterfaceDispatch.GetInstance<Ole32.IDropSourceNotify>((ComInterfaceDispatch*)thisPtr);
nit:  inst ->instance (we recommend avoiding abbreviations and short words if we can). Applies to other instances n this PR.

2022-05-12 17:26 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +            }
```suggestion
            }
            catch { }
            
            dragDropHelper = default;
            return false;
```

2022-05-12 17:32 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +                if ((drgevent.DropImageType > DropImageType.Invalid) && (drgevent.Data is IComDataObject comDataObject) && (_hwndTarget != IntPtr.Zero))
This logic seems common between multiple functions. Can you pull this out into separate method and call it?

2022-05-12 17:32 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +            if ((_lastDropImageType > DropImageType.Invalid) && (_lastDataObject is IComDataObject comDataObject))
same here. common logic across multiple methods. Can be moved to separate method.

2022-05-12 17:40 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.Designer.cs
> +            //
Is this Designer generated code or you manually edited? Why am i not seeing  `AutoScaleMode` and `AutoScaleDimension` properties serialized?

2022-05-12 17:42 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.cs
> +                && e.Data.GetData(nameof(_nyanCatAscii)) is string asciiCat)
```suggestion
            if (e?.Data is not null
                && e.Data.GetDataPresent(nameof(_nyanCatAscii), false)
                && e.Data.GetData(nameof(_nyanCatAscii)) is string asciiCat)
```

2022-05-12 17:43 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.cs
> +            if (e.Data is not null)
revert `if` and return early to reduce nesting

2022-05-12 17:48 UTC, dreddy-work commented
Thanks @willibrandon . I finished my review and will be asking my team to finish their review this week. Once feedback is addressed, we should be able to take this in current preview.

2022-05-12 20:35 UTC, JeremyKuhne requested changes
Thanks for all your hard work. Comments need a pass through to be consistent for indentation and full XML comment usage for new public surface area. Variable / parameter naming needs a pass as well to be consistent with C# style guidelines (notably no abbreviations). P/Invoke and native type definitions in `Interop` are the exception to this rule.

Error handling needs updated to account for the fact that we don't typically have `SetLastError` in our P/Invokes for performance.

We should have a follow-up issue to remove COM interop from this code to enable us to get to a point where we can enable trimming. It will also help performance.

2022-05-12 20:35 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDropTargetHelper.cs
> +                uint dwEffect);
We should use `Ole32.DROPEFFECT` for these parameters.

2022-05-12 20:35 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropFormat.cs
> +        public DragDropFormat(short cfFormat, STGMEDIUM pMedium, bool fRelease)
Use C# like naming here ('format', 'medium', 'release'). Same goes for the rest of the class. `fRelease` isn't very descriptive. Invert and rename to `copyData` perhaps? A comment for this parameter would be helpful.

2022-05-12 20:35 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropFormat.cs
> +        private static STGMEDIUM HandleOwner(short cfFormat, STGMEDIUM pMedium, bool fRelease)
As there are only two callers and this is just one line, I'd remove this helper. It would make the calling code clearer.

2022-05-12 20:35 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropFormat.cs
> +        public void RefreshData(short cfFormat, STGMEDIUM pMedium, bool fRelease)
Same comments as the constructor.

2022-05-12 20:35 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
> +        public static void DragEnter(IntPtr hwndTarget, IComDataObject dataObject, ref Point ppt, uint dwEffect)
Please use C# naming style in this class. Also use `Ole32.DROPEFFECT` for the parameters.

2022-05-13 07:37 UTC, willibrandon commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.Designer.cs
> +            //
Manually edited. I'm not sure if the designer has ever worked on my machine.

2022-05-13 07:40 UTC, willibrandon commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.Designer.cs
> +            //
![LoadingDesigner](https://user-images.githubusercontent.com/5017479/168235165-b3633bac-1a2d-44b3-b2ee-edf3289487ed.png)

2022-05-13 18:29 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.Designer.cs
> +            //
hmm. That is a bigger issue then :). IS your solution too long? can you create this test designer in a separate solution and add back here? it would be reliable if this code is generated by designer. It is missing few properties that are required when opening this designer on a machine that may have different settings than your development machine.

2022-05-14 08:08 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +                if ((drgevent.DropImageType > DropImageType.Invalid) && (drgevent.Data is IComDataObject comDataObject) && (_hwndTarget != IntPtr.Zero))
I've pulled these out into separate methods throughout this PR. Thoughts?

2022-05-16 03:07 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.Designer.cs
> +            //
@willibrandon check https://aka.ms/winforms/designer/troubleshooting out and see if you get more information on the issue.
In general, to be able to use the designer with this solution you need to have the same SDK installed globally (i.e., under C:\Program Files\dotnet).

2022-05-16 03:12 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DROPDESCRIPTION.cs
> +            public DROPIMAGETYPE Type
Doesn't look like this was addressed. It should be:
```cs
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        public unsafe struct DROPDESCRIPTION
        {
            public DROPIMAGETYPE type;
            private fixed char _szMessage[Kernel32.MAX_PATH];
            private fixed char _szInsert[Kernel32.MAX_PATH];

            // ...
```

2022-05-16 03:34 UTC, willibrandon commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DROPDESCRIPTION.cs
> +            public DROPIMAGETYPE Type
Makes sense now, I missed the intent on the first pass, thank you.

2022-05-16 04:02 UTC, RussKie reviewed
👍 with few nits, comments and questions.

2022-05-16 04:02 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.OleCallback.cs
> +                if (!dragEventArgs.DropImageType.Equals(_lastDropImageType) || !dragEventArgs.Message.Equals(_lastMessage) || !dragEventArgs.MessageReplacementToken.Equals(_lastMessageReplacementToke
We appear to be doing the same checks in many places. Have you considered tracking the eventargs object instead of tracking several properties?
E.g., something like:
```cs
        private class OleCallback : Richedit.IRichEditOleCallback
        {
            private DragEventArgs  _lastDragEventArgs;

            private void UpdateDropDescription(DragEventArgs dragEventArgs)
            {
                if (!dragEventArgs.Equals(_lastDragEventArgs))
                 {
                    _lastDragEventArgs = dragEventArgs.Clone();
                    DragDropHelper.SetDropDescription(_lastDragEventArgs);
                }
            }
```

This way we can encapsulate the equality logic and state tracking.

2022-05-16 06:36 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +            Debug.WriteLineIf(CompModSwitches.DragDrop.TraceInfo, "DropTarget destroyed");
I can only wonder why I was here, adding spaces, for no good reason.

2022-05-16 06:48 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +            Debug.WriteLineIf(CompModSwitches.DragDrop.TraceInfo, "DropTarget destroyed");
It happens to all of us occasionally :)

2022-05-17 03:25 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DragEventArgs.cs
> +        internal bool Equals(DragEventArgs? dragEventArgs)
@RussKie - Thoughts?

2022-05-17 11:03 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
> +        private void UpdateDropDescription(DragEventArgs dragEventArgs)
It is customary to use `e` for event args.
```suggestion
        private void UpdateDropDescription(DragEventArgs e)
```

2022-05-17 11:03 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragEventArgs.cs
> +        internal bool Equals(DragEventArgs? dragEventArgs)
Please keep methods after properties. See https://docs.microsoft.com/en-us/archive/blogs/brada/internal-coding-guidelines#28-file-organization

2022-05-26 04:46 UTC, RussKie reviewed
We'll need unit tests for the new functionality too (where practical obviously). Worth looking into a UI integration test too for an E2E scenario (i.e., using `InputSimulator`).

2022-05-26 04:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/GiveFeedbackEventArgs.cs
> +        public Bitmap DragImage { get; set; }
Should this be?
```suggestion
        public Bitmap? DragImage { get; set; }
```

2022-05-26 04:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/GiveFeedbackEventArgs.cs
> +                && giveFeedbackEventArgs.DragImage.Equals(DragImage)
This may result in a NRE

2022-05-26 04:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/GiveFeedbackEventArgs.cs
> +        }
What relevance does this method have to `GiveFeedbackEventArgs`?

2022-05-26 04:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
> +                    if ((dragEnterArgs.DropImageType > DropImageType.Invalid) && (owner is ToolStrip toolStrip) && toolStrip.IsHandleCreated)
Parens are redundant

2022-05-26 04:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DragEventArgs.cs
> +                && dragEventArgs.Message.Equals(Message)
What if `dragEventArgs.Message` is null and `Message` isn't?
```suggestion
                && dragEventArgs.Message == Message
```

2022-06-01 02:49 UTC, willibrandon commented
My cadence has been off the last week, I apologize, but I plan to pick this back up tomorrow.

2022-06-02 00:29 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                _lastGiveFeedbacEventArgs = gfbevent;
When you suggest clone, do mean shallow copy or deep copy?

2022-06-02 05:43 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/GiveFeedbackEventArgs.cs
> +        public Bitmap DragImage { get; set; }
Probably, and I should test whether there is a bonafide use case for passing a null Bitmap to `IDragSourceHelper.InitializeFromBitmap`. Perhaps the application initially specifies a drag image during `DoDragDrop` and then later wants to remove the drag image by setting the `DragImage` bitmap to null in `GiveFeedback`, but leave the drop description as-is. So, remove the initial drag image but leave the drop description.

2022-06-02 05:45 UTC, willibrandon commented
I feel like I've been saying this for months but I swear I'm going to write a test tomorrow.

2022-06-02 05:54 UTC, kant2002 commented
> but I swear I'm going to write a test tomorrow.

Everybody watching you! 😈

2022-06-02 08:16 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                _lastGiveFeedbacEventArgs = gfbevent;
I've looked at the latest code, and `DropSource` appears to have the full control over the `GiveFeedbackEventArgs` instance, and it doesn't look like it's possible to mutate it from the outside as we don't share the instance (with the local function I suggested earlier). This means we don't need to clone:
```cs
        public HRESULT GiveFeedback(Ole32.DROPEFFECT dwEffect)
        {
            GiveFeedbackEventArgs gfbevent = _lastGiveFeedbacEventArgs is null
                ? new((DragDropEffects)dwEffect, useDefaultCursors: true)
                : new((DragDropEffects)dwEffect,
                    useDefaultCursors: false,
                    _lastGiveFeedbacEventArgs.DragImage,
                    _lastGiveFeedbacEventArgs.CursorOffset,
                    _lastGiveFeedbacEventArgs.UseDefaultDragImage);

            _peer.OnGiveFeedback(gfbevent);

            if (gfbevent.DragImage is not null && !gfbevent.Equals(_lastGiveFeedbacEventArgs))
            {
                _lastGiveFeedbacEventArgs = gfbevent;
                UpdateDragImage(_lastGiveFeedbacEventArgs, _dataObject, _lastHwndTarget);
            }

            if (gfbevent.UseDefaultCursors)
            {
                return HRESULT.DRAGDROP_S_USEDEFAULTCURSORS;
            }

            return HRESULT.S_OK;

            void UpdateDragImage(GiveFeedbackEventArgs e, IComDataObject? dataObject, IntPtr lastHwndTarget)
            {
                if (dataObject is null)
                {
                    return;
                }

                DragDropHelper.SetDragImage(dataObject, e);

                if (lastHwndTarget != IntPtr.Zero && (Cursor.Position is Point point))
                {
                    DragDropHelper.DragEnter(lastHwndTarget, dataObject, ref point, (Ole32.DROPEFFECT)e.Effect);
                }
            }
        }
```

2022-06-02 08:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                _lastGiveFeedbacEventArgs = gfbevent;
Of course, as soon as I posted I realised that I totally missed `_peer.OnGiveFeedback(gfbevent)` call, and hence everything I said above it not true. We do need to clone because we don't know who may have taken a reference to `gfbevent` and whether anyone can mutate it while we try to use it later.

2022-06-02 08:40 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                _lastGiveFeedbacEventArgs = gfbevent;
As far as deep/shallow clone - the only point of contention is `Bitmap DragImage` property, everything else is a value type, meaning it's copied by value.
What would happen if the bitmap is modified or disposed mid drag-drop by a different thread? What should happen? 

May be `GiveFeedbackEventArgs` should take ownership of the set bitmap so we can do a shallow clone, e.g.:
```cs
        public Bitmap? DragImage
        {
            get => _dragImage;
            set
            {
                _dragImage?.Dispose();
                _dragImage = null;

                if (value is not null)
                {
                    _dragImage = (Bitmap)value.Clone();
                }
            }
        }
```

Thoughts?

2022-06-03 06:38 UTC, willibrandon commented
Made the cutoff, barely.

2022-06-05 20:13 UTC, willibrandon commented
@RussKie - Pretty surreal to see the that result automated from a test.

2022-06-06 04:45 UTC, RussKie commented
> Pretty surreal to see that result automated from a test.

🎉 

> Spoke too soon. Fatal error 0xC0000005 on x86.

That's probably the most interesting part from the logs:
```
Fatal error. 0xC0000005
   at Interop+Shell32+IDragSourceHelper2.InitializeFromBitmap(SHDRAGIMAGE, System.Runtime.InteropServices.ComTypes.IDataObject)
   at System.Windows.Forms.DragDropHelper.SetDragImage(System.Runtime.InteropServices.ComTypes.IDataObject, System.Drawing.Bitmap, System.Drawing.Point, Boolean)
   at System.Windows.Forms.DragDropHelper.SetDragImage(System.Runtime.InteropServices.ComTypes.IDataObject, System.Windows.Forms.GiveFeedbackEventArgs)
   at System.Windows.Forms.DropSource.<GiveFeedback>g__UpdateDragImage|6_0(System.Windows.Forms.GiveFeedbackEventArgs)
   at System.Windows.Forms.DropSource.GiveFeedback(DROPEFFECT)
   at Interop+WinFormsComWrappers+IDropSourceVtbl.GiveFeedback(IntPtr, DROPEFFECT)
   at Interop+Ole32.DoDragDrop(IntPtr, IntPtr, DROPEFFECT, DROPEFFECT ByRef)
   at Interop+Ole32.DoDragDrop(System.Runtime.InteropServices.ComTypes.IDataObject, IDropSource, DROPEFFECT, DROPEFFECT ByRef)
   at System.Windows.Forms.Control.DoDragDrop(System.Object, System.Windows.Forms.DragDropEffects, System.Drawing.Bitmap, System.Drawing.Point, Boolean)
   at System.Windows.Forms.Control.DoDragDrop(System.Object, System.Windows.Forms.DragDropEffects)
   at System.Windows.Forms.UITests.DragDropTests+DragDropForm.ListDragSource_MouseMove(System.Object, System.Windows.Forms.MouseEventArgs)
```



[System.Windows.Forms.UI.IntegrationTests_net7.0_x86.log](https://github.com/dotnet/winforms/files/8841915/System.Windows.Forms.UI.IntegrationTests_net7.0_x86.1.log)

2022-06-06 04:49 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
> +                    .Sleep(100)
?
```suggestion
                    .Sleep(DragDropDelayMS)
```

2022-06-06 05:16 UTC, kant2002 commented
> That's probably the most interesting part from the logs:

Phew, initially I thought that this was my issue! Looks like not.

2022-06-06 05:30 UTC, RussKie commented
...though you may have some thoughts on it ;)

2022-06-06 05:51 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDragSourceHelper2.cs
> +                SHDRAGIMAGE pshdi,
```suggestion
                ref SHDRAGIMAGE pshdi,
```

https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-idragsourcehelper-initializefrombitmap

2022-06-06 05:52 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDragSourceHelper2.cs
> +                Point ppt,
```suggestion
                in Point ppt,
```

https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-idragsourcehelper-initializefromwindow

2022-06-07 01:43 UTC, willibrandon commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDragSourceHelper2.cs
> +                SHDRAGIMAGE pshdi,
Tests succeeded and you are awesome! Thank you!

2022-06-07 01:48 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDragSourceHelper2.cs
> +                Point ppt,
The docs indicate that the 2nd and 3rd args are pointers, since `IDataObject` is a ref type, it's passed by ref. But shouldn't it be `Point* ppt`?

2022-06-07 01:52 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDragSourceHelper2.cs
> +                Point ppt,
I guess `in` is likely achieving the same, https://devblogs.microsoft.com/premier-developer/the-in-modifier-and-the-readonly-structs-in-c/. Though we generally strive to align with the native definitions where possible.

2022-06-07 01:53 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDragSourceHelper2.cs
> +                SHDRAGIMAGE pshdi,
Accodring to the docs, the struct is passed by ref, i.e., `SHDRAGIMAGE* pshdi`

2022-06-07 02:34 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDragSourceHelper2.cs
> +                Point ppt,
`LPDATAOBJECT` in C++ is `IDataObject` in C# in order to add `ref` we need at least `LPLPDATAOBJECT` in C++

2022-06-07 02:36 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDragSourceHelper2.cs
> +                Point ppt,
I use `in` here, because other option to use `ref` and because `[in] Point*` I belive it's better capture that `[in]` modifier in C# which is possible nowadays.

2022-06-08 05:50 UTC, willibrandon commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                _lastGiveFeedbacEventArgs = gfbevent;
> What would happen if the bitmap is modified or disposed mid drag-drop by a different thread?

My tests indicate that if I dispose or modify the bitmap mid drag-drop on a different thread, that it has no negative effect and the drag image works as expected, even if I do a really long drag loop. I assume that when the drag image manager is initialized that it takes ownership of the bitmap object, formats the drag image bits according to some rules, and then sets the bits into the data object. I also assume that it deletes the bitmap when its finished. Please share the source 😄

2022-07-01 18:18 UTC, JeremyKuhne submitted a review, later dismissed
Looks good! Thanks for all of your hard work and patience!

2022-07-01 18:20 UTC, JeremyKuhne approved these changes
Resolved the conflict

2022-07-01 18:43 UTC, dreddy-work commented
@willibrandon, as FYI, this will be merged for the Preview 7 release.

2022-07-05 17:04 UTC, merged

2022-07-07 00:24 UTC, willibrandon commented
I'm seeing an `AccessViolationException` when drag-and-dropping to the `RichTextBox`, and the operation fails.

![AccessViolationException](https://user-images.githubusercontent.com/5017479/177663031-cdd6a4b9-d488-42dc-baf0-46ffd0ddc33a.png)

I'm not yet sure if this is related to the work done in this PR, or not.

2022-07-07 00:29 UTC, dreddy-work commented
@willibrandon , can you open a new issue for this and we can track the discussion there to figure out ?

2022-07-08 09:08 UTC, kant2002 commented
Congratulation! That’s WinForms team for you 🏅. Also, take care of your heart ;)

2022-07-18 08:37 UTC, RussKie commented
Thank you so much for your efforts and your patience!