Added "Skip" attribute for fail unit tests in arm64
dotnet/winforms pull request #6599
Opened 2022-02-02 06:35 UTC by vladimir-krestov

Related Issue #6597

## Proposed changes
- Skipped unit tests that fail sometimes in arm64 environment, that blocks fixes deployment.

## Customer Impact
- No

## Regression? 
- No

## Risk
- Minimal

## Test methodology 
- CI build

2022-02-02 23:24 UTC, RussKie requested changes

2022-02-02 23:24 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
> +        [WinFormsTheory(Skip = "https://github.com/dotnet/winforms/issues/6597")]
We historically skip like this:
https://github.com/dotnet/winforms/blob/81774abbcbb885fe906f1c0f813e8175eef8705c/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs#L460-L463

2022-02-02 23:24 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
> +        [WinFormsFact(Skip = "https://github.com/dotnet/winforms/issues/6597")]
I suppose it's ok to raise a single issue for flaky tests related to the same control, but please separate unrelated controls' tests into own issues. 

Also when raising issues please establish the context of failures, i.e. include stack traces, etc.

2022-02-02 23:27 UTC, RussKie commented
> Maybe we should skip them only for ARM64 arc.

Right now we only have x86/x64 detection. dotnet/runtime has decorations, but I don't know if they work out of the box or require elbow grease to get those working for us. https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/filtering-tests.md.

2022-02-03 13:29 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
> +        [WinFormsFact(Skip = "https://github.com/dotnet/winforms/issues/6597")]
I created additional issues, please take a look:
DGV: https://github.com/dotnet/winforms/issues/6597
ToolStrip: https://github.com/dotnet/winforms/issues/6610
RichTextBox: https://github.com/dotnet/winforms/issues/6609

2022-02-03 16:01 UTC, vladimir-krestov commented
> > Maybe we should skip them only for ARM64 arc.
> 
> Right now we only have x86/x64 detection. dotnet/runtime has decorations, but I don't know if they work out of the box or require elbow grease to get those working for us. https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/filtering-tests.md.

I tried to find some solution, but didn't find exist one. So created my own. Please check the second commit as example.

2022-02-03 21:58 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
> +        [WinFormsTheory(Skip = "Flaky tests, see: https://github.com/dotnet/winforms/issues/6597")]
SkipCondition default to `false`. Does this skip the test or doesn't? unclear from reading the code.

2022-02-03 22:01 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
> +        [WinFormsTheory(Skip = "Flaky tests, see: https://github.com/dotnet/winforms/issues/6597")]
To use `SkipCondition` you need to use `WinFormsTheoryEx`. I added it only to one file for example. Maybe Igor has a better way

2022-02-03 22:02 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
> +        [WinFormsTheory(Skip = "Flaky tests, see: https://github.com/dotnet/winforms/issues/6597")]
Got it.

2022-02-03 22:03 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
> +        [WinFormsTheory(Skip = "Flaky tests, see: https://github.com/dotnet/winforms/issues/6597")]
I am fine if we are forced to skip for all archs here in case if we do not agree on this implementation as long as we have tracking issues that we prioritize in this release

2022-02-04 02:19 UTC, RussKie reviewed
Great idea! 

Perhaps we could extend the API a little furhter, so that we could write something like this:
```cs
        [ConditionalWinFormsFact(UnsupportedArchitecture = Architecture.Arm64)]
        public void ToolStrip_WndProc_InvokeMouseActivateWithHandle_Success()
```
...or
```cs
        [ConditionalWinFormsFact(SupportedArchitecture = Architecture.x86)]
        public void ToolStrip_WndProc_InvokeMouseActivateWithHandle_Success()
```
The later will allow us to apply the same attributes to `PARAMTests` and Co tests.

2022-02-04 18:18 UTC, dreddy-work commented
@vladimir-krestov , lets get this merged ASAP. CI is making lot of noise.

2022-02-07 11:53 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/TestUtilities/WinFormsFactEx.cs
> +                }
We can't do this just like that, because at the moment when we set `Skip`, `UnsupportedArchitecture` is not set yet. So we will always have the exception.

2022-02-07 12:00 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/TestUtilities/WinFormsFactEx.cs
> +                }
null `_skipReason` means, that we didn't set `Skip` yet. In my environment, `Skip` is set first, and then `UnsupportedArchitecture` is set. I'm not sure, that `Skip` is always first. So we may have the exception, even if `Skip` is set. I plan to find some more universal solution, eg. using the attribute constructor. But let's merge it as is to not block Devendar with CI. And continue discussing in the next refactoring PR.

2022-02-07 18:49 UTC, dreddy-work commented
Seems there is one more test in debug mode here.  Would you mind adding that to skip list as well.

2022-02-07 21:19 UTC, vladimir-krestov commented
Added `Skip` for `ImageList_FinalizerReleasesNativeHandle_ReturnsExpected` as well. But didn't add the conditional attribute, because this test is in the project, that doesn't have references to unit test utilities. So we need to decide how to add conditional attributes for UI tests (add dependecy or copy-paste attributes). But I suggest to do this in the next PR.

2022-02-07 21:54 UTC, dreddy-work commented
> Added `Skip` for `ImageList_FinalizerReleasesNativeHandle_ReturnsExpected` as well. But didn't add the conditional attribute, because this test is in the project, that doesn't have references to unit test utilities. So we need to decide how to add conditional attributes for UI tests (add dependecy or copy-paste attributes). But I suggest to do this in the next PR.

Please create a tracking issue so we don't loose it.

2022-02-07 23:31 UTC, dreddy-work approved these changes

2022-02-08 00:20 UTC, merged

2022-02-08 00:50 UTC, dreddy-work commented
FOllowing is one more to add in your next PR: 
![image](https://user-images.githubusercontent.com/36968667/152896958-76169505-0348-4b00-8fb0-eb49d59863f3.png)

2022-02-08 18:07 UTC, dreddy-work commented
Another one.

![image](https://user-images.githubusercontent.com/36968667/153048805-7aa8af17-3665-4070-9862-947c19dc64ff.png)

![image](https://user-images.githubusercontent.com/36968667/153048920-58ad3b7a-6cc2-46bf-a527-560a37fccdda.png)

2022-02-09 07:39 UTC, vladimir-krestov commented
> > Added `Skip` for `ImageList_FinalizerReleasesNativeHandle_ReturnsExpected` as well. But didn't add the conditional attribute, because this test is in the project, that doesn't have references to unit test utilities. So we need to decide how to add conditional attributes for UI tests (add dependecy or copy-paste attributes). But I suggest to do this in the next PR.
> 
> Please create a tracking issue so we don't loose it.

Created https://github.com/dotnet/winforms/issues/6653