Use ComWrappers for IFileSaveDialog
dotnet/winforms pull request #6608
Opened 2022-02-03 11:39 UTC by kant2002

I extract from FileOpenDialogWrapper base class FileDialogWrapper to handle just IFileDialog and derive FileSaveDialogWrapper form it.
Add missing methods for IFileSaveDialog

2022-02-03 16:38 UTC, kant2002 commented
This PR requires https://github.com/dotnet/winforms/pull/6574 to be merged because of changes in `CoCreateInstance`.

2022-02-07 20:03 UTC, kant2002 commented
This is ready for review

2022-02-08 00:25 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                return retVal;
```suggestion
                return ((delegate* unmanaged<IntPtr, IntPtr, HRESULT>)(*(*(void***)_wrappedInstance + 3)))
                    (_wrappedInstance, parent);

```

2022-02-08 00:27 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                HRESULT retVal;
i see some places defined as `result `and in some places `retVal`. Good to unify them.

2022-02-08 00:27 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                HRESULT retVal;
same here.  I do not see a need for local variable here.

2022-02-08 00:29 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                HRESULT result;
and can be moved to inline?

2022-02-08 01:26 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                HRESULT retVal;
We generally strive to use standard English terms for variable names unless there is a specific alignment to native definitions. So "result" is the better choice here (and elsewhere).

2022-02-08 01:27 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                HRESULT retVal;
And this one also does not even need a variable- you can just return from within the fixed block.

2022-02-08 01:32 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                if (result.Failed())
As we're doing this over and over again it would be good to add an extension to `HResultExtensions` and start using it:

``` C#
public static void ThrowIfFailed(this HRESULT hr)
{
    if hr.Failed()
    {
        Marshal.ExceptionForHR((int)hr);
    }
}
```

2022-02-08 01:35 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                HRESULT result;
Should check `pszTitle` for null and throw here.

2022-02-08 01:39 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                result = ((delegate* unmanaged<IntPtr, IntPtr*, HRESULT>)(*(*(void***)_wrappedInstance + 13)))
Just throw right away if the called method failed as we're going to throw anyway. There shouldn't be a case where we return a valid object when we throw. Same for other instances.

2022-02-08 01:40 UTC, JeremyKuhne requested changes
Some general clean-up feedback. I'll review again once you've made another pass.

2022-02-08 22:35 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                    (_wrappedInstance, &ppsi_local);
shouldn't this check for result value?

2022-02-08 22:37 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                if (result.Failed())
this method can be cleaned further to use `extension `method on `HRESULT `and inline `result `declaration.

2022-02-09 00:29 UTC, RussKie reviewed
👍

2022-02-09 00:29 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
> +                    throw new System.InvalidCastException();
```suggestion
                    throw new InvalidCastException();
```

2022-02-09 00:29 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
>          // D57C7288-D4AD-4768-BE02-9D969532D960
Please keep entries in this file in alphabetical order

2022-02-09 00:29 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                    ((IDisposable)results).Dispose();
```suggestion
                    (results as IDisposable)?.Dispose();
```

2022-02-09 02:57 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                    ((IDisposable)results).Dispose();
Null check is not needed. We control right now exact type of the COM wrapper instance. So we know that that type implement IDisposable always.

2022-02-09 03:09 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                    (_wrappedInstance, &ppsi_local);
Obviously!!

2022-02-09 05:58 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
> +                    (_wrappedInstance, &ppsi_local);
Actually not. We return result. That's intended.

2022-02-09 06:24 UTC, dreddy-work commented
👍

2022-02-14 07:55 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                    ((IDisposable)results).Dispose();
If you take a look at this https://github.com/dotnet/winforms/pull/6685/commits/5e9697957fb7cdfa5fd070ee09641b4d427fd5d4#diff-6fb59eb16f6df895c60c72cf64adbca50feb1556190727a7c648817a891cd0cfR21

you may notice that by knowing explicit type of RCW you can get rid of COM interfaces. I did not go that route in this PR because even this way seems beneficial, it definitely require discussion, or at least not obvious choice.

2022-02-14 08:17 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                    ((IDisposable)results).Dispose();
In this linked commit it is obvious. Here we operate on interfaces, so in theory it is possible that a given instance may not implement `IDisposable`. Hence it is better to be safe than sorry :)

2022-02-14 08:47 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                    ((IDisposable)results).Dispose();
I can swear in blood that this will never happens. My plan is to remove interfaces where possible and have only concrete classes. If I introduce that in this PR it will produce a lot of noise and distrat with more important problem. Validating that wrapper do not have leaks and correctly convert data. 

In that location we can change `IFileDialog` to `FileDialogWrapper` and all your concerns would disappear since they would be inapplicable. That change will also affect Open File dialog.

If you insist on being pedantic, I will gladly made change, because the faster this is lands, the better I can move to other places.

2022-02-14 09:07 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                    ((IDisposable)results).Dispose();
Alright, sign in blood here 📜. 👹

On a serious note, if you're planning to update this code with wrappers in the near future - we can leave it as is. Otherwise, let's add a check. How does this sound?

2022-02-14 09:20 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                    ((IDisposable)results).Dispose();
That would be my next PR.

2022-02-14 09:26 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                    ((IDisposable)results).Dispose();
Awesome, keeping it as is then.

2022-02-14 09:27 UTC, RussKie commented
@msftbot merge if @JeremyKuhne approves.

2022-02-14 18:59 UTC, JeremyKuhne approved these changes

2022-02-14 18:59 UTC, merged