Enable nullability in ListView
dotnet/winforms pull request #6627
Opened 2022-02-05 10:27 UTC by gpetrou

## Proposed changes

- Enable nullability in ListView.

2022-02-07 00:49 UTC, RussKie requested changes
In the future it'd really appreciated it if you presented non-functional changes (e.g., variable renames, code clean up, etc.) in separate commits from functional changes (such as NRTA), as it'd greatly improve the readability of the changeset.
Thanks

2022-02-07 00:49 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ItemCheckedEventArgs.cs
> +        public ItemCheckedEventArgs(ListViewItem item)
We must validate this in this case, e.g. `.ThrowIfNull()`.

2022-02-07 00:49 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                fi = new IO.FileInfo(_bkImgFileNames[i]!);
We can't assume it's not null (see `SetBackgroundImage()` method). We should null check, and continue.

2022-02-07 00:49 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                                    subItemBounds.Width = _columnHeaders![0].Width;
We can't assume this. In other parts of the class we always null-check before dereferencing the value.

2022-02-07 00:49 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                        fi = new IO.FileInfo(_bkImgFileNames![i]!);
As above

2022-02-07 00:49 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
>          internal void UpdateSavedCheckedItems(ListViewItem item, bool addItem)
Propose to refactor as follows:
```cs
            if (addItem)
            {
                savedCheckedItems ??= new List<ListViewItem>();
                savedCheckedItems.Add(item);
            }
            else if (savedCheckedItems is not null)
            {
                Debug.Assert(savedCheckedItems.Contains(item), "somehow we lost track of one item");
                savedCheckedItems.Remove(item);
            }
```

2022-02-07 06:15 UTC, gpetrou commented
> In the future it'd really appreciated it if you presented non-functional changes (e.g., variable renames, code clean up, etc.) in separate commits from functional changes (such as NRTA), as it'd greatly improve the readability of the changeset. Thanks

Sure. I'll keep that in mind.

2022-02-07 06:48 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                if (bkImgFileName is not null)
Please invert
```cs
if (bkImgFileName is null)
{
    continue;
}
```

2022-02-07 06:48 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                            if (bkImgFileName is not null)
ditto

2022-02-13 15:34 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +        private Collections.Specialized.BitVector32 _listViewState; // see LISTVIEWSTATE_ consts above
Doesn't seem like they can.

2022-02-13 15:43 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                if (value.Index == topItem!.Index)
Sorry, not sure what you mean here? Should I change something?

2022-02-14 01:00 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                if (value.Index == topItem!.Index)
We can't assume `topItem` is not null here. I think we should just return if `topItem` is null.

2022-02-14 05:07 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
>          internal void UpdateSavedCheckedItems(ListViewItem item, bool addItem)
This is still outstanding.

2022-02-14 06:08 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
>          internal void UpdateSavedCheckedItems(ListViewItem item, bool addItem)
Hmm, I see that I already applied the proposed change. Not sure why you don't see it.
![image](https://user-images.githubusercontent.com/4172445/153809404-9d0af8db-2fba-4c5e-83f6-050024aec1fa.png)

2022-02-14 08:21 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
>          internal void UpdateSavedCheckedItems(ListViewItem item, bool addItem)
Apologies, you have indeed. I must have looked at the stale diff...

2022-02-21 00:14 UTC, RussKie approved these changes

2022-02-23 05:49 UTC, gpetrou commented
@RussKie perhaps we could merge this?

2022-02-23 06:04 UTC, RussKie commented
I can indeed. Thank you for the nudge.

2022-02-23 06:04 UTC, merged