Option to not use WebRequest for PictureBox
dotnet/winforms pull request #6684
Opened 2022-02-12 06:44 UTC by kant2002

Indirectly related to #1756 because if that would work, I would be able to fix #1756 using the same approach.

2022-02-14 09:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +        private async void LoadFromFileAsync()
```suggestion
        private async Task LoadFromFileAsync()
```

2022-02-14 09:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +                                        new ProgressChangedEventArgs(progress, null));
```suggestion
                                _currentAsyncLoadOperation.Post(_loadProgressDelegate, new ProgressChangedEventArgs(progress, null));
```

2022-02-14 09:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +                                        new ProgressChangedEventArgs(100, null));
```suggestion
                            _currentAsyncLoadOperation.Post(_loadProgressDelegate, new ProgressChangedEventArgs(100, null));
```

2022-02-14 09:46 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +        private async void LoadFromFileAsync()
If I apply that change, then analyzer complain about this function at callsite. Whole body in `try/catch`. Do you think having `Task` is important enough?

2022-02-17 15:34 UTC, kant2002 commented
If subsequently apply https://github.com/kant2002/winforms/commit/7ce82f2a4b307588b2c232c449617ba20c3ded5c then application trimmed to 15Mb and that with reflection

2022-02-18 17:18 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +        private async void LoadFromFileAsync()
Should switch to `Task` and annotate code
or should I keep `async void`?

2022-02-18 19:39 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +                        throw new NotSupportedException("Loading from remove location disabled.");
should this string be localized?

2022-02-18 19:43 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +                        PostCompleted(null, false);
you do not need to post  `PostCompleted `here

2022-02-27 12:35 UTC, kant2002 commented
@RussKie do you think, this PR require some additional work?

2022-02-28 05:39 UTC, RussKie commented
Apologies for the delay, I’m working on multiple streams and stretched pretty thin atm. I’ll try to get to this asapp.

2022-02-28 19:39 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +        private async void LoadFromFileAsync()
@kant2002 I'd put the option inside of the existing `Task.Run` and not mix in `async` here. Better to stick with the existing patterns (which predate `async`).

2022-02-28 19:41 UTC, JeremyKuhne requested changes
I'd stick with putting this in the existing `Task.Run` and avoid introducing `async`.

2022-03-03 18:23 UTC, kant2002 commented
@JeremyKuhne did I infer your proposal correctly?

2022-03-03 19:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +                    Task.Run(() => LoadFromFileAsync());
When you do this you're spinning two workers. What I was suggesting was that you remove `async` from the helper and not use `ReadAsync()`. Something like `Task.Run(() => LoadFromFileWithProgress())` or have `void LoadFromFileAsync()` with a `Task.Run` in it.

2022-03-06 15:34 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +                    Task.Run(() => LoadFromFileAsync());
> or have void LoadFromFileAsync() with a Task.Run in it.

@JeremyKuhne Hopefully I get it right this time.

2022-03-07 18:20 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +                    PostCompleted(null, false);
nit: when passing `true` or `false` it is better to explicitly name the parameter for clarity. You should also consider naming the parameter when passing `null`.

2022-03-07 19:00 UTC, JeremyKuhne requested changes
Spending some more time looking at this I think you'd be better off using the existing `ReadCallBack()`. Let me know if that doesn't work for you or if you have any other questions.

2022-03-07 19:00 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
> +        private void LoadFromFileAsync()
Looking at this again I wonder why we don't just use the existing `ReadCallback()`? It would be clearer to reutilize the existing code instead of duplicating it. Then you'd also get cancellation support, which you haven't currently implemented.

``` C#
private void LoadFromFileAsync()
{
    // Shouldn't need to check CancellationPendingState here if all we're doing is Task.Run(() => LoadFromFileAsync())
    FileStream stream = null;

    try
    {
        stream = File.OpenRead(_imageLocation);
        _contentLength = stream.Length;
        _totalBytesRead = 0;

        stream.BeginRead(
            _readBuffer,
            0,
            ReadBlockSize,
            new AsyncCallback(ReadCallBack),
            responseStream);
    }
    catch (Exception error)
    {
        PostCompleted(error, cancelled: false);
    }
    finally
    {
         stream?.Dispose();
    }
}
```

2022-03-07 19:02 UTC, JeremyKuhne commented
@kant2002 appreciate your effort here.

2022-03-09 09:22 UTC, kant2002 commented
@JeremyKuhne reason why I did use `async/await` in "new" implementation is because I think they are easier to reason about. And  seems here appetite eventually move to HttpClient so `async/await` is would be natural choice. Since this is new code path, "some regressions" maybe acceptable for target audience.

Anyway, I update as you suggest the code. I do not have questions and this approach is fine.

2022-03-10 19:06 UTC, JeremyKuhne commented
> I think they are easier to reason about.

Normally, I'd agree. As this code predates `async` you introduce a fair amount of cognitive overhead if you mix and match approaches. While the code could be completely rewritten to leverage new patterns I'd hesitate to do so without a strong justification.

> Since this is new code path, "some regressions" maybe acceptable for target audience.

I think the default position should be "no differences in functionality". We can, of course, alter that based on data and discussion.

Again, thanks for your effort here.

2022-03-10 19:08 UTC, JeremyKuhne approved these changes
Looks good!

2022-03-10 19:08 UTC, merged