Enable nullability in FolderBrowserDialog
dotnet/winforms pull request #6725
Opened 2022-02-20 09:44 UTC by gpetrou

## Proposed changes

- Enable nullability in FolderBrowserDialog.

2022-02-20 19:57 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        public string? SelectedPath
I do not see this returning null

2022-02-20 19:57 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        public string? InitialDirectory
same here

2022-02-20 19:58 UTC, dreddy-work requested changes
Why did we make nullable and returning empty string?

2022-02-20 23:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +        private string? _initialDirectory;
Since all properties exposing these fields are annotated as `[DefaultValue("")]`, these fields must be assigned to `string.Empty`.

2022-02-22 00:04 UTC, RussKie reviewed
👍

2022-02-22 00:04 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                    if (_initialDirectory is not null && _initialDirectory.Length != 0)
```suggestion
                    if (InitialDirectory.Length != 0)
```

2022-02-22 00:04 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                    if (_selectedPath is not null && _selectedPath.Length != 0)
```suggestion
                    if (SelectedPath.Length != 0)
```

2022-02-28 18:50 UTC, dreddy-work approved these changes

2022-02-28 21:48 UTC, merged