Use ComWrappers for IErrorInfo
dotnet/winforms pull request #6743
Opened 2022-02-23 08:16 UTC by kant2002

Progress towards #5163 and #4649

2022-02-24 22:45 UTC, RussKie commented
The change looks sensible. Can you please elaborate how you tested it? Also can you please at least manual test to WinformsControlsTest project.

2022-02-25 11:21 UTC, kant2002 commented
I add small window which display COM Object which supports `ISuportsErrorInfo` but unfortunately I cannot find CLSID for an object which has properties which trigger `IErrorInfo` code path. I manage to test only `GetErrorInfo() == S_FALSE` path.

2022-03-06 15:35 UTC, kant2002 commented
@RussKie this is hard time, and if you have spare cycles, can you take a look?

2022-03-08 02:33 UTC, RussKie commented
> I add small window which display COM Object which supports `ISuportsErrorInfo`

Are you able to add your test harness to the solution? Either as an extension to one of the existing integration projects (e.g., under IntegrationTests or InteropTests) or add a new stand-alone project.

2022-03-08 02:41 UTC, RussKie commented
>  I manage to test only GetErrorInfo() == S_FALSE path.

Can we make a custom COM object that returns S_OK? For example, in https://github.com/dotnet/winforms/pull/4685 @weltkante added a native project that loads the managed code. Maybe we can do something like this too.

2022-03-08 02:42 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.GetErrorInfo.cs
> +        public static extern HRESULT GetErrorInfo(uint dwReserved, out IntPtr pperrinfo);
Is this used outside this file? If not, please make it private.

2022-03-08 02:46 UTC, RussKie commented
We (the team) have a extremely limited test capabilities and limited understanding of real scenarios in which COM is used in conjunction with Windows Forms apps. This makes it very difficult to accept changes in this area without good and verifiable test coverage.

2022-03-13 09:10 UTC, kant2002 commented
Tests are in place. I have to only fix infra issues. Creation of IDispatch COM objects rely on TLB file which produced by MIDL and this is failing right now. It works for me locally in the Developer command prompt, but not in regular PowerShell for example. If somebody have an idea, I would like to know what should I do.

2022-03-13 20:00 UTC, weltkante commented
> It works for me locally in the Developer command prompt, but not in regular PowerShell for example. If somebody have an idea, I would like to know what should I do.

Developer command prompt is setting additional search paths & environment variables, but the powershell scripts are using the arcade build infrastructure, so needs someone who knows how to configure C++ projects for that I guess.

2022-03-14 03:15 UTC, kant2002 commented
I the dotnet/runtime this is done like that https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/eng/native/init-vs-env.cmd so maybe I'll start with this approach.

2022-03-14 12:48 UTC, kant2002 commented
Progress:
1. building locally from Powershell
2. Release build issues on CI, no sure what it is.
3. Debug issues with running tests. I have this one locally, but think that I solve them by making test fixture to run sequentially. Seems to be I done that wrong. 

Would gladly accept suggestions how to run specific test fixture sequentially. Or how I can run Reg-free COM in XUint that way tests would be more realistic.

2022-03-14 13:31 UTC, weltkante commented
> Or how I can run Reg-free COM in XUint that way tests would be more realistic.

In my experience you usually have the manifest for regfree COM alongside the exe, which with unit tests is a bit problematic as it will be a test runner not under your control.

You could start a separate process for the test, where you put the manifest along that processes exe

Or you could try to use [activation contexts](https://docs.microsoft.com/en-us/windows/win32/sbscs/activation-contexts) to load a manifest for a library loaded at runtime. I've never used activation contexts so I can't guarantee that it works for .NET libraries this way, would need some research/experimentation to see if that route is viable.

2022-03-14 15:41 UTC, kant2002 commented
Activation contexts scares me. Even if see snippets for .Net I do not fully understand them. If it would be acceptable just run `regsvr32` I probably would be happy

2022-03-14 16:43 UTC, weltkante commented
> Activation contexts scares me. Even if see snippets for .Net I do not fully understand them.

I did a quick test and it works seamlessly by [doing a few interop calls](https://gist.github.com/weltkante/dd0ed188ab3bb0ba3c0f96a854959818) to load the manifest manually

2022-03-15 03:08 UTC, RussKie commented
> I the dotnet/runtime this is done like that [dotnet/runtime@`57bfe47`/eng/native/init-vs-env.cmd](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/eng/native/init-vs-env.cmd) so maybe I'll start with this approach.

I'm sure the runtime team won't mind if we borrowed the script. We can invoke it from start-vs.cmd.

2022-03-15 03:10 UTC, RussKie commented
I'm phoning a friend - @AaronRobinsonMSFT :) May be he can help...

2022-03-15 03:12 UTC, RussKie commented
> If it would be acceptable just run `regsvr32` I probably would be happy

I'm not sure other contributors would be happy if we'd reg'ed some random COM object in their system, nor if we'd be able to do this on CI boxes either. @MattGal any thoughts?

2022-03-15 14:12 UTC, AaronRobinsonMSFT commented
@RussKie Thanks for adding me to the conversation. Per usual, @weltkante is providing solid guidance here.

>If it would be acceptable just run regsvr32 I probably would be happy

Yep, I get that, but that is not something any test should be doing. The interop team took great pains to ensure all COM related testing avoided global registration. The RegFree/ActivationCxt approach is recommended for these cases.

> Activation contexts scares me. Even if see snippets for .Net I do not fully understand them.

Agreed. It is a convoluted system and has corner cases that have kept me, and the rest of the Interop team stuck debugging weird issues at times. However, we have tamed the beast for .NET Core testing and have a well-worn path in dotnet/runtime. See [here](https://github.com/dotnet/runtime/blob/466b0f66aafe63a31696c16dca43a727cd4bbce5/src/coreclr/hosts/corerun/corerun.hpp#L261-L296) for `corerun`. @weltkante's example above is the same logic, but in C# - thank you!

A manifest example can be found in dotnet/runtime for one of the COM tests - [`App.manifest`](https://github.com/dotnet/runtime/blob/main/src/tests/Interop/COM/NETClients/IDispatch/App.manifest).

2022-03-16 12:30 UTC, kant2002 commented
@RussKie can you, or somebody else from the team look at what I done with csproj and sln for ARM64? I do not have hardware, so cannot test this configuration and something is off

2022-03-16 17:31 UTC, kant2002 commented
> Oops, I missed this tag and came here to check why I was getting so many updates

Thankfully for me, @MattGal all these updates right now from the regular dev activity. I implement reg-free COM with help and guidance of others. Breakages in CI right now from my lack of access to ARM64

> registering random COM objects on their machine at best leaves stuff behind polluting their registry and at worst can cause unexpected behavior / stability issues.

Yeah, that was desperate request to somehow get unblocked. Thankfully my advisors all insist that I would not be lazy and implement proper solution. Deeply thankful for that.

> If you go one of the other routes and it comes around to affect other users, we will chat in the future :)

I appreciate that people on Dotnet organization so talkative, and like to make new friends. I probably reserve chat for with you, for more interesting topics. :)

2022-03-17 03:50 UTC, kant2002 commented
@RussKie I think I make it works, but right now I see some issues with build itself. Once more then one project with `<NativeProjectReference Include="xxx\CMakeLists.txt" CMakeProject="xxx\xxx.proj" BuildNative="true" />` then current build start have race conditions. I thought I have just one issue with XML files which I fix by do not work with XML files in native projects https://github.com/dotnet/winforms/pull/6743/files#diff-50e91c82311ea26f2a73202525dfdf2b0a89c178ee666b2bf3ad4c84ac4c06dcR5, but now I see some issues with building CMake projects. I cannot explain issues which I see in any way as concurrency issues. I thought that this is because `BuildNative="true"` is set. And in order to have native projects, we probably have to move building of native projects to separate step.

Commit [9b54574](https://github.com/dotnet/winforms/pull/6743/commits/9b545744fd7d398013666ef627e742797617b535) has issues only with ARM64, and no funny CMake related issues. Since I change just solution configuration, I cannot explain what's going on currently.

I would like that somebody check my thought process. and look at the issues in last couple builds.

2022-03-18 07:00 UTC, RussKie commented
I'll have a look early next week.

2022-03-23 03:18 UTC, kant2002 commented
@RussKie can somebody take a look again? I think my build issue was coincidental with GitHub issue at this day.

2022-03-23 04:56 UTC, RussKie commented
> can somebody take a look again? I think my build issue was coincidental with GitHub issue at this day.

It's building:
![image](https://user-images.githubusercontent.com/4403806/159626841-22039a61-53e4-433b-b246-f01c759f44b2.png)
...or is there something else?

2022-03-23 05:01 UTC, kant2002 commented
Not sure, but some of my builds there was some race conditions during Xml Intellisense files. There was no such issues locally, and after I rebase all issues are gone. But at least once agents timed out. 

Also I implement tests, so all my changes are covered now. I would like finish this PR

2022-03-23 05:32 UTC, RussKie reviewed
This is a 🚀 science 😄.

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
> +    <NativeProjectReference Include="WindowsFormsTests\CMakeLists.txt" CMakeProject="WindowsFormsTests\WindowsFormsTests.proj" BuildNative="true" />
Can we rename to align with https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/InteropTests/NativeTests?
```suggestion
    <NativeProjectReference Include="WindowsFormsTests\CMakeLists.txt" CMakeProject="NativeTests\NativeTests.proj" BuildNative="true" />
```

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +        public const int DISP_E_MEMBERNOTFOUND = unchecked((int)0x80020003);
We have this defined in:
https://github.com/dotnet/winforms/blob/1f4032c1ba6e1bb97aee586605616a4f01cbaf45/src/System.Windows.Forms.Primitives/src/Interop/Interop.HRESULT.cs#L50

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +        public const string System_Windows_Forms_NativeTests = "System_Windows_Forms_NativeTests";
Where is this used?

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            var IID_IUnknown = new Guid("{00000000-0000-0000-C000-000000000046}");
We have this one defined in:
https://github.com/dotnet/winforms/blob/1f4032c1ba6e1bb97aee586605616a4f01cbaf45/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs#L169

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +        }
We have this defined in:
https://github.com/dotnet/winforms/blob/1f4032c1ba6e1bb97aee586605616a4f01cbaf45/src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.ACTCTXW.cs#L11-L23

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            [MarshalAs(UnmanagedType.Interface)] out object ppv);
This one is defined in:
https://github.com/dotnet/winforms/blob/1f4032c1ba6e1bb97aee586605616a4f01cbaf45/src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CoCreateInstance.cs#L11-L25

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +        private static extern bool DeactivateActCtx(int dwFlags, IntPtr ulCookie);
These are too defined in the Interop namespace (except for `ReleaseActCtx` I think)

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/System_Windows_Forms_NativeTests.X.manifest
> +      threadingModel="Both" />
[nit] Incorrect indent

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            var clsid = new Guid("0ED8EE0D-22E3-49EA-850C-E69B20D1F296");
```suggestion
            Guid clsidRawErrorInfoUsageTest = new("0ED8EE0D-22E3-49EA-850C-E69B20D1F296");
```

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            var clsid = new Guid("EA1FCB3A-277C-4C79-AB85-E2ED3E858201");
```suggestion
            Guid clsidStandardErrorInfoUsageTest = new("EA1FCB3A-277C-4C79-AB85-E2ED3E858201");
```

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/WindowsFormsTests.proj
> +<Project Sdk="Microsoft.DotNet.CMake.Sdk">
Can you please add a readme file for those who aren't very good with C++ and COM (e.g., me 😊) explaining what this project does. 
If I understand it correctly, this project contains two COM objects RawErrorInfoUsageTest (CLSID: 0ED8EE0D-22E3-49EA-850C-E69B20D1F296) and StandardErrorInfoUsageTest (CLSID: EA1FCB3A-277C-4C79-AB85-E2ED3E858201), that are used in PropertyGrid_IErrorInfoSupportTests tests.

2022-03-23 05:32 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +                    }
It would be great if you could add some comments explaining the test mechanics, and why we're asserting in the `catch` clause. Ditto for `ISupportErrorInfo_Supported_WithIErrorInfoGiven`.

2022-03-23 05:59 UTC, kant2002 commented on eng/init-vs-env.cmd
> +@if not defined _echo @echo off
This script right now run as part of build. For the developer no need to do anything with this script.

2022-03-23 06:02 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
> +    <NativeProjectReference Include="WindowsFormsTests\CMakeLists.txt" CMakeProject="WindowsFormsTests\WindowsFormsTests.proj" BuildNative="true" />
It did not work for me. Have  issues with CMake SDK where both projects use `NativeTests` as output folder. Maybe `NativeTests\WindowsFormsTests.proj` is good compromise. Not sure that this will works.

2022-03-23 06:02 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +        public const string System_Windows_Forms_NativeTests = "System_Windows_Forms_NativeTests";
Letftover. Will remove.

2022-03-23 06:07 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            [MarshalAs(UnmanagedType.Interface)] out object ppv);
I would like to keep tests unrelated to Winforms code if possible. Yes, this will lead to a bit of duplication, but that way we would not touch code.

Specifically this `[MarshalAs(UnmanagedType.Interface)] out object ppv);` require have built-in COM interop. I would like to push code which does not rely on it. End-goal is this declaration would not be present at all in the Primitives project, and it anyway have to be reintroduced in tests.

Maybe `IDispatch` support never let me do that with current ComWrappers approach, but `IDynamicInterfaceCastable` should do the trick eventually.

2022-03-23 06:08 UTC, kant2002 commented on Winforms.sln
> +		{AB38E262-F206-4820-8F29-23C5F72A4A16}.Release|x86.Build.0 = Release|x86
CMake did not like when I have AnyCPU for the `csproj` with CMake reference.

2022-03-23 06:10 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +        public const int DISP_E_MEMBERNOTFOUND = unchecked((int)0x80020003);
I prefer tests to be self-contained. I would not insist on that, but what if have separate set of constants in Primitives and somewhere in the tests infra?

2022-03-23 06:11 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +                    }
I would try, but GridEntry and their behavior is a bit black box. I just capture existing behaviour. Will try to comeup with some explanation for catch, etc.

2022-03-23 06:14 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/WindowsFormsTests.proj
> +<Project Sdk="Microsoft.DotNet.CMake.Sdk">
That's for now. I expect to have more COM objects in this project eventually, since you would not let me off the hook with my changes. Will add README where I try to give rationale for project and Reg-free com configuration.

2022-03-23 06:15 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +        private static extern bool DeactivateActCtx(int dwFlags, IntPtr ulCookie);
I can use them from Primitives project, but would like to keep declarations in the test projects if possible. All such cases except CoCreateInstance is not important IMO for have non-changeable tests.

2022-03-23 06:17 UTC, kant2002 commented
@RussKie I left some comments about code duplication in tests. Let me know about your opinion, since immutable tests is pattern which I mimic from runtime repo. After that I will start cleaning up and adding comments.

2022-03-23 11:02 UTC, kant2002 commented on Winforms.sln
> +		{AB38E262-F206-4820-8F29-23C5F72A4A16}.Release|x86.Build.0 = Release|x86
Also seems that ARM64 tests executed under x64 simulation (?) because it is important that ARM64 configuraiton build using x64, otherwise build did not build/pickup native parts.

2022-03-23 11:13 UTC, weltkante commented on Winforms.sln
> +		{AB38E262-F206-4820-8F29-23C5F72A4A16}.Release|x86.Build.0 = Release|x86
When I was looking at native tests last there were no ARM tests, the project files were building X64 just so they would have something to build, but no tests were executed. I don't know if the situation changed, quite some time has gone by.

2022-03-23 11:27 UTC, kant2002 commented on Winforms.sln
> +		{AB38E262-F206-4820-8F29-23C5F72A4A16}.Release|x86.Build.0 = Release|x86
> When I was looking at native tests last there were no ARM tests

There ARM64 unit tests running. https://dev.azure.com/dnceng/public/_build/results?buildId=1677777&view=logs&j=a8f71490-549e-54d9-6b98-8fc4837d22f9&t=9ed0a6c0-fd3e-5751-41bf-59e617722956

But because I do not have hardware, I just make tests pass in CI. But I have to say that ARM64 solution configuration should build x64 DLL. You can see that in SLN file. When I was "smart" and try to say "arm64" it blow-up on CI.

2022-03-24 11:03 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            [MarshalAs(UnmanagedType.Interface)] out object ppv);
a duplication is a maintenance overhead. If there's more than one definition, a contributor has a dilemma - which definition is to use? And if the definitions differ in some way - which definition is correct? And so on...

> End-goal is this declaration would not be present at all in the Primitives project, and it anyway have to be reintroduced in tests.

We are free to move anything that's not a part of a public API, and if we have definitions that are "test only" - we can move those across.

2022-03-24 11:10 UTC, RussKie reviewed
Thank you for the comments and the readme 👍

2022-03-24 11:10 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +                        // So grid entry knows only about error code.
👍 
```suggestion
                        // Most default C++ implementations when Invoke return error code.
                        // Consult IErrorInfo object and populate EXCEPINFO structure so grid entry knows only about the error code.
```

2022-03-24 11:10 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +                        // and display that error message to the user.
👍 

```suggestion
                        // If C++ implementation of Invoke did not populate EXCEPINFO structure
                        // from IErrorInfo, then we read that information about error call and display that error message to the user.
```

2022-03-24 11:10 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/README.md
> +This project builds as native DLL, which can be used as reg-free COM host. That allow run tests and do not worry about polluting the developer/build machines.
```suggestion
This project is native DLL which provide unmanaged parts required for testing WinForms components. Most interesting part of the tests would be COM objects which given to controls.
This project builds as a native DLL, which can be used as a reg-free COM host. That allow running tests without worrying about "polluting" developer/build machines.
```

2022-03-24 11:21 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            [MarshalAs(UnmanagedType.Interface)] out object ppv);
> a duplication is a maintenance overhead.

I think not. I think so, because I prefer having tests in write-only mode. This does not works well with new projects, but works perfect with mature projects like this one. If you never touch test then you do not care how things are declared.

If we have same declaration in code and tests we may slightly change test scenario when we refactor. Since as you told, team not always have full understanding of consequences of changes, Also that allow refactoring spree, and do not care that you may break tests by that.

In a sense writing tests is already "maintainance overhead" for regular developer, since writing tests slightly different mindset.

Would like to summon @weltkante on this topic, and other persistent contributors to say on the matter.

I will comply in this PR, since for me it is more important to move forward, but expect me to be vocal about this testing strategy on each opportunity. I hope I can change team's mind on this topic.

2022-03-24 11:23 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +                        // So grid entry knows only about error code.
This change meaning. `Invoke` method look a the IErrorInfo and populate `EXCEPINFO` where you assume that it is developer/caller job to look at IErrorInfo. It does not mean that my English is fine 😄

2022-03-24 13:01 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +                        // So grid entry knows only about error code.
I rewrote explanation.

2022-03-24 16:03 UTC, weltkante commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            [MarshalAs(UnmanagedType.Interface)] out object ppv);
I don't have a strong opinion here. I also haven't been following closely what the "state of the art" for the new COM interop is - but `CoCreateInstance` was redundant under the old model, you'd just annotate the interface/class correctly and could `new` it up directly. Under the new model it seems wrong that its annotated with `MarshalAs`.

2022-03-24 18:12 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            [MarshalAs(UnmanagedType.Interface)] out object ppv);
Thanks for feedback. I really do not think that in tests we should go with “new” ways only. But for this particular function, “old” way is better, since it allow write test easier. Anyway. I do apply @RussKie suggestion so I can move forward

2022-03-28 09:49 UTC, kant2002 commented
@RussKie can you take a look, to keep me busy?

2022-03-28 11:45 UTC, RussKie commented
The team  is currently busy with urgent work, and it may be few days before I may get to this. Please bear with me.
________________________________
From: Andrii Kurdiumov ***@***.***>
Sent: Monday, 28 March 2022 8:50 PM
To: dotnet/winforms ***@***.***>
Cc: Igor Velikorossov ***@***.***>; Mention ***@***.***>
Subject: Re: [dotnet/winforms] Use ComWrappers for IErrorInfo (PR #6743)


@RussKie<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRussKie&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7Cf3becfd81b8640bd7e8508da10a05874%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637840578108254156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=f5E%2FGhEJ453h56jj4OcEEWEXt%2FQOXekKtecUYyJFLs8%3D&reserved=0> can you take a look, to keep me busy?

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fpull%2F6743%23issuecomment-1080438533&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7Cf3becfd81b8640bd7e8508da10a05874%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637840578108254156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QMFRHVgKjws65l84nLnTKTWxuCH7n3NehmxFZVHuO3s%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABBTEXWU3Z5HTFVH2AWGKXLVCF6FBANCNFSM5PDTVSNQ&data=04%7C01%7Cigor.velikorossov%40microsoft.com%7Cf3becfd81b8640bd7e8508da10a05874%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637840578108254156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qsj6moQ1bWeRkiYkUpCYf0kryLCrq25QUDCnEcBUSU0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-03-28 11:47 UTC, kant2002 commented
Thank you for telling me. For sure I will wait how long it is necessary.

2022-03-28 15:27 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.IErrorInfoSupportTests.cs
> +            [MarshalAs(UnmanagedType.Interface)] out object ppv);
@kant2002 I agree with @weltkante here. Having a single definition is preferrable. I appreciate your statement regarding "new" vs "old" ways in which COM interop works though. It should be possible to simply do the object marshal manually using [`Marshal.GetObjectForIUnknown`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshal.getobjectforiunknown). The benefit here is the same API can be called for either and the tests explicit indicate what they want to test as opposed to relying on the magic of the generated IL stub.

2022-03-28 15:40 UTC, kant2002 commented
@AaronRobinsonMSFT I would like to ask your opinion on my manual approach to reducing size of RCW for IErrorInfo for example. I provide just necessary methods which is require to run WinForms. Let’s say in the future somebody want to use additional methods from the COM interface, so it has to manually check for method number in Vtbl. That’s error prone. At the same time if RCW would be generated automatically all methods would be added. Isn’t this “expensive” and what do you think about this in general?

2022-03-28 16:30 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/StandardErrorInfoUsageTest.h
> +    ~StandardErrorInfoUsageTest()
The destructor isn't needed here. If it is desired, then I'd use the default.

```c++
~StandardErrorInfoUsageTest() = default;
```

2022-03-28 16:30 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/RawErrorInfoUsageTest.h
> +    ~RawErrorInfoUsageTest()
Remove or use default.

```cpp
~RawErrorInfoUsageTest() = default;
```

2022-03-28 16:30 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/StandardErrorInfoUsageTest.cpp
> +    ICreateErrorInfo* cei;
`ComSmartPtr<>`

2022-03-28 16:30 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/StandardErrorInfoUsageTest.cpp
> +                IErrorInfo* errorInfo;
`ComSmartPtr<>`

2022-03-28 16:30 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/DispatchImpl.cpp
> +DispatchImpl::~DispatchImpl()
This destructor can be turned into `virtual ~DispatchImpl() = default;` in the header if `ComSmartPtr<>` is used for `IUnknown` types.

2022-03-28 16:30 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ErrorInfoWrapper.cs
> +                pBstrDescription = Marshal.PtrToStringUni(descriptionPtr);
These should only be checked if `result` is non-failure.

2022-03-28 16:30 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ErrorInfoWrapper.cs
> +        internal class ErrorInfoWrapper
I would add the methods for the rest of the `IErrorInfo` interface. They can all just throw `NotImplementedException`.

2022-03-28 16:30 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IErrorInfo.cs
> -        public unsafe interface IErrorInfo
I don't understand why we are getting rid of the `IErrorInfo` type here. That is what we are working with not an `ErrorInfoWrapper`.

2022-03-29 03:05 UTC, kant2002 commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/DispatchImpl.h
> +    ITypeLib *_typeLib;
That's borrowed from https://github.com/dotnet/runtime/blob/71ad9f5382b1936db7bb6ee03a75efdb8c7cb675/src/tests/Interop/COM/Dynamic/Server/DispatchImpl.h#L29-L31 
Should go back and change there too?

2022-03-29 03:21 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms/tests/UnitTests/WindowsFormsTests/DispatchImpl.h
> +    ITypeLib *_typeLib;
Boo. I didn't realize we missed that in dotnet/runtime. Yes, we should update that as well.

2022-03-29 03:25 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ErrorInfoWrapper.cs
> +        internal class ErrorInfoWrapper
Ok. I was thinking that general sentiment is to remove methods https://github.com/dotnet/runtime/blob/890fde7c5a57ca3f367131f173773c410e4fc26f/src/libraries/System.Drawing.Common/src/System/Drawing/DrawingCom.COMWrappers.cs#L284-L293

Also Jeremy has different idea, to comment out method/#ifdef so I see slight twists on the matter in each person. If you see I remove interface altogether, since I do not think that having artificial interface is anybetter then just directly work with class. I notice that just so you have visibility of the usage for that pattern which you probably interested in.

2022-03-29 03:27 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IErrorInfo.cs
> -        public unsafe interface IErrorInfo
I do not fully understand what do you mean. Technically in this piece of code there no `IErrorInfo` usage anymore and I get rid of it.  I think you saying something which I do not get.

2022-03-29 03:56 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ErrorInfoWrapper.cs
> +        internal class ErrorInfoWrapper
That is a fair perspective to have. My personal preference is to have the well-known COM interface around instead of having to search for it at some point in the future. Simply operating on the class itself isn't a bad idea, just slightly confusing from my perspective. I say that because if I come into this space the API to use is `GetErrorInfo()` and that is documented to return an `IErrorInfo` but in this code base I don't see that used and so am confused as to why. This is just my perspective, likely because I am so familiar with COM.

Jeremy's perspective to have the methods but ifdef them out also seems reasonable. I don't have a strong preference other than someone coming into this space is likely to at least be passingly familiar with COM and `GetErrorInfo()`. However, how it is currently designed avoids anything familiar with respect to COM and forces the new person to start from the beginning and ask: how does all this fit together?

2022-03-29 03:58 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IErrorInfo.cs
> -        public unsafe interface IErrorInfo
My point is that using the `GetErrorInfo()` and `IErrorInfo` is more intuitive with the correct types that match the official documentation. We can define these types nicely in C# so I would suggest doing that. However, I will defer to the WinForms team if their preference is what you have written here.

2022-03-29 10:32 UTC, RussKie commented
> Failures seem to be a parallel build issue. Does the `NativeTests.proj` need to have access to the `xml` doc?

Not at all. Raised https://github.com/dotnet/winforms/issues/6928 to track the reentrancy.

2022-03-29 10:39 UTC, RussKie commented
> Is there something I can help review here?

@AaronRobinsonMSFT yes, your help is very much appreciated 👍

2022-04-02 12:53 UTC, kant2002 commented
@AaronRobinsonMSFT I do think I address all main questions. @RussKie can you also take a look again?

2022-04-04 08:08 UTC, RussKie reviewed
I'm trying to catch up, and I'd appreciate it if you could help me understand the chosen organisation of the tests.

To me PropertyGrid.IErrorInfoSupportTests look like integration tests (arguably most of our unit tests are not "true" unit tests as our implementations involve Win32, etc., but some tests are "more integration tests" than the other). And logically these tests, I'd think, belong to System.Windows.Forms.Interop.Tests project. The C++ implementations could reside in the System.Windows.Forms.Interop.Tests/NativeTests project.
Was there any reason why you decided not to place the new tests there?

Thank you

2022-04-04 11:20 UTC, kant2002 commented
My rationale is following. Tests for me mostly are specifications of behaviours for the component. Displaying COM object inside Property Grid is just one of these requirements. I suspect if wrote properly we can have up to 10 COM objects of different shapes which test all possible cases of OLE/IDispatch magic. Integration testing for me is more of when multiple things come into interplay. For example: I setup `PropertyGrid`, set `SelectObject`, let somebody indirectly change that object and indirectly trigger `PropertyGrid` update. Then this would be qualified for me as integration testing.

The more requirements for same component living together, the better. I do not think that COM interop is something special for `PropertyGrid`. Consider that this eventually would be not one-off job, but more `ComWrappers` work, the more tests should I have to cover existing codepaths for ugly cases.

Anyway, is rule of thumb that all "unit-tests" which involve COM should be in the `System.Windows.Forms.Interop.Tests` I definitely can live with that.

I will take a look at the new location for tests, moving things should not be that difficult.

2022-04-05 00:41 UTC, RussKie commented
> Anyway, is rule of thumb that all "unit-tests" which involve COM should be in the `System.Windows.Forms.Interop.Tests` I definitely can live with that.
> 
> I will take a look at the new location for tests, moving things should not be that difficult.

🚀

2022-04-06 02:10 UTC, RussKie approved these changes
👍

2022-04-06 02:11 UTC, RussKie commented
@JeremyKuhne can you please review as well

2022-04-06 18:00 UTC, JeremyKuhne requested changes
Just some formatting nits- otherwise I'm good with this. Thanks for your effort!

2022-04-07 02:30 UTC, kant2002 commented
@RussKie @JeremyKuhne I think I'm done here.

2022-04-07 19:07 UTC, JeremyKuhne approved these changes
:shipit:

2022-04-07 21:13 UTC, merged