Enable nullability in ListViewSubItem
dotnet/winforms pull request #6836
Opened 2022-03-12 09:54 UTC by gpetrou

## Proposed changes

- Enable nullability in ListViewSubItem.

2022-03-14 20:54 UTC, dreddy-work requested changes
Please take a relook at accessibleobject use.

2022-03-14 20:54 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                IRawElementProviderFragment? nextAccessibleObject = accessibleObject?.FragmentNavigate(NavigateDirection.NextSibling)!;
you have negation operator telling `accessibleObject` cannot be null at this location.

2022-03-16 20:10 UTC, gpetrou commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
> +                IRawElementProviderFragment? nextAccessibleObject = accessibleObject?.FragmentNavigate(NavigateDirection.NextSibling)!;
I should have removed these.

2022-03-16 20:19 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
> +            internal AccessibleObject? AccessibilityObject
@vladimir-krestov/ @Tanya-Solyanik  , does this alter any assumptions or behavior around accessibility object?

2022-03-22 17:15 UTC, merged