Enable nullability in Splitter
dotnet/winforms pull request #6904
Opened 2022-03-26 06:49 UTC by gpetrou

## Proposed changes

- Enable nullability in Splitter.

2022-03-26 17:03 UTC, dreddy-work submitted a review, later dismissed

2022-03-29 01:27 UTC, RussKie requested changes

2022-03-29 01:27 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
> +            Rectangle bounds = splitTarget!.Bounds;
Instead I propose we pass `splitTarget` in, e.g.:
```cs
private Rectangle CalcSplitLine(Control splitTarget, int splitSize, int minWeight)
```

2022-03-29 01:27 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
>              switch (Dock)
ditto for `GetSplitSize`

2022-03-29 09:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
> +            SplitEnd(true);
Can you please help me understand this change?

2022-03-29 14:23 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
> +            SplitEnd(true);
If I had to guess, I would say that this code was a copy/paste from `OnMouseMove`. However, here we call `SplitEnd` instead of `OnSplitterMoving`. So, `xSplit` and  `ySplit` are not used. Same applies for `r`, `x` and `y`. Inside `SplitEnd` we use `_splitTarget = null;`, so I removed the `if (splitTarget is not null)` check.

2022-03-29 23:31 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
> +            SplitEnd(true);
That makes sense. Thank you.

2022-03-29 23:33 UTC, RussKie approved these changes

2022-03-29 23:33 UTC, merged