Enable nullability in classes that inherit from Control.ControlCollection
dotnet/winforms pull request #6935
Opened 2022-03-30 05:27 UTC by gpetrou

## Proposed changes

- Enable nullability in classes that inherit from Control.ControlCollection.

2022-03-30 16:29 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
> -            Assert.Throws<NullReferenceException>(() => collection.Add(null));
you did not change any exception types in this PR. how come this test was passing earlier?

2022-03-31 15:45 UTC, gpetrou commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
> -            Assert.Throws<NullReferenceException>(() => collection.Add(null));
Before, we had:
`throw new ArgumentException(string.Format(SR.TabControlInvalidTabPageType, value.GetType().Name));`
Now, we have:
`throw new ArgumentException(string.Format(SR.TabControlInvalidTabPageType, value?.GetType().Name));`

2022-04-01 17:05 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
> -            Assert.Throws<NullReferenceException>(() => collection.Add(null));
Isn't test expecting `NullReferenceException` exception before?

2022-04-02 07:46 UTC, gpetrou commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
> -            Assert.Throws<NullReferenceException>(() => collection.Add(null));
Not sure what you are asking, but before `value.GetType()` would throw a `NullReferenceException` in the specific test. Now with `value?.GetType()` it will throw `ArgumentException`. Unfortunately, the implementations of the `Add` methods are inconsistent between the classes. Some have nop, some have `ArgumentNullException`, some have ArgumentException.

2022-04-03 14:45 UTC, gpetrou commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
> -            Assert.Throws<NullReferenceException>(() => collection.Add(null));
Since it doesn't make much sense to Add/Remove null controls, perhaps what we should do is throw ArgumentNullException in all cases. I have added a separate commit for that.

2022-04-04 04:50 UTC, RussKie requested changes

2022-04-04 04:50 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
> -
❗  This is a breaking change. We can't do this.

Applies universally.

2022-04-04 04:50 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.ControlCollection.cs
>                  }
This looks like an inconsistent oversight. In other collections we ignore `null` value, and I think we should do the same here. Whilst technically it is a change of behaviour I don't believe it will result in a breaking change.
```cs
            public override void Add(Control? value)
            {
                if (value is null)
                {
                    return;
                }

                if (value is not TabPage tabPage)
                {
                    throw new ArgumentException(string.Format(SR.TabControlInvalidTabPageType, value.GetType().Name));
                }
```

2023-10-04 22:55 UTC, dreddy-work commented
@gpetrou, can take a look at current state of this PR and see if it needs to be out of draft?

2023-10-25 23:17 UTC, lonitra commented
@gpetrou Apologies for this longstanding PR. It looks like this PR now just adds tests. Could you update PR title and fix test errors?

2023-11-06 17:51 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridView.DataGridViewControlCollectionTests.cs
> +        using var owner = new DataGridView();
Could you change the objects we are instaniating in tests to have type on left hand side? e.g.
```suggestion
        using DataGridView owner = new();
```
Otherwise LGTM, thanks for adding tests! 👍

2023-11-06 21:16 UTC, lonitra approved these changes

2023-11-06 21:34 UTC, merged