Add Message.GetLParam<T>for link-friendliness
dotnet/winforms pull request #6962
Opened 2022-04-04 06:45 UTC by kant2002

That remove one warning from linker.

This method is good candidate for the public API surface

2022-04-04 07:12 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
> +        public T? GetLParam<T>() => Marshal.PtrToStructure<T>(LParamInternal);
This is a new public API, and _if_ it's really needed it needs to go through the API review process. However, I don't believe this API is necessary. Please read on...

2022-04-04 07:12 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> +            var point = message.GetLParam<Point>();
We can do an unsafe cast
![image](https://user-images.githubusercontent.com/4403806/161491805-70d08ede-70e6-42a6-ab04-4d5fabe61ab3.png)

2022-04-04 07:14 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> +            var point = message.GetLParam<Point>();
You are right. Too much automatic replacements hurting my reasoning capabilities.

2022-04-05 03:13 UTC, RussKie commented
I'm happy to take ToolTip changes, but RTB-related changes require tests and more thinking. 

I guess there was a reason why `ENLINK` et al were duplicated for x64, this comment provides some insight but sadly lacks details, which we need to find:
https://github.com/dotnet/winforms/blob/1616cf133035beadf3c97573c8abecbdb6750967/src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs#L3278-L3279

For example, packing may differ between platforms, and we've already stepped on this rake before in https://github.com/dotnet/winforms/issues/2814 (fixed in https://github.com/dotnet/winforms/pull/2851). 

To have better a comfort level with the RTB-related changes we'd need to check native definitions and write tests that verify the struct layouts similar to https://github.com/dotnet/winforms/pull/2851.

2022-04-05 04:41 UTC, RussKie commented
Related work https://github.com/dotnet/winforms/pull/6399

2022-04-11 03:47 UTC, kant2002 commented
@RussKie think I’m done. Take a look at the approach

2022-04-21 07:19 UTC, kant2002 commented
Maybe @Tanya-Solyanik or @dreddy-work has time for this?

2022-04-21 18:40 UTC, JeremyKuhne requested changes
Thanks! If you could move these types to the new `Interop` location that would be fantastic.

2022-04-21 18:40 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
> +        [StructLayout(LayoutKind.Sequential, Pack = 4)]
We should call out that everything from `richedit.h` is packed at 4.

2022-04-21 18:40 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
> +        public struct ENLINK
Can you please move these out of `NativeMethods` to `Interop.Richedit`? `NativeMethods` is a TODO chunk of code.

2022-04-21 18:42 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
> +            public IntPtr wParam;
Can you change these to nint/nuint too please? We need to get off of IntPtr for things that are actually nint/nuint to avoid checked.

2022-04-22 00:10 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
> +        [StructLayout(LayoutKind.Sequential, Pack = 4)]
Do you want apply that to all structs in `Interop.Richedit` and write tests for them in similar manner?

2022-04-22 00:11 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
> +            public IntPtr wParam;
Hope I'm done what you ask me to do.

2022-04-22 03:06 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
> +        [StructLayout(LayoutKind.Sequential, Pack = 4)]
That'd be great 👍

2022-04-22 03:15 UTC, RussKie approved these changes

2022-04-22 03:17 UTC, kant2002 commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
> +        [StructLayout(LayoutKind.Sequential, Pack = 4)]
Can I do that in follow up PR?

2022-04-22 15:27 UTC, kant2002 commented
Hey, I even found one funny bug with these new tests.

2022-04-22 21:23 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/InteropTests/NativeTests/RichTextBoxTests.cpp
> +    value->nmhdr.code = 132;
Would be nice to share the magic numbers between this code and the .cs code. Though I don't have any idea how to do it other than a text file.

2022-04-22 21:23 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
> +        [StructLayout(LayoutKind.Sequential, Pack = 4)]
>We should call out that everything from richedit.h is packed at 4.

@kant2002  - I did not see a comment to this effect added, could you please add one?

2022-04-22 23:18 UTC, RussKie commented on src/System.Windows.Forms/tests/InteropTests/NativeTests/RichTextBoxTests.cpp
> +    value->nmhdr.code = 132;
A comment in the managed test code stating these numbers come from the unmanaged side (with a link to the file) would suffice imo.

2022-04-26 00:25 UTC, RussKie reviewed
👍 with few nits

2022-04-26 00:25 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CHARRANGE.cs
> +        // All structures from richedit.h is packed at 4
I suggest going one step further and create a const that we can reuse across the lot. This way we don't have to dup the comment and the value across multiple fies.
A good question where to define the said const... Maybe put it in src/Interop/Richedit/Interop.RichEditPack.cs file?

2022-04-26 00:25 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GTL.cs
> +            NUMBYTES = 16,
🎉

2022-04-26 00:25 UTC, RussKie commented on src/System.Windows.Forms/tests/InteropTests/RichTextBoxTests.cs
> +// at https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/InteropTests/NativeTests/RichTextBoxTests.cpp
```suggestion
// at src/System.Windows.Forms/tests/InteropTests/NativeTests/RichTextBoxTests.cpp
```

2022-04-26 05:56 UTC, RussKie approved these changes

2022-04-26 07:58 UTC, merged

2022-04-26 07:58 UTC, RussKie commented
Thank you