Enable nullability in OpenFileDialog
dotnet/winforms pull request #6997
Opened 2022-04-10 07:02 UTC by gpetrou

## Proposed changes

- Enable nullability in OpenFileDialog.

2022-04-11 03:53 UTC, kant2002 commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                        files[unchecked((int)i)] = GetFilePathFromShellItem(item) ?? string.Empty;
Isn’t this a potential breaking change for somebody?

2022-04-11 05:29 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
> +                        files[unchecked((int)i)] = GetFilePathFromShellItem(item) ?? string.Empty;
I added some more changes to remove `string.Empty` usages.

2022-04-11 21:20 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    string? fileName = _fileNames[i];
you could make this non-nullable and avoid `!` in rest of the places.

2022-04-11 21:20 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    string? fileName = _fileNames[i];
you could make this non-nullable and avoid `!` in rest of the places.

2022-04-11 21:26 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    _charBuffer.PutString(_fileNames[0]!);
this change seems breaking. Did you check when we would have filename in the array as `null` ?

2022-04-11 21:26 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    _charBuffer.PutString(_fileNames[0]!);
this change seems breaking. Did you check when we would have filename in the array as `null` ?

2022-04-11 21:29 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    _charBuffer.PutString(_fileNames[0]!);
Never mind i see native method from `ProcessVistaFiles` that could return null.  `!` is necessary even after checking for not null?

2022-04-11 21:29 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    _charBuffer.PutString(_fileNames[0]!);
Never mind i see native method from `ProcessVistaFiles` that could return null.  `!` is necessary even after checking for not null?

2022-04-26 05:29 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    string? fileName = _fileNames[i];
I'd do a check for null and exit early in this method.

2022-04-26 05:40 UTC, RussKie requested changes

2022-04-26 05:40 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    _charBuffer.PutString(_fileNames[0]!);
Use `FileName` instead.

2022-04-26 05:40 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
> +        private protected abstract string?[] ProcessVistaFiles(WinFormsComWrappers.FileDialogWrapper dialog);
I don't think this is correct. Which path do you see that could result in a null? I think `GetFilePathFromShellItem` _may_ be annotated incorrectly, as it returns the string is the call succeeded (see https://docs.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellitem-getdisplayname).

2022-04-30 06:59 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
> +        private protected abstract string?[] ProcessVistaFiles(WinFormsComWrappers.FileDialogWrapper dialog);
You are right. Since we throw on failure, we can use the null forgiving operator.

2022-04-30 07:10 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    _charBuffer.PutString(_fileNames[0]!);
Yes, there is a warning if we remove this. We had similar cases in previous PRs.

2022-04-30 07:12 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    _charBuffer.PutString(_fileNames[0]!);
`Filename` does the same check internally, so we would duplicate the check. Perhaps we should leave this as it is?

2022-05-06 04:05 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    _charBuffer.PutString(_fileNames[0]!);
The whole block can be simplified to `_charBuffer.PutString(FileName);

2022-05-06 04:18 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +        private string?[]? _fileNames;
I don't believe this is correct. Where do you see we set a `null` entry?

2022-05-06 04:18 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +                    string? fileName = _fileNames[i];
To avoid `!` operators we need to do the following:
```diff
         /// </summary>
-        private bool ProcessFileNames()
+        private bool ProcessFileNames(string[] fileNames)
         {
             if ((_options & (int)Comdlg32.OFN.NOVALIDATE) == 0)
             {
                 string[] extensions = FilterExtensions;
-                for (int i = 0; i < _fileNames!.Length; i++)
+                for (int i = 0; i < fileNames.Length; i++)
                 {
-                    string? fileName = _fileNames[i];
+                    string fileName = fileNames[i];
                     if ((_options & AddExtensionOption) != 0 && !Path.HasExtension(fileName))
                     {
                         bool fileMustExist = (_options & (int)Comdlg32.OFN.FILEMUSTEXIST) != 0;
@@ -699,7 +699,7 @@ namespace System.Windows.Forms
                             }
                         }
 
-                        _fileNames[i] = fileName;
+                        fileNames[i] = fileName;
                     }
```

2022-05-06 05:44 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +        private string?[]? _fileNames;
In current main, we have `if (_fileNames is null || string.IsNullOrEmpty(_fileNames[0]))` in `FileName` property. So, I thought that we could have null string elements. Should I remove that and the check?

2022-05-06 06:08 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
> +        private string?[]? _fileNames;
I've checked how `_fileNames` is populated (a double check is welcome), and I couldn't see how we can end up with a null element.

2022-05-12 03:29 UTC, RussKie approved these changes

2022-05-12 03:29 UTC, merged