Data grid view row accessible object
dotnet/winforms pull request #7069
Opened 2022-04-22 07:27 UTC by gpetrou

## Proposed changes

- Enable nullability in DataGridViewRowAccessibleObject.

2022-04-22 10:05 UTC, RussKie requested changes

2022-04-22 10:05 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
> +                _owner = owner.OrThrowIfNull();
We can't do this, it's a breaking change to the public API.

2022-04-23 08:01 UTC, vladimir-krestov reviewed
Looks good, have cosmetic points only (except https://github.com/dotnet/winforms/pull/7069/files#r856045276)

2022-04-27 08:59 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
> +                _owner = owner.OrThrowIfNull();
Just to be clear, you want me to make `DataGridViewRow` nullable or just remove `OrThrowIfNull`?

2022-04-28 02:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
> +                _owner = owner.OrThrowIfNull();
Just remove `.OrThrowIfNull` since we're throwing IOEs. It's inconsistent with the way we generally do things, but it's an old code and we leave it as is.

2022-04-29 01:04 UTC, RussKie approved these changes

2022-04-29 01:04 UTC, merged