Introduce CommandBinding, Bindable ToolStripItems and DataContext to WinForms
dotnet/winforms pull request #7143
Opened 2022-05-05 22:21 UTC by KlausLoeffelmann

This is a draft PR, and work in progress.
Feel free to comment to principal issues but note that this PR is in flux and still subject to change.

This fixes #4895.

2022-05-11 03:46 UTC, RussKie reviewed
As discussed, please bring the API proposal up-to-date. Few nits and suggestions.

2022-05-11 03:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> -        internal virtual int DeviceDpi
Alphabetising members is a great idea, however please do it in a dedicated commit, separate from all other changes.

2022-05-11 03:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +            }
[nit]
```suggestion
            get => CommonProperties.xGetAnchor(this);
```

2022-05-11 03:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/IBindableCommandProvider.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
Filenames must match types contained within.

2022-05-11 03:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/IBindableCommandProvider.cs
> +    internal class CommandControl : Control, ICommandProvider
One type per file

2022-05-11 03:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ExecuteCommandEventArgs.cs
> +#nullable disable
All new API must be NRT annotated

2022-05-11 03:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +            => ((EventHandler)Events[s_commandChangedEvent]!)?.Invoke(this, e);
```suggestion
            => ((EventHandler?)Events[s_commandChangedEvent])?.Invoke(this, e);
```

2022-05-11 03:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +        void ICommandProvider.HandleCommandCanExecuteChanged(object sender, CommandEventArgs e)
To align with .NET runtime annotations:
```suggestion
        void ICommandProvider.HandleCommandCanExecuteChanged(object? sender, CommandEventArgs e)
```

ditto for other instances.

2022-06-17 07:48 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +            => ((EventHandler)Events[s_commandParameterChangedEvent]!)?.Invoke(this, e);
All of these are incorrect. Please refer to https://github.com/dotnet/winforms/pull/7143/files#r869843036

2022-06-17 07:49 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public virtual Object? DataContext
```suggestion
        public virtual object? DataContext
```

2022-06-17 07:50 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // enumerate
Whilst this is a good note, it's not required - we don't use linq in the codebase.

2022-06-17 16:55 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // enumerate
I can delete it, yes, but I think it didn't refer to LINQ. It's a copy-paste note from the original source. And I am not sure if it related to LINQ, but to For Each.

2022-06-23 02:27 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +            }
This was marked as new through resorting, but I never touched it.

2022-06-23 18:26 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public virtual Object? DataContext
Good catch, thanks!

2022-06-24 03:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            // The parent DataContext value, though, in that case would be null.
Please reformat to 120 chars long.
Applies to the added xml-docs as well.

2022-06-24 03:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            // The parent DataContext value, though, in that case would be null.
It'd be great if you could help me understand this comment. 

Here's what I understand:
- The form may have `DataContext` set.
- The container (i.e., parent of this control) may have had its `DataContext` set to null.

But from this point I get lost. The children of which control need to be notified?
And more generally, why do we care if `DataContext` is null to begin with?

2022-06-24 03:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        /// Occurs, when the Command property has changed.
```suggestion
        /// Occurs when the Command property has changed.
```

ditto other places

2022-06-24 03:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        /// <param name="e"></param>
Missing. Ditto other places.

2022-06-24 03:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +            ref ICommand? commandBackingField)
Keep this on the same line

2022-06-24 03:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        private void CommandCanExecuteChangedProc([AllowNull] object sender, EventArgs e)
```suggestion
        private void Command_CanExecuteChanged(object? sender, EventArgs e)
```
ditto other places

2022-06-24 03:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        protected static void RequestCommandExecute(ICommandProvider commandComponent)
We need to validate the args on the public API, and add xml-docs for the ANE.
```suggestion
        protected static void RequestCommandExecute(ICommandProvider!! commandComponent)
```
See https://github.com/dotnet/runtime/pull/64720.

Ditto other places that allow non-nullable input args.

2022-06-24 03:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +            => _bounds;
We generally don't wrap short lines.
```suggestion
        public virtual Rectangle Bounds => _bounds;
```

Ditto other places

2022-06-24 03:21 UTC, RussKie commented
@gewarren when you have a chance, may I get you to review from the docs perspective?

2022-06-24 03:25 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        protected void RaiseCommandCanExecuteChanged([AllowNull] object sender, EventArgs e);
This makes me uncomfortable - we don't have any public API like that (i.e., `RaiseXyz`) that accept `sender`. 
Why is `sender` necessary?

2022-06-24 22:43 UTC, gewarren reviewed
In case it's helpful, the guidelines for documenting event-related APIs are here: https://github.com/dotnet/dotnet-api-docs/wiki/Summary%3A-Event-related

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +        ///  Call base.CommandChanged to send this event to any registered event listeners.
Add a `<block>` element like this:

```
<block subset="none" type="overrides">
  Override this method to handle the event. In the overriding method, call ...
</block>
```

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        ///  An ambient property to hold a data source for binding purposes.
```suggestion
        ///  Gets or sets the data source for binding purposes.
```

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        ///  Reassignment to BindingSources or other binding mechanism is
This might belong in remarks instead of summary?

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        /// which should be assigned to the property.</param>
```suggestion
        /// that should be assigned to the property.</param>
```

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        /// As an example, a <see cref="Button"/> should call this method inside the method which
```suggestion
        /// As an example, a <see cref="Button"/> should call this method inside the method that
```

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        /// also raises the <see cref="Control.Click"/> Event of that Button, which
```suggestion
        /// also raises the <see cref="Control.Click"/> event of that Button, which
```

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        /// would be the <see cref="Button.OnClick(EventArgs)"/> OnClick method.
```suggestion
        /// is the <see cref="Button.OnClick(EventArgs)"/> method.
```

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
>          ///  Determines whether we set the ToolStripItem to its preferred size
```suggestion
        ///  Gets or sets a value that indicates whether to set the ToolStripItem to its preferred size.
```

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +        /// The bounds of the item
```suggestion
        /// Gets the bounds of the item.
```

2022-06-24 22:43 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +        ///  Determines whether or not the item can be selected.
```suggestion
        ///  Gets a value that indicates whether or not the item can be selected.
```

2022-06-27 03:52 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +        /// </summary>
An extra offset increases readability, e.g.:
![image](https://user-images.githubusercontent.com/4403806/175856645-41e35573-09a5-48c5-aef2-617c079354ce.png)

2022-06-28 01:09 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +        /// </summary>
We had problems in the past (Sandcastle) that those extra spaces where then in the docs. That's no longer a problem then anymore, I assume?

Also, we are not doing it in the runtime. So, why are we doing it differently?
Shouldn't we change it to be in parity with the runtime?

I personally don't like that additional character.

2022-06-28 01:21 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            // The parent DataContext value, though, in that case would be null.
`DataContext` is an ambient property. Like `Font`. So, if it's defined once in a parent control, children take that setting simply by referring to it. So, consider Form's DC is something, then a user control in that Form would also have that something as DC - because it's ambient. _Now_ you set the UserControl's DC explicitly to `null` in addition. In that moment you want to make sure, that those children again receive the DC changed, _even_ though technically theirs _is_ already `null` and their direct parent's is null.

2022-06-28 01:29 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        protected void RaiseCommandCanExecuteChanged([AllowNull] object sender, EventArgs e);
I was struggling with that as well, to be honest, but it seemed to be the most logical choice.
In this case, the ViewModel/DataSource had technically indicated the Command's execution context by raising that event. So, it should also be the ViewModel to be indicated as the sender, because _it is_ technically the sender.

Now, if it's more about obtaining the standard than the logic, that would also be fine with me.
I guess in that case, we would need to introduce additional `EventArgs`, and introduce something like `OriginalSender`. Would you feel more comfortable with that?

I'd also be interested in additional ideas around that. @Tanya-Solyanik, @JeremyKuhne?

2022-06-28 01:30 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        ///  Reassignment to BindingSources or other binding mechanism is
Oh, absolutely!

2022-06-28 02:33 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        }
This look strange to say the least....

2022-06-28 02:55 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        private void CommandCanExecuteChangedProc([AllowNull] object sender, EventArgs e)
As dicussed you may wnat to verify this is all we need:
```suggestion
        private void Command_CanExecuteChanged(object? sender, EventArgs e)
        {
           Command?.RaiseCommandCanExecuteChanged();
           Enabled = Command?.CanExecute(CommandParameter) ?? false;
        }
```

2022-06-28 03:17 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +        /// </summary>
We don't use Sandcastle. The docs are xml that gets turned into html, and html is indifferent to spaces.

> Also, we are not doing it in the runtime. So, why are we doing it differently?
> Shouldn't we change it to be in parity with the runtime?

Which runtime are you referring to? :) There are many differences between Windows Forms runtime and .NET runtime in various points.

2022-07-18 06:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/CommandComponent.cs
> +    public abstract class CommandComponent : BindableComponent, ICommandPropertyProvider
All new public API must be xml-doc annotated.

2022-07-18 06:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/CommandComponent.cs
> +        internal static readonly object s_commandChangedEvent = new object();
```suggestion
        internal static readonly object s_commandChangedEvent = new();
```

ditto other places

2022-07-18 06:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/CommandComponent.cs
> +        public abstract bool Enabled { get; set; }
This should be placed below `CommandParameterChanged`

2022-07-18 06:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public virtual object? DataContext
Should data context be a part of `CommandControl`?

2022-07-18 06:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
> +        public BindingContext BindingContext
What's the difference between `BindingContext` (used here) and `DataContext` (used in `Control`)?

2022-07-18 06:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandPropertyProvider.cs
> +    internal interface ICommandPropertyProvider
https://github.com/dotnet/winforms/issues/4895#issuecomment-1184777610 gives me an impression that the interface should go... Am I reading it correctly?

2022-07-19 16:00 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> -        internal virtual int DeviceDpi
Since we refactored the whole thing after the API review, the original code was restored (except one line), so this is no longer an issue.

2022-07-19 16:04 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +            ref ICommand? commandBackingField)
No longer applies.

2022-07-19 16:04 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandProvider.cs
> +        private void CommandCanExecuteChangedProc([AllowNull] object sender, EventArgs e)
It's gone.

2022-07-19 16:16 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        public virtual object? DataContext
No. `DataContext` is a carrier for data sources which need to be passed down the line. For example: A form consists of a series of UserControls. `DataContext` - as an ambient property - provides a central place to assign the data source. Now, since it's ambient - the data source is handed down to each respective child control in every container's `ControlsControllection`. The receiving [User]Controls get notified and can assign their BindingSources as they see fit. 

This API has been cleared by the API Review already.

2022-07-19 16:25 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandPropertyProvider.cs
> +    internal interface ICommandPropertyProvider
Well, yes and no. Certainly we don't need it publicly, because best practice is now to just inherit from `BindableComponent`, `CommandComponent` and `CommandControl`. This interface just helps to internally to not have redundant code. It's not exposed, so we meet their request.

2022-07-19 18:02 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +        /// </remarks>
Does no longer apply.

2022-07-20 02:14 UTC, RussKie reviewed
Looks good. 

As mentioned before all public API (i.e., marked as `public`, `protected` or explicit interface implementations) must be correctly xml-doc annotated.

2022-07-20 02:14 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
> +            }
Mixing backing fields (i.e., `_bindingContext`) and properties (i.e., `BindingContext`) often makes it harder to reason about the state. Can we use one or the other?
Also using `DataBindings` may force creation of the backing field, so should this be as follows?
```suggestion
            if (_bindingContext is not null && _dataBindings is not null)
            {
                for (int i = 0; i < _dataBindings.Count; i++)
                {
                    _bindingContext.UpdateBinding(_bindingContext, _dataBindings[i]);
                }
            }
```

Btw, this looks very strange: `BindingContext.UpdateBinding(BindingContext, ...)`

2022-07-20 02:14 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/CommandComponent.cs
> +        internal static readonly object s_commandCanExecuteChangedEvent = new();
Why are these leaking outside this type?
Ditto below

2022-07-20 02:14 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandPropertyProvider.cs
> +        public class CommandProviderManager
If we don't expect this to be inherited let's seal it, as it'd allow the compiler to do a better job.
```suggestion
        public sealed class CommandProviderManager
```

2022-07-20 02:14 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandPropertyProvider.cs
> +                if (!Equals(commandBackingField, newCommand))
Invert to reduce nesting

2022-08-01 18:33 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
> +            }
In this case `BindingContext` is the type name - we're calling the _static_ method 'UpdateBinding'. It may look a bit weird, but it should be fine like this.

2022-08-01 18:33 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandPropertyProvider.cs
> +        public class CommandProviderManager
Outdated.

2022-08-01 21:03 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +        ///  Call base.CommandChanged to send this event to any registered event listeners.
These comments don't make sense anymore, since we got rid of the respective base classes.

2022-08-03 06:23 UTC, RussKie requested changes
Looking good!

2022-08-03 06:23 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandBindingTargetProvider.cs
> +        /// Occurs, when the Command property has changed.
```suggestion
        /// Occurs when the <see cref="Command"/> property has changed.
```

ditto below

2022-08-03 06:23 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandBindingTargetProvider.cs
> +        /// can respond to user interaction.
This line is well under 120 chars, please keep it on the same line. Ditto other similar instances.

Please install the [editor guidelines extension](https://github.com/dotnet/winforms/blob/main/docs/developer-guide.md#machine-setup), which will help you in such situations.

2022-08-03 06:23 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandBindingTargetProvider.cs
> +        /// interface, when the assigned <see cref="Command"/> should be executed.
The summary should explain what the method does not who should call it. 
Who and/or when should invoke the method could be explained in the remarks section.

2022-08-03 06:23 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.cs
> +#pragma warning disable CA2252
As discussed please have comments added for all suppression/restorations similar to how we do the same in other places
![image](https://user-images.githubusercontent.com/4403806/182536393-8606fbc0-37bb-4b34-a789-f9631e408a8d.png)

2022-08-03 06:23 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +        /// </summary>
I don't think the last bit is nessecary. Ditto for the ButtonBase class
```suggestion
        /// <summary>
        ///  Gets or sets the <see cref="System.Windows.Input.ICommand"/> object whose <see cref="System.Windows.Input.ICommand.Execute(object?)"/>
        ///  method will be called when <see cref="Click"/> event is invoked.
        /// </summary>
```

2022-08-03 15:19 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +        ///  Call base.CommandChanged to send this event to any registered event listeners.
Yes, you're right.

2022-08-03 15:37 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
> +        ///  Call base.OnBindingContextChanged to send this event to any registered event listeners.
@gewarren: I would like to know if all that isn't some standard-ceremony kind of event lyrics, which (can) get inserted automatically?

2022-08-03 16:30 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +            // We need to opt into previre features here, because we calling a preview feature from the setter.
It'll not hurt either. If there is a need to document the conditional compilation directive to ignore the `RequiresPreviewFeatures`, then we should also include a hint, why this doesn't sit on top of the property, but rather on the getter and setter individually. I am changing the comment though, to reflect this clearer.

2022-08-03 16:32 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +            // TODO: Is passing 'this' correct here?
No. I need to talk with @JeremyKuhne about this.

2022-08-03 16:58 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +        // Called by the CommandProviderManager's internal DIM-based logic.
Rephrased.

2022-08-03 17:06 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        ///  the relevant data from the data context to a BindingSource component's <see cref="BindingSource.DataSource"/>.
Yes. But `BindingSource` was tagged a few words before, so I decided to not tag it again.
I saw that a few times in the docs, that APIs were tagged only on first occurrence, so I assumed that was best practice?

2022-08-03 18:16 UTC, gewarren commented on src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
> +        ///  Call base.OnBindingContextChanged to send this event to any registered event listeners.
I don't see anything about the standard text in the remarks either [here](https://github.com/dotnet/dotnet-api-docs/wiki/Summary%3A-Event-related) or in the Remarks section of the wiki. So I don't think you need to add it unless you want to.

2022-08-03 18:49 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ICommandBindingTargetProvider.cs
> +        /// interface, when the assigned <see cref="Command"/> should be executed.
Note, that this is all none-public.

2022-08-03 18:53 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +        /// </summary>
Let's put that in the remarks then.

2022-08-03 19:04 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +            // TODO: Is passing 'this' correct here?
@KlausLoeffelmann What else would you pass? The sender is this class. It would be odd to pass something different. I'd recommend reading the updated guidance on events in the latest Framework Design Guidelines to make sure we're in alignment.

2022-08-03 19:19 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
> +            // TODO: Is passing 'this' correct here?
Of course, I know the guidance on events, but I was wondering if it is that simple here. 
In WinForms, we don't have the concept of [RoutedEvents](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/events/routed-events-overview?view=netdesktop-6.0) which are bubbling up, like in WPF. And even if this doesn't apply here in the same way, technically, this Control is not the originator in this case, but a bound Data Source is, and the event is kind of passed on. It would be confusing, not have the Control as the sender all right, but at least I wanted to raise awareness of this.

If this becomes an issue, we can add the dedicated EventArgs with the original sender later. I don't think so it will though, since the originator will always be the assigned Data Source.

2022-08-07 03:13 UTC, RussKie commented
@KlausLoeffelmann I just come across this blog https://devblogs.microsoft.com/dotnet/announcing-the-dotnet-community-toolkit-800/. 
Do you think this work would make us compatible with [MVVM Toolkit](https://devblogs.microsoft.com/dotnet/announcing-the-dotnet-community-toolkit-800/#mvvm-toolkit)?

2022-08-07 18:59 UTC, KlausLoeffelmann commented
I don't see why not!
I will certainly take it into account, when we'll preparing the WinForms/MAUI example.

2022-08-08 04:15 UTC, RussKie approved these changes, later dismissed

2022-08-08 17:06 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
> +            [RequiresPreviewFeatures]
Q:  I see not all public properties has `RequiresPreviewFeatures` attribute. How are you deciding on this?

2022-08-08 17:20 UTC, dreddy-work approved these changes, later dismissed
RLGTM.

2022-08-08 17:20 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                if (Properties.ContainsObject(s_dataContextProperty) && Equals(ParentInternal?.DataContext, value))
Can you add a comment for this condition to make it clear? It seems you are also checking parent Internals context should be different from current context before setting the new value.

2022-08-08 17:22 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
> +            [RequiresPreviewFeatures]
Actually, the individual properties had been attributed before, and then we changed this to be on class level (line 14, which is including all the public members). So yes, these attributes are now redundant, good catch!

2022-08-08 17:30 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                if (Properties.ContainsObject(s_dataContextProperty) && Equals(ParentInternal?.DataContext, value))
Yes. If `DataContext` was different than its parent `DataContext`, and it's now about to become the same, we're removing the object altogether, since it's an ambient property and should inherit the (same) value from its parent. Added a comment.

2022-08-08 17:30 UTC, JeremyKuhne approved these changes, later dismissed

2022-08-08 17:32 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // When DataContext was different than its parent before, but now is is about to become the same,
```suggestion
                // When DataContext was different than its parent before, but now it is about to become the same,
```

2022-08-08 17:33 UTC, dreddy-work approved these changes

2022-08-08 17:34 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // When DataContext was different than its parent before, but now is is about to become the same,
Yeah, I saw that already... 😦 
Corrected!

2022-08-08 17:58 UTC, merged

2022-08-08 19:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +            // We won't let the preview feature warnings bubble further up beyond this point.
I don't really follow this comment. Do you mean that application that overrides this method will not  show the warning?

2022-08-08 19:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +        ///  Called in the context of <see cref="OnClick(EventArgs)"/> to invoke <see cref="System.Windows.Input.ICommand.Execute(object?)"/> if the context allows.
nit; this line is too long

2022-08-08 23:00 UTC, RussKie commented on src/System.Windows.Forms/src/Resources/SR.resx
> +    <value>Occurs whenever the bindable command changes.</value>
This wording is common for event handlers, and it's used in other parts of the codebase.

2023-08-07 22:41 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +        ///  Called in the context of <see cref="OnClick(EventArgs)"/> to invoke <see cref="System.Windows.Input.ICommand.Execute(object?)"/> if the context allows.
Corrected.

2023-08-07 22:42 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +            // We won't let the preview feature warnings bubble further up beyond this point.
No, but at one point we needed to protect the WinForms runtime against the Preview warnings themselves. It's gone now.

2023-08-07 22:43 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.cs
> +#pragma warning disable CA2252 // Suppress 'Opt in to preview features' (https://aka.ms/dotnet-warnings/preview-features)
Cut off the dependencies, when the consumer does not use the Preview feature directly. If we didn't do this, also using `OnFontChange` would have been considered a Preview feature, and so on, and so on.