Enable nullability in ToolStripItemInternalLayout
dotnet/winforms pull request #7298
Opened 2022-06-14 04:47 UTC by gpetrou

## Proposed changes

- Enable nullability in ToolStripItemInternalLayout.

2022-06-15 03:05 UTC, RussKie requested changes

2022-06-15 03:05 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
> +                    _lastPreferredSize = _currentLayoutOptions!.GetPreferredSizeCore(constrainingSize);
`GetLayoutData()` must be annotated with `MemeberNotNull`. Though I'm not sure, if the analyzer will see it.

`_currentLayoutOptions` will always be initialised if  `EnsureLayout()` is called, because it will get called at least once (for `_layoutData is null`) and, in turn, it'll invoke `PerformLayout()` that'll unconditionally invoke `GetLayoutData()`. So `EnsureLayout()` must be annotated with `MemeberNotNull(_currentLayoutOptions)`.

Please add a comment above `EnsureLayout` explaining this.

2022-06-15 04:50 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
> +                    _lastPreferredSize = _currentLayoutOptions!.GetPreferredSizeCore(constrainingSize);
Unfortunately, adding `MemberNotNull` for `_currentLayoutOptions` will not work, so I added a comment instead.

2022-06-15 08:27 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
> +                    _lastPreferredSize = _currentLayoutOptions!.GetPreferredSizeCore(constrainingSize);
Could you please elaborate why it won't work?

![image](https://user-images.githubusercontent.com/4403806/173780482-aefae7cd-a9c5-4525-8278-828d506c989d.png)

2022-06-16 04:53 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
> +                    _lastPreferredSize = _currentLayoutOptions!.GetPreferredSizeCore(constrainingSize);
This is what I see:
![image](https://user-images.githubusercontent.com/4172445/173993726-7f2ce8ae-e954-44e3-8408-4c17a5483690.png)
Perhaps it is because I still use VS 2022 17.2 version? I see lots of other warnings, but the build still works.

2022-06-16 06:05 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
> +                    _lastPreferredSize = _currentLayoutOptions!.GetPreferredSizeCore(constrainingSize);
👍 

We still need to do this:
```diff
diff --git a/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs b/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
index 6019222bb..469a5a04c 100644
--- a/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
+++ b/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
@@ -135,17 +135,15 @@ namespace System.Windows.Forms
             }
 
             [MemberNotNull(nameof(_layoutData))]
-            private bool EnsureLayout()
+            private void EnsureLayout()
             {
                 if (_layoutData is null || _parentLayoutData is null || !_parentLayoutData.IsCurrent(ParentInternal))
                 {
                     PerformLayout();
-                    return true;
                 }
-
-                return false;
             }
 
+            [MemberNotNull(nameof(_currentLayoutOptions))]
             private ButtonBaseAdapter.LayoutData GetLayoutData()
             {
                 _currentLayoutOptions = CommonLayoutOptions();
@@ -181,6 +179,7 @@ namespace System.Windows.Forms
             }
 
             [MemberNotNull(nameof(_layoutData))]
+            [MemberNotNull(nameof(_currentLayoutOptions))]
             internal void PerformLayout()
             {
                 _layoutData = GetLayoutData();
```

2022-06-17 06:09 UTC, RussKie approved these changes

2022-06-17 06:09 UTC, merged

2022-06-17 06:09 UTC, RussKie commented
Thank you