Enable nullability in TabControl
dotnet/winforms pull request #7316
Opened 2022-06-16 18:29 UTC by gpetrou

## Proposed changes

- Enable nullability in TabControl.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7316)

2022-06-17 06:00 UTC, RussKie commented
/azp run

2022-06-17 07:35 UTC, RussKie submitted a review, later dismissed
I'm going to look into this in more details next week.

2022-06-17 10:35 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +        private TabPage?[]? _tabPages;
I made it like that because we have existing calls like `_tabPages[_tabPageCount] = null;` and `_tabPages = null;`. Some of the `!` usages are to keep the existing tests happy and avoid changing the behavior. For example, `DeselectTab(tabPage!);`. Alternatively, we could change that to Nop or InvalidOperationException.

2022-06-23 10:50 UTC, vladimir-krestov reviewed
1) These changes looks good, but I really don't like how `_tabPages` was implemented before. Its usage looks too confusingly and not obvious. I spent time to understand that we won't catch NRE if try to get `_tabPages`, it will never be null when getting items, but the current implementation too unsafe and unstable. We have 2 related collections: `_tabPages` array (that tries to be as a List) and `_tabCollection` TabPageCollection. It looks strange, unsafe, unstable to me. And I would prefer to rework these collections in the future, not now, because it is risky.
Just my thoughts and FYI @RussKie.

2) Using of "!" operator looks complex and unreadable to me. If we have related checks in methods (like `index < _tabPageCount`, that means that `_tabPages` is not null), why not just to add null-checks (`if (_tabPages is not null) ...`) for `_tabPages` everywhere, where we are sure that it is not null. It would be more clear and readable to me, clear VisualStudio warnings and this way allows us to avoid of using "!" operator. @gpetrou, what do you think about this approach?

2022-06-28 18:16 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +                    if (_tabPages[i]!.Equals(tabPage))
This doesn't make sense. If input can be null and indexed tab page is not.

2022-06-28 18:19 UTC, dreddy-work requested changes
@gpetrou , i see multiple places where `!` operator is not meaningful. A little restructure of existing code would avoid it. Do you mind take a relook and see if we can make changes but not break existing apps.

2022-07-14 18:19 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +                    if (_tabPages[i]!.Equals(tabPage))
Sorry, you mean you want me to do a null check before calling this instead?

2022-07-14 18:22 UTC, gpetrou commented
> i see multiple places where `!` operator is not meaningful. A little restructure of existing code would avoid it. Do you mind take a relook and see if we can make changes but not break existing apps.

Can you please give me some examples? As I mentioned in https://github.com/dotnet/winforms/pull/7316#discussion_r899995657 some usages of `!` are because I wanted to avoid changes in behavior.

2022-07-14 18:24 UTC, gpetrou commented
> 2\. Using of "!" operator looks complex and unreadable to me. If we have related checks in methods (like `index < _tabPageCount`, that means that `_tabPages` is not null), why not just to add null-checks (`if (_tabPages is not null) ...`) for `_tabPages` everywhere, where we are sure that it is not null. It would be more clear and readable to me, clear VisualStudio warnings and this way allows us to avoid of using "!" operator.

I can try to add a separate commit and see how that looks like.

2022-07-19 06:14 UTC, RussKie commented
> I can try to add a separate commit and see how that looks like.

Yes, please

2022-12-13 23:33 UTC, dreddy-work commented
By revisiting this PR, it makes more sense to change type for `_tabPages` from array to list. It isn't directly exposed outside of this class.

2022-12-14 19:30 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +        private TabPage?[]? _tabPages;
Why can't this be `TabPage[]?`. Where am I missing the need to have a `null` in the array?

2022-12-14 19:34 UTC, JeremyKuhne commented
> By revisiting this PR, it makes more sense to change type for _tabPages from array to list. 

That seems orthogonal. `TabPage[]?` and `List<TabPage>?` are effectively the same from a nullability standpoint. We should first try to get the nulls out of the collection, then see if it is desirable (or even possible) to make the field itself non-nullable. If there is value to making it a `List<TabPage>?` that should be called out separately.

2022-12-14 19:34 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +        private TabPage?[]? _tabPages;
while removing the tab pages, we are filling the empty entries of array with null: https://github.com/dotnet/winforms/blob/503bff4ae3c967e975836d094e036f08b3429881/src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs#L1644

2023-02-28 19:56 UTC, gpetrou commented
@dreddy-work this one should be ready for review as well.

2023-03-13 18:15 UTC, gpetrou commented
@dreddy-work do you need any more changes on this one?

2023-03-13 19:23 UTC, dreddy-work commented
> @dreddy-work do you need any more changes on this one?

@gpetrou, haven't got chance to go over this again. Will do this week and update if anything needed here.

2023-03-31 04:59 UTC, gpetrou commented
@dreddy-work kind reminder on this one.

2023-04-27 17:48 UTC, dreddy-work commented
@gpetrou, Can you consider making the `_tabPages `variable read-only and assigning the list inline? This would allow us to check for `Count` where necessary and ignore the possibility of `null`. The `RemoveAll` method could just clear the list. Avoids `!`

2023-04-28 17:03 UTC, dreddy-work reviewed
Thank you. Seems some unit tests failed.

2023-04-28 17:03 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +        TabPage tabPage = TabPages[tabPageName]!;
```suggestion
        TabPage? tabPage = TabPages[tabPageName];
        ArgumentNullException.ThrowIfNull(tabPage);
```

2023-04-29 06:54 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +        TabPage tabPage = TabPages[tabPageName]!;
This already exists inside `DeselectTab` and seems to be more appropriate there than here.

2023-05-01 16:47 UTC, dreddy-work approved these changes

2023-05-01 16:48 UTC, merged