Enable nullability in RelatedImageListAttribute
dotnet/winforms pull request #7317
Opened 2022-06-16 19:02 UTC by gpetrou

## Proposed changes

- Enable nullability in RelatedImageListAttribute.

2022-06-17 06:03 UTC, RussKie commented
/azp run

2022-06-17 06:07 UTC, RussKie requested changes

2022-06-17 06:07 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/RelatedImageListAttribute.cs
>          public RelatedImageListAttribute(string relatedImageList)
We don't make any assumptions or assertions about `relatedImageList`
```suggestion
        private readonly string? _relatedImageList;

        public RelatedImageListAttribute(string? relatedImageList)
```

ditto below

2022-06-17 10:31 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/RelatedImageListAttribute.cs
>          public RelatedImageListAttribute(string relatedImageList)
This is currently used only with strings such as `[RelatedImageList("ListView.GroupImageList")]` in the codebase and the property is called like `RelatedImageList.Split('.');` in a couple of places. So, since there is no null check before `Split` I thought it is better to make it non-nullable as a suggestion.

2022-06-17 12:09 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/RelatedImageListAttribute.cs
>          public RelatedImageListAttribute(string relatedImageList)
This is used by (at least) the Windows Forms designer, and it's checked for nulls.
This is a public API which doesn't performs any null checks, so it means it can be a null :)

2022-07-18 17:53 UTC, dreddy-work approved these changes

2022-07-19 04:05 UTC, RussKie approved these changes

2022-07-19 04:05 UTC, merged