Fixing memory leaks of Numeric/DomainUpDown elements accessible objects
dotnet/winforms pull request #7330
Opened 2022-06-21 16:09 UTC by vladimir-krestov

Fixes #7328
⚠️Doesn't fix memory leaks of TextPattern. It will be fixed as another fix for TextBox as well.

## Proposed changes

- Rework and refactor accessible objects implementation of UpDown controls. Removed `ItemList` and Item accessible objects, because they are unnecessary. Moved the implementation to the base class. [This comment](https://github.com/dotnet/winforms/issues/4207#issuecomment-941950437) describes why we don't keep ItemsList anymore. 
- Add a call of `UiaDisconnectProvider` for `Numeric/DomainUpDown` elements (its textbox and buttons) when the control is disposing.

## Customer Impact

- Less memory leaks

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before

- There are some left objects in memory due to `UpDownEdit` and `UpDownButtons`:
![image](https://user-images.githubusercontent.com/49272759/174846510-c6be894d-d85d-43f0-b439-f52f93ca8991.png)

### After
- Memory is clear after disposing:
![image](https://user-images.githubusercontent.com/49272759/174846839-57c3faa0-b76c-495f-8bd6-4a42d2d5bb38.png)

## Test methodology
- CTI
- Manual
- Unit tests

## Accessibility testing 
- Using Narrator/Inspect and WinDbg

## Test environment(s) 
- .NET 7.0 Preview 4
- Windows 11

2022-06-22 06:19 UTC, RussKie commented
/azp run

2022-06-22 06:41 UTC, RussKie requested changes

2022-06-22 06:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
> -        public class DomainItemAccessibleObject : AccessibleObject
❗ We can't remove public API, this is a binary breaking change.
https://docs.microsoft.com/dotnet/api/system.windows.forms.domainupdown.domainitemaccessibleobject#applies-to

I have checked [public GitHub repos](https://github.com/search?l=C%23&p=14&q=DomainItemAccessibleObject&type=Code), and this types doesn't appear to be used. [.NET API catalog](https://apisof.net/catalog/3cc9a46b-db22-be36-1ac4-6f7b88abe571) doesn't appear to have any telemetry for this type either.
Since the docs have a disclaimer that this type shouldn't be used directly I think we _can_ obsolete this API with the error and replace implementations with `NotImplementedExceptions`.
![image](https://user-images.githubusercontent.com/4403806/174960036-8c1a9d74-24ce-44bd-a0f2-e0e9b590c126.png)

Still, we have to follow the obsoletion process https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/better-obsoletion.md.

In the subsequent release (e.g., in .NET 8 timeframe) we can consider removing the type completely.

2022-06-22 06:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
> -        public class DomainUpDownAccessibleObject : ControlAccessibleObject
ditto

2022-06-22 06:44 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
> -        public class DomainItemAccessibleObject : AccessibleObject
Good catch! Will return this type, thank you!

2022-06-23 15:15 UTC, vladimir-krestov commented
PS. These controls and their AO already have unit tests. There is no ability to add unit tests for the memory leak fix (for `UiaDisconnectProvider` method).

2022-06-24 02:40 UTC, RussKie submitted a review, later dismissed
👍 

The team has discussed the obsoletion, and it was decided that we should obsolete the two defunct types with `[ObsoleteAttribute(..., IsError = false)]`. Please raise a new issue to track this work, and I'll work with you on that once this is merged.

2022-06-24 02:41 UTC, RussKie commented
Multile test failures:
```
System.NullReferenceException : Object reference not set to an instance of an object.

System.Windows.Forms.Tests.DirectionButtonAccessibleObjectTests.DirectionButtonAccessibleObject_Invoke_ChangesValue_InDomainUpDown(Int32 childId, Int32 expectedIndex) in /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DirectionButtonAccessibleObjectTests.cs:line 40
```

2022-06-24 12:39 UTC, vladimir-krestov commented
> we should obsolete the two defunct types with `[ObsoleteAttribute(..., IsError = false)]`

#7344

2022-06-24 15:21 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
> +                        UiaCore.UiaDisconnectProvider(_downButton!);
Added these changes to release navigation button AOs that Narrator keeps.
Used "!" here, because we don't care if these field are null. `UiaDisconnectProvider` doesn't throw an exception for null.
Moreover, 99% that these field won't be null because they will be created in first call of `FragmentNavigate`.

2022-06-27 18:50 UTC, vladimir-krestov commented
CTI approved the fix ✔️

2022-06-28 01:36 UTC, RussKie requested changes
A little more work to do

2022-06-28 01:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
> +        // We can't remove this class just like that because it's a public API.
👍

2022-06-28 01:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
> -            private DomainItemListAccessibleObject? _domainItemList;
I've looked at the dotnet/runtime codebase, and no code is being deleted when types/members are marked as obosolete. We shouldn't do it either.

2022-06-28 01:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
Could you please help me understanding this comment?

2022-06-28 01:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
> +                        UiaCore.UiaDisconnectProvider(_downButton!);
> `UiaDisconnectProvider` doesn't throw an exception for null.

Then we need to update the NRTA for this API, and don't use `!`.

2022-06-28 01:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
> +        /// </summary>
This is a public API, and it needs to be [documented/annotated correctly](https://docs.microsoft.com/dotnet/api/system.windows.forms.control.createaccessibilityinstance). In this case though, it doesn't look like there are any special conditions to document, and the docs will be inherited from the base. Please use `<inheritdoc />` instead.

2022-06-28 01:36 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
> +        // We can't remove this class just like that because it's a public API.
```suggestion
        // This class is not used anyhow for building of DomainUpDown accessibility tree, but
        // we can't remove this class just like that because it's a public API.
        // See https://github.com/dotnet/winforms/issues/7344 for more details.
```

2022-06-28 09:34 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
> +                        UiaCore.UiaDisconnectProvider(_downButton!);
I wasn't right. This API doesn't support null arguments. Yes, we can call it with null and we won't catch an exception, but in this case it returns an [error code](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcoreapi/nf-uiautomationcoreapi-uiadisconnectprovider#return-value).

2022-06-28 13:40 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
> +        /// </summary>
Doesn't it inherit by default without `<inheritdoc />`?

2022-06-28 14:28 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
The base `CreateAccessibilityInstance` method already returns a correct object for `DomainUpDown`, we don't need `DomainUpDownAccessibleObject` for it. I proposed to remove this line when `DomainUpDownAccessibleObject` is removed or marked as "obsolete".

2022-06-28 14:46 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
> -            private DomainItemListAccessibleObject? _domainItemList;
Returned all back. Anyway, there are no leaks.

2022-07-08 09:10 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
> +        /// </summary>
@RussKie, please check it

2022-07-29 18:00 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
> +                    if (OsVersion.IsWindows8OrGreater)
i see OS check was already made by caller. Do you expect this to be reused elsewhere?

2022-08-02 11:00 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
Removed this comment, we can't remove public `DomainUpDownAccessibleObject`.

2022-08-02 11:05 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>          public class DomainUpDownAccessibleObject : ControlAccessibleObject
No, a public class can't be inherited from a private/internal class (VS throws an error)

2022-08-02 11:15 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownBaseAccessibleObject.cs
> +                    AccessibleRole role = Owner.AccessibleRole;
I wouldn't take this way because we call the complex `AccessibleRole` getter 2 times, that is not productive.
```cs
public override AccessibleRole Role
     => Owner.AccessibleRole != AccessibleRole.Default
          ? Owner.AccessibleRole
          : AccessibleRole.SpinButton;
```

So, I will use this approach:
```cs
public override AccessibleRole Role
{
     get
     {
          AccessibleRole role = Owner.AccessibleRole;

          return role != AccessibleRole.Default
               ? role
               : AccessibleRole.SpinButton;
     }
}
```

2022-08-02 12:13 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
> +                            Debug.Assert(result == HRESULT.S_OK);
@Tanya-Solyanik, I saw your [comment](https://github.com/dotnet/winforms/pull/7319#pullrequestreview-1050060036), but I don't see the reason, why do we need to do it? There are no leaks after disposing, so what is the reason?

2022-08-02 21:46 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
> +                            Debug.Assert(result == HRESULT.S_OK);
Reason is to not disconnect twice. ReleaseUIAProvider is called from WM_DESTROY message handler. We are usually disposing managed controls in response to this message as well. However in the Dispose sequence we can also reference the _upButton provider. We should not do it because this provider is not in the accessibility client process space anymore. Also this is a guard against a potential double-disconnect.

2022-08-02 22:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>          public class DomainUpDownAccessibleObject : ControlAccessibleObject
Good point, but you can have a private field `UpDownBaseAccessibleObject` in this class and redirect all calls to the corresponding calls in _upDownBaseAccessibleObject. 
The reason is to make the code obviously redundant rather than trying to explain that in the comment.

2022-08-02 22:12 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownBaseAccessibleObject.cs
> +                    AccessibleRole role = Owner.AccessibleRole;
Sounds good, but I don't see this change applied, thus re-activating the comment.

2022-08-03 01:09 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
> +        /// </summary>
I think that `<inheritdoc />` is redundant in this case, intellisense reads the comment from the base. @RussKie - are you ok with removal of this comment?

2022-08-03 09:30 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>          public class DomainUpDownAccessibleObject : ControlAccessibleObject
I wouldn't do it.
1. I don't want change "private" to "internal" of `UpDownBaseAccessibleObject` for it only
2. I can create `_upDownBaseAccessibleObject` field, but there is no way to set some instance for it
3. The implementation will be bulky and strange
4. We have no time before RC2

A comment much simpler and faster. Do you agree?

2022-08-03 09:50 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
>          internal class DomainItemListAccessibleObject : AccessibleObject
I want to delete it at all. It's used for private filed and property of obsolete `DomainUpDownAccessibleObject`, so removing of this file and the private filed and property won't affect users. I don't see risks without cases of using reflection by users (unlikely). So, @Tanya-Solyanik, @RussKie, can I remove this file?

2022-08-03 09:54 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
> +                    if (OsVersion.IsWindows8OrGreater)
Good point, no, it's won't be reused. Thanks, will remove this extra check

2022-08-03 19:05 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>          public class DomainUpDownAccessibleObject : ControlAccessibleObject
No, I don't agree, comment is not obviously true if looking a this file only - one has to read 2 classes instead of seeing obvious redirect from one to another. Changing private to internal is not a breaking change. I think that number of lines of code will be less than it is now.

However this is not worth a discussion.

2022-08-03 19:10 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
>          internal class DomainItemListAccessibleObject : AccessibleObject
I suggest removing this file in NET8, when we properly obsolete the unused objects. Please add it to the follow up work item.

2022-08-03 19:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
> +        [Obsolete("This public class is not necessary anymore for building of DomainUpDown accessibility tree after https://github.com/dotnet/winforms/issues/4207.", false)]
Is text of this warning visible to developer who uses this class? I think the message should call out `nameof(DomainUpDown.DomainItemAccessibleObject)` rather than say "this class".
You should be able to use operator `nameof` in the warning text.

2022-08-03 19:30 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
> +                    _upButton = null;
This can be executed only when we know that the provider is not null. I.e. move to after line 126. And the same with _downButton

2022-08-04 19:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
> +        [Obsolete("This public class is not necessary anymore for building of DomainUpDown accessibility tree after https://github.com/dotnet/winforms/issues/4207.", false)]
@JeremyKuhne - could you please review this obsoletion?

2022-08-04 21:38 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
> +        [Obsolete("This public class is not necessary anymore for building of DomainUpDown accessibility tree after https://github.com/dotnet/winforms/issues/4207.", false)]
This was never meant to be used from user code anyway. It should get:

``` C#
[EditorBrowsable(EditorBrowsableState.Never)]
[Obsolete($"{nameof(DomainItemAccessibleObject)} is no longer used to provide accessible support for {nameof(DomainUpDown)} items.", error: false)] 
```

2022-08-04 21:44 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
>          internal class DomainItemListAccessibleObject : AccessibleObject
I wouldn't bother keeping this as there is no direct way to create it as an end user. All we do is cast to it (for some reason). Just kill this and change `DomainItemAccessibleObject.Parent` to always return null.

2022-08-04 21:46 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>          public class DomainUpDownAccessibleObject : ControlAccessibleObject
Same comment as https://github.com/dotnet/winforms/pull/7330/files#r938267721

2022-08-04 22:35 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
> +        [Obsolete("This public class is not necessary anymore for building of DomainUpDown accessibility tree after https://github.com/dotnet/winforms/issues/4207.", false)]
Thank you, Is this a compile time error?

2022-08-04 22:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>          public class DomainUpDownAccessibleObject : ControlAccessibleObject
@JeremyKuhne - I don't follow your suggestion. Are you saying we can make `DomainUpDownAccessibleObject` obsolete now?

My comment was about making code in this class look obsolete - for example copy/paste content of UpDownBaseAccessibleObject.cs

2022-08-05 00:09 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
>          internal class DomainItemListAccessibleObject : AccessibleObject
Sounds good

2022-08-05 04:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>          public class DomainUpDownAccessibleObject : ControlAccessibleObject
Things that are for internal use only per the docs should be hidden from intellisense.

2022-08-07 08:42 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
>          internal class DomainItemListAccessibleObject : AccessibleObject
Removed the class, but it changed NRTA of `DomainItemAccessibleObject.Parent.get` (see `PublicAPI.Shipped.txt`).
For the rest, everything is ok.

2022-08-07 10:27 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>          public class DomainUpDownAccessibleObject : ControlAccessibleObject
@Tanya-Solyanik, looks like I see your idea, I have reworked this class to reflect on `UpDownBaseAccessibleObject`, please check

2022-08-08 05:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>          public class DomainUpDownAccessibleObject : ControlAccessibleObject
Hm, they are still not identical.

2022-08-08 06:26 UTC, Tanya-Solyanik reviewed
I added a couple of comments, the rest looks good.

@JeremyKuhne - Since DomainUpDownAccessibleObject class is obsolete now, would it make sense to remove the Create method from DomainUpDown control and rely on the UpDownBase create method?

2022-08-08 06:26 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(_upDownButtons.AccessibilityObject);
It is possible that we are forcing creation of AOs here, can we delegate disconnect to the `UpDownButtons` class? For example implement internal UpDownButtons.DisconnectProvider method?

2022-08-08 06:26 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(_upDownButtons.AccessibilityObject);
And the same for UpDownEdit

2022-08-08 19:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/misc/Obsoletions.cs
> +    internal const string DomainUpDownAccessibleObjectMessage = $"{nameof(System.Windows.Forms.DomainUpDown.DomainUpDownAccessibleObject)} is no longer used to provide accessible support for {nameof(
```suggestion
    internal const string DomainUpDownAccessibleObjectMessage = $"{nameof(System.Windows.Forms.DomainUpDown.DomainUpDownAccessibleObject)} is no longer used to provide accessible support for {nameof(System.Windows.Forms.DomainUpDown)} controls.";
```

2022-08-08 19:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
> +        [Obsolete($"{nameof(DomainUpDownAccessibleObject)} is no longer used to provide accessible support for {nameof(DomainUpDown)} control.", error: false)]
Did you intend to use the new message defines in `obsoletions.cs`?

2022-08-08 19:54 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +|  __`WINFORMS0001`__ | `DomainUpDown.DomainUpDownAccessibleObject` is no longer used to provide accessible support for `DomainUpDown` items. |
We are using a different ID format here - https://github.com/dotnet/winforms/blob/84042a843540a07a6c64fb6fb36006e5f2fe8fd4/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs#L76

2022-08-08 20:21 UTC, vladimir-krestov commented on docs/list-of-diagnostics.md
> +|  __`WINFORMS0001`__ | `DomainUpDown.DomainUpDownAccessibleObject` is no longer used to provide accessible support for `DomainUpDown` items. |
So here are 2 options:
1. Change the new Id names and the new documentation
2. Change `Message.cs` Id naming to the new format

Which one should I use?

2022-08-08 20:24 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
> +        [Obsolete($"{nameof(DomainUpDownAccessibleObject)} is no longer used to provide accessible support for {nameof(DomainUpDown)} control.", error: false)]
Implemented, thanks

2022-08-08 20:25 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(_upDownButtons.AccessibilityObject);
Great catch! Actually, the buttons and the edit are controls, so they can release their AO themself. Moreover, now I don't do double disconnecting for them.

2022-08-08 20:26 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +|  __`WINFORMS0001`__ | `DomainUpDown.DomainUpDownAccessibleObject` is no longer used to provide accessible support for `DomainUpDown` items. |
Follow the existing pattern. Also please add message warnings to the .md file

2022-08-08 20:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs
> +                if (IsAccessibilityObjectCreated
I think it makes sense to add a `bool TryGetAccessibilityObject(out AccessibleObject accessibeObject)` to control class to handle use cases like this one. It probably logically belongs to your refactoring PR.

2022-08-08 20:36 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/misc/Obsoletions.cs
> +    // The diagnostic ids reserved for obsoletions are SYSLIB0### (SYSLIB0001 - SYSLIB0999).
Why does this comment mention SYSLIB? Should it be replaced with WFDEVXXX?

2022-08-08 20:37 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/misc/Obsoletions.cs
> +    internal const string DomainUpDownAccessibleObjectDiagId = "WINFORMS0001";
`Diag` -> `Diagnostics` or `Warning`

2022-08-08 20:47 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/misc/Obsoletions.cs
> +    internal const string DomainUpDownAccessibleObjectDiagId = "WINFORMS0001";
I like `Diagnostic`

2022-08-08 20:50 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/misc/Obsoletions.cs
> +    // The diagnostic ids reserved for obsoletions are SYSLIB0### (SYSLIB0001 - SYSLIB0999).
Actually, I don't know where Igor took it. But it should be WFDEV###, I guess.

2022-08-08 20:52 UTC, vladimir-krestov commented on docs/list-of-diagnostics.md
> +|  __`WINFORMS0001`__ | `DomainUpDown.DomainUpDownAccessibleObject` is no longer used to provide accessible support for `DomainUpDown` items. |
@Tanya-Solyanik, please see 4th commit, it affects `Message.cs`. Do you like it?

2022-08-08 20:57 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +        * `<Compile Include="$(CommonPath)System\Obsoletions.cs" Link="Common\System\Obsoletions.cs" />`
This is not the right folder, this file is in `misc`

2022-08-08 20:58 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs
> +                if (IsAccessibilityObjectCreated
Will consider it in scope of #7362

2022-08-08 20:59 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +        * `<Compile Include="$(CommonPath)System\Obsoletions.cs" Link="Common\System\Obsoletions.cs" />`
Obsoletions should really be moved to a folder that could be linked into all projects

2022-08-08 21:00 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +        * `<Compile Include="$(CommonPath)System\Obsoletions.cs" Link="Common\System\Obsoletions.cs" />`
For example - C:\WinForms\src\Common\src

2022-08-08 21:02 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
> +            DiagnosticId = "WFDEV002")]
@JeremyKuhne  - I think you had used the same warning ID intentionally, no?

2022-08-08 21:03 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> +~virtual System.Windows.Forms.ToolStripItem.OnRequestCommandExecute(System.EventArgs e) -> void
@vladimir-krestov - seems like your change collided with Klaus' PR, please re-generate this file

2022-08-08 21:05 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
> +            DiagnosticId = "WFDEV002")]
Yes, there is no need for separate IDs as these are the same root cause.

2022-08-08 21:09 UTC, vladimir-krestov commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
> +            DiagnosticId = "WFDEV002")]
Which message should I use for the docs?

2022-08-08 21:16 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
> +            DiagnosticId = "WFDEV002")]
I would say - all of them each on a new line. Ultimately this does not matter.

2022-08-08 21:17 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/misc/Obsoletions.cs
> +    // The diagnostic ids reserved for obsoletions are SYSLIB0### (SYSLIB0001 - SYSLIB0999).
He copied it from the runtime :) But we can modify it to suite our needs

2022-08-08 21:40 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +|  __`WINFORMS0001`__ | `DomainUpDown.DomainUpDownAccessibleObject` is no longer used to provide accessible support for `DomainUpDown` items. |
I would prefer to have Obsoletions.cs file in a common folder, to be shared among all projects when needed. I expect this to be a quick change. Anyway it might be prudent to send privates to Olina for a quick re-test, so I think you have time to move that file.

2022-08-08 21:54 UTC, vladimir-krestov commented on docs/list-of-diagnostics.md
> +        * `<Compile Include="$(CommonPath)System\Obsoletions.cs" Link="Common\System\Obsoletions.cs" />`
If to move it to the common folder, projects will throw build error, because, for example, S.W.F.Primitives project can't link to `System.Windows.Forms.DomainUpDown.DomainUpDownAccessibleObject`. Primitives project doesn't have references to System.Windows.Forms namespace. So, I will move the file, but propose to resolve this issue later.

2022-08-08 22:21 UTC, Tanya-Solyanik approved these changes
Looks good, thanks!

2022-08-08 22:48 UTC, RussKie commented
For the context, which I failed to provide yesterday to @vladimir-krestov (it was late on my end) - I copied `Obsoletion.cs` and the doc from dotnet/runtime:
* https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/Obsoletions.cs
* https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md

2022-08-08 22:51 UTC, RussKie commented on docs/list-of-diagnostics.md
> +|  __`WFDEV001`__ | Casting to/from IntPtr is unsafe, use `ResultInternal`. |
These are all dupes, we should keep only one

2022-08-08 22:54 UTC, vladimir-krestov commented on docs/list-of-diagnostics.md
> +|  __`WFDEV001`__ | Casting to/from IntPtr is unsafe, use `ResultInternal`. |
Tanya proposed this way: https://github.com/dotnet/winforms/pull/7330#discussion_r940671358
I agree, because they have different messages. Do you think that I should keep only one of them?

2022-08-08 23:07 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
> +            if (!_upDownEdit.SupportsUiaProviders)
FYI: `UpDownEdit` inherits from `TextBox` that doesn't support UIA. So `ReleaseUiaProvider` is not call for `UpDownEdit` in `Control.WmDestroy` (line 12326) because it has `SupportsUiaProviders` check. So we need this check to release its objects from memory, otherwise it doesn't work. When we implement UIA supporting for `TextBox`, this check will save us from double disconnection.

2022-08-09 08:40 UTC, vladimir-krestov commented
CTI approved the fix ✅

2022-08-09 22:29 UTC, Tanya-Solyanik commented on docs/list-of-diagnostics.md
> +|  __`WFDEV001`__ | Casting to/from IntPtr is unsafe, use `ResultInternal`. |
Why not document all messages?

2022-08-09 22:30 UTC, Tanya-Solyanik commented
I reformatted Obsolete attributes as multilines.

2022-08-09 22:31 UTC, Tanya-Solyanik approved these changes
Thank you!

2022-08-09 23:00 UTC, merged

2022-08-09 23:26 UTC, RussKie commented on docs/list-of-diagnostics.md
> +|  __`WFDEV001`__ | Casting to/from IntPtr is unsafe, use `ResultInternal`. |
Ah, I can now see the types are different `WParamInternal`, `LParamInternal`, `ResultInternal`.... My eyes must have been tired to notice this.
I think thse can be combined, but I don't have a strong opinion.

2022-08-09 23:37 UTC, RussKie commented
@vladimir-krestov please raise a breaking docs issue in https://github.com/dotnet/docs/issues/new/choose
You can see examples of how we've done this [here](https://github.com/dotnet/docs/issues?q=label%3Adotnet-winforms%2Ftech+is%3Aclosed+label%3Abreaking-change).

2022-08-12 06:08 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
@vladimir-krestov @Tanya-Solyanik could you please help me understand this? `DomainUpDownAccessibleObject` is now marked as obsolete, shouldn't this be removed completely, so that we would invoke `UpDownBase.CreateAccessibilityInstance()`?

2022-08-12 06:23 UTC, RussKie commented
@vladimir-krestov @Tanya-Solyanik I would also apprecite it if you could help me filling the blanks in https://github.com/dotnet/docs/issues/30640. Thank you.

2022-08-12 16:00 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
I would like to remove it, it looks incorrect when we still use obsolete class, it's a bad example. So, created #7584
Tanya noted about it (https://github.com/dotnet/winforms/pull/7330#pullrequestreview-1064624409), I agree with it.
@JeremyKuhne, could you please give your opinion?

2022-08-12 17:12 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
Let me sync with Jeremy. Maybe I misinterpreted his comments, I thought we should keep that returning this class from the `create` method.

2022-08-12 19:19 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
We'll be conservative inNET7 and will remove the create methos in NET8 if compat rules allow us to remove an override

2022-08-13 01:58 UTC, Tanya-Solyanik commented
> if you could help me filling the blanks in https://github.com/dotnet/docs/issues/30640.

done

2022-08-15 08:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
My recollection of the outcomes of the obsoletion discussion was that we don't remove the obsolete code - i.e., `DomainUpDownAccessibleObject` definition remains in the codebase. 
When we obsolete a type we need to provide an alternative, and I'm struggling to understand what the alternative is. That is, a developer will now get `WFDEV002`, and they want to update the code. IIUIC, the correct behaviour now is to use the accessibility object provided by `UpDownBase`, but a developer using an instance of `DomainUpDown` won't be able to get it because that types overrides the base with the obsolete member.

Perhaps I'm completely missing it, but right now it feels we regressed the devex...

2022-08-15 08:29 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
The compat rules are [here](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md). Adding and removing overrides is completely [acceptable](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#members), and we've been leaning on this rules quite actively for all the accessibility work.

2022-08-15 08:34 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>              }
Still trying to figure out....
`DomainUpDownAccessibleObject` now proxies everything to `UpDownBaseAccessibleObject` to facilitate the correct behaviour. So what's the point of obsoleting `DomainUpDownAccessibleObject`?

2022-08-16 05:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
> +            => new DomainUpDownAccessibleObject(this);
>My recollection of the outcomes of the obsoletion discussion was that we don't remove the obsolete code - i.e., DomainUpDownAccessibleObject definition remains in the codebase.

This is exactly what I'm suggesting. Remove the create method, not the type in NET8.
DomainUpDownAccessible object does not have any public methods, only `public override`s, so it is completely replaceable by casting instance created by CreateAccessibilityInstance method to ControlAccessibleObject.

2022-08-19 18:34 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
>              }
Please see the following thread: https://github.com/dotnet/winforms/pull/7330#discussion_r936067830