Update AccessibilityApp as .Net 4.8.1 updated, fix GH issues: 7336, 7337
dotnet/winforms pull request #7359
Opened 2022-06-28 09:49 UTC by Olina-Zhang

Fixes #

Update Accessibility testing application as .Net 4.8.1 we did, and fix GH issues: https://github.com/dotnet/winforms/issues/7336, https://github.com/dotnet/winforms/issues/7337

## Customer Impact
N/A

## Regression? 

No

## Risk

No

2022-06-29 00:49 UTC, RussKie requested changes

2022-06-29 00:49 UTC, RussKie commented on Winforms.sln
> -Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "AccessibilityTests", "src\System.Windows.Forms\tests\AccessibilityTests\AccessibilityTests.csproj", "{A9F13504-5560-4CC7-80A2-11E23E5852E1}"
@Olina-Zhang you're deleting an existing project and replacing it with another. You're also adding files for the new project, however you're not deleting files from the old project...

Also some of the added files lack the required headers, e.g.:
```
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
```

2022-06-29 00:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/PrintingControls.cs
> +
Please remove this blank line, it breaks style rules and causes a build break

2022-06-29 00:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/PrintingControls.cs
> +
nit: we are trying to get rid of extra blank lines in this code base.

2022-06-29 00:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/PrintingControls.cs
> +        int totalnumber = 0;//this is for total number of items of the list or array
nit: we are usually capitalizing words in local variable names: totalNumber

2022-06-29 00:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/PrintingControls.cs
> +        int totalnumber = 0;//this is for total number of items of the list or array
Please remove initialization to `0` from integers because they are initialized like this by default.

2022-06-29 00:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/RemainingControls.cs
> -﻿// Licensed to the .NET Foundation under one or more agreements.
I think we do need the license header in these files.

2022-06-29 00:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/RemainingControls.cs
> +
This blank line breaks the build

2022-06-29 00:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/RemainingControls.Designer.cs
> +            this.Text = "RamainingControls";
typo: Remaining

2022-06-29 00:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/PrintingControls.Designer.cs
> +            this.label1.Text = "Please inout you want to print";
`&Input text` is a better choice because it provides a shortcut key. Also please fix a typo.

2022-06-29 04:11 UTC, RussKie reviewed
Do the samples need to be localized? If not, please remove all the added xlf files.

2022-06-29 05:38 UTC, Olina-Zhang commented
> Do the samples need to be localized? If not, please remove all the added xlf files.

Removed it, the app doesn't need.

2022-06-29 22:33 UTC, Tanya-Solyanik reviewed
I added a couple of nits

2022-06-29 22:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/CommonControl1.cs
> +            //comboBox8.SelectedText = "row6";
If these lines are not needed, please remove them.

2022-06-29 22:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/DataControls.cs
>              //this.dataGridView2.DataSource = dt;
Please remove this line if it is not used

2022-06-29 22:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/DataControls.cs
> +            this.bindingNavigator1.AccessibilityObject.RaiseAutomationNotification(
FYI: we don't use `this` modifier in this code base, could you please run a global replace and get rid of these modifiers.

2022-06-29 22:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/DialogControls.cs
> +            ColorDialog colordialog = new ColorDialog();
Could you please use camel casing? colorDialog?

2022-06-29 22:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/DialogControls.cs
> +            FontDialog fontdialog = new FontDialog();
nit: `fontDialog`

2022-06-29 22:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/Main.cs
> +            CommonControl1 commontrol1 = new CommonControl1();
nit: `commonControl1 `

2022-06-29 22:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/PrintingControls.cs
> +            Brush bru = Brushes.Blue;
nit: `brush`

2022-06-29 22:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/PrintingControls.cs
> +                e.Graphics.DrawString(this.txtPrint.Text.ToString() + " " + totalNumber.ToString(), font, bru, 50, currentY);//print each item
```suggestion
                // Print each Item.
                e.Graphics.DrawString($"{txtPrint.Text} {totalNumber}", font, brush, 50, currentY);
```

2022-06-29 22:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/AccessibilityTests/Program.cs
> +            Application.SetHighDpiMode(HighDpiMode.PerMonitorV2);
Nice!

2022-06-30 20:05 UTC, Tanya-Solyanik approved these changes
Thank you! Looks good!

2022-07-01 01:50 UTC, Olina-Zhang commented on Winforms.sln
> -Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "AccessibilityTests", "src\System.Windows.Forms\tests\AccessibilityTests\AccessibilityTests.csproj", "{A9F13504-5560-4CC7-80A2-11E23E5852E1}"
I have removed the original entire project and replaced a new one. And added above licensed headers for every form.cs file.

2022-07-05 17:10 UTC, merged