Attempt to get the default error icon from the OS
dotnet/winforms pull request #7402
Opened 2022-07-13 02:33 UTC by 0xC0000054

Fixes #7390

## Proposed changes

- ErrorProvider attempts to get the default error icon from the operating system.

## Customer Impact

- The error icon should now match the one used by the MessageBox/TaskDialog.

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before

![WinForms ErrorProvider icon](https://user-images.githubusercontent.com/26996983/178137141-891719cb-f298-4972-b669-e3ad04ebd420.png)

### After

 ![Win10 Error icon](https://user-images.githubusercontent.com/26996983/178137230-469573c3-3256-4d00-8db8-2d34ddc31336.png) (Win10 21H2)

## Test methodology 

- Manually tested the change in a winforms app
 

## Test environment(s) 

- 7.0.100-preview.5.22307.18

2022-07-13 02:34 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=7402) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=7402) before we can accept your contribution.<br/><br/>:x: 0xC0000054 [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=7402)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=7402) it.</sub>

2022-07-18 19:49 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGetStockIconInfo .cs
> +
@0xC0000054 , compiler warning about this empty line.  Can you please make the correction to get the buil pass?

2022-07-19 00:01 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
> +                static unsafe Icon GetDefaultIcon()
Proposal by @JeremyKuhne on the original issue was to add an API in runtime similar to this and use it in higher stack apps . At the same time, I see runtime has not prioritized the issue yet. @JeremyKuhne , any inputs on this?

2022-07-19 03:32 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
> +                static unsafe Icon GetDefaultIcon()
Looks like https://github.com/dotnet/runtime/issues/67040 _may_ be a candidate for .NET 8. I think we can take this with a view that this will be revisited/updated when the .NET runtime API is available.

2022-07-19 03:41 UTC, RussKie requested changes

2022-07-19 03:41 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGetStockIconInfo .cs
> +        public enum SHSTOCKICONID
Please move to Interop.SHSTOCKICONID.cs

Please have all values aligned, e.g.:
```cs
        public enum SHSTOCKICONID
        {
            DOCNOASSOC      = 0,
            DOCASSOC        = 1,
            APPLICATION     = 2,
        }
```

And lastly, since we have no use for all values, keep only those that are required and remove all others.

2022-07-19 03:41 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGetStockIconInfo .cs
> +        public enum SHGSI
Ditto

2022-07-19 03:41 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGetStockIconInfo .cs
> +        public unsafe struct SHSTOCKICONINFO
Ditto

2022-07-19 03:41 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGetStockIconInfo .cs
> +        [DllImport(Libraries.Shell32, ExactSpelling = true)]
Please use `LibraryImport` instead of `DllImport`.

2022-07-19 03:41 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGetStockIconInfo .cs
> +                                                               SHSTOCKICONINFO* psii);
[nit] this can be a oneliner

2022-07-19 08:16 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGSI.cs
> +            SMALLICON = 0x000000001,
```suggestion
            ICON      = 0x000000100,
            SMALLICON = 0x000000001,
```

2022-07-19 08:17 UTC, RussKie approved these changes
👍 LGTM

2022-07-19 16:44 UTC, AaronRobinsonMSFT commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHSTOCKICONINFO.cs
> +        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
The `CharSet` also applies to the `char` type when using `DllImport`, but the rules aren't obvious and the inline fixed array exacerbates that case. The rules with `LibraryImport` are much clearer in this case. Stating the `CharSet` here is appropriate.

2022-07-20 01:57 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHSTOCKICONINFO.cs
> +        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
🤯 Thank you

2022-07-20 01:57 UTC, RussKie approved these changes

2022-07-27 00:22 UTC, merged