Fixing incorrect selection of ListViewGroup for ListView.GroupCollapsedStateChanged event (#6708)
dotnet/winforms pull request #7412
Opened 2022-07-14 10:44 UTC by NikitaSemenovAkvelon

Fixes #6708

## Proposed changes

- Processed all unique groups of selected items through collapse. The collapse state had been validated in cycle and correct group(s) triggered for GroupCollapsedStateChanged.

## Customer Impact

- ListView.GroupCollapsedStateChanged event works correctly in case of multiple groups selection.

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before

![154516575-62709402-0a92-4ace-9579-1ea66eeef564](https://user-images.githubusercontent.com/109065597/178964523-34595f6f-6592-41f0-a3ed-3e6a86bdab93.gif)

### After

![dECVUwE2AK](https://user-images.githubusercontent.com/109065597/178964332-749ee0a4-85b0-451d-995f-52e000036742.gif)

## Test methodology 

- Manually tested the change in a winforms app

## Test environment(s) 

- 7.0.100-preview.5.22307.18
- Windows 11

2022-07-14 10:45 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=7412) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=7412) before we can accept your contribution.<br/><br/>:x: NikitaSemenovAkvelon [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=7412)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=7412) it.</sub>

2022-07-15 23:26 UTC, Tanya-Solyanik commented
@NikitaSemenovAkvelon , @vladimir-krestov - had you guys confirmed that this bug is a regression from the .NET framework?

2022-07-15 23:38 UTC, Tanya-Solyanik reviewed
Looks good, but please confirm that this is a regression from the Framework.
Is it possible to add a unit test?

2022-07-15 23:38 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                        // User can select more than one group
nit: comments should resemble sentences, i.e. end with a period. This is not true across the code base, but we are moving in that direction.

2022-07-18 08:19 UTC, RussKie commented
Please do a clean rebase on top of the latest main
![image](https://user-images.githubusercontent.com/4403806/179471456-123c3b7c-7d5a-4557-87be-c1f73ca4b293.png)

2022-07-19 00:03 UTC, dreddy-work commented
@NikitaSemenovAkvelon , are you planning on adding unit tests here?

2022-07-19 04:48 UTC, NikitaSemenovAkvelon commented
> @NikitaSemenovAkvelon , are you planning on adding unit tests here?

Yes, I'm trying to add it now.

2022-07-19 06:09 UTC, RussKie requested changes
👍

2022-07-19 06:09 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                            if (group is null || !groups.Add(group.ID) || group.CollapsedState is ListViewGroupCollapsedState.Default)
I'd keep the original order and append the new operation to the end as it has perf implications
```suggestion
                            if (group is null || group.CollapsedState is ListViewGroupCollapsedState.Default || !groups.Add(group.ID))
```

2022-07-19 06:11 UTC, RussKie commented
Looking at the "after" animation - when we select both groups and collapse them together, shouldn't there be two notification, i.e., for each group?

2022-07-19 07:22 UTC, NikitaSemenovAkvelon commented
> Looking at the "after" animation - when we select both groups and collapse them together, shouldn't there be two notification, i.e., for each group?

In animation it looks like all items are selected but the only one group.

2022-07-19 08:14 UTC, RussKie commented
Ah, the translucent rectangle is on a specific group and it gets collapsed/expanded. 
👍

2022-07-19 08:15 UTC, RussKie approved these changes
LGTM

2022-07-20 21:03 UTC, Tanya-Solyanik approved these changes

2022-07-20 21:04 UTC, Tanya-Solyanik commented
@vladimir-krestov - I assume you are adding test in a separate PR?

2022-07-20 21:07 UTC, merged

2022-07-22 13:42 UTC, vladimir-krestov commented
> @vladimir-krestov - I assume you are adding test in a separate PR?

Yes, will try

2022-07-25 07:31 UTC, vladimir-krestov commented
> @vladimir-krestov - I assume you are adding test in a separate PR?

PR #7489