Use SequenceEqual instead of a handwritten loop in one case.
dotnet/winforms pull request #7417
Opened 2022-07-14 16:55 UTC by teo-tsirpanis

And simplify some nested ifs.

We save one array allocation (by replacing the static readonly array with the `ReadOnlySpan` property), and code gets shortened.

2022-07-18 08:24 UTC, RussKie requested changes
Nice!

2022-07-18 08:24 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.BitmapBinder.cs
> +                        && nameToBind.GetPublicKeyToken().AsSpan().SequenceEqual(AllowedToken))
`GetPublicKeyToken()` is annotated as nullable, and it was previoulsy checked for null.

2022-07-18 08:26 UTC, teo-tsirpanis commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.BitmapBinder.cs
> +                        && nameToBind.GetPublicKeyToken().AsSpan().SequenceEqual(AllowedToken))
`AsSpan` on a `null` array returns an empty span. The comparison would fail.

https://github.com/dotnet/runtime/blob/aafa91036e1efd3d4dcb67eeb261cb6d8f774685/src/libraries/System.Private.CoreLib/src/System/Span.cs#L40-L46

2022-07-18 08:30 UTC, RussKie approved these changes

2022-07-18 10:51 UTC, teo-tsirpanis commented
@RussKie CI is green.

2022-07-19 02:22 UTC, merged

2022-07-19 02:23 UTC, RussKie commented
Thank you!