Enable nullability in ToolStripPanel
dotnet/winforms pull request #7437
Opened 2022-07-18 07:07 UTC by gpetrou

## Proposed changes

- Enable nullability in ToolStripPanel.

2022-07-18 17:46 UTC, dreddy-work requested changes

2022-07-18 17:46 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
> +                    }
```suggestion
                        var toolStrip = e.Control as ToolStrip;
                        if (toolStrip is not null)
                        {
                            Join(toolStrip, e.Control.Location);
                        }
```

2022-07-19 04:14 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
> +            _owner = owner;
The field is only used here:
https://github.com/dotnet/winforms/blob/cc7abf13047404ea935a2d57c71e6badc3aaece4/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs#L612-L615

This .ctor is only invoked here:
https://github.com/dotnet/winforms/blob/cc7abf13047404ea935a2d57c71e6badc3aaece4/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContainer.cs#L29-L32

2022-07-19 04:15 UTC, RussKie reviewed
LGTM

2022-07-19 05:15 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
> +                    }
This will give a warning on `e.Control`.

2022-07-19 16:07 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
> +            _owner = owner;
in this case, we should not make owner nullable.

2022-07-19 18:25 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
> +            _owner = owner;
I did not make this nullable.

2022-07-19 18:50 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
> +            _owner = owner;
on line 24 `_owner` is nullable.  If we do not expect it bu null, it shouldn't be.

2022-07-19 19:13 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
> +            _owner = owner;
Oh, I thought you were talking about the parameter of the internal constructor. We have the public constructor which does not set the `_owner ` value. This is why that needs to be nullable.

2022-07-19 19:15 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
> +            _owner = owner;
hmm. thx for checking on it.

2022-07-19 19:16 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
> +                    }
hmm. i though you could use `as` with `null` here.

2022-07-19 19:16 UTC, merged