User32 ActivateKeyBoardLayout
dotnet/winforms pull request #7451
Opened 2022-07-19 07:16 UTC by elachlan

#7445

2022-07-19 10:59 UTC, RussKie approved these changes

2022-07-19 10:59 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
> +    <AdditionalFiles Include="Interop\User32\NativeMethods.txt" />
Would globing work?
```suggestion
    <AdditionalFiles Include="Interop\**\NativeMethods.txt" />
```

2022-07-19 22:49 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
> +    <AdditionalFiles Include="Interop\User32\NativeMethods.txt" />
@RussKie, @AArnott stated that we should use a centralized version of the `NativeMethods.txt` in https://github.com/microsoft/CsWin32/issues/606

> We don't recommend splitting NativeMethods.txt up. At least, I haven't come across any scenario where it would be beneficial. I heard someone suggest a couple weeks ago that perhaps one in each feature directory of a library would make sense, where the APIs used by that feature would be listed. But that's not really sustainable because there is no enforcement, and it would be a lot of extra bookkeeping on the part of the consumer to try to avoid using APIs that weren't asked for in their local file.
The reason we support multiple files is for Shared Project scenarios, where legitimately shared code requires p/invokes and should carry its own NativeMethods.txt file so that anyone who consumes the Shared Project will automatically generate the APIs it needs.

2022-07-19 23:26 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
> +    <AdditionalFiles Include="Interop\User32\NativeMethods.txt" />
>  At least, I haven't come across any scenario where it would be beneficial.

I think in our case it's clearly benefitial - we use a lot of interops 
https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms.Primitives/src/Interop

2022-07-19 23:47 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
> +    <AdditionalFiles Include="Interop\User32\NativeMethods.txt" />
I don't want to have multiple NativeMethods.txt as figuring out where to put things and to find existing entries is not clear.

2022-07-19 23:49 UTC, JeremyKuhne requested changes
Please keep a single NativeMethods.txt in the root for discoverability.

2022-07-20 00:22 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
> +    <AdditionalFiles Include="Interop\User32\NativeMethods.txt" />
@JeremyKuhne how is it different from how we do it now?

2022-07-20 00:36 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
> +    <AdditionalFiles Include="Interop\User32\NativeMethods.txt" />
No matter where you put these NativeMethods.txt files you'll get the same top level `PInvoke` method call. Other support types are under a structure defined by the Windows team in the metadata (*not* the source dll).

So this isn't a matter of matching code structure, and it is also just a long list of method names, no implementation.

2022-07-20 21:03 UTC, lonitra requested changes

2022-07-20 22:36 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/NativeMethods.txt
> +﻿ActivateKeyboardLayout
It was a zero width space character. I have made a PR to fix the processing in https://github.com/microsoft/CsWin32/pull/609

2022-07-20 23:18 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
>                  if (handleOld == IntPtr.Zero)
should we still comparing it with IntPtr.Zero? can we just check `== 0` here?

2022-07-20 23:25 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
>                  if (handleOld == IntPtr.Zero)
I tried, I think the compiler doesn't like it because HKL doesn't have an implicit conversion to int? I wasn't sure what to do.

2022-07-21 01:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
>                  if (handleOld == IntPtr.Zero)
`HKL` should have a `.NULL` on it, if not get the `.Value` and compare to `0`.

2022-07-21 01:16 UTC, AArnott approved these changes

2022-07-21 01:16 UTC, AArnott commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
>                  if (handleOld == IntPtr.Zero)
I just tried this syntax. It compiled fine when targeting .NET 6 and net472:

```cs
using Windows.Win32.UI.TextServices;

HKL hkl = default;
if (hkl == 0)
{
}
```

This is using CsWin32 0.2.1-beta.

2022-07-21 01:16 UTC, AArnott commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                fixed (HKL* pHandles = handles)
No need for `fixed` here any more. With CsWin32 you can do this:

```cs
var handles = new HKL[5];
PInvoke.GetKeyboardLayoutList(handles);
```

2022-07-21 01:44 UTC, AArnott commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
>                  if (handleOld == IntPtr.Zero)
HKL looks like a candidate for the `IsNull` property that we're supposed to generate on pointer-sized handles, per https://github.com/microsoft/CsWin32/issues/206. If HKL is a handle (or a pointer) and we missed that, can you file a new issue for it?

2022-07-21 02:14 UTC, AArnott commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                if (handleOld.Value == 0)
Weird. Well, I'm glad you have a workaround.

2022-07-21 02:26 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                if (handleOld.Value == 0)
Doing a cast to nint works and there is no nint.Zero. HKL has an operator for nint, but not int. Should I just do the cast or is there a better way?
```
 HKL handleOld = PInvoke.ActivateKeyboardLayout(new HKL(value.Handle), 0);
                if (handleOld == (nint)0)
                {
                    throw new ArgumentException(SR.ErrorBadInputLanguage, nameof(value));
                }
```

2022-07-21 02:31 UTC, AArnott commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                if (handleOld.Value == 0)
The cast isn't necessary in my project. Maybe it's an odd C# 11 or .NET 7 targeting thing. You can choose whatever syntax you're happiest with. They're all equivalent in the end.

2022-07-21 02:32 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                if (handleOld.Value == 0)
Does `if (handleOld == default)` work?

2022-07-21 02:35 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                if (handleOld.Value == 0)
> Does `if (handleOld == default)` work?

yes!

2022-07-21 02:40 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
>                  if (handleOld == IntPtr.Zero)
done. https://github.com/microsoft/CsWin32/issues/610

2022-07-21 02:43 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
> +                if (handleOld.Value == 0)
for integral types such as `int`, `IntPtr`, etc. `default` == 0. So it's equivalent.

2022-07-21 16:28 UTC, lonitra approved these changes

2022-07-29 17:51 UTC, dreddy-work approved these changes

2022-07-29 17:52 UTC, dreddy-work commented
@elachlan , can you resolve merge conflict?

2022-07-30 04:44 UTC, merged