Fixing TabPage memory leaks
dotnet/winforms pull request #7453
Opened 2022-07-19 09:48 UTC by dkazennov

Fixes #7415 

## Proposed changes

- Changed TabPage class

## Customer Impact

- Less memory leaks of TabPage 

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before

https://user-images.githubusercontent.com/102961955/179677786-89b6722e-d0b2-4fa9-897b-5b3a12824343.png

### After

https://user-images.githubusercontent.com/102961955/179707383-55e03da5-5c37-4b0c-844f-d802e4979f0b.png

## Test methodology 

- CTI
- Manually (via WinDbg)

## Accessibility testing  

- Using AI, Inspect, Narrator

 

## Test environment(s) 

- .NET 7.0 Preview 5
- Windows 10

2022-07-19 18:56 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                HRESULT result;
declare inline.

2022-07-20 11:18 UTC, dkazennov commented
> Add unit test for the scenario?

As far as I know we don't create unit tests for memory leaks. Memory leaks are being tested manually and with CTI.

2022-07-20 16:48 UTC, dkazennov commented
1. Changed TabPageCollection.Remove() -- added call for removed TabPage.ReleaseUiaProvider
2. !gcroot showed AO object to be hold back by TabPage.TabAccessibleObject
3. Changed TabAccessibleObject.RuntimeId to include HashCode, not GetChildId (the index in the collection)
4. TabPage.TabAccessibleObject is fixed, yet AO object are now holded by ButtonAccessibleObject

2022-07-21 13:17 UTC, dkazennov commented
The source of the issue discovered by CTI turned out to be hierarchy on nested TabControls, TabPages and elements.
To reproduce it remove the tabPage with nested tabPages.
![image](https://user-images.githubusercontent.com/102961955/180222645-27f5a5fd-1aec-43c1-b97a-ab3a1b35ef09.png)

The memory leaks are fixed.
![image](https://user-images.githubusercontent.com/102961955/180222767-92a6c830-77b0-44c7-a0b1-b31cc33edb12.png)

2022-07-21 14:21 UTC, dkazennov commented
Issues found by CTI are fixed.
CTI re-test will be requested.

2022-07-22 02:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                            ReleaseChildControls(control.Controls);;
```suggestion
                            ReleaseChildControls(control.Controls);
```

2022-07-22 02:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                    if (OsVersion.IsWindows8OrGreater && control.IsAccessibilityObjectCreated)
Invert to reduce nesting. I'd also do this check before the Debug.Writeline

2022-07-22 02:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +            private static void ReleaseChildControls(Control.ControlCollection controls)
If this is the only called from `ReleaseTabPageUiaProviders` then it's worth considering turning this method into a local method.

2022-07-22 02:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +            private static void ReleaseTabPageUiaProviders(TabPage tabPage)
Looks like this method is only called from `Remove`. I don't think there's much value breaking the functionality across multiple methods. Whilst having one large method that does many different things is bad, there's a cost to having multiple methods too. In this case, these costs aren't necessary.
I suggest considering something like:
```cs
            public void Remove(TabPage value)
            {
                ArgumentNullException.ThrowIfNull(value);

                _owner.Controls.Remove(value);

                ReleaseTabPageUiaProviders(value);

                return;

                static void ReleaseTabPageUiaProviders(TabPage tabPage)
                {
                    // all release-related functionality
                }
            }
```

2022-07-22 07:03 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                    if (OsVersion.IsWindows8OrGreater && control.IsAccessibilityObjectCreated)
I believe we can delete Debug.WriteLine now.

2022-07-22 07:54 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +            private static void ReleaseTabPageUiaProviders(TabPage tabPage)
Yes, I was thinking that the ReleaseTabPageUiaProviders() method may be redundant as a separate method.

2022-07-22 10:59 UTC, dkazennov commented
Fixed failures with unit tests.

2022-07-22 12:35 UTC, dkazennov commented
![image](https://user-images.githubusercontent.com/102961955/180440279-c2907ee5-22e5-44cc-a36c-73edac5905bc.png)

2022-07-22 12:44 UTC, dkazennov commented
The fix now works both with Narrator and Inspect. Requesting re-test for CTI.

2022-07-25 08:00 UTC, dkazennov commented
It seems that some builds are affected by https://github.com/dotnet/winforms/issues/6739

2022-07-25 12:42 UTC, dkazennov commented
Relocated static void ReleaseChildrenUiaProviders() from TabCollection.Remove() to TabPage.ReleaseUiaProvider()

2022-07-25 16:02 UTC, dkazennov commented
It is hard to pinpoint remaining memory leakages. Most tests shows no leaks.
![image](https://user-images.githubusercontent.com/102961955/180823006-52ac6394-b338-44dc-980f-0fde7ed7e43f.png)

2022-07-26 06:50 UTC, dkazennov commented
After consulting with @vladimir-krestov I believe this PR is worthy to be merged into main. I believe I have successfully fixed most memory leaks, including most cases where a TabPage being removed - both with Inspect and Narrator.

There are however some odd and rare case where an empty TabPage is being removed and with the Narrator there are memory leaks (as shown by CTI results). 

@Tanya-Solyanik could we implement what is already achieved by this fix and leave the remaining rare leak case for now? It seems it will take too much time and effort to find where is the exact source of the remaining issue (is possible).

2022-07-26 08:41 UTC, RussKie submitted a review, later dismissed

2022-07-26 20:55 UTC, vladimir-krestov requested changes
It should be reworked and retested.
@Tanya-Solyanik, please describe, why should we avoid double releasing of controls?

2022-07-26 20:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                    value.ReleaseUiaProvider(value.Handle);
I'm not sure, that it's right. Control calls ReleaseUiaProvider when destroying. In this case we will call this method twice, that may lead to some unexpected errors, mentioned by @Tanya-Solyanik before, so we should avoid double releasing.
First, please make sure, that a TabPage destroys after removing from the collection or after destroying of the whole TabControl. If it's true, we must not call this method here.

2022-07-26 20:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
> +                    GetHashCode()
Please describe why did you changed it. It will be helpful in the future to understand reasons of this change and prevent changing back by someone.

2022-07-26 20:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +            return;
You don't need this

2022-07-26 20:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +            base.ReleaseUiaProvider(handle);
I usually call it first to release the main object and then its elements

2022-07-26 20:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                Debug.Assert(result == HRESULT.S_OK);
You should remove this, because the base implementation do it. And we must avoid double releasing of AO

2022-07-26 20:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                UiaCore.UiaReturnRawElementProvider(Handle, wParam: IntPtr.Zero, lParam: IntPtr.Zero, el: null);
`Handle` getter forces its value creation. We had some unexpected important bugs with it, this getter may create a Handle in incorrect time, or recreate a control after destroying. It's FYI in the future. But in this case you should remove it, because the base implementation do it well.

2022-07-26 20:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +            if (OsVersion.IsWindows8OrGreater)
Please add IsAOCreated check as well

2022-07-26 20:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +            static void ReleaseChildrenUiaProviders(ControlCollection controls)
As I understand, it's really extra. Because as I described above, every control care about its own AO and releasing when destroying. So every child control will call `ReleaseUiaProvider` independently when destroying, we shouldn't force this process and make double releasing, that will lead to unexpected errors. Every control will be destroyed anyway, so they will release their AO themself.
Please:
1) Make sure, that ReleaseUiaProvider is called for them without your changes after destroying of TabControl. (see Control.cs line 12212)
2) Remove this method at all

2022-07-26 20:55 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(TabAccessibilityObject);
I see, that it's only one thing that should be implemented here

2022-07-27 08:36 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                Debug.Assert(result == HRESULT.S_OK);
Yes, indeed. So we need to disconnect only TabAccessibilityObject.

2022-07-27 09:32 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                UiaCore.UiaReturnRawElementProvider(Handle, wParam: IntPtr.Zero, lParam: IntPtr.Zero, el: null);
Removed UiaReturnRawElementProvider.

2022-07-27 09:36 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                    value.ReleaseUiaProvider(value.Handle);
I believed the issue found by CTI team was because after removing from collection objects still remained in memory and was not properly destroyed. I'll check if objects are destroyed then.

2022-07-27 10:27 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(TabAccessibilityObject);
![image](https://user-images.githubusercontent.com/102961955/181225187-4f220587-a83e-4138-b79d-f6ce914f7794.png)

This way we don't have memory leaks if no TabPage is removed from TabPageCollection. But if TabPage is being removed from TabPageCollection there will be leaks. So I suspect there is no Destroy() for TabPage after it is being removed from collection.

2022-07-27 12:45 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(TabAccessibilityObject);
So tests show that there will be memory leaks if TabPage is being removed.

I believe we can safely call Dispose() for a TabPage being removed from TabPageCollection as suggested in https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-add-to-or-remove-from-a-collection-of-controls-at-run-time?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-6.0

2022-07-27 12:49 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
> +                    GetHashCode()
If RuntimeId is depended on index in collection, removing or adding elements to collection will affect RuntimeId which will cause objects to not properly disconnected.

2022-07-28 07:59 UTC, dkazennov commented
**Conclusion:**

1. On the last meeting we have decided that the most safe way to prevent a memory leak if removing the TabPage is to call ReleaseUiaProvider() from TabPageCollection.Remove() for the removed TabPage and all its controls. Calling for Dispose() leads to undesirable risks. @Tanya-Solyanik 

2. @vladimir-krestov If a TabPage is being removed and right after that added (I've put into test code Add(value) right after Remove(value)) than it will be added with all its elements intact and functional. No memory leaks will be spotted.

![image](https://user-images.githubusercontent.com/102961955/181453202-4579430c-c66b-4a95-8163-42e6d6c78cc0.png)

2022-08-02 00:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
> +                    GetHashCode()
Hash code makes sense to me.

2022-08-02 00:23 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                UiaCore.UiaReturnRawElementProvider(Handle, wParam: IntPtr.Zero, lParam: IntPtr.Zero, el: null);
UiaReturnRawElementProvider(all nulls) is required. If control invokes this API with an actual provider in WM_GETOBJECT handler, it should clean up afterwards with a call with all null values for the same handle.
https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcoreapi/nf-uiautomationcoreapi-uiareturnrawelementprovider#remarks

2022-08-02 00:26 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(TabAccessibilityObject);
This sounds like a reasonable thing to try.

2022-08-02 00:27 UTC, Tanya-Solyanik commented
>@Tanya-Solyanik, please describe, why should we avoid double releasing of controls?

Because the second `Disconnect` crashes the application. I think there is more to these crashes than disconnecting twice, but disconnecting twice is contributing.

2022-08-02 06:33 UTC, dkazennov commented
@Tanya-Solyanik this issue is ready for review.
We have the final way to fix these leaks.
All cases of memory leaks are covered except for one rare and odd case found by CTI with empty TabPage. Vladimir proposed we implement everything that is already achieved.

2022-08-02 06:49 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(TabAccessibilityObject);
Both ways (calling for Dispose() in Remove() and calling for disconnection in Remove()) work.
As I understood the second way is more safe.

2022-08-03 06:56 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                UiaCore.UiaReturnRawElementProvider(Handle, wParam: IntPtr.Zero, lParam: IntPtr.Zero, el: null);
@Tanya-Solyanik in current fix there is a override ReleaseUiaProvider class which calls for base.ReleaseUiaProvider(handle);
There is already the call for UiaCore.UiaReturnRawElementProvider(handle, 0, 0, null); in Control.ReleaseUiaProvider(handle);

Should there be a second call for UiaReturnRawElementProvider in override class of child class?

2022-08-03 21:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                    value.ReleaseUiaProvider(value.Handle);
This is strange because `TabPage` is a Control, thus is backed up by a window handle. And all window handles receive WM_DESTROY, and Control class calls `ReleaseUiaProvider` when handling this message. One possibility is that WM_DESTROY arrived after the native window is un-subclassed, and NativeWindow.cs WinProc receives and handles WM_DESTROY. In this case we might want to do the same trick and combo box's sub-controls do. We create custom Native Windows subclasses for them and have a chance to handle WM_DESTROY in these subclasses. You can use spy++ (distributed with the VS) to double check if this message is sent.

2022-08-03 21:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                Debug.Assert(result == HRESULT.S_OK);
Please set `_tabAccessibilityObject ` to null after it is disconnected.

2022-08-03 21:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                UiaCore.UiaReturnRawElementProvider(Handle, wParam: IntPtr.Zero, lParam: IntPtr.Zero, el: null);
No, a single call to `UiaReturnRawElementProvider` is sufficient, I misunderstood Vladimir's comment.

2022-08-03 21:51 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(TabAccessibilityObject);
Yes, Remove is safer because additional Dispose could break code that moves TabPages between different TabControls.

2022-08-03 21:54 UTC, Tanya-Solyanik reviewed
Please understand lifetime of Tab windows in order to find a good spot to Disconnect providers and address all Vladimir's feedback. Also other similar PRs are adding unit tests please see if you can add similar ones.

2022-08-04 07:19 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                Debug.Assert(result == HRESULT.S_OK);
I added the check for value.IsHandleCreated because there are unit tests that check the TabPage class without the handler. 
In all actual cases handle is indeed created, but in unit tests cases the handle should not be created or unit tests will fail.

2022-08-04 07:31 UTC, dkazennov commented
> Please understand lifetime of TabPage windows in order to find a good spot to Disconnect providers and address all Vladimir's feedback. Also other similar PRs are adding unit tests please see if you can add similar ones.

As I understand the TabPage in most cases will end it's life if it is removed. But as Vladimir requested I have tested the case when the TabPage is added after it was being removed. That way the TabPage is being added with all it's contents intact, and the accessible objects are being created once more.

I'll try to figure it out if it is possible to test memory leaks with unit tests. I thought there is no way to test a leak with a unit test since we detect leaks with WinDbg?

2022-08-04 19:38 UTC, Tanya-Solyanik reviewed
Remaining issues in this PR:
1. remove `result == S_OK` check
2. add unit tests
@vladimir-krestov  - please re-review, you are blocking this change right now.

2022-08-04 19:38 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                if (result == HRESULT.S_OK)
It actually fails to disconnect when there is something wrong with the accessible object, so we don't want to keep a "bad" object around. I would set AO to null regardless of the return code.

2022-08-04 19:38 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                if (result == HRESULT.S_OK)
I guess that the reason why we have to disconnect TabAO manually is that Tab is a fully native window, with no backing managed control, and thus there is no place to put `SupportsUIAProviders == true` and activate release on the Control level.

2022-08-05 09:37 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                if (result == HRESULT.S_OK)
> It actually fails to disconnect when there is something wrong with the accessible object, so we don't want to keep a "bad" object around. I would set AO to null regardless of the return code.

Oh, I see. Ok.

I have finished the unit test to check the diconnection of _tabAccessibilityObject. But right now the unit test to control the Remove() method in TabPageCollection returns unexpected results.

2022-08-05 11:48 UTC, dkazennov commented
I've added a new test TabAccessibilityObject_IsDisconnected_WhenTabPageReleasesUiaProvider which successfully covers the case with _tabAccessibilityObject is being disconnected.

But there is probably no way to cover a case with disconnection of removed from TabControl.TabPageCollection items. While manual testing and CTI show that removed items are being disconnected the call for TabPageCollection .Remove() in a unit test fails to disconnect accessible objects.

2022-08-08 04:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                    value.ReleaseUiaProvider(value.Handle);
One way to avoid a double disconnect of provider here is to set Accessible object to null(by calling Properties.SetObject) in Control.cs in ReleaseUiaProvider

2022-08-08 05:01 UTC, Tanya-Solyanik reviewed
Unit test looks good, but please see the comment about the `Remove` method

2022-08-09 01:09 UTC, Tanya-Solyanik reviewed
Looks good with minor comments. Should it be re-tested by the CTI team?

2022-08-09 01:09 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.Handle);
nit: use `HandleInternal`

2022-08-09 01:09 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                            if (control.IsHandleCreated)
please test if this control supports UIA Providers

2022-08-09 01:09 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.Handle);
`control.ReleaseUiaProvider(control.Handle);` only works correctly if Control.cs sets Accessibility object to null (via Properties.SetObject) This is called out in @vladimir-krestov refactoring PR. Please coordinate who implements this cleanup.

2022-08-09 08:50 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                            if (control.IsHandleCreated)
TabPage have 
**ProviderDescription:**
"[pid:13080,providerId:0x10BBA 
Main:Nested [pid:26208,providerId:0x10BBA 
Main(parent link):Unidentified Provider (unmanaged:coreclr.dll)]; 
Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"

By comparing with the https://github.com/dotnet/winforms/pull/7314 (where I added the UIA Provider support) I can conclude that TabPage Control supports UIA Providers.

2022-08-09 09:05 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.Handle);
This is about https://github.com/dotnet/winforms/pull/7362/files#r939832225, as I understand.
We might need to test this whole issue in separate branch and possibly create a new Issue. This new Issue could probably lead to a separate big PR with huge amount on testing for side effects.

2022-08-09 09:18 UTC, dkazennov commented
Probably we don't new CTI since the last one? We haven't changed the fix here since then, only added a unit test and refactored the fix.

2022-08-09 16:54 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.Handle);
Please discuss this change with Vladimir, I agree that a separate PR is apropriate.

2022-08-09 16:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                    value.ReleaseUiaProvider(value.Handle);
Please use `HandleInternal`

2022-08-10 00:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                            if (control.IsHandleCreated)
I think if control does not have Handle created, there is no reason to iterate its children.

2022-08-10 00:59 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                            if (control.IsHandleCreated)
I'm not talking about the tabpage control, but about children of this tabpage - i.e. controls placed on the tab page, like buttons. I'm suggesting this:
```
       static void ReleaseChildrenUiaProviders(Control.ControlCollection controls)
        {
            foreach (Control control in controls)
            {
                if (control.IsAccessibilityObjectCreated && control.IsHandleCreated && OsVersion.IsWindows8OrGreater)
                {
                    var children = control.Controls;
                    if (children.Count > 0)
                    {
                        ReleaseChildrenUiaProviders(children);
                    }

                    if (control.SupportsUiaProviders)
                    {
                        control.ReleaseUiaProvider(control.HandleInternal);
                    }
                }
            }

        }
```

2022-08-10 07:14 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.Handle);
We have decided I should create a separate Issue and it will be fixed in the separate PR.

2022-08-10 08:21 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                            if (control.IsHandleCreated)
> I'm not talking about the tabpage control, but about children of this tabpage - i.e. controls placed on the tab page, like buttons. I'm suggesting this:
> 
> ```
>        static void ReleaseChildrenUiaProviders(Control.ControlCollection controls)
>         {
>             foreach (Control control in controls)
>             {
>                 if (control.IsAccessibilityObjectCreated && control.IsHandleCreated && OsVersion.IsWindows8OrGreater)
>                 {
>                     var children = control.Controls;
>                     if (children.Count > 0)
>                     {
>                         ReleaseChildrenUiaProviders(children);
>                     }
> 
>                     if (control.SupportsUiaProviders)
>                     {
>                         control.ReleaseUiaProvider(control.HandleInternal);
>                     }
>                 }
>             }
> 
>         }
> ```

Oh, I got it, thanks. This looks safer.

2022-08-10 19:09 UTC, Tanya-Solyanik approved these changes
fill free to apply my comments in the next PR.

2022-08-10 19:09 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> -
nit: this repo is moving towards the style where argument validation is separated from the rest of the code by a blank line.

2022-08-10 19:09 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                        if (control.IsAccessibilityObjectCreated && control.IsHandleCreated && OsVersion.IsWindows8OrGreater)
nit: If handle is not created, then the AO is unlikely to exist as well. So it might be better to test for handle first.

2022-08-10 19:13 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.HandleInternal);
I'm not still agree with it. Let me double check
@Tanya-Solyanik, I think inner controls should care about disconnection themself. Right?

2022-08-10 19:33 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.HandleInternal);
Yes, we call `ReleaseUiaProvider` for an inner control twice. So it is incorrect

2022-08-10 19:48 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                static void ReleaseChildrenUiaProviders(Control.ControlCollection controls)
Actually, if to remove all of this, I don't see leak in case of removing a TabPage form a TabControl. @dkazennov, please describe a case that we need it in.

2022-08-10 19:50 UTC, vladimir-krestov approved these changes
I don't like double disconnections, but it should be tested more. Approved the rest ✅

2022-08-10 20:02 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.HandleInternal);
Good point. This will double-disconnect when tage is removed from the control and then its child controls are disposed. @dkazennov - please test if tabpage leaks even after all child controls are disposed bythe application.

2022-08-10 20:09 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.HandleInternal);
Maybe it's try to release TabPage after deletion. But the main reason - `WmDestroy` is not called for deleted TabPage for some reason. I will try to rework it

2022-08-10 20:22 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.HandleInternal);
So `WmDestroy` is not called for a deleted TabPage, and for its Controls as well. I think the right way - destroy TabPage control after deletion, but it's so complex issue with many side effects

2022-08-10 21:26 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.HandleInternal);
Sorry, it was a mistake of testing. This implementation works well, because a deleted TabPage and its inner controls are not destroyed and disconnected, so in the case of deleting a TabPage there are no any double disconnections

2022-08-10 22:56 UTC, Tanya-Solyanik approved these changes

2022-08-10 22:56 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
> +                HRESULT result = UiaCore.UiaDisconnectProvider(TabAccessibilityObject);
@Tanya-Solyanik, this dialog.

2022-08-10 23:18 UTC, merged

2022-08-11 04:22 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
> +                                control.ReleaseUiaProvider(control.HandleInternal);
> so in the case of deleting a TabPage there are no any double disconnections

So everything works as intended and this fix is merged, cool! Thanks!