Created a type string variable named 'qualifier' which is equaled to …
dotnet/winforms pull request #7469
Opened 2022-07-20 21:41 UTC by fernandanavamoya

Fixes #7346

## Proposed changes

- Added full qualifier to ApplicationConfiguration generated code by creating a type string variable named 'qualifier' which is equaled to the full qualifier and then adding it to the controls.
-  Changed expected result in test file by adding the full qualifier.

``` C#
static string GenerateCode(ApplicationConfig projectConfig, string? defaultFont, string indent)
            {
                StringBuilder code = new();
                string qualifier = "global::System.Windows.Forms.Application.";
                if (projectConfig.EnableVisualStyles)
                {
                    code.AppendLine($"{indent}{qualifier}EnableVisualStyles();");
                }

                code.AppendLine($"{indent}{qualifier}SetCompatibleTextRenderingDefault({projectConfig.UseCompatibleTextRendering.ToString().ToLowerInvariant()});");

                code.AppendLine($"{indent}{qualifier}SetHighDpiMode(HighDpiMode.{projectConfig.HighDpiMode});");

                // Note: we need to set the font _after_ we set the DPI scaling, as it affects how we scale the font.
                if (!string.IsNullOrWhiteSpace(defaultFont))
                {
                    code.AppendLine($"{indent}{qualifier}SetDefaultFont({defaultFont});");
                }

                // Don't append line as we don't need the trailing \r\n!
                code.Remove(code.Length - Environment.NewLine.Length, Environment.NewLine.Length);

                return code.ToString();
            }
```

2022-07-20 22:35 UTC, KlausLoeffelmann approved these changes
Looks good to me!

I'd probably want to change the title of this PR to describe what it fixes rather how it fixes it, though. Like "Fix failing AppConfig code generation for namespaces including 'Application'" or something like that. (The description of the PR is probably derived from a commit description?)

2022-07-20 22:35 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilder.cs
> +                string qualifier = "global::System.Windows.Forms.Application.";
This could be a string constant, so we don't allocate anything at runtime.
Take a look here to read up on this:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/const

Be careful though, when using constants which are visible to other assemblies. It's not good practice, and in any case, should you ever change them, you'd need to recompile everything depending on them, since they are stored in the meta data rather than at runtime. (Which is the whole point! 😄).

2022-07-20 22:36 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilder.cs
> +                string qualifier = "global::System.Windows.Forms.Application.";
Oh, and take a look why the tests are failing!

2022-07-20 22:37 UTC, KlausLoeffelmann requested changes
Please check the failing tests first.

2022-07-20 23:13 UTC, RussKie commented on src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilder.cs
> +                string qualifier = "global::System.Windows.Forms.Application.";
```suggestion
                const string qualifier = "global::System.Windows.Forms.Application.";
```

2022-07-20 23:23 UTC, RussKie commented
@fernandanavamoya there are still [tests failing](https://dev.azure.com/dnceng/public/_build/results?buildId=1893870&view=ms.vss-test-web.build-test-results-tab&runId=49368450&resultId=100127&paneView=debug).

2022-07-21 03:57 UTC, RussKie approved these changes

2022-07-21 03:58 UTC, RussKie commented
Thank you

2022-07-21 03:58 UTC, merged

2022-07-21 03:59 UTC, RussKie commented
/backport to release/6.0