Add Tests to StronglyTypedResourceBuilder/ResXDataNode
dotnet/winforms pull request #7515
Opened 2022-07-30 00:17 UTC by lonitra

- Ensure type `byte[]` from `System.Private.Corelib` assembly is handled correctly in `ResXDataNode.GenerateObjectFromDataNodeInfo` and expand its test suite

- Add Bitmap/Icon/Audio/Txt File tests: 

In Framework, the main scenario resources that are added to the .resx file are strings, images, icons, audios, and files. The tests added check if the `StronglyTypedResourceBuilder`, no matter if given a resource list or resx file, is able to spit out the correct resource type. The tests also validate the resulting value grabbed from the property. 

Note that the resource property types (seen in `Resources.designer.cs` file) for images and icons in Core are different from Framework. In Core, image and icon are type `byte[]` while in Framework they are `Bitmap` and `Icon` respectively. Thus, in the image/icon tests there is additional checking for whether the resulting `byte[]` can be converted to type `Icon`/`Bitmap`. Issue will be created for this so that images/icons can actually be strongly typed in core.

2022-07-30 18:21 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +            "System.Byte[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
string `mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089` can be made const in the test class and reuse across tests.

2022-07-30 18:21 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +        Bitmap resourceBitmap = Assert.IsType<Bitmap>(converter.ConvertFrom(resourceBytes));
if this is a new bitmap instance, we need to dispose before test ends. Can you take a look at other instances in these new tests and see they are disposed as necessary?

2022-07-30 18:21 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +        ResXResourceWriter resxWriter = new(resxStream);
i see some inconsistency in disposing ResXResourcewritters. Some are used with `using `and others are not. Can you cross check  these in new tests added in this PR?

2022-07-30 18:21 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +        Icon icon = new(@"Resources\Icon1.ico");
same here. use `using`  to dispose.

2022-08-01 01:11 UTC, RussKie requested changes

2022-08-01 01:11 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +        byte[] resourceBytes = Assert.IsType<byte[]>(imageProperty.GetValue(obj: null));
This looks like an exact replica of the code above and below. Can you please factor out the repeating [arrangement logic](https://methodpoet.com/aaa-in-unit-testing/#Arrange_or_Preparation) in a helper method to reduce duplication.
Whilst there are different school of thoughts on how to write a good test, in this case duplication of code doesn't carry a great deal of value, but introduces a maintenance overhead.

2022-08-01 19:34 UTC, lonitra commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +        Bitmap bitmap = (Bitmap)Image.FromFile(@"Resources\Image1.png");
Looks like `ResourceWriter`/`ResXResourceWriter`/`ResXResourceReader` dispose of streams that are passed to them upon construction -- do we still need to add `using` statements for these streams?

2022-08-01 20:54 UTC, lonitra commented on src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
> +                        (typeName.Contains("System.Byte[]") && (typeName.Contains("mscorlib") || typeName.Contains("System.Private.CoreLib"))))
I'm not sure I understand here. We want to do a fast check if `type == typeof(byte[])` , but there is a comment below (line 437) stating that that this may not always work, so in the case that it doesn't for the reason mentioned in the comment, we need to check using the slower way which is where we check that `typeName` contains System.Byte[] and mscorlib or it contains System.Byte[] and private.corlib

2022-08-02 04:35 UTC, RussKie commented on src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
> +                        (typeName.Contains("System.Byte[]") && (typeName.Contains("mscorlib") || typeName.Contains("System.Private.CoreLib"))))
I initially though the expression looked like `A || (B && C || D)`. I had a loooong look again, and I can see that it's actually `A || (B && (C || D))`.
Apologies.

2022-08-02 04:39 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +        Bitmap bitmap = (Bitmap)Image.FromFile(@"Resources\Image1.png");
IMO that's an implementation detail - unless you peak inside you can't be sure. The docs aren't stating that the supplied stream will be disposed of either, so to be on a safe side I suggest always dispose disposable objects.

2022-08-02 04:59 UTC, RussKie reviewed
Some dispose and styling issues, other than that - 👍

2022-08-02 04:59 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +[Fact]
Bad indentation

2022-08-02 04:59 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +    private static void validateResultIcon(PropertyInfo iconPropertyInfo, Icon expected, TypeConverter converter)
Incorrect capitalisation

2022-08-02 04:59 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +    private static PropertyInfo getPropertyInfo(IDictionaryEnumerator enumerator,
Ditto

Can you please move the helper methods after the tests? It _can_ kind of make sense if a method is directly near the callsite, but this (and other) helper method is used multiple times.

2022-08-02 04:59 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +        CodeCompileUnit compileUnit, string propertyName)
Please keep either all args on the same line, or each one on the separate line

2022-08-02 04:59 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +            $"System.IO.MemoryStream, {TypeAssembly}");
This line is well under 120 chars, please keep it on the same line. Ditto other similar instances.

Please install the [editor guidelines extension](https://github.com/dotnet/winforms/blob/main/docs/developer-guide.md#machine-setup), which will help you in such situations.

2022-08-02 04:59 UTC, RussKie commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +        validateResultIcon(iconPropertyInfo, expected, TypeDescriptor.GetConverter(typeof(Icon)));
Following the [AAA pattern](https://methodpoet.com/aaa-in-unit-testing/) (i.e., arrange, act, assert), am I reading this correctly?
```cs
	// arrange
        ResXFileRef fileRef = new(@"Resources\Icon1.ico",
            $"System.Byte[], {TypeAssembly}");
        Hashtable values = new()
        {
            { "Icon1", new ResXDataNode("Icon1", fileRef) }
        };

	// act
        var compileUnit = StronglyTypedResourceBuilder.Create(...);

	// assert
        MemoryStream resxStream = new();
        using ResXResourceWriter resxWriter = new(resxStream);
        // .., the rest
```

2022-08-02 16:45 UTC, lonitra commented on src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
> +        validateResultIcon(iconPropertyInfo, expected, TypeDescriptor.GetConverter(typeof(Icon)));
Yup, that's correct

2022-08-03 06:25 UTC, RussKie approved these changes

2022-08-03 06:25 UTC, merged