Convert CloseHandle/GetLocaleInfoEx/LoadLibrary to CsWin32
dotnet/winforms pull request #7541
Opened 2022-08-04 21:02 UTC by fernandanavamoya

Created
- PInvoke.CloseHandle.cs
- PInvoke.LoadLibrary

Use SafeHandle instead of Foundation.HANDLE
- LoadLibraryEx

2022-08-04 21:15 UTC, JeremyKuhne requested changes
Should try to keep things as their handle type and can skip using explicit interface implementation for .Handle. Otherwise looks good.

2022-08-04 21:15 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.LoadLibrary.cs
> +                        IntPtr result = LoadLibraryEx(lpLibFileName, (HANDLE)0, 0);
We should pass back `HINSTANCE` from these instead of letting them cast to `IntPtr` or `nint`. Now that we have "strong" handle types, we should try to carry them through the system and only convert to `IntPtr` when absolutely needed.

2022-08-04 21:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
> +            nint IHandle.Handle => _handle;
This should be `internal Handle => _handle;`. When you do it this way you have to cast it to the interface to use it.

2022-08-04 21:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            nint threadHandle = ((IHandle)ctx).Handle;
See the comment in `ThreadContext`, this cast shouldn't be necessary.

2022-08-04 21:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
> +                    nint threadHandle = (ctx is null ? 0 : ((IHandle)ctx).Handle);
Same here- this cast can be removed when you fix `ThreadContext`.

2022-08-04 21:28 UTC, fernandanavamoya commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.LoadLibrary.cs
> +                        IntPtr result = LoadLibraryEx(lpLibFileName, (HANDLE)0, 0);
By casting it to an `IntPtr` or `nint` only when necessary, do you mean we should also change the return type of the method to `HINSTANCE`?

2022-08-04 21:47 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.LoadLibrary.cs
> +                        IntPtr result = LoadLibraryEx(lpLibFileName, (HANDLE)0, 0);
> do you mean we should also change the return type of the method to HINSTANCE?

Yes

2022-08-04 22:54 UTC, fernandanavamoya commented
cc: @AArnott

2022-08-05 20:32 UTC, dreddy-work approved these changes
LGTM

2022-08-08 22:39 UTC, JeremyKuhne approved these changes

2022-08-08 22:39 UTC, merged