Convert CreateX to Cswin32
dotnet/winforms pull request #7542
Opened 2022-08-04 22:56 UTC by lonitra

Add conversion for `CreatedHDC` -> `HDC` and `Gdi.HPALETTE` <-> `HPALETTE`

2022-08-04 23:07 UTC, dreddy-work approved these changes

2022-08-04 23:07 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
> +                fixed (void* ib = imageBuffer)
can this be moved to where it is used?

2022-08-04 23:08 UTC, dreddy-work commented
LGTM.

2022-08-05 01:06 UTC, JeremyKuhne requested changes
Think there was an existing bug here. :)

2022-08-05 01:17 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
> +                fixed (void* ib = imageBuffer)
This actually would not be better to move closer. Having it here would allow you to lose a level of nesting because you could use the same block as the other fixed statement. That said, there appears to be a bug in the existing code and we probably don't need the `imageBuffer` array at all.

2022-08-05 01:19 UTC, JeremyKuhne commented
ControlPaint tests are failing, I think this might be related to the issue I discussed.

2022-08-06 00:00 UTC, RussKie commented on src/System.Windows.Forms.Primitives/tests/UnitTests/System.Windows.Forms.Primitives.Tests.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
This file should be reverted.

2022-08-10 04:06 UTC, merged