Convert Gdi32 GetX to Cswin32
dotnet/winforms pull request #7581
Opened 2022-08-12 05:55 UTC by lonitra

- Convert `GetBitmapBits`,`GetBkColor`,`GetBkMode`,`GetBrushOrgEx`,`GetClipBox`,`GetClipRgn`,`GetCurrentObject`,`GetDeviceCaps`,
`GetDIBits`,`GetMapMode`,`GetNearestColor`,`GetObjectType`,`GetRegionData`,`GetRgnBox`,`GetROP2`,`GetStockObject`,
`GetSystemPaletteEntries`,`GetTextAlign`,`GetTextColor`,`GetTextExtentPoint32W`,`GetTextMetrics`,`GetViewportExtEx`,
`GetViewportOrgEx`,`GetWorldTransform`,`StretchDIBits`,`GetObject`,`GetPaletteEntries`,`GetTextExtendPoint32W`
- Move `SelectPaletteScope` to PInvoke folder
- Add `IHandle<HDC>` to `HDC`
- `Control.MetafileDCWrapper.cs`: Change initialization of `BITMAPINFO` used in calls `GetDIBits` and `StretchDIBits`. Cswin32 definition of `BITMAPINFO` contains trailing array thus we now need to manually allocate enough space for the bitmap colors. Also done some re-arrangement of code to try to reduce nesting.

2022-08-12 21:49 UTC, JeremyKuhne requested changes
Awesome work!

Try constraining the `SIZE`/`SIZEF` types in the API surface area. Consider extending `SIZE` and `SIZEF` structs to provide conversion operators to `Size` and `SizeF`. Also it is valid to just force cast when calling with them by reference (`(SIZE*)(void*)&size`). Whichever combination of things you choose I'm fine with.

2022-08-12 21:49 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetPaletteEntries.cs
> +        fixed (PALETTEENTRY* entry = &MemoryMarshal.GetReference(entries))
nit: the `&MemoryMarshal.GetReference` is an artifact of early Span work. C# added the ability to provide a method called `GetPinnableReference()` that allows spans (or anything else that implements it) to just get pinned with `&`. So this could be `&entries`, but that can be done in a follow-up.

2022-08-12 21:49 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SelectPaletteScope.cs
> -using System.Drawing;
Surprised that `System.Drawing` is causing conflicts.

2022-08-12 21:49 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/tests/TestUtilities/DeviceContextState.cs
> +            XFORM transform = default;
It would be nice to have `XFORM` mapped to `Matrix3x2`, or at least have the option to. It is supported on .NET Standard, although it does require a package ref.  https://apisof.net/catalog/bb678d8b-2368-b6c1-8f06-e436bb2fa874 Would be worth opening an issue on cswin32.

For now it might be better to just keep it as `Matrix3x2` and pass it as `(XFORM*)(void*)&transform`.

2022-08-12 21:49 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs
> +                if (GetTextExtentPoint32(ch, out SIZE size))
`SIZE` to `Size` is missing from cswin32 and we should make sure we have an issue on it. For now I'd keep this as `Size` and cast to `SIZE*` after pinning it.

2022-08-12 21:49 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/TextExtensions.cs
>              return new Size(size.Width, size.Height);
Wow, this line is bizarre. Surprised I missed it when I was working on this. When `size` was `Size` it should have just returned `size`.

2022-08-13 02:02 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SelectPaletteScope.cs
> -using System.Drawing;
On line 54 we had a call `Graphics.GetHalftonePalette` which comes from `System.Drawing`. Since this file has been moved to namespace `Windows.Win32`, the compiler kept trying to find a `GetHalftonePalette` method from `Windows.Win32.Graphics`. Figured since there is only one instance of this call, removing the using and just putting `global::System.Drawing.Graphics.GetHalftonePalette()` would suffice. Thinking again, I could've also just had a static using for `System.Drawing.Graphics`

2022-08-13 03:05 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs
> +                if (GetTextExtentPoint32(ch, out SIZE size))
I looked again more carefully and cswin32 has implicit conversion for `SIZE` <-> `Size`, just need to cast the pointers. I will fix this up.

2022-08-13 03:33 UTC, JeremyKuhne approved these changes
:shipit: 🚀

2022-08-15 19:46 UTC, merged