Convert FormatMessageW to CsWin32
dotnet/winforms pull request #7588
Opened 2022-08-13 00:39 UTC by fernandanavamoya

Converted `FormatMessageW` to CsWin32

2022-08-13 03:44 UTC, JeremyKuhne requested changes

2022-08-13 03:44 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                                errorInfo = TrimNewline(IpBuffer);
The result is the number of characters in the buffer.  You can create a `ReadOnlySpan<char>` around the buffer with that length, then `.TrimEnd()` the `\n` and `\r` characters off of it. Then simply call `.ToString()` on the span to get your string.

2022-08-13 03:44 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                        char[] IpBuffer = ArrayPool<char>.Shared.Rent(256 + 1);
Local variables should be camel cased. `buffer` would be a good name here. When you are done with the array you need to return it to the `ArrayPool`.

2022-08-13 05:35 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                                errorInfo = string.Format(CultureInfo.CurrentCulture, string.Format(SR.DispInvokeFailed, "SetValue", hr));
You don't need to nest string.Format, I think this override will work - https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=net-6.0#system-string-format(system-iformatprovider-system-string-system-object-system-object). Though this is not part of your change, so take it or leave it. This would be a candidate for a second commit within the PR.

2022-08-16 22:57 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                                //errorInfo = TrimNewline(buffer);
Let's go ahead and remove this line :)

2022-08-16 22:57 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +        private static string TrimNewline(char[] errorInfo)
Is this method still in use? If not, we can remove this as well.

2022-08-17 00:07 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
> +                                ReadOnlySpan<char> buff = new(buffer);
Please use full words for variable names

2022-08-17 02:48 UTC, merged