Convert threads to CsWin32
dotnet/winforms pull request #7650
Opened 2022-08-24 01:03 UTC by fernandanavamoya

- Converted `SHCreateShellItem`, `SHGetPathFromIDListLongPath` and `SHBrowseForFolderW`.
- Converted `BrowseInfoFlags` to CsWin32 `BIF_*`
- Added `IShellItem = Interop.Shell32.IShellItem`, `Shell = Windows.Win32.UI.Shell` and `SIGDN = Interop.Shell32.SIGDN` to resolve ambigous usings.

2022-08-24 01:15 UTC, RussKie reviewed
👍

2022-08-24 01:15 UTC, RussKie commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowserStyles.cs
> +            ShowTextBox = unchecked((int)PInvoke.BIF_EDITBOX)
To improve readability could you please align all the value? We're generally striving to do this, but in some places we failed to do so.
```suggestion
            BrowseForComputer        = unchecked((int)PInvoke.BIF_BROWSEFORCOMPUTER),
            BrowseForEverything      = unchecked((int)0x00004000),
            BrowseForPrinter         = unchecked((int)PInvoke.BIF_BROWSEFORPRINTER),
            RestrictToDomain = unchecked((int)PInvoke.BIF_DONTGOBELOWDOMAIN),
            RestrictToFilesystem = unchecked((int)PInvoke.BIF_RETURNONLYFSDIRS),
            RestrictToSubfolders = unchecked((int)PInvoke.BIF_RETURNFSANCESTORS),
            ShowTextBox = unchecked((int)PInvoke.BIF_EDITBOX)
```

2022-08-24 17:42 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowser.cs
> +                if (listHandle is not null)
this condition seems wrong. Shouldn't it be `is null` ?

2022-08-24 17:43 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowser.cs
> +                        if (browseHandle is not null)
same here.  am i missing something?

2022-08-24 17:48 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SHCreateShellItem.cs
> +﻿// Licensed to the .NET Foundation under one or more agreements.
File name should be changed to match the method being defined.

2022-08-24 18:11 UTC, fernandanavamoya commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowser.cs
> +                if (listHandle is not null)
You're right. I totally missed that, sorry. Thank you :)

2022-08-24 18:28 UTC, KlausLoeffelmann requested changes
I had a few minor things.
Let's talk about testing before we merge this!

2022-08-24 18:45 UTC, fernandanavamoya commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowserStyles.cs
> +            BrowseForEverything = unchecked((int)0x00004000),
Not in CsWin32. There was one in [SHBrowserForFolder.cs](https://github.com/dotnet/winforms/pull/7650/files/src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHBrowseForFolder.cs), it was called BIF_BROWSEFOREVERYTHING but since this was the only place being referenced to, I decided to just add it directly. Do you think it would be better to either create a file inside our PInvoke library for this constant or to define it somewhere else?

2022-08-24 18:45 UTC, fernandanavamoya commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SHCreateShellItem.cs
> +            if (SHParseDisplayName(path, pbc: null, out ITEMIDLIST* ppidl, 0, psfgaoOut: null).Succeeded)
pbc is of type IBindCtx which is not an int therefore It would have to be casted to one: (System.Com.IBindCtx*)0. For this reason I believe it would be better to make it null but I could be wrong.

2022-08-24 18:48 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowserStyles.cs
> +            BrowseForEverything = unchecked((int)0x00004000),
Can you check if `BIF_BROWSEINCLUDEFILES (0x00004000)` would work? It's the same value, isn't it?

2022-08-24 20:21 UTC, fernandanavamoya commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SHCreateShellItem.cs
> +                Shell.IShellItem** ppsi = default;
I believe it would be better to make it just a pointer and call its reference inside the function. What are your thoughts about this?
```C#
Shell.IShellItem* ppsi = default;
if (SHCreateShellItem(pidlParent: null, psfParent: null, ppidl, &ppsi).Succeeded)
```

2022-08-25 05:50 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowserStyles.cs
> +            BrowseForEverything = unchecked((int)0x00004000),
I can't see `BIF_BROWSEFOREVERYTHING` in the metadata.

From `ShlObj_core.h`:
`#define BIF_BROWSEINCLUDEFILES  0x00004000  // Browsing for Everything`

You should just use that. it equals 16384 in decimal. I had to look it up.

2022-08-25 06:15 UTC, RussKie commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowserStyles.cs
> +            ShowTextBox = unchecked((int)PInvoke.BIF_EDITBOX)
Align these too please?

2022-08-25 18:00 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SHCreateShellItem.cs
> +            if (SHParseDisplayName(path, pbc: null, out ITEMIDLIST* ppidl, 0, psfgaoOut: null).Succeeded)
I meant this guy:
![image](https://user-images.githubusercontent.com/9663150/186736470-7d197fb2-1cdc-43f7-b4f3-09c70167fb0b.png)
That you put the `parametername: 0` (whatever it is 😄) in front of it?

2022-08-25 18:01 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SHCreateShellItem.cs
> +                Shell.IShellItem** ppsi = default;
Probably? I'd need to see the signature. Let me try and test.

2022-08-25 18:06 UTC, KlausLoeffelmann approved these changes
When I approve, but you it still need changes, do I need to approve another time here?

2022-08-25 21:02 UTC, fernandanavamoya commented
> When I approve, but you it still need changes, do I need to approve another time here?
I don't think so. I believe one time is enough. :)

2022-08-26 03:42 UTC, RussKie commented
> When I approve, but you it still need changes, do I need to approve another time here?

Approvals get reset after new changes are pushed in. This is by design in this repo.
So, yes, a new approval will be required.

2022-08-31 20:49 UTC, dreddy-work approved these changes

2022-09-01 22:32 UTC, lonitra approved these changes

2022-09-01 23:06 UTC, merged