Implementing UIA provider for TextBox and MaskedTextBox controls
dotnet/winforms pull request #7741
Opened 2022-09-06 05:54 UTC by NikitaSemenovAkvelon

Fixes #3421 

## Proposed changes

- Enabled UIA provider for `TextBox` with nested classes and `MaskedTextBox`.
- Refactored `TextBox's` child classes to reduce extra code.
- Implemented `IValueProvider` for `TextBoxBaseAccessibleObject`.
- Raised `AutomationFocusChangedEvent` in `OnGotFocus` methods.
- Added few unit tests.

## Customer Impact

- Improving development experience for `TextBox` with nested classes and `MaskedTextBox` control accessibility.
- 

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before

![Screenshot 2022-09-06 090441](https://user-images.githubusercontent.com/109065597/188556771-28808ba1-d5e1-4bd1-bc00-47d6403b390c.png)
_TextBox_
![Screenshot 2022-09-06 090506](https://user-images.githubusercontent.com/109065597/188556791-d37cf036-67c2-4257-a95a-2e39c4dd4768.png)
_MaskedTextBox_

### After

![Screenshot 2022-09-06 085747](https://user-images.githubusercontent.com/109065597/188556916-837b6660-dbad-427d-9fe5-aaa3769d0255.png)
![Screenshot 2022-09-06 090029](https://user-images.githubusercontent.com/109065597/188556942-994b7c6d-f9c3-4e80-8dfd-0f76ea2bec1b.png)
_TextBox_
![Screenshot 2022-09-06 085948](https://user-images.githubusercontent.com/109065597/188556931-f946f47f-e662-45eb-a41e-91934181452c.png)
![Screenshot 2022-09-06 090049](https://user-images.githubusercontent.com/109065597/188556955-f046bc77-07da-4b67-a839-2d4e6c6edfa8.png)
_MaskedTextBox_

## Test methodology 

- Manually
- Accessibility tools
- Unit tests
- CTI

## Accessibility testing  

- Inspect
- AI
- Narrator

 

## Test environment(s) 

- 8.0.100-alpha.1.22423.9

2022-09-08 11:22 UTC, dkazennov submitted a review, later dismissed
As I understand in it's principle it is similar to other PRs to add UIA provider to controls (like #7314 I did).
Looks good to me.

2022-09-11 20:20 UTC, vladimir-krestov reviewed
Looks good, but should be carefully tested

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
> +                AccessibilityObject.SetFocus();
Why do we need it?

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
> +                            return selectedGridEntry.AccessibilityObject.Name;
It duplicates. Try this:
```cs
return _owningPropertyGridView.SelectedGridEntry?.AccessibilityObject.Name ?? base.Name;
```

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
> +                AccessibilityObject.SetFocus();
What is the reasons for this?

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +                    UIA.ValuePatternId => true,
1) Did it work before? For .NET Framework for example? Or in Explorer?
2) Please check related methods of this pattern, they should be implemented as well. (like `Expand` method of expand-collapse pattern)

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +                => Owner is TextBoxBase { ReadOnly: true };
Great! 👍

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
> -                        }
It was necessary for RichTextBox AO, find the commit in history of this change to read the reason.
As I remember, you should keep it

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObject.cs
> -                    set => _parent.AccessibilityObject.Name = value;
I think, you should return it, because we don't set it via `base.Name`, we use the another logic

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
> -                SetStyle(ControlStyles.Selectable, false);
Please describe in details here and in the PR description why should we remove this.
It's necessary now and in the future to understand reasons of this change and make it clear if we will catch some possible future regressions

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
> +                    AccessibilityObject.SetFocus();
Doesn't the base implementation work?

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs
> -        public void TextBoxBaseAccessibleObject_Value_ReturnsEmpty_WithoutHandle()
Please keep this test and create new one for `Name`

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs
> +        public void TextBoxBaseAccessibleObject_Name_Default()
This test name is not clear enough

2022-09-11 20:20 UTC, vladimir-krestov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObjectTests.cs
> +            Assert.Equal(string.Empty, accessibleObject.Name);
Will `Assert.Empty` work?

2022-09-12 11:55 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
> +                AccessibilityObject.SetFocus();
It is for Narrator announcements. In AO.SetFocus method notifications are raised. The answer is also relevant to the same questions in other classes.

2022-09-12 11:56 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
> +                AccessibilityObject.SetFocus();
Answered here: https://github.com/dotnet/winforms/pull/7741#discussion_r968320837

2022-09-12 12:10 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
> -                        }
The first case was removed because of `UiaCore.UiaDisconnectProvider` is called from another place. Moreover, it is unreachable now.
But the second case is still here, below.

2022-09-12 12:20 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
> -                SetStyle(ControlStyles.Selectable, false);
Because it is a very old line of code. Without it the control works identically. But the line breaks the logic of calculating IsKeyboardFocusableProperty value. 
Moreover, via MSAA it always returns as true, even if control is disabled. But currently, it depends on its styles.
Do you think that is a good idea to put a comment about the removed code? I think it may be confusing.

2022-09-12 12:26 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
> +                    AccessibilityObject.SetFocus();
The base method contains additional logic which may be unnecessary. Therefore we don't call it here.

2022-09-12 12:44 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs
> -        public void TextBoxBaseAccessibleObject_Value_ReturnsEmpty_WithoutHandle()
Currently, the test doesn't make sense. `AO.Value` strongly referenced to `Owner.Text`, as in MSAA.

2022-09-12 12:46 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +                    UIA.ValuePatternId => true,
1. Yes, it works in Explorer and via MSAA.
2. Fixed and added a unit test for the SetValue method.

2022-09-12 14:21 UTC, dmitrii-drobotov reviewed
Nice work! Did you also test that there are no memory leaks for accessible objects after your changes?

2022-09-12 14:21 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
> -                        }
> The first case was removed because of `UiaCore.UiaDisconnectProvider` is called from another place. 

It's called only when control has `SupportsUiaProviders` as `true`, but there is `RichTextBox` for which it's `false`. RichTextBox could still somehow have an active `AccessibilityObject` for which we need to call `UiaCore.UiaDisconnectProvider`, so you definitely should keep it. Although maybe it would make sense to move it to `RichTextBox` class if it's the only affected control now.

2022-09-13 04:26 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
> -                        }
Oh, it's true. I've moved this logic to `RichTextBox`.

2022-09-15 20:08 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
> -                        }
>RichTextBox could still somehow have an active AccessibilityObject

RichTextBox should not register a `IRawElementProviderSimple` (because `SupportsUiaProviders` is false) and the MSAA Proxy provider should be ref-counted by the proxy. So we should not need to disconnect in this case and our disconnect call should not do anything.....

2022-09-15 20:12 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
> -                SetStyle(ControlStyles.Selectable, false);
Sorry, I don't follow why this line was removed. ControlStyles are part of the control. Provider should represent this control. Mayve providers should not take this style into account?

2022-09-15 20:49 UTC, Tanya-Solyanik reviewed
Looks good, I added some comments, please see them. Had you compared the resulting provider set and properties to what is required by the docs https://docs.microsoft.com/windows/win32/winauto/uiauto-supporteditcontroltype?

2022-09-15 20:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +            public override string? Name => Owner.AccessibleName ?? string.Empty;
Why does the base class implementation not work? TextBox should get AccessibleName from the label placed before it in the tab order. You dropped that part of the implementation. Maybe it does not make sense for the DGV  cells, but it makes sense for other TextBoxes.

2022-09-15 20:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +                RaiseAutomationEvent(UIA.AutomationFocusChangedEventId);
This implementation probably belongs to the ControlAccessibleObject. But not in this PR.

2022-09-15 20:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObject.cs
> +                            _ => string.Empty
Why did you change that? null and "" are interpreted differently by UIAutomation

2022-09-15 20:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
> +            // toolStripTextBox1
👍

2022-09-19 05:14 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +            public override string? Name => Owner.AccessibleName ?? string.Empty;
When I compared my implementation with MSAA behavior, the `AccessibleName` was empty. It was a reason why I implemented it that way. It was probably wrong and I've reworked it through the documentation above.

2022-09-19 10:52 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
> -                SetStyle(ControlStyles.Selectable, false);
Vladimir tried to investigate why the line was put here. He looked into branches that were created in 2010 and the line was still here. So, we didn't find the reason for that code and we decided that it may be obsolete.
However, it doesn't make sense, because the control is selectable. The property `IsKeyboardFocusableProperty` is depending on `Control.CanSelect` which is calculated here and uses this style (https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L4862).

2022-09-20 00:32 UTC, Tanya-Solyanik reviewed
Please see the question about the RichTextBox

2022-09-20 00:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> +*REMOVED*override System.Windows.Forms.DataGridViewTextBoxEditingControl.OnGotFocus(System.EventArgs! e) -> void
Add space after the `removed` prefix

2022-09-20 00:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> +*REMOVED*override System.Windows.Forms.DataGridViewTextBoxEditingControl.OnGotFocus(System.EventArgs! e) -> void
And remove this API from the `shipped` file.

2022-09-20 00:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
> +        protected override AccessibleObject CreateAccessibilityInstance() =>
I think overall it's more common to start the line with `=>` rather than to leave it on the previous line in this codebase. My reasoning is that CS is read left to right, so the more important statements should be on the left.

2022-09-20 00:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
> -                SetStyle(ControlStyles.Selectable, false);
I suppose this control being an internal one, we can change this property, as no one should be calling `CanSelect` on it.

2022-09-20 00:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs
> +            AccessibleObject accessibleObject = textBoxBase.AccessibilityObject;
Consider using a discard
`_ = textBoxBase.AccessibilityObject;`

2022-09-20 00:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs
> +            Assert.Equal(text, textBoxBase.Text);
Please insert a blank line before the validation.

2022-09-20 04:22 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs
> +            AccessibleObject accessibleObject = textBoxBase.AccessibilityObject;
I'm using the variable in a next line.

2022-09-20 16:16 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +            public override string? Name => Owner.AccessibleName ?? string.Empty;
I see that now accessible names match the TextBox content:
![Accessibility Insights shows accessible names of TextBoxes which match its content](https://user-images.githubusercontent.com/102954094/191308989-d1ec0542-910d-4a35-85ae-8779a0540f25.png)

I don't think this is expected behavior because it makes Narrator announce the content twice:

> TextBoxes window, Some long long text for a multiline TextBox that contains several lines with withspaces,tabs and numbers 12345, edit, Some long long text for a multiline TextBox that contains several lines with withspaces,tabs and numbers 12345, 
> Some long long text for a RTL TextBox, edit, Some long long text for a RTL TextBox, 
> Some long long text for a TextBox, edit, Some long long text for a TextBox, 

If there is a label before TextBox then name will be filled from it, but I think the default name should be empty.

2022-09-20 16:58 UTC, dmitrii-drobotov reviewed
Looks good! I also checked the [accessibility docs](https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-supporteditcontroltype) for edit control and found some inconsistencies. For example:

> If an edit control contains placeholder text (for example, a cue banner), the text should be used as the HelpText property unless the text can be edited by the user and then reused as placeholder text. For example, the Windows Internet Explorer address bar contains the text "about:Tabs" when a new tab is opened. This is not HelpText because it is a programmatic address that can be used or edited by the user.

We have the `PlaceholderText` property, so it's possible to set a placeholder, but the `HelpText` property won't be set, because it's not implemented in this PR. But what I found is that this functionality didn't work before, so this PR won't be a regression.

I didn't go through all the docs content but there is at least `UIA_IsPasswordPropertyId` with the same problem — it's not implemented in this PR but wasn't working before either. Should we fix all these inconsistencies in this PR or later as separate issues?

2022-09-20 18:09 UTC, Tanya-Solyanik commented
@dmitrii-drobotov  - great findings! Yes, please open a new issue.

2022-09-20 18:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
> -                        }
Had you tested rich text boxes after this change?

2022-09-20 18:15 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +            public override string? Name => Owner.AccessibleName ?? string.Empty;
I see this as an application problem that should be raised by the AccessibilityInsights for the app developer to fix. Framework does not know the business logic behind this text box and can't assign a meaningful name. As long as tooling raises the issue, we are good. 

If there is a code path to keep Accessible Name empty , it would be a better fix, but I wouldn't spend much time on it (I think we have a property that controls it)

2022-09-20 18:16 UTC, Tanya-Solyanik commented
/azp run

2022-09-22 16:44 UTC, CodeDummy-03 submitted a review, later dismissed
Looks good to me! ... Good work :)

2022-09-22 21:43 UTC, Tanya-Solyanik commented
@NikitaSemenovAkvelon - please confirm if you had test rich textbox for leaks and send this to the CTI team

2022-09-23 04:26 UTC, NikitaSemenovAkvelon commented
> @NikitaSemenovAkvelon - please confirm if you had test rich textbox for leaks and send this to the CTI team

Confirmed. There are no leaks of TextBox*AccessibleObject after closing a window with RichTextBox.
![image](https://user-images.githubusercontent.com/109065597/191891696-bdc0b5cb-85cf-4140-bd14-6d60cf757ac1.png)

2022-09-23 20:17 UTC, Tanya-Solyanik commented
@NikitaSemenovAkvelon  - is this the same set of objects as we have before the fix? BTW, I don't find the screenshot useful because it's not clear what code you executed to  get there. Specifically, did you run GC?

2022-09-26 05:16 UTC, NikitaSemenovAkvelon commented
> @NikitaSemenovAkvelon - is this the same set of objects as we have before the fix? BTW, I don't find the screenshot useful because it's not clear what code you executed to get there. Specifically, did you run GC?

Oh, sorry. I meant the RichTextBoxes form. The version without a fix has the same set of objects. Also, I didn't call GC.
![image](https://user-images.githubusercontent.com/109065597/192198596-1c0d0be5-ff1d-4d19-9ad7-1165c2d33683.png)

2022-09-27 02:51 UTC, Tanya-Solyanik approved these changes
Thank you! Please sent to the CTI team for testing if you had not done already.

2022-09-28 09:33 UTC, NikitaSemenovAkvelon commented
Fixed cases that CTI found.

2022-09-28 12:17 UTC, dmitrii-drobotov requested changes

2022-09-28 12:17 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
> +                AccessibilityObject?.RaiseAutomationEvent(UiaCore.UIA.Text_TextSelectionChangedEventId);
Please add a check for `IsAccessibilityObjectCreated`, because `AccessibilityObject` accessor creates an accessible object even if user doesn't use any accessibility tools.

2022-09-29 16:02 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MaskedTextBox.MaskedTextBoxAccessibleObjectTests.cs
> +        public void MaskedTextBoxAccessibleObject_GetPropertyValue_Value_AccessDenied_WithUseSystemPasswordChar()
I think it would make sense to add a similar test for regular `TextBox` to avoid possible regressions for it as well.

2022-09-30 08:00 UTC, dmitrii-drobotov approved these changes

2022-10-05 00:32 UTC, Tanya-Solyanik approved these changes

2022-10-05 00:37 UTC, merged

2022-10-13 03:38 UTC, MelonWang1 commented
Verified this issue with latest .NET 8.0.100-alpha.1.22512.27, Add support UIA provider for TextBox and MaskedTextBox controls, screenshort as below:
Textbox:
![inspect-textbox](https://user-images.githubusercontent.com/94418985/195493482-c0b85919-d791-4e21-ab41-ad48e9b8416c.png)
![ai-textbox](https://user-images.githubusercontent.com/94418985/195493512-2423d7ee-73fc-4247-b364-ec03084250f6.png)

MaskedTextbox:
![inspect-masktextbox](https://user-images.githubusercontent.com/94418985/195493499-f8622355-8d7d-4cca-a81f-7f49f608abfe.png)
![ai-masktextbox](https://user-images.githubusercontent.com/94418985/195493537-ca5bd4b1-4e39-4961-88dc-f77f2fc5f04a.png)