Convert Imm32 to CsWin32
dotnet/winforms pull request #7840
Opened 2022-09-25 07:24 UTC by elachlan

Relates to #7445

I was unsure how to convert `ImmGetConversionStatus` so I changed the existing pinvoke signature for now.

2022-09-26 00:55 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
> +            }
I am not 100% on the changes for `ImmGetConversionStatus`

2022-09-26 01:35 UTC, RussKie reviewed
LGTM

2022-09-26 17:45 UTC, lonitra requested changes
Just comments on using existing pattern, but otherwise looks good :)

2022-09-26 17:45 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.ImmGetContext.cs
> +            GC.KeepAlive(hWnd);
We want to use the following existing pattern: 
```suggestion
        public static HIMC ImmGetContext(in T hWnd) where T : IHandle<HWND>
        {
            HIMC result = ImmGetContext(hWnd.Handle);
            GC.KeepAlive(hWnd.Wrapper);
```

2022-09-26 17:45 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.ImmReleaseContext.cs
>              GC.KeepAlive(hWnd);
Same here
```suggestion
        public static BOOL ImmReleaseContext(in T hWnd, HIMC hIMC) where T : IHandle<HWND>
        {
            BOOL result = ImmReleaseContext(hWnd.Handle, hIMC);
            GC.KeepAlive(hWnd.Wrapper);
```

2022-09-27 16:49 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.ImmReleaseContext.cs
>              GC.KeepAlive(hWnd);
```suggestion
            GC.KeepAlive(hWnd.Wrapper);
```

2022-09-27 16:49 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.ImmGetContext.cs
> +            GC.KeepAlive(hWnd);
```suggestion
            GC.KeepAlive(hWnd.Wrapper);
```

2022-09-27 22:27 UTC, lonitra approved these changes
LGTM, thank you!

2022-09-28 00:23 UTC, merged