Enable nullability in LinkLabel
dotnet/winforms pull request #7877
Opened 2022-10-03 17:42 UTC by gpetrou

## Proposed changes

- Enable nullability in LinkLabel.

2022-10-05 23:17 UTC, dreddy-work approved these changes
LGTM.

2022-10-05 23:27 UTC, RussKie commented
@msftbot forget it

2022-10-05 23:27 UTC, RussKie commented
There are few new `!` operators and I'd like to review each one of those.

2022-10-05 23:28 UTC, RussKie requested changes
Blocking so I can review `!` operators

2022-10-12 18:11 UTC, gpetrou commented
> Blocking so I can review `!` operators

@RussKie any more thoughts on this PR?

2022-10-17 17:24 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
> +        public static void EnsureLinkFonts(Font baseFont, LinkBehavior link, ref Font? linkFont, ref Font? hoverLinkFont, bool isActive = false)
Hmm, we do have null checks below, so I assume that these should be nullable. Note that this method is used in two other classes that are not annotated yet where `linkFont` and `hoverLinkFont` seem to be nullable as well.

2022-10-18 01:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
> +        public static void EnsureLinkFonts(Font baseFont, LinkBehavior link, ref Font? linkFont, ref Font? hoverLinkFont, bool isActive = false)
https://github.com/gpetrou/winforms/blob/40be9862dcd56473e3ea255d741e1ab98181dbcc/src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs#L161-L247

I don't see any codepaths that would result in either `linkFont` or `hoverLinkFont` being null at the end of the call.

It looks like I forgot `[AllowNull]` annotations, updated.

2022-10-18 01:56 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
> +        public static void EnsureLinkFonts(Font baseFont, LinkBehavior link, ref Font? linkFont, ref Font? hoverLinkFont, bool isActive = false)
![image](https://user-images.githubusercontent.com/4403806/196317296-ba424ff7-7a3d-492b-905e-b375e9f8d670.png)

2022-10-19 22:40 UTC, RussKie approved these changes

2022-10-19 22:40 UTC, merged

2022-10-19 22:40 UTC, RussKie commented
Thank you