Enable CA1416
dotnet/winforms pull request #7888
Opened 2022-10-05 08:46 UTC by elachlan

Enabling roslyn analyzer CA1416.
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416

There is currently an issue with the analyzer resolving the windows 8.1 check.
https://github.com/dotnet/roslyn-analyzers/issues/6189

Feedback would be appreciated.

I removed `OsVersion` as it doesn't work with the analyzer. I feel this might be a reason to not use the analyzer, as the developer experience is easier with the static properties.

2022-10-05 08:47 UTC, elachlan commented
@RussKie what are your thoughts on the removal of `OsVersion` in favour of `OperatingSystem.IsWindowsVersionAtLeast()` checks?

2022-10-05 22:58 UTC, RussKie requested changes

2022-10-05 22:58 UTC, RussKie commented on Directory.Build.props
> +    <TargetFramework>$(TargetFrameworkName)$(TargetFrameworkVersion)-windows</TargetFramework>
This solution doesn't use the Windows Desktop SDK, hence we don't use the suffix

2022-10-05 22:58 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +                if (OperatingSystem.IsWindowsVersionAtLeast(major: 10, build: 15063))
To avoid making many changes, and (more importantly) to avoid the need to remember which build maps to which "human-redable" version I suggest retaingin `OsVersion` type, though turn it in a helper type which provides convinience API, e.g. seomthing like:
```cs
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static bool IsWindows10_1703OrGreater => OperatingSystem.IsWindowsVersionAtLeast(major: 10, build: 15063);
```

2022-10-05 23:01 UTC, RussKie commented
The build is failing with
```
##[error]src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Internals\DpiHelper.cs(404,17): error CA1416: (NETCORE_ENGINEERING_TELEMETRY=Build) This call site is reachable on: 'Windows' from version 6.3 to 10.0.14393. 'PInvoke.GetProcessDpiAwareness(HANDLE, out PROCESS_DPI_AWARENESS)' is only supported on: 'windows' 8.1 and later.
D:\a\_work\1\s\src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Internals\DpiHelper.cs(464,27): error CA1416: This call site is reachable on: 'Windows' from version 6.3 to 10.0.15063. 'PInvoke.SetProcessDpiAwareness(PROCESS_DPI_AWARENESS)' is only supported on: 'windows' 8.1 and later. [D:\a\_work\1\s\src\System.Windows.Forms.Primitives\src\System.Windows.Forms.Primitives.csproj]
##[error]src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Internals\DpiHelper.cs(464,27): error CA1416: (NETCORE_ENGINEERING_TELEMETRY=Build) This call site is reachable on: 'Windows' from version 6.3 to 10.0.15063. 'PInvoke.SetProcessDpiAwareness(PROCESS_DPI_AWARENESS)' is only supported on: 'windows' 8.1 and later.
```

2022-10-05 23:08 UTC, elachlan commented on Directory.Build.props
> +    <TargetFramework>$(TargetFrameworkName)$(TargetFrameworkVersion)-windows</TargetFramework>
I'll test without it, but I think it was required so that the analyzer didn't do linux checks. The other option is putting attributes in the assembly info.

2022-10-05 23:09 UTC, elachlan commented
> The build is failing with
> 
> ```
> ##[error]src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Internals\DpiHelper.cs(404,17): error CA1416: (NETCORE_ENGINEERING_TELEMETRY=Build) This call site is reachable on: 'Windows' from version 6.3 to 10.0.14393. 'PInvoke.GetProcessDpiAwareness(HANDLE, out PROCESS_DPI_AWARENESS)' is only supported on: 'windows' 8.1 and later.
> D:\a\_work\1\s\src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Internals\DpiHelper.cs(464,27): error CA1416: This call site is reachable on: 'Windows' from version 6.3 to 10.0.15063. 'PInvoke.SetProcessDpiAwareness(PROCESS_DPI_AWARENESS)' is only supported on: 'windows' 8.1 and later. [D:\a\_work\1\s\src\System.Windows.Forms.Primitives\src\System.Windows.Forms.Primitives.csproj]
> ##[error]src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Internals\DpiHelper.cs(464,27): error CA1416: (NETCORE_ENGINEERING_TELEMETRY=Build) This call site is reachable on: 'Windows' from version 6.3 to 10.0.15063. 'PInvoke.SetProcessDpiAwareness(PROCESS_DPI_AWARENESS)' is only supported on: 'windows' 8.1 and later.
> ```

I think this is a bug in the analyzer and I mentioned it in a related issue on the roslyn github. I will create an issue and see if I can get a proper response.

2022-10-05 23:29 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +                if (OperatingSystem.IsWindowsVersionAtLeast(major: 10, build: 15063))
This doesn't work in appeasing the analyzer. I'll raise an issue.

2022-10-05 23:35 UTC, RussKie commented on Directory.Build.props
> +    <TargetFramework>$(TargetFrameworkName)$(TargetFrameworkVersion)-windows</TargetFramework>
I think there's some sort of an property or an attribute to mark a project as "windows" only.

2022-10-05 23:36 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +                if (OperatingSystem.IsWindowsVersionAtLeast(major: 10, build: 15063))
Thinking out loud (since I haven't spent any time with these attributes) - can we apply respective attributes on the helper API 
```cs
[MethodImpl(MethodImplOptions.AggressiveInlining)]
[SupportedOSPlatform("windows10")]
public static bool IsWindows10_1703OrGreater => OperatingSystem.IsWindowsVersionAtLeast(major: 10, build: 15063);
```

2022-10-05 23:45 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +                if (OperatingSystem.IsWindowsVersionAtLeast(major: 10, build: 15063))
Otherway to re-write this to have a static property and class for each version and use those major/minor/build properties in the IsWindowsVersionAtLeast calls. But that seems messy.

2022-10-06 01:34 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs
> +        public static bool IsWindows8_1OrGreater() => OperatingSystem.IsWindowsVersionAtLeast(major: 6, minor: 3);
This one I think might give us issues based on this comment: https://github.com/dotnet/roslyn-analyzers/issues/6189#issuecomment-1269095452

2022-10-06 01:36 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs
> +        public static bool IsWindows8OrGreater() => OperatingSystem.IsWindowsVersionAtLeast(major: 6, minor: 2);
This was checking on version 8, but windows 8 is 6.2. 
We might have issues as well based on https://github.com/dotnet/roslyn-analyzers/issues/6189#issuecomment-1269095452

2022-10-06 01:38 UTC, elachlan commented on Directory.Build.targets
> +  <ItemGroup>
This causes a build failure for projects targeting `netstandard2.0`.
- System.Windows.Forms.PrivateSourceGenerators
- System.Windows.Forms.Analyzers
- System.Windows.Forms.Analyzers.CSharp

2022-10-06 02:06 UTC, RussKie commented on Directory.Build.targets
> +  <ItemGroup>
It may worth adding a comment to the source giving a little more cotext.

2022-10-06 02:08 UTC, elachlan commented on Directory.Build.targets
> +  <!-- CA1416 Validate platform compatibility-->
done.

2022-10-06 02:49 UTC, RussKie approved these changes

2022-10-06 02:50 UTC, merged