Convert multiple User32 PInvokes to CsWin32
dotnet/winforms pull request #7910
Opened 2022-10-09 11:30 UTC by elachlan

Convert multiple User32 PInvokes to CsWin32.

Related: #7445

2022-10-10 04:48 UTC, elachlan commented
@RussKie there is some weird CI problem here with a timeout. Can you please trigger it to build again?

2022-10-10 07:42 UTC, RussKie commented
/azp run

2022-10-10 10:57 UTC, elachlan commented
Cc @lonitra/@JeremyKuhne

2022-10-10 16:54 UTC, lonitra reviewed
There are some files that has been renamed but the contents of the file have not changed. Should the contents of those files remain the same?

2022-10-10 16:54 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.InvalidateRgn.cs
>              GC.KeepAlive(hWnd);
```suggestion
            GC.KeepAlive(hWnd.Wrapper);
```

2022-10-10 16:54 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
>          {
nit: we can remove the curly braces and use `=>` instead:
```c#
public static Screen FromPoint(Point point) =>
                SystemInformation.MultiMonitorSupport
                ? new Screen(PInvoke.MonitorFromPoint(point, MONITOR_FROM_FLAGS.MONITOR_DEFAULTTONEAREST))
                : new Screen((IntPtr)PRIMARY_MONITOR);
```

2022-10-10 16:54 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
>          public static Screen FromRectangle(Rectangle rect)
nit: same as above

2022-10-10 16:54 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
>          public static Screen FromHandle(IntPtr hwnd)
nit: ditto here

2022-10-11 17:30 UTC, lonitra reviewed
Looks good! Just a few small comments. :)

2022-10-11 17:30 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                PInvoke.SetMenu(this, (HMENU)IntPtr.Zero);
```suggestion
                PInvoke.SetMenu(this, HMENU.Null);
```

2022-10-11 17:30 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                        PInvoke.SetMenu(this, (HMENU)IntPtr.Zero);
```suggestion
                        PInvoke.SetMenu(this, HMENU.Null);
```

2022-10-11 17:30 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs
> +                    if (rootHwnd != IntPtr.Zero && !PInvoke.IsZoomed(rootHwnd))
```suggestion
                    if (!rootHwnd.IsNull && !PInvoke.IsZoomed(rootHwnd))
```

2022-10-11 17:30 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.ModalMenuFilter.cs
> +                    PInvoke.HideCaret((HWND)IntPtr.Zero);
```suggestion
                    PInvoke.HideCaret(HWND.Null);
```

2022-10-11 17:30 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
> +            Assert.True(PInvoke.GetScrollInfo((HWND)control.Handle, SCROLLBAR_CONSTANTS.SB_CTL, ref si));
Let's call control.HWND in this file instead of casting
```suggestion
            Assert.True(PInvoke.GetScrollInfo(control.HWND, SCROLLBAR_CONSTANTS.SB_CTL, ref si));
```

2022-10-11 22:07 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                PInvoke.SetMenu(this, (HMENU)IntPtr.Zero);
Thanks, I wasn't sure these were syntactically the same. I will keep it in mind for the future.

2022-10-11 23:13 UTC, JeremyKuhne commented
@elachlan I'll get a look tomorrow sometime. Trying to wrap up a change to use CsWin32 for our CCWs.

2022-10-12 22:06 UTC, JeremyKuhne requested changes
Thanks for doing this! Sorry for the delay and apologies for colliding with this with my dialog change. I added a few comments.

2022-10-12 22:06 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                PInvoke.EnableMenuItem(new HandleRef<HMENU>(this, hmenu), User32.SC.MINIMIZE, MENU_ITEM_FLAGS.MF_BYCOMMAND | MENU_ITEM_FLAGS.MF_GRAYED);
I'd consider just doing a `GC.KeepAlive(this)` at the end of this method to avoid all of the `HandleRef` initialization.

2022-10-12 23:14 UTC, elachlan commented
@JeremyKuhne I think I have sorted all the things you have raised.

2022-10-12 23:16 UTC, JeremyKuhne approved these changes

2022-10-13 02:15 UTC, RussKie requested changes
There are multiple unrelated commits in thie PR:
![image](https://user-images.githubusercontent.com/4403806/195483103-e94ae157-76c0-40ce-8c37-f857834091d0.png)

Please retain only those directly related to the CsWin32 work and remove the rest

2022-10-13 03:08 UTC, elachlan commented
> There are multiple unrelated commits in thie PR: 
> Please retain only those directly related to the CsWin32 work and remove the rest

I think because I hadn't pulled down and did a rebase it has broken it a bit. I am attempting to fix it now.

2022-10-17 20:38 UTC, lonitra approved these changes

2022-10-17 20:40 UTC, merged

2022-10-17 20:40 UTC, lonitra commented
Thank you! 🥳