Update Anchor Layout to support high Dpi machines.
dotnet/winforms pull request #7956
Opened 2022-10-17 20:38 UTC by dreddy-work

We have multiple [issues](https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+anchor+-label%3Atest-bug+-label%3A%22%3Aconstruction%3A+work+in+progress%22+-label%3Aapi-suggestion+-label%3Aapi-approved+-label%3Atenet-localization) reported in WinForms on around the anchor layout being problematic on higher DPI scale monitors, irrespective of application DPI mode. This PR outlines the changes being made in .NET 8.0 to address these issues along with setting the goal to support all supported application Dpi modes in WinForms

**Problem in Scope:**
	Anchored control’s position with respect to its parent should be able to determine at the design time and would only need to be changed   if there were explicit changes in the control’s Bounds. Bounds changes as result of Parent’s bounds change or Dpi scaling in which everything is scaled (interpolated) shouldn’t alter control’s relative position in its parent. However, Layout in WinForms computes the anchored control’s position every time there are changes to control’s Bounds. This is and are leading to the issues we have been seeing. The following source snippet that is being serialized in the WinForms designer and highlights are when anchor computations are happening and why they could be wrong or unnecessary.

```CS
this.button14.Anchor = (System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) -> Layout tries to compute anchors with default button14 size and without parent. 
this.button14.Location = new System.Drawing.Point(431, 110); -> Layout updates computed anchors for this new bounds, still with default size and no parent.
this.button14.Name = "button14";
this.button14.Size = new System.Drawing.Size(111, 23); -> Layout updates computed anchors for this new bounds, still with no parent.
this.Controls.Add(this.button14); -> Layout updates computed anchors with parents default size. Which may still be wrong.
this.Size = new System.Drawing.Size(828, 146); -> Layout updates computed anchors with parents new size but this size could change based on the Dpi when parent Handle is created.
this.ResumeLayout(false) -> Layout updates computed anchors with parents size. Dpi of the screen is still not considered (Handle creations or delayed until control is visible)

```

The above snippet does not represent the complete set of instances where anchor computations are unnecessary and may hold invalid anchor values. It gets even more complicated when nested user controls are involved.

**Known issues:**
We have multiple issues reported [here](https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+anchor+-label%3Atest-bug+-label%3A%22%3Aconstruction%3A+work+in+progress%22+-label%3Aapi-suggestion+-label%3Aapi-approved+-label%3Atenet-localization) from customers and some of them are direct result of anchor miscalculations. The following are snippets of the category of issues we currently see.

**Expected:** 
![image](https://user-images.githubusercontent.com/36968667/196277747-0cbf1820-f42d-4279-9e61-ba67a2a43a6a.png)

![image](https://user-images.githubusercontent.com/36968667/196277893-6325ff9e-0c37-4c89-862d-69b7d00e3473.png)

**Current Behavior:** 
![image](https://user-images.githubusercontent.com/36968667/196277793-26f67908-0f63-4104-8edf-1c3abacad129.png)

![image](https://user-images.githubusercontent.com/36968667/196277917-8784b2e1-514e-460d-9b5c-904ac9d9eee5.png)

**Proposed solution:** 
Unnecessary control’s anchors computation is the root cause for many issues reported so far. We also have issues with how we are computing anchor s but that is less of a concern.  In this proposal, we are delaying the anchors computation to the specific time in the layout flow - which is when the controls and its parent’s handles are created. By that time, in majority of the scenarios, the controls and its parent’s bounds are finalized, and the display monitor’s DPI applied on them. 
We may still have cases where developers are forced to handle creation explicitly, out of order, but those cases can be handled separately for any anchor miscalculations. The following are the events we would be using to compute anchors.

- 	OnCreateControl
- 	OnParentChanged
- 	SetBounds

**Source snippet:**

```CS
protected virtual void OnCreateControl()
{
UpdateAnchorsIfRequired();
}
private void UpdateAnchorsIfRequired()
 {
   if (!LocalAppContextSwitches.EnableImprovedAnchorLayout)
    {
      return;
    }

   if (IsHandleCreated && Parent is not null && Parent.IsHandleCreated)
    {
      DefaultLayout.UpdateAnchorInfo(this, enableImprovedAnchorLayout: true);
    }
 }
```
**Simplifying Anchor calculations:**
The current anchor calculations implementation seems complicated and appears to have been a were the result of unnecessary attempts to calculate them anchors with invalid bounds. Making anchor calculation changes as simple as we see in the above pic. 
```CS
private static void ComputeAnchorInfo(IArrangedElement element)
 {
   AnchorInfo? anchorInfo = GetAnchorInfo(element);
   if (anchorInfo is null)
    {
       anchorInfo = new AnchorInfo();
       SetAnchorInfo(element, anchorInfo);
    }

    Rectangle displayRect = element.Container.DisplayRectangle;
    Rectangle elementBounds = element.Bounds;

    int x = elementBounds.X;
    int y = elementBounds.Y;

    anchorInfo.Left = x;
    anchorInfo.Top = y;

    anchorInfo.Right = displayRect.Width - (x + elementBounds.Width);
    anchorInfo.Bottom = displayRect.Height - (y + elementBounds.Height);
 }
```
**Risk mitigation:**
Layout in general is complex and could impact every component in the WinForms . In order to reduce the potential risk and provide backward compatibility, these changes are `quirked` under switch `System.Windows.Forms.EnableImprovedAnchorLayout `. These changes are by default on for new/migrating applications targeting .NET 8.0 but the developers can control this by setting the above-mentioned flag to `false` in the runtimeconfig .json for the application.

2022-10-20 20:09 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +        public static bool EnableAnchorLayoutV2
`EnableAnchorLayoutV2` sounds like a method. Do we have a standardized method how to name the switches? I'd prefer something `IsAnchorLayoutV2Enabled` to make it easier to read.

2022-10-20 20:11 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                        Control control = controlsCollection[i];
Do you want an extra local variable for this?

2022-10-20 20:30 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                        Control control = controlsCollection[i];
I cleaned extra lines that i had in my original change but given that this is used twice, It still be better to store in local variable.

2022-10-20 22:55 UTC, JeremyKuhne requested changes
Mostly nits. If you can try to update to interpolated strings wherever you're touching code it helps avoid extra work / allocations. They are significantly better everywhere and Debug statements will completely skip forming the string if conditions aren't met.

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                              + ", " + top
Can you please convert this to an interpolated string (there is a quick fix for it).

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                                                                      + left
Please make this an interpolated string

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        // Checks if element is ready to compute anchors by checking if this element
Please use XML comments for methods.

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            ) => LocalAppContextSwitches.EnableAnchorLayoutV2 ? element is not Control control || control.IsHandleCreated : true;
Inverting this would make it easier to read

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            Debug.WriteLineIf(CompModSwitches.RichLayout.TraceInfo, "Parent displayRectangle" + parentDisplayRect);
Please use interpolated strings

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            Debug.WriteLineIf(CompModSwitches.RichLayout.TraceInfo, "anchor info (l,t,r,b): (" + anchorInfo.Left + ", " + anchorInfo.Top + ", " + anchorInfo.Right + ", " + anchorInfo.Bottom + ")");
Please convert this to an interpolated string.

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        /// (ToDo)https://github.com/microsoft/winforms/blob/main/docs/AnchorLayoutChangesInNet80.md for more details.
Don't check in a TODO. Make sure there is an issue for the TODO.

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        /// Updates anchor calculations if the control is parented and both control's and its parent's handle are created.
Please indent by 1 with XML

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            if (control is null || control.Parent is null)
I'd check IsHandleCreated here before parent checks to avoid any unexpected work with the virtual ParentInternal that gets called with control.Parent. Also, I'd combine the current/parent if checks to reduce the length of this method.

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                && (ParentInternal is not null)
parenthesis aren't needed here

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // In V2(.NET 8.0 and beyond) version, anchors are updated after the controls bounds changed
I don't understand the comment here and the commented out code.

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                // If Anchored both left anf right, element's width will be forced to update according to
```suggestion
                // If anchored both Left and Right, element's width will be forced to update according to
```

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                // parents DisplayRect.
```suggestion
                // parent's DisplayRect.
```

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                // If anchored Right but not Left, element's X- co-ordinate should be updated according to parents DisplayRect.
```suggestion
                // If anchored Right but not Left, element's X- co-ordinate should be updated according to parent's DisplayRect.
```

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // Element neither anchored Right or Left but anchored Top or Bottom,  elements X-coordinate is adjusted relative to  DisplayRect chnage.
```suggestion
                    // Element neither anchored Right or Left but anchored Top or Bottom,  elements X-coordinate is adjusted relative to DisplayRect change.
```

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // If Anchored both Top anf Bottom, element's height will be forced to update according to
```suggestion
                    // If Anchored both Top and Bottom, element's height will be forced to update according to
```

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // parents DisplayRect.
```suggestion
                    // parent's DisplayRect.
```

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                // If anchored Bottom but not Top, element's Y- co-ordinate should be updated according to parents DisplayRect.
```suggestion
                // If anchored Bottom but not Top, element's Y co-ordinate should be updated according to parent's DisplayRect.
```

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // Element neither anchored Top or Bottom but anchored Right or left,  elements X-coordinate is adjusted relative to  DisplayRect chnage.
```suggestion
                    // Element neither anchored Top or Bottom but anchored Right or left, elements X coordinate is adjusted relative to the DisplayRect change.
```

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            // We clip element but not position at negative location with respect parents DisplayRect.
```suggestion
            // We clip the element but not the position at negative locations with respect to the parent's DisplayRect.
```

2022-10-20 22:55 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            if (x < 0 || width < 0 || y < 0 || height < 0)
Put this as a `DebugWriteLineIf` condition to have this completely elided in release builds.

2022-10-20 23:30 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // In V2(.NET 8.0 and beyond) version, anchors are updated after the controls bounds changed
I disabled while i was testing to see impact. put that back.

2022-10-20 23:47 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        /// (ToDo)https://github.com/microsoft/winforms/blob/main/docs/AnchorLayoutChangesInNet80.md for more details.
Will be sending doc update in a separate PR. Its being reviewed currently.

2022-10-21 00:20 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +        public static bool EnableAnchorLayoutV2
@KlausLoeffelmann , can we debate on the key name on the doc i shared with team earlier the week. We can come back and change to whatever we decide there.

2022-10-21 19:54 UTC, JeremyKuhne submitted a review, later dismissed

2022-10-23 22:07 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                // and doesn't need to be scaled.
```suggestion
                // In the v2 layout, anchors are updated/computed after the controls bounds changed
                // and, thus, doen't need to be scaled.
```

2022-10-23 22:09 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                // parent's DisplayRect.
```suggestion
                // If anchored both left and right, the element's width will be forced to update according to
                // the parent's DisplayRect.
```

2022-10-23 22:10 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                // If anchored Right but not Left, element's X- co-ordinate should be updated according to parent's DisplayRect.
```suggestion
                // If anchored Right but not Left, the element's X-coordinate should be updated according to the parent's DisplayRect.
```

2022-10-23 22:13 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // Element neither anchored Right or Left but anchored Top or Bottom,  elements X-coordinate is adjusted relative to parent's DisplayRect change.
```suggestion
                    // The element neither anchored Right or Left but anchored Top or Bottom, the element's X-coordinate
                    // is adjusted relative to the parent's DisplayRect.
```

2022-10-23 22:13 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // If anchored both Top and Bottom, element's height will be forced to update according to parent's DisplayRect.
```suggestion
                    // If anchored both Top and Bottom, the element's height will be forced to update according to the parent's DisplayRect.
```

2022-10-23 22:14 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                // If anchored Bottom but not Top, element's Y- co-ordinate should be updated according to parent's DisplayRect.
```suggestion
                // If anchored Bottom but not Top, the element's Y-coordinate will be updated according to the parent's DisplayRect.
```

2022-10-23 22:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // Element neither anchored Top or Bottom but anchored Right or left,  elements X-coordinate is adjusted relative to parent's DisplayRect change.
```suggestion
                    // The element neither anchored Top or Bottom but anchored Right or Left, the element's X-coordinate
                    // is adjusted relative to the parent's DisplayRect.
```

2022-10-23 22:20 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            // We clip the element but does not position element at negative location with respect to parents DisplayRect.
```suggestion
            // Clip the element but don't position it at a negative location with respect to the parent's DisplayRect.
```

2022-10-23 22:21 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        private static Rectangle ComputeAnchorDestination(IArrangedElement element, Rectangle displayRect)
```suggestion
        private static Rectangle ComputeAnchorBounds(IArrangedElement element, Rectangle displayRect)
```

2022-10-23 22:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        private static Rectangle ComputeLegacyAnchorDestination(IArrangedElement element, Rectangle displayRect, bool measureOnly)
```suggestion
        private static Rectangle ComputeAnchoredBounds(IArrangedElement element, Rectangle displayRect, bool measureOnly)
```

2022-10-23 22:22 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                : ComputeLegacyAnchorDestination(element, displayRect, measureOnly);
```suggestion
            return LocalAppContextSwitches.EnableAnchorLayoutV2
                ? ComputeAnchoredBoundsV2(element, displayRect)
                : ComputeAnchoredBounds(element, displayRect, measureOnly);
```

2022-10-23 22:30 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // handle was created. This case handle those scenarios and compute anchors for the element.
```suggestion
                    // It is possible that the parent's handle might not have been created when the element's
                    // handle was created. If that's the case, compute the element's anchors.
```

2022-10-23 22:34 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        /// handle are created to make sure bounds are applied with current DPI.
```suggestion
        ///  Inidcates that the element is ready to compute its anchors.
```

2022-10-23 22:35 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        ///  Updates the element's anchors information based on element's current bounds.
```suggestion
        ///  Updates the element's anchors information based on the element's current bounds.
```

2022-10-23 22:37 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            if (!CommonProperties.GetNeedsAnchorLayout(element))
It's not obvious how the comment correlates with the code - e.g., layout v2 here is an implementation detail.
Suggest removing the comment completely.

2022-10-23 22:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            // Use AnchorLayoutV2 if application targets .NET 8.0 and beyond.
This comment doesn't add much value, suggest removing it.

2022-10-23 22:38 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            AnchorInfo oldAnchorInfo = new AnchorInfo
```suggestion
            AnchorInfo oldAnchorInfo = new()
```

2022-10-23 22:42 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            // Use AnchorLayoutV2 if application targets .NET 8.0 and beyond.
I differ on this. It helps when it was introduced without looking further.

2022-10-24 06:53 UTC, RussKie requested changes

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                            : Math.Max(prefSize.Height, anchorDest.Bottom);
Incorrect indentation

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +            return (form, button);
`button` isn't hosted on the `form`

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +            button.Anchor = AnchorStyles.Left | AnchorStyles.Top | AnchorStyles.Right | AnchorStyles.Bottom;
This is unnecessary, it gets set in the test (line:44).

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +            form.Controls.Add(button);
Why not do this in `GetFormWithAnchoredButton`?

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +                Assert.Equal(height, button1.Bounds.Height);
Trailing spaces

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +            void OnFormShown(object? sender, EventArgs e)
```suggestion
        private static (Form, Button) GetFormWithAnchoredButton(AnchorStyles buttonAnchors)
        {
            Form form = new();
            form.Size = new Size(200, 300);

            Button button = new()
            {
                Location = new Point(20, 30),
                Size = new Size(20, 30),
                Anchor = buttonAnchors
            };

            DefaultLayout.AnchorInfo anchorInfo = DefaultLayout.GetAnchorInfo(button);
            Assert.Null(anchorInfo);

            form.Controls.Add(button);

            return (form, button);
        }

        [WinFormsTheory]
        [InlineData(AnchorStyles.Top, 120, 30, 20, 30)]
        [InlineData(AnchorStyles.Left, 20, 180, 20, 30)]
        [InlineData(AnchorStyles.Right, 220, 180, 20, 30)]
        [InlineData(AnchorStyles.Bottom, 120, 330, 20, 30)]
        [InlineData(AnchorStyles.Top | AnchorStyles.Left, 20, 30, 20, 30)]
        [InlineData(AnchorStyles.Top | AnchorStyles.Right, 220, 30, 20, 30)]
        [InlineData(AnchorStyles.Top | AnchorStyles.Bottom, 120, 30, 20, 330)]
        [InlineData(AnchorStyles.Left | AnchorStyles.Right, 20, 180, 220, 30)]
        [InlineData(AnchorStyles.Bottom | AnchorStyles.Right | AnchorStyles.Top | AnchorStyles.Left, 20, 30, 220, 330)]
        public void ResizeAnchoredControlsParent_HanldeCreated_AnchorsApplied(AnchorStyles anchor, int x, int y, int width, int height)
        {
            var (form, button) = GetFormWithAnchoredButton();
            form.Shown += OnFormShown;

            // Showing the dialog will execute the assertions
            form.ShowDialog();

            button?.Dispose();
            form?.Dispose();
            return;

            void OnFormShown(object? sender, EventArgs e)
```

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +                //Resize Form to compute button anchors.
```suggestion
                // Resize the form to compute button anchors.
```

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +        public void ResizeAnchoredControlsParent_HanldeCreated_AnchorsApplied(AnchorStyles anchor, int x, int y, int width, int height)
```suggestion
        public void ResizeAnchoredControlsParent_HanldeCreated_AnchorsApplied(AnchorStyles anchor, int expectedX, int expectedY, int expectedWidth, int expectedHeight)
```

Any reason not to use `Rectangle` instead?

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +                Control button1 = formLocal.Controls[0];
There's no reason for this, we can use `form` and `button` variables.

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +        private static (Form, Button) GetFormWithAnchoredButton()
It's customary in this codebase to place all helpers after the test methods.
Ditto in src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs
> +        public void ControlNotParented_NoAnchorsComputed()
Please follow the established naming convention: https://github.com/dotnet/winforms/blob/main/docs/testing.md#naming

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs
> +            Dispose(form, button);
[nit/readability] The code looks smashed together, which inhibits the readability of it. Some blank lines between each logical section would help, e.g.:
```suggestion
            var (form, button) = GetFormWithAnchoredButton();

            DefaultLayout.AnchorInfo anchorInfo = DefaultLayout.GetAnchorInfo(button);
            Assert.Null(anchorInfo);

            _ = button.Handle; // Force handle creation;
            Assert.Null(anchorInfo);

            Dispose(form, button);
```

2022-10-24 06:53 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs
> +            _ = button.Handle; // Force handle creation;
We don't use this pattern, instead we'be using either 
```suggestion
            button.CreateControl();
```
\- or -
```suggestion
           Assert.NotEqual(IntPtr.Zero, button.Handle);
```

2022-10-24 16:21 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +                Control button1 = formLocal.Controls[0];
we can but I wanted to make this complete and avoid further refactoring in case this method moved out from this scope.

2022-10-24 16:22 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs
> +            _ = button.Handle; // Force handle creation;
Create control does lot more. I just wanted to create Handle.

2022-10-24 16:49 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +        public void ResizeAnchoredControlsParent_HanldeCreated_AnchorsApplied(AnchorStyles anchor, int x, int y, int width, int height)
Each anchor property is a separate calculation and like to keep it that way in tests.

2022-10-24 18:41 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs
> +            _ = button.Handle; // Force handle creation;
Could you please add a comment to the test explaining the scenario where Handle is created but control is not.

Also, I prefer an Assert to a comment, but this is up to you.

2022-10-24 20:31 UTC, Tanya-Solyanik reviewed
I added some minor comments but it's really hard to review this change. The most interesting part is the test application set.

2022-10-24 20:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            anchorInfo.Left = element.Bounds.Left;
I see that this is the old code, but it would be nice to improve it a bin and factor out `element. Bounds` into a local var.

2022-10-24 20:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +                //Resize the form to compute button anchors.
add a whitespace after slashes

2022-10-24 20:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +        public void ResizeAnchoredControlsParent_HanldeCreated_NewAnchorsApplied(AnchorStyles anchor, int expectedX, int expectedY, int expectedWidth, int expectedHeight)
`anchor` -> `anchors` because these are flags

2022-10-24 20:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
> +            Form form = new();
these names - form and button are inconsistent with names used above (button1).

2022-10-24 20:31 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            DefaultLayout.UpdateAnchorInfoV2(this);
I expected to see V1 code being skipped in this case, how was it scaled before the change?

2022-10-25 00:02 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs
> +            _ = button.Handle; // Force handle creation;
> Create control does lot more. I just wanted to create Handle.

Then please use the 2nd snippet.
I've looked at the `CreateControl` code and I don't really see "lot more work" there in this scenario besides settings flags. If you could provide some insights and, and how that affects the tests it would be great.

2022-10-25 00:08 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs
> +            _ = button.Handle; // Force handle creation;
In this scenario functionally you may not see difference but i don't need to call that extra code from `CreateControl` (which sets some flag and raise event) method. Test was to ensure Handle creation doesn't alter Anchors yet. Well, if you both feel Assert is more meaningful, i will change to it but by then we are hiding the fact that Handle is just created.

2022-10-25 01:18 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs
> +            _ = button.Handle; // Force handle creation;
> by then we are hiding the fact that Handle is just created.

I don't think we are hiding anything here. Accessing `Handle` force-creates a handle, if it's not created. 
This has been the source of many bugs.

2022-10-26 21:16 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +                        {
These switches default in .NET8.0 and test matrix for this product is Windows 10 and above. Windows 7 is not officially listed but doesn't bail out. We don't.

2022-10-26 21:17 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                : ComputeAnchoredBounds(element, displayRect, measureOnly);
right and DisplayRect passed is empty in those cases. In V2, we return element bounds.

2022-10-26 21:18 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            Debug.WriteLineIf(x < 0 || width < 0 || y < 0 || height < 0, $"\t\t'{element}' destination bounds resulted in negative");
changed it to negative width or height. Not an error but not a common scenario, so logging for debug purpose.

2022-10-26 21:19 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                if (IsAnchored(anchor, AnchorStyles.Right))
Maybe. We can clean that later as this method is used in many more places.

2022-10-26 21:20 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            // Clip the element but don't position it at a negative location with respect to the parent's DisplayRect.
Removed this condition and matching with what we have in legacy.

2022-10-26 21:22 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +            DefaultLayout.UpdateAnchorInfoV2(this);
It was part of Layout that will be triggered after assigning parent.

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +        ///  Returns AnchorLayoutV2 switch value from runtimeconfig.json. Defaults to true if application is targeting .NET 8.0 and beyond.
The comment has a lot of implementation details, which aren't enforcable. For example, nowhere here we read runtimeconfig.json. We also don't have any guarantees that it would be coming from there. 
Summary tag isn't suited for explaining the default values. Please refer to https://learn.microsoft.com/dotnet/csharp/language-reference/xmldoc/recommended-tags and https://review.learn.microsoft.com/en-au/help/contribute-ref/how-to-write-net-docs?branch=main.

```suggestion
        ///  Indicates whether AnchorLayoutV2 feature is enabled.
```

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +                // is limited to Windows 10 and above versions.
I couldn't find any information on the .NET 8 OS support. [.NET 7 still supports W7SP1](https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md).
Could you please share a link to the official document?

I also feel that the comment largely duplicating information obvious from code:
- we're in the .NET 8 branch - so "_introducing switch defaults in .NET 8.0+_" feels redundant (this code doesn't exist in the earlier versions), and
- `OsVersion.IsWindows10_1703OrGreater()` makes "this product is limited to Windows 10 and above versions." redundant too.

Perhaps the whole comment can be replaced with a link to the official document.

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        ///  and layout child anchored elements with V2 version.
```suggestion
        ///  and to layout child anchored elements with V2 version.
```

What's a "child anchored elements"? Does it mean "anchored children controls"?

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            // element is not Control type, use legacy layout.
```suggestion
            // AnchorLayoutV2  only supports Control types. If the feature is disabled or
            // the element is not of Control type, use the original layout method.
```

```suggestion
```

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            // If container handle is not created, child controls do not have anchors computed.
```suggestion
            // If the container handle is not created, no need to compute anchors for its children controls.
```

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // when the control's handle was created. If that's the case, compute the control's anchors.
```suggestion
                    // It is possible that the parent's handle might not have been created
                    // when the control's handle was created. If that's the case, compute the control's anchors.
```

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                    // Parent was resized to fit its parent, or screen, we need to reuse old anchors info to prevent losing control beyond bottom edge.
```suggestion
                    // The parent was resized to fit its parent or the screen, we need to reuse the old anchors info to prevent positioning the control beyond the bottom edge.
```

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                        // Control might have been resized, update Top anchors.
```suggestion
                        // The control might have been resized, update the Top anchor.
```

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            if (!CommonProperties.GetNeedsAnchorLayout(control))
We should add at least an assert that this method is only called with AnchorLayoutV2 enabled. Likewise add an assert to the original code paths to verify those are only called with AnchorLayoutV2 is disabled.

2022-10-27 02:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        ///  Developers may opt-out of this new behavior using switch <see cref="LocalAppContextSwitches.AnchorLayoutV2"/>.
```suggestion
        ///  Updates anchors calculations if the control is parented and both control's and its parent's handle are created.
```

2022-10-27 16:21 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +        // https://github.com/microsoft/winforms/blob/main/docs/AnchorLayoutChangesInNet80.md
Correcting link. regarding change or moving location, I am not planning on it for now. Will check once feature is settled.

2022-10-27 16:36 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +                // is limited to Windows 10 and above versions.
I disagree on some of these points. 

- We introduced switch in .NET 7.0 but is defaulted only in 8.0. 
- Feature is mainly addressing anchors on high DPI machines and DPI is supported on Windows 8.1 and above. our.NET 8.0 support OS matrix is not out yet but I remember discussing in tactics on 7.0 support being limited given we don't block or we don't go beyond to support it.
- This comment is a result of earlier feedback. Given it is not sending any misinformation, I will keep the comment.

2022-10-27 21:10 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +        ///  Returns AnchorLayoutV2 switch value from runtimeconfig.json. Defaults to true if application is targeting .NET 8.0 and beyond.
@dreddy-work - you can use `<devdoc>` tag for comments that explain usage.

2022-10-27 21:56 UTC, Tanya-Solyanik approved these changes

2022-10-27 21:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +                int centerPos = displayRect.Width / 2;
nit: `centerPos` -> `center`

2022-10-27 21:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +            bool usedV2Layout = UseAnchorLayoutV2(container);
nit: `usedV2Layout` -> `useV2Layout`

2022-10-27 21:56 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +        internal void UpdateAnchorsIfRequired()
Should it be private?

2022-10-27 22:41 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> -            if (cachedSwitchValue < 0)
This syntax was selected because it generated the tightest IL, please change it back

2022-10-27 22:42 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +                // is limited to Windows 10 and above versions.
word `is` is repeated twice

2022-10-27 22:55 UTC, Tanya-Solyanik approved these changes

2022-10-28 00:06 UTC, dreddy-work commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +        // https://github.com/microsoft/winforms/blob/tree/main/docs/design/anchor_layout_changes_in_net80.md
Changing name to anchor-layout-changes-in-net80.md when renaming it on doc PR. Intentionally underscored here.

2022-11-01 16:33 UTC, merged

2022-11-02 00:34 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +        // https://github.com/microsoft/winforms/blob/tree/main/docs/design/anchor_layout_changes_in_net80.md
❗ This link is still incorrect.

2022-11-02 00:34 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +        ///  https://github.com/microsoft/winforms/blob/tree/main/docs/design/anchor_layout_changes_in_net80.md for more details.
diito

2022-11-02 00:35 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        ///  https://github.com/microsoft/winforms/blob/tree/main/docs/design/anchor_layout_changes_in_net80.md for more details.
ditto

2022-11-02 00:38 UTC, RussKie commented
A friendly reminder to raise a breaking doc in https://github.com/dotnet/docs/

2022-11-02 21:17 UTC, dreddy-work commented
https://github.com/dotnet/docs/issues/32145