Fix `FolderBrowserDialog.ShowDialog`
dotnet/winforms pull request #7982
Opened 2022-10-21 08:06 UTC by elachlan

Fixes #7981

2022-10-21 08:07 UTC, elachlan commented
CC: @lonitra @JeremyKuhne

2022-10-21 10:06 UTC, RussKie commented
We can probably enumerate open windows and search for the dialog window.
In UIIntegration project we have methods to search for controls, maybe something like that can be used...
Just random thoughts

________________________________
From: Lachlan Ennis ***@***.***>
Sent: Friday, 21 October 2022 7:09 PM
To: dotnet/winforms ***@***.***>
Cc: Igor Velikorossov ***@***.***>; Review requested ***@***.***>
Subject: Re: [dotnet/winforms] Fix `FolderBrowserDialog.ShowDialog` (PR #7982)


I have no idea how to write a test for this since showdialog() will block.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fpull%2F7982%23issuecomment-1286614926&data=05%7C01%7Cigor.velikorossov%40microsoft.com%7Cfa810004f5ac4c0f01d008dab33b8428%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638019365456615161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yrc0ciQiOxhZHDXvBTAFuYDt2gGMhTMJ7NugEn6s5Ng%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABBTEXSJNVU7337ZF2QYVSLWEJFR5ANCNFSM6AAAAAARK5ICHE&data=05%7C01%7Cigor.velikorossov%40microsoft.com%7Cfa810004f5ac4c0f01d008dab33b8428%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638019365456615161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ToTCzQTuf6ZEn%2BKQTAbV620CKzRPE2eu6tRpMJk0gDI%3D&reserved=0>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2022-10-21 17:34 UTC, JeremyKuhne requested changes
Thanks for looking into this! Just one comment.

2022-10-21 17:34 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> +                    Span<char> buffer = stackalloc char[PInvoke.MAX_PATH + 1];
This should be inside the `if (selectedPidl is not null)` and should assign to `char* buffer` so you can just pass it as the argument. Then you can avoid the unnecessary pin syntax.

2022-10-21 22:26 UTC, elachlan commented
The other issue was we were passing lParam to `GCHanle.FromIntPtr` which caused another exception since its `null` when `msg == 'BFFM_INITIALIZED'`.

2022-10-21 22:39 UTC, elachlan commented
With regards to the tests. I looked at adding a `RunCommonDialogAsync` to `ControlTestBase` Or making a `ComponentTestBase`. Issue is that `CommonDialog` doesn't have a `Close()` method, since its always called via `ShowDialog`. I think someone more skilled will need to put together a plan so we can test the folder/save/open dialogs.

2022-10-23 23:33 UTC, RussKie commented
> I have no idea how to write a test for this since `showdialog()` will block.

Could probably try something like this: https://stackoverflow.com/a/42405020/2338036.

2022-10-23 23:45 UTC, elachlan commented
> > I have no idea how to write a test for this since `showdialog()` will block.
> 
> Could probably try something like this: https://stackoverflow.com/a/42405020/2338036.

Thanks, So I'd have to call `ShowDialog` in a different thread and then call to window via that code?

2022-10-23 23:54 UTC, RussKie commented
I think - the other way around. Here's a raw braindump of how I'd try it - spawn a new thread (e.g., a Windows Forms timer) that would search for a window and cap the lifetime of that thread too (e.g., give it like 3 seconds, else fail with timeout). If the window is found - close it - send WM_DESTROY message or ESC key...

2022-10-24 17:24 UTC, JeremyKuhne approved these changes
Thanks! Going to put this in to get manual coverage of the scenario. You can follow up with a unit test for it on another PR.

2022-10-24 17:24 UTC, merged

2022-10-26 01:14 UTC, RussKie commented
@JeremyKuhne we shouldn't be merging fixes without tests, as then it makes it harder to validate. There was nothing pressing about this regression and the test was already being developed.