Document updated AnchorCalculation in .NET 8.0
dotnet/winforms pull request #7985
Opened 2022-10-21 17:49 UTC by dreddy-work

Related to #7956.

Documenting the updated Anchor calculations in .NET 8.0 for future reference.

2022-10-21 22:07 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +Layout in general is complex and could impact every component in the WinForms  . In order to reduce the potential risk and provide backward compatibility, This changes are `quirked` under switch `Sys
I got a similar feedback in the blog draft - we don't appear to be using "quirk" publicly.

2022-10-21 22:20 UTC, dreddy-work commented on docs/AnchorLayoutChangesInNet80.md
> +Layout in general is complex and could impact every component in the WinForms  . In order to reduce the potential risk and provide backward compatibility, This changes are `quirked` under switch `Sys
how about `hidden` under flag?

2022-10-24 01:40 UTC, RussKie requested changes

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +Anchored control’s position with respect to its parent should be able to determine at the design time and would only need to be changed   if there were explicit changes in the control’s Bounds or whe
The 3rd and onwards:
```suggestion
Anchored control’s position with respect to its parent should be able to determine at the design time and would only need to be changed   if there were explicit changes in the control’s Bounds or when the control is scaled in response to a DPI changed event. Bounds changes as result of Parent’s bounds change shouldn’t alter control’s relative position in the parent’s rectangle. However, the layout engine computes the anchored control’s position every time there are changes to the control’s bounds or the control's location-related properties.

For example, the following somewhat trivial code snippet copide from an `InitializeComponent` method demonstrates the impact of the "over-eager" computations. The number of unncessary computations can increase quite dramatically for nested layouts.
```

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +The above snippet does not represent the complete set of instances where anchor computations are unnecessary and may hold invalid anchor values. It gets even more complicated when nested UserControls
I would remove this sentence.

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +We have multiple issues reported [here](https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+anchor+-label%3Atest-bug+-label%3A%22%3Aconstruction%3A+work+in+progress%22+-label%3Aapi-sugge
We seem to be repeating this idea over and over. 
```suggestion
Customer reported issues can be largely groupped as follows.
```

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +Along with above reason, If we happened to scale parent control to match with current monitors DPI and child control's anchor calculations happen out of sync with this scaling, we may see issues like
Refrain from "we", "you", etc., and use the passive voice.
```suggestion
Related to the above reason, if the parent control is caled to match the current monitor's DPI, and the control's anchor calculations happen out of sync with this scaling, controls may overlap:
```

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +- `Top` arrow indicates the Y co-ordinate of the button location with respect to parents display rectangle.
"coordinate" doesn't have hyphers.

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +The following image illustrates how we calculate anchors with respect to a control’s parent’s display rectangle. Rectangle marked in `red` is Parent’s display rectangle while the rectangle marked in
```suggestion
The following image illustrates anchors calculation with respect to a control’s parent’s display rectangle. The "red" rectangle is the parent’s display rectangle, and the "green" rectangle is the anchored control’s (button) bounds.
```

Ditto below

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +In the above picture the boundary marked in `red` is a container hosting the control (boundary marked with `green`). The control can define its anchor property to explicitly tell the layout engine ho
```suggestion
In the above picture the boundary marked in `red` is a container hosting the control (boundary marked with `green`). The control can define its anchor property to explicitly tell the layout engine how its bounds change relative to its parent’s bounds. For example:
```

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +When Control’s Anchor property is set, we compute anchors (left, top, right, bottom values) and store them in an internal struct `AnchorInfo`. We expect these anchor values to be in negative only whe
```suggestion
When the control’s `Anchor` property is set, the anchors (that is, left, top, right, bottom values) are computed and stored in an internal struct `AnchorInfo`. The only time the anchor values can be negative is when the control is placed/position outside/overlapped with the hosting controls bounds.
```

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +Unnecessary control’s anchors computation is the root cause for many [issues](https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+anchor+-label%3Atest-bug+-label%3A%22%3Aconstruction%3A+
IMO the first sentence is redundant, the previous sections set the scene and described the issue. This section is expected to describe the solution.

```suggestion
The proposal is to delay the anchors computation until the control’s and its parent’s handles are created. By that time, in the majority of scenarios, the control’s and its parent’s bounds are finalized, and the display monitor’s DPI has been applied to them.  Whilst there may still be other issues related to how anchors are calculated, but this proposal would singnificantly improve our ability to diagnose and address such issues.
```

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +- SetBounds
```suggestion
Additionally there may be cases where developers could be force-creating handle out of order, but those cases are not expected to be main stream, and such cases will have to be handled by application developer. 

The following are the events we would be using to compute anchors and replacing the current set of events mentioned in Scope section above.
- `OnCreateControl`,
- `OnParentChanged`,
- `SetBounds`.
```

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +The current anchor calculation implementation is complicated and appears to have been a result of unnecessary attempts to calculate anchors with invalid bounds. Replacing the current implementation w
The first sentense feels like we're airing dirty laundy, I suggest removing it.

2022-10-24 01:40 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +Layout in general is complex and could impact every component in the WinForms. In order to reduce the potential risk and provide backward compatibility, These changes are `hidden` under switch `Syste
"Layout ...is complex and could impact every component in the WinForms." - Yes, the layout is complex and impacts every control. What's the point? :)

```suggestion
The layout engine, in general, is quite complex, and any changes in it carry a very high risk. In order to reduce the risks and to provide backward compatibility, the new anchor calculations are put behind a feature switch `System.Windows.Forms.EnableAnchorLayoutV2`. The switch is enabled by default for Windows Forms applications targeting .NET 8.
It is possible to retain the original anchor calculations by setting the swtich to `false` in the [runtimeconfig.json](https://learn.microsoft.com/dotnet/core/runtime-config/#runtimeconfigjson).
```

2022-10-24 02:10 UTC, dreddy-work commented on docs/AnchorLayoutChangesInNet80.md
> +We have multiple [issues](https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+anchor+-label%3Atest-bug+-label%3A%22%3Aconstruction%3A+work+in+progress%22+-label%3Aapi-suggestion+-label%3
thx for pointing this. I remember using anchor label in query.

2022-10-24 02:17 UTC, dreddy-work commented on docs/AnchorLayoutChangesInNet80.md
> +Layout in general is complex and could impact every component in the WinForms. In order to reduce the potential risk and provide backward compatibility, These changes are `hidden` under switch `Syste
Setting justification for introducing switch.

2022-10-24 02:18 UTC, dreddy-work commented on docs/AnchorLayoutChangesInNet80.md
> +Layout in general is complex and could impact every component in the WinForms. In order to reduce the potential risk and provide backward compatibility, These changes are `hidden` under switch `Syste
> "Layout ...is complex and could impact every component in the WinForms." - Yes, the layout is complex and impacts every control. What's the point? :)

Setting justification for introducing switch.

2022-10-24 02:22 UTC, dreddy-work commented on docs/AnchorLayoutChangesInNet80.md
> +The above snippet does not represent the complete set of instances where anchor computations are unnecessary and may hold invalid anchor values. It gets even more complicated when nested UserControls
why?

2022-10-24 18:26 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +We have multiple [issues](https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+anchor+label%3A%22area%3A+anchor%2Fscaling%22) reported in WinForms around the anchor layout being problemat
```suggestion
We have multiple [issues](https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+anchor+label%3A%22area%3A+anchor%2Fscaling%22) reported in WinForms around the anchor layout being problematic on higher DPI scale monitors, irrespective of application DPI mode. This document outlines the changes being made in .NET 8.0 to address these issues, which is aligned with the larger goal to support all supported application DPI modes in WinForms.
```

2022-10-24 18:31 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +Anchored control's position with respect to its parent should be able to determine at the design time and would only need to be changed   if there were explicit changes in the control's Bounds or whe
```suggestion
The position of an anchored control with respect to its parent should be able to determined at design time and should only need to be changed  if there were explicit changes in the control's bounds or when the control is scaled in response to a DPI changed event. Bounds changes as result of the parent control's bounds changing shouldn’t alter a control's relative position in the parent's rectangle. However, currently the layout engine computes the anchored control's position every time there are changes to the control's bounds or the control's location-related properties.
```

2022-10-24 18:33 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +For example, the following somewhat trivial code snippet copide from an `InitializeComponent` method demonstrates the impact of the "over-eager" computations. The number of unncessary computations ca
```suggestion
For example, the following simple code snippet copied from an `InitializeComponent` method demonstrates the impact of the "over-eager" computations. The number of unnecessaryy computations can increase quite dramatically for nested layouts.
```

2022-10-24 18:34 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +// Following line trigger layout to compute anchors with default button size and without parent.
```suggestion
// The following line triggers layout to compute anchors with default button size and without parent.
```

2022-10-24 18:36 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +// Following line trigger layout again to compute anchors with button's new size and still without parent.
```suggestion
// The following line triggers layout once again to compute anchors with button's new size but still without parent.
```

2022-10-24 18:37 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +// Following line trigger layout to compute anchors with button's current size and new size for parent.
```suggestion
// The following line triggers layout to compute anchors with button's current size and new size for parent.
```

2022-10-24 18:37 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +// These size still may be changed for the DPI on the monitor depending on application's DPI mode
```suggestion
// These sizes still may be changed for the DPI on the monitor depending on application's DPI mode
```

2022-10-24 18:37 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +// Following line trigger layout to compute anchors with button's
```suggestion
// The following line triggers layout to compute anchors with button's
```

2022-10-24 18:38 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +The above snippet does not represent the complete set of instances where anchor computations are unnecessary and may hold invalid anchor values. It gets even more complicated when nested UserControls
FYI - I do like this sentence and agree that keeping it is a good idea.

2022-10-24 19:01 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +Additionally there may be cases where developers could be force-creating handle out of order, but those cases are not expected to be main stream, and such cases will have to be handled by application
```suggestion
There may be cases where developers could be force-creating handles out of order, but those cases are not expected to be mainstream, and such cases will have to be handled by application developer. 
```

2022-10-24 19:21 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +The following are the events we would be using to compute anchors and replacing the current set of events mentioned in Scope section above.
```suggestion
The following are the events we will be using to compute anchors and replacing the current set of events mentioned in Scope section above.
```

2022-10-24 19:22 UTC, merriemcgaw commented on docs/AnchorLayoutChangesInNet80.md
> +The current anchor calculation implementation is designed prior to adding high DPI support to winforms. This proposal is replacing the current implementation with the one described in Figure 1 above.
```suggestion
The current anchor calculation implementation was designed prior to adding high DPI support to WinForms. This proposal is replacing the current implementation with the one described in Figure 1 above. Following is the source snippet that computes the anchors.
```

2022-10-24 19:24 UTC, merriemcgaw requested changes
Mostly grammatical suggestions.

2022-10-25 23:47 UTC, RussKie approved these changes
Good stuff 🚀

2022-10-25 23:47 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +     }
The indentations here and in other snippets appear off.

2022-10-25 23:47 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +     }
ditto

2022-10-25 23:47 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +The position of an anchored control with respect to its parent should be able to determined at design time and should only need to be changed  if there were explicit changes in the control's bounds o
Looks like there are rogue apostrophies, may worth bulk fixing this
![image](https://user-images.githubusercontent.com/4403806/197901940-35377b8c-058f-4884-b71b-b959148ad16e.png)

2022-10-25 23:47 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +Related to the above reason, if the parent control is caled to match the current monitor's DPI, and the control's anchor calculations happen out of sync with this scaling, controls may overlap:
```suggestion
Related to the above reason, if the parent control is scaled to match the current monitor's DPI, and the control's anchor calculations happen out of sync with this scaling, controls may overlap:
```

2022-10-25 23:47 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +In the above picture the boundary marked in `red` is a container hosting the control (boundary marked with `green`). The control can define its anchor property to explicitly tell the layout engine ho
```suggestion
In the above image the boundary marked in "red" is a container hosting the control (boundary marked with "green"). The control can define its anchor property to explicitly tell the layout engine how its bounds change relative to its parent's bounds. For example: 
```

2022-10-27 02:03 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +# Anchor layout changes in .NET 8.0
Reading https://github.com/dotnet/winforms/pull/7956 I realised that the proposed location is probably not the best. The docs folder contains general purpose docs, e.g., related to how to build the repo. This doc is a "feature design" doc, and I don't think it belongs here. Especially, as other designs docs will be added it will create a mental overhead for both maitnainers and contributors.
For example, have a look at how the docs are structured in https://github.com/dotnet/runtime/tree/main/docs.

I suggest creating "docs/design" folder and moving this doc there.

Another consideration to make is that CamelCase could make it harder to read file names, as well as non-Windows OS are case sensitive when it comes to file names. With this, we adopted a "kebab-casing" for file names, and dotnet/runtime generally uses the same kebab-casing for naming docs too.

2022-10-27 02:29 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +    "System.Windows.Forms.EnableAnchorLayoutV2": false
❗  Please ensure the switch name is aligned with the actual implementation (#7956)
```suggestion
    "System.Windows.Forms.AnchorLayoutV2": false
```

2022-10-27 02:31 UTC, RussKie commented
Having the doc in a different PR from the implementation PR makes it significantly harder to review - I need to check different PRs to correlate the information.

2022-10-27 21:06 UTC, Tanya-Solyanik commented on docs/AnchorLayoutChangesInNet80.md
> +The following image illustrates anchors calculation with respect to a control's parent's display rectangle. The "red" rectangle is the parent's display rectangle, and the "green" rectangle is the anc
Would you be able to replace green/red color combination with some other colors or pen patterns?

2022-10-28 00:06 UTC, RussKie commented on docs/AnchorLayoutChangesInNet80.md
> +The following image illustrates anchors calculation with respect to a control's parent's display rectangle. The "red" rectangle is the parent's display rectangle, and the "green" rectangle is the anc
Great a11y reminder! Thank you

2022-11-01 17:44 UTC, dreddy-work commented
> Having the doc in a different PR from the implementation PR makes it significantly harder to review - I need to check different PRs to correlate the information.

tbh, I didn't want to pollute grammatical feedback with source code and linked source changes separately.

2022-11-01 17:59 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +The position of an anchored control with respect to its parent should be able to determined at design time and should only need to be changed  if there were explicit changes in the control's bounds o
```suggestion
The position of an anchored control with respect to its parent should be able to be determined at design time and should only need to be changed if there were explicit changes in the control's bounds or when the control is scaled in response to a DPI changed event. Bounds changes that happen as result of the parent control's bounds changing shouldn't alter a control's relative position in the parent's rectangle. However, currently the layout engine computes the anchored control's relative position every time there are changes to the control's bounds or the control's location-related properties.
```

2022-11-01 18:00 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +For example, the following simple code snippet copied from an `InitializeComponent` method demonstrates the impact of the "over-eager" computations. The number of unnecessaryy computations can increa
```suggestion
For example, the following simple code snippet copied from a Control's `InitializeComponent` method demonstrates the impact of the "over-eager" computations. The number of unnecessary computations can increase quite dramatically for nested layouts.
```

2022-11-01 18:00 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +// The following line triggers layout to compute anchors with default button size and without parent.
```suggestion
// The following line triggers layout to compute anchors with default button size and without a parent control.
```

2022-11-01 18:01 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +// The following line triggers layout again to compute anchors with default button size with new location but still without parent.
```suggestion
// The following line triggers layout again to compute anchors with default button size with new location but still without a parent control.
```

2022-11-01 18:01 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +// The following line triggers layout once again to compute anchors with button's new size but still without parent.
```suggestion
// The following line triggers layout once again to compute anchors with the button's new size but still without a parent.
```

2022-11-01 18:02 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +// The following line triggers layout to compute anchors with button's current size and the default size for parent.
```suggestion
// The following line triggers layout to compute anchors with the button's current size and the default size for the parent control.
```

2022-11-01 18:03 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +// The following line triggers layout to compute anchors with button's current size and new size for parent.
```suggestion
// The following line triggers layout to compute anchors with the button's current size and a new size for the parent control.
```

2022-11-01 18:04 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +// These sizes still may be changed for the DPI on the monitor depending on application's DPI mode
```suggestion
// These sizes still may be changed for the current DPI depending on the application's DPI mode.
```

2022-11-01 18:05 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +// The following line triggers layout to compute anchors with button's
```suggestion
// The following line triggers layout to compute anchors with the button's current size and a new size for the parent control.
```

2022-11-01 18:06 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +// DPI on the monitor still not applied.
```suggestion
// The current DPI is still not applied.
```

2022-11-01 18:07 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +Calculation of control's anchors with default sizes may result in negative anchors and, thus, result in invalid location for the anchored controls.
```suggestion
Calculation of control's anchors with default sizes may result in negative anchors and, thus, result in an invalid location for the anchored controls.
```

2022-11-01 18:08 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +Related to the above reason, if the parent control is scaled to match the current monitor's DPI, and the control's anchor calculations happen out of sync with this scaling, controls may overlap:
```suggestion
Related to the "Missing controls" issue above, if the parent control is scaled to match the current monitor's DPI, and the control's anchor calculations happen out of sync with this scaling, controls may overlap:
```

2022-11-01 18:09 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +- `Top` arrow indicates the Y coordinate of the button location with respect to parents display rectangle.
```suggestion
- `Top` arrow indicates the Y coordinate of the button location with respect to the parent's display rectangle.
```

2022-11-01 18:09 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +- `Right` arrow indicates the distance from right edge of parent's rectangle where button is placed.
```suggestion
- `Right` arrow indicates the distance from right edge of the parent's rectangle where the button is placed.
```

2022-11-01 18:09 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +- `Right` arrow indicates the distance from bottom edge of parent's rectangle where button is placed.
```suggestion
- `Right` arrow indicates the distance from the bottom edge of the parent's rectangle where the button is placed.
```

2022-11-01 18:26 UTC, JeremyKuhne commented on docs/design/anchor-layout-changes-in-net80.md
> +// The current DPI  still not applied.
```suggestion
// The current DPI is still not applied.
```

2022-11-02 00:41 UTC, RussKie commented on docs/design/anchor-layout-changes-in-net80.md
> +The following image illustrates anchors calculation with respect to a control's parent's display rectangle. The "red" rectangle is the parent's display rectangle, and the "green" rectangle is the anc
You have updated the image, but the text still refers to "green" and "red".

2022-11-02 00:42 UTC, RussKie commented on docs/design/anchor-layout-changes-in-net80.md
> +When the control's `Anchor` property is set, the anchors (that is, left, top, right, bottom values) are computed and stored in an internal struct `AnchorInfo`. The only time the anchor values can be
```suggestion
When the control's `Anchor` property is set, the anchors (that is, left, top, right, bottom values) are computed and stored in an internal struct `AnchorInfo`. The only time the anchor values can be negative is when the control is placed/position outside/overlapped with the hosting control's bounds.
```

2022-11-02 00:43 UTC, RussKie commented on docs/design/anchor-layout-changes-in-net80.md
> +    }
Incorrect indentation

2022-11-02 00:43 UTC, RussKie commented on docs/design/anchor-layout-changes-in-net80.md
> +   Control control = element as Control;
```suggestion
   Control? control = element as Control;
```

2022-11-02 00:45 UTC, RussKie commented on docs/design/anchor-layout-changes-in-net80.md
> +The current anchor calculation implementation was designed prior to adding high DPI support to WinForms. This proposal is replacing the current implementation with the one described in Figure 1 above
```suggestion
The original anchor calculation implementation was designed prior to adding high DPI support to WinForms. This proposal is replacing the current implementation with the one described in Figure 1 above. Following is the source snippet that computes the anchors.
```

2022-11-02 00:47 UTC, RussKie commented on docs/design/anchor-layout-changes-in-net80.md
> +The current anchor calculation implementation was designed prior to adding high DPI support to WinForms. This proposal is replacing the current implementation with the one described in Figure 1 above
I don't think the second sentence is correct - we're not replacing the original implementation; we're providing an alternative mechanism. And the original implementation can't be re-enabled with the feature switch.

2022-11-02 00:47 UTC, RussKie commented on docs/design/anchor-layout-changes-in-net80.md
> + }
Incorrect indentation

2022-11-02 00:48 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
> +        // https://github.com/microsoft/winforms/blob/tree/main/docs/design/anchor-layout-changes-in-net80.md
The link is incorrect "https://github.com/microsoft/winforms"

2022-11-02 03:26 UTC, dreddy-work commented on docs/design/anchor-layout-changes-in-net80.md
> +The current anchor calculation implementation was designed prior to adding high DPI support to WinForms. This proposal is replacing the current implementation with the one described in Figure 1 above
I did not get it. we are replacing given its default in .NET 8.0 and beyond. Developer can go back to original with switch.

2022-11-02 03:37 UTC, dreddy-work commented on docs/design/anchor-layout-changes-in-net80.md
> +    }
Now i am copying from VS. Hopefully indentation is right. Are you using any tools to visually identify indentation here?

2022-11-02 05:03 UTC, RussKie commented on docs/design/anchor-layout-changes-in-net80.md
> +
I would expect this section to explain the proposed solution, yet I'm not seeing it. The first sentence talks about the edge cases. Then the three events are mentioned followed by a code snippet. Followed by another sentence alluding to the past implementation and some reference to some "figure 1". And then some more code...
Where's the proposal?

I can see some bits explaining the proposal above, but they are kind of disjoined. I think the document needs to be restructured in a way that puts all proposal bits together under one section.

2022-11-02 07:04 UTC, dreddy-work commented on docs/design/anchor-layout-changes-in-net80.md
> +
Restructures. Take a look.

2022-11-02 07:11 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
> +        ///  https://github.com/microsoft/dotnet/blob/tree/main/docs/design/anchor-layout-changes-in-net80.md for more details.
Boo :)
```suggestion
        ///  https://github.com/dotnet/winforms/blob/tree/main/docs/design/anchor-layout-changes-in-net80.md for more details.
```

2022-11-02 07:11 UTC, RussKie approved these changes

2022-11-02 15:45 UTC, merged