Add Test for FolderBrowserDialog
dotnet/winforms pull request #8021
Opened 2022-10-24 22:06 UTC by elachlan

Fixes #79

2022-10-24 23:28 UTC, RussKie requested changes
I think you're on the right track, though a little more work is needed.

2022-10-24 23:28 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +            FolderBrowserDialog form = new()
```suggestion
            using FolderBrowserDialog form = new()
```

2022-10-24 23:28 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +            Timer timer = new();
```suggestion
            using Timer timer = new();
```

2022-10-24 23:28 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +            timer.Interval = 3000;
This makes the timer fires every three seconds. We can probably reduce this value to 1,000.
Also we need to introduce a timeout mechanism - i.e., if the dialog remains open after, say, three seconds - fail the test.

2022-10-24 23:28 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +        }
Psuedocode
```suggestion
            Timer timer = new();
            timer.Interval = 1_000;
            
            int counter = 0;
            timer.Tick += (s, e) =>
            {
                counter++;                
                if (counter > 2)
                    throw new TimeoutException("Failed to close the dialog");
                    
                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
            };

            timer.Start();
            form.ShowDialog();
            
            // The dialog has opened and closed successfully
            Assert.True(true);
        }
```

2022-10-24 23:44 UTC, elachlan commented
Sorry for the force push, I rebased to main.

2022-10-24 23:53 UTC, RussKie commented
No worries at all, the diff is simple :)

2022-10-24 23:54 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                AutoUpgradeEnabled = false,
Also we'd want to test both cases, right? Suggest turning the test into a theory.

2022-10-24 23:55 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
Have you checked the timeout approach is working? E.g., comment out line:36 and see if the test'd fail.

2022-10-25 00:02 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
It works! 

I get an exception here though, which I am unsure if its a bug:
https://github.com/dotnet/winforms/blob/7ba5f72a2698b3b2476a016f48f7066af8158c89/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ThemingScope.cs#L55

```
System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'
System.Windows.Forms.Primitives.dll!System.Windows.Forms.ThemingScope.Deactivate(nint userCookie) Line 55	C#
System.Windows.Forms.dll!System.Windows.Forms.CommonDialog.ShowDialog(System.Windows.Forms.IWin32Window owner) Line 236	C#
System.Windows.Forms.dll!System.Windows.Forms.CommonDialog.ShowDialog() Line 158	C#
System.Windows.Forms.UI.IntegrationTests.dll!System.Windows.Forms.UITests.FolderBrowserDialogTests.FolderBrowserDialog_ShowDialog() Line 40	C#
[External Code]	
[Resuming Async Method]	
[External Code]	
System.Windows.Forms.dll!System.Windows.Forms.Control.InvokeMarshaledCallbackDo(System.Windows.Forms.Control.ThreadMethodEntry tme) Line 6652	C#
System.Windows.Forms.dll!System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(object obj) Line 6600	C#
[External Code]	
System.Windows.Forms.dll!System.Windows.Forms.Control.InvokeMarshaledCallback(System.Windows.Forms.Control.ThreadMethodEntry tme) Line 6577	C#
System.Windows.Forms.dll!System.Windows.Forms.Control.InvokeMarshaledCallbacks() Line 6687	C#
System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m) Line 13438	C#
System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m) Line 65	C#
System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m) Line 114	C#
System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.Callback(Windows.Win32.Foundation.HWND hWnd, Interop.User32.WM msg, Windows.Win32.Foundation.WPARAM wparam, Windows.Win32.Foundation.LPARAM lparam) Line 376	C#
[External Code]	
System.Windows.Forms.dll!System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(nuint dwComponentID, Interop.Mso.msoloop uReason, void* pvLoopData) Line 340	C#
System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Interop.Mso.msoloop reason, System.Windows.Forms.ApplicationContext context) Line 1116	C#
System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Interop.Mso.msoloop reason, System.Windows.Forms.ApplicationContext context) Line 980	C#
System.Windows.Forms.dll!System.Windows.Forms.Application.DoEvents() Line 807	C#
[External Code]
```

2022-10-25 01:13 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
Do you think you could run your test against release/7.0 branch? This way we could establish a baseline whether this is something we're doing wrong in the test, or whether it's an indication of a regression of some kind in the main branch.
Thank you

2022-10-25 02:59 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
The failure is when I remove the "escape key press". I will test this scenario on 7.0 branch.

2022-10-25 03:28 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
7.0 Branch also throws this error when we comment out the line:
`new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE)`

So I think its good to go. Although I am unsure on the test failures here.

2022-10-26 01:27 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
@RussKie are you happy with this?

2022-10-26 01:42 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
I experimented with it, and I don't get the same error. I made few discoveries though.
1. We need to stop the timer upon the timeout
1. If we fail by timeout - we lock the test process with a popup dialog, which is quite bad:
![image](https://user-images.githubusercontent.com/4403806/197910768-fe2a143d-04f1-4e24-ab88-cc7e6d3251e4.png)
2. We don't need the send any keys, and can terminate the application instead. Here's the demo code:
```cs
            using FolderBrowserDialog dialog = new()
            {
                AutoUpgradeEnabled = autoUpgradeEnabled,
            };

            using Timer timer = new();
            timer.Interval = 1_000;
            int counter = 0;

            bool dialogDismissed = true;

            timer.Tick += (s, e) =>
            {
                counter++;
                TestOutputHelper.WriteLine($"Counter {counter}");

                if (counter > 2)
                {
                    dialogDismissed = false;

                    TestOutputHelper.WriteLine($"Timeout");

                    timer.Stop();
                    TestOutputHelper.WriteLine($"timer.Stop");

                    Application.Exit();
                    TestOutputHelper.WriteLine($"Application.Exit");
                }

                //new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
            };

            timer.Start();
            dialog.ShowDialog();

            // The dialog has opened and closed successfully
            TestOutputHelper.WriteLine($"End");
            Assert.True(dialogDismissed);
        }
```

But now it looks like we don't need the input simulator as we can dismiss the dialog ourselves (though in a brutal kind of way).

I have locally undone the fix and, having played with it, I think we can reduce the test down to the following:
```cs
            using FolderBrowserDialog dialog = new()
            {
                AutoUpgradeEnabled = autoUpgradeEnabled,
            };

            bool dialogDismissed = false;

            using Timer timer = new();
            timer.Interval = 1_000;

            timer.Tick += (s, e) =>
            {
                dialogDismissed = true;
                timer.Stop();

                // Forcefully close the dialog
                Application.Exit();
            };

            timer.Start();
            dialog.ShowDialog();

            // The dialog has opened and closed successfully
            Assert.True(dialogDismissed);
```

If the dialog has opned - we can force-close it. If it failed to open - it'd have brought down the test process.

2022-10-26 01:50 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
would the code ever hit this?
```csharp
// The dialog has opened and closed successfully
Assert.True(dialogDismissed);
```

Doesn't application.exit close the whole app and not just the dialog? Or are the tests treated as individual apps?

2022-10-26 02:48 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
With this code I get the following exception when running with autoUpgradeEnabled=true
```
System.Runtime.InteropServices.COMException: 'Catastrophic failure (0x8000FFFF (E_UNEXPECTED))'
System.Windows.Forms.Primitives.dll!Windows.Win32.Foundation.HRESULT.ThrowOnFailure(nint errorInfo) Line 63	C#
System.Windows.Forms.dll!System.Windows.Forms.FolderBrowserDialog.GetResult(Windows.Win32.UI.Shell.IFileOpenDialog* dialog) Line 383	C#
System.Windows.Forms.dll!System.Windows.Forms.FolderBrowserDialog.TryRunDialogVista(Windows.Win32.Foundation.HWND owner, out bool returnValue) Line 299	C#
System.Windows.Forms.dll!System.Windows.Forms.FolderBrowserDialog.RunDialog(nint hWndOwner) Line 261	C#
System.Windows.Forms.dll!System.Windows.Forms.CommonDialog.ShowDialog(System.Windows.Forms.IWin32Window owner) Line 221	C#
System.Windows.Forms.dll!System.Windows.Forms.CommonDialog.ShowDialog() Line 158	C#
System.Windows.Forms.UI.IntegrationTests.dll!System.Windows.Forms.UITests.FolderBrowserDialogTests.FolderBrowserDialog_ShowDialog(bool autoUpgradeEnabled) Line 42	C#
```

2022-10-26 02:58 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
I got this too in the trimmed down version. I didn't have time to investigate it though... The question whether this work on .NET 7 (i.e., pror to cswin32 work) or not.
Do you get the same with the input simulator? If not, we can probably retain that iteration.

2022-10-26 03:40 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
.NET7 has the same error. Might be best to use the input simulator to avoid the error.

2022-10-26 03:53 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
OK. I think this latest push is the best of both worlds. I imagine there are some minor improvements there.

2022-10-26 06:11 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                new InputSimulator().Keyboard.KeyPress(VirtualKeyCode.ESCAPE);
> would the code ever hit this?
> 
> ```cs
> // The dialog has opened and closed successfully
> Assert.True(dialogDismissed);
> ```
> 
> Doesn't application.exit close the whole app and not just the dialog? Or are the tests treated as individual apps?

Yes, that code is hit - if you run my sample you'd see the debug output.

2022-10-26 06:12 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                    timer.Stop();
If we end up here - we need to fail the test. Right now, I don't think it's happening, is it?

2022-10-26 06:17 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                    timer.Stop();
I think I need to add back in `dialogDismissed`. I'll test and adjust accordingly.

2022-10-26 23:17 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                    Assert.Fail("Failed to close the dialog");
My local tests didn't indicate this will  be hit or result in a failed test.

2022-10-26 23:38 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                    Assert.Fail("Failed to close the dialog");
It works if I use only `Assert.Fail()`. 

I was looking into the exception caused by `ThemingScope.Deactivate(userCookie);` in `CommonDialog.cs`. The call to `PInvoke.DeactivateActCtx` causes the exception only if `Application.Exit()` or `Assert.Fail()` is called from the timer.tick event. I think this is threading related but I am not 100% sure.

https://stackoverflow.com/questions/26514954/registration-free-com-interop-deactivating-activation-context-in-finalizer-thro

2022-10-27 00:02 UTC, elachlan commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                    Assert.Fail("Failed to close the dialog");
With this latest code, the vista version throws an exception because of an `E_UNEXPECTED` HRESULT returned from GetResult in this call chain. `dialog->GetResult(item).ThrowOnFailure();`.

2022-10-27 01:50 UTC, RussKie reviewed
I think we're almost there :)

2022-10-27 01:50 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> +                    failedClose=true;
```suggestion
                    failedClose = true;
```

2022-10-27 01:51 UTC, RussKie approved these changes

2022-10-27 02:48 UTC, elachlan commented
Test is failing. Maybe its flaky? :(

2022-10-27 02:54 UTC, RussKie commented
/azp run

2022-10-27 03:31 UTC, RussKie commented
![image](https://user-images.githubusercontent.com/4403806/198184789-bdcd1027-ff89-461b-9b31-8c5f522156c4.png)

2022-10-27 03:32 UTC, RussKie commented
/azp run

2022-10-31 02:23 UTC, RussKie commented
/azp run

2022-10-31 02:56 UTC, elachlan commented
Are the UI Integration tests run concurrently or do they run serially?

2022-11-01 07:55 UTC, RussKie commented
> Are the UI Integration tests run concurrently or do they run serially?

All tests in UI Integration project should be running serially:
https://github.com/dotnet/winforms/blob/8f1be5d8453763501aea20070bb6cabf97a49b34/eng/pipelines/build.yml#L108

2022-11-01 23:33 UTC, RussKie commented
/azp run

2022-11-01 23:36 UTC, RussKie submitted a review, later dismissed

2022-11-02 03:49 UTC, elachlan commented
No other test uses the `InputSimulator` directly like this. It wraps everything to make sure the Form/Control are focused and the input is done on the UI thread.

2022-11-04 03:06 UTC, elachlan commented
@RussKie I think you did it! Can you please rerun the pipeline?

2022-11-04 05:18 UTC, RussKie commented
Indeed :)

2022-11-04 05:18 UTC, RussKie commented
/azp run

2022-11-04 06:07 UTC, RussKie commented
/azp run

2022-11-04 06:07 UTC, RussKie commented
I'm going to run this few times to see if there are any flakiness to it.

2022-11-04 06:53 UTC, RussKie approved these changes

2022-11-04 06:53 UTC, merged

2022-11-04 06:53 UTC, RussKie commented
Thank you!