Convert AxHost IPersistX Interface to Cswin32
dotnet/winforms pull request #8052
Opened 2022-10-27 16:08 UTC by lonitra

- Converted rest of AxHost interfaces (IPersistX) to cswin32 version, which prompted for the conversion of other relating interfaces: `IStream`,`IStorage`,`IPropertyBag`,`IPicture`,`IPictureDisp`
- Added helpers to ComHelpers.cs to get IDispatch property and get scoped pointers
- Convert IStream vtable to the new pattern
- Remove PictureWrapper
- Create real mocks in Com2PictureConverterTests since IPicture can no longer be mocked using moq

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8052)

2022-10-27 17:54 UTC, JeremyKuhne requested changes
Added some comments. I'll connect with you to see if we can remove the PictureWrapper.

2022-10-27 17:54 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.GPStream.cs
> +            /// Returns <see cref="HRESULT.STG_E_INVALIDFUNCTION"/> as a documented way to say we don't support locking
nit: I'd just do a regular comment here, cref'ing STG_E_INVALIDFUNCTION doesn't add much. I'm also not clear on what the rules are for XML comments- I would have thought that having an enclosing tag would have been required?

2022-10-27 17:54 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/ComHelpers.cs
> +        public static HRESULT InvokePictureDisp(
This should be generic and take `IDispatch*`. I'd do something like this:

`public static HRESULT GetDispatchProperty(IDispatch* dispatch, uint dispid, out VARIANT result)`

2022-10-28 00:09 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.GPStream.cs
> +                ((Com.ISequentialStream.Interface)this).Read(pv, cb, pcbRead);
It's customary to have `=>` on the new line
```suggestion
            HRESULT Com.IStream.Interface.Read(void* pv, uint cb, uint* pcbRead)
                => ((Com.ISequentialStream.Interface)this).Read(pv, cb, pcbRead);
```

2022-10-28 00:09 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.GPStream.cs
> +            HRESULT Com.IStream.Interface.Write(void* pv, uint cb, uint* pcbWritten) =>
ditto

2022-10-28 00:58 UTC, JeremyKuhne approved these changes
🔥

2022-10-28 01:18 UTC, JeremyKuhne approved these changes

2022-10-28 01:56 UTC, merged