Fix a SaveTabSelection method
dotnet/winforms pull request #8055
Opened 2022-10-28 05:24 UTC by mikhailovalex

Hi,

My name is Alex M. I am a software developer at DevExpress WinForms Team.

I created a pull request that fixes the following issue. It's related only for .NET 7 after this PR - [Combine PropertyGrid tab information.](https://github.com/dotnet/winforms/pull/6108).

### Fixes
"Invalid cast error" in the TryGetSavedTabSelection method. PropertyGrid saves information about selectedTab in a [SaveTabSelection ](https://github.com/dotnet/winforms/blob/7ef35233ec820db47dce981b9ba403850b98d7ec/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs#L3628) method. After change the _selectedTab field from int to a TabInfo record we should use a _tabs.IndexOf(_selectedTab) method. In a [TryGetSavedTabSelection ](https://github.com/dotnet/winforms/blob/7ef35233ec820db47dce981b9ba403850b98d7ec/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs#L3646) method we restore information and we expect int value in a _designerSelections Hashtable. 

## Proposed changes

-Changed the type of value added to the _designerSelections dictionary in the SaveTabSelection method.

-Before
TabInfo 

-After
int

## Customer Impact

The error occurs when an end-user modify somthing in Visual Studio designer.

## Regression?

Yes

## Risk

Medium

## Test methodology 

* Manually

## Test environment(s) 

VisualStudio 2022 Preview 4
.NET 7 RC2

2022-10-28 07:57 UTC, gpetrou commented
Perhaps also change `_designerSelections` from `Hashtable` to `Dictionary<int, int>`?

2022-10-31 02:40 UTC, RussKie requested changes
Thank you for the fix, but it needs a little more work.

In addition to https://github.com/dotnet/winforms/pull/8055#issuecomment-1294635501, to me it looks like the naming may have been a significant contributor to the underlying issue. I propose to do the following:
* rename `SaveTabSelection()` to `SaveSelectedTabIndex()`
* rename `TryGetSavedTabSelection()` to `TryGetSavedTabIndex()`
* rename the argument `private bool TryGetSavedTabIndex(out int selectedTab)` to `private bool TryGetSavedTabIndex(out int selectedTabIndex)`

We'll also need to add few regression tests. The tests would go into [`PropertyGridTests`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs). The non-public API (e.g., `SaveSelectedTabIndex()` API) should be exposed through [`PropertyGridTestAccessor`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/TestAccessors.PropertyGridTestAccessor.cs).
You can see an example of how the test accessor is used here:
https://github.com/dotnet/winforms/blob/367fa09ab6e3cdab51e7c70b1b8de02ec349aefb/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridViewTests.cs#L14-L15

2022-10-31 02:44 UTC, RussKie commented
OT: instead of tracking merges I recommend doing `git rebase` - the latter avoids irrelevant changes and makes the review experience outside GitHub significantly easier.
![image](https://user-images.githubusercontent.com/4403806/198920240-1035476e-6b1e-469a-a577-3d857af3a789.png)

2022-10-31 06:43 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=8055) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=8055) before we can accept your contribution.<br/><br/>:x: mikhailovalex [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=8055)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=8055) it.</sub>

2022-10-31 06:58 UTC, mikhailovalex commented
Thanks for the review.
I hope I did everything right.

2022-11-01 07:34 UTC, RussKie reviewed
Looks good with few comments.

Would you mind adding few more test cases for these paths?
![image](https://user-images.githubusercontent.com/4403806/199182320-76583082-57a1-4729-a777-0c9e7de9fdf7.png)

Thank you.

2022-11-01 07:34 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
> +            Assert.Equal(savedTabIndex, selectedTabIndex);
Grouping helps with readability
```suggestion
            using PropertyGrid propertyGrid = new();
            propertyGrid.Site = mockSite.Object;
            Assert.NotNull(propertyGrid.ActiveDesigner);

            propertyGrid.TestAccessor().Dynamic.SaveSelectedTabIndex();
            Assert.NotNull(propertyGrid.TestAccessor().Dynamic._designerSelections);

            Dictionary<int,int> _designerSelections = propertyGrid.TestAccessor().Dynamic._designerSelections;
            Assert.True(_designerSelections.ContainsKey(propertyGrid.ActiveDesigner.GetHashCode()));

            int savedTabIndex = _designerSelections[propertyGrid.ActiveDesigner.GetHashCode()];
            int selectedTabIndex = -1;
            Assert.NotEqual(savedTabIndex, selectedTabIndex);

            bool isInvokeMethodSuccessful = propertyGrid.TestAccessor().Dynamic.TryGetSavedTabIndex(out selectedTabIndex);
            Assert.True(isInvokeMethodSuccessful);
            Assert.Equal(savedTabIndex, selectedTabIndex);
```

2022-11-01 07:34 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
> +            Assert.Equal(savedTabIndex, selectedTabIndex);
It would be better to enhance [`PropertyGridTestAccessor`](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/TestAccessors.PropertyGridTestAccessor.cs), so that in the test we deal with "typed" API. But even if we don't do this, let's put `propertyGrid.TestAccessor().Dynamic` into a local variable, and reuse it.

2022-11-01 07:45 UTC, RussKie commented
> It's related only for .NET 7 after this PR - [Combine PropertyGrid tab information.](https://github.com/dotnet/winforms/pull/6108).

@JeremyKuhne it looks like #6108 has introduced a regression. This breaking change must also be documented, and likely serviced.
/cc: @merriemcgaw FYI

2022-11-01 23:43 UTC, RussKie approved these changes

2022-11-02 00:01 UTC, Tanya-Solyanik approved these changes

2022-11-02 00:03 UTC, merriemcgaw commented
/backport release/7.0

2022-11-02 00:05 UTC, RussKie commented
/backport to release/7.0

2022-11-02 18:56 UTC, merged