Enable nullability in Help
dotnet/winforms pull request #8067
Opened 2022-10-29 05:42 UTC by gpetrou

## Proposed changes

- Enable nullability in Help.

2022-10-31 00:12 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Interop/Hhctrl/Interop.HtmlHelpW.cs
> +        public static extern int HtmlHelpW(IntPtr hwndCaller, string? pszFile, HH uCommand, IntPtr dwData);
Raised an issue for win32metadata so we can use cswin32 for these PInvokes.
https://github.com/microsoft/win32metadata/issues/1345

I suspect the change would mean the `pszFile` would change from a `string` to `LPCWSTR` (struct) and therefore no longer be nullable.

2022-10-31 01:31 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Hhctrl/Interop.HtmlHelpW.cs
> +        public static extern int HtmlHelpW(IntPtr hwndCaller, string? pszFile, HH uCommand, IntPtr dwData);
Thank you @elachlan. How would it reconcile with the docs?
![image](https://user-images.githubusercontent.com/4403806/198913652-469e6a3d-5203-4052-ad4a-dee770a44eeb.png)

2022-10-31 01:40 UTC, RussKie requested changes

2022-10-31 01:40 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
> +                            htmlParam = int.Parse(param!, CultureInfo.InvariantCulture);
I can't see any reason to do this. If we know `param` is null - we can just return `HH.HELP_CONTEXT`. Exceptions are expensive, and if we should avoid them if we can.

2022-10-31 01:40 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
> +            Debug.WriteLineIf(WindowsFormsHelpTrace!.TraceVerbose, "Help:: ShowHTML10Help:: " + url + ", " + command.ToString("G") + ", " + param);
Since we're touching these, could you please use string interpolation syntax?

2022-10-31 01:40 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
>  // The .NET Foundation licenses this file to you under the MIT license.
Could you please reformat the document too? looks like there are few styling imperfections.
![image](https://user-images.githubusercontent.com/4403806/198914330-fd208c00-c2f3-465f-9bad-d72e9476c67e.png)

2022-10-31 02:24 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Interop/Hhctrl/Interop.HtmlHelpW.cs
> +        public static extern int HtmlHelpW(IntPtr hwndCaller, string? pszFile, HH uCommand, IntPtr dwData);
Yes, I saw that. I am not sure how C# will work with LPCWSTR. I think you will just be able to pass null without issues.

2022-10-31 21:56 UTC, dreddy-work approved these changes

2022-11-01 05:15 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
> +                        if (int.TryParse(param, out int htmlParamAsInt))
Nice!

2022-11-01 05:15 UTC, RussKie approved these changes

2022-11-01 05:15 UTC, merged

2022-11-01 05:16 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Interop/Hhctrl/Interop.HtmlHelpW.cs
> +        public static extern int HtmlHelpW(IntPtr hwndCaller, string? pszFile, HH uCommand, IntPtr dwData);
We can iterate on this later when CsWin32 is ready for this.