CA1838 Avoid 'StringBuilder' parameters for P/Invokes
dotnet/winforms pull request #8113
Opened 2022-11-04 01:20 UTC by elachlan

Fixes #3983

Analyzer:
- https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1838

Work based on:
- https://github.com/dotnet/msbuild/pull/7186
- #4751

TODO:
https://github.com/dotnet/winforms/blob/15ab89b1017e0da7e7448118b3d0a80632c9f146/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeMethods.vb#L30-L33

Related: #7887

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8113)

2022-11-04 01:27 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_PATH.cs
> +                    bool isMaxPathRestricted = IsLongPathsEnabledRegistry();
In MSBuild there is an escape hatch for long paths. I am unsure if winforms needs an escape hatch here.
https://github.com/dotnet/msbuild/blob/207f71329700f2b178a832bb1f0930c107fda0e9/src/Framework/NativeMethods.cs#L600-L611

2022-11-04 02:02 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            if (MemoryExtensions.Equals(className, buffer.SliceAtFirstNull(), StringComparison.Ordinal))
The idea here was to avoid a string allocation. But I am unsure if this is correct.

2022-11-04 02:03 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +        private static unsafe string GetClassName(HWND hWnd)
should this move to the PInvoke namespace?

2022-11-04 02:23 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            if (MemoryExtensions.Equals(className, buffer.SliceAtFirstNull(), StringComparison.Ordinal))
In the tests we aren't as strict about memory allocations (though we shouldn't go bonkers either :))

2022-11-04 02:29 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_CLASS_NAME.cs
> +        public const int MAX_CLASS_NAME = 256;
How is this used?

2022-11-04 02:29 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            if (MemoryExtensions.Equals(className, buffer.SliceAtFirstNull(), StringComparison.Ordinal))
Oh, this is actually the shippable code... 👀

2022-11-04 02:29 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            if (MemoryExtensions.Equals(className, buffer.SliceAtFirstNull(), StringComparison.Ordinal))
Oh, this is actually the shippable code... 👀

2022-11-04 02:52 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_CLASS_NAME.cs
> +        public const int MAX_CLASS_NAME = 256;
RichTextBoxTests.cs `GetClassName`

2022-11-04 02:54 UTC, elachlan commented
I don't think the vb.net PInvokes are able to avoid stringbuilder. We would have to pull it into the PInvoke class and then have a wrapper that returns the needed information.

2022-11-04 05:21 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_CLASS_NAME.cs
> +        public const int MAX_CLASS_NAME = 256;
If it's test-specific, then it should reside in the test part of the solution.

2022-11-04 05:23 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_PATH.cs
> +                    bool isMaxPathRestricted = IsLongPathsEnabledRegistry();
Tbh, I'm not currently convinced we need this... I'll leave it to @JeremyKuhne and @lonitra to decide though.

2022-11-04 05:25 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_CLASS_NAME.cs
> +        public const int MAX_CLASS_NAME = 256;
Do we want to centralise the PInvokes though? It would reduce the chance of code duplication.

2022-11-04 17:19 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            if (MemoryExtensions.Equals(className, buffer.SliceAtFirstNull(), StringComparison.Ordinal))
This LGTM! Just a nit that this can be rewritten as 
`className.Equals(buffer.SliceAtFirstNull(), StringComparison.Ordinal)`

2022-11-04 17:19 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_PATH.cs
> +                    bool isMaxPathRestricted = IsLongPathsEnabledRegistry();
I also don't see that it is needed, but waiting for Jeremy's thoughts.

2022-11-04 22:16 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_PATH.cs
> +        private static bool IsLongPathsEnabledRegistry()
This has nothing to do with whether or not long paths can be used in general, this is whether or not you can opt-in to using long paths without using `\\?\` as a path prefix. You also have to actually have a proper manifest for the current executable. The only way to really know is to call an undocumented API. In any case, there is no need to do this.

2022-11-04 22:21 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_PATH.cs
> +        internal static int MaxPath
This is not going to be correct and you shouldn't try to implement it. Fundamentally the maximum path is the size of UNICODE_STRING, which is a ushort of bytes in length. Even knowing that isn't sufficient as the path gets manipulated as it passes through the system to whichever driver is involved. You can think of the path max as being roughly 32K characters, but that is just the ballpark. It will never be over, however.

2022-11-04 22:30 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            for (int bufferSize = MAX_PATH; bufferSize <= MaxPath; bufferSize *= 2)
I wouldn't double as it is a bit too aggressive for those that would have more common long paths. You also won't be correct here as you'll never actually include the longest paths by doubling this way (presuming you had MaxPath defined correctly, but you don't). If performance was super critical here you could:

1. Attempt a stackalloc buffer of MAX_PATH
2. Fall back to a loop of ArrayPool buffers, starting at 4096 characters and adding 4096 every time until you pass short.MaxValue.

But you're probably just fine doing `4096 * i` buffer rents from the start here. We don't call this that often and the 4K buffer will get reused for sure. I'd actually recommend it as it is simpler, logic-wise.

2022-11-04 22:31 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                try
You don't need a try block here. You shouldn't be throwing out of here. Generally speaking, if exceptions are expected to be rare it is better to drop an ArrayPool buffer than take the hit of the try block.

2022-11-04 22:37 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                    if (pathLength != 0 && !isBufferTooSmall && bufferSize <= int.MaxValue)
`bufferSize <= int.MaxValue` is _always_ true.

2022-11-04 22:39 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                    if (pathLength != 0 && !isBufferTooSmall && bufferSize <= int.MaxValue)
The right check is `(pathLength > 0 && (pathLength < buffer.Length || Marshal.GetLastWin32Error() != INSUFFICENT_BUFFER))`

2022-11-04 22:40 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                    {
You'll keep increasing the size of the buffer in the error case (returns a length of 0).

2022-11-04 22:41 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                        pathLength = GetModuleFileName(hModule, lpFilename, (uint)bufferSize);
Use `buffer.Length`, never an intermediary value.

2022-11-04 22:44 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            const int INSUFFICIENT_BUFFER = 0x007A;
This is a standard error so we should be pulling it from CSWin32. `WIN32_ERROR.ERROR_INSUFFICENT_BUFFER`

2022-11-04 22:46 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +                s_executablePath ??= Path.GetFullPath(PInvoke.GetModuleFileNameLongPath(default));
Calling `GetFullPath` will do nothing here as the API claims it always returns a fully qualified path.

2022-11-04 22:49 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            Span<char> buf = stackalloc char[PInvoke.MAX_CLASS_NAME];
Don't abbreviate here- use `buffer`

2022-11-04 22:51 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +                _ = PInvoke.GetClassName(hWnd, lpClassName, buf.Length);
This API is clearly documented to return the count of characters. We should capture that and slice at that length, not scan for the null.

2022-11-04 22:52 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +            Assert.Contains("RICHEDIT50W", GetClassName(control.HWND), StringComparison.InvariantCultureIgnoreCase);
The comparison here should be ordinal (best) or ordinal ignore case. Class names don't have a culture, they're an ID.

2022-11-04 22:54 UTC, JeremyKuhne requested changes
Left a number of comments. Biggest thing is not to try and guess what the exact max allowable path will be (outside of constraining to not go over 32K characters for sanity).

2022-11-04 23:11 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +        private static unsafe string GetClassName(HWND hWnd)
I didn't move this because its a wrapper and isn't used in the other calls. I am happy to still move it. The other uses avoid string allocations.

2022-11-04 23:12 UTC, elachlan commented
Any advice on the VB PInvokes? Should I write a wrapper in C# and call it from the VB code? I think that is most efficient to avoid a string builder.
https://github.com/dotnet/winforms/blob/15ab89b1017e0da7e7448118b3d0a80632c9f146/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeMethods.vb#L30-L33

2022-11-04 23:15 UTC, elachlan commented
@AArnott Would you want GetModuleFileNameLongPath in CsWin32 as a friendly wrapper/overloads?

2022-11-05 18:25 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                if (pathLength > 0 && (pathLength < buffer.Length || (WIN32_ERROR)Marshal.GetLastWin32Error() == WIN32_ERROR.ERROR_INSUFFICIENT_BUFFER))
You're still not exiting out in the error case ('0')

2022-11-05 18:27 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                ArrayPool<char>.Shared.Return(buffer);
You need to be returning this to the pool when you succeed. It is ok to not return them in super rare cases, but you defeat the purpose of using the pool if you don't normally return them.

2022-11-05 18:31 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                Debug.Assert(bufferSize <= int.MaxValue / 2, "Buffer size approaching int.MaxValue");
This assert isn't useful, I'd just remove it. Additionally, in its current state it will always be true. If we thought large paths were interesting to know about in our debug builds we could put a `Debug.WriteLine` in, but I don't think that it actually adds any real value.

2022-11-05 18:37 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_CLASS_NAME.cs
> +        public const int MAX_CLASS_NAME = 256;
I don't think this is a real Windows define. Presuming it isn't we should use normal casing `MaxClassName` and document where this number comes from. The simplest way is probably to `<see cref>` the `WNDCLASS.lpszClassName` definition as it should have the docs on it. (Or WNDCLASSEX, I'm not remembering off the top of my head what we actually use.)

2022-11-05 18:40 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +                s_executablePath ??= Path.GetFullPath(PInvoke.GetModuleFileNameLongPath(HINSTANCE.Null));
nit: combine with the next line and make this `ExecutablePath => s_...`  Also, no need for `Path.GetFullPath` as I mentioned before.

2022-11-05 18:49 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            // class name #32770
This comment isn't useful. What would be is specifying that this is the class name for dialogs and linking to https://learn.microsoft.com/windows/win32/winmsg/about-window-classes#system-classes.

2022-11-05 18:50 UTC, JeremyKuhne requested changes
Added a few more comments

2022-11-05 18:52 UTC, JeremyKuhne commented
> Any advice on the VB PInvokes? Should I write a wrapper in C# and call it from the VB code? I think that is most efficient to avoid a string builder.

I would presume it is better to keep this in VB. @KlausLoeffelmann do you have any opinions here?

2022-11-05 20:28 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MAX_CLASS_NAME.cs
> +        public const int MAX_CLASS_NAME = 256;
https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-wndclassexw

> The maximum length for lpszClassName is 256. If lpszClassName is greater than the maximum length, the [RegisterClassEx](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-registerclassexa) function will fail.

I was unable to find a related constant in the metadata project in `winuser.h`.

2022-11-06 04:15 UTC, AArnott commented
> Would you want GetModuleFileNameLongPath in CsWin32 as a friendly wrapper/overloads?

@elachlan not at this point. The implementation has to be opinionated because there are tradeoffs to be made, so unless there was evidence of some consensus around which implementation was best 90% of the time, I'd say it's better for folks to write their own (as you do here).

2022-11-06 04:16 UTC, AArnott commented
> I don't think the vb.net PInvokes are able to avoid stringbuilder. We would have to pull it into the PInvoke class and then have a wrapper that returns the needed information.

VB.NET should be able to invoke IntPtr methods after allocating memory using the `Marshal` class, then again use that class to convert the data into a `String`. It certainly makes things harder to not have pointers, ironically.

2022-11-06 04:16 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                buffer = ArrayPool<char>.Shared.Rent(bufferSize);
Array pools can return longer arrays than requested. If for example it gave you 16KB instead of 4KB, you may as well skip the 8, 12, and 16KB attempts that you would otherwise try. 
But that makes the logic more complex, and unless it's thoroughly tested, that could lead to bugs.
As an alternative, considering a reasonable max size like 32KB, you could use stackalloc for the whole 32KB and lose the arraypool and loop altogether. Super simple and better performing.

2022-11-06 09:55 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                buffer = ArrayPool<char>.Shared.Rent(bufferSize);
In dotnet runtime they try to keep stackalocs to 1024 or less. Is there a general rule to avoid an overflow?

2022-11-06 21:36 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                buffer = ArrayPool<char>.Shared.Rent(bufferSize);
I managed to find where I remembered reading it.
https://github.com/dotnet/msbuild/pull/7186#discussion_r796202803

I think its more, is the  stackalloc likely to push the stack over the standard 1mb windows stack limit. Causing a stack overflow. So the guidance is to be as conservative as possible when using stackalloc.

2022-11-06 23:55 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                buffer = ArrayPool<char>.Shared.Rent(bufferSize);
Sure, but you can also think about the scenario that your code will execute in. For the .NET runtime itself, almost anything in the BCL is fair game for an app to invoke anywhere on a stack, so they want to be conservative. This is especially important when the method may be called multiple times on a thread recursively, such that what you allocate may be multiplied. But at the app level, you can decide how likely your call stacks are to approach the 1MB (default) limit and make other decisions. In WinForms, if you have an idea about the scenario you're called from, such that you would know you'll likely be on a 'short' callstack, then a 32KB frame size on a scale of 1MB seems small, IMO. 

Alternatively, if you're going to use a heap array, which is totally fine, I would _not_ try 'n' times. I would try once or twice. If once, I would just borrow an array that is at least as large as the largest value I would consider allowable. 
If twice, I would borrow an array that should fit 95% of the cases (say, 500 bytes), and if that fails, retry with the largest allowable length to scoop up the last 5%. The loop approach is just getting the worst of all worlds, IMO. You'll be slow, all in the name of trying to be efficient by not borrowing a longer array, but borrowing an array is pretty cheap. And borrowing _several_ arrays in a loop is more expensive.

2022-11-07 00:14 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                buffer = ArrayPool<char>.Shared.Rent(bufferSize);
Yeah, I feel the same way. I'll investigate the call stack to see how short it is. I like the idea of avoiding the heap. If we use is a loop is most likely a horrible idea compared to just asking for a bit more memory upfront.

2022-11-07 01:44 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                buffer = ArrayPool<char>.Shared.Rent(bufferSize);
Another option: use `stackalloc` with 1KB, and fallback to a 32KB array from the pool if that fails. You get the best of all worlds that way.

2022-11-07 02:19 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MaxClassName.cs
> +        /// <para><see href="https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-wndclassexw#members">Read more on docs.microsoft.com</see>.</para>
```suggestion
        /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-wndclassexw#members">Read more on docs.microsoft.com</see>.</para>
```

https://review.learn.microsoft.com/help/platform/links-how-to?branch=main#locale-codes-in-external-links

2022-11-07 02:19 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
> +                            // https://learn.microsoft.com/en-au/windows/win32/winmsg/about-window-classes#system-classes
Ditto

2022-11-07 03:52 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +                caption = Path.GetFileName(PInvoke.GetModuleFileNameLongPath(HINSTANCE.Null));
Instead of calling out to GetModuleFileNameLongPath, can we just use `AppDomain.CurrentDomain.FriendlyName`?
https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.friendlyname?view=net-7.0

https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/System.Private.CoreLib/src/System/AppDomain.cs#L52-L59

Or is that a lot slower of a code path?

2022-11-07 19:03 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                buffer = ArrayPool<char>.Shared.Rent(bufferSize);
Yes, we definitely don't want to stack alloc more than 1KB and I generally tried to keep under .5K on the runtime team (well, up to `MAX_PATH` chars (520 bytes)). In this case, looping is fine, and you could double I suppose to accommodate the internals of `ArrayPool`, but I wouldn't bother stressing too much about it. 4K (of bytes or chars) are super common buffer sizes taken from the pool and would cover 99.999% of path cases. While you could have paths that are longer than 2,000 characters, it would be terrible practice. In Unix based implementations the most you're going to see is 4KB of bytes (UTF-8 typically), but if I recall correctly Linux is 1K? In any case, we shouldn't optimize for extreme cases. :)

When running as 32bit (which WinForms users do, sometimes out of necessity) large allocations can have more of an impact. If we grab 32K buffers from the `ArrayPool` while under memory pressure they are much more likely to get aggressively trimmed from the `ArrayPool`, which would cause a lot of extra work for cases we will almost never see.

2022-11-07 19:12 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                if (pathLength > 0 && (pathLength < buffer.Length || (WIN32_ERROR)Marshal.GetLastWin32Error() != WIN32_ERROR.ERROR_INSUFFICIENT_BUFFER))
Probably need a comment here `If the length equals the buffer size we need to check to see if we were told the buffer was insufficient (it was trimmed).`.

Additionally, as it is a `uint` we don't need to check for `> 0`.  Finally, it should be `pathLength < buffer.Length - 1` (for the null).

2022-11-09 00:24 UTC, KlausLoeffelmann commented
> I would presume it is better to keep this in VB. @KlausLoeffelmann do you have any opinions here?

Not sure. Honestly, I am tending to go for a C# mapper. I guess it seems more consistent, and it might be even less error prone and more efficient.

2022-11-09 05:16 UTC, elachlan commented
The code has a `MAX_TITLE_LENGTH = 511`. Should I use this inside the PInvoke as the buffer constant? At the moment I have it written to call `GetWindowTextLength` and then either use `stackalloc` or `ArrayPool` depending on the size returned.
https://github.com/dotnet/winforms/blob/2479775c33fa9196e6717770e852b663aba283a7/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb#L136-L146

Secondly, VB is complaining because the `PInvoke` class is internal. How do I expose it to `Microsoft.VisualBasic.Forms`? Is it possible? Does `[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]` in `AssemblyInfo.cs` work with VB.Net?

2022-11-09 16:39 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                bufferOut = buffer[..(int)pathLength].ToArray();
nit: You're allocating a `char[]` only to pass it to a `string` that is also allocated. What if we move the `stackalloc` to the caller and pass in `ref Span<char>` as a parameter instead. This method could slice the span to fit the length and the caller can then initialize the string based on the `Span<char>` without ever allocating a `char[]`.

2022-11-09 23:15 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                isBufferTooSmall = (WIN32_ERROR)Marshal.GetLastWin32Error() == WIN32_ERROR.ERROR_INSUFFICIENT_BUFFER;
You should _not_ use `GetLastWin32Error` to determine *if* there was a problem. Per the docs:

> If the function succeeds, the return value is the length of the string that is copied to the buffer, in characters, not including the terminating null character. If the buffer is too small to hold the module name, the string is truncated to nSize characters including the terminating null character, the function returns nSize, and the function sets the last error to ERROR_INSUFFICIENT_BUFFER.

Note that in a success case, 'last error' is undefined. This is a common mistake in calling win32 APIs. You first must ascertain whether an error occurred, then if it has, you can call `GetLastWin32Error` to obtain the reason for failure. 
The bug here is that many Win32 APIs (including this one, we must assume based on the docs) do not call `SetLastError` in their success paths, so by calling `GetLastError` unconditionally here, you run the risk of getting an error code set by some earlier Win32 call, which may or may not randomly match the value you're checking for here.

Based on the docs, you can detect an error by comparing `pathLength == buffer.Length`. That can *only* be true in an error case, because in a success case, `pathLength < buffer.Length` since `pathLength` will exclude the null terminator.

2022-11-09 23:21 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
>              return string.Empty;
Is quietly returning an empty string here really the best thing to do here, or should we throw to call attention to the bizarre long path case?

2022-11-09 23:21 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                if (pathLength < lbuffer.Length - 1 && !isBufferTooSmall)
```suggestion
                if (pathLength < lbuffer.Length)
```

I don't know why you had the `- 1` as part of the expression. That looks like a bug.

2022-11-09 23:28 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
>              return string.Empty;
Most usages will error out anyway with an empty string. So I guess it might make sense to throw here so its obvious what is happening.

2022-11-09 23:29 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
>              return string.Empty;
I will wait on the winforms team to advise what they want.

2022-11-09 23:37 UTC, AArnott requested changes

2022-11-09 23:37 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetWindowText.cs
> +            lBuffer = ArrayPool<char>.Shared.Rent(length + 1);
You're missing a `return` above this point in the happy path on a non-empty window text that is 1KB or less. :)

2022-11-10 00:02 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetWindowText.cs
> +                pathLength = GetWindowText(hWnd, (PWSTR)lpString, lBuffer.Length);
That is why I asked about `MAX_TITLE_LENGTH`, If we use that, then the size doesn't matter because we will truncate it to the `MAX_TITLE_LENGTH`.

2022-11-10 00:23 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetWindowText.cs
> +                pathLength = GetWindowText(hWnd, (PWSTR)lpString, lBuffer.Length);
Also, if the max length is used, then we can avoid the whole > 1024 scenario.

2022-11-10 00:35 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
>              return string.Empty;
What exception would you use here?

2022-11-10 00:44 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
>              return string.Empty;
I used `InvalidOperationException`, its seems most appropriate.

2022-11-10 01:14 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
This should have worked but we are still getting build errors. I don't know why.

2022-11-10 01:36 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +        private static unsafe string GetClassName(HWND hWnd)
If you think this is a dup, feel free to remove this. I can't recall exact reasons why I copied it here.

2022-11-10 01:38 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
The build is failing for other reasons:
```
##[error]src\System.Windows.Forms.Primitives\src\Windows\Win32\PInvoke.GetModuleFileNameLongPath.cs(6,1): error IDE0005: (NETCORE_ENGINEERING_TELEMETRY=Build) Using directive is unnecessary.
```

2022-11-10 01:38 UTC, AArnott approved these changes

2022-11-10 01:46 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
> +        private static unsafe string GetClassName(HWND hWnd)
Since its a wrapper of the pinvoke and we don't reuse it, I think it can stay here.

2022-11-10 02:20 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
Now it has the failures:
```
error BC30389: (NETCORE_ENGINEERING_TELEMETRY=Build) 'Windows.Win32.PInvoke' is not accessible in this context because it is 'Friend'.
```

2022-11-10 02:32 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
Microsoft.VisualBasic.Forms doesn't reference System.Windows.Forms.Primitives project directly.

2022-11-10 02:34 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
...and I _personally_ don't think it should.

2022-11-10 02:37 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
It references `System.Windows.Forms`, which gives it a transitive reference to `System.Windows.Forms.Primitives` doesn't it?

2022-11-10 02:45 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
IVT is not transitive.

2022-11-10 03:25 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
@RussKie Did you want me to remove the `Microsoft.VisualBasic.Forms` changes and we can work out what to do for it in a separate PR?

2022-11-10 04:43 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
I defer the decision to @lonitra and @JeremyKuhne.

2022-11-10 06:56 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
@elachan it's probably better to do the VB stuff separately for clarity.

2022-11-10 07:12 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            if (pathLength < buffer.Length)
You need to check the error result if the `pathLength` is less than `buffer.Length - 1`. Remember that it will truncate at `buffer.Length - 1` if it can't fit. It is `-1` as it always null terminates. Same goes for below. Documentation is off here (and conflicting). I've looked at the actual implementation.

Try to test this code out by manually setting smaller buffer sizes to make sure your logic is working correctly.

2022-11-10 07:12 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            Span<char> buffer = stackalloc char[MAX_PATH];
I'd call this `stackBuffer` and the other `buffer`

2022-11-10 07:13 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                if (pathLength < lbuffer.Length)
As above, this needs to be -1 and check for the buffer too small error.

2022-11-10 07:14 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            throw new InvalidOperationException();
Don't introduce a throw here. Debug.Fail is more appropriate.

2022-11-10 13:51 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                if (pathLength < lbuffer.Length)
As above, I believe `-1` would introduce a bug where a file name that is exactly `lBuffer.Length - 1` in length would be misinterpreted as a 'too small' buffer.

2022-11-10 13:51 UTC, AArnott commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            throw new InvalidOperationException();
`Debug.Fail` is meaningless in the release bits, as you know. Would you really rather return `string.Empty` as if nothing went wrong?

2022-11-10 19:44 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            if (pathLength < buffer.Length)
As I mentioned, the docs are conflicting. It also states that it always reserves space for the null, which isn't included in the returned size. The returns `nSize` is a bug in the docs- it will _never_ return `nSize`. I've validated that this is the case by reviewing the Windows sources, but this can also be confirmed by running some tests. I'll see about creating an issue on the docs.

2022-11-10 19:56 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            if (pathLength < buffer.Length)
Never mind, I'm wrong. Looked again and it does return nSize (well as long as it isn't larger than the maximum unicode string)- the docs could stand for some clarification in any case.

2022-11-10 20:07 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            if (pathLength < buffer.Length)
These truncations are terribly inconsistent in the Win32 API. So in this case:

If you give a buffer `nSize` of 100 and the path is 100 characters long, you will get 100 back and it will _include_ the null. You actually have a 99 character string.

If you give a buffer `nSize` of 100 characters and the path is 99 characters long you will get 99 back.

So you can presume that if you get `nSize` back you didn't have a buffer that was big enough. Sorry for the confusion.

2022-11-10 20:08 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +                if (pathLength < lbuffer.Length)
You're right.

2022-11-10 20:09 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetModuleFileNameLongPath.cs
> +            throw new InvalidOperationException();
Yes, as that was our "normal" error case.

2022-11-10 20:55 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.VisualBasic.Forms, PublicKey=00000000000000000400000000000000")]
Removed it.

2022-11-11 01:13 UTC, RussKie commented
/azp run

2022-11-11 22:46 UTC, JeremyKuhne approved these changes
Thanks for your effort and patience here!

2022-11-11 22:46 UTC, merged