Enable nullability in some ToolStripItem members
dotnet/winforms pull request #8118
Opened 2022-11-05 06:15 UTC by gpetrou

## Proposed changes

- Enable nullability in some ToolStripItem members.

2022-11-07 19:26 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +                    imageSize = Owner!.ImageList!.ImageSize;
online 1633, we may expect `Owner` to be null and here we say NOT. I do not see anything else assigning it inbetween.

2022-11-08 07:43 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +                    imageSize = Owner!.ImageList!.ImageSize;
```suggestion
                    imageSize = Owner?.ImageList!?ImageSize ?? Size.Empty;
```

2022-11-08 07:45 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.cs
> +                ToolStrip? parent = ParentInternal;
```suggestion
                ToolStrip? parent = ParentInternal ?? Owner;
```

Not sure if `Owner` can be null here or not.

2022-11-08 07:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.cs
> +                switch (parent!.LayoutStyle)
Whether this is safe depends on line:173

2022-11-08 07:46 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
> +            ToolStripRenderer renderer = Renderer!;
Could you please clarify why are we making this assumption?

2022-11-08 16:41 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
> +            ToolStripRenderer renderer = Renderer!;
The implementation is a bit hard to go through, but inside `Renderer` property we check if `Owner is not null` and return a non-nullable `Renderer`. Otherwise, we return a nullable renderer. Because here and in other similar cases we check if Owner is null in the previous lines it seems that we can use the null-forgiving operator.

2022-11-08 22:47 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
> +            ToolStripRenderer renderer = Renderer!;
Makes sense, thank you.

2022-11-08 23:10 UTC, RussKie requested changes

2022-11-08 23:10 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +                    return _propertyStore!.GetObject(ToolStripItem.s_tagProperty);
1. I think `Properties` should be decorated with `MemberNotNull`, and
2. we should use `Properties` here instead of the field.

2022-11-09 05:45 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
> +                    return _propertyStore!.GetObject(ToolStripItem.s_tagProperty);
Just using `Properties` seems enough. `_propertyStore` is not used in other places besides inside the property.

2022-11-09 05:47 UTC, RussKie approved these changes

2022-11-09 20:05 UTC, merged