Enable nullability in some ListViewItem members
dotnet/winforms pull request #8123
Opened 2022-11-05 08:06 UTC by gpetrou

## Proposed changes

- Enable nullability in some ListViewItem members.

2022-11-08 08:05 UTC, RussKie commented
We're adding a lot new bang operators, and I find it concerning... Did you check if the code could be restructured in some way that could help avoiding these?

2022-11-09 18:11 UTC, gpetrou commented
> We're adding a lot new bang operators, and I find it concerning... Did you check if the code could be restructured in some way that could help avoiding these?

It's the same problem we have in other classes where there is an existing check about the number of items (for example we have `SubItemCount` here) or a method from another class that initializes the collection (for example we have `EnsureSubItemSpace` here) or checking of index and throwing `ArgumentOutOfRangeException`, etc... I have not found a good alternative to avoid these.

2022-11-11 23:06 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
> -        private int indentCount;
Fyi: normally you cannot change field names for classes that have `[Serializable]`. You can in this case as serialization is customized with `ISerializable` and the name changes won't impact that method.

2022-11-11 23:18 UTC, JeremyKuhne requested changes
I would harden the deserialization to not allow nulls in as a first step, then iterate from that point. One should presume everything is well-formed after calling Deserialize. Don't allow any nulls into the `_subItems` array.

2023-04-26 00:38 UTC, dreddy-work commented
@gpetrou, Can you see if you can spend some time to clean this and get it ready for review again?

2023-04-26 17:39 UTC, gpetrou commented
> Can you see if you can spend some time to clean this and get it ready for review again?

@dreddy-work I updated this one and https://github.com/dotnet/winforms/pull/7316.

2023-04-26 17:46 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems[_owner.SubItemCount] = null!;
on one end, we are ensuring we are not inserting null into `subItems` and throw right away but here in the remove method, we are inserting null. Given `subItem` is private, can you try moving it away from array?

2023-04-26 17:47 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems[_owner.SubItemCount] = null!;
that should help prevent use of `!` and also ensure `subItem` never contain `null`

2023-04-26 18:04 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems[_owner.SubItemCount] = null!;
Hmm, I assume you mean to use a generic List instead? What should we do in this case with `public ListViewItem(ListViewSubItem[] subItems, int imageIndex)` constructor for example? Is it OK to allocate more by converting to a list?

2023-04-27 17:19 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems[_owner.SubItemCount] = null!;
> What should we do in this case with public ListViewItem(ListViewSubItem[] subItems, int imageIndex) constructor for example? 

I missed that constructor. Allocating memory is not the only issue in this case. `ListViewSubItem[]` is by reference and any state changes like `owner` or `Name` or other properties assigned after wouldn't be in sync.

2023-04-27 17:20 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems[_owner.SubItemCount] = null!;
I will take another look this week and let you know if any other feedback.

2023-05-01 19:10 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems[_owner.SubItemCount] = null!;
As there is some risk of breaking here you could just put `Array.Empty<ListViewSubItem>()` into the field. While it seems unlikely that someone would be dependent on the passed in array being the initial array, it's probably not worth changing this without significantly more documented value.

As to using `List<T>`, it doesn't allocate an array until you add something to it, so it isn't a huge hit and could be considered where we don't have additional side effects like this classes' constructor.

2023-05-04 17:27 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems[_owner.SubItemCount] = null!;
If I understand correctly your comments, I should just change `null!` to `Array.Empty<ListViewSubItem>()`.

2023-05-05 00:01 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems[_owner.SubItemCount] = null!;
@gpetrou, discussed offline with Jeremy. In this case, it is more appropriate to go with `List<ListViewSubItem>` and prevent inserting null values into it. Also, on public constructor that passes `ListViewSubItem[]` , let's check the values of the array being non-null before assigning/inserting them to `subItems` to make it consistent.

2023-05-05 05:10 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems[_owner.SubItemCount] = null!;
@dreddy-work and @JeremyKuhne I added a separate commit. Is this what you had in mind?

2023-05-05 18:21 UTC, JeremyKuhne requested changes
This is in the right direction, changing to `List` can greatly simplify things. I've left a number of comments in this regard.

2023-05-05 18:21 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
> +        newItem.subItems = clonedSubItems.ToList();
This code is a little suboptimal- we're passing it in when we're not creating a derived instance above. I'd just do `new ListViewItem()` above and manually copy the items into the new `subItems` _here_ to avoid the extra unnecessary array creations.

2023-05-05 18:21 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
> +            subItems = newItems.ToList();
This again is a place you could just ensure capacity and add the rehydrated subitems directly to the list.

2023-05-05 18:21 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            _owner.subItems ??= new List<ListViewSubItem>();
This shouldn't be necessary at all. If there is always a list you can just add, insert, etc.

2023-05-05 18:21 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +                return new ArraySubsetEnumerator(_owner.subItems.ToArray(), _owner.SubItemCount);
This can all be collapsed to `public IEnumerator GetEnumerator() => _owner.subItems;`

2023-05-05 18:21 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +                Array.Copy(_owner.subItems!.ToArray(), 0, dest, index, Count);
You can skip an unnecessary copy here by `((ICollection)_owner.subItems).CopyTo(index, Count)`

2023-05-08 18:07 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            EnsureSubItemsCapacity(items.Length);
These aren't quite right. The method would ensure that there is (_owner._subItems.Count + items.Length) capacity. There is also a MaxItems check, which I can't find the reason for the limitation in the docs.

The check isn't quite right anyway, as it only ever checks if the capacity is exactly at the limit, it doesn't check when you're adding things if they go over. I'm not sure that the check is worth having without a documented reason.

Consider changing the method to `EnsureAdditionalCapacity` and having it calculate Length + additional.

2023-05-08 18:14 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
>          set => SubItems[0].Font = value;
This seems odd. Why is there no check for SubItemsCount when there is above?

2023-05-08 18:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
> +#nullable disable
Why disable again?

2023-05-08 18:16 UTC, JeremyKuhne requested changes
Looking better, added a few more comments

2023-05-08 18:41 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
> +#nullable disable
When files contain many lines and require lots of changes, I split the annotation changes in many PRs to help reviewers check them.

2023-05-08 18:50 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
> +            EnsureSubItemsCapacity(items.Length);
I changed it to `EnsureAdditionalCapacity`. Hopefully, this is what you had in mind. With regards to the limit, I wasn't sure why is it there, so I kept it.

2023-05-10 05:01 UTC, gpetrou commented
@JeremyKuhne, @dreddy-work any more feedback on this one?

2023-05-10 17:07 UTC, JeremyKuhne requested changes
@gpetrou just one last minor thing. This is looking great! I've been really busy, so please tag me when you've addressed it.

2023-05-10 17:54 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
> +                    ? _owningGroup.Items[0].ListView!
@JeremyKuhne I updated this.

2023-05-10 18:43 UTC, JeremyKuhne approved these changes
Looks great!

2023-05-10 18:44 UTC, merged