Enable nullability in some TreeNode members
dotnet/winforms pull request #8126
Opened 2022-11-06 07:40 UTC by gpetrou

## Proposed changes

- Enable nullability in some TreeNode members.

2022-11-07 22:11 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +                    TreeView tv = TreeView!;
is `TreeView` and t`reeView` same here?

2022-11-11 23:32 UTC, JeremyKuhne requested changes
It's worth trying to fix up the disconnect between the array and the count as it's really dangerous to have them separate. Additionally please make sure the `Deserialize` doesn't let garbage (nulls, etc.) back in where we would never have serialized garbage in the first place. That will put us in a better position to null annotate.

2022-11-11 23:32 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +                return children![childCount - 1];
Why can't we tie `childCount` and `children` together? Can you try to remove `childCount` and let `children` be the source of truth?

2022-11-12 07:02 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +                return children![childCount - 1];
Hmm, `childCount` according to `TreeNodeAndPropertyBag_RoundTripAndExchangeWithNet` participates in serialization/deserialization. So, I assume that we can't just remove it, right? Or you mean something else?

2022-11-14 03:41 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +                return children![childCount - 1];
I don't think it "participates" in the serialization, it just gets validated after the deserialization is complete to contain the expected value.

2022-11-14 03:49 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +                return children![childCount - 1];
The field is read here, but the value can be equally read from another source:
https://github.com/dotnet/winforms/blob/852e29689aca09c81bba1c73eade41a96e13704b/src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs#L2152

Here we probably don't technically need to assign the field, but use it as a local variable to initialise the underlying value collection:
https://github.com/dotnet/winforms/blob/852e29689aca09c81bba1c73eade41a96e13704b/src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs#L1597-L1598
https://github.com/dotnet/winforms/blob/852e29689aca09c81bba1c73eade41a96e13704b/src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs#L1636-L1646

2023-04-27 23:40 UTC, dreddy-work commented
@gpetrou, checking back on this long pending PR. Let us know if you are waiting on us.

2023-07-11 05:18 UTC, gpetrou commented
@dreddy-work any feedback on this one?

2023-09-26 04:43 UTC, gpetrou commented
@dreddy-work maybe you could also take a look at this one?

2023-10-04 18:40 UTC, JeremyKuhne approved these changes
Just one nit, otherwise looks good.

2023-10-04 22:54 UTC, merged