Using GetScaledBitmapFromIcon instead of GetBitmapFromIcon
dotnet/winforms pull request #8145
Opened 2022-11-09 12:25 UTC by NikitaSemenovAkvelon

Fixes #6137

## Proposed changes

- Added new overload `Bitmap GetScaledBitmapFromIcon(Type type, string name)` with default size 16x16 which uses in most cases.
- Replaced `GetBitmapFromIcon` with `GetScaledBitmapFromIcon` in cases where resize isn't applied and we know the size of the icon precisely. 

## Customer Impact

- Icons will be more appropriate and their size will be depended on the current DPI.

## Regression? 

- No

## Risk

- Minimal.

## Test methodology 

- Manually (using different screen scales 100%-175%)

 

## Test environment(s) 

.NET SDK:
 Version:   8.0.100-alpha.1.22512.5
 Commit:    1b80461e45

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8145)

2022-11-09 20:18 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        ///  Syze by default is set to 16x16.
I would say something like " most common icon size in WinForms controls is 16x16, use this size by default."

2022-11-09 20:18 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        /// <param name="type">Resource type</param>
This comment was there before your change, so take it or leave it. But this explanation is not helpful, and we are trying to improve the files we are touching.  MSDN says:
https://learn.microsoft.com/en-us/dotnet/api/system.drawing.icon.-ctor?view=windowsdesktop-7.0#system-drawing-icon-ctor(system-type-system-string)
> A [Type](https://learn.microsoft.com/en-us/dotnet/api/system.type?view=windowsdesktop-7.0) that specifies the assembly in which to look for the resource.

2022-11-09 20:18 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        /// <param name="type">Resource type</param>
Also `defaultSize` is not an accurate argument name, this is an unscaled size

2022-11-09 20:18 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        internal static Bitmap GetScaledBitmapFromIcon(Type type, string name)
`GetScaledBitmapFromIcon` does not reflect what this function is doing. Function is creating a bitmap of an unscaled size actually. At most callsites, these images are scaled by controls later (by buttons)

2022-11-09 20:18 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/BindingNavigator.cs
> +            Bitmap moveFirstImage = DpiHelper.GetScaledBitmapFromIcon(typeof(BindingNavigator), "BindingNavigator.MoveFirst");
nitpick: these local variables are used in a single place, they could be removed.

2022-11-09 20:18 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        internal static Bitmap GetScaledBitmapFromIcon(Type type, string name)
Maybe: `Get16by16BitmapFromIcon`? And then you don't need the `<summary>` comment, as they are not required for internals and only are confusing.

2022-11-09 20:51 UTC, dreddy-work requested changes
Before i go into the changes, I wanted to get clarification. Winforms uses various sizes for their default size. we use `SM_CYSMICON` and `SM_CXICON` as required. Defaulting to 16*16 will not work for all of them. Also, are you certain we never needed 32*32 as default? 

Also, we already have a method called `GetScaledBitmapFromIcon`. Can you please elaborate your changes and intention here more clearly and how complete is your testing with respect to all WinForms controls? Are you addressing a specific section here and we still have more instances? These changes need deeper analysis.

2022-11-10 02:03 UTC, RussKie commented
@NikitaSemenovAkvelon could you please provide some images showing the before and the after states?

2022-11-10 02:08 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        /// <returns>New scaled bitmap</returns>
Generally, non public API aren't required to have xml-docs (though very much encouraged). However, the xml-docs for non-public API must follow the same [rules and standards](https://learn.microsoft.comdotnet/csharp/language-reference/xmldoc/recommended-tags) as their public counterparts. That is:
- follow the wording patterns - use MSDN as a source of examples,
- follow "Sentence case rules." - i.e., capitalise the first word and end with a full stop.

2022-11-10 02:10 UTC, RussKie commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        internal static Bitmap GetScaledBitmapFromIcon(Type type, string name)
> Maybe: `Get16by16BitmapFromIcon`? And then you don't need the `<summary>` comment, as they are not required for internals and only are confusing.

`Get16x16BitmapFromIcon

2022-11-10 02:11 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
> +            _imageList.Images.AddStrip(DpiHelper.GetScaledBitmapFromIcon(typeof(PrintPreviewDialog), "PrintPreviewStrip", new(112, 16)));
`112 x 16`? Is this expected? If so, this deserves a comment.

2022-11-10 02:12 UTC, RussKie commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
> +                Bitmap bitmap = DpiHelper.GetScaledBitmapFromIcon(toolStripScrollButtonType, dpiTestData.ResourceName);
```suggestion
                using Bitmap bitmap = DpiHelper.GetScaledBitmapFromIcon(toolStripScrollButtonType, dpiTestData.ResourceName);
```

2022-11-10 05:01 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        internal static Bitmap GetScaledBitmapFromIcon(Type type, string name)
This method was added just for ease of use due to the default size of most icons is 16x16. By the method, we can avoid creating instances of default unscaled size if it 16x16.
Anyway, it calls `GetScaledBitmapFromIcon(Type type, string name, Size unscaledSize)` overload and then compares unscaled and scaled sizes, and if needed load icon in different sizes (20x20, 24x24, 32x32, etc).

2022-11-10 05:07 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
> +            _imageList.Images.AddStrip(DpiHelper.GetScaledBitmapFromIcon(typeof(PrintPreviewDialog), "PrintPreviewStrip", new(112, 16)));
It is the size of the icon in recourses.

2022-11-10 05:19 UTC, NikitaSemenovAkvelon commented
> Before i go into the changes, I wanted to get clarification. Winforms uses various sizes for their default size. we use `SM_CYSMICON` and `SM_CXICON` as required. Defaulting to 16_16 will not work for all of them. Also, are you certain we never needed 32_32 as default?
> 
> Also, we already have a method called `GetScaledBitmapFromIcon`. Can you please elaborate your changes and intention here more clearly and how complete is your testing with respect to all WinForms controls? Are you addressing a specific section here and we still have more instances? These changes need deeper analysis.

As I mentioned above, the new method `Bitmap GetScaledBitmapFromIcon(Type type, string name)` was added just for ease of use. A method with `Size` is still here, you might provide any custom value. And the resulting size is still calculated and might be different from the default unscaled if a user uses a custom DPI.
As the default unscaled size, I used the size of icons in resources.

2022-11-10 05:34 UTC, NikitaSemenovAkvelon commented
> @NikitaSemenovAkvelon could you please provide some images showing the before and the after states?

In UI no changes now, therefore I haven't used Before/After section. Currently, all of these icons, which I used in the PR, have small sizes and can't be scaled bigger. As I see, previous changes (#5976) work due to the size of icons being 64x64 and they can be scaled to smaller sizes.

2022-11-10 16:40 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        internal static Bitmap GetScaledBitmapFromIcon(Type type, string name)
Well, the callers expect unscaled bitmap because it will be scaled later in the process and control has to store an unscaled bitmap as a reference to use for scaling on each DPI change.
```
        public static Bitmap GetBitmapFromIcon(Type t, string name)
        {
            Icon b = new Icon(t, name);
            Bitmap bitmap = b.ToBitmap();
            b.Dispose();
            return bitmap;
        }
```

2022-11-11 01:49 UTC, dreddy-work commented
> As I mentioned above, the new method `Bitmap GetScaledBitmapFromIcon(Type type, string name)` was added just for ease of use. A method with `Size` is still here, you might provide any custom value. And the resulting size is still calculated and might be different from the default unscaled if a user uses a custom DPI. As the default unscaled size, I used the size of icons in resources.

I do not see a value add with this additional method other than adding more confusion with existing similar method names.  You have not clarified if 16*16 size is specific to Toolstrip's Icons or applicable across all WinForms controls.  Also, this change still doesn't solve the original issue of showing difference by scaling bitmaps between 126% and 150%. Happy to chat offline if you like to.

2022-11-15 01:16 UTC, elachlan commented
BindingNavigator.cs(8,1): error IDE0005: (NETCORE_ENGINEERING_TELEMETRY=Build) Using directive is unnecessary.

2023-05-31 21:28 UTC, Tanya-Solyanik commented
@dreddy-work  - I agree that `Bitmap GetScaledBitmapFromIcon(Type type, string name)` is error-prone, and that that call should always pass in the actual resource size.

>Also, this change still doesn't solve the original issue of showing difference by scaling bitmaps between 126% and 150%.

Please clarify this for me. I thought the issue was about always scaling using the icon class methods because they pick the frame that is closes to the desired size, so we do less "stretching" on our own.

2023-05-31 22:23 UTC, elachlan commented
Could the DPIHelper functions be moved to System.Drawing? I imagine that means an API Proposal/Review?

2023-05-31 23:09 UTC, Tanya-Solyanik commented
>Could the DPIHelper functions be moved to System.Drawing? I imagine that means an API Proposal/Review?

This would be out of scope for this change.

2023-11-15 05:49 UTC, lonitra commented
Closing given that issue has no customer impact and this PR is outdated with main. If anyone feels strongly, they are welcome to give this another go in a newer PR.

2023-11-15 05:49 UTC, closed without merging