Refactor `ResXResourceWriter` to use `Dictionary<string, string>` instead of `Hashtable`
dotnet/winforms pull request #8160
Opened 2022-11-10 23:07 UTC by elachlan

Refactor `ResXResourceWriter` to use `Dictionary<string, string>` instead of `Hashtable`.

Related: #8143

2022-11-11 00:21 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
> +            string alias = _cachedAliases[assemblyName.FullName];
wouldn't this result in key not found exception when `_cachedAliases` is assigned with `new` ?  Did you see a scenario where we are calling this with `_cachedAliases` being null?

2022-11-11 00:25 UTC, elachlan commented on src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
> +            string alias = _cachedAliases[assemblyName.FullName];
Ahh, I see. I will sort it. We will need to use TryGetValue.

2022-11-11 00:57 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
> +            if (!_cachedAliases.TryGetValue(assemblyName.FullName, out string alias))
I know this is existing code but it is flawed.  It was okay with `Hashtable` but replacing it with Dictionary prompts to refactor this code. Assigning an empty dictionary and immediately trying to access the index is not efficient. 
Is assignment necessary in this method? can we simply do   ` if (_cachedAliases == null ) return null ;`

2022-11-11 01:07 UTC, elachlan commented on src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
> +            if (!_cachedAliases.TryGetValue(assemblyName.FullName, out string alias))
No. If `GetAliasFromName` is called, it needs to return an alias string. 

The logic is basically saying, create a cache if we haven't created one already. Check if the value exists in the cache, if it doesn't exist in the cache, add the alias to the cache and return said alias.

2022-11-11 01:10 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
> +            if (!_cachedAliases.TryGetValue(assemblyName.FullName, out string alias))
:). you are right. i read next line checking as non null.

2022-11-11 01:11 UTC, dreddy-work submitted a review, later dismissed
LGTM.

2022-11-11 01:12 UTC, elachlan commented on src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
> +            if (!_cachedAliases.TryGetValue(assemblyName.FullName, out string alias))
Thank you for being a sanity check!

2022-11-11 22:49 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
> +            if (!_cachedAliases.TryGetValue(assemblyName.FullName, out string alias))
This isn't exactly the same. Without null annotations turned on this is a dictionary of `<string?, string?>`. Please check that the returned value isn't null or empty as before.

2022-11-11 23:34 UTC, JeremyKuhne requested changes
See my comment on checking for null or empty.

2022-11-13 22:34 UTC, elachlan commented on src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
> +            if (!_cachedAliases.TryGetValue(assemblyName.FullName, out string alias))
done.

2022-11-15 03:01 UTC, RussKie approved these changes

2022-11-18 01:03 UTC, elachlan commented
@JeremyKuhne Could you please look over this one as well.

2022-11-19 01:16 UTC, JeremyKuhne approved these changes

2022-11-19 01:16 UTC, merged