Refactor `AxHost` to use `Dictionary<VSSDK.PROPCAT, CategoryAttribute>` instead of `Hastable`
dotnet/winforms pull request #8163
Opened 2022-11-10 23:24 UTC by elachlan

Related: #8143

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8163)

2022-11-11 01:02 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +                if (_objectDefinedCategoryNames.TryGetValue(propcat, out CategoryAttribute rval))
nit: merge with above `if` and try simplify.

2022-11-11 01:09 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +                if (_objectDefinedCategoryNames.TryGetValue(propcat, out CategoryAttribute rval))
I tried this, this solution seemed cleaner because it avoids a clash with the local further down and the null check cannot be simplified for whatever reason.

2022-11-11 01:12 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +                if (_objectDefinedCategoryNames.TryGetValue(propcat, out CategoryAttribute rval))
hmm.

2022-11-11 01:13 UTC, dreddy-work submitted a review, later dismissed

2022-11-11 18:16 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +                if (_objectDefinedCategoryNames.TryGetValue(propcat, out CategoryAttribute rval))
The two local `rval` seem unnecessary here. We should create just one of these (`CategoryAttribute rval = null`) before the `if` and reuse this same variable to get/return the `CategoryAttribute` throughout. We would be able to merge the `if` statements if we restructure it this way I believe. We should also just rename this variable to `category` :).

2022-11-11 23:41 UTC, lonitra requested changes
Just a suggestion to restructure code a little bit

2022-11-13 22:46 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +                if (_objectDefinedCategoryNames.TryGetValue(propcat, out CategoryAttribute rval))
I think that does it.

2022-11-14 04:18 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +                ?? false && category is not null)
```suggestion
            if (_objectDefinedCategoryNames?.TryGetValue(propcat, out CategoryAttribute category) ?? false
                && category is not null)
```

2022-11-14 06:52 UTC, RussKie approved these changes

2022-11-14 16:47 UTC, lonitra approved these changes
LGTM, thank you!

2022-11-14 16:47 UTC, merged