Refactor `HelpProvider` to use `Dictionary` instead of `Hastable`
dotnet/winforms pull request #8164
Opened 2022-11-11 01:59 UTC by elachlan

Refactor `HelpProvider` to use `Dictionary` instead of `Hastable`

Related: #8143

2022-11-11 02:00 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
>          private readonly Hashtable _boundControls = new Hashtable();
I thought this might be a good use of `Hashset<T>`, but stackoverflow suggests the performance isn't as good as `List<T>` for objects until after 20 items. https://stackoverflow.com/a/10762995/908889

2022-11-11 23:46 UTC, JeremyKuhne requested changes
A couple of comments.

2022-11-11 23:46 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
> +            return _navigators.TryGetValue(ctl, out HelpNavigator value) ? value : HelpNavigator.AssociateIndex;
This needs to allow for a null `HelpNavigator`. Without null annotations to ensure that the `Dictionary` doesn't allow nulls, play safe.

```suggestion
            return _navigators.TryGetValue(ctl, out HelpNavigator value) && value is not null ? value : HelpNavigator.AssociateIndex;
```

2022-11-11 23:46 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
>          private readonly Hashtable _boundControls = new Hashtable();
I'd still make this something of `<Control>`. Pick `List<T>` or `HashSet<T>`, I'm fine with either if we think there will be few items.

2022-11-12 07:50 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
>          private readonly Hashtable _boundControls = new Hashtable();
Maybe `Dictionary<HWND, Control>`, that way we can quickly lookup the control without doing a large computation on the hashcode? `Control.HWND` should be unique enough for this scenario right?

2022-11-12 07:59 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
> +            return _navigators.TryGetValue(ctl, out HelpNavigator value) ? value : HelpNavigator.AssociateIndex;
If I add that I get the following error: `Cannot convert null to 'HelpNavigator' because it is a non-nullable value type`.

2022-11-15 00:21 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
> +            return _navigators.TryGetValue(ctl, out HelpNavigator value) ? value : HelpNavigator.AssociateIndex;
Sorry, thought it was a class, my mistake. :)

2022-11-15 00:32 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
>          private readonly Hashtable _boundControls = new Hashtable();
Using the HWND as a key is risky (and wrong) as Control can have its handle recreated. Hash codes for objects shouldn't be a concern, they're static for a given instance, have nothing to do with instance fields, and are likely to have already been generated. If you want a hashed lookup, just use HashSet<T>.

2022-11-15 00:34 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
> +        private readonly List<Control> _boundControls = new();
I think instead of `List<Control>` we should use `Dictionary<HWND, Control>` as it would reduce the lookup time.

2022-11-15 00:36 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
>          private readonly Hashtable _boundControls = new Hashtable();
Thanks! I think List<Control> should be okay then. Since its performance is better than HashSet for Count < 20.

2022-11-15 01:14 UTC, elachlan commented
@RussKie flaky test, can you please re-run pipeline?

2022-11-16 01:01 UTC, RussKie approved these changes

2022-11-17 23:08 UTC, elachlan commented
@JeremyKuhne could you please check over this again?

2022-11-18 00:51 UTC, JeremyKuhne approved these changes

2022-11-18 01:26 UTC, merged