Refactor `VisualStyleRenderer` to use `Dictionary` instead of `Hastable`
dotnet/winforms pull request #8166
Opened 2022-11-11 05:09 UTC by elachlan

Related: #8143

2022-11-12 00:19 UTC, lonitra requested changes
Some small fixes, otherwise looks good! :)

2022-11-12 00:19 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
>                  return tHandle.Handle;
Let's remove this line as this is the same return statement as below.

2022-11-12 00:19 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +            if (!t_themeHandles.TryGetValue(className, out ThemeHandle? tHandle))
nit:
```suggestion
            if (!t_themeHandles.TryGetValue(className, out ThemeHandle? themeHandle))
```

2022-11-14 16:33 UTC, lonitra approved these changes
Thank you!

2022-11-14 16:55 UTC, merged

2022-11-14 22:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +                ThemeHandle? themeHandle = t_themeHandles[className];
Should this use `TryGet` method?

2022-11-14 23:02 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
> +                ThemeHandle? themeHandle = t_themeHandles[className];
It might be a good idea to do so. But not totally necessary, since we do a null check when adding the themeHandle to the dictionary.