Refactor several data grid view classes to use List<T> instead of ArrayList
dotnet/winforms pull request #8188
Opened 2022-11-14 18:19 UTC by Jericho

Related: https://github.com/dotnet/winforms/issues/8140

2022-11-14 18:58 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
> +            _items.ToArray().CopyTo(array, index);
FYI: I would have prefered `_items.CopyTo((DataGridViewCell[])array, index);` but the `DataGridViewSelectedCellCollection_IListCopyTo_InvokeEmpty_Success` unit test verifies that the collection, when empty, can be copied to an array of objects. This array of objects cannot be cast to `.DataGridViewCell[]` which leads to the failed unit test with this exception: `System.InvalidCastException : Unable to cast object of type 'System.Object[]' to type 'System.Windows.Forms.DataGridViewCell[]'.`

2022-11-14 19:04 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedRowCollection.cs
> +            _items.ToArray().CopyTo(array, index);
FYI: I would have preferred `_items.CopyTo((DataGridViewRow[])array, index);` but the `DataGridViewSelectedRowCollection_IListCopyTo_InvokeEmpty_Success` and `DataGridViewSelectedRowCollection_IListCopyTo_InvokeNotEmpty_ReturnsExpected` unit tests verify that the collection can be copied to an array of objects. This array of objects cannot be cast to `DataGridViewRow[]` which leads to failed unit tests with this exception: `System.InvalidCastException : Unable to cast object of type 'System.Object[]' to type 'System.Windows.Forms.DataGridViewRow[]'.`

2022-11-15 02:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs
> +        private readonly List<DataGridViewCell> _items = new List<DataGridViewCell>();
[nit]
```suggestion
        private readonly List<DataGridViewCell> _items = new();
```

2022-11-15 02:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs
> +            };
I'm not an expert on pattern matching, do we need `null => false` clause here? Isn't this sufficient?
```cs
            return value switch
            {
                DataGridViewCell dataGridViewCell => Contains(dataGridViewCell),
                _ => false,
            };
```

Do we have a test coverage for this method?

2022-11-15 02:53 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
> +            _items.ToArray().CopyTo(array, index);
Since we're changing the underlying types, it's appropriate and acceptable to update tests.
I think we've dealt with a similar issue in the past, see if [this discussion](https://github.com/dotnet/winforms/pull/6909#discussion_r837008443) helps.

2022-11-15 02:54 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs
> +            _items.ToArray().CopyTo(array, index);
On the surface this seems wasteful - `_items.ToArray()` allocates one array, then we copy from that array into another array...
I think we've dealt with a similar issue in the past, see if [this discussion](https://github.com/dotnet/winforms/pull/6909#discussion_r837008443) helps.

2022-11-15 02:54 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
> +        private readonly List<DataGridViewCell> _items = new List<DataGridViewCell>();
```suggestion
        private readonly List<DataGridViewCell> _items = new();
```

2022-11-15 15:58 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs
> +            _items.ToArray().CopyTo(array, index);
Thanks for the link. I'll implement Stephen's suggestion.

2022-11-15 16:25 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs
> +            };
Your suggestion is indeed sufficient. I'll make the change.

2022-11-15 17:50 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs
> +            int index = _items.LastIndexOf(dataGridViewCell);
can it not be just `_items.Count -1` ?

2022-11-15 17:51 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
> +            var index = _items.LastIndexOf(dataGridViewCell);
same here.

2022-11-15 23:34 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
> +            var index = _items.LastIndexOf(dataGridViewCell);
yes it can

2022-11-16 00:54 UTC, RussKie reviewed
👍

2022-11-16 00:59 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedColumnCollection.cs
> +        private readonly List<DataGridViewColumn> _items = new List<DataGridViewColumn>();
```suggestion
        private readonly List<DataGridViewColumn> _items = new();
```

2022-11-16 01:06 UTC, RussKie approved these changes

2022-11-17 17:46 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
> +            return index;
```suggestion
            return _items.Count - 1;
```

2022-11-17 17:47 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedColumnCollection.cs
> +            return _items.LastIndexOf(dataGridViewColumn);
same here. `return _items.Count - 1;`

2022-11-17 17:47 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedRowCollection.cs
> +            return index;
```suggestion
            return _items.Count - 1;
```

2022-11-17 17:48 UTC, dreddy-work requested changes
Added comments

2022-11-17 17:54 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
> +            return index;
I was trying to be consistent with other instances where the index of the new item is returned by respecting the syntax that was used in those cases but I'm happy to switch to your proposed syntax.

2022-11-17 17:55 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedColumnCollection.cs
> +            return _items.LastIndexOf(dataGridViewColumn);
Same explanation too!

2022-11-17 17:56 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedRowCollection.cs
> +            return index;
I was trying to be consistent with other instances where the index of the new item is returned by respecting the syntax that was used in those cases but I'm happy to switch to your proposed syntax.

2022-11-17 18:38 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedColumnCollection.cs
> +            return _items.LastIndexOf(dataGridViewColumn);
Change made.

2022-11-17 18:39 UTC, Jericho commented
@dreddy-work thanks. I addressed all your comments

2022-11-17 18:52 UTC, dreddy-work approved these changes

2022-11-17 19:07 UTC, merged