Refactor DesignerActionService to replace Hashtable and ArrayList
dotnet/winforms pull request #8198
Opened 2022-11-15 05:12 UTC by elachlan

Related: #8140, #8143

2022-11-15 12:13 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                            bool hookupEvents = !_componentToVerbsEventHookedUp.Contains(component);
```suggestion
                            bool hookupEvents = _componentToVerbsEventHookedUp.Add(component);
```
and delete `if` below?

2022-11-16 04:40 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                            bool hookupEvents = !_componentToVerbsEventHookedUp.Contains(component);
Thanks, done.

2022-11-17 17:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                            bool hookupEvents = _componentToVerbsEventHookedUp.Add(component);
can you explain how this is equivalent? Also is `hookupEvents` used anywhere else?

2022-11-17 17:56 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                        actionLists.RemoveAt(i);
I don't think this is right way to remove element. Once you remove, its elements indexes changed. It would be nice if you can add a unit test as well here to make sure we don't do this in the future accidentally.

2022-11-17 17:56 UTC, dreddy-work requested changes
Added comments

2022-11-18 00:56 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                            bool hookupEvents = _componentToVerbsEventHookedUp.Add(component);
`hookupEvents` is a local. `HashSet.Add()` returns a bool depending on the existence of the item in the HashSet.

> true if the element is added to the [HashSet<T>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1?view=net-7.0) object; false if the element is already present.
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.add?view=net-7.0

It simplifies the whole thing since the old version only had items in the collection when their value was true.

2022-11-18 01:01 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                        actionLists.RemoveAt(i);
We are doing a reverse loop. Example: https://stackoverflow.com/questions/1582285/how-to-remove-elements-from-a-generic-list-while-iterating-over-it

I think the other option is to do a `List<T>.RemoveAll()` like in the link. That would be even less verbose.

2022-11-18 01:33 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                        actionLists.RemoveAt(i);
Thank you. I should have paid more attention. Names confused me.

2022-11-18 01:34 UTC, dreddy-work approved these changes

2022-11-18 01:41 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                        actionLists.RemoveAt(i);
Do you want me to use RemoveAll? it would remove the loop and make it less verbose and easier to understand.

2022-11-18 02:01 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                        actionLists.RemoveAt(i);
Sure. I do not see collection list doing anything else when removed item individually.

2022-11-18 02:08 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
> +                        actionLists.RemoveAt(i);
Actually its of type `DesignerActionListCollection`, so `RemoveAll` isn't available :(

2022-11-18 17:33 UTC, merged