Refactor ArrangedElementCollection to use List<IArrangedElement> instead of ArrayList
dotnet/winforms pull request #8207
Opened 2022-11-16 17:23 UTC by Jericho

Related: #8140

2022-11-16 21:55 UTC, elachlan commented
```
src\System.Windows.Forms\src\System\Windows\Forms\Control.ControlCollection.cs(193,43): error CS8604: (NETCORE_ENGINEERING_TELEMETRY=Build) Possible null reference argument for parameter 'item' in 'bool List<IArrangedElement>.Contains(IArrangedElement item)'.
```

2022-11-16 23:06 UTC, Jericho commented
@elachlan Thanks for pointing this out. Fixed.

2022-11-17 18:02 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
> -                ccOther.InnerList.AddRange(this);
Little confusing here. fist, why this change? second, InnerList is coming from parent whereas this is current control. Can you explain these two are same here?

2022-11-17 18:05 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
> -        public virtual bool IsReadOnly => InnerList.IsReadOnly;
Changes like these makes it hard to review. Can you make sure you add detailed description of your changes ? this is just not replacing `Arraylaist` with generic Collections.

2022-11-17 18:05 UTC, dreddy-work submitted a review, later dismissed
Please add description with details for each change types to help review better.

2022-11-17 18:42 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
> -                ccOther.InnerList.AddRange(this);
Without this change you would get the following compile this exception:
```
Error	CS1503	Argument 1: cannot convert from 'System.Windows.Forms.Control.ControlCollection' to 'System.Collections.Generic.IEnumerable<System.Windows.Forms.Layout.IArrangedElement>'	System.Windows.Forms	D:\_build\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.ControlCollection.cs	187	Active	Normal

2022-11-17 18:55 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
> -        public virtual bool IsReadOnly => InnerList.IsReadOnly;
The data type of 'InnerList' used to be `ArrayList` which has a `IsReadOnly` property. That's why, before this change, you could write ` public virtual bool IsReadOnly => InnerList.IsReadOnly;`. But, after that change, this is no longer possible because `List<T>` does not have a `IsReadOnly` property. I argue that this change in the code is absolutely related to replacing `ArrayList` with `List<T>`. We have made this exact same change in several other places as well such as [here](https://github.com/dotnet/winforms/pull/8142/files#diff-42a2342eabb487120f84d2a4d87df7c6e59b47b2f10c2529eb725f25a4e610b7R47), [here](https://github.com/dotnet/winforms/pull/8212/files#diff-94be5b9664d883143a3192afd1664637a0945d3b3dd3eaee693ab63d1e82319aR116) and [here](https://github.com/dotnet/winforms/pull/8153/files#diff-0a1ebad9dd3c77e05a4f6a7bcaf4c7e72a9a0521b799b6f6a6d9908621c9bcdbR34).

2022-11-18 00:41 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
> -        public virtual bool IsReadOnly => InnerList.IsReadOnly;
Thank you @Jericho for pointing those. Will go over the PR once again.

2022-11-24 01:17 UTC, elachlan commented
@dreddy-work this looks like flaky tests, can you please refresh the pipeline?

2022-11-24 01:18 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
> +                return control is null ? false : InnerList.Contains(control);
use expression body?

2022-11-24 01:18 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
> +                return control is null ? -1 : InnerList.IndexOf(control);
use expression body?

2022-11-24 15:05 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
> +                return control is null ? false : InnerList.Contains(control);
I was trying to respect the current syntax but happy to change it.

2022-11-24 15:09 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
> +                return control is null ? -1 : InnerList.IndexOf(control);
I was trying to respect the current syntax but happy to change it.

2022-11-28 21:46 UTC, JeremyKuhne requested changes
Thanks for doing this! I've got a couple of comments to address, but otherwise looks good!

2022-11-28 21:46 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
> +        internal virtual IArrangedElement this[int index] => InnerList[index]!;
Shouldn't the bang be able to be removed now?

2022-11-28 21:46 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
> +            if (value is IArrangedElement element)
Typing this collection is a breaking change so it is probably better to throw an argument exception here and change the documentation to make it clear that the collection will only take `IArrangedElement` now. `-1` is not something you would ever get from `ArrayList.Add`.

2022-11-28 21:50 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
> +            if (value is IArrangedElement element)
One option here is to cast the inner list to `IList` so you get the same exact throw it would do (`ArgumentException`). You'll also get the count out that way.

2022-11-29 15:08 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
> +        internal virtual IArrangedElement this[int index] => InnerList[index]!;
I'll remove it.

2022-11-29 15:31 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
> +            if (value is IArrangedElement element)
I like your idea to cast to `IList`. I'll make the change in `Add` and `IndexOf` as well.

FYI: as part of #8140, we modified several `Add`, `Contains`, `IndexOf`, etc. methods that could probably have benefited from your suggestion. Here are just a few examples: [here](https://github.com/dotnet/winforms/pull/8188/files#diff-0b3e6d3de1bcf8ce19e1a6bf0f7c6c4a4de8edcde488a696471cc55fb6470abeR36-R40), [here](https://github.com/dotnet/winforms/pull/8142/files#diff-42a2342eabb487120f84d2a4d87df7c6e59b47b2f10c2529eb725f25a4e610b7R65-R66), [here](https://github.com/dotnet/winforms/pull/8153/files#diff-0a1ebad9dd3c77e05a4f6a7bcaf4c7e72a9a0521b799b6f6a6d9908621c9bcdbR198-R199) and [here](https://github.com/dotnet/winforms/pull/8188/files#diff-0b3e6d3de1bcf8ce19e1a6bf0f7c6c4a4de8edcde488a696471cc55fb6470abeR45-R49).

2022-11-29 18:49 UTC, JeremyKuhne reviewed
:shipit:

2022-11-29 18:49 UTC, JeremyKuhne approved these changes

2022-11-29 18:51 UTC, merged

2022-11-29 18:55 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
> +            if (value is IArrangedElement element)
Absolutely. I'll go back to all PRS where we refactored classes to use List instead if Array List.