Refactor ComponentDesigner.ShadowPropertyCollection to use Dictionary<TKey, TValue> instead of Hashtable
dotnet/winforms pull request #8222
Opened 2022-11-17 20:01 UTC by Jericho

Related: #8143

2022-11-17 20:25 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> +                    return property;
could `property `be null here?

2022-11-17 21:35 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> +                    return property;
`_descriptors` is never added to and seems redundant? Maybe one of the @dotnet/dotnet-winforms team members knows whats going on there.

2022-11-18 00:23 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> +                    return property;
Given setter is public and may allow null, What do we lose if we like to keep existing functionality?

2022-11-18 00:39 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> +                    return property;
I think its designed as a cache, so it should probably add to it further down. But I am not 100% sure of that.

2022-11-18 01:00 UTC, Jericho commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> +                    return property;
The values stored in the Hashtable (or Dictionary) are not null and this particular dictionary is not publicly exposed (the other dictionary is exposed though).

I was about to point out that the `_descriptors` Hashtable (or Dictionary) is never assigned to but @elachlan beat me to it! This means that it's always empty! So the current logic is flawed. My guess is the original intent was to use `_descriptors` as a cache to store the values returned by `TypeDescriptor.GetProperties(_designer.Component.GetType())[propertyName]` so that it would be much faster to subsequently retrieve the values. Again, I'm just guessing, but my guess is the original author of this code forgot to add the values to the Hashtable and nobody ever noticed this omission.

I'll be happy to fix this omission by caching the values into the Dictionary.

2022-11-18 01:05 UTC, Jericho commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> +                    return property;
I propose fixing the omission like so:

```csharp
if (!_descriptors.TryGetValue(propertyName, out PropertyDescriptor property))
{
    property = TypeDescriptor.GetProperties(_designer.Component.GetType())[propertyName];
    _descriptors.Add(propertyName, property);
}

return property;
```

2022-11-18 02:29 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> +                    return property;
I think it might be better if we create an issue for that specific change and keep the existing logic. I think we would need a bit of investigation to see if this would interfere with object lifecycles.

2022-11-22 02:13 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> +                    return property;
@Jericho / @elachlan , looking at the various references, `_descriptors `could be populated with [null values](https://github.com/dotnet/winforms/blob/7d1bd879fe2dd030f5d36a8cb25ef1b352e90c60/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormDocumentDesigner.cs#L341) and [here](https://github.com/dotnet/winforms/blob/7d1bd879fe2dd030f5d36a8cb25ef1b352e90c60/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDropDownDesigner.cs#L576) not just missing descriptors. Call sites of this method was not expecting null in all cases though. Needs further investigation before updating functionality.

2022-11-22 02:18 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
>                      _properties[propertyName] = value;
@dreddy-work Should we add a null check on value here to avoid the null problem?

2022-11-28 21:56 UTC, JeremyKuhne requested changes
Just a minor nit.

2022-11-28 21:56 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> +                        return prop;
You could make this `property` by getting rid of the other local or use a descriptive term like `existing`.

2022-11-29 18:40 UTC, JeremyKuhne approved these changes

2022-11-29 18:40 UTC, merged