Refactor KeysConverter to remove ArrayList
dotnet/winforms pull request #8255
Opened 2022-11-23 02:34 UTC by elachlan

Related #8140

2022-11-23 17:42 UTC, dreddy-work submitted a review, later dismissed

2022-11-28 09:33 UTC, halgab commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +                    List<string> termStrings = asString ? new() : null;
You could turn `termStrings` into a StringBuilder directly

2022-11-28 09:34 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +                    List<string> termStrings = asString ? new() : null;
I think it might be faster to do a string.join instead. I'll have to do a test.

2022-11-29 18:32 UTC, dreddy-work commented
@elachlan , multiple build failures here.
src\System.Windows.Forms\src\System\Windows\Forms\KeysConverter.cs(246,48): error CS8600: (NETCORE_ENGINEERING_TELEMETRY=Build) Converting null literal or possible null value to non-nullable type.

2022-11-29 19:25 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> -                    ArrayList terms = new ArrayList();
Build is complaining about possible null references. We can potentially do the following instead of avoid having to null check everywhere and avoid having two variables that essentially go through the same code:
``` c#
bool asString = destinationType == typeof(string);
bool asEnum = !asString && destinationType == typeof(Enum[]);
IList? terms = asString ? new List<string>() :
                asEnum ? new List<Enum>() : null;
if (terms is null)
{
    return base.ConvertTo(context, culture, value, destinationType);
}

// continue with rest of code..
```

though I am currently not sure if there are performance drawbacks with `IList`..

2022-11-29 22:23 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +            if (value is Keys or int)
```csharp
if (value is not Keys or not int)
{
    return base.ConvertTo(context, culture, value, destinationType);
}
```

I get the following warning:
```
Warning	CS8794	An expression of type 'object' always matches the provided pattern.
```

2022-11-30 02:02 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +            if (value is Keys or int)
If we invert we should get 
```c#
if (value is not Keys and not int)
{
    return base.ConvertTo(context, culture, value, destinationType);
}
```

Do you still get a warning with this?

2022-11-30 02:21 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> -                    ArrayList terms = new ArrayList();
I tried a few different things here, the current solution seems the most simple whilst keeping with generics. 

The option I didn't try was refactoring out the string vs enum solution into their own functions. I think that might be the best solution, since it would remove most of the branching.

2022-11-30 03:05 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> -                    ArrayList terms = new ArrayList();
I've pushed through a refactor using local functions, which simplifies the logic. but duplicates the code a bit.

2022-11-30 16:37 UTC, lonitra requested changes
Just a few comments, otherwise this is looking much cleaner! :)

2022-11-30 16:37 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +                if (added && asString)
Now that this is refactored into its own method I don't think checking `asString` is necessary anymore.
```suggestion
                if (added)
```

2022-11-30 16:37 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +                    if (((int)keyValue & (int)modifiers) != 0)
```suggestion
                    if (keyValue.HasFlag(modifiers))
```

2022-11-30 16:37 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +                    if (((int)keyValue & (int)modifiers) != 0)
```suggestion
                    if (keyValue.HasFlag(modifiers))
```

2022-11-30 18:15 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +                        added = true;
what is this assignment for?

2022-11-30 22:47 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +                        added = true;
I have removed it. It looked redundant.

2022-12-01 00:51 UTC, dreddy-work approved these changes

2022-12-01 09:38 UTC, halgab commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +                            termStrings.Append('+');
Isn't this equivalent to directly doing `termStrings.Append(keyString).Append('+')` on line 296 and removing the `added` logic entirely?

2022-12-01 09:59 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
> +                            termStrings.Append('+');
Good spot. It took me a bit, but it makes sense.

2022-12-01 17:06 UTC, merged