Refactor GetStandardValues implementations to remove ArrayList
dotnet/winforms pull request #8276
Opened 2022-11-24 00:41 UTC by elachlan

Related #8140

2022-11-28 22:10 UTC, JeremyKuhne requested changes
Just a few comments, otherwise looks good!

2022-11-28 22:10 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
> +                if (values[i] is object currentItem)
Consider inverting the if and continuing

2022-11-30 16:47 UTC, lonitra submitted a review, later dismissed
LGTM

2022-11-30 22:03 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
> +                if (values[i] is not object currentItem)
Its doing a pattern match so we don't have to index into the array again. It also continues to the next item if the item is null.

2022-11-30 22:14 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
> +                if (values[i] is not object currentItem)
I was walking over hierarchy and do not see an instance where you would be seeing null values inserted into `StandardCollection` . At most, it would be empty. Can you point me where that is happening? Otherwise, line 35 is sufficient here.

2022-11-30 22:20 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
> +                if (values[i] is not object currentItem)
It has a possibility of being null, which causes compile errors because of nullable reference types. This takes care of that possibility. The alternative is to use null forgiving operators.

2022-11-30 23:19 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
> +                if (values[i] is not object currentItem)
> It has a possibility of being null,

By definition, but in this scenario, it won't. I would add an assert and prevent adding to list if it is null at line 46. As per indexing, you can store it to local. Concern is, if there is ever a scenario where it could end up with null( i do not see any), it is altering existing behavior and proceeding silently.

2022-11-30 23:52 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
> +                if (values[i] is not object currentItem)
Is the whole point of an EnumConverter class to convert the values returned from GetStandardValues to the associated Enum?

Would that mean that the list should really be `List<Environment.SpecialFolder>`?

2022-12-01 00:49 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
> +                if (values[i] is not object currentItem)
Its internal and ideally, that may be the case but haven't checked all use cases here.

2022-12-01 00:50 UTC, dreddy-work approved these changes

2022-12-01 21:16 UTC, JeremyKuhne approved these changes

2022-12-01 21:16 UTC, merged