Convert Rest of Com Vtbls to New Pattern
dotnet/winforms pull request #8330
Opened 2022-12-05 19:35 UTC by lonitra

Follow up from #8311

- Convert `IDataSource`,`IDataSourceNotify`,`IDataObject`,`IEnumFORMATETC` to our new CCW pattern
- Add explicit conversion for `ComTypes.STGMEDIUM` and Cswin32 `STGMEDIUM`
- Implement the respective Cswin32 interfaces for our managed objects. 
   Note: 
    - `ComTypes.IDataObject` interface cannot be removed from `DataObject` due to it being a public class
    - `ComTypes.IEnumFORMATETC` interface cannot be removed from `FormatEnumerator` since it is used by `DataObject`
- Remove `EnumFORMATETCWrapper` 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8330)

2022-12-05 19:59 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +            if (pmedium is null)
what is the significance of `pmedium` check for null if this just being overridden on line 1064?

2022-12-05 20:02 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +            if (pmedium is null)
never mind. i see what is going.

2022-12-05 20:05 UTC, dreddy-work reviewed
LGTM

2022-12-06 01:02 UTC, JeremyKuhne requested changes
Nice!! A few questions, but mostly nits.

2022-12-06 01:02 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
> +                 && !grfKeyState.HasFlag(MODIFIERKEYS_FLAGS.MK_RBUTTON)
nit: indenting

2022-12-06 17:39 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
> +            try
Ah that's right! We do wrap this at the CCW level. Thanks!

2022-12-06 18:16 UTC, JeremyKuhne approved these changes
There are still a few files that have no break between the class and the namespace. Other than that looks great!

2022-12-06 19:56 UTC, JeremyKuhne approved these changes
❤️‍🔥

2022-12-06 20:55 UTC, merged