Enable nullability for TestUtilities Project
dotnet/winforms pull request #8331
Opened 2022-12-05 20:09 UTC by lonitra

Follow up to https://github.com/dotnet/winforms/pull/8251#discussion_r1030797441

2022-12-05 20:18 UTC, Tanya-Solyanik commented on src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
> +            Thread.CurrentThread.CurrentCulture = _originalCulture!;
Is it possible to put a [MemberNotNull](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.membernotnullattribute?view=net-7.0) attribute on the `Before` method instead of the `!`?

2022-12-05 20:38 UTC, dreddy-work commented on src/Common/tests/TestUtilities/CommonMemberDataAttribute.cs
> +        protected override object[]? ConvertDataItem(MethodInfo testMethod, object item)
and why item not marked nullable here?

2022-12-05 20:41 UTC, dreddy-work commented on src/Common/tests/TestUtilities/CommonTestHelper.cs
> +            var data = new TheoryData<string?>
as we are adapting following notion, you may want to make those changes as well for the lines/files your touch.
```suggestion
            TheoryData<string?>data = new
```

2022-12-05 22:59 UTC, RussKie commented on src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
> +        private CultureInfo? _originalUICulture;
I don't believe either of these can ever be null:
```cs
            _originalCulture = Thread.CurrentThread.CurrentCulture;
            _originalUICulture = Thread.CurrentThread.CurrentUICulture;
```
```suggestion
        private CultureInfo _originalCulture = null!;
        private CultureInfo _originalUICulture = null!;
```

2022-12-05 23:00 UTC, RussKie commented on src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
> +        private CultureInfo? _originalUICulture;
https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.currentuiculture?view=net-7.0#exceptions

2022-12-06 00:58 UTC, lonitra commented on src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
> +            Thread.CurrentThread.CurrentCulture = _originalCulture!;
I tried this and still ended up needing to put a `!` but I will go with [Igor's suggestion](https://github.com/dotnet/winforms/pull/8331#discussion_r1040191364) to get around the `!` here.

2022-12-06 00:58 UTC, lonitra commented on src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
> +        private CultureInfo? _originalUICulture;
Thank you! I wasn't quite sure the best way to get around the fact that these are not set in the constructor. It makes more sense that these do not have `?`

2022-12-06 01:16 UTC, JeremyKuhne requested changes
Yay! Only one non-nit comment.

2022-12-06 01:16 UTC, JeremyKuhne commented on src/Common/tests/TestUtilities/CustomConverter.cs
> +        if (type is null || converter is null)
nit: it's better to throw for which one is null, but that isn't critical as this is test code `ArgumentNullException.ThrowIfNull(type)`

2022-12-06 01:16 UTC, JeremyKuhne commented on src/Common/tests/TestUtilities/TestAccessor.cs
> +                            args is null ? Array.Empty<Type>() : args.Where(a => a is not null).Select(a => a!.GetType()).ToArray(),
The right answer here is to throw if any of the parameters is null- we don't want to match random signatures.

2022-12-06 01:16 UTC, JeremyKuhne commented on src/Common/tests/TestUtilities/TestAccessors.cs
> +            return testAccessor!;
Why does this need a bang after you checked it?

2022-12-06 01:16 UTC, JeremyKuhne commented on src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
> +        private CultureInfo _originalCulture = null!;
A comment would be good

2022-12-06 01:49 UTC, RussKie commented on src/Common/tests/TestUtilities/TestAccessors.cs
> +            ITestAccessor? testAccessor = instanceOrType is Type type
Looks like broken indentation

2022-12-06 18:22 UTC, JeremyKuhne commented on src/Common/tests/TestUtilities/TestAccessor.cs
> +                            args.Where(a => a is not null).Select(a => a!.GetType()).ToArray(),
You can't have the `Where` condition here.  We're trying to find a matching signature with `args.Length` arguments. So far we haven't hit a situation where we're trying to pass null to an overloaded method. When we do we'll have to make this more sophisticated to find a single match for all of the non-null arguments.

2022-12-06 19:55 UTC, JeremyKuhne approved these changes
🚀

2022-12-06 20:56 UTC, merged