Cache Top-level Window Form's size in PMV2 mode applications
dotnet/winforms pull request #8333
Opened 2022-12-06 02:10 UTC by dreddy-work

When `AutoScaleMode` is `Font`, for PMV2 mode applications, when top-level `Form` is moved from one monitor to the other with different DPI settings, we compute the new size based on the scale factor we compute for the `Font` on the new monitor. This sometimes, especially when the DPI setting on those monitors is not multiple of 100s, causes rounding issues in the size computations. Rounding issue gets worse when user move top-level `Form` between monitors multiple times. Caching size for the Form, prevents rounding issues in this scenario.

ToDo:  Before/After screenshots.

2022-12-06 04:19 UTC, elachlan commented
@dreddy-work flaky test?

2022-12-06 17:48 UTC, dreddy-work commented
> @dreddy-work flaky test?

Yep. Also, i am still working on it. Will reset when this is ready for review.

2022-12-06 23:04 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
> +        internal static void Initialize()
If you're only doing this for tests, use the TestAccessor.

2022-12-06 23:13 UTC, JeremyKuhne requested changes
Added a few comments

2022-12-06 23:13 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                    // AutoscaleMode is Font and/or Dpi. Especially after adding support for non-leaner Form size in PMv2.
```suggestion
                    // AutoscaleMode is Font and/or Dpi. Especially after adding support for non-linear Form size in PMv2.
```

2022-12-06 23:13 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
> +                    // AutoscaleFactor is not updated until after OnFontChanged event is raised. Hence, computing
```suggestion
                    // AutoscaleFactor is not updated until after the OnFontChanged event is raised. Hence, computing
```

2022-12-06 23:13 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        internal Dictionary<int, Size>? FormSizeCache;
`DpiFormSizes` would be clearer. And again, don't make things internal just for tests. Use the `TestAccessor`.

2022-12-06 23:13 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        private bool _clearFormSizeCache = true;
This would be much better tied to the scenario by `_inDpiChanged`, `_processingDpiChanged` or something similar.

2022-12-06 23:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                _clearFormSizeCache = true;
Should probably use a try finally to clear the flag.

2022-12-06 23:32 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        internal Dictionary<int, Size>? FormSizeCache;
[naming]
```suggestion
        internal Dictionary<int, Size>? _formSizeCache;
```

2022-12-06 23:32 UTC, RussKie commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +        // error in size calculations with float DPI factor and rounding it to nearest integer.
This can be reflowed to 120 chars.

2022-12-07 22:21 UTC, merged

2022-12-08 02:38 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                        _dpiFormSizes ??= new Dictionary<int, Size>();
This dictionary should be cleared if form's `AutoScaleMode` or Form's font is changed dynamically.

2022-12-08 18:22 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                        _dpiFormSizes ??= new Dictionary<int, Size>();
Thanks @Tanya-Solyanik. When do you expect `AutoScaleMode` change dynamically? That would break lot more things and i haven't come across any such scenario so far.

`FontChange `make sense. I will update it in the next PR.

2022-12-09 04:39 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> +                        _dpiFormSizes ??= new Dictionary<int, Size>();
>When do you expect AutoScaleMode change dynamically?

This is a public property, it can change any time.