Add Documentation For Registering Custom Type Converter
dotnet/winforms pull request #8340
Opened 2022-12-06 21:29 UTC by lonitra

Related: #8296

Getting this process documented in our repo for now. Eventually we may want these docs to be pushed up to the [TypeConverter docs](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter?view=net-7.0).

2022-12-06 23:36 UTC, RussKie reviewed
🎉

2022-12-06 23:36 UTC, RussKie commented on docs/serialization/register-custom-type-converter.md
> +Typically, a type converter is bound to a class by adding the [TypeConverterAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverterattribute?view=net-7.0) to the c
https://review.learn.microsoft.com/help/platform/links-how-to?branch=main#locale-codes-in-external-links
```suggestion
Typically, a type converter is bound to a class by adding the [TypeConverterAttribute](https://learn.microsoft.com/dotnet/api/system.componentmodel.typeconverterattribute) to the class. 
```

2022-12-06 23:36 UTC, RussKie commented on docs/serialization/register-custom-type-converter.md
> +and the object/type you want your custom converter to be associated with.
Please don't hard wrap sentences, it makes it harder to review and to make suggestions.

2022-12-07 01:40 UTC, RussKie commented on docs/serialization/register-custom-type-converter.md
> +A type converter is bound to a class by adding the [TypeConverterAttribute](https://learn.microsoft.com/dotnet/api/system.componentmodel.typeconverterattribute) to the class. However, there are some
May worth formatting all API like this:
```suggestion
A type converter is bound to a class by adding the [`TypeConverterAttribute`](https://learn.microsoft.com/dotnet/api/system.componentmodel.typeconverterattribute) to the class. However, there are some scenarios where it is not possible to add the attribute to the class. e.g., user may not own the class, but there is no type converter registered to that class for serialization. This document outlines how to manually register a [`TypeConverter`](https://learn.microsoft.com/dotnet/api/system.componentmodel.typeconverter) to a class for these scenarios.
```

2022-12-07 01:40 UTC, RussKie commented on docs/serialization/register-custom-type-converter.md
> +Note: The parent `TypeDescriptionProvider` to be passed to the constructor can be grabbed by calling [TypeDescriptor.GetProvider()]() and passing in the class that is intended to be associated to you
I suppose you missed this one: ![image](https://user-images.githubusercontent.com/4403806/206066457-4b36e590-da03-44ae-9af5-cb4c89b67df7.png)

2022-12-07 01:40 UTC, RussKie commented on docs/serialization/register-custom-type-converter.md
> +```
Nice!

I'm using https://sequencediagram.org/ and then exporting images from it.

2022-12-07 02:02 UTC, lonitra commented on docs/serialization/register-custom-type-converter.md
> +```
Thank you! Always coming in with great tips 🙏

2022-12-07 04:14 UTC, JeremyKuhne requested changes
Added some more comments.

2022-12-07 04:14 UTC, JeremyKuhne commented on docs/serialization/register-custom-type-converter.md
> +If you want this type converter to be temporarily registered to the class, do not forget to call [`TypeDescriptor.RemoveProvider()`](https://learn.microsoft.com/dotnet/api/system.componentmodel.typed
```suggestion
To restore the previous behavior call [`TypeDescriptor.RemoveProvider()`](https://learn.microsoft.com/dotnet/api/system.componentmodel.typedescriptor.removeprovider).
```

2022-12-07 04:14 UTC, JeremyKuhne commented on docs/serialization/register-custom-type-converter.md
> +    // MyCustomTypeConverterDescriptor code...
```suggestion
    // Consider nesting MyCustomTypeConverterDescriptor here
```

2022-12-07 04:14 UTC, JeremyKuhne commented on docs/serialization/register-custom-type-converter.md
> +public class MyTypeDescriptionProvider : TypeDescriptionProvider
I'd consider being more formal as this is usable as is. `CustomConverterProvider` perhaps. Likewise for the class above `CustomConverterDescriptor`. (That way it can be copy / pasted.)

2022-12-08 00:41 UTC, JeremyKuhne commented on docs/serialization/register-custom-type-converter.md
> +```mermaid
Love this!

2022-12-14 19:43 UTC, JeremyKuhne approved these changes
Looks good to me.

2022-12-14 20:52 UTC, merriemcgaw approved these changes
Looks good. Easy to follow and I liked the diagram tremendously.

2022-12-15 22:08 UTC, merged