Refactor Com2IManagedPerPropertyBrowsingHandler to replace ArrayList with List<Atrribute>
dotnet/winforms pull request #8365
Opened 2022-12-11 17:08 UTC by Jericho

Related: #8140

2022-12-12 19:02 UTC, JeremyKuhne commented
> I believe @JeremyKuhne is working on some Com2 stuff and wanted that namespace left alone for a bit.

That is true, both Com2 and AxHost related things should be avoided for now. I'll review this one, but please hold off on any cleanup in those types.

2022-12-12 19:03 UTC, Jericho commented
Sorry about that. I wasn't aware.

2022-12-12 19:09 UTC, JeremyKuhne requested changes
One minor comment

2022-12-12 19:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                            if (fieldValue is Attribute fva)
You should collapse these and please stay away from abbreviations. `if (fi.GetValue(null) is Attribute attribute)`

2022-12-12 19:15 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                            if (fieldValue is Attribute fva)
Sure

2022-12-12 21:04 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                        if (attr is not null) attrs.Add(attr);
Line 198 to 200 - > attrs.ToArray()

2022-12-13 16:31 UTC, Jericho commented on src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
> +                        if (attr is not null) attrs.Add(attr);
Done.

2022-12-13 18:04 UTC, dreddy-work approved these changes

2022-12-14 19:23 UTC, JeremyKuhne approved these changes
:shipit:

2022-12-14 19:23 UTC, merged