Enable Nullability in `ImageListImageEditor`
dotnet/winforms pull request #8390
Opened 2022-12-15 09:09 UTC by elachlan

Related: #8342

2022-12-19 22:17 UTC, elachlan commented on src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
> +virtual System.Drawing.Design.ImageEditor.LoadFromStream(System.IO.Stream! stream) -> System.Drawing.Image!
`LoadFromStream` does a null check `ArgumentNullException.ThrowIfNull(stream);`. I am unsure what to do with the annotation here?

2022-12-19 22:19 UTC, elachlan commented on src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
> +virtual System.Drawing.Design.ImageEditor.LoadFromStream(System.IO.Stream! stream) -> System.Drawing.Image!
Remembered I got told about this before:
> They stay annotated as not-null and we leave the null check in place. Being annotated as not-null doesn't change behavior at run-time, so the null check is there to validate null isn't being passed in, just as before.

https://github.com/dotnet/runtime/pull/79429#discussion_r1044033195

2022-12-21 23:54 UTC, elachlan commented
@lonitra I think the test failures are unrelated?

2022-12-22 18:10 UTC, lonitra requested changes

2022-12-22 18:10 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs
> +            string? extensions = CreateExtensionsString(editor.GetExtensions(), ",");
I think there is some inconsistency here. The first parameter in `CreateExtensionsString()` is nullable, but it looks like every time `CreateExtensionsString()` is called we are passing in the return value of `GetExtensions()` which is currently nonnullable. Could you verify whether or not `GetExtensions()` ever returns a `null` value and adjust accordingly?

2022-12-22 22:34 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs
> +            string? extensions = CreateExtensionsString(editor.GetExtensions(), ",");
`GetExtensions` always returns a non-null value. `CreateExtensionsString` is `protected` so it is externally accessible. So a null value is possible. 

I've removed the nullability annotations on `CreateExtensionsString` parameter `extensions`. I think its best to let the user know that we expect a value. Since if you pass null, we return null.

2023-01-05 22:48 UTC, elachlan commented on src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs
> +            string? extensions = CreateExtensionsString(editor.GetExtensions(), ",");
I think I might have been wrong here. In a stricter sense, if we throw a `ArguementNullException` or `ArguementException`, then it would make more sense to annotate that we don't want nulls. But because we handle it in code, I think we should have the nullability.

I think the idea is that if a null input is going to cause an error or invalid state, then we annotate it not null. This isn't the case here.

2023-01-05 22:55 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs
> +            string? extensions = CreateExtensionsString(editor.GetExtensions(), ",");
Correct, while we like to make it explicit with respect to nullability, in this case, we are handling null values and it's been exposed publicly. We should mark it nullable for compatibility even when we internally never pass null. Our documentation is also doesn't enforce this.

2023-01-05 22:57 UTC, dreddy-work approved these changes

2023-01-05 23:30 UTC, elachlan commented
I rebased due to a clash. Apologies for that. The last commit is really the only change.

2023-01-06 18:06 UTC, dreddy-work approved these changes

2023-01-06 18:07 UTC, merged