Enable nullability in Formatter
dotnet/winforms pull request #8435
Opened 2022-12-29 09:05 UTC by gpetrou

## Proposed changes

- Enable nullability in Formatter.

2023-01-04 01:57 UTC, dreddy-work requested changes

2023-01-04 01:57 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(null, GetFormatterCulture(formatInfo), value!);
param names where constants/nulls passed. 

Also, you could check for value being bull as well on line 280 and avoid `!` here.

2023-01-04 01:57 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(null, GetFormatterCulture(formatInfo), value!);
param names for `null` . We have multiple instances like this in this file.

2023-01-04 01:57 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                MethodInfo? mi = targetType.GetMethod(
mi => methodInfo

2023-01-04 01:57 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                throw new FormatException(ex.InnerException!.Message, ex.InnerException);
I do not see any reason why we can not make this change here. 

```suggestion
                throw new FormatException(ex.InnerException?.Message, ex.InnerException);
```

2023-01-04 19:38 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(null, GetFormatterCulture(formatInfo), value!);
@gpetrou , you missed this suggestion?

2023-01-04 19:48 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +            if (EqualsFormattedNullValue(value, formattedNullValue, formatInfo) || value == DBNull.Value)
Checking `value` to null in this block make sense based on description and remove `!` from rest of the instances.  @Tanya-Solyanik / @KlausLoeffelmann any suggestions here?

2023-01-04 19:50 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(context: null, GetFormatterCulture(formatInfo), value!);
Based on my understanding of the code, it seems that it is possible for the value to be null in this situation, which supports the reasoning for the change i proposed above..

2023-01-04 20:23 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +            if (EqualsFormattedNullValue(value, formattedNullValue, formatInfo) || value == DBNull.Value)
Only if `formattedNullValue` is null.

2023-01-04 20:29 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(context: null, GetFormatterCulture(formatInfo), value!);
The way I understand it is: We're parsing `value`, which could be any representation which would lead to `dbNull`, so I guess that also includes a "real" `null`. In that case, we're indeed returning `dbNull` - so at this point every `null`, `""`, `"{NULL}"` case (I am making the null-versions up for an easier explanation) has been handled. Since we are not changing the type of the variable just because of its nullability, I'd assume a) `value` cannot be `null` at this point and b) using `!` in this context is one of the cases where we have `!` for.

2023-01-04 21:03 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(context: null, GetFormatterCulture(formatInfo), value!);
> so I guess that also includes a "real" `null`. In that case, we're indeed returning `dbNull` - so at this point every `null`, `""`, `"{NULL}"` case (I am making the null-versions up for an easier explanation) has been handled

Based on `null` check on line 330, i assumed it is possible for `value ` to be null here. Where do you see `value ` being `null` handled? Are you referring to callers?

2023-01-04 22:25 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(context: null, GetFormatterCulture(formatInfo), value!);
I wasn't, but that should be checked. Correct, the "real" `null` isn't checked at that point. The question is, would `null` ever been passed, but then again if that is the case, we wouldn't need nullability for `value` in that signature to begin with.

2023-01-04 23:08 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(context: null, GetFormatterCulture(formatInfo), value!);
I have noticed that there is at least one situation where a `null `value (in a `DataGridViewCell`) may be passed. I am not sure if it is safe to return dbNull if the value is `null`. @Tanya-Solyanik ?

2023-01-04 23:45 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(null, GetFormatterCulture(formatInfo), value!);
@Youssef1313 sorry to ping you all the time, but do you know of an analyzer for using a parameter name when the value is null?

2023-01-05 01:03 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
>          ///  - Throws a FormatException is no suitable conversion can be found
```suggestion
        ///  - Throws a FormatException if no suitable conversion can be found
```

2023-01-05 01:13 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +            if (EqualsFormattedNullValue(value, formattedNullValue, formatInfo) || value == DBNull.Value)
Hm, `value==null` means that value had not been entered, not that a `null` value had been entered...

2023-01-05 01:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +            if (EqualsFormattedNullValue(value, formattedNullValue, formatInfo) || value == DBNull.Value)
Before these changes `value==null` was processed by the type converter or resulted in a FormatException. I don't think that returning DBNull.Value is accurate.

2023-01-05 01:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(context: null, GetFormatterCulture(formatInfo), value!);
I'm not sure that it's correct that TypeConverter does not accept a `null` value in ConvertFrom but accepts it in  ConvertTo.

2023-01-05 01:32 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(context: null, GetFormatterCulture(formatInfo), value!);
I don't think we should return dbNull in the case of `value==null`.  Nor should we skip TypeConverter - it could be user-defined and it could handle nulls. It's unfortunate that the runtime team already marked ConvertFrom as not taking nulls. I think it's appropriate to throw an exception inthis case in the `Parse...` method as this should be something that developer finds while porting the app.

2023-01-05 10:10 UTC, Youssef1313 commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(null, GetFormatterCulture(formatInfo), value!);
@elachlan https://github.com/dotnet/roslyn/issues/43988

2023-01-10 18:47 UTC, dreddy-work approved these changes

2023-01-10 20:16 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
> +                return targetConverter.ConvertFrom(null, GetFormatterCulture(formatInfo), value!);
I would, but the analyzer hasn't been written yet. I'll add it once it's been written.

2023-01-11 18:33 UTC, merged