Removed DefaultValue attribute from the RowTemplate.Height property
dotnet/winforms pull request #8474
Opened 2023-01-09 16:59 UTC by dkazennov

Fixes #4461

## Proposed changes

- Introduces a new private property `DefaultHeight` with **the intended value** (by default in Winforms Control.DefaultFont is **Segoe UI, Size 9, Height 16** which gives us **default Row height = 25**).
- Removes the DefaultValue attribute from the `DataGridViewRow.Height` property;
- Implements `ResetHeight` and `ShouldSerializeHeight` methods ([see more](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods?view=netframeworkdesktop-4.8)).
- The `DataGridViewRow.Height` property still returns the value of the  `Thickness` property.
- Existing unit tests weren't changed.
- New unit test `DataGridViewRow_Height_NotEqualDefaultHeight_IfDefaultFontIsChanged` is added.

## Customer Impact

- Fixes the Issue which impacts user experience,  breaks DPI and Font scaling. For the _newly created_ control at 100% scaling, designer should generate the same value as is defined by the Default. There is no extra code.

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before

![image](https://user-images.githubusercontent.com/15823268/104521807-77f4be80-55b2-11eb-9f38-b7e32eff005d.png)

### After

![image](https://user-images.githubusercontent.com/15823268/104521910-b5f1e280-55b2-11eb-804e-5a05b8b8a195.png)

## Test methodology

- Manual (Issue can be tested via substitution of dlls, complete restart of the VS recommended)
- Unit test

 

## Test environment(s) 

- dotnet 8.0.100-alpha.1.22607.6

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8474)

2023-01-09 17:03 UTC, dkazennov commented
If this approach suits us we can fix https://github.com/dotnet/winforms/issues/4463 the same way.

2023-01-09 22:43 UTC, merriemcgaw requested changes

2023-01-09 22:43 UTC, merriemcgaw commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 22;
Is this 22 the old default height from Framework, or is it taking into consideration the new default font and the height that should be associated with that?

2023-01-10 09:22 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 22;
> Is this 22 the old default height from Framework, or is it taking into consideration the new default font and the height that should be associated with that?

This is default value which was hardcoded in the DefaultValue attribute. Given Issue description and the way to fix the similar problem proposed by @RussKie I thought we need to preserve this value as a private constant and avoid rely on default font height.

2023-01-10 16:28 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 22;
I would go with 25 to keep the appropriate height for current font and to not change .NET Core+ apps which already had the default height as 25. And also I'm not sure that using a fixed value is the best approach, because if there is a [custom DefaultFont](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#applicationdefaultfont), then current implementation would adjust height accordingly, but with this change it'd break and require setting a new height.

2023-01-11 08:19 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 22;
> I would go with 25 to keep the appropriate height for current font and to not change .NET Core+ apps which already had the default height as 25. And also I'm not sure that using a fixed value is the best approach, because if there is a [custom DefaultFont](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#applicationdefaultfont), then current implementation would adjust height accordingly, but with this change it'd break and require setting a new height.

Yes, indeed. But there are also some other problems here.
Existing realization uses DataGridViewBand.Thickness as a value for DataGridViewRow.Height, and DataGridViewBand.Thickness (the property of the base class) has complex set and get logic.  This is why 21 unit tests failed with this fix.

2023-01-11 09:49 UTC, dkazennov commented
This issue raises the question : should we even made the Height property of the DVG row a constant as @RussKie [proposed](https://github.com/dotnet/winforms/issues/4463#issuecomment-768831519) or should we stick to font height value? 
Given the task in the Issue I believed we should made the Property value to be equal the constant by default.

Failing unit tests made me believe that instead of changing the DataGridViewRow.Height we should probably change DataGridViewBand.Thickness (but this will affect many other components of DataGridView I'm afraid).

2023-01-15 18:52 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 22;
> I would go with 25 to keep the appropriate height for current font and to not change .NET Core+ apps which already had the default height as 25. And also I'm not sure that using a fixed value is the best approach, because if there is a [custom DefaultFont](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#applicationdefaultfont), then current implementation would adjust height accordingly, but with this change it'd break and require setting a new height.

The Control.DefaultFont is either Application.DefaultFont or SystemFonts.MessageBoxFont. I have Application.DefaultFont "Calibri" (Size=11 & **Height = 23**), so in my case DataGridViewBand.Thickness should be 32. The Idea with private constant value in a similar situation was initially proposed by @RussKie [here](https://github.com/dotnet/winforms/issues/4463#issuecomment-768831519). 

What bothers me here is the value returned (by Application.DefaultFont) will vary depending on the user's operating system the local culture setting of their system.

2023-01-17 14:13 UTC, dkazennov commented
This way we:
1) check for changes in Control.DefaultFont.Height;
2) get rid of extra code as intended by the issue;
3) all unit tests passes (therefore we make sure the Height has indented value);

This may looks not exactly the perfect solutions but it is best we can get - as @RussKie [pointed out](https://github.com/dotnet/winforms/issues/4463#issuecomment-768831519).

2023-01-17 17:24 UTC, dmitrii-drobotov reviewed
Looks good!

2023-01-17 17:24 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            return _height != DefaultHeight;
Can it be just `Height != DefaultHeight;`? That way `_height` variable could be removed.

2023-01-17 17:24 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private void ResetHeight()
Since this is a private method without any explicit usages, I think someone could remove it by mistake. Consider adding a comment that this method is used by the designer via reflection. And the same for `ShouldSerializeHeight`

2023-01-17 18:40 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            return _height != DefaultHeight;
> Can it be just `Height != DefaultHeight;`? That way `_height` variable could be removed.

The trick here is that without this assignment 

> Can it be just `Height != DefaultHeight;`? That way `_height` variable could be removed.

The trick here is that without this assignment there would be extra code `dataGridView1.RowTemplate.Height`

2023-01-18 10:29 UTC, dkazennov commented
Some builds in the pipeline has faulty tests (and those tests have nothing to do with this fix or the `DataGridViewRow.Height` property in particular):

    DataGridView_ColumnHeadersHeight_SetWithHandle_GetReturnsExpected
    DataGridView_ColumnHeadersHeight_SetWithParentWithHandle_GetReturnsExpected
    DataGridView_RowHeadersWidthSizeMode_SetWithHandle_GetReturnsExpected
    DataGridView_ColumnHeadersHeightSizeMode_SetNonResizeThenResize_RestoresOldValue
    DataGridView_RowHeadersWidthSizeMode_SetNonResizeThenResize_RestoresOldValue
    
According to [Runfo application](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E100+definition%3A76+name%3AataGridView_ColumnHeadersHeight_SetWithHandle_GetReturnsExpected) those tests fail in different PRs like #8500

I'll do rebase for Issue_4461_ExtraCode_RowTemplateHeight on the most recent main to see if it fixes the issue.

2023-01-18 14:09 UTC, dmitrii-drobotov reviewed
LGTM! Can you also add unit tests, so that if the default font changes in the future, we would notice it?

2023-01-19 07:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            Height = Control.DefaultFont.Height + 9 == DefaultHeight ? DefaultHeight : Thickness;
```suggestion
            Height = Thickness;
```

2023-01-19 07:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 22;
>because if there is a [custom DefaultFont](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#applicationdefaultfont), then current implementation would adjust height accordingly, but with this change it'd break and require setting a new height.

@dkazennov  - had you investigated this idea? It would handle the case when control is defined in the library were default font is not modified and used in an all with a custom default font.

2023-01-19 07:34 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            Height = DefaultHeight;
This implementation runs the same logic as  `[DefaultValue(25)]` would had run, i.e. a comparison with a constant. Dynamic methods had an advantage if you adjust `DefaultValue` according to DPI and custom default font. @dreddy-work  -is default font adjusted for the DPI?

2023-01-19 07:37 UTC, Tanya-Solyanik commented
Unit test that compares `DefaultHeight` field to the actual app default font height(with appropriate adjustments) would be nice.

2023-01-19 19:23 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            Height = DefaultHeight;
Default Font if it is not SystemFont, is scaled to DPI settings on primary monitor. But it is not updated at runtime when moving between monitors.

2023-01-20 08:27 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            Height = Control.DefaultFont.Height + 9 == DefaultHeight ? DefaultHeight : Thickness;
@Tanya-Solyanik 
> isn't this condition equivalent to -

If (Control.DefaultFont.Height + 9 == DefaultHeight) then the default font is not changed.
This way we can use the constant DefaultHeight.

But if (Control.DefaultFont.Height + 9 != DefaultHeight) then the default font is changed and so we should use Thickness (as was before this fix).

2023-01-20 09:04 UTC, dkazennov commented
> Unit test that compares `DefaultHeight` field to the actual app default font height(with appropriate adjustments) would be nice.

Yes! I will make tests to cover this fix as @dmitrii-drobotov also proposed.

2023-01-20 09:11 UTC, dkazennov commented
@Tanya-Solyanik 
Regarding custom default font and `Height = Control.DefaultFont.Height + 9 == DefaultHeight ? DefaultHeight : Thickness;`
In WinformsControlsTest application we have custom default font of Calibri-11 with height 23. So Height and Thickness are 32 instead on 25.

![image](https://user-images.githubusercontent.com/102961955/213657312-292d5120-44df-4b57-8341-752cc9d7f3a6.png)

2023-01-20 09:39 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            Height = Control.DefaultFont.Height + 9 == DefaultHeight ? DefaultHeight : Thickness;
> isn't this condition equivalent to -

Yes, you are correct. I'm not getting anything by adding this assignment.

2023-01-20 20:55 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 25;
I would investigate into this direction:

private int DefaultFont
{
    return Control.DefaultFont.Height + 9;
}

2023-01-20 21:21 UTC, Tanya-Solyanik commented
>In WinformsControlsTest application we have custom default font of Calibri-11 with height 23. So Height and Thickness are 32 instead on 25.

I think that row height value of 32 should not be serialized in this case, is it?

2023-01-23 09:58 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 25;
This way the unit test implemented earlier fails (since in is designer to make sure that custom default font's height is not equal to the constant AND that actual row height is equal to Control.DefaultFont.Height + 9). 

I believed that we should stick to the initial idea of the fix which works as far as I understand. Or if there is something wrong with the current fix?

2023-01-23 13:18 UTC, dkazennov commented
Builds fail because new unit test. But it passes locally both in Test Explorer and with cmd script replicating CI\CD builds.
The fix with the property instead of the constant seems to work as well (with a unit test changed). I will commit changed code and see if the test will pass or fail.

2023-01-23 14:11 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 25;
> I would investigate into this direction:
> 
> private int DefaultHeight { return Control.DefaultFont.Height + 9; } This way height serialized for one DefaultFont will pick up a different default font at runtime.

Actually this works too and looks more consistent than the initial idea.
I've changed the PR and adjusted the unit tests as well.

2023-01-23 14:21 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs
> +            applicationTestAccessor.s_defaultFont = new Font("Times New Roman", 12);
Can `Application.SetDefaultFont` be used here instead?

2023-01-23 14:31 UTC, dkazennov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs
> +            applicationTestAccessor.s_defaultFont = new Font("Times New Roman", 12);
> Can `Application.SetDefaultFont` be used here instead?

It gives `SetDefaultFont must be called before the first IWin32Window object is created in the application.` which is probably why TestAccessor is being used in all similar cases.

2023-01-23 20:46 UTC, Tanya-Solyanik submitted a review, later dismissed

2023-01-24 07:34 UTC, NikitaSemenovAkvelon commented
Is the default value should be recalculated if `DefaultCellStyle.Font` is changed?
![image](https://user-images.githubusercontent.com/109065597/214235418-85f53355-4f1d-40c8-934c-c1b5518e606b.png)
![image](https://user-images.githubusercontent.com/109065597/214235492-0a81d4be-04b7-4606-a6cc-c92499512c43.png)

2023-01-24 07:40 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            get => Control.DefaultFont.Height + 9;
In line 37, `Thickness` is set to the same value `Control.DefaultFont.Height + 9`. I suggest replacing it with `DefaultHeight`.

2023-01-24 07:40 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            get => Control.DefaultFont.Height + 9;
I would like to move `9` to a `const` with an appropriate name. Now, at least for me, it seems like a magic value.

2023-01-24 11:04 UTC, dkazennov commented
> Is the default value should be recalculated if `DefaultCellStyle.Font` is changed?
In the most recent revision we don't recalculate the value. We use a property instead of a constant, so we always have the actual value.

2023-01-24 11:33 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            get => Control.DefaultFont.Height + 9;
> I would like to move `9` to a `const` with an appropriate name. Now, at least for me, it seems like a magic value.

It looks like a loop. We add a property (or a constant) to store some value. Then we add a constant to store the addendum value.

2023-01-24 11:52 UTC, NikitaSemenovAkvelon commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            get => Control.DefaultFont.Height + 9;
In my humble opinion, it is still better than a magic value

2023-01-24 12:59 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            get => Control.DefaultFont.Height + 9;
We have to store a literal value one way or another. We don't have any kind of enum with offset constants, but we now have the new property DefaultHeight which already serves exactly this purpose. I believe it is fine to use DefaultHeight to store the value.

2023-01-24 17:49 UTC, dmitrii-drobotov approved these changes
LGTM

2023-02-01 07:33 UTC, dkazennov commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +        private const int DefaultHeight = 22;
This marked as resolved for now the DefaultHeight property has no constant value. It depends on the actual Control.DefaultFont.Height.

2023-02-01 09:31 UTC, dkazennov commented
@merriemcgaw could you please approve this PR regarding the changes you have requested? (Since then this fix have changed quite a lot).

2023-02-02 01:11 UTC, merriemcgaw approved these changes
Approving to unblock merging based on the new approach.

2023-02-03 18:31 UTC, dreddy-work commented
@Tanya-Solyanik, can you take a final look at this?

2023-02-05 22:56 UTC, Tanya-Solyanik commented
>@Tanya-Solyanik, can you take a final look at this?

@dreddy-work - I want to discuss this pattern with the team. Attribute removal is a breaking change - https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#attributes. But I consider this case a `grey area` because functionality is preserved.

2023-02-06 22:54 UTC, merriemcgaw commented
@Tanya-Solyanik, @dreddy-work Let's put this on the agenda for tomorrow's meeting.

2023-02-09 18:22 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> +            get => Control.DefaultFont.Height + 9;
Please store the height in a static field in the same way as you did in the list box PR.

2023-02-10 01:21 UTC, Tanya-Solyanik commented
breaking change doc that covers all attributes removals that follow this pattern - https://github.com/dotnet/docs/issues/33954

2023-02-24 06:57 UTC, Tanya-Solyanik approved these changes
Thank you!

2023-02-24 06:58 UTC, merged

2023-03-02 20:02 UTC, Tanya-Solyanik commented
@Nora-Zhou01  - yes, this is expected because we had changed the font height in .NET