Prevent disposing Icons that are not owned by the caller.
dotnet/winforms pull request #8618
Opened 2023-02-10 19:48 UTC by dreddy-work

We regressed this issue here: https://github.com/dotnet/winforms/pull/8486.

by accidentally disposing Icons that may not be owned or created by us. In this scenario, It was default Icon that is getting disposed.

Added unit test.

2023-02-10 19:49 UTC, dreddy-work commented
@Olina-Zhang, can you please run some scenarios here apart from the repro app to make sure we are not regressing anything else?

@elachlan as FYI.

2023-02-10 20:03 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            Assert.Equal(handle, Icon.Handle);
Had this failed before your fix?

2023-02-10 20:05 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            var Icon = provider.Icon;
This is hard to read with the casing wrong.

```suggestion
            var icon = provider.Icon;
```

2023-02-10 20:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            provider.Icon = new Icon(typeof(ErrorProvider), "Error");
The new Icon should be disposed when you're done with it.

2023-02-10 20:10 UTC, JeremyKuhne requested changes
A few minor things in the test.

2023-02-10 20:38 UTC, lonitra commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            var Icon = provider.Icon;
Do we need using statement here? Doesn't seem like the old icon is getting disposed at end of test.

2023-02-10 20:50 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            Assert.Equal(handle, Icon.Handle);
Yes. Accessing Icon.Handle throw `ObjectDisposedException`

2023-02-10 20:51 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
> -                _icon.Dispose();
`_icon` is assigned with `DefaultIcon` initially which is owned by WinForms. Subsequent changes to public property  `Icon` should be owned by caller (user).

2023-02-10 20:59 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            var Icon = provider.Icon;
Not on this one but the one we are creating in this test. This one is default Icon.

2023-02-10 21:01 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using var provider = new SubErrorProvider();
are you referring to `SubErrorProvider`? I will have to check what all it does to come up with right name but that could be outside of this PR.

2023-02-10 21:37 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            Assert.Equal(handle, Icon.Handle);
So this test is not about equality, but about  the Handle property being set to something.

2023-02-10 21:39 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            Assert.Equal(handle, Icon.Handle);
Yes. Checking Handle to `null` or `zero` is ideal but Handle accessor on Icon throws exception if it was `null` or `zero`. So, I went this route.

2023-02-10 22:07 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using var provider = new SubErrorProvider();
If you don't need something specific from `SubErrorProvider` you should just use `ErrorProvider`. That makes intent and dependencies much clearer.

2023-02-10 22:07 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
This constructor is accessing a winforms resource that might be accessed at the same time (this assembly runs tests in parallel) by another test. Is it possible to create an in-memory icon?

2023-02-12 00:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
Sorry, I meant something like this:
```
            using Bitmap bitmap = new(16, 16);
            using Graphics graphics = Graphics.FromImage(bitmap);
            Rectangle rectangle = new(new Point(1, 1), new Size(14, 14));
            using SolidBrush brush = new(Color.Blue);
            graphics.FillRectangle(brush, rectangle);
            Icon icon = Icon.FromHandle(bitmap.GetHicon());
```

2023-02-12 20:12 UTC, KlausLoeffelmann commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            // Make sure old icon that is not owned by us, is not disposed
```suggestion
            // Make sure the old icon that is not owned by us, is not disposed
```

2023-02-13 03:17 UTC, Olina-Zhang commented
@dreddy-work, Tested this PR for GH issue: [8513](https://github.com/dotnet/winforms/issues/8513), it is fixed: the automation case about ErrorProvider passed now, and tested following scenarios manually, no new issue found.
![image](https://user-images.githubusercontent.com/26474449/218362638-d138a3a8-2875-44da-9691-e957e7fd98c1.png)

2023-02-13 17:39 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
That could work but I am using one of the existing Icons in this case. For reading is `Open|Shared` so shouldn't be a problem. Leving as-is.

2023-02-13 19:03 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
>For reading is Open|Shared so shouldn't be a problem.

What do you mean by open or shared?

2023-02-13 19:05 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
Ico file used in this test is open in those modes for reading. So, even if other test running in parallel and accessing, it shouldn't be an issue.

2023-02-13 19:11 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
Could you please share the code pointer? Is it really loaded from the file each time the icon is accessed?

2023-02-13 19:15 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
Here is the code that read Icon from file.  It is read only when the Icon is created. https://github.com/dotnet/runtime/blob/52fea7fb9fdc4a80ae5f1646b8461bb6545ab563/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Windows.cs#L65

2023-02-13 19:26 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
I think you are using this constructor - https://github.com/dotnet/runtime/blob/52fea7fb9fdc4a80ae5f1646b8461bb6545ab563/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Windows.cs#L99

We don't ship icons as stand alone files, we embed them into the winforms assembly. I don't see in docs if GetManifestResource supports concurrent read.

2023-02-13 19:30 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
I am confused. Are you referring to latest change? I am using following file to read Icon from.

"bitmaps/10x16_one_entry_32bit.ico"

2023-02-13 19:33 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
> +            using Icon newIcon = new (typeof(ErrorProvider), "Error");
Ah, you are right!

2023-02-13 19:43 UTC, Tanya-Solyanik approved these changes

2023-02-13 19:44 UTC, merged