[Test] Disable parallel mode for test collections.
dotnet/winforms pull request #8772
Opened 2023-03-09 19:40 UTC by dreddy-work

No review required.

Testing theory for disabling test collection parallelism fixing flaky tests.

2023-03-11 06:44 UTC, RussKie commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/xunit.runner.json
> +﻿{
If these are all the same, then you should be able to reuse it and include it via the MSBuild plumbing.

2023-03-11 06:48 UTC, dreddy-work commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/xunit.runner.json
> +﻿{
i have not thought about it yet. Just experimenting few things. Will have to check.

2023-03-11 07:07 UTC, dreddy-work commented
vsplit.cur and hsplit.cur are consistent in resulting disposed handle ( or handle may never be created).

2023-03-11 20:09 UTC, dreddy-work commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/xunit.runner.json
> +﻿{
@RussKie, can you give me pointers on how we can do this into MSbuild action or steps?

2023-03-13 03:52 UTC, RussKie commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/xunit.runner.json
> +﻿{
Looking through the Arcade code, I believe you need to use `XUnitDesktopSettingsFile` property:
https://github.com/dotnet/arcade/blob/cb64095ec45ac34378a1a26db9932a3b561f9e4e/src/Microsoft.DotNet.Arcade.Sdk/tools/XUnit/XUnit.targets#L19

```diff
diff --git a/Directory.Build.props b/Directory.Build.props
index 290e10e19..90b5829db 100644
--- a/Directory.Build.props
+++ b/Directory.Build.props
@@ -46,6 +46,13 @@
     <DefineConstants>WINFORMS_ANALYZERS</DefineConstants>
   </PropertyGroup>
 
+  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
+    <XUnitDesktopSettingsFile>$(RepositoryEngineeringDir)xunit.runner.parallelize.json</XUnitDesktopSettingsFile>
+  </PropertyGroup>
+  <PropertyGroup Condition="'$(IsIntegrationTestProject)' == 'true'">
+    <XUnitDesktopSettingsFile>$(RepositoryEngineeringDir)xunit.runner.nonparallelize.json</XUnitDesktopSettingsFile>
+  </PropertyGroup>
+
   <!-- SDK flipped to 'true' by default https://github.com/dotnet/sdk/pull/12720 -->
   <PropertyGroup>
     <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
```

Here's a patch file: [0001-.patch](https://github.com/dotnet/winforms/files/10953266/0001-.patch)

2023-03-13 04:11 UTC, RussKie commented on src/Microsoft.VisualBasic.Forms/tests/UnitTests/xunit.runner.json
> +﻿{
If XUnit Console doesn't like the custom names, then you can consider putting different versions under different folders, e.g.:
```
/eng
  /xunit.nonparallelized
    xunit.runner.json
  /xunit.nparallelized
    xunit.runner.json
```
...and then reference those:
```xml
  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <XUnitCoreSettingsFile>$(RepositoryEngineeringDir)xunit.parallelized/xunit.runner.json</XUnitCoreSettingsFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsIntegrationTestProject)' == 'true'">
    <XUnitCoreSettingsFile>$(RepositoryEngineeringDir)xunit.nonparallelized/xunit.runner.json</XUnitCoreSettingsFile>
  </PropertyGroup>
```

2023-03-13 18:20 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
> +                    inputSimulator => inputSimulator.Mouse.LeftButtonClick().Sleep(INPUTSIMULATOR_DELAY));
Could you please explain how InputSimulator works? After we awaited for the SendAsync method, and got to line 47, does it mean that the left click had been inserted into the input stream?
I feel uncomfortable about a delay, who knows if it's enough, and I really don't want these tests to run longer than 10 min per leg. I'd rather moved validation to the point when we know that the form cloased. We could restructure the test runner to accept 3 callbacks - setup(where we create the form and add the button), action (click the button) and validation that happens after `ShowDialog` exits,

2023-03-13 18:31 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
> +                    inputSimulator => inputSimulator.Mouse.LeftButtonClick().Sleep(INPUTSIMULATOR_DELAY));
@JeremyKuhne is going to look into replacement for InputSimulator. This is a temporary solution until then.

> After we awaited for the SendAsync method, and got to line 47, does it mean that the left click had been inserted into the input stream?

That is my understanding. Delay i am experimenting is to make sure that input is cleared, and actions are performed before we move to validations. Running tests multiple times still not guarantee success.

2023-03-13 18:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
> +                    inputSimulator => inputSimulator.Mouse.LeftButtonClick().Sleep(INPUTSIMULATOR_DELAY));
@dreddy-work The thing that _might_ be missing in the helper code is a `DoEvents()` to clear the message queue. Have you tried checking for / adding that?

2023-03-13 19:21 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
> +                    inputSimulator => inputSimulator.Mouse.LeftButtonClick().Sleep(INPUTSIMULATOR_DELAY));
Our helper did not have it. Will experiment that in next commit.

2023-03-13 20:01 UTC, dreddy-work commented
Experiment with `DoEvents()` instead of sleep/delay.

2023-03-13 20:58 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
> +                    inputSimulator => inputSimulator.Mouse.LeftButtonClick().Sleep(INPUTSIMULATOR_DELAY));
It seems `DoEvents` might help in some cases but doesn't fix all cases.  There may still be instances where user input is cleared but the resulting events triggered by the input may not have been fully processed or propagated. 

An example of this is when the user clicks on a checkbox using the mouse and expects the state change to reflect on the checkbox.

2023-03-13 22:07 UTC, dreddy-work commented
/azp run

2023-03-13 22:52 UTC, dreddy-work commented
/azp run

2023-03-14 01:18 UTC, RussKie commented on Directory.Build.props
> +  <PropertyGroup Condition="'$(IsTestProject)' == 'true' or '$(IsIntegrationTestProject)' == 'true'">
`IsTestProject` is an all-encoumpasing flag
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.props#L21-L22

2023-03-14 01:19 UTC, RussKie commented on src/System.Windows.Forms.Primitives/tests/UnitTests/System.Windows.Forms.Primitives.Tests.csproj
> +  </ItemGroup>
Why is this needed?

2023-03-14 01:22 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
> +                    inputSimulator => inputSimulator.Mouse.LeftButtonClick().Sleep(INPUTSIMULATOR_DELAY));
InputSimulator is a 3P library, which is largely unmaintained. @sharwell knows a little more about it.
I think it can/should be replaced by UIA API.

2023-03-14 18:02 UTC, dreddy-work commented
/azp run

2023-03-14 21:31 UTC, dreddy-work commented
/azp run

2023-03-15 01:21 UTC, JeremyKuhne requested changes
A comment nit from me.

2023-03-15 01:21 UTC, JeremyKuhne commented on eng/xunit.runner.json
> +  "maxParallelThreads": 1,
Making _everything_ serial should have a follow up issue for tracking if it doesn't already. It is unfortunate that we can't add comments in json. Doing this will facilitate adding poorly written tests making it harder and harder to go back to parallel testing.

2023-03-15 01:21 UTC, JeremyKuhne commented on Directory.Build.props
> +  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
This would be a good place to have a comment for our re-parallelization tracking issue.

2023-03-16 21:21 UTC, dreddy-work commented
Closing as we are trying to remove all delays and a part of these changes are taken separately.

2023-03-16 21:21 UTC, closed without merging