Enable nullability in ExpressionContext and ExpressionTable
dotnet/winforms pull request #8776
Opened 2023-03-10 09:49 UTC by halgab

Contributes to #1107

2023-03-10 18:06 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ExpressionTable.cs
> +        private Dictionary<object, ExpressionInfo>? _expressions;
I do not see need for a backing field as well as property on it. Can you simplify the code to use only one of them and after that, we don't need it nullable.

2023-03-10 18:08 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
> +System.ComponentModel.Design.Serialization.ExpressionContext.Expression.get -> System.CodeDom.CodeExpression
You are not supposed to update this file manually. Just build your changes locally and build will update `Unshipped.txt`.

2023-03-10 18:09 UTC, dreddy-work requested changes
please check build failure.

2023-03-10 19:28 UTC, halgab commented
Well, I thought my second commit would fix them, and I'm not really sure why it hasn't...

2023-03-10 21:08 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
> +System.ComponentModel.Design.Serialization.ExpressionContext.Expression.get -> System.CodeDom.CodeExpression
May be not build, but you should see Analyzer suggestion to add it to the API's.

We track these and move to Shipped when ready for current preview release.

2023-03-10 21:13 UTC, halgab commented on src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
> +System.ComponentModel.Design.Serialization.ExpressionContext.Expression.get -> System.CodeDom.CodeExpression
Okay, I saw the analyser this time. Thanks for your help!

2023-03-10 22:21 UTC, dreddy-work commented
@halgab, when you get chance, can you rebase it on main?

2023-03-10 22:41 UTC, dreddy-work commented
Seems conflict is still not resolved. @halgab.

2023-03-10 23:08 UTC, halgab commented
should be good now, sorry

2023-03-11 00:04 UTC, dreddy-work approved these changes

2023-03-11 00:19 UTC, merged