Close ServerManager window on build agents and save screenshot in UI test failures.
dotnet/winforms pull request #8875
Opened 2023-03-20 17:58 UTC by dreddy-work

- Close ServerManager window on build agents that may interfere with UI tests.
- Take screenshots and save them in case any UI test fails.

2023-03-20 18:38 UTC, JeremyKuhne requested changes
Comments in line

2023-03-20 18:38 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +                            PInvoke.SwitchToThisWindow((HWND)process.MainWindowHandle, true);
Why switch?

2023-03-20 18:38 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +                        }
I'd think logging here would be useful. Did we close successfully? Did we not find the ServerManager?

2023-03-20 18:38 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +                    string path = $"{assemblyPath[..index]}log\\{config}";
Consider using `Path` methods to find parent directories and `Path.Join` segments. Generally speaking it is much more robust.

2023-03-20 18:38 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +                TestOutputHelper.WriteLine($"Failed to save screenshot: {exception.Message}.");
Consider using `exception.ToString` here. It would probably be useful to see the stack in the output.

2023-03-20 22:04 UTC, dreddy-work commented
/azp run

2023-03-20 23:31 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +            TestOutputHelper!.WriteLine($"Moving mouse to ({point.X}, {point.Y}).");
Not needed. Didn't remove test code.

2023-03-20 23:38 UTC, JeremyKuhne approved these changes

2023-03-21 00:42 UTC, merged

2023-03-21 07:09 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +                    TrySaveScreenshot();
There's already an infra that can take screenshots and memdumps. It's located here: https://github.com/dotnet/winforms/blob/main/eng/Screenshots.win.psm1.
The screenshots can be taken at intervals and published as part of the build artifacts.
![image](https://user-images.githubusercontent.com/4403806/226538679-bc6c1c13-2dac-4b5d-8d53-1eecf03f532c.png)

2023-03-21 16:29 UTC, dreddy-work commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +                    TrySaveScreenshot();
I know this. Its at specific intervals. We need something when test fails but not at periodic intervals.

2023-03-22 07:21 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +            }
The current implementation hardcodes the knowledge of the current folder layout, which isn't set in stone. 
Suppose that you'll (eventually) run these tests in Helix. You won't have the same folder layout.

2023-03-22 07:23 UTC, RussKie commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +            }
Thinking of Helix - burning a const at the time of a compilation may pose challenges too, and I see that you entertaining ideas of defining an env var for the log path. 👍