Use RegLoadMUIString API instead of SHLoadIndirectString
dotnet/winforms pull request #8921
Opened 2023-03-30 16:17 UTC by DJm00n

I have extracted part of #8573 into separate PR until decision is made on some aspects of that PR.

## Proposed changes

- Use `RegLoadMUIString` API instead of the `SHLoadIndirectString` as recommended at https://learn.microsoft.com/windows/win32/intl/locating-redirected-strings#load-a-language-neutral-registry-value
- Move InputLanguage `GetKeyboardLayoutNameForHKL` method implementation to the internal `LayoutId` property (to ease debugging)

## Customer Impact

- Shouldn't have any visible customer impact

## Regression? 

- No

## Risk

- Little

## Test methodology 

- Install "Canadian Multilingual Standard"  keyboard layout in Windows.
- Check that its `LayoutId` is `00011009` under debugger.
- Check that its `LayoutName` is "Canadian Multilingual Standard".

2023-04-05 11:21 UTC, DJm00n commented
@JeremyKuhne any objections on this topic?

2023-04-05 18:22 UTC, JeremyKuhne requested changes
Comments are inline.

2023-04-05 18:22 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvike.RegLoadMUIString.cs
> +        public static unsafe bool RegLoadMUIString(RegistryKey key, string keyName, out string localizedValue)
This looks like something that we should create an API proposal for in the runtime. `RegistryKey.GetMUIString()` maybe?

2023-04-05 18:22 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvike.RegLoadMUIString.cs
> +            if (key.Handle.IsInvalid)
I would expect that this is uncommon, maybe better to just let if fail with the call to RegLoadMUIString().

2023-04-05 18:22 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvike.RegLoadMUIString.cs
> +            Span<char> buffer = stackalloc char[(int)bytes / sizeof(char)];
The data here appears to be unbounded. One presumes that this could be pretty expensive if it follows through to a PE file to load a string resource just to return the length.

The safer/better choice is to stack allocate some reasonable buffer and then rent/return a bigger array from the `ArrayPool` if the size isn't large enough. It may also make sense to just use the `ArrayPool`, as I the benefit of skipping the rental is probably minimal at best. Just using the `ArrayPool` would make the logic simpler, for sure.

2023-04-05 18:23 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvike.RegLoadMUIString.cs
> +        public static unsafe bool RegLoadMUIString(RegistryKey key, string keyName, out string localizedValue)
To be clear- I don't think we should block here, but I would assume this functionality is generally useful for our developers.

2023-04-07 10:24 UTC, DJm00n commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvike.RegLoadMUIString.cs
> +            Span<char> buffer = stackalloc char[(int)bytes / sizeof(char)];
>One presumes that this could be pretty expensive if it follows through to a PE file to load a string resource just to return the length.

I can bet that RegLoadMUIString is caching MUI strings to avoid this rereading but I'll do the changes.

2023-04-07 22:07 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvike.RegLoadMUIString.cs
> +            Span<char> buffer = stackalloc char[(int)bytes / sizeof(char)];
> I can bet that RegLoadMUIString is caching MUI strings to avoid this rereading but I'll do the changes.

It doesn't look like it. You'll probably get some general IO caching though. The more critical issue is that the buffer size is unbounded, which is a problem for stack allocation.

2023-04-10 16:13 UTC, DJm00n commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvike.RegLoadMUIString.cs
> +        public static unsafe bool RegLoadMUIString(RegistryKey key, string keyName, out string localizedValue)
@JeremyKuhne I have added `RegistryKeyExtensions.GetMUIString` extension method

2023-04-10 16:16 UTC, DJm00n commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvoke.RegLoadMUIString.cs
> +            char[] buffer = ArrayPool<char>.Shared.Rent(MAX_PATH + 1);
`FolderNameEditor.FolderBrowser.cs` is using `MAX_PATH` for `displayName` buffer too...

2023-04-11 00:35 UTC, JeremyKuhne requested changes
Added a few more comments.

2023-04-11 00:35 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvoke.RegLoadMUIString.cs
> +            return HRESULT.HRESULT_FROM_WIN32(error).Succeeded;
You should only try to create the string when `ERROR_SUCCESS` is returned and that should be the only thing you check to return success.

2023-04-18 19:58 UTC, DJm00n commented
Hi @JeremyKuhne! Do you have any updates on this review?

2023-04-18 20:38 UTC, JeremyKuhne commented
@DJm00n I'm in the process of adding a `BufferScope` that makes writing this sort of thing easier. #8999

It would be good to use that to simplify this if possible. You should be able to do something similar to what I did with PInvoke.GetModuleFileNameLongPath.cs in that change.

Hopefully I'll have it checked in this afternoon.

2023-04-19 10:57 UTC, DJm00n commented
> GetModuleFileNameLongPath
Nice! This is indeed looks more simple!

Pushed updated version of `PInvoke.RegLoadMUIString`.

2023-04-25 14:56 UTC, DJm00n commented
Hi @JeremyKuhne! Any updates on this review?

2023-04-25 17:26 UTC, JeremyKuhne approved these changes
Looks great- thanks for your patience!

2023-04-26 00:31 UTC, dreddy-work commented
@DJm00n, can you rebase this?

2023-04-26 10:07 UTC, DJm00n commented
@dreddy-work done

2023-05-04 20:19 UTC, dreddy-work approved these changes

2023-05-04 20:35 UTC, merged