8295 - ResXResourceWriterTests
dotnet/winforms pull request #9070
Opened 2023-05-04 14:33 UTC by ssflynn77

Adds to #8295 - Added tests to ResXResourceWriter

## Proposed changes
- Additional unit tests for ResXResourceWriter

## Customer Impact
- None

## Regression? 
-  No

## Risk
- Low
- PR only has unit tests

## Test methodology
- Successful Unit Tests

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9070)

2023-05-04 20:08 UTC, dreddy-work commented
@ssflynn77, build failed.

src\System.Windows.Forms\tests\UnitTests\System\Resources\ResXResourceWriterTests.cs(60,18): error CS8632: (NETCORE_ENGINEERING_TELEMETRY=Build) The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.

2023-05-04 20:17 UTC, dreddy-work requested changes
please check build failure.

2023-05-04 20:17 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        ResXResourceWriter writer = new ResXResourceWriter(fileName);
```suggestion
        using ResXResourceWriter writer = new(fileName);
```

2023-05-04 20:17 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        ResXResourceWriter writer = new ResXResourceWriter(fileName, typeNameConverter);
```suggestion
        using ResXResourceWriter writer = new(fileName, typeNameConverter);
```

2023-05-04 20:17 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        ResXResourceWriter writer = new ResXResourceWriter(stream);
```suggestion
        using ResXResourceWriter writer = new(stream);
```

2023-05-04 20:17 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        Stream stream = new MemoryStream();
```suggestion
        using var stream = new MemoryStream();
```

2023-05-04 20:17 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        ResXResourceWriter writer = new ResXResourceWriter(stream);
Same below.  Make sure we are disposing disposables.

2023-05-04 20:17 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        string name = "TestMetaData";
see if you can consolidate this to a local field and reuse in tests?

2023-05-04 20:17 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        byte[] value = new byte[] { 1, 2, 3 };
we use either one of the following to avoid repeating the type information in the declaration/initializations.

```CS
var value = new byte[] {1,2,3}
```

or

```CS
    byte[] value = new {1, 2, 3}
```

Please check other cases in this file.

2023-05-05 00:41 UTC, ssflynn77 commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        byte[] value = new byte[] { 1, 2, 3 };
Added several new declarations .

2023-05-05 00:41 UTC, ssflynn77 commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        string name = "TestMetaData";
Consolidated the test strings in the latest commit

2023-05-05 00:43 UTC, ssflynn77 commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        ResXResourceWriter writer = new ResXResourceWriter(fileName);
Added using statements to all IDisposable instances

2023-05-05 00:43 UTC, ssflynn77 commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        ResXResourceWriter writer = new ResXResourceWriter(stream);
Added using statements to all IDisposable instances

2023-05-05 18:53 UTC, dreddy-work requested changes
Thanks for a quick look. Added some feedback.

2023-05-05 18:53 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +    private readonly string _ResxFileName = "test.resx";
`_resxFileName `instead of `_ResxFileName`

2023-05-05 18:53 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +#nullable enable
how hard it is to enable nullability on this file? if not feasible, i would leave this `Func` as well without `nullability `enabled so we can clean entire file when we ready to enable nullability on the file.

2023-05-05 18:53 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        using ResXResourceWriter writer = new ResXResourceWriter(fileName);
seems you missed my other suggestion here. We avoid type name twice in the declarations like this.  This is applicable to all the changes you made in this file.

```suggestion
        using ResXResourceWriter writer = new(fileName);
```

2023-05-05 18:53 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        using ResXResourceWriter writer = new ResXResourceWriter(fileName, _typeNameConverter);
same here and other places below.

2023-05-05 18:53 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        Assert.NotNull(enumerator);
i don't think you need to check for non-null on enumerator here. Same for other instances of checking `notnull `on enumerator in this file.

2023-05-08 12:10 UTC, ssflynn77 commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +#nullable enable
I removed the "#nullable" lines and changed the line to 
`private readonly Func<Type, string> _typeNameConverter = type => type?.AssemblyQualifiedName ?? string.Empty;`

Just removing the nullable from "Type"

I'm not sure what you mean by 

> how hard it is to enable nullability on this file?
Enable it on Test file or the base class file?

2023-05-08 12:13 UTC, ssflynn77 commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        using ResXResourceWriter writer = new ResXResourceWriter(fileName);
Fixed for this instance and other instances in the file

2023-05-08 12:14 UTC, ssflynn77 commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +        Assert.NotNull(enumerator);
Removed checks for this instance and other instances in the file.

2023-05-08 12:14 UTC, ssflynn77 commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +    private readonly string _ResxFileName = "test.resx";
Fixed

2023-05-08 17:00 UTC, dreddy-work commented on src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
> +#nullable enable
THat is fine. Wanted to see if we could try enabling nullability on the entire file but that doesn't need to be in this PR.

2023-05-08 17:02 UTC, dreddy-work approved these changes

2023-05-08 17:02 UTC, merged