Use generic list instead of array in TreeNode
dotnet/winforms pull request #9078
Opened 2023-05-06 10:03 UTC by gpetrou

## Proposed changes

- Use generic list instead of array in TreeNode.

2023-05-06 16:52 UTC, halgab commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
>              (children[i] = children[i - 1]).index = i;
Isn't that line broken now that `children` is a List? I guess now you just have to change the index without the `children[i] = children[i - 1]` part, and this loop can be move after `children.Insert(index, node);` right?

2023-05-06 16:52 UTC, halgab commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> -                (parent.children[i] = parent.children[i + 1]).index = i;
Is it okay to no longer update the `index`?

2023-05-06 16:52 UTC, halgab commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +        children.EnsureCapacity(1);
Is that still necessary now? Looking at the previous `EnsureCapacity` method, `1` was special-cased but here it will no longer be the case.

2023-05-06 16:52 UTC, halgab commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +            childCount = 0;
Can't `childCount` be replaced with `children.Count` now?

2023-05-07 06:55 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +            childCount = 0;
Seems like it can be.

2023-05-07 06:56 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> -                (parent.children[i] = parent.children[i + 1]).index = i;
I should not have removed this one.

2023-05-08 18:04 UTC, dreddy-work requested changes
It would be nice if you could add one or two new tests exercising these changes.

2023-05-08 18:04 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
> +            owner.children.EnsureCapacity(1);
please check this case too.

2023-06-21 20:18 UTC, dreddy-work approved these changes

2023-06-21 21:29 UTC, merged