Fix Application.Exit issues
dotnet/winforms pull request #9085
Opened 2023-05-06 17:39 UTC by kirsan31

Fixes #3606

## Proposed changes

- Replace `foreach` in `OpenForms` iteration.
- Iterate in backward direction.

## Customer Impact
- Users now can close existing and open new forms in `FormClosing`.
- MDI users now safely can use `Application.Exit` and `Application.Restart`.

## Regression? 

- No

## Risk

- Minimal

## Test methodology

- New integration tests added.

2023-05-06 18:28 UTC, kirsan31 commented
Hmmm it's seems that `OpenForms` is always empty after first test call 🤔
Any Ideas? On my local PC everything are ok...

2023-05-09 17:22 UTC, dreddy-work commented
> Are this integration tests running in parallel in own gui thread each?

All tests, including UI, currently running in sequential. 

@kirsan31, I will have to debug to understand the behavior, hence delay.  Will check sometime this week (only if you don't get to it before me :))

2023-05-09 17:25 UTC, kirsan31 commented
@dreddy-work 

>  I will have to debug to understand the behavior, hence delay. Will check sometime this week (only if you don't get to it before me :))

How can I debug it on your test servers? On my local windows pc all test work as they must.

2023-05-09 17:28 UTC, dreddy-work commented
> How can I debug it on your test servers? On my local windows pc all test work as they must.

Unfortunately, we cannot debug on build agents. If these tests are consistently failing on build agents, I would start adding more **test** logging and assertion in tests that are failing, and we can get logs from the build agents after.

2023-05-09 17:31 UTC, kirsan31 commented
> Unfortunately, we cannot debug on build agents. If these tests are consistently failing on build agents, I would start adding more test logging and assertion in tests that are failing, and we can get logs from the build agents after.

Ok,  I will try...

2023-05-10 08:41 UTC, kirsan31 commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +                Assert.True(Application.OpenForms.Count == 1, $"OnLoadCalled {dialog!._OnLoadCalled}");
Here all are ok.

2023-05-10 08:44 UTC, kirsan31 commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> +            Assert.True(Application.OpenForms.Count > 0);
Fail here. On local PC all of this normally pass.

2023-05-10 08:51 UTC, kirsan31 commented
@dreddy-work 
I found that form disappear from `OpenForms` after `WaitForIdleAsync` call. I added assertions to `WaitForIdleAsync`, which pass normally on the local machine. One of them fails on your test bench. See the comments on the methods above.
To advance further, I'm afraid I do not have enough understanding of how your test environment works 😳

2023-05-10 16:49 UTC, dreddy-work commented
Thanks @kirsan31 for the update. I will try to spend some time this week and update this thread.,

2023-05-10 19:56 UTC, kirsan31 commented
I've added StackTrace to last call of `FormCollection.Remove` (for some reason form is Disposed):
```cs
at System.Windows.Forms.FormCollection.Remove(Form form) in //src/System.Windows.Forms/src/System/Windows/Forms/FormCollection.cs:line 100
   at System.Windows.Forms.Form.OnHandleDestroyed(EventArgs e) in //src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 4014
   at System.Windows.Forms.Control.WmDestroy(Message& m) in //src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 12081
   at System.Windows.Forms.Control.WndProc(Message& m) in //src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 13061
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m) in //src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs:line 1508
   at System.Windows.Forms.ContainerControl.WndProc(Message& m) in //src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs:line 2126
   at System.Windows.Forms.Form.WndProc(Message& m) in //src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 6714
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) in //src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 65
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) in //src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 114
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, WM msg, WPARAM wparam, LPARAM lparam) in //src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 373
   at Windows.Win32.PInvoke.DestroyWindow(HWND hWnd)
   at System.Windows.Forms.NativeWindow.DestroyHandle() in //src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 553
   at System.Windows.Forms.Control.DestroyHandle() in //src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 5050
   at System.Windows.Forms.Control.Dispose(Boolean disposing) in //src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 5104
   at System.Windows.Forms.ContainerControl.Dispose(Boolean disposing) in //src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs:line 633
   at System.Windows.Forms.Form.Dispose(Boolean disposing) in //src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 3391
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Application.ThreadWindows.Dispose() in //src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadWindows.cs:line 79
   at System.Windows.Forms.Application.ThreadContext.DisposeThreadWindows() in //src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 594
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData) in //src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs:line 276
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context) in //src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 1104
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context) in //src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 965
   at System.Windows.Forms.Application.RunDialog(Form form) in //src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1205
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner) in //src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 5384
   at System.Windows.Forms.Form.ShowDialog() in //src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 5269
   at System.Windows.Forms.UITests.ControlTestBase.RunFormWithoutControlAsync[TForm](Func1 createForm, Func2 testDriverAsync, Boolean clearOpenFormsOnDone) in //src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 386
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Windows.Forms.UITests.ControlTestBase.RunFormWithoutControlAsync[TForm](Func1 createForm, Func2 testDriverAsync, Boolean clearOpenFormsOnDone)
   at System.Windows.Forms.UITests.ApplicationTests.RunTestAsync(Func2 runTest) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ApplicationTests.cs:line 323
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Windows.Forms.UITests.ApplicationTests.RunTestAsync(Func2 runTest)
   at System.Windows.Forms.UITests.ApplicationTests.Application_Exit_OpenForms_Show_Close(Int32 nChildFrms, Int32 nRemovedFrms, Int32 nAddFrms, Boolean cancel) in //src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ApplicationTests.cs:line 205
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Windows.Forms.UITests.ApplicationTests.Application_Exit_OpenForms_Show_Close(Int32 nChildFrms, Int32 nRemovedFrms, Int32 nAddFrms, Boolean cancel)
   at InvokeStub_ApplicationTests.Application_Exit_OpenForms_Show_Close(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xunit.Sdk.TestInvoker1.CallTestMethod(Object testClassInstance) in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 150
   at Xunit.Sdk.UITestInvoker.<>c__DisplayClass2_0.<<RunAsync>b__2>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.UITestInvoker.<>c__DisplayClass2_0.<RunAsync>b__2()
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func1 asyncAction) in //src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func1 asyncAction)
   at Xunit.Sdk.UITestInvoker.<RunAsync>b__2_0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.UITestInvoker.<RunAsync>b__2_0()
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func1 code) in //src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func1 code)
   at Xunit.Sdk.UITestInvoker.RunAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.UITestInvoker.RunAsync()
   at Xunit.Sdk.UITestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator)
   at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestRunner.cs:line 67
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
   at Xunit.Sdk.TestRunner1.<>c__DisplayClass43_0.<RunAsync>b__0() in //src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func1 code)
   at Xunit.Sdk.TestRunner1.RunAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestRunner.cs:line 149
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& sta [...]

2023-06-27 06:01 UTC, kirsan31 commented
@dreddy-work any chance you look into this? I am afraid we may not be in time for 8.0 🙃

2023-06-27 17:04 UTC, dreddy-work commented
> @dreddy-work any chance you look into this? I am afraid we may not be in time for 8.0 🙃

Apology for the delay @kirsan31. I overlooked this and was under assumption that it was on waiting on you. Will be looking into it.

2023-06-27 23:29 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +                        if (ver != s_forms._addVersion) // A new form was added, we need to iterate again
what is the scenario you expect a new form launched after Application.exit is called?

2023-06-27 23:29 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +                        if (ver != s_forms._addVersion) // A new form was added, we need to iterate again
if this is possible, how do you handle, Forms that are explicitly closed? `_addVersion` doesn't help there.

2023-06-27 23:29 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
> +                        var form = s_forms[^1];
same here.  why did you not consider adding new form in this?

2023-07-15 09:30 UTC, kirsan31 commented
From [StackTrace](https://github.com/dotnet/winforms/pull/9085#issuecomment-1542729035) I can say only that after `RunDialog` we immediately got 'User32.WM.QUIT' here:
https://github.com/kirsan31/winforms/blob/4d80d902bf86533275dc9c81e8a793adafaa6505/src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs#L270-L276

2023-07-27 09:42 UTC, kirsan31 commented
@dreddy-work any chance to be in time to 8.0? Or relax until 9.0? 😁

2023-07-27 16:59 UTC, dreddy-work commented
> @dreddy-work any chance to be in time to 8.0? Or relax until 9.0? 😁

@kirsan31, After experiencing issues with flakiness in our UI tests, we made the decision to disable them temporarily. Our plan is to address these problems once we complete the 8.0 wrap-up. The failures seem to be specific to the UI tests and, as you pointed out, they only occur on the build agents, which complicates the investigation process. Regardless of the release, we need to fully understand the failure and the potential risks associated with the change involving the order of events. I will bring this to the team for triaging again and to set a milestone accordingly.

2023-07-28 00:03 UTC, JeremyKuhne commented
It seems fundamentally wrong to have a static lock on the FormCollection. This is what I would expect:

``` C#
    internal object CollectionSyncRoot => InnerList.SyncRoot;
```

That said, the other thing I would be doing is looking at trying to make a copy of the list (to array, just expose the ArrayList internally) before going through it, then locking the collection (then repeating as necessary). I'm not sure what the expected mutability is on initial perusal, but that's usually the way you deal with clearing a mutable collection.

I'm not sure our tests should ever call `Application.Exit`. Every test gets a new thread from XUnit and then a new STA thread is spun up to run each test. This means we get a separate `ThreadContext` for every test, then `Application.Exit` would try to close all of them.

In any case, this is something to mess with early in .NET 9. We're too close to closing down .NET 8 and messing with this is quite risky.

2023-07-28 18:39 UTC, kirsan31 commented
@JeremyKuhne 



> It seems fundamentally wrong to have a static lock on the FormCollection. This is what I would expect:
> 
> ```cs
>     internal object CollectionSyncRoot => InnerList.SyncRoot;
> ```

Sorry, didn't catch this part - how it's related to this pr?

> That said, the other thing I would be doing is looking at trying to make a copy of the list (to array, just expose the ArrayList internally) before going through it, then locking the collection (then repeating as necessary). I'm not sure what the expected mutability is on initial perusal, but that's usually the way you deal with clearing a mutable collection.

If I understand you correctly, then this technique will not work here. On each step we need to iterate over again after new form added - to not violate mdi form closing events order.

> I'm not sure our tests should ever call Application.Exit. Every test gets a new thread from XUnit and then a new STA thread is spun up to run each test. This means we get a separate ThreadContext for every test, then Application.Exit would try to close all of them.

Hmmm... Problems with parallel run was the [first I think of](https://github.com/dotnet/winforms/pull/9085#issuecomment-1537197511):

> Are this integration tests running in parallel in own gui thread each?

And the answer [was](https://github.com/dotnet/winforms/pull/9085#issuecomment-1540572499):

> All tests, including UI, currently running in sequential.

🤔

> In any case, this is something to mess with early in .NET 9. We're too close to closing down .NET 8 and messing with this is quite risky.

😢

2023-11-20 23:33 UTC, lonitra commented
@JeremyKuhne , now that we are in .NET 9, could you take another look at this?

2024-01-04 01:15 UTC, JeremyKuhne requested changes
Added a number of comments. In general, I'm good with this change. There are a few comments on minimizing some of the changes to the released code. It does need to be brought up to our coding style guidelines- I've commented on a few of the issues there.

2024-01-04 01:15 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/FormCollection.cs
> +            _lastRemoveStackTrace = Environment.StackTrace;
Taking a stack trace is quite expensive. This shouldn't be done unless absolutely necessary. Unless we're expecting this to be something we frequently need in tests I'd remove it. If we really do need it, the tests that need it should enable stashing the stack trace.

2024-01-04 13:01 UTC, kirsan31 commented
> Added a number of comments. In general, I'm good with this change. There are a few comments on minimizing some of the changes to the released code. It does need to be brought up to our coding style guidelines- I've commented on a few of the issues there.

Thank you for taking look at this @JeremyKuhne. But I think it's a bit early to fix styling, because many of this code will be removed after we solve tests problems.
![image](https://github.com/dotnet/winforms/assets/17767561/90ed4ffd-daa0-4c96-9651-f0035747d422)
Only 1 commit will go to release (may be second too) but all debug commits will be reverted.
We stack here because of test failure on your test systems (on local windows PC all are ok). Last note on this [was](https://github.com/dotnet/winforms/pull/9085#issuecomment-1654003457):

> After experiencing issues with flakiness in our UI tests, we made the decision to disable them temporarily. Our plan is to address these problems once we complete the 8.0 wrap-up. The failures seem to be specific to the UI tests and, as you pointed out, they only occur on the build agents, which complicates the investigation process. Regardless of the release, we need to fully understand the failure and the potential risks associated with the change involving the order of events. I will bring this to the team for triaging again and to set a milestone accordingly.

So I think we need to decide what to do with tests problem and then I will correct styling...

2024-01-04 19:06 UTC, JeremyKuhne commented
@kirsan31 I don't want to check in temporary code that isn't up to snuff. Addressing integration tests is behind schedule as @dreddy-work left the team. Can we get the MDI fix in now?

2024-01-04 19:45 UTC, kirsan31 commented
@JeremyKuhne 
> I don't want to check in temporary code that isn't up to snuff.

Sorry, nobody wants this and that's why I was surprised that you did it 🤷‍♂️
My work on this PR stopped at what I quoted above. There were no further significant updates here from the team for a half of the year.
And after @lonitra ping, I was expecting some instructions on what to do next (e.g. continue test fails investigations, or drop them)🤔

> Can we get the MDI fix in now?

You want that I dropped all debug code and `all tests` too + applied you suggestions? Am I understand right?

2024-01-04 19:58 UTC, JeremyKuhne commented
@kirsan31 it looks like `RemoteExecutor` issue has been fixed (https://github.com/dotnet/runtime/issues/13610#issuecomment-703290446) so the tests could be added to the regular unit tests. https://github.com/dotnet/winforms/blob/735c0ee3c5fe7a4a78ced063896e6f78a41cdfc2/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs#L37

I'll look at re-enabling all the existing `RemoteExecutor` based tests.

2024-01-04 20:01 UTC, kirsan31 commented
> @kirsan31 it looks like `RemoteExecutor` issue has been fixed ([dotnet/runtime#13610 (comment)](https://github.com/dotnet/runtime/issues/13610#issuecomment-703290446)) so the tests could be added to the regular unit tests.
> 
> https://github.com/dotnet/winforms/blob/735c0ee3c5fe7a4a78ced063896e6f78a41cdfc2/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs#L37
> 
> I'll look at re-enabling all the existing `RemoteExecutor` based tests.

Got it - thank you. Will try...

2024-01-06 13:05 UTC, kirsan31 commented
@JeremyKuhne 
- Debug code removed + rebased on main.
- Integration tests replaced with unit tests + `RemoteExecutor`.
- Suggestions implemented.

2024-01-07 18:29 UTC, merged