Enable nullability in CodeDomSerializerBase
dotnet/winforms pull request #9099
Opened 2023-05-10 11:37 UTC by halgab

This one is pretty big, apologies for that. It enables nullability in CodeDomSerializerBase to get one foot in the door to annotate more serializers down the road,
One issue I had doing this is the lack of annoations in System.CodeDom (see https://github.com/dotnet/runtime/issues/41720, https://github.com/dotnet/runtime/issues/78036)

Contributes to #8342

## Proposed changes

- Enable nullability in CodeDomSerializerBase
- Refactor CodeDomSerializerBase and fix an apparent bug
- Introduce new helper functions to simplify more parts of the code

2023-05-10 11:51 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
> -                                    DeserializeExpression(manager, null, ces.Expression);
This looked a lot like a bug

2023-05-10 11:51 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
> +                                object? index = DeserializeExpression(manager, name, arrayIndexerEx.Indices[i]);
This should fix the trace in the non `IConvertible` case

2023-05-10 12:50 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
> -                                DeserializeExpression(manager, null, ces.Expression);
This looked a lot like a bug

2023-05-10 12:50 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
> +                            object? index = DeserializeExpression(manager, name, arrayIndexerEx.Indices[i]);
This should fix the trace in the non IConvertible case

2023-05-11 03:57 UTC, elachlan commented
Thanks for working on this!

2023-06-21 22:12 UTC, JeremyKuhne requested changes
In general, looks really good! I think there is a bit more opportunity to use pattern matching. See my comments.

2023-06-21 22:12 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
> +        ReadOnlySpan<TypeCode> compatibleTypes = new TypeCode[]
Why change this to ReadOnlySpan?

2023-06-21 22:12 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/System/ComponentModel/Design/Serialization/DesignerSerializationManagerHelper.cs
> +        public static bool TryGetContext<T>(this IDesignerSerializationManager manager,
nit: when we break parameters they should all start indented on their own line

2023-06-22 09:21 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
> +                typeName.Append('[');
Done. In the end there weren't many opportunities to do so, as line 93 isn't a direct `Append` call

2023-06-22 09:22 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
> +            TypeDescriptionProvider? targetProvider = GetTargetFrameworkProvider(manager, instance);
I took the opportunity to move this logic to a helper to reduce code duplication

2023-06-22 09:22 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
> +                    ICustomTypeDescriptor? targetAwareDescriptor = targetProvider.GetTypeDescriptor(instance);
done

2023-06-22 09:22 UTC, halgab commented on src/System.Windows.Forms.Primitives/src/System/ComponentModel/Design/Serialization/DesignerSerializationManagerHelper.cs
> +        public static bool TryGetContext<T>(this IDesignerSerializationManager manager,
done

2023-07-12 20:02 UTC, JeremyKuhne approved these changes
Looks good, thanks for this!

2023-07-12 20:33 UTC, merged

2023-08-02 14:32 UTC, steveharter commented
What is left to fully address https://github.com/dotnet/winforms/issues/8342?

2023-08-03 07:52 UTC, halgab commented
There are quite a lot of files that still need annotating. I count 192 as of current main branch.