Enable nullability in classes that inherit from Form in System.Windows.Forms.Design
dotnet/winforms pull request #9102
Opened 2023-05-10 15:15 UTC by gpetrou

## Proposed changes

- Enable nullability in classes that inherit from Form in System.Windows.Forms.Design.

2023-05-10 19:03 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatStringDialog.cs
> +    private static int GetRightSideOffset(Control? ctl)
This one looks odd to me. Isn't it better to silence the warnings at the callsite?

2023-05-15 22:33 UTC, dreddy-work requested changes

2023-05-15 22:33 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewCellStyleBuilder.cs
> +            public override string? Name
nit: remove backing field?

2023-05-15 22:33 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.CurrencyFormatType.cs
> +        }
can be simplified others in this statement.

```suggestion
        public override string TopLabelString => SR.BindingFormattingDialogFormatTypeCurrencyExplanation;
```

2023-05-15 22:33 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.CurrencyFormatType.cs
> +                switch ((int)_owner.decimalPlacesUpDown.Value)
nit: simplify to new switch format.

2023-05-15 22:33 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.CustomFormatType.cs
> +                string label = "";
nit: can you replace "" with `string.empty` in this file?

2023-05-17 04:33 UTC, gpetrou commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatStringDialog.cs
> +    private static int GetRightSideOffset(Control? ctl)
The problem is not the callsites but the use of `Parent` inside the while loop. I will add an extra variable to hopefully make this easier to understand.

2023-05-17 04:56 UTC, gpetrou commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.CurrencyFormatType.cs
> +                switch ((int)_owner.decimalPlacesUpDown.Value)
I don't see any refactoring suggestions in Visual Studio about this. Is this doable on properties?

2023-05-17 04:57 UTC, gpetrou commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewCellStyleBuilder.cs
> +            public override string? Name
This is an override, so I assume that we should not remove this?

2023-05-17 07:40 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatStringDialog.cs
> +        while (control is not null)
nit: this could be a do{} while() loop

2023-05-17 07:43 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.DateTimeFormatType.cs
> +#if DEBUG
this preprocessing instruction is unnecessary.

2023-05-17 07:44 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.NumericFormatType.cs
> +#if DEBUG
ditto

2023-06-06 17:53 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewCellStyleBuilder.cs
> +            public override string? Name
not override but just the backing field.

```suggestion
            public override string? Name { get; set;}
```

2023-06-06 17:56 UTC, dreddy-work commented
Thanks @gpetrou. Can you also address remaining comments and get this PR ready for review again?

2023-06-21 20:06 UTC, dreddy-work commented
I can take this in @gpetrou, seems there is one more conflict.

2023-06-21 20:06 UTC, dreddy-work approved these changes

2023-06-22 16:20 UTC, dreddy-work commented
@gpetrou, seems this still has conflict.

2023-06-26 18:53 UTC, gpetrou commented
@dreddy-work could we also merge this one?

2023-06-26 19:36 UTC, dreddy-work approved these changes

2023-06-26 19:36 UTC, merged