Enable nullability in remaining ListViewItem members
dotnet/winforms pull request #9109
Opened 2023-05-11 16:19 UTC by gpetrou

## Proposed changes

- Enable nullability in remaining ListViewItem members.

2023-05-15 22:25 UTC, dreddy-work requested changes

2023-05-15 22:25 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
> +        ListViewGroup? group = _listView.Groups[_groupName];
direct assignment? 
```suggestion
        Group = _listView.Groups[_groupName];
```

2023-05-17 18:25 UTC, gpetrou commented
@dreddy-work any more feedback on this one?

2023-05-17 18:51 UTC, dreddy-work commented
> @dreddy-work any more feedback on this one?

Not at the moment but when i get chance, i will check these and merge if no further feedback.

2023-06-05 17:06 UTC, dreddy-work approved these changes

2023-06-05 17:06 UTC, merged