Enable nullability in CodeDomComponentSerializationService
dotnet/winforms pull request #9120
Opened 2023-05-15 10:12 UTC by halgab

## Proposed changes

- Enable nullability in `CodeDomComponentSerializationService`
- Change `ArrayList` with `List<T>` (contributes to #8140)
- Change all not serialized `Hashtable`s to `Dictionary<K, V>` and `HashSet<T>` (contributes to #8143)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9120)

2023-05-15 21:51 UTC, dreddy-work requested changes

2023-05-15 21:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +        private static readonly TraceSwitch? s_trace;
do you need this in release build?

2023-05-15 21:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                Hashtable state = new Hashtable(_objects!.Count);
```suggestion
                Hashtable state = new(_objects!.Count);
```

2023-05-15 21:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                Hashtable state = new Hashtable(_objects!.Count);
Can this be moved to dictionary as well?

2023-05-15 21:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            List<object> collection = new List<object>();
```suggestion
            List<object> collection = new();
```

2023-05-15 21:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            private void PopulateCompleteStatements(object? data, string name, CodeStatementCollection completeStatements)
originally callers are ensuring `data `is never null. I don't see a reason to call this method when `data `is null.
Either exit early if `null `or refactor.

2023-05-15 21:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                else if (data is not null)
you  may not need this.

2023-05-15 21:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                if (manager is not null)
nit: reduce nesting by quitting early.

2023-05-15 21:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
>                  if (state is not null && _applyDefaults)
nit: reduce nesting with early exit.

2023-05-16 07:55 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +        private static readonly TraceSwitch? s_trace;
I followed the blueprint set [here](https://github.com/dotnet/winforms/pull/8072#discussion_r1009826425). That's why I moved `TraceSwitchExtensions` from `System.Windows.Forms` to `System.Windows.Forms.Primitives`. If you prefer another approach I'll change the code accordingly

2023-05-16 08:12 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                Hashtable state = new Hashtable(_objects!.Count);
`state` is assigned to private field `_objectState`, which is serialized at line 598 (old) / 554 (new). That made me a bit nervous about changing both objects' type, but if you think it's safe and that this code is the only one also deserializing, then I'd be happy to change them as well. I can prepare a commit in that direction that we can scrap if it's incorrect

2023-05-16 08:33 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                Hashtable state = new Hashtable(_objects!.Count);
Okay, I think you were right, it looks safe. I pushed the change. Thanks!

2023-05-16 13:15 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                else if (data is not null)
Okay, apparently it breaks the unit tests because of [this line](https://github.com/dotnet/winforms/blob/1a1608fe3661728a8c3bc50959f5e0145b62ea48/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs#LL553C11-L553C11), but [this comment](https://github.com/dotnet/winforms/blob/1a1608fe3661728a8c3bc50959f5e0145b62ea48/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs#L547) makes me wonder if we couldn't just update the tests. What do you think?

2023-05-16 17:00 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            private void PopulateCompleteStatements(object? data, string name, CodeStatementCollection completeStatements)
in such case, i would exit early in the function if it is null.

2023-05-16 18:36 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            private void PopulateCompleteStatements(object? data, string name, CodeStatementCollection completeStatements)
I've already made the change following your earlier comments

2023-05-16 18:43 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                Hashtable state = new Hashtable(_objects!.Count);
Okay, apparently it breaks the unit tests because of [this line](https://github.com/dotnet/winforms/blob/1a1608fe3661728a8c3bc50959f5e0145b62ea48/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs#LL553C11-L553C11), but [this comment](https://github.com/dotnet/winforms/blob/1a1608fe3661728a8c3bc50959f5e0145b62ea48/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs#L547) makes me wonder if we couldn't just update the tests. What do you think? Should I rollback the last commit?

2023-05-17 08:18 UTC, halgab commented
Following [this comment](https://github.com/dotnet/winforms/pull/9120#discussion_r1194375880), I tried to modify the state hashtables with dictionaries. It makes the tests break because they control the content of those hashtables, but checking again, only the tests access them directly. They do through the `ISerializable` interface which is implemented by private class [`CodeDomSerializationStore`](https://github.com/dotnet/winforms/blob/1a1608fe3661728a8c3bc50959f5e0145b62ea48/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs#L174)
So I think these objects can be refactored safely. I then tried to push the refactoring further and replace the `object[]` array with a strongly typed, dedicated state object. All tests were updated accordingly.
I understand if you think this is to big of a change, and I can easily rollback the commits that have to do with the state Hashtables

2023-06-21 20:01 UTC, dreddy-work commented
This needs a thorough review. Requesting @JeremyKuhne and @Tanya-Solyanik on this.

2023-09-12 08:18 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +        return cdStore.Deserialize(_provider!);
`_provider` is initialised in the constructor (line 31), but there is another public constructor without any arguments that inits this field to null

2023-09-12 08:19 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +        return cdStore.Deserialize(_provider!, container);
Same thing here

2023-09-12 10:06 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                    if (!_expressions!.TryGetValue(name, out List<CodeExpression>? exps))
`ComponentListCodeDomSerializer` is used as a singleton. `_expressions` is used only for deserialisation. `_statementsTable` follows the same pattern.

I tried to change the `Deserialize` method to be a static method rather than calling an instance method on `s_instance`, with the hope that I could change `_expressions` to be a local variable that I could pass along methods. I hit a wall because the method `OnResolveName` is called as a callback to an event, and it needs access to `_expressions` (through its call to the `ResolveName` method).

We could always init `_expressions` and `_statementsTable` to a new empty (and arguably useless) dictionary at the creation of any `ComponentListCodeDomSerializer` instance, e.g.

`private Dictionary<string, List<CodeExpression>> _expressions = new();`

Another option would be to write

`private Dictionary<string, List<CodeExpression>> _expressions = null!;`

It's not great, but it's valid given current use cases of the field.

Let me know if/how you want to change this

2023-09-14 04:16 UTC, LeafShi1 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +        return cdStore.Deserialize(_provider!);
Sorry for my issue, I mean _provider may be null here, so using ! here may be caused exception.

2023-09-14 07:12 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +        return cdStore.Deserialize(_provider!);
Okay, sorry. I've just pushed a commit to address this, but it slightly changes the behaviour. One path used to throw an NRE, and that's no longer the case, but I think it's fine. Let me know what you think

2023-09-14 08:50 UTC, LeafShi1 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                    if (!_expressions!.TryGetValue(name, out List<CodeExpression>? exps))
Instead of using `private Dictionary<string, List<CodeExpression>> _expressions = null!;` why not add a non-null judgment before using _expressions

2023-09-14 09:10 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                    if (!_expressions!.TryGetValue(name, out List<CodeExpression>? exps))
you mean something like `if (_expressions is null || !_expressions.TryGetValue(name, out List<CodeExpression>? exps))`?

2023-09-20 02:45 UTC, LeafShi1 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                    if (!_expressions!.TryGetValue(name, out List<CodeExpression>? exps))
Yes, like 
 ```
_if (_expressions is not null)
 {
     // we handle expressions a little differently since they don't have a LHS or RHS they won't show up correctly in the statement table. We will deserialize them explicitly.
     if (!_expressions.TryGetValue(name, out List<CodeExpression>? exps))
     {
         exps = new();
         _expressions[name] = exps;
     }

     exps.Add(expression);
 }_
```

2023-09-20 08:17 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                    if (!_expressions!.TryGetValue(name, out List<CodeExpression>? exps))
I didn't add a null check on `_expressions` because here we know for a fact that ir's not null. The method `PopulateCompleteStatements` is only called by the method `Deserialize`, just after `_expressions = new();`
To make that explicit, I'm pushing a change where we pass `_expressions` as an argument to `PopulateCompleteStatements` (which is now static. It's a poor method name btw as it also populates expression, but I can't think of anything good as a replacement)

2023-10-02 20:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            _objects = new Dictionary<object, ObjectData>();
may be we should declare `_objects `read only and avoid assigning to `null`. Instead, just clear dictionary in the close and leave it to GC.

2023-10-02 20:54 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            s_trace.TraceVerbose($"ComponentSerialization: Adding object '{data._name}' ({data._value.GetType().FullName}:{member.Name}) {(absolute ? "ABSOLUTE" : "NORMAL")}");
why not move this verbose log inside `GetOrCreateObjectData` ?

2023-10-02 21:07 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            private Dictionary<string, List<CodeExpression>>? _expressions;
nit: Would declare this read-only with assignment and clear it before `deserialize()`.

2023-10-02 21:11 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +                if (statements is not null)
nit: return early and reduce nesting?

2023-10-02 21:15 UTC, dreddy-work submitted a review, later dismissed
adding @JeremyKuhne  and @lonitra  to take a second look.

2023-10-03 07:25 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
> +            s_trace.TraceVerbose($"ComponentSerialization: Adding object '{data._name}' ({data._value.GetType().FullName}:{member.Name}) {(absolute ? "ABSOLUTE" : "NORMAL")}");
The logs after the 2 callsites of method `GetOrCreateObjectData` are slightly different. I think that putting the tracing inside the method would complicate it with limited benefits, but I can do it anyway if you want me to.

2023-10-03 16:37 UTC, lonitra reviewed
Nice work!

2023-10-03 16:37 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeMethodMap.cs
> -        Method = method;
Why was this removed from the constructor?

2023-10-03 16:37 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs
> +                            if (statements.Count > 0)
Let's use else if to reduce nesting here

2023-10-03 16:37 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs
> +                                        resolved = true;
Is `DeserializeExpression` doing any state change? If not, I believe we maybe be able to `break` after this since once `resolved = true` we'll never go into the if statements again

2023-10-03 16:37 UTC, lonitra commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs
> +                                    if (canInvokeManager && manager.GetInstance(name) is null)
Please combine these

2023-10-03 20:02 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeMethodMap.cs
> -        Method = method;
Because it was always called with a null `method`

2023-10-04 21:11 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs
> +                        PropertyDescriptorCollection eventProps = ebs.GetEventProperties(TypeDescriptor.GetEvents(comp));
Well, `IEventBindingService` is annotated, and `GetEventProperties` is supposed not to be null. I guess the null check protects us against implementations that don't respect this contract, but I can remove it if you want

2023-10-04 21:26 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs
> +                                        resolved = true;
I don't think it changes any state but it's such a huge method, I can't say I'm a 100% sure...

2023-10-10 17:33 UTC, lonitra approved these changes
LGTM!

2023-10-11 19:37 UTC, merged

2023-10-11 19:58 UTC, halgab commented
🥳