Enable nullability in remaining ToolTip members
dotnet/winforms pull request #9130
Opened 2023-05-16 17:02 UTC by gpetrou

## Proposed changes

- Enable nullability in remaining ToolTip members.

2023-05-16 19:55 UTC, dreddy-work requested changes

2023-05-16 19:55 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +    private string? _toolTipCaption = string.Empty;
why? i don't see it would ever be null.

2023-05-16 19:55 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +    private string? _controlTipText = string.Empty;
same here.

2023-05-16 19:55 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
> +        string? tipText = GetToolTipText(GetTabPage(commandID));
this shouldn't either.

2023-05-16 19:55 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> +        string? caption = GetToolTip(control);
same.

2023-05-16 19:55 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
> +        string? caption = toolTip.GetToolTip(this);
here too.

2023-05-30 23:06 UTC, dreddy-work commented
waiting on author.

2023-06-19 18:47 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +    private string? _toolTipCaption = string.Empty;
I made this and the other items nullable because the methods such as `GetToolTip` return nullable. Should I use a null-forgiving operator instead?

2023-06-21 19:59 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +    private string? _toolTipCaption = string.Empty;
Current state of `GetToolTip` is not returning null. Can you point me to code where this is true?

2023-06-22 05:29 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +    private string? _toolTipCaption = string.Empty;
In current main, nullability is not enabled in this part of the file.
It is enabled in this PR.
Please check https://github.com/dotnet/winforms/pull/9130/files#diff-f722fa05d83cae80d8fb79d78bcdae58f57170fcf56479a1a8cda42db71e6155R1029
`tipInfo.Caption` is nullable.

2023-07-03 17:20 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> +            ? tipInfo.Caption
@Tanya-Solyanik, I am inclining to make changes on the [TipInfo.Caption](https://github.com/dotnet/winforms/blob/d4388546b5ee57f1bdc6f13bb703d9b1602073c2/src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.TipInfo.cs#L26) as non-nullable and return `string.empty` in those cases and avoid `!` in many places. Do you see any concerns?

2023-07-04 05:43 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> +            ? tipInfo.Caption
The `TipInfo` constructor is called in many places with `caption` possibly null though. What would we do in such cases?

2023-07-05 17:05 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> +            ? tipInfo.Caption
I wouldn't touch them yet. Only caption property's setter. Let me think it through. Will update this

2023-07-10 22:22 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
> +            ? tipInfo.Caption
`Caption `is passed to native API and native APIs expect null. So, we may not want to change it. Certainly, without complete scenario validations.

2023-07-10 22:23 UTC, dreddy-work approved these changes

2023-07-10 22:24 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +    private string? _toolTipCaption = string.Empty;
We can not avoid Caption being null give Native APIs using this allows it to be null.

2023-07-10 22:24 UTC, merged