Enable nullability in WebBrowserBase
dotnet/winforms pull request #9350
Opened 2023-06-23 06:02 UTC by gpetrou

## Proposed changes

- Enable nullability in WebBrowserBase.

2023-06-25 08:29 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
> +            ScrollableControl? f = ctl.ContainingControl;
Need a better variable name.

2023-06-25 08:29 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
> +        ContainerControl? f = site.ContainingControl;
Same here.

2023-07-03 17:42 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> -    private IOleObject.Interface axOleObject;
Can you fix naming violations in this file?

2023-07-03 17:44 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> +        axOleObject?.GetExtent(DVASPECT.DVASPECT_CONTENT, (SIZE*)&size);
why not `!`  ?

2023-07-03 17:46 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> -    private IOleObject.Interface axOleObject;
follow-up PR should fine.

2023-07-05 16:59 UTC, dreddy-work requested changes

2023-07-05 16:59 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> +            _axSite ??= CreateWebBrowserSiteBase();
nit: convert to an expressional body.

2023-07-05 16:59 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> +            _selectionChangeHandler ??= new EventHandler(OnNewSelection);
same here.

2023-07-05 16:59 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> +            return _axEditMode != WebBrowserHelper.AXEditMode.None;
same here and also check other places in this file.

2023-07-05 16:59 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> +        ContainerControl? cc = null;
`cc ->containerControl`

2023-07-05 16:59 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
> +                    object? ax = webBrowserBase._activeXInstance;
`ax -> activeX`

2023-07-08 09:01 UTC, gpetrou commented
@dreddy-work any more feedback on this one?

2023-07-10 16:50 UTC, dreddy-work requested changes
RLGTM.

2023-07-10 16:50 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> +        return _ignoreDialogKeys ? false : base.ProcessDialogKey(keyData);
nit: move to expression body.

2023-07-10 16:50 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> +        return _axHostState[mask];
same here.

2023-07-10 16:50 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> +        _wbContainer ??= new WebBrowserContainer(this);
move to expression body.

2023-07-10 16:50 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
> +        _axSite ??= CreateWebBrowserSiteBase();
nice!.

2023-07-10 19:57 UTC, dreddy-work approved these changes

2023-07-10 20:16 UTC, merged