Use `KEYEVENTF_EXTENDEDKEY` flag only extended keys
dotnet/winforms pull request #9354
Opened 2023-06-23 13:16 UTC by DJm00n

Use `KEYEVENTF_EXTENDEDKEY` flag only when calling SendInput function with scan codes that have 0xE0 prefix.

See:
https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-keybdinput https://learn.microsoft.com/windows/win32/inputdev/about-keyboard-input#extended-key-flag

2023-06-23 18:06 UTC, sharwell commented on src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Input/InputBuilder.cs
> +                    dwFlags = (scanCode & 0xFF00) == 0xE000 ? KEYBD_EVENT_FLAGS.KEYEVENTF_EXTENDEDKEY : 0,
💭 Do we need to add handling for `0xE100`?

2023-06-23 18:09 UTC, sharwell commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
> -        if (VirtualKeyUtilities.IsExtendedKey(vk))
❔ Should we assert that `vk` is only one of the two known values passed by a caller (neither of which is an extended key)?

2023-06-23 18:13 UTC, sharwell commented on src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
> -        if (VirtualKeyUtilities.IsExtendedKey(vk))
❓ Considering this path always used to set `KEYBD_EVENT_FLAGS.KEYEVENTF_EXTENDEDKEY` (the two inputs are VIRTUAL_KEY.VK_RIGHT` and `VIRTUAL_KEY.VK_LEFT`, both of which were considered extended), is there a reason we are no longer doing so?

2023-06-23 18:14 UTC, sharwell commented on src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
> -                        if (IsExtendedKey(skEvent))
❔ How do we know `skEvent` isn't going to be extended?

2023-06-26 14:05 UTC, sharwell requested changes
Flagging this one for a more detailed internal review.

Reviewer note: Please feel free to reach out to me internally to help move it forward.

2023-07-07 19:26 UTC, JeremyKuhne commented
@DJm00n @sharwell do we have a specific scenario that is broken? What is broken that this is fixing?

2023-07-07 22:46 UTC, DJm00n commented
@JeremyKuhne there shouldn't be any visible change in behaviour. I just removed a bit of useless code.

2023-09-07 08:49 UTC, DJm00n commented
@sharwell do you have any updates on this topic?

2023-09-13 16:48 UTC, sharwell commented
I'm hesitant to make a change in this space unless an observable bug is identified, and/or an expert within the Windows team explains why the change would be needed.

2023-09-13 19:42 UTC, DJm00n commented
@sharwell maybe you can ask someone from Windows team to review this?

2023-10-02 21:19 UTC, dreddy-work commented
Given the concerns and no reported issue, this cleanup isn't prioritized now. Also, some of these constants may be converted to CSwin32.

Closing the PR.

2023-10-02 21:19 UTC, closed without merging