fix Accessible properties AccessKey and KeyboardShortcut ignore UseMnemonic = false
dotnet/winforms pull request #9365
Opened 2023-06-25 10:22 UTC by Epica3055

Fixes #9296 

## Proposed changes

- 
- Before return shortcut and name, add if useMnemonic condition
- 

## Regression? 

-  No

## Risk

-

## Screenshots 

### Before

![image](https://github.com/dotnet/winforms/assets/135201996/425359e5-878d-49e6-ac8b-ba97323b967b)

### After

![image](https://github.com/dotnet/winforms/assets/135201996/81c43eb8-b884-41c5-bbf1-cbd674e034ee)

## Test methodology 

- 
- manually
-

2023-06-26 17:49 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +        }
```suggestion
        private bool GetOwnerUseMnemonic(Control? control)
        {
            if (control is null)
            {
               return true;
            }

            Reflection.PropertyInfo? propertyInfo = control.GetType().GetProperty(nameof(ButtonBase.UseMnemonic));
            if (propertyInfo is not null && propertyInfo.GetValue(control) is bool useMnemonic)
            {
                return useMnemonic;
            }

            if (PreviousLabel is not null)
            {
                return PreviousLabel.UseMnemonic;
            }

            return true;
        }
```

2023-06-26 17:52 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +        }
And change/simplify use cases.

2023-06-27 02:31 UTC, Epica3055 commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +        }
did you mean like this one?
![image](https://github.com/dotnet/winforms/assets/135201996/7aa7cb7f-7549-422e-a340-e8611133d098)

2023-06-27 07:38 UTC, Epica3055 commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +        private bool GetOwnerUseMnemonic(Control control)
I have a different point of view. Actually, not every control has a UseMnemonic property(like TextBox), only a few controls have it.
But a control may have a label before it. Label has UseMnemonic Property, I think this label could determine UseMnemonic  of the control. So I think basicly every contol has UseMnemonic  property.
Maybe using reflection is a little bit easier than to implement virtual function in every derived AO class of control accessible object

2023-06-27 07:54 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +        private bool GetOwnerUseMnemonic(Control control)
Then the default implementation on Control class should return `true`.

2023-06-27 17:28 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +        private bool GetOwnerUseMnemonic(Control control)
Perhaps we could handle shortcuts from `TextLabel` and from Button/Label's mnemonic separately? If there is a Label with `UseMnemonic = true; Text = "&Text"` and next to it a Button with `UseMnemonic = false; Text = "a&b"`, the button will be accessible by Alt+T shortcut. But with current implementation, it won't have this shortcut in `KeyboardShortcut` property.

2023-06-27 17:49 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +        private bool GetOwnerUseMnemonic(Control control)
@dmitrii-drobotov  - good point and thank for testing the behavior!  

This comment, however, was about reflection. We are trying to not use it for performance reasons and because reflection prevents making these controls trimmable - https://learn.microsoft.com/dotnet/core/deploying/trimming/trim-self-contained. We are not trimmable as a whole yet, but are working to enable it in the future. So a virtual method is a better route as it avoids reflection.

2023-06-28 07:11 UTC, Epica3055 commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +        }
@dreddy-work could you please take a look at this?

2023-06-28 19:17 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +            Reflection.PropertyInfo? propertyInfo = control.GetType().GetProperty(nameof(ButtonBase.UseMnemonic));
Please get rid of reflection in this code.

2023-06-28 19:28 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +            Reflection.PropertyInfo? propertyInfo = control.GetType().GetProperty(nameof(ButtonBase.UseMnemonic));
UseMnemonic property on button controls can be used to set `ControlStyles.UseTextForAccessibility`, then the existing logic will take it into account

2023-07-03 17:10 UTC, dreddy-work requested changes

2023-07-03 17:10 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +            get
also , other places in this PR.

2023-07-03 17:10 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelAccessibleObject.cs
> +                if (!this.TryGetOwnerAs(out Label? owner) || !owner.UseMnemonic)
conditional return with expression body.

2023-07-03 18:42 UTC, Tanya-Solyanik reviewed
Thank you for simplifying the change!

2023-07-03 18:42 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.RadioButtonAccessibleObject.cs
> +        public override string? KeyboardShortcut
Please add a blank line above this method.

2023-07-03 18:42 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Button.ButtonAccessibleObjectTests.cs
> +        var buttonAccessibleObject = new Button.ButtonAccessibleObject(button);
Consider introducing an alias for `Button.ButtonAccessibleObject` and other nested accessible objects where you touched the test files in this PR.
```
using ButtonAccessibleObject = Button.ButtonAccessibleObject;
```

2023-07-03 18:42 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBox.CheckBoxAccessibleObjectTests.cs
> +        var buttonAccessibleObject = new CheckBox.CheckBoxAccessibleObject(checkBox);
Consider renaming `buttonAccessibleObject ` -> `accessibleObject` in all changes tests.

2023-07-03 18:42 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBox.CheckBoxAccessibleObjectTests.cs
> +        var buttonAccessibleObject = new CheckBox.CheckBoxAccessibleObject(checkBox);
Alternatively, consider creating a theory test, where you pass in typeof control to create and typeof accessible object to create.  In fact, this theory should be working for almost all controls.  @dmitrii-drobotov  - do we have anything like this already?

This could be done in a follow up PR.

2023-07-03 18:42 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +                return ButtonBaseAccessibleObject.GetKeyboardShortcut(owner, false, PreviousLabel);
Please add parameter name in front of the literal. This applies to multiple changes in this PR.

2023-07-04 02:08 UTC, Epica3055 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Button.ButtonAccessibleObjectTests.cs
> +        var buttonAccessibleObject = new Button.ButtonAccessibleObject(button);
It looks like I can't use using, because ButtonAccessibleObject doesn't implement IDisposable.

2023-07-04 02:44 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Button.ButtonAccessibleObjectTests.cs
> +        var buttonAccessibleObject = new Button.ButtonAccessibleObject(button);
`using` as an alias definition - https://learn.microsoft.com/dotnet/csharp/language-reference/keywords/using-directive#using-alias

2023-07-04 06:32 UTC, Epica3055 commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBox.CheckBoxAccessibleObjectTests.cs
> +        var buttonAccessibleObject = new CheckBox.CheckBoxAccessibleObject(checkBox);
I don't fully understand.

2023-07-04 15:54 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBox.CheckBoxAccessibleObjectTests.cs
> +        var buttonAccessibleObject = new CheckBox.CheckBoxAccessibleObject(checkBox);
Yes, there is a similar test: https://github.com/dotnet/winforms/blob/918e34631094c184e6b29d659842b540f092ed98/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs#L1251-L1271

@Epica3055 - this PRs adds many very similar tests, it would be cleaner to use a theory test like above with type of control as argument to reduce duplication.

2023-07-04 18:06 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +        public override string? Name => this.TryGetOwnerAs(out ButtonBase? owner) && owner.UseMnemonic ? base.Name : TextLabel;
I'm not sure if it correctly handles custom `AccessibleName` with `UseMnemonic = false`. Could you please test it? We might need to do something like in `base.Name` but return just `TextLabel` without `WindowsFormsUtils.TextWithoutMnemonics`:
https://github.com/dotnet/winforms/blob/918e34631094c184e6b29d659842b540f092ed98/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs#L286-L300

2023-07-05 17:20 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
> +        }
Looks `GetOwnerUseMnemonic` method is complete removed. So this comment is not valid anymore.

2023-07-05 22:12 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +                {
If the owner is gone, we can short-circuit. If there is no owner, there is no PreviousLabel for TextLabel to read either. See ConstrolAccessibleObject class. And since the base class is repeating logic from this method, I would not call it, but simply repeat the code from the base class here.

```
                if (!this.TryGetOwnerAs(out ButtonBase? owner))
                {
                    return null;
                }
    
                if (owner.AccessibleName is { } name)
                {
                    return name;
                }

                return owner.UseMnemonic ? WindowsFormsUtils.TextWithoutMnemonics(TextLabel) : TextLabel;
```

2023-07-05 22:12 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.RadioButtonAccessibleObject.cs
> +        public override string? Name
This method can be inherited from ButtonBase.

2023-07-06 02:28 UTC, Epica3055 commented on src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.RadioButtonAccessibleObject.cs
> +        public override string? Name
Sorry, I don't fully understand. RadioButtonAccessibleObject doesn't derive from ButtonBaseAccessibleObject

2023-07-06 17:46 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.RadioButtonAccessibleObject.cs
> +        public override string? Name
Oh, I see, this is unfortunate. This PR is ok as is then.

2023-07-06 17:48 UTC, Tanya-Solyanik submitted a review, later dismissed

2023-07-06 18:16 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +                }
```suggestion
            mnemonic = WindowsFormsUtils.GetMnemonic(previousLabel.Text, false);
```

You do not need explicit check. `GetMnemonic` handle null or empty strings.

2023-07-06 18:16 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +                }
same here.

2023-07-06 18:16 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelAccessibleObject.cs
> +                if (!this.TryGetOwnerAs(out Label? owner))
why not move this logic to `ControlAccessibleObject`? and simply call.

```CS
   return owner.UseMnemonic ? base.Name : TextLabel;
```

Also, if natively parented, do we leave accessible name as `null`?

2023-07-06 18:23 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +            }
I'm not sure if it correctly handles case when button has `UseMnemonic = true` and its `Text` doesn't contain a mnemonic shortcut, but previous label does, like this:
![image](https://github.com/dotnet/winforms/assets/102954094/3600b9b0-6863-4f68-94fc-d0af00f8ba1e)

The button can be focused by Alt+L, but the shortcut will be empty. Could you look into this as well?

2023-07-06 18:40 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelAccessibleObject.cs
> +                if (!this.TryGetOwnerAs(out Label? owner))
I see Control does not have `UseMnemonic`  and with offlien discussion with Tanya, it may not worth moving logic to base class here.

2023-07-07 04:20 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +            char mnemonic = (char)0;
It is more concise and readable to use` char mnemonic = '\0';` here

2023-07-07 05:43 UTC, LeafShi1 approved these changes

2023-07-07 05:45 UTC, LeafShi1 commented
> Fixes #9296
> 
> ## Proposed changes
> * Before return shortcut and name, add if useMnemonic condition
> 
> ## Regression?
> * No
> 
> ## Screenshots
> ### Before
> ![image](https://user-images.githubusercontent.com/135201996/248547374-425359e5-878d-49e6-ac8b-ba97323b967b.png)
> 
> ### After
> ![image](https://user-images.githubusercontent.com/135201996/248547475-81c43eb8-b884-41c5-bbf1-cbd674e034ee.png)
> 
> ## Test methodology
> * manually and Unit Tests
> 
> ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9

2023-07-07 05:48 UTC, LeafShi1 commented
Please add more description on 
![image](https://github.com/dotnet/winforms/assets/132890443/14f0a4ea-e851-44bc-9db2-e1da3756885e)

2023-07-07 18:14 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +        }
I think we can use `WindowsFormsUtils.ContainsMnemonic` instead of this method

2023-07-07 18:14 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
> +        yield return new object[] { typeof(CheckBox) };
There is also the `LinkLabel` with `UseMnemonic`, but its accessible object already extends from `LabelAccessibleObject`. Could you check if it behaves correctly with these changes? And also include it into unit tests.

2023-07-10 05:35 UTC, SimonZhao888 approved these changes

2023-07-10 13:38 UTC, dmitrii-drobotov reviewed
Just some code style comments, the rest looks good to me!

2023-07-10 13:38 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +            ? ButtonBaseAccessibleObject.GetKeyboardShortcut(control: owner, useMnemonic: false, previousLabel: PreviousLabel)
We usually specify parameter names only for literal values (`false`, `"text"`, `10`, `null`, etc.). For variables or properties we can omit it.
```suggestion
            ? ButtonBaseAccessibleObject.GetKeyboardShortcut(control: owner, useMnemonic: false, PreviousLabel)
```
Same for a few other changes in this PR.

2023-07-11 10:22 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +                mnemonic = WindowsFormsUtils.GetMnemonic(control?.Text, false);
Nit: `control` variable is not nullable, so we don't have to check it for null.
```suggestion
            if ((!useMnemonic || !WindowsFormsUtils.ContainsMnemonic(control.Text)) && previousLabel is not null && previousLabel.UseMnemonic)
            {
                mnemonic = WindowsFormsUtils.GetMnemonic(previousLabel.Text, false);
            }
            else if (useMnemonic)
            {
                mnemonic = WindowsFormsUtils.GetMnemonic(control.Text, false);
```

2023-07-11 10:22 UTC, dmitrii-drobotov commented on src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObject.cs
> +                mnemonic = WindowsFormsUtils.GetMnemonic(previousLabel.Text, false);
Could you also specify parameter name for `GetMnemonic` calls?
```suggestion
                mnemonic = WindowsFormsUtils.GetMnemonic(previousLabel.Text, convertToUpperCase: false);
```

2023-07-12 01:55 UTC, Tanya-Solyanik approved these changes
Please let @dmitrii-drobotov and @dreddy-work finish their reviews before merging

2023-07-12 18:22 UTC, dreddy-work approved these changes

2023-07-12 18:22 UTC, merged