Enable nullability in DesignerActionService, DesignerActionUIService, DesignerActionUI and SelectionManager
dotnet/winforms pull request #9367
Opened 2023-06-25 14:14 UTC by halgab

## Proposed changes

- Enable nullability in `DesignerActionService`, `DesignerActionUIService`, and all the internal code these classes use: `DesignerActionUI` and `SelectionManager`

2023-06-26 22:39 UTC, dreddy-work commented
Check the build failures.

2023-06-30 21:58 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
> +        void IWindowsFormsEditorService.DropDownControl(Control? control)
Did you check if interface declaration can be changed on nullability? I don't see any internal reference that passing null in.

2023-07-01 12:35 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
> +        void IWindowsFormsEditorService.DropDownControl(Control? control)
I had a look following your comment. Internally, I don't see any reference passing null. As for the implenting types, I saw another one that assumed this parameter wouldn't be null. I'll change the interface annotation accordingly, and see if the CI agrees with our analysis

2023-07-03 17:51 UTC, dreddy-work requested changes

2023-07-03 17:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.CheckBoxPropertyLine.cs
> +        private CheckBox? _checkBox;
can this be assigned in constructor or currently, any of its properties changed from constructor to current initialization? Wanted to see if we can avoid `!` all over.

2023-07-03 17:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
> +        private EditorButton? _button;
same with `_button`. if we ensure dispose of it if not used, i think we can avoid `!`

2023-07-03 20:24 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.CheckBoxPropertyLine.cs
> +        private CheckBox? _checkBox;
I attempted a big shake-up of the code to avoid that, and got afraid it was too big of a change, I can try again and let you assess if it's too ambitious.

The problem I remember adding though is that the method `AddControls` is only called through `GetControls`, which is called only when we end up actually using the created `Line` objects.

2023-07-03 20:34 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.CheckBoxPropertyLine.cs
> +        private CheckBox? _checkBox;
Try in a separate PR and see if we can take it independently before this.

2023-07-03 22:15 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.CheckBoxPropertyLine.cs
> +        private CheckBox? _checkBox;
My idea was [this](halgab/winforms#1). I know I need to move some classes around before this is good to merge, but I wanted your opinion on it because it feels pretty heavy. And I don't know if I should bring the PR to this repo instead?

2023-07-03 22:49 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.CheckBoxPropertyLine.cs
> +        private CheckBox? _checkBox;
I can not access that link. You can push as draft PRs if you have draft changes. I will make sure me/someone on the team take a look later this week and share next steps.

2023-07-04 09:49 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.CheckBoxPropertyLine.cs
> +        private CheckBox? _checkBox;
I opened #9422. The end result is a lot simpler than what I thought it would be.

2023-07-19 06:29 UTC, LeafShi1 commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.TextBoxPropertyLine.cs
>                  }
This part can use ternary expressions to make the code more concise 
` int specialPadding = EditControl is TextBox ? 2 : 0;`

2023-07-19 07:06 UTC, LeafShi1 approved these changes

2023-07-19 20:26 UTC, halgab commented
Thanks for your review @LeafShi1. Did you get a chance to have a look at the version in #9422?

2023-07-20 13:33 UTC, halgab commented
I applied review feedback, rebased to solve conflicts, and mirrored the changes in #9422

2023-10-20 08:03 UTC, halgab commented
This is superseded by numerous PRs that break down the work started here

2023-10-20 08:03 UTC, closed without merging