Enable nullability in DesignerUtils and replace ArrayList with List
dotnet/winforms pull request #9381
Opened 2023-06-27 20:47 UTC by halgab

## Proposed changes

- Enable nullability in internal helper `DesignerUtils`.
- Replace a few `ArrayList`s with List<T> (contributes to #8140). This change should make it easier to annotate all the files touched by this refactoring

2023-06-28 23:13 UTC, elachlan commented
Why the change away from `IComponent` to `Control`?

2023-06-29 05:42 UTC, halgab commented
Because we keep casting the `IComponent`s to `Control`, to the point where they can't not be `Control` instances. So I figured it would be simpler to be more specific and stop casting around all the time.

2023-06-29 08:45 UTC, elachlan commented
Awesome. Sounds good.

2023-06-30 07:31 UTC, halgab reviewed
I think I might have been a bit too optimistic. I'll rollback to a less ambitious version. I'll put this PR back to draft in the meantime

2023-06-30 07:31 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
> +        foreach (T childComp in designer.AssociatedComponents)
I **think** that if this doesn't hold, we're going to break later, but I'm not 100% sure

2023-07-05 09:52 UTC, LeafShi1 approved these changes

2023-07-05 18:15 UTC, dreddy-work requested changes
Logically looks good but hard to validate these design scenarios at runtime.

Any possibility to add some unit tests around these changes?

2023-07-05 18:15 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
> +    private Control[] dragObjects; // used to initialize the DragAssistanceManager
why do you need it to be changed to array?

Also can you see if you can fix naming violations in this PR?

2023-07-05 18:28 UTC, halgab commented
I'm usually having a pretty hard time running tests locally, but sure, I'll have a look. I understand your concerns

2023-07-05 18:31 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
> +    private Control[] dragObjects; // used to initialize the DragAssistanceManager
I'll have to double check (not in front of my computer right now), but I think I needed the variance of arrays to pass it to a method expecting an `IReadonlyList<IComponent>`

2023-07-06 10:02 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
> +    private Control[] dragObjects; // used to initialize the DragAssistanceManager
Okay, my bad, I can declare it as a 'List<Control>' without any issues. I'll make the change

2023-07-06 22:21 UTC, dreddy-work commented
> I'm usually having a pretty hard time running tests locally, but sure, I'll have a look. I understand your concerns

Let me know what kind of issue you see when running tests locally.  If you start VS using `start-vs.cmd` from the repo root, it should load everything needed.

2023-07-21 20:07 UTC, dreddy-work commented
We will take this early in 9.0

2023-09-14 03:11 UTC, Epica3055 commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
> -            selSvc = (ISelectionService)serviceProviderTarget.GetService(typeof(ISelectionService));
Also, for readability, avoid abbreviation.  `selSvc ` to `selectionService `. And other multiple places.

2023-09-14 07:22 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
> +        if (c.Site is not null && !(c.Site is INestedSite) && _destHost is not null)
This file is not annotated as part of this PR. Do you still want me to address this here, or should I wait for a dedicated PR?

2023-09-14 07:22 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
> -            selSvc = (ISelectionService)serviceProviderTarget.GetService(typeof(ISelectionService));
https://github.com/dotnet/winforms/pull/9381#discussion_r1325480907

2023-09-15 02:12 UTC, Epica3055 commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
> +        if (c.Site is not null && !(c.Site is INestedSite) && _destHost is not null)
I think maybe you can do it in this PR, since it doesn't require many changes.

2023-09-15 02:14 UTC, Epica3055 commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
> -            selSvc = (ISelectionService)serviceProviderTarget.GetService(typeof(ISelectionService));
[discussion_r1326703412](https://github.com/dotnet/winforms/pull/9381#discussion_r1326703412)

2023-09-15 09:17 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
> +        if (c.Site is not null && !(c.Site is INestedSite) && _destHost is not null)
That's done. This file could use some cleanup on other aspects, but I'll leave that for a subsequent PR

2023-10-10 22:28 UTC, KlausLoeffelmann requested changes
I have only started to look through this, but I am not at all feeling comfortable taking this.

Why can we assume, that the behaviors/designers only process Controls and no (I)Components or other objects?

I know in the Out-Of-Proc Designer, for example, this would not work.

But maybe I am missing some additional information or have not read previous discussions, so I am happy to hear more about this!

Thx!

2023-10-10 22:28 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ContainerSelectorBehavior.cs
> +        List<Control> dragControls = new();
Why do we want to change this from `IComponent` to `Control`?

2023-10-10 22:28 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
> +    internal DragAssistanceManager(IServiceProvider serviceProvider, IReadOnlyList<IComponent> dragComponents, bool resizing) : this(serviceProvider, null, dragComponents, null, resizing, false)
Would this not break backwards-compatibility in certain custom Designer scenarios? What makes us sure, that it doesn't?

2023-10-10 22:28 UTC, KlausLoeffelmann commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.BehaviorDataObject.cs
> +        public BehaviorDataObject(List<Control> dragComponents, Control source, DropSourceBehavior sourceBehavior) : base()
How can we be sure only be getting controls at this point?

2023-10-11 06:34 UTC, RussKie commented
> * Enable nullability in internal helper `DesignerUtils`.
> * Replace a few `ArrayList`s with` List<T>`s (contributes to [Convert `ArrayList` usage to `List<T>` where possible #8140](https://github.com/dotnet/winforms/issues/8140)). This change should make it easier to annotate all the files touched by this refactoring

These are two different kind of changes that must not be mixed together. The latter one has much higher risk of introducing a breaking change.

2023-10-11 09:05 UTC, halgab commented
Yes, I get now that my attempt at a refactoring here got out of hand and shouldn't be mixed with the nullability here. I'll revisit this PR. My feeling is that replacing `ArrayList`s with `List`s help with the nullability annotations, so if that's okay with the team, I'll attempt to address the second bullet point in a first PR (staying conservative this time, again sorry for the mess here), and then follow-up with a NRT annotation PR.

2023-10-11 09:25 UTC, halgab commented
I've just opened #10091 that focus solely on the `ArrayList` removal. This should be easy to review

2023-10-27 20:14 UTC, halgab commented
Closed in favor of #10091, #10092 and #10183

2023-10-27 20:14 UTC, closed without merging