Add unit tests to ToolboxItem and ComponentDesigner #714
dotnet/winforms pull request #9483
Opened 2023-07-13 07:26 UTC by Epica3055

…arkers. Add Verbs,GetService,PostFilterProperties unitTests

Related to https://github.com/dotnet/winforms/issues/714

## Proposed changes

-  Remove codeMarkers. 
-  Add Verbs,GetService,PostFilterProperties unitTests

## Test methodology 

- 
- Unit Tests
- 

## Test environment(s) 

- 8.0.0-preview.7.23360.15

2023-07-13 17:11 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
> +        using var designer = new ComponentDesigner();
```suggestion
        using ComponentDesigner designer = new();
```

2023-07-13 17:13 UTC, dreddy-work requested changes
added suggestion.

2023-07-13 17:32 UTC, Tanya-Solyanik reviewed
Looks good, I added only a minor comment.

2023-07-14 03:18 UTC, Tanya-Solyanik approved these changes
Thank  you!

2023-07-14 14:46 UTC, dmitrii-drobotov submitted a review, later dismissed

2023-07-14 16:50 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
> +        using Component component = new();
why not on line 2124?

2023-07-14 16:50 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
> +        using ComponentDesigner designer = new();
why not for mocksite below?

2023-07-14 16:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
>          var properties = new Dictionary<string, PropertyDescriptor>
same here.

2023-07-14 16:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerVerbCollectionTests.cs
> +        var collection = new DesignerVerbCollection(value);
here.

2023-07-14 16:51 UTC, dreddy-work commented on src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerVerbCollectionTests.cs
> +        var collection = new DesignerVerbCollection();
in this file

2023-07-14 16:52 UTC, dreddy-work requested changes
we are enforcing pattern for object initialization with type declaration on left side of expression wherever possible.

i.e :` Object object=  new();`

2023-07-17 19:12 UTC, Tanya-Solyanik approved these changes
Thank you for applying this pattern to the code base!

2023-07-17 20:49 UTC, dreddy-work approved these changes

2023-07-17 20:49 UTC, merged