Add PrintDialogDesigner.cs
dotnet/winforms pull request #9579
Opened 2023-07-27 07:57 UTC by LeafShi1

Related to #4908 

## Proposed changes

- Port MonthCalendarDesigner to runtime 

## Customer Impact

- PrintDialogDesigner can be designed in runtime

## Regression? 

- No

## Risk

- Minimal

## Screenshots 

### Before
The default value of the property "UseEXDialog" is false
![image](https://github.com/dotnet/winforms/assets/132890443/8c4d18e3-3f29-441b-b862-a69d704649ce)

### After
The default value of the property "UseEXDialog" is true
![image](https://github.com/dotnet/winforms/assets/132890443/6b151d71-9f4d-410a-992f-5a1b0e9338f9)

## Test methodology 

- Manually (added PrintDialogDesigner to DemoConsole test app)

## Test environment(s) 

- .Net 8.0.100-rc.1.23375.11
- Windows 10 Enterprise 22H2

2023-07-27 12:21 UTC, SimonZhao888 approved these changes

2023-07-28 00:07 UTC, elachlan commented
@LeafShi1 this PR contains commits which aren't related to the issue. When you rebase, you might need to "Skip" some of the commits from the previous "base". I ran into a similar issue.

2023-07-28 00:20 UTC, dreddy-work requested changes
Please rebase.

2023-07-28 08:47 UTC, LeafShi1 commented
> * .Net 8.0.100-rc.1.23375.11
> * Windows 10 Enterprise 22H2



> @LeafShi1 this PR contains commits which aren't related to the issue. When you rebase, you might need to "Skip" some of the commits from the previous "base". I ran into a similar issue.

Thanks for your reminder! After I rebase, it still included the extra commit, I submitted a new [PR](https://github.com/dotnet/winforms/pull/9595) and deleted this one.

2023-07-28 08:47 UTC, closed without merging