Implement: Mark some properties and methods as `readonly`
dotnet/winforms pull request #9641
Opened 2023-08-02 22:07 UTC by hamarb123

Fixes #9618

## Proposed changes

<details>
<summary>
API proposal
</summary>

```diff
namespace System.Drawing
{
-	public struct CharacterRange
+	public struct CharacterRange : IEquatable<CharacterRange>
	{
-		public int First { get; set; }
+		public int First { readonly get; set; }
-		public int Length { get; set; }
+		public int Length { readonly get; set; }
-		public override bool Equals(object? obj);
+		public override readonly bool Equals(object? obj);
+		public readonly bool Equals(CharacterRange other);
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
	}
}

namespace System.Windows.Forms
{
-	public struct BindingMemberInfo
+	public readonly struct BindingMemberInfo
	{
	}

-	public struct ImeModeConversion
+	public readonly struct ImeModeConversion
	{
	}

	public struct LinkArea
	{
-		public int Start { get; set; }
+		public int Start { readonly get; set; }
-		public int Length { get; set; }
+		public int Length { readonly get; set; }
-		public bool IsEmpty { get; }
+		public bool IsEmpty { readonly get; }
-		public override bool Equals(object? o);
+		public override readonly bool Equals(object? o);
-		public bool Equals(LinkArea other);
+		public readonly bool Equals(LinkArea other);
-		public override string ToString();
+		public override readonly string ToString();
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
	}

	public struct Message
	{
-		public int Msg { get; set; }
+		public int Msg { readonly get; set; }
-		public IntPtr WParam { get; set; }
+		public IntPtr WParam { readonly get; set; }
-		public IntPtr LParam { get; set; }
+		public IntPtr LParam { readonly get; set; }
-		public IntPtr Result { get; set; }
+		public IntPtr Result { readonly get; set; }
-		public object? GetLParam(Type cls);
+		public readonly object? GetLParam(Type cls);
-		public override bool Equals(object? o);
+		public override readonly bool Equals(object? o);
-		public bool Equals(Message other);
+		public readonly bool Equals(Message other);
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
-		public override string ToString();
+		public override readonly string ToString();
	}

	public struct Padding
	{
-		public int All { get; set; }
+		public int All { readonly get; set; }
-		public int Bottom { get; set; }
+		public int Bottom { readonly get; set; }
-		public int Left { get; set; }
+		public int Left { readonly get; set; }
-		public int Right { get; set; }
+		public int Right { readonly get; set; }
-		public int Top { get; set; }
+		public int Top { readonly get; set; }
-		public int Horizontal { get; }
+		public int Horizontal { readonly get; }
-		public int Vertical { get; }
+		public int Vertical { readonly get; }
-		public Size Size { get; }
+		public Size Size { readonly get; }
-		public override bool Equals(object? other);
+		public override readonly bool Equals(object? other);
-		public bool Equals(Padding other);
+		public readonly bool Equals(Padding other);
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
-		public override string ToString();
+		public override readonly string ToString();
	}

	public struct TableLayoutPanelCellPosition
	{
-		public override bool Equals(object? other);
+		public override readonly bool Equals(object? other);
-		public bool Equals(TableLayoutPanelCellPosition other);
+		public readonly bool Equals(TableLayoutPanelCellPosition other);
-		public override string ToString();
+		public override readonly string ToString();
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
	}
}
```

</details>

## Customer Impact

- Allows avoiding defensive copies

## Regression? 

- No

## Risk

- No

2023-08-02 22:59 UTC, elachlan commented
@hamarb123 There are some build/test failures. It might be because of the build targets for .net framework. 
```
API compatibility errors between 'lib/netstandard2.0/System.Drawing.Common.dll' (left) and 'lib/net462/System.Drawing.Common.dll'
Type 'System.Drawing.CharacterRange' does not implement interface 'System.IEquatable<System.Drawing.CharacterRange>' on lib/net462/System.Drawing.Common.dll but it does on lib/netstandard2.0/System.Drawing.Common.dll
API breaking changes found. If those are intentional, the APICompat suppression file can be updated by rebuilding with '/p:ApiCompatGenerateSuppressionFile=true'
API compatibility errors between 'lib/netstandard2.0/System.Drawing.Common.dll' (left) and 'lib/net462/System.Drawing.Common.dll' (right):
```

2023-08-02 23:10 UTC, hamarb123 commented
It seems like it got removed in whenever https://github.com/dotnet/winforms/blob/9cf5b5ac66b48fa77fe9af28e2957ff73f5bbadf/src/System.Drawing.Common/ref/System.Drawing.Common.netcoreapp.cs got removed. Would that mean that there were other APIs removed on accident?

2023-08-02 23:20 UTC, hamarb123 commented
Nevermind, I must have tested it on `net6.0` last time.

2023-08-03 08:22 UTC, hamarb123 commented
I ran my analyser on the projects and discovered some defensive copies on internal types. I have made them no longer cause a defensive copy.
There is 1 more in `ToolStripManager.ModalMenuFilter.cs` that I didn't fix (`IsChildOrSameWindow`), it's on the parameters. Let me know if I should fix it too - I didn't fix it, because there's not an obvious solution other than just using `Unsafe.AsRef`.

2023-08-03 21:39 UTC, JeremyKuhne requested changes
Added a few comments

2023-08-03 21:39 UTC, JeremyKuhne commented on src/System.Drawing.Common/src/NotSupported.cs
> +        private int _first;
This should stay `_dummyPrimitive`.

2023-08-03 21:39 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
> +    internal readonly IME_CONVERSION_MODE setBits;
Better to change these to autoprops `internal IME_CONVERSION_MODE SetBits { get; init; }`

Then you can do the following:

``` C#
s_imeModeConversionBits.Add(
    ImeMode.Hiragana,
    new()
    {
        SetBits = IME_CONVERSION_MODE.IME_CMODE_FULLSHAPE | IME_CONVERSION_MODE.IME_CMODE_NATIVE,
        ClearBits = IME_CONVERSION_MODE.IME_CMODE_KATAKANA
    });
```

2023-08-03 21:39 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
>      private static Dictionary<ImeMode, ImeModeConversion>? imeModeConversionBits;
Since we're touching this, can you please update this to `s_imeModeConversionBits`

2023-08-03 21:39 UTC, JeremyKuhne commented on src/System.Drawing.Common/src/System/Drawing/Interop/LOGFONT.cs
> +    internal fixed char _lfFaceName[LF_FACESIZE];
This shouldn't be necessary.

2023-08-03 22:01 UTC, hamarb123 commented on src/System.Drawing.Common/src/System/Drawing/Font.cs
> +        bool gdiVerticalFont = logFont._lfFaceName[0] == '@';
@JeremyKuhne `_lfFaceName` is made `internal` so it can be used here. `lfFaceName` causes a defensive copy as it's a `Span`, not a `ReadOnlySpan`, and therefore cannot be exposed as a readonly member - this means it would copy the whole struct just to check if one `char` is `@`.

2023-08-03 22:13 UTC, hamarb123 commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
> +            if (s_imeModeConversionBits is null)
Also, is this code even multi-threading safe? It doesn't seem like it is to me. If it was built up in a local and then stored using a volatile write it would be multi-threading safe, I can implement that if you want.

2023-08-03 22:13 UTC, hamarb123 commented on src/System.Drawing.Common/src/System/Drawing/Interop/LOGFONT.cs
> +    internal fixed char _lfFaceName[LF_FACESIZE];
Replied to this [here](https://github.com/dotnet/winforms/pull/9641#discussion_r1283761197).

2023-08-03 22:33 UTC, JeremyKuhne commented on src/System.Drawing.Common/src/System/Drawing/Font.cs
> +        bool gdiVerticalFont = logFont._lfFaceName[0] == '@';
You're right, thought it would be smart enough to know it didn't have to. We might be exposed elsewhere with this pattern.

2023-08-03 22:35 UTC, hamarb123 commented on src/System.Drawing.Common/src/System/Drawing/Font.cs
> +        bool gdiVerticalFont = logFont._lfFaceName[0] == '@';
I fixed all of the violations my analyser picked up on except the one I mentioned in a comment. It's probably not written perfectly, so maybe it missed something, but I think it can find most things.

2023-08-03 22:42 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
> +            if (s_imeModeConversionBits is null)
Yeah, it's probably better to build this in a local. Using `=> s_imeModeConversionBits ??= new(7) {{...}};` should do the right thing I think.

2023-08-03 23:27 UTC, elachlan commented on src/System.Drawing.Common/src/System/Drawing/Font.cs
> +        bool gdiVerticalFont = logFont._lfFaceName[0] == '@';
Maybe we ping the Roslyn team and see if they can improve the IL around this pattern?

2023-08-03 23:31 UTC, hamarb123 commented on src/System.Drawing.Common/src/System/Drawing/Font.cs
> +        bool gdiVerticalFont = logFont._lfFaceName[0] == '@';
It's not something that can be solved currently, it has to make a defensive copy to be correct. @jaredpar and some other people including me were talking about a new language feature which could achieve something like this yesterday on the C# discord, but it gets into the realm of generics over readonly to solve this particular case (without just adding a ROS property also obviously).

2023-08-03 23:38 UTC, hamarb123 commented on src/System.Drawing.Common/src/System/Drawing/Font.cs
> +        bool gdiVerticalFont = logFont._lfFaceName[0] == '@';
The reason it's an invalid operation to not make a defensive copy is because if I marked `lfFaceName` as readonly, then you could do `logFont.lfFaceName[0] = '@';` on a `ref readonly`. The C# compiler doesn't have special knowledge of `Span`, nor should it (for all it knows, `this[int]` could do a bunch of mutation on its ref - this would not break the span's `readonly` contract as nothing in the span itself changes). This would be something which should be solved in a more general way imo, which is difficult without things like `[MatchedMutabilityRef]` (what we were discussing yesterday) and generics over mutability.

2023-08-04 00:01 UTC, elachlan commented on src/System.Drawing.Common/src/System/Drawing/Font.cs
> +        bool gdiVerticalFont = logFont._lfFaceName[0] == '@';
Instead of exposing _lfFaceName would it make sense to add an internal `readonly bool IsGdiVerticalFont =>_lfFaceName[0] == '@';` to `LOGFONT`? or am I way off?

2023-08-04 20:01 UTC, JeremyKuhne approved these changes
Looks good!

2023-08-04 20:02 UTC, merged