Make sure the Narrator won't announce the password text
dotnet/winforms pull request #9733
Opened 2023-08-16 08:13 UTC by SimonZhao888

Fixes #7852

## Proposed changes

- Implemented HasKeyboardFocusPropertyId for TextBoxBaseAccessibleObject.
- Update the Text property in the TextBoxBaseUiaTextProvider to ensure that passwords are not displayed in plaintext in Insights.

## Customer Impact

- When enable UseSystemPasswordChar or PasswordChar properties in TextBox/MaskedTextBox, Narrator won't announce the text.
- Passwords are not displayed as plaintext in Insights.

## Regression? 

- No

## Risk

- Low

## Screenshots 

### Before

When typing text in TextBox/MaskedTextBox with UseSystemPasswordChar or PasswordChar, Narrator announce text to "Hidden", but when focus on TextBox/MaskedTextBox or specific text, it will announce as specific text.
![image](https://github.com/dotnet/winforms/assets/133954995/704b82a7-d6d2-4e65-b639-163177d5ba16)

### After

When enable UseSystemPasswordChar or PasswordChar properties in TextBox/MaskedTextBox, Narrator won't announce the text, and passwords are not displayed as plaintext in Insights.
![PassWord](https://github.com/dotnet/winforms/assets/133954995/f7b68f72-380e-4323-8ea0-d1ff1f5f6ab6)

![image](https://github.com/dotnet/winforms/assets/133954995/3fe9ffb0-02a2-4deb-a29f-3e4d891f2717)

## Test methodology 

- Manual

## Accessibility testing  

 

## Test environment(s) 

-  8.0.0-rc.1.23381.3
- Windows 11 22H2

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9733)

2023-08-17 03:14 UTC, Epica3055 requested changes

2023-08-17 03:14 UTC, Epica3055 commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
> +        private string _passwordString => Owner is not null ? new string('*', Owner.Text.Length) : string.Empty;
Maybe `new string(PasswordChar Owner.Text.Length)` is more appropriate. 

This is what I observed from WPF.
![image](https://github.com/dotnet/winforms/assets/135201996/42afaf30-87f1-429e-bd64-e00525cd73dc)

![image](https://github.com/dotnet/winforms/assets/135201996/61d95392-a9e5-479d-80cb-a805c075894e)

2023-08-23 08:33 UTC, Epica3055 commented on src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
> +        if (IsHandleCreated && IsAccessibilityObjectCreated && ContainsNavigationKeyCode(e.KeyCode) && _passwordChar == 0 && !UseSystemPasswordChar)
Maybe you could extract `_passwordChar == 0 && !UseSystemPasswordChar` into a method, since it is used in multiple places.

2023-08-25 19:08 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
> +        private string _passwordString => Owner is not null ? new string(Owner is TextBox ? ((TextBox)Owner).PasswordChar : ((MaskedTextBox)Owner).PasswordChar, Owner.Text.Length) : string.Empty;
nit: for readability
```suggestion
        private string _passwordString => Owner is not null 
        ? new string(Owner is TextBox textBox ? textBox.PasswordChar : ((MaskedTextBox)Owner).PasswordChar, Owner.Text.Length)
        : string.Empty;
```

2023-08-28 05:21 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
> +    private bool _isUseSystemPasswordChar => _passwordChar == 0 && !UseSystemPasswordChar;
Shouldn't this be `IsUseSystemPasswordChar` since it is a property? Same question for `PasswordString`.

2023-08-28 06:36 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
> +        if (IsHandleCreated && IsAccessibilityObjectCreated && ContainsNavigationKeyCode(e.KeyCode) && _passwordChar == 0 && !UseSystemPasswordChar)
Done.

2023-08-28 06:36 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
> +        private string _passwordString => Owner is not null ? new string(Owner is TextBox ? ((TextBox)Owner).PasswordChar : ((MaskedTextBox)Owner).PasswordChar, Owner.Text.Length) : string.Empty;
Done.

2023-08-28 06:36 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
> +    private bool _isUseSystemPasswordChar => _passwordChar == 0 && !UseSystemPasswordChar;
Done.

2023-08-28 16:34 UTC, lonitra approved these changes
LGTM 👍

2023-08-28 22:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
> +                : string.Empty;
Consider indenting each branch
```suggestion
                ? Owner.PasswordProtect 
                    ? PasswordString
                    : Owner.Text
                : string.Empty;
```

2023-08-28 22:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
> +                ? new string(Owner is TextBox ? ((TextBox)Owner).PasswordChar
```suggestion
                ? new string(Owner is TextBox textBox 
                    ? (textBox.PasswordChar
```

2023-08-28 22:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
>              AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.Text_TextChangedEventId);
Do you really have to avoid raising such events? Now that the UIA Text provider has the textual representation of password characters, wouldn't it announce "dot dot dot"

2023-08-28 22:57 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
> +    private bool IsUseSystemPasswordChar => _passwordChar == 0 && !UseSystemPasswordChar;
As is the name of this property seems to be incorrect, should it be `DontHidePassword`?

2023-08-29 02:39 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
> +                : string.Empty;
Done.

2023-08-29 02:44 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
>              AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.Text_TextChangedEventId);
Yes, we don't need to avoid this event, do we also not need to avoid the TextSelectionChangedEventId event?

2023-08-30 01:49 UTC, Epica3055 approved these changes

2023-08-31 18:10 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
>              AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.Text_TextChangedEventId);
Yes, I think that none of the events are needed anymore

2023-08-31 18:22 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +            }
```suggestion
            if (this.TryGetOwnerAs(out owner))
            {
                if (propertyID == UIA.IsPasswordPropertyId)
                {
                    return owner.PasswordProtect;
                }

                if (propertyID == UIA.HasKeyboardFocusPropertyId)
                {
                    return owner.Focused;
                }
            }
```

2023-08-31 18:22 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
>              AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.Text_TextChangedEventId);
Please retest all these event after you re-enable them.

2023-09-01 01:43 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
>              AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.Text_TextChangedEventId);
Yes, I had retest all these event, and update the test result.

2023-09-01 01:43 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
> +            }
Done.

2023-09-01 02:04 UTC, LeafShi1 approved these changes

2023-09-01 17:31 UTC, lonitra approved these changes

2023-09-01 20:43 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
>              AccessibilityObject.RaiseAutomationEvent(UiaCore.UIA.Text_TextChangedEventId);
Great test! I think we don't have any password tests in our WinformsControlsTest app (please double-check that). Could you please add your test form to our test app? Do it in the next PR , or open a tracking work item to not forget about it. But I think this is a very quick PR given that you already have the code. 
I'm re-activating this comment for visibility.

2023-09-01 20:50 UTC, Tanya-Solyanik approved these changes
@SimonZhao888  - this change looks good, but please add your test form to our WinformsControlsApp or open a follow up work item on it.

2023-09-01 20:51 UTC, merged