Issue 7263 fix label edit show in correct position
dotnet/winforms pull request #9782
Opened 2023-08-25 04:46 UTC by SimonZhao888

Fixes #7263

## Proposed changes

- Add a variable to the ListView to record the ListViewSubItem to which the Label Edit belongs.
- Modify the code related to Label Edit in ListView.
- Adjust the ListViewSubItemAccessibleObject and ListViewLabelEditAccessibleObject classes so that the Label Edit will be displayed under the ListViewSubItem node when constructing the tree structure.

## Customer Impact

- The control of LabelEdit will show under ListViewSubItem .
- 

## Regression? 

- Yes 

## Risk

- Minimal

## Screenshots 

### Before
Label Edit is at the same level as the List item and is displayed under the root node of the List.
![image](https://github.com/dotnet/winforms/assets/133954995/619a5fa0-7f23-4687-a299-fc0e381e8cbf)

### After
Label Edit displays under the edited cell.
![image](https://github.com/dotnet/winforms/assets/133954995/8b878aec-9a77-4fff-a3ee-a5786fc64d9f)

## Test methodology 

- Manual (using inspect )

## Accessibility testing  

 

## Test environment(s) 

- 8.0.100-preview.7.23376.3

2023-08-25 06:50 UTC, Epica3055 requested changes

2023-08-25 06:50 UTC, Epica3055 commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditAccessibleObject.cs
> +            UiaCore.NavigateDirection.PreviousSibling => Parent?.GetChildIndex(this) is int childId and >= 0 ? Parent.GetChild(childId - 1) : null,
These two lines are not necessary, since labelEdit is inside the subItem. And it has no siblings.

2023-08-25 06:50 UTC, Epica3055 commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                            ListViewSubItem lvsi = lvi.SubItems[j];
avoid abbreviation  `lvsi `

2023-08-25 06:52 UTC, Epica3055 commented
Is it possible  to write UnitTest?

2023-08-28 02:15 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditAccessibleObject.cs
> +            UiaCore.NavigateDirection.PreviousSibling => Parent?.GetChildIndex(this) is int childId and >= 0 ? Parent.GetChild(childId - 1) : null,
Done.

2023-08-28 02:15 UTC, SimonZhao888 commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                            ListViewSubItem lvsi = lvi.SubItems[j];
Done.

2023-08-28 02:16 UTC, SimonZhao888 commented
> Is it possible to write UnitTest?

The relevant test cases have been modified.

2023-08-29 20:28 UTC, Tanya-Solyanik approved these changes
Looks good!

2023-08-29 20:29 UTC, Tanya-Solyanik commented
@Epica3055  - please re-review and unblock the merge if all your comments are addressed

2023-08-30 01:20 UTC, Epica3055 approved these changes

2023-08-30 01:26 UTC, merged