Convert AxHost to use Pointers
dotnet/winforms pull request #9847
Opened 2023-09-05 22:10 UTC by lonitra

- Convert applicable `T.Interface` fields in `AxHost` to type `AgileComPointer<T>`
- Update methods in `AxHost.State` to use pointers instead of `T.Interface`

2023-09-05 22:56 UTC, JeremyKuhne requested changes
Added a few comments. We probably should convert `STG_*` into a `StorageType` enum and add something for `PropertyBag`.

2023-09-05 22:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
>              if (_instance is IPersistStreamInit.Interface init)
All of these `is` checks need to go away. You need to query for the desired interface pointer.

2023-09-05 22:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +    private AgileComPointer<IPersistPropertyBag>? _iPersistPropBag;
It would be better to get rid of the fields completely and just use the STG_ flags to identify which one we should re-query for when we need it.

2023-09-05 22:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +    private void DepersistFromIStream(IStream* istream)
These methods should probably be moved inline.

2023-09-05 22:56 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
>              if (_instance is IPersistPropertyBag.Interface persistPropertyBag)
It still strikes me as super odd that this case will throw (that it doesn't return). Also that we don't have a `STG_PROPERTYBAG`.

2023-09-05 23:05 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
>              if (_instance is IPersistPropertyBag.Interface persistPropertyBag)
Same here 🤔 had to re-check Framework to make sure it didn't accidentally get removed, but seems like it was always like this..

2023-09-06 23:33 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.StorageType.cs
> +    [Flags]
Don't use the `[Flags]` if multiple won't be set at the same time. If these are actually flags you'll want to make sure the values don't overlap.

In either case, `Unknown` should be `0`.

2023-09-06 23:51 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +            if (ComHelpers.SupportsInterface<IPersistStreamInit>(_instance))
It is better to query here and not use `SupportsInterface` as otherwise you're querying twice. Probably worth adding a comment to the helper method to remind on this case.

2023-09-06 23:52 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +            if (ComHelpers.SupportsInterface<IPersistStorage>(_instance))
Same comment as above, try to get the ComScope directly

2023-09-06 23:52 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +            if (ComHelpers.SupportsInterface<IPersistPropertyBag>(_instance))
Same comment as above, try to get the ComScope directly

2023-09-06 23:53 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +                if (ComHelpers.SupportsInterface<IPersistStreamInit>(_instance))
Same comment as above, try to get the ComScope directly

2023-09-06 23:54 UTC, JeremyKuhne requested changes
A few more comments

2023-09-07 00:11 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.StorageType.cs
> +    [Flags]
We have a public constructor in AxHost.State that takes an int for storage type https://github.com/dotnet/winforms/blob/01d50d1f4479d150234190718abfdda885e4293f/src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs#L63
Originally `Unknown = -1` so is it fine to make the change that `Unknown = 0` even though we have this public constructor?

2023-09-07 00:21 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.StorageType.cs
> +    [Flags]
Ugh. It's safer to have `default` (i.e. `0`) be unknown. I'd just translate here by `+1`.

2023-09-07 02:04 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
> +                if (ComHelpers.SupportsInterface<IPersistStreamInit>(_instance))
This one still needs updated.

2023-09-07 17:18 UTC, JeremyKuhne approved these changes
Looks good!

2023-09-07 17:34 UTC, merged