Migrate `InitCommonControls` to CsWin32
dotnet/winforms pull request #9875
Opened 2023-09-09 04:21 UTC by elachlan

Related to: #7445

2023-09-10 22:33 UTC, elachlan commented
@lonitra I might need a hand with some of the code. I think I have made a pretty good start.

2023-09-11 04:12 UTC, elachlan commented
I think I fixed the issues I had. The final compile issue is waiting on:
https://github.com/microsoft/win32metadata/pull/1703

2023-09-11 17:18 UTC, lonitra reviewed
Nice work on this! Things LRGTM, just a few comments :)

2023-09-11 17:18 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
>  public partial class TreeNode : MarshalByRefObject, ICloneable, ISerializable
I believe we may want to implement `IHandle<HTREEITEM>` to this similar to our implementation of `IHandle<HWND>` in Control.cs to follow existing patterns.
https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L13591-L13593

Perhaps also add a `HTREEITEMInternal` property for when we just want a handle without forcing creation and then using that instead of casting everywhere.

2023-09-11 21:47 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/PCWSTR.cs
> +    public string? ToStringAndCoTaskMemFree()
I needed `IsNull`, I figured the rest would be useful. But I don't think I got around to using it.

2023-09-12 09:24 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> +                                int C = (int)(nmcd->clrText & mask);
renamed to `color`

2023-09-12 16:58 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +    internal HTREEITEM HTREEITEMInternal => (HTREEITEM)_handle;
Digging through the code again, I don't see anywhere we are doing P/Invoke calls that explicitly need HTREEITEM, so I am not sure that implementing `IHandle<HTREEITEM>` is totally necessary. Let's remove the implementation for now and we can easily add it if we see it is needed later, my apologies for that. 🙏 
We should still add some internal properties for getting the HTREEITEM though, so this is close to what we want, but as it is right now, this would be changing the behavior since we are no longer calling `Handle`, which would force handle creation if it hasn't already been created. I think we should have something like the following:
```suggestion
    internal HTREEITEM HTREEITEM => (HTREEITEM)Handle
    internal HTREEITEM HTREEITEMInternal => (HTREEITEM)_handle;
```

then anywhere that was originally calling `Handle` can be replaced with `HTREEITEM` (I believe I also saw a few in TreeNodeTest.cs) while anywhere that was originally calling `_handle` can be replaced with `HTREEITEMInternal`. You may be able to actually get rid of `_handle` entirely and just have `HTREEITEMInternal` serve as an auto prop for it, but I am not entirely sure by just looking 🤔

2023-09-12 17:04 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/PCWSTR.cs
> +    public string? ToStringAndCoTaskMemFree()
Gotcha, let's remove the methods that aren't in use and we can add it later as needed

2023-09-12 23:30 UTC, elachlan commented
I ran the test locally 1000 times and didn't have a failure. So someone might want to look at it?

2023-09-13 16:59 UTC, lonitra commented
We are getting the following exception. Didn't have time to dig further on what was going on
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.

Stack trace
   at Windows.Win32.UI.Controls.LVITEMW.UpdateText(ReadOnlySpan`1 text) in /_/src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/LVITEMW.cs:line 25
   at System.Windows.Forms.Tests.InteropTests.LVITEMWTests.UpdateText_should_limit_input_text_to_cchTextMax_less_1_text_longer(String originalText, Int32 maxLength, String newText, String expected) in /_/src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/LVITEMWTests.cs:line 34
   at InvokeStub_LVITEMWTests.UpdateText_should_limit_input_text_to_cchTextMax_less_1_text_longer(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   ```

2023-09-13 22:55 UTC, lonitra commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/LVITEMW.cs
> +        Span<char> targetSpan = pszText.AsSpan()[..cchTextMax];
Okay so I'm not sure why the CI points to the failing test as being `LVITEMWTests.UpdateText_should_limit_input_text_to_cchTextMax_less_1_text_longer` , but I found that the real test that is failing/aborting is [this one](https://github.com/dotnet/winforms/blob/f59965e707d1a68bf381f59a721a97ff0c6fbcd2/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs#L4374). I think we will need to revert this back to what this originally was to resolve this. I am seeing that in the test `pszText` points to an empty string so this change results in `OutOfRangeException`.
```suggestion
        Span<char> targetSpan = new(pszText, cchTextMax);
```

2023-09-14 00:04 UTC, elachlan commented
@lonitra CI is passing!

2023-09-14 16:03 UTC, lonitra approved these changes
Awesome! Thank you for your work here! :)

2023-09-14 18:01 UTC, JeremyKuhne commented on src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
> +    internal HTREEITEM HTREEITEMInternal;
This is a little confusing. Better choice is to put this next to the `Handle` property and make them properties I think.

``` C#
public IntPtr Handle => (nint)HTREEITEM;
internal HTREEITEM HTREEITEMInternal { get; private set; }
internal HTREEITEM HTREEITEM
{
    get
    {
        if (HTREEITEMInternal // ...
    }
}
```

2023-09-14 18:07 UTC, JeremyKuhne commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/LVITEMW.cs
> +    /// Set the new text. The text length is limited by <see cref="cchTextMax"/>.
Can you please indent XML tag content by 1 space?

2023-09-14 18:09 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewInsertionMarkTests.cs
> +            var insertMark = new LVINSERTMARK
When you change code it would be good to flip to target type new to match our desired pattern

```suggestion
            LVINSERTMARK insertMark = new()
```

2023-09-14 18:11 UTC, JeremyKuhne requested changes
Great work! I only have a few minor comments.

2023-09-14 18:11 UTC, JeremyKuhne commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewInsertionMarkTests.cs
> +            var insertMark = new LVINSERTMARK
Don't sweat changing everything in the file, just what you touch.

2023-09-14 22:27 UTC, elachlan commented on src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewInsertionMarkTests.cs
> +            var insertMark = new LVINSERTMARK
It was a small file, so I did everything.

2023-09-19 17:59 UTC, JeremyKuhne approved these changes
Great work! Thanks!

2023-09-19 17:59 UTC, merged