Enable nullability in ElementProxy
dotnet/winforms pull request #9887
Opened 2023-09-12 04:52 UTC by gpetrou

## Proposed changes

- Enable nullability in ElementProxy.

2023-09-12 10:08 UTC, LeafShi1 requested changes

2023-09-12 10:08 UTC, LeafShi1 commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.ElementProxy.cs
> +                AnchorStyles anchorStyles = LayoutUtils.GetUnifiedAnchor(Element!);
Element may be null here, so if use !, it will cause exception. 
same issue in below code.

2023-09-12 10:18 UTC, halgab commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
> +                if (control.LayoutEngine is DefaultLayout)
nit: You could have a single if clause without introducing a new variable:

`if (element.Container is Control { LayoutEngine: DefaultLayout })`

2023-09-12 16:38 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.ElementProxy.cs
> +                AnchorStyles anchorStyles = LayoutUtils.GetUnifiedAnchor(Element!);
The usage of this class is a bit weird. We set `Element` before using it as seen in https://github.com/dotnet/winforms/blob/b3ce60f0b2af034ce8326b7e3da81c2bef88d2b9/src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs#L204 So, not sure if it is worth adding lots of null checks in this file.

2023-09-12 16:38 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
> +                if (control.LayoutEngine is DefaultLayout)
As mentioned before, I am not a big fan of this syntax. But if the maintainers want, I could do the change.

2023-10-04 22:38 UTC, dreddy-work requested changes

2023-10-04 22:38 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.ElementProxy.cs
> +            return _element!.GetPreferredSize(proposedSize);
nit: expressional body

2023-10-06 17:00 UTC, dreddy-work approved these changes

2023-10-06 17:00 UTC, merged