Migrate TaskDialogIndirect to CsWin32
dotnet/winforms pull request #9900
Opened 2023-09-13 00:46 UTC by elachlan

Fixes #9825

We are waiting on some Win32MetaData changes to bubble into CsWin32 before I can complete this.

2023-09-14 00:47 UTC, elachlan commented
@JeremyKuhne any suggestions on the BOOL.ToString() clash? Should we rename our implementation, or should we fix it upstream in CsWin32?

2023-10-05 17:59 UTC, JeremyKuhne commented
@elachlan I'd just remove ours and have everything do `((bool)value).ToString()`.

2023-10-09 09:22 UTC, elachlan commented
@AArnott could you please bump the CsWin32 Win32Metadata SDK version?

2023-10-09 18:49 UTC, AArnott commented
@elachlan I have a local change where I started the work to update the metadata, but some breaking changes in the metadata made it more challenging than usual, so I set it aside. I'll pick it back up and see what I can do.

2023-10-09 19:29 UTC, AArnott commented
Metadata update coming: https://github.com/microsoft/CsWin32/pull/1063

2023-10-23 23:35 UTC, elachlan commented
@lonitra can you please have a look?

2023-10-23 23:36 UTC, elachlan commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/ToolInfoWrapper.cs
> +            uId = (nuint)(IntPtr)handle.Handle,
Did we want an explicit operator on `HWND` to `nuint`?

2023-10-24 02:14 UTC, lonitra commented
I will take a look this week

2023-10-24 18:01 UTC, lonitra reviewed
Great work here! My main concern here is making the .Anonymous more readable

2023-10-25 01:14 UTC, elachlan commented on src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGIconUnionTests.cs
> +        Assert.Equal(4, sizeof(TASKDIALOGCONFIG._Anonymous1_e__Union));
I have been trying to solve this in the win32metadata. But haven't had traction yet. I think when discriminated unions are added to c# it solves this.

Ill do the work around for now.

2023-10-26 00:16 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
To match the `pfcallback` signature of the `TASKDIALOGCONFIG` struct. Which changed when we switched to using the cswin32 generated struct. See line 1330.

2023-10-26 00:19 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
It might make sense to update win32metadata based on the doc.
https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nc-commctrl-pftaskdialogcallback

2023-10-26 00:40 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +#pragma warning restore CS3016 // Arrays as attribute arguments is not CLS-compliant
We shouldn't need a suppression here because its a private method:
https://github.com/dotnet/roslyn/issues/68526

2023-10-27 01:02 UTC, elachlan commented on src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGIconUnionTests.cs
> +        Assert.Equal(4, sizeof(TASKDIALOGCONFIG._Anonymous1_e__Union));
This specific code is using `sizeof` on a type. The field for this type is `TASKDIALOGCONFIG.Anonymous1`. Are you asking me to add a `MainIcon` and `FooterIcon` ref properties to make the union properties more obvious?

2023-10-27 17:19 UTC, lonitra commented on src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGIconUnionTests.cs
> +        Assert.Equal(4, sizeof(TASKDIALOGCONFIG._Anonymous1_e__Union));
Yep, in this PR we seem to be doing a lot with what was originally named `MainIcon`/`FooterIcon` but due to way win32metadata defines things, this changes to be less readable with the `Anonymous` names. So wondering if we could do something similar to what we did in `VARIANT.data` to maintain readability here.

2023-10-27 17:32 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
Based on docs that does seem to make sense. Could you open an issue there and perhaps also add a comment here to update this when that issue is resolved and cswin32 has consumed the fix? I think we'd probably get an error anyways once we update cswin32 version that has that fix, but it doesn't hurt.

2023-10-31 22:39 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
Issue raised at: https://github.com/microsoft/win32metadata/issues/1733

I am unsure if it will be accepted. But I think we are now allowing enums to group the constants and then adding an attribute to point to the enum for cswin32 to consume. This is instead of using the enum directly, to avoid issues.

2023-10-31 22:40 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +#pragma warning restore CS3016 // Arrays as attribute arguments is not CLS-compliant
Is there anyway you could bump that issue? based on my reading, the team doesn't want to change it because the current behavior matches the reference design. But based on the reading of the standard it sounds like its a bug.

2023-11-14 04:45 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
https://github.com/microsoft/win32metadata/issues/810
This issue removed the enum for "notification message constants". Since messages can include values that aren't one of the constants its unlikely to be changed back to an enum.

2023-11-14 08:36 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
Ok, we managed to get the issue resolved and now I guess we wait for a cswin32 update?

2023-11-14 17:46 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +#pragma warning restore CS3016 // Arrays as attribute arguments is not CLS-compliant
Apologies, missed this. I'll see what I can do, but let's not block on this. Let's leave a comment with the suppression highlighting that it should be removed when issue resolves.

2023-11-14 17:46 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
Pinged for a cswin32 update. Will circle back to this to review soon

2023-11-15 17:42 UTC, lonitra commented on src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGTests.cs
> +        Assert.Equal(24, (byte*)&sut.Anonymous1 - addr);                // 4, union { HICON; PCWSTR; }
Can the .Anonymous in this file be changed to use sut.mainIcon/sut.footerIcon now?

2023-11-15 17:42 UTC, lonitra commented on eng/Versions.props
> +    <MicrosoftWindowsCsWin32PackageVersion>0.3.50-beta</MicrosoftWindowsCsWin32PackageVersion>
There should be a new cswin32 drop today that would allow you to update to 0.3.51-beta

2023-11-15 17:42 UTC, lonitra commented on src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGIconUnionTests.cs
> +        TASKDIALOGCONFIG._Anonymous1_e__Union sut = new TASKDIALOGCONFIG._Anonymous1_e__Union();
```suggestion
        TASKDIALOGCONFIG._Anonymous1_e__Union icon = new();
```
ditto below

2023-11-15 22:58 UTC, elachlan commented on src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGTests.cs
> +        Assert.Equal(24, (byte*)&sut.Anonymous1 - addr);                // 4, union { HICON; PCWSTR; }
I get this error if I try: `CS0212 You can only take the address of an unfixed expression inside of a fixed statement initializer`

2023-11-15 23:07 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
![image](https://github.com/dotnet/winforms/assets/2433737/0278b823-e2a6-4ccd-8c0a-966f4d3b656e)
Based on the commit history, we need to use v57 and cswin32 is using v56.

2023-11-17 01:10 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
Oops 🤦‍♀️ v57 is not released yet so we would need to wait on that.. Once that is released we can follow steps in [cswin32 readme to use newer metadata](https://github.com/microsoft/CsWin32#newer-metadata) to avoid waiting for cswin32 to consume. Alternatively if we'd rather not wait we can leave as is and create tracking issue to bump and update this code when v57 is released.

2023-11-17 01:10 UTC, lonitra commented on src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGTests.cs
> +        Assert.Equal(24, (byte*)&sut.Anonymous1 - addr);                // 4, union { HICON; PCWSTR; }
I believe you can resolve this if you do
``` c#
fixed(void* mainIconPtr = &sut.mainIcon)
fixed(void* footerIconPtr = &sut.footerIcon)
{
    // ....
    Assert.Equal(24, (byte*)mainIconPtr  - addr); 
    // ...etc.
}
```

2023-11-21 01:08 UTC, elachlan commented on src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
> +        uint msg,
Tracking issue is good:
https://github.com/dotnet/winforms/issues/10348

2023-11-21 05:31 UTC, lonitra approved these changes
👍

2023-11-22 23:17 UTC, Tanya-Solyanik reviewed
@elachlan  - seem like https://github.com/dotnet/winforms/pull/9900/files#r1374857146 is not addressed, are we waiting on something to implement it?

2023-11-22 23:17 UTC, Tanya-Solyanik commented on src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/ToolInfoWrapper.cs
> +            where T : IHandle<HWND>
Please indent by 4 spaces or keep everything in a single line

2023-11-22 23:17 UTC, Tanya-Solyanik commented on src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/TaskDialog/TaskDialogButton.cs
> +        GetStandardButtonFlagForResult(_standardButtonResult!.Value);
When the line starts with the `?` or `:`, logical flow is more prominent, and condition fits into 120 char line limit, so there is no reason to put it on a new line, could you please reformat this ternary operator ?
 
 ```   
internal TASKDIALOG_COMMON_BUTTON_FLAGS GetStandardButtonFlag() => !IsStandardButton
    ? throw new InvalidOperationException() 
    : GetStandardButtonFlagForResult(_standardButtonResult!.Value);
```

2023-11-22 23:32 UTC, elachlan commented on src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGIconUnionTests.cs
> +        Assert.Equal(4, sizeof(TASKDIALOGCONFIG._Anonymous1_e__Union));
@Tanya-Solyanik I think we have address what is needed here. We can't rename the struct generated by CsWin32, just the properties.

2023-11-28 19:27 UTC, Tanya-Solyanik approved these changes

2023-11-28 21:25 UTC, lonitra requested changes

2023-11-28 21:25 UTC, lonitra commented on src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGIconUnionTests.cs
> +using TASKDIALOGCONFIG_MainIcon = Windows.Win32.UI.Controls.TASKDIALOGCONFIG._Anonymous1_e__Union;
😮 Cool change! I hadn't thought about doing this to make it more readable. Could you do the same for the other files that are referencing `TASKDIALOGCONFIG._Anonymous1_e__Union` and `TASKDIALOGCONFIG._Anonymous2_e__Union`. Then we can get this merged :)

2023-11-28 21:25 UTC, lonitra commented on src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/TaskDialog/TaskDialogButton.cs
> +        GetStandardButtonFlagForResult(_standardButtonResult!.Value);
nit: `? :` should be at start of line
```suggestion
    internal TASKDIALOG_COMMON_BUTTON_FLAGS GetStandardButtonFlag() => !IsStandardButton 
        ? throw new InvalidOperationException()
        : GetStandardButtonFlagForResult(_standardButtonResult!.Value);
```

2023-11-28 22:02 UTC, lonitra approved these changes

2023-11-28 22:24 UTC, merged

2023-11-28 23:03 UTC, elachlan commented
Thank you for pushing through with the reviews!