Enable nullability in OleDragDropHandler and SelectionUIHandler
dotnet/winforms pull request #9938
Opened 2023-09-18 10:19 UTC by halgab

## Proposed changes

- Enable nullability in `OleDragDropHandler`
- Enable nullability in `SelectionUIHandler`
- Remove unused fields and fix field names

2023-09-19 20:59 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
> +                List<object> topComponents = new(_components.Length);
Do we need to assign size here? are you sure the size of the `topComponents ` is always same as `_components` ? but not less.

2023-09-19 21:04 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs
> +                        if (o is IComponent component && !Destination.IsDropOk(component))
nice!.

2023-09-19 21:25 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
> +                List<object> topComponents = new(_components.Length);
We could very well write `List<object> topComponents = new();`. It's just that we know `topComponents` cannot be bigger than `_components.Length`, so setting that as the capacity to avoid list resizes seemed like a good idea to me.
That being said, I find this code a bit odd. I don't understand why we need to copy `objects` into `_components` before filtering it and why we can't do both at the same time...

2023-09-19 21:40 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
> +                return (object[])_components!.Clone();
I don't like that I had to write `_components!`. Either some null checks are redundant on line 68 or the check on line 71 should be move to the outer scope I think

2023-09-28 21:56 UTC, dreddy-work commented
@halgab, can you get this to a review state by fixing buil issues?

2023-09-29 00:17 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
> +                return (object[])_components!.Clone();
`Deserialize(null, false);` on line 70 ensure `_components` is not null.  So check on line 71 and the block of code is unnecessary. 

I think it was intended to be moved out  and make line 77  as
 
```CS

return _components is null ? Array.Empty<object>() : (object[])_components!.Clone()

```

This change will be breaking.  @halgab, can you see if we have unit tests that are running through this code path?

2023-09-29 07:25 UTC, halgab commented
Sorry, I forgot to check the CI after my last rebase...

2023-09-29 07:40 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
> +                return (object[])_components!.Clone();
I don't see any test coverage, but I've looked manually. I don't have any tool that allows me to measure code coverage, so I can't be sure. Should I make the change anyway? Or maybe in a separate PR?

2023-10-03 18:39 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
> +                return (object[])_components!.Clone();
@halgab , i lost context here around `breaking change` comment. Did you revert or rebase code here?

2023-10-03 19:54 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
> +                return (object[])_components!.Clone();
So far I haven't done anything. I checked the code wasn't covered (not 100% sure though), and I was asking if I should go ahead and make the (breaking) change anyway considering the current code looks broken

2023-10-04 22:34 UTC, dreddy-work requested changes

2023-10-04 22:34 UTC, dreddy-work commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
> +                return (object[])_components!.Clone();
sure. Go ahead. If you still have to end up using `!`, i would go with debug assert.

2023-10-08 12:25 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
> +                return (object[])_components!.Clone();
done. Sorry for the delay, this fell off my radar

2023-10-26 16:44 UTC, lonitra approved these changes
LGTM

2023-10-27 18:54 UTC, merged