Enable nullability in remaining DataGridView members
dotnet/winforms pull request #9982
Opened 2023-09-23 05:18 UTC by gpetrou

## Proposed changes

- Enable nullability in remaining DataGridView members.

2023-09-26 16:52 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
> +            return _topLeftHeaderCell!;
We are setting this in the setter below, so I don't think we need any checks.

2023-09-28 17:48 UTC, dreddy-work requested changes

2023-09-28 17:48 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
> +    internal ToolTip? KeyboardToolTip
When does this return null?

2023-09-28 17:48 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
> +                _rowHeadersDefaultCellStyle!.AddScope(this, DataGridViewCellStyleScopes.RowHeaders);
I would change this to `_rowHeadersDefaultCellStyle?.AddScope(this, DataGridViewCellStyleScopes.RowHeaders);`

2023-09-28 18:20 UTC, gpetrou commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
> +    internal ToolTip? KeyboardToolTip
`TryGetObject` will return nullable value. Without `?` there is a warning.

2023-09-28 21:38 UTC, dreddy-work commented on src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
> +    internal ToolTip? KeyboardToolTip
hmm. return value in those cases should be `false`.  However, Its unfortunate that its not honoring that convention in `GetObject` call made by this API.

2023-09-28 21:38 UTC, dreddy-work approved these changes

2023-09-29 18:28 UTC, merged