Enhance nullable annotations in DataGridViewColumnCollectionDialog and replace Hashtables
dotnet/winforms pull request #9991
Opened 2023-09-26 11:23 UTC by halgab

## Proposed changes

- Enhance nullable annotations in `DataGridViewColumnCollectionDialog`, removing almost all in the process `!`
- Replace `Hastable`s with `Dictionary`s and a `HashSet` (contributes to #8143)

2023-09-28 21:56 UTC, dreddy-work commented
@JeremyKuhne as FYI.

2023-09-29 21:25 UTC, JeremyKuhne requested changes
Thanks for cleaning this up! You can get further with this by always keeping a collection instance in the fields.

2023-09-29 21:25 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
> +    private HashSet<DataGridViewColumn>? _userAddedColumns;
This is another one where I think we can just put in an empty `HashSet<>` to get rid of the other `!`s. You can `Clear()` and `EnsureCapacity()` when setting new data.

2023-09-29 21:25 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
> +    private Dictionary<DataGridViewColumn, string?>? _columnsNames;
This can be changed to always have a `Dictionary`. `.Clear()` and `.EnsureCapacity()` can be used to initialize the data. There are few places where we are checking for null, but those were introduced in the other annotation work.

2023-10-04 23:31 UTC, JeremyKuhne approved these changes
Nice work, thanks!

2023-10-04 23:32 UTC, merged