Enable nullability in ByteViewer and remove allocations when drawing
dotnet/winforms pull request #9998
Opened 2023-09-27 08:48 UTC by halgab

## Proposed changes

- Enable nullability in `ByteViewer`
- Cleanup code and remove most allocations when drawing

2023-09-28 18:50 UTC, JeremyKuhne requested changes
Nice! I've added a few comments.

2023-09-28 18:50 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        using BufferScope<char> charsBufferScope = new(maxLength);
Another improvement you can do here is to provide a stack allocated space. Something like this provides a nice safe alternative:

```suggestion
        using BufferScope<char> charsBuffer = new(stackalloc char[256], maxLength);
```

You also don't need to assign it to a local. The pattern is to just use it and let the implicit cast operator get out the span.

2023-09-28 18:50 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        byte[] buf = new byte[length + 1];
This should all be collapsed to `SetBytes(File.ReadAllBytes(path));`

2023-09-28 18:50 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        using FileStream currentFile = new FileStream(path, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None);
We prefer to use target typed new:

```suggestion
        using FileStream currentFile = new(path, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None);
```

2023-09-28 18:50 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +            text.Replace('\0', (char)0x0B);
```suggestion
            text.Replace('\0', '\v');
```

2023-09-28 18:50 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        text.AsSpan(0, size).Replace('\0', (char)0x0B);
```suggestion
        text.AsSpan(0, size).Replace('\0', `\v`);
```

2023-09-28 18:50 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        text.AsSpan(0, size).Replace('\0', (char)0x0B);
Consider replacing `text` with `BufferScope<char>`.

2023-09-29 07:53 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        using BufferScope<char> charsBufferScope = new(maxLength);
I assigned it to a local because I wanted to avoid having the implicit cast happening over and over inside the loop, but I can remove it if you think that's overkill

2023-09-29 08:02 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        byte[] buf = new byte[length + 1];
Will do. Just 2 things on this:

1. I don't get why `byte[]` wasn't set to `new byte[length]`
2. We are going to fix a potential bug making the change, as `currentFile.Read` can very well read less than `length`, and we never check for that scenario. I've seen this same problem at several other places in the repo btw

2023-09-29 19:14 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        byte[] buf = new byte[length + 1];
This change makes tests fail:

 ```
    System.ComponentModel.Design.Tests.ByteViewerTests.ByteViewer_SetFile_InvokeWithBytes_Success [FAIL]
      Assert.Equal() Failure
                           (pos 3)
      Expected: [1, 2, 3, 0]
      Actual:   [1, 2, 3]
      Stack Trace:
        /_/src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ByteViewerTests.cs(896,0): at System.ComponentModel.Design.Tests.ByteViewerTests.ByteViewer_SetFile_InvokeWithBytes_Success()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
    System.ComponentModel.Design.Tests.ByteViewerTests.ByteViewer_SetFile_InvokeNoBytes_Success [FAIL]
      Assert.Equal() Failure
                           (pos 3)
      Expected: [1, 2, 3, 0]
      Actual:   [1, 2, 3]
      Stack Trace:
        /_/src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ByteViewerTests.cs(885,0): at System.ComponentModel.Design.Tests.ByteViewerTests.ByteViewer_SetFile_InvokeNoBytes_Success()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

I guess my first point above was relevant. Should I roll this back @JeremyKuhne?

2023-09-29 21:05 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        byte[] buf = new byte[length + 1];
@halgab Sorry, didn't notice that it was putting a trailing `0` into the buffer. That seems wrong, but there is a lot of wrong here. Opening and saving the same file name is going to add a byte that doesn't exist. That said, saving to the file doesn't reset the length of the file, which doesn't seem sensible (that you could end up with data after the buffer).

I'm inclined to fix this and change the test. It makes the file usage symmetrical, and it won't change the behavior of `BinaryEditor`.

2023-09-29 21:08 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        using BufferScope<char> charsBufferScope = new(maxLength);
Yeah, it isn't going to measure in the scope of the cost of rendering here, so I'd go with simpler.

2023-09-29 21:09 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +    private byte[]? _dataBuf;
This one I think is pretty important.

2023-09-29 21:13 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +    private byte[]? _dataBuf;
Yes, I was preparing it for after my first batch of changes. But if I make the change, the behaviour of `SaveToFile` will change slightly. Today it's a no-op when we haven't called `SetBytes`. Now it's going to dump an empty file. It's minor, but that's still a change

2023-09-29 22:41 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +            int offset = (startLine + line) * _columnCount;
`startLine` shouldn't be used here

2023-09-29 22:44 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +            if (offset + _columnCount > _dataBuf.Length)
Consider using the ternary operator.

2023-09-30 06:54 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +            int offset = (startLine + line) * _columnCount;
Oops... Fixed

2023-09-30 11:53 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +    private byte[]? _dataBuf;
The change stated above makes the tests fail. Should I try to preserve existing behaviour this time, or should I go ahead and fix the tests?

2023-10-11 20:05 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +    private byte[]? _dataBuf;
@JeremyKuhne the current behaviour of method `GetBytes` is to return `null` if `SetBytes` has never been called. Would you like me to maintain this behaviour or should the method return an empty array from now on?

2023-10-31 21:54 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +    private byte[]? _dataBuf;
I went ahead and change the test, assuming we're happy we the behaviour change.

2023-11-14 21:53 UTC, halgab commented
This one is still waiting on team @lonitra, @JeremyKuhne

2023-11-14 21:58 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        _edit.Text = string.Create(_dataBuf.Length / 2 + 1, _dataBuf, static (text, dataBuf) =>
```suggestion
        _edit.Text = string.Create(_dataBuf.Length / sizeof(char) + 1, _dataBuf, static (text, dataBuf) =>
```

2023-11-14 22:01 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        _edit.Text = string.Create(_dataBuf.Length / 2 + 1, _dataBuf, static (text, dataBuf) =>
@halgab just this one nit left

2023-11-14 22:02 UTC, halgab commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        _edit.Text = string.Create(_dataBuf.Length / 2 + 1, _dataBuf, static (text, dataBuf) =>
Thanks! So you're fine with https://github.com/dotnet/winforms/pull/9998#discussion_r1355711840?

2023-11-14 22:11 UTC, JeremyKuhne commented on src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
> +        _edit.Text = string.Create(_dataBuf.Length / 2 + 1, _dataBuf, static (text, dataBuf) =>
Yes. Sorry about the delay on this, I was out for most of October.

2023-11-14 22:11 UTC, JeremyKuhne approved these changes

2023-11-14 22:21 UTC, merged